- public/static/js/directives/directives.patch.js
- public/static/partials/patch_diff.html
https://jira.mongodb.org/browse/EVG-1109
> EVG-1109 clearly indicate results of new tasks/tests in patch status panel

- service/templates/task_queues.html
Jira issue: https://jira.mongodb.org/browse/EVG-1129
> EVG-1129 task queue page grid system issues

- service/middleware.go
Jira issue: https://jira.mongodb.org/browse/EVG-1160
> EVG-1160 current project persists

- proto/agent.go
This is covered by TestAgentTestSuite/TestAbort and TestAgentTestSuite/TestEndTaskResponse, which were failing in master, but I hadn't looked at them yet. Instead I noticed that successful tasks ran EndTask successfully in staging, but failed tasks got 400s back.
> EVG-1917 Fix end task response

- proto/background.go
- proto/background_test.go
- proto/task.go
- rest/client/client.go
- rest/client/interface.go
- rest/client/mock.go
- rest/client/request.go
- rest/client/sender.go
(I don't think this actually works because it'll get bumped for
heartbeats, which means there'll be no timeouts, but it's a start)
> EVG-1919: update idle timeout if there's been command updates

- globals.go
- proto/agent.go
- proto/background.go
- rest/client/request.go
- Stop running the task if the agent receives a 409
- Do not run post for 409s and aborts
> EVG-2069 Improve 409/abort handling

- cli/patch.go
Patch build:
https://evergreen.mongodb.com/version/59ba98dde3c3315da2001cf9
> EVG-2076 Link to version with --finalize is given

- public/static/js/admin.js
- public/static/js/directives/directives.eventlogs.js
- public/static/partials/adminevent.html
- service/admin.go
- service/templates/admin.html
- service/templates/event_log.html
> EVG-2000 show admin event log in UI

- agent/agent.go
- agent/agent_command_test.go
- agent/agent_test.go
- agent/background.go
- agent/background_test.go
- agent/command.go
- agent/global.go
- agent/task.go
- command/git.go
- command/shell.go
- subprocess/local_command.go
The blocking case is probably here: https://github.com/evergreen-ci/evergreen/blob/master/agent/command.go#L69
> EVG-2130: idle timeout updating non-blocking

- agent/agent.go
- agent/agent_integration_test.go
- agent/agent_test.go
- agent/background.go
- agent/command.go
- agent/directory.go
- agent/task.go
- cli/agent.go
- cli/runner.go
- cli/service.go
- command/results_native.go
- command/s3_copy.go
- config.go
- notify/notify.go
- util/info_collectors.go
- util/recover.go
- util/recover_test.go
patch: https://evergreen.mongodb.com/version/59d162b42a60ed080a00ae45
> EVG-2134: add panic handlers to agent code

- command/results_xunit.go
- command/results_xunit_test.go
I went with a low-risk approach since the previous 2 attempts to refactor the code broke things
> EVG-2141 add system-out and system-err to junit logs

- agent/agent.go
- agent/status.go
- service/api_patch_test.go
patch: https://evergreen.mongodb.com/version/59df9ba92a60ed504b004e82
> EVG-2208 fix tests that start an HTTP server

- rest/client/interface.go
- rest/client/mock.go
- rest/client/rest.go
- rest/route/keys_routes.go
- rest/usage.rst
I forgot to add client method for this change. Need feedback on interface.
> EVG-1727 Add rest client method for POST /keys

- cli/migration.go
- migrations/anser_setup.go
- migrations/testresults.go
- migrations/testresults_test.go
- Fix bug in setting up application environment
- Use local unordered queue, as ordered queue was serial
- Fix old_tasks collection migration bug
> EVG-2052 Improvements to test results migration

- rest/client/rest.go
I was erroneously wrapping a nil error (which is nil) and not returning the error message from the rest api's response body.
> EVG-1726 EVG-1727 EVG-1728 Fix error handling in REST Client's Key handling functions

- migrations/anser.go
- migrations/anser_test.go
- migrations/testresults.go
- migrations/testresults_test.go
(sorry for the pull-request/ticket noise, this builds on top of #417)
> EVG-2333: cleanup migration generator registry, refactor simple migration

- model/build/task_cache.go
- model/build/task_cache_test.go
- model/lifecycle.go
- model/lifecycle_test.go
- model/patch/patch.go
- model/patch_lifecycle.go
- model/project.go
- model/project_parser.go
- model/project_parser_test.go
- model/task/db.go
- model/task/results.go
- model/task/task.go
- model/task_lifecycle.go
- model/task_lifecycle_test.go
- public/static/js/patch_new.js
- public/static/js/task_admin.js
- repotracker/repotracker.go
- service/api_patch.go
- service/build.go
- service/patch.go
- service/task.go
- service/templates/task.html
You only need to look at the commit marked EVG-2061, the rest have been approved already. I also submitted a patch build + deployed the same patch to staging with a display task in the ubuntu1604 distro: https://evergreen-staging.corp.mongodb.com/version/5a21d65697b1d374d000000a
> EVG-2061 implement restarting display tasks, misc display task fixes

- self-tests.yml
patch: https://evergreen-staging.corp.mongodb.com/task/mci_race_detector_display_lint_patch_c38e87c34b161f1b37ffe2ad865826e3340d97bb_5a29c5d89dbe32434d000004_17_12_07_22_51_17
> EVG-2367 split up lint task

- cli/cli_integration_test.go
Patch build: https://evergreen.mongodb.com/version/5a2b0becc9ec444dab003334
> EVG-2256 Fix Broken tests 

- plugin/builtin/perf/perf.go
- service/plugins/perf/static/js/perf.js
- service/plugins/perf/static/js/trend_chart.js
- service/plugins/perf/static/task_perf_data.html
- service/plugins/perf/templates/task_perf_data.html
> EVG-2376 Perf plugin: Trend chart improvements

- plugin/builtin/buildbaron/tickets.go
- plugin/builtin/buildbaron/tickets_test.go
here's a ticket I filed from it: https://jira.mongodb.org/browse/EVG-2420
> EVG-2418 support display tasks in build baron plugin

- service/templates/task.html
> EVG-2436 limit size of task page panel

- service/task.go
- service/templates/task.html
> EVG-2557 display more data about execution tasks on display task page

- public/static/plugins/perf/js/perf.js
- public/static/plugins/perf/js/trend_chart.js
* Persistent colors
* Per-thread level mean lines
> Persistent thread level colors; per-thread mean lines

- public/static/plugins/perf/js/perf.js
- public/static/plugins/perf/js/trend_chart.js
> EVG-2540: Fix 'Invalid date' bug; Improve color persistence

- public/static/plugins/perf/js/perf.test.js
- public/static/plugins/perf/js/trend_chart.js
> EVG-2574: Proper 'maxonly' mode implementation

- model/lifecycle.go
- model/lifecycle_test.go
- model/matrix_smoke_test.go
- model/patch_dependencies.go
- model/patch_lifecycle_test.go
- model/project.go
- model/project_matrix.go
- model/project_matrix_test.go
- model/project_parser.go
- model/project_parser_test.go
- model/project_selector.go
- model/project_test.go
- model/testutil/api.go
- plugin/builtin/perfdash/perf_dashboard.go
- plugin/builtin/perfdash/perf_dashboard_test.go
- repotracker/repotracker_test.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
- service/api.go
- service/stats.go
- service/task_history.go
- validator/project_validator.go
- validator/project_validator_test.go
Half the code changes are renaming things so you can ignore anything that's not model/project_*.go
> EVG-2485 create task group model

- public/static/plugins/perf/js/trend_chart.js
- service/templates/task_perf_data.html
> EVG-2589 (fix) Perf graphs: Show current commit with a dot

- public/static/plugins/perf/js/trend_chart.js
> EVG-2621 (feat) Perf. trendchart: Don't show MAX label in graphs

- agent/task.go
- model/project.go
- model/project_test.go
- model/task_config.go
- model/testutil/api.go
- rest/client/methods.go
I've already tested this in staging.
> EVG-2545 Expansions for Patches created by Github Pull Requests

- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- service/templates/perfdiscovery.html
> EVG-2657 (feat) Perfdiscovery basic page layout

- hostinit/setup.go
- hostinit/setup_test.go
- model/distro/distro.go
- model/host/db.go
- model/host/host.go
- monitor/host_monitoring.go
- service/api_task.go
> EVG-2639: retry host setup

- rest/client/rest.go
- rest/model/admin.go
- rest/model/admin_test.go
- rest/route/admin_routes.go
I made everything nullable because I want the requester to be able to omit fields they don't want changed
> EVG-2663 fixup rest models for config

- model/task_history.go
This uses the same amount of memory as before but returns much more quickly so we're not holding on to it (also should be easier on the db)
before:
[test.model] 2018/02/13 14:54:52 [p=info]: elapsed time for aggregation test history query on task names: 9.428189583s
[test.model] 2018/02/13 14:54:52 [p=info]: elapsed time for non-aggregation test history query on task names: 8.499267969s
[test.model] 2018/02/13 14:55:09 [p=info]: elapsed time for aggregation test history query on test names: 9.350376492s
[test.model] 2018/02/13 14:55:09 [p=info]: elapsed time for non-aggregation test history query on test names: 8.487023192s
after:
[test.model] 2018/02/13 11:37:25 [p=info]: elapsed time for aggregation test history query on task names: 11.509020889s
[test.model] 2018/02/13 11:37:25 …
> EVG-2778 make test history endpoint more efficient

- model/task_json.go
- plugin/builtin/taskdata/json.go
- plugin/builtin/taskdata/ui.go
- public/static/app/common/ApiTaskdata.js
- public/static/app/common/ApiUtil.js
- public/static/app/common/constants.js
- public/static/app/perfdiscovery/PerfDiscoveryService.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- service/templates/perfdiscovery.html
> EVG-2696: (feat) Baseline (tag) drop down functionality

- public/static/app/common/ApiUtil.test.js
- public/static/app/perfdiscovery/PerfDiscoveryService.js
- public/static/app/perfdiscovery/PerfDiscoveryService.test.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/js/tests/conf/karma.conf.js
> EVG-2763: Add unit tests to performance discovery

- config.go
- config_registry.go
- config_test.go
- model/event/admin_event.go
- model/event/admin_event_test.go
- model/event/event.go
- rest/data/admin.go
- rest/data/admin_test.go
- rest/model/admin.go
I'm not finished yet, but wanted to get some eyes on this to see if the model makes sense
> EVG-2660 event models for config

- agent/agent.go
- agent/agent_test.go
- agent/task.go
- model/lifecycle.go
- model/project.go
- model/project_test.go
- scheduler/scheduler.go
- scheduler/scheduler_test.go
- service/api_task.go
- validator/project_validator.go
- use task group name passed from API to agent
- handle task groups in task scheduling
- set task group in next task endpoint
- add task groups to validator
> EVG-2784 Fix bugs found in manual task group testing

- public/static/app/common/EvgGridUtil.test.js
- public/static/app/common/EvgUiGridUtil.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/app/perfdiscovery/multiselectGridHeader.js
- public/static/app/perfdiscovery/templates.js
- service/templates/perfdiscovery.html
>  EVG-2834: (feat) Perf. Discovery - filtering

- public/static/app/common/ApiV1.js
- public/static/app/common/constants.js
- public/static/app/perfdiscovery/PerfDiscoveryService.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- service/rest_routes.go
- service/waterfall.go
The code quality is lower than usually, because of rush. I promise to fix all issues later.
> EVG-2762 (feat) Perf. discovery - load versions with test data only

- config.go
- environment.go
- util/copy.go
- util/copy_test.go
Let the records show that I hate everything about this pr
> EVG-2852 hacky workaround for getting plugin config in db

- config.go
- public/static/js/services/rest.js
- rest/client/rest.go
- rest/route/admin_routes.go
- rest/route/service.go
> EVG-2920 add route to preserve CLI compatibility, fix route problem with new CLI

- model/event/event.go
- model/event/event_test.go
TLDR: i was unmarshalling only part of the struct in MarshalJSON. But that whole function wasn't even needed in the first place.
> EVG-2859 fix JSON unmarshalling

- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/js/filters/filters.common.js
> EVG-2930 (feat) Perf. discovery - ratio as percentage

- public/static/app/common/EvgUiGridUtil.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
> EVG-2931 (fix) Perf. discovery - numeric sort

- model/task/task.go
> EVG-2836 display task with some finished + some that will never finish = finished

- public/static/js/task.js
I auto indented this file so the diff is a mess, but I added the code from lines 594-607 and 641-644
> EVG-2715 collapse scheduled events in task event log to most recent

- service/templates/menu.html
> EVG-2959 (feat) Perf. discovery - create menu item

- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/app/perfdiscovery/perfDiscoveryRatio.js
- public/static/app/perfdiscovery/templates.js
- service/templates/perfdiscovery.html
> EVG-2961 (feat) Perf. Discovery - ratio color coding

- plugin/builtin/buildbaron/build_baron.go
- public/static/plugins/buildbaron/js/task_build_baron.js
- public/static/plugins/buildbaron/partials/task_build_baron.html
> EVG-1400 show created tickets in build baron plugin

- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/app/perfdiscovery/perfdiscovery.css
- service/templates/perfdiscovery.html
> EVG-2963 (feat) Perf. discovery - spinner; no data text

- public/static/app/perfdiscovery/PerfDiscoveryService.js
- public/static/app/perfdiscovery/PerfDiscoveryService.test.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
> EVG-2974 (feat) Perf.discovery - avg to baseline ratio

- public/static/app/perfdiscovery/PerfDiscoveryService.js
- public/static/app/perfdiscovery/PerfDiscoveryService.test.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/app/perfdiscovery/microTrendChart.js
- public/static/app/perfdiscovery/perfdiscovery.css
- service/templates/perfdiscovery.html
> EVG-2727 (feat) Perf. Discovery - trend chart

- cloud/static.go
- model/event/host_event.go
- model/event/host_event_test.go
- model/host/host.go
- model/host/host_test.go
- public/static/partials/hostevent.html
- rest/data/host.go
- service/api_spawn.go
- service/api_task.go
- service/host.go
- taskrunner/error_handler.go
- taskrunner/error_handler_test.go
- taskrunner/host_gateway.go
> EVG-2917 log extra data when host status changes

- public/static/app/perfdiscovery/perfdiscovery.css
- service/templates/perfdiscovery.html
> EVG-3000 (fix) Perf. Discovery - dropdown labels; styles;

- public/static/plugins/perf/js/perf.js
- service/templates/task_perf_data.html
> EVG-2990: consuming pointer pointer events when invisible stops text selection

- public/static/app/common/constants.js
- public/static/app/perfdiscovery/PerfDiscoveryService.js
- public/static/app/perfdiscovery/PerfDiscoveryService.test.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/app/perfdiscovery/templates.js
> EVG-3003 (feat) Perf. Discovery - build and task links

- agent/agent.go
- agent/agent_test.go
- agent/logging.go
- operations/service_deploy_smoke_utils.go
- Run teardown_group in case where agent does not get a next task
- Flush logger in teardown_group
- Test setup_task, teardown_task, setup_group, teardown_group in smoke test
> EVG-3005 Fix task group teardown_group

- repotracker/repotracker.go
- repotracker/repotracker_test.go
- repotracker/wrappers.go
- units/repotracker.go
I haven't written/modified any tests yet, looking for advice on how to proceed in this case!
> EVG-2945: Respect NumNewRepoRevisionsToFetch

- public/static/plugins/perf/js/perf.js
- service/templates/task_perf_data.html
> EVG-2962 (feat) Perf. discovery - navigate rom perf results page

- public/static/plugins/perf/js/perf.js
- public/static/plugins/perf/js/trend_chart.js
> EVG-2603 (fix) Perf trend chart - align ops/s labels; fix $scope bug

- public/static/plugins/perf/js/trend_chart.js
There are few minor code duplications, I know. I'll fix them later. There are some parts that should be refactored also.
> EVG-2652 (feat) Perf - toggle thread levels

- public/static/app/common/styles/ui-grid.css
- public/static/app/perfdiscovery/perfdiscovery.css
- public/static/app/signal-processing/SignalProcessingCtrl.js
- service/templates/perfdiscovery.html
- service/templates/signal_processing.html
Query will be modified in terms of "filtering" ticket. This displays 100 random items.
> EVG-3439 (feat) - Signal Processing page - grid

- model/trigger/task_test.go
for some reason, I used the wrong function in this test. This PR fixes it. task-regression is fine.
> EVG-3084 fix tests in task-regression trigger

- config_containerpools.go
- config_test.go
- model/distro/distro.go
- model/distro/distro_test.go
- public/static/js/admin.js
- rest/route/admin_route_test.go
- rest/route/admin_routes.go
- service/templates/admin.html
- testdata/smoke_config.yml
- testutil/config.go
Added the UI element under the now renamed "providers" category. Made it as its own row because it's going to be pretty long. Also included validation so that the user cannot save a container pool configuration with duplicate IDs.
> EVG-3521 create container pool UI element for admin page

- public/static/app/common/Stitch.js
- public/static/app/signal-processing/SignalProcessingCtrl.js
* Basic filtering
* Basic sorting
* Hidden columns
> EVG-3441 (feat) Signal Processing - Basic sorting/filtering

- cloud/ec2_price.go
this is mostly to run the patch build.
> EVG-3346: cache latest spot calls

- public/static/js/task.js
- public/static/plugins/perf/js/perf.js
- service/templates/task.html
- service/templates/task_perf_data.html
> EVG-3377 (feat) Perf - make trendchart order consistent w/ test order

- units/host_stats.go
The existing job runs every 20 mins btw
> EVG-3225 log hosts spawned by tasks

- public/static/js/distros.js
- service/distros.go
- service/templates/distros.html
looks like this when the ID in "Pool ID" exists:
> EVG-3524: display container pool mapping information in UI

- scripts/indexes.js
`parent_id` and `container_pool_settings.id`
> EVG-3668: add new host index fields

- public/static/app/common/MDBQueryAdaptor.js
- public/static/app/common/MDBQueryAdaptor.test.js
- public/static/app/signal-processing/SignalProcessingCtrl.js
- service/templates/signal_processing.html
> EVG-3540 (feat) Signal processing - comprehensive filtering

- model/host/db.go
- model/host/host.go
- rest/client/methods.go
- rest/data/host.go
- rest/data/host_test.go
- rest/data/interface.go
- rest/route/admin_events.go
- rest/route/admin_test.go
- rest/route/build_routes.go
- rest/route/build_task.go
- rest/route/host.go
- rest/route/host_spawn.go
- rest/route/host_test.go
- rest/route/patch_routes.go
- rest/route/patch_test.go
- rest/route/service.go
- rest/route/service_test.go
- rest/route/version_routes.go
- rest/route/version_test.go
- scheduler/utilization_based_host_allocator_test.go
this also removes some random print statements I found.
> EVG-3671: port host routes to new framework

- rest/model/distro.go
- rest/model/distro_test.go
- rest/route/distro_routes.go
- scripts/smoke_test.yml
I'm not sure if this is should be SuperUser required or not.
> EVG-3209 Expose provider settings in distros REST API

- model/task_lifecycle.go
only logging for lobster/mci since i don't want to inundate splunk.
> EVG-3455 Add additional temporary logging

- environment.go
- mock/environment.go
- operations/service_deploy_migration.go
- units/stats_amboy.go
this is a more limited un-revert of an earlier commit to give us better logging
> EVG-3632: log queue state aggregations 

- public/static/js/build.js
- public/static/js/notifications.js
- public/static/js/version.js
- public/static/partials/subscription_modal.html
- service/templates/notifications.html
This redoes the notifications list to be a little clearer. I forgot to take a picture of the Clear All Subscriptions button, but there is a big red button just below the list to delete the subscriptions
> EVG-3493 Add a way to delete all existing subscriptions on notifications page

- public/static/js/task.js
- service/templates/task.html
You'll want to hide whitespace changes when looking at the diff
> EVG-3683 better resize behavior for task drawer

- alerts/email_test.go
- alerts/jira.go
- alerts/jira_test.go
- service/ui_plugin_build_baron_tickets.go
- trigger/task_jira.go
- trigger/task_jira_test.go
Also added in testing for ProjectRepo alongside existing ProjectOwner
> EVG-3717 URL-escape BFG task links

- public/static/plugins/perf/js/trend_chart.js
> EVG-3515 (feat) Trendchart - Change point statistics

- public/static/app/common/MDBQueryAdaptor.js
- public/static/app/common/MDBQueryAdaptor.test.js
- public/static/app/common/templates.js
- public/static/app/signal-processing/SignalProcessingCtrl.js
- public/static/js/mci_module.js
- service/templates/base_angular.html
- service/templates/signal_processing.html
> EVG-5176 (feat) PerfBB - Group CPs by revision

- model/host/db.go
- scheduler/scheduler.go
- scheduler/scheduler_integration_test.go
- scheduler/wrapper.go
- units/provisioning_create_host.go
the scheduler has checks against this, but this protects hostinit from scheduler bugs
> EVG-5194: do not provision more hosts in maxHost conditions

- public/static/app/common/templates.js
- public/static/app/signal-processing/SignalProcessingCtrl.js
- public/static/app/signal-processing/hazardLevelCell.js
- public/static/app/signal-processing/templates.js
- public/static/js/mci_module.js
- service/templates/signal_processing.html
> EVG-5188 (feat) PerfBB - Hazard Level column

- model/event/subscriptions.go
- public/static/js/projects.js
- public/static/js/subscriptions.js
- trigger/task.go
- trigger/task_test.go
The UI is inconsistent with the other regexes, but I feel like it's fine
> EVG-3646 test regression notifications by name

- rest/route/metrics.go
found a change that missed an earlier commit
> EVG-5172: fix lingering time parsing case

- repotracker/repotracker.go
1. Always send build break notifications if the user has subscribed
2. Only notify admins build break notifications have been enabled in the project
3. Notify admins if we failed to fetch a user's subscriber data.
> EVG-3612 Always send evergreen build failures from a commit to the committer

- model/task_lifecycle.go
- public/static/js/build.js
I couldn't figure out what the actual cause of the issue was, but this fixes the problem for display tasks and works around the problem in the UI in general
> EVG-3636 UI task statuses fixes for build page

- public/static/app/perf-bb/SignalProcessingCtrl.js
- public/static/app/perf-bb/hazardLevelCell.js
- public/static/app/perf-bb/templates.js
> EVG-5177 (feat) Aggregation for grouped items

- public/static/plugins/perf/js/perf.js
- public/static/plugins/perf/js/trend_chart.js
- service/templates/task_perf_data.html
> EVG-3310 (feat) Trendchart - annotate data with BFs

- public/static/app/common/tagInput.html
- public/static/app/common/tagInput.js
- public/static/js/projects.js
- service/templates/base_angular.html
- service/templates/projects.html
> EVG-3443 (feat) Project admin - allow tags for GH aliases

- public/static/app/perf-bb/hazardLevelCell.js
> EVG-5401 (fix) PerfBB - inverted hazard valiues

- globals.go
- model/build/db.go
- model/build_variant_history.go
- model/event/subscriptions.go
- model/grid/grid.go
- model/project_ref.go
- model/task/db.go
- model/task/task.go
- model/task_history.go
- model/version/db.go
- model/version/version.go
- model/version_history.go
- repotracker/repotracker.go
- repotracker/repotracker_test.go
- rest/model/build.go
- scheduler/setup_funcs.go
- scheduler/task_prioritizer.go
- scheduler/task_priority_cmp.go
- service/grid.go
- service/models.go
- service/rest_task_history.go
- service/rest_version.go
- service/stats.go
- service/task_history.go
- service/timeline.go
- trigger/task.go
- trigger/version.go
- units/crons.go
most of this is actually "handle new requester types in existing queries"
> EVG-5369 create data models for triggers

- public/static/app/common/tagInput.html
- public/static/app/common/tagInput.js
- public/static/js/projects.js
- service/templates/base_angular.html
- service/templates/projects.html
This is replacement for this PR https://github.com/evergreen-ci/evergreen/pull/1659
Already **reviewed**
Recommendation: should be deployed together with https://github.com/evergreen-ci/evergreen/pull/1684
>  EVG-3443 (feat) Project admin - allow tags for GH aliases 

- public/static/js/host.js
- service/templates/host.html
> EVG-5284 (feat) Host - Hyperlink for 'started by: task'

- rest/model/version.go
- rest/route/version_test.go
> EVG-3640 (feat) retrieve project via /api/rest/v2/versions/

- public/static/app/common/EvgUtil.js
- public/static/app/common/EvgUtil.test.js
- public/static/app/common/templates.js
- public/static/app/perf-bb/SignalProcessingCtrl.js
- public/static/js/tests/conf/karma.conf.js
- service/templates/base_angular.html
> EVG-5403 (feat) PerfBB - links for task and bv

- public/static/app/perf-bb/ChangePointsService.js
- public/static/app/perf/perf.js
- public/static/app/perf/trend_chart.js
- service/templates/task.html
- service/templates/task_perf_data.html
> EVG-5459 (feat) Trendchart - CP actions

- model/distro/distro.go
- model/distro/distro_test.go
- rest/model/host.go
- rest/model/host_test.go
- rest/route/host_test.go
- rest/route/service_test.go
Added some testing here as well.
> EVG-5314: Expose image ID in rest v2 host API endpoint

- model/project.go
- model/project_ref.go
- model/project_test.go
- model/version/db.go
- public/static/app/waterfall/waterfall.jsx
- public/static/dist/js/waterfall/waterfall.js
- rest/data/version.go
- service/waterfall.go
The version on the right is a triggered version
> EVG-5378 add filtering of triggered builds to waterfall

- operations/model.go
- operations/model_test.go
I'm pretty sure this doesn't get merged as is however, using this locally it works exactly as the ticket EVG-5542 describes.
But I'm happy to do whatever is required to make this merge-able.
> EVG-5542 Load a local config file and override global settings from it

- public/static/app/common/EvgGridUtil.test.js
- public/static/app/common/EvgUiGridUtil.js
- public/static/app/perfdiscovery/PerfDiscoveryStateService.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- public/static/app/perfdiscovery/multiselectGridHeader.js
- public/static/app/perfdiscovery/templates.js
> EVG-3409 (feat) Perfdiscovery - exclusionary filtering

- public/static/app/perf-bb/PerfBBFailuresCtrl.js
- public/static/app/perf-bb/failures.html
- public/static/app/perf-bb/routes.js
- service/templates/signal_processing.html
> EVG-5552 (feat) PerfBB - rename Warnings to Failures

- public/static/app/perf-bb/change-points.html
> EVG-5562 (feat) PerfBB - Green buttons

- public/static/app/perf-bb/PerfBBFailuresCtrl.js
> EVG-5483 (feat) PerfBB/Failures - make Create Time col 1st

- public/static/app/perf-bb/SignalProcessingCtrl.js
> EVG-5520 (fix) PerfBB - variant links wrong date part

- public/static/js/task_timing.js
- public/static/js/task_timing.test.js
Haven't tested in the wild, but unit tests have passed.
> EVG-5608 (feat) Task Timing - exclude execution tasks

- public/static/app/perf-bb/PerfBBFailuresCtrl.js
- public/static/app/perf-bb/failures.html
- public/static/app/perf-bb/templates.js
> EVG-5652 (feat) PerfBB/Failures - Grouping + EVG-5653

- model/project_ref.go
- public/static/js/projects.js
- public/static/partials/project_trigger_modal.html
- service/templates/projects.html
- trigger/process.go
- trigger/process_test.go
> EVG-5530 redo UI for triggers

- cloud/docker_client.go
- cloud/docker_integration_test.go
- cmd/parse-host-file/parse-host-file.go
- makefile
- model/distro/distro.go
- self-tests.yml
- service/templates/distros.html
the earliest commit is probably the only one worth reviewing
> EVG-5477 support pulling docker images from registries

- plugin/perf.go
- public/static/app/perf/PerfChartService.js
- public/static/app/perf/TestSample.js
- public/static/app/perf/TrendSamples.js
- public/static/app/perf/perf.js
- public/static/app/perf/perf.test.js
- public/static/app/perf/trend_chart.js
- service/templates/task_perf_data.html
> EVG-5718 (feat) Trendchart - metric selection (minimal)

- model/notification/db.go
- model/notification/notification_test.go
- units/event_metajob.go
Not a fix, but should help debugging.
> EVG-5717: Missing notifications for GutHub PR status

- units/event_metajob.go
Lets us see notifications generated by an event before inserting into database.
> EVG-5717: One more logging addition

- rest/data/commit_queue.go
- rest/data/commit_queue_test.go
- rest/data/impl.go
- rest/data/interface.go
- rest/model/commit_queue.go
- rest/model/commit_queue_test.go
- rest/route/commit_queue.go
- rest/route/commit_queue_test.go
- rest/route/github_test.go
- rest/route/service.go
Also preemptively changing variable names: CommitQ->CommitQueue
> EVG-5591: Add REST route for getting commit queue contents

- model/notification/notification.go
- units/event_metajob.go
- change sent_at field in notifications to omit_empty
- remove debugging logging
> EVG-5717: GitHub Status Notifications Fix

- agent/command.go
Let me know if this isn't what we wanted or if any error messages should be reworded.
> EVG-5474 clarify error message for context timeouts

- model/task/task.go
- model/task_lifecycle_test.go
- service/task.go
- service/templates/task.html
> EVG-5751 display log links in UI

- public/static/js/task.js
- public/static/js/version.js
This approach isn't precise and has some limitations, but works pretty well. Wwriting something more comprehensive makes no sense unless we going to refactor these components, which may took days.
> EVG-1864 (fix) History panel - better infinite scroll up

- model/commitqueue/github_pr_sender.go
GitHub won't display new statuses on PRs if the status is received after the PR has been merged.
Therefore, remove the post to status for the merge success case.
> EVG-5810: Remove post to GitHub status for merge success case

- rest/data/commit_queue.go
- rest/data/commit_queue_test.go
- rest/data/interface.go
- rest/route/github.go
- rest/route/github_test.go
- rest/route/service.go
- thirdparty/github.go
- thirdparty/github_test.go
Check a user's permissions when they trigger the commit queue to make sure we're okay with the m running a patch and merging.
> EVG-5811: check user's GitHub permissions

- config_db.go
- config_serviceflags.go
- rest/model/admin.go
- rest/route/stats.go
- service/templates/admin.html
JIRA: https://jira.mongodb.org/browse/EVG-5633
> EVG-5633: add degraded mode for cache historical test endpoint

- thirdparty/github.go
Fix a bug in checking user permissions for commit queue
> EVG-5811: Check user permissions

- public/static/js/host.js
For some context: https://jira.mongodb.org/browse/EVG-5284?focusedCommentId=2017458&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2017458
> EVG-5738 (fix) Host - link for started by task

- subprocess/subtree_oom.go
- subprocess/subtree_oom_darwin.go
- subprocess/subtree_oom_linux.go
- subprocess/subtree_oom_test.go
Please let me know if I'm misinterpreting the use or results of exec.Command, or if there's a way to test it that I'm unfamiliar with.
> EVG-5419 check for processes killed by OOM killer

- public/static/js/spawned_hosts.js
- public/static/partials/user_host_update.html
- public/static/thirdparty/SHA-1.js
- service/templates/spawned_hosts.html
> EVG-473 (feat) Spawned hosts - random RDP password

- model/project_ref.go
- units/crons.go
- units/repotracker.go
JIRA: https://jira.mongodb.org/browse/EVG-1053
> EVG-1053: repo tracker only fetches revisions if project is configured

- config.go
- validator/project_validator.go
- validator/project_validator_test.go
JIRA: https://jira.mongodb.org/browse/EVG-763
> EVG-763: validate command inside of functions

- command/git.go
- command/git_test.go
- model/project.go
- model/project_test.go
- model/task_config.go
- model/testutil/api.go
- rest/data/host_create_test.go
- service/api.go
This is almost exactly Stu's code but I didn't see anything else that needed changing, but let me know if there's something else I should be testing or looking at.
> EVG-3678 make oauth tokens default

- public/static/js/projects.js
Not sure if this was the way to go about this, but I grabbed the default value from [here](https://github.com/evergreen-ci/evergreen/blob/master/trigger/task.go#L80) .
> EVG-5835 default re-notify value

- model/commitqueue/github_pr_sender.go
- rest/route/github.go
- units/commit_queue.go
- units/github_status_api.go
- units/github_status_api_test.go
JIRA: https://jira.mongodb.org/browse/EVG-5838
> EVG-5838: post status message that commit queue merge request has been received by Evergreen

- cmd/evergreen/evergreen.go
- config.go
- operations/notification.go
- rest/client/interface.go
- rest/client/mock.go
- rest/client/rest.go
JIRA: https://jira.mongodb.org/browse/EVG-5884
This doesn't seem to actually work when it sends the request, even though the response is 200 OK.
> EVG-5884: add command to send notifications via CLI

- config.go
- operations/notification.go
- rest/model/notification.go
- rest/route/notification.go
JIRA: https://jira.mongodb.org/browse/EVG-5890
> EVG-5890: add priority to Composers and validation check for octothorpe/arobase for slack messages

- public/static/js/projects.js
- service/project.go
- service/templates/projects.html
This fixes a bug introduced by PR #2061. The fixes not included in the last PR are just the last commit, 
f28bf8c.
> EVG-5771: Project webhooks on by default

- agent/agent.go
- agent/task.go
- rest/client/logger.go
JIRA: https://jira.mongodb.org/browse/EVG-5882
I moved the deferred killProcs into finishTask.
> EVG-5882: log when killProcs is cleaning up

- agent/agent.go
- rest/client/logger.go
This reverts commit 206d9881caea648b26724ed9bc23ae9956787f5e.
> Revert "EVG-5882: log when killProcs is cleaning up (#2082)"

- cmd/build-cross-compile/build-cross-compile.go
- makefile
- units/event_metajob.go
also include go1.12 build improvements
> EVG-5927: event/notification dispatch speed improvements

- public/static/app/common/constants.js
- public/static/app/perf-bb/PerfBBOutliersCtrl.js
- public/static/app/perf-bb/PerfBBOutliersCtrl.test.js
- public/static/app/perf-bb/SignalProcessingCtrl.js
- public/static/app/perf-bb/constants.js
- public/static/app/perf-bb/outliers.html
- public/static/app/perf-bb/routes.js
- public/static/js/tests/conf/karma.conf.js
- service/templates/signal_processing.html
- service/templates/task_perf_data.html
This is still some work to be done here, but I wanted to make sure I was headed in the right direction. This adds an outliers tab to the performance build baron page. Right now, it will display the detected and suspected outliers.
> EVG-5913: Add Outlier tab to Performance Baron page

- model/task_lifecycle.go
JIRA: https://jira.mongodb.org/browse/EVG-5965
> EVG-5965: add logs to debug where cached task is not updated

- trigger/task_jira.go
- trigger/task_jira_test.go
More in line with model/task/results.go#L27-L42
> EVG-5819: Fix system unresponsive status for Jira tickets

- units/host_monitoring_container_state.go
I may be missing some context, but doesn't look like there's much to do--the [aggregation](https://github.com/ablack12/evergreen/pull/new/EVG-5868) that determines when to terminate hosts spawned by tasks would cover docker containers, and the jobs themselves handle containers correctly.
> EVG-5868 remove containers after task is done

- public/static/app/common/OutliersDataService.js
- public/static/app/common/OutliersDataService.test.js
- public/static/app/common/PointsDataService.js
- public/static/app/common/PointsDataService.test.js
- public/static/app/perf-bb/PerfBBOutliersCtrl.js
- public/static/app/perf-bb/SignalProcessingCtrl.js
- public/static/app/perf/perf.js
- public/static/app/perfdiscovery/PerfDiscoveryDataService.js
- public/static/app/perfdiscovery/PerfDiscoveryDataService.test.js
- public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
- service/templates/base_angular.html
First set of changes to display detected outliers. Marked outliers will be added later.
> EVG-5912 show-outlier-status on PerfDiscovery page

- units/provisioning_setup_host.go
JIRA: https://jira.mongodb.org/browse/EVG-6076
> EVG-6076: setup host job should return if distro is not found

- public/static/app/perf/TestSample.js
- public/static/app/perf/TrendSamples.js
- public/static/app/perf/perf.js
- public/static/js/filters/filters.common.js
This doesn't fix the ticket entirely, but makes the trend charts more generalized so that they can support metrics other than ops/sec and makes it a lot easier for me to debug what's left of the ticket
> EVG-6087 make perf trend charts more generalized

- public/static/app/perf-bb/PerfBBOutliersCtrl.js
- public/static/app/perf-bb/PerfBBOutliersCtrl.test.js
- public/static/app/perf-bb/outliers.html
> EVG-6032 sorting and filtering, ensure type column is visible.

- operations/patch_util.go
Output from my locally built binary:
```
@rocinante ➜  evergreen git:(master) ✗ ./clients/darwin_amd64/evergreen list-patches
ID : 5cc74eb72fbabe51c0f4a9e4
Created : 2019-04-29 19:21:28.275 +0000 UTC
Description : fix-embedded-no-venv: WIP: fix possible shell quoting issue?
Build : https://evergreen.mongodb.com/version/5cc74eb72fbabe51c0f4a9e4
Status : started
Finalized : Yes
ID : 5cc74e7e0305b925bcfa86b0
Created : 2019-04-29 19:20:31.407 +0000 UTC
Description : hy-ng: WIP: Add tarball builder
Build : https://evergreen.mongodb.com/patch/5cc74e7e0305b925bcfa86b0
Status : created
Finalized : No
ID : 5cc725b00305b932d7cc5f1e
Created : 2019-04-29 16:26:26.289 +0000 UTC
Description : fix-embedded-no-venv: SERVER-40462: Disallow transactions on shard servers with …
```
> EVG-6127 Add patch status to CLI output

- command/git.go
David Bradford wants the revision for the module logged for better debugging.
> EVG-6160 add logging for module revision

- model/host/db.go
- model/host/host_test.go
- model/task_queue.go
- model/task_queue_service.go
- model/task_queue_test.go
- rest/route/distro_test.go
- service/api.go
- service/api_task.go
- service/api_task_test.go
- service/ui.go
- units/crons.go
> EVG-6170 turn on new task queue service as an experiment

- operations/agent_monitor.go
- self-tests.yml
JIRA: https://jira.mongodb.org/browse/EVG-6207
> EVG-6207: fix agent monitor port range

- model/build/build.go
- model/build/build_test.go
- model/build/task_cache.go
- model/build/task_cache_test.go
- model/task/sorter.go
- model/task/task.go
- model/task_lifecycle.go
- model/task_lifecycle_test.go
- units/task_monitor_execution_timeout_test.go
Reintroduce the changes from #2332, which were reverted by 5176052890cdcdc49c9ff903f937907b7604b6c2.
The new changes begin from commit 15027f7
> EVG-6159: restart system failed tasks

- model/project_vars.go
- model/project_vars_test.go
- rest/data/interface.go
- rest/data/project.go
- rest/data/project_test.go
- rest/model/project_event.go
- rest/route/project_test.go
- rest/route/project_vars.go
- rest/route/project_vars_test.go
- rest/route/service.go
The GET route returns the redacted variables.
The PATCH route allows you to add, change, and delete variables (let me know if the varsToDelete list is awkward), and returns the updated list of variables (redacted).
> EVG-6189 get/modify variables

- cloud/ec2.go
- model/distro/db.go
- model/distro/distro.go
- model/host/hostutil.go
- model/host/hostutil_test.go
- rest/model/distro.go
- rest/route/distro_test.go
- service/templates/distros.html
- units/provisioning_setup_host.go
JIRA: https://jira.mongodb.org/browse/EVG-6225
* Location of curator is now based on distro setting instead of hard-coded value.
> EVG-6225: add config options for distro-specific curator location

- public/static/js/task.js
- service/templates/task.html
Test results on the task page cannot be searched using cmd/ctrl-F, so I added a search text box to filter the results by their display name.
> EVG-6008: Create search box to filter test results on task page

- config.go
- operations/fetch.go
- operations/http.go
- operations/patch_list.go
Currently we don't actually implement the --patch or --variant flags. I fixed the --patch flag because that's what was requested by the ticket, but I get the feeling nobody uses the --variant flag since no one has ever said anything, so I'm just going to remove it.
> EVG-6218 fix list-patches by id

- public/static/js/distros.js
- service/templates/distros.html
> EVG-6266 dependencies are scheduled in tunable scheduler

- model/project_ref.go
- model/project_ref_test.go
- public/static/js/projects.js
- service/project.go
- service/templates/projects.html
> EVG-6267 periodic builds - configuration

- model/project_ref.go
- model/project_ref_test.go
- model/version.go
- model/version_db.go
- model/version_test.go
- repotracker/repotracker.go
- scripts/indexes.js
- service/project.go
- trigger/project_triggers.go
- units/crons.go
- units/crons_remote_fifteen_minute.go
- units/periodic_builds.go
- units/periodic_builds_test.go
activating the build with the alias will be in the next PR since this one was getting long
> EVG-6267 create periodic build job

- public/static/app/perf/trend_chart.js
@dbradf @jimoleary @ancostas this is the result of https://mongodb.slack.com/archives/C0V3KSB52/p1561130681062200
> EVG-6106 only show change points for ops/s

- operations/patch_list.go
Sample output:
```
@raza ➜  evergreen git:(master) ./clients/linux_amd64/evergreen list-patches --json -n 1
[
{
"patch_id": "5d1676971e2d1735ef152247",
"description": "fix-lint: SERVER-41168 Add docstrings to lldb debug extensions",
"project_id": "mongodb-mongo-master",
"branch": "mongodb-mongo-master",
"git_hash": "7f2630cf028f38d45dd5d9e3415d44f31b3cc030",
"patch_number": 851,
"author": "mathew.robinson",
"version": "5d1676971e2d1735ef152247",
"status": "succeeded",
"create_time": "2019-06-28T20:20:39.577Z",
"start_time": "2019-06-28T20:20:39.577Z",
"finish_time": "2019-06-28T20:20:39.577Z",
"builds": [
"enterprise-rhel-62-64-bit"
],
"tasks": [
"lint"
],
"variants_tasks": [
{
"name": "enterprise-rhel-62-64-bit",
"tasks": [
"lint"
]
}
],
"activated": true,
"alias": "", …
```
> EVG-6387 Add JSON output to list-patches as a flag

- makefile
I found myself using delve in EVG-6176, so I added support in the makefile. The goal is to to be able to take a command like:
```
SETTINGS_OVERRIDE=/Users/brian/Desktop/config.yml RUN_TEST=TestGitGetProjectSuite/TestBuildCloneCommandDefaultCloneMethodUses make test-command
```
and simply substitute "dlv" for "test":
```
SETTINGS_OVERRIDE=/Users/brian/Desktop/config.yml RUN_TEST=TestGitGetProjectSuite/TestBuildCloneCommandDefaultCloneMethodUses make dlv-command
```
As as you have delve installed `go get -u github.com/go-delve/delve/cmd/dlv`, it should just work. I've done a little bit of testing, and it seems to work, but I could be missing something.
> EVG-6176 Add delve support to makefile

- model/version_db.go
- public/static/partials/github_commit_panel.html
- rest/data/interface.go
- rest/data/project.go
- rest/route/project.go
- rest/route/project_test.go
- rest/route/service.go
- service/templates/build.html
- service/templates/projects.html
- service/templates/task.html
- service/templates/version.html
example build: https://evergreen-staging.corp.mongodb.com/version/5d3615e79dbe32172d795887
> EVG-6267 UI fixes, make periodic builds discoverable

- service/service.go
- service/ui.go
we might want to move this to gimlet (longer term) or put
> EVG-6499: add robots.txt handler

- service/templates/distros.html
JIRA: https://jira.mongodb.org/browse/EVG-6505
> EVG-6505: correctly set fields for distro bootstrap config

- units/provisioning_setup_host.go
JIRA: https://jira.mongodb.org/browse/EVG-6503
> EVG-6503: allow scp command to put file in non-home directory in setup host job

- glide.lock
- model/host/hostutil.go
- model/host/hostutil_test.go
- vendor/github.com/mongodb/jasper/command.go
- vendor/github.com/mongodb/jasper/command_test.go
- vendor/github.com/mongodb/jasper/glide.lock
- vendor/github.com/mongodb/jasper/process_basic.go
- vendor/github.com/mongodb/jasper/process_blocking.go
- vendor/github.com/mongodb/jasper/rpc/creds.go
- vendor/github.com/mongodb/jasper/vendor/github.com/tychoish/bond/util.go
JIRA: https://jira.mongodb.org/browse/EVG-6495
> EVG-6495: set user for host's Jasper service

- model/host/hostutil.go
JIRA: https://jira.mongodb.org/browse/EVG-6509
> EVG-6509: set ServerName when exporting credentials to JSON file

- model/host/host.go
- units/host_monitoring_idle_termination_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6513
> EVG-6513: terminate idle non-legacy hosts

- model/distro/distro.go
- units/provisioning_agent_monitor_deploy.go
JIRA: https://jira.mongodb.org/browse/EVG-6511
> EVG-6511: run agent monitor command in bash

- config_scheduler.go
- globals.go
- model/distro/distro.go
- model/distro/distro_test.go
- rest/model/admin.go
- rest/model/distro.go
- rest/route/distro_test.go
- scheduler/host_allocator_fuzzer_test.go
- scheduler/planner.go
- scheduler/planner_test.go
- scheduler/scheduler.go
- scheduler/setup_funcs.go
- scheduler/task_prioritizer.go
- scheduler/task_queue_persister.go
- scheduler/task_queue_persister_test.go
- scheduler/utilization_based_host_allocator_test.go
- scheduler/wrapper.go
- validator/distro_validator.go
This is a work in progress. Still needs:
- tests
- options to enable it (distro config/scheduler job)
> EVG-5694: new planner

- model/credentials/db_test.go
- model/host/hostutil.go
JIRA: https://jira.mongodb.org/browse/EVG-6509
> EVG-6509: ensure all credentials functions return ServerName with RPC credentials

- config_ui.go
- model/user/user.go
- public/static/js/settings.js
- rest/model/admin.go
- rest/model/user.go
- rest/model/user_test.go
- service/templatefuncs.go
- service/templates/admin.html
- service/templates/menu.html
- service/templates/settings.html
This currently only changes the /patches/mine page, if the config option is set by the user. The master admin switch is a later ticket. I also removed some new waterfall stuff that seems to be old since everyone is now on the new waterfall.
> EVG-6476 add a config option to point to new UI

- model/credentials/db.go
- model/credentials/db_test.go
- model/host/host.go
- units/jasper_deploy_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6509
> EVG-6509: return ServerName from credentials functions

- agent/agent_test.go
- agent/task.go
- model/project.go
- model/project_parser.go
No project configs are using the existing field
> EVG-6526 add option to fail task if pre fails

- model/host/hostutil.go
- model/host/hostutil_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6528
> EVG-6528: explicitly set host when installing Jasper service

- public/static/js/settings.js
- service/templates/settings.html
This set of changes includes adding form fields when a user clicks the "opt out" checkbox on the patches page .
> EVG-6447: add form for opting out of new patches page

- operations/agent_monitor.go
JIRA: https://jira.mongodb.org/browse/EVG-6541
> EVG-6541: fix agent monitor file logging

- operations/agent_monitor.go
JIRA: https://jira.mongodb.org/browse/EVG-6541
> EVG-6541: make parent directories of agent monitor log file if nonexistent

- model/lifecycle.go
- model/task_lifecycle.go
- service/api_task.go
I believe Jonathan's PR will address the rest of this
> EVG-6497 remove logging

- model/host/db.go
- model/host/host.go
- model/host/host_test.go
- units/crons.go
JIRA: https://jira.mongodb.org/browse/EVG-6562
> EVG-6562: only set NeedsNewAgent on legacy hosts

- operations/commit_queue.go
Check project has commit-queue enabled before creating a patch.
> EVG-6311 check project has commit-queue enabled

- model/host/db.go
- model/host/host.go
- model/host/host_test.go
- service/api_task.go
- service/api_task_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6579
> EVG-6579: log time to first agent-initiated contact

- public/static/app/perf/perf.js
(hopefully) fixes a timing issue when we tried to draw graphs before data was actually loaded when a perf test has data in both evergreen and cedar
> EVG-6420 consistently load graphs with legacy trend data

- glide.lock
- model/host/hostutil.go
- model/host/hostutil_test.go
- units/jasper_deploy.go
- vendor/github.com/mongodb/jasper/cli/ssh_client.go
- vendor/github.com/mongodb/jasper/cli/ssh_client_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6610
> EVG-6610: close connection when done with Jasper client

- units/host_termination_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6636
> EVG-6636: increase cost delta for TestHostCosts

- public/static/app/perf/perf.js
We've been having problems with loading data racing with drawing of graphs that I've tried to fix in various ways, so I'm just removing 1 layer of concurrency with this
> EVG-6670 use fewer promises in trend graphs

- public/static/app/perf/perf.js
The second commit is whitespace and formatting only. The fixes is in the last commit.
> EVG-6678 fix change points / build Failures

- public/static/app/perf/perf.js
> EVG-6678 bugfix.

- service/templatefuncs.go
- service/templates/menu.html
- service/timeline.go
Redirect `patches/mine` and `pathces/user/<username>` to the new patch page for users who've opted in.
> EVG-6561 redirect to new patch page

- model/patch_lifecycle.go
- model/patch_lifecycle_test.go
- model/project_parser.go
- model/project_parser_test.go
- scheduler/setup_funcs.go
- scheduler/task_priority_cmp_test.go
- service/api_patch.go
- units/commit_queue.go
- units/patch_intent.go
The commit that needs review is the second one. Had to modify some yamls in the tests but I believe thats' because they didn't have to be translated before.
> EVG-6441 store untranslated projects for versions

- model/generate.go
- model/version.go
- model/version_test.go
If a generate tasks task runs as part of a commit queue patch and the patch doesn't contain a merge task (such as for a PR queue) it will cause a panic.
> EVG-6426: check for nil task

- model/task/task.go
- model/task/task_test.go
In the case of a race generate.tasks returns document not found, since the
config string had been modified by another job. This commit fixes a case where we
failed to check this. In this case we should not set the GeneratedTasksKey
field, since this job has not in fact generated tasks.
> EVG-6517 Do not mark task as having generated if it raced

- plugin/perf.go
- public/static/app/common/ApiTaskdata.js
- public/static/app/common/constants.js
- public/static/app/perf/perf.js
- public/static/app/perf/perf.test.js
- public/static/app/perf/trend_chart.js
- public/static/js/filters/filters.common.js
- public/static/js/filters/filters.test.js
Plus multiple bug fixes. I'll list the tickets in a subsequent comment.
I've tried to separate the commits into logical groups, the middle one contains all the significant code changes.
> EVG-6291 nearest bf

- model/task_queue_service_dependency.go
- public/static/js/distros.js
- service/templates/distros.html
- validator/distro_validator.go
- validator/distro_validator_test.go
> EVG-6640: add distro UI configuration for distro alias field

- model/host/hostutil.go
- model/host/hostutil_test.go
- units/provisioning_setup_host.go
JIRA: https://jira.mongodb.org/browse/EVG-6742
> EVG-6742: ensure parent directories exist when running provisioning commands

- model/host/hostutil.go
- model/host/hostutil_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6748
> EVG-6748: use splunk channel flag for Jasper service only if set

- model/host/hostutil.go
- model/host/hostutil_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6766
> EVG-6766: allow non-root user to write to directories made by user data

- cloud/ec2_fleet.go
Log the actual response to aid debugging.
> EVG6768 log Fleet error

- environment.go
- vendor/github.com/mongodb/amboy/queue/group_remote_mongo_single.go
includes the chage from: https://github.com/mongodb/amboy/pull/126
> EVG-6670: cleanup queue creation code

- service/api_task_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6658
> EVG-6658: fix TestNextTask

- cloud/ec2_util.go
Fixes issue with expire-on tag.
> EVG-6665 Fix expire-on tag

- units/commit_queue.go
Project syntax warnings shouldn't cause a commit to be rejected by the commit queue.
> EVG-6781 allow project warnings through the commit queue

- model/distro/db.go
- model/distro/distro.go
- model/host/db.go
- model/host/host.go
- model/host/hostutil.go
- model/host/hostutil_test.go
- public/static/js/distros.js
- rest/model/distro.go
- rest/model/distro_test.go
- rest/route/distro_test.go
- service/templates/distros.html
- units/provisioning_setup_host.go
- validator/distro_validator.go
- validator/distro_validator_test.go
JIRA: https://jira.mongodb.org/browse/EVG-6508
* PowerShell script to set up a new user with Administrator privileges and the right to run services.
* Distro setting for new service user's name.
* Service user's password generated for each host.
* Host's Jasper service runs as the new user.
> EVG-6508: use admin user for Windows provisioning instead of LocalSystem default

- public/static/js/directives/directives.spawn.js
- public/static/js/services/rest.js
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_start.html
- public/static/partials/user_host_stop.html
- public/static/partials/user_host_terminate.html
- service/spawn.go
- service/templates/spawned_hosts.html
This adds pause and play buttons alongside the existing trash can that allows users to stop and start their instances using the Evergreen UI. The pause button only appears when the host is running, and the play button only appears when the host is stopped.
> EVG-6628 Start and stop instances via the host spawn page

- cloud/docker_client.go
Clusters of provision-host failures are the result of a missing Docker container image on the parent host. Log the parent host when this error is encountered.
> EVG-6721 add logging on failed container creation

- service/templates/distros.html
- units/provisioning_setup_host.go
* Fix required root directory field in html
* Fix error message
> EVG-6815: only require root directory in distro settings for Windows

- units/stats_host_idle.go
JIRA: https://jira.mongodb.org/browse/EVG-6840
> EVG-6840: include provisioning type in idle host stats

- service/templates/spawned_hosts.html
Hides start/stop buttons until https://jira.mongodb.org/browse/EVG-6848 is addressed.
> EVG-6627 Hide start/stop buttons until users can ssh after stopping hosts

- cloud/user_data_test.go
- model/host/db.go
- model/host/host_test.go
- units/host_allocator.go
JIRA: https://jira.mongodb.org/browse/EVG-6824
> EVG-6824: remove credentials when deleting stale initializing/building hosts

- apimodels/agent_models.go
- cloud/docker_client.go
- model/host/host.go
- rest/data/host_create.go
- rest/data/host_create_test.go
- self-tests.yml
For example, `docker run -e port=20216`.
> EVG-6243 use docker environment variables

- cloud/ec2.go
- model/host/host.go
- model/host/host_test.go
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_details.html
- service/spawn.go
This reverts commit 86f12eade693f883a2693ea119cd3edea57bf71f.
> Revert "EVG-6617 logic for non-expirable hosts from UI (#2792)"

- cloud/ec2.go
- model/host/host.go
- model/host/host_test.go
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_details.html
- service/spawn.go
This commit handles the javascript display logic differently using `setCurrentExpirationOnClick`. The refactor that was attempted here will actually be separated into EVG-6872.
> EVG-6617 logic for non-expirable hosts from UI

- model/host/db.go
- model/host/host.go
- model/host/host_intent.go
JIRA: https://jira.mongodb.org/browse/EVG-6902
* Remove `host.Host.DispatchTime` since it seems unused.
* Set `host.Host.LastTaskCompletedTime` once updated in the DB.
> EVG-6902: remove unused Host.DispatchTime field

- public/static/js/spawned_hosts.js
- public/static/partials/user_host_details.html
Modularized the js file a bit. The initial update is the same, but the later updates only look at uptime, status, expires in, id, and instance type (if previously unpopulated).
> EVG-6872 only update certain fields with the timer

- makefile
JIRA: https://jira.mongodb.org/browse/EVG-6905
> EVG-6905: remove model-credentials from makefile

- cloud/ec2.go
- config.go
- model/host/db.go
- operations/host_spawn.go
- operations/volume.go
- rest/client/interface.go
- rest/client/mock.go
- rest/client/rest.go
- rest/model/host.go
- rest/route/host_spawn.go
- rest/route/host_spawn_test.go
- rest/route/service.go
```
2 volumes started by user (total size 100):
ID                : volume1
Size              : 64
Type              : gp2
Availability Zone : us-east-1a
Device Name       : /dev/sdf4
Attached to Host  : has-a-volume
ID                : volume2
Size              : 36
Type              : gp2
Availability Zone : us-east-1a
```
> EVG-6841 list volumes

- model/host/host.go
- model/host/host_test.go
- operations/host_spawn.go
- operations/host_test.go
- public/static/js/services/rest.js
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_details.html
- rest/model/host.go
- service/spawn.go
Also moves tag validation out of operations.
> EVG-6619 add/delete tags from UI

- glide.lock
- operations/admin.go
- operations/service_web.go
- units/stats_amboy.go
- vendor/github.com/mongodb/amboy/glide.lock
- vendor/github.com/mongodb/amboy/periodic.go
- vendor/github.com/mongodb/amboy/periodic_test.go
- vendor/github.com/mongodb/amboy/queue/group_remote_mongo.go
- vendor/github.com/mongodb/amboy/rest/service_abortable_pool.go
- vendor/github.com/mongodb/amboy/rest/service_group_management.go
(I shimed in https://github.com/mongodb/amboy/pull/128 and will revendor and adjust later)
> EVG-6729: add queue group reporting

- public/static/partials/user_host_details.html
JIRA: https://jira.mongodb.org/browse/EVG-6978
The key in the model distro was changed, so I updated it.
> EVG-6978: fix user data check in spawn host page

- rest/route/host_spawn.go
JIRA: https://jira.mongodb.org/browse/EVG-6983
> EVG-6983: improve max unexpirable spawn host error message

- public/static/js/spawned_hosts.js
- service/spawn.go
This ticket originally was to add stop/start to the notifications page, however this is already a part of Spawn Host Outcome. This is undocumented in the wiki so I'll just add it, and these are a couple of fixes I found in testing.
> EVG-6622 spawn host fixes

- public/static/app/perf-bb/SignalProcessingCtrl.js
- public/static/app/perf-bb/SignalProcessingCtrl.test.js
The lint errors are due to previous commits.
> EVG-7027 hide acked.

- rest/model/build.go
- rest/route/build.go
- rest/route/build_test.go
This code removes Branch from APIBuild and assigns ProjectId in APIBuild the Branch from the Build model
> EVG-6416: Build project and branch are incorrect in rest v2

- units/stats_host_idle_test.go
- units/stats_task_end_test.go
I forgot to add these tests before merging #2898
> EVG-6408 add tests

- public/static/js/services/rest.js
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_details.html
- Run prettier (don't review first commit)
- Nest some of the controls on the spawn host details pane into a single card with a single update button at the bottom
- Modify the functions that previously sent requests to update data. Call them sequentially if anything changed
> EVG-6898 combine buttons on spawn host page

- units/provisioning_setup_host.go
JIRA: https://jira.mongodb.org/browse/EVG-7049
This command is using Append instead of Add, which is incorrect and a source of shell quoting bugs.
> EVG-7058: fix shell quoting on spawn host commands in legacy SSH

- model/commitqueue/commit_queue.go
- model/commitqueue/commit_queue_test.go
- model/commitqueue/db.go
- operations/commit_queue.go
- operations/flags.go
- rest/client/interface.go
- rest/client/mock.go
- rest/client/rest.go
- rest/data/commit_queue.go
- rest/data/commit_queue_test.go
- rest/data/interface.go
- rest/route/commit_queue.go
- rest/route/commit_queue_test.go
- rest/route/github.go
- rest/route/github_test.go
As stated in the ticket, this won't auth but will log at a high level so we're aware of when it's used.
> EVG-6893 add force flag to commit queue

- command/git.go
I decided to make it opt-in to give users more flexibility.
On the other hand I can't think of a scenario where you wouldn't want to check out submodules (where there are submodules), so I'd be open to the argument that maybe we should just do it automatically.
> EVG-6419 add recurse-submodules option to git.get_project

- glide.lock
- globals.go
- model/distro/distro.go
- model/distro/distro_test.go
- model/project_ref.go
- model/project_ref_test.go
- model/user/user_test.go
- service/distros.go
- service/project.go
- vendor/github.com/evergreen-ci/gimlet/auth_interfaces.go
- vendor/github.com/evergreen-ci/gimlet/evergreen.yaml
- vendor/github.com/evergreen-ci/gimlet/makefile
- vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager.go
- vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager_test.go
- Add a function that creates a scope, creates an admin role, and gives that admin role to the creator of a project or distro
- Call this function when one is created from the UI
> EVG-7061 add permissions when a project is created

- public/static/js/patches.js
Referencing a DM from benety, non-super users couldn't see configure/reconfigure.
> EVG-7162 correctly access patch author

- agent/task.go
(should i have created a ticket for this or)
> fix-task check pt is not nil

- rest/route/auth.go
> EVG-7042: check acl enabled for permissions check endpoint

- globals.go
- model/generate.go
- rest/data/host_create_test.go
- service/rest_version.go
- service/rest_version_test.go
This reverts commit 66bc22361f6b7b72d60cbc445cff5955ae520293.
Does not need review.
> EVG-7085 turn on parser project (#3024)

- rest/data/host.go
- units/building_container_image.go
- units/host_monitoring_parent_decommission.go
- units/host_termination.go
mostly just for headache reduction when debugging
> EVG-7249 better logging of host deco reason

- public/static/js/distros.js
JIRA: https://jira.mongodb.org/browse/EVG-7284
> EVG-7284: fix copying distro's host allocator settings

- model/host/hostutil.go
- model/host/hostutil_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7298
> EVG-7298: add newlines for bash profile append

- db/db_utils.go
- model/task/expected_duration.go
- model/task/expected_duration_test.go
- scheduler/planner_test.go
this is just a hack until we figure out why the query is using the wrong index
> EVG-7286 hint expected duration query

- public/static/js/spawned_hosts.js
- public/static/partials/user_host_details.html
- service/spawn.go
- service/templates/spawned_hosts.html
If a user has exhausted their unexpirable hosts the UI should prevent them from trying to request more and tell them why.
> EVG-7166 never expire checkbox

- model/host/hostutil.go
- model/host/hostutil_test.go
JIRA: https://jira.mongodb.com/browse/EVG-7298
> EVG-7298: fix permissions after umask

- rest/model/distro.go
Accidentally was not setting this if ProviderSettingsList was populated.
> EVG-7232 set settings in API route

- public/static/app/perf/trend_chart.js
It is possible that thread level do not contain any results. When this happens on a change point, walk the previous point back to find the correct place to draw the line segment.
> EVG-7364 gracefully handle missing results.

- graphql/generated.go
- graphql/integration_spec.json
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/testdata/remove-favorite-project-mutation.graphql
- model/user/user.go
- model/user/user_test.go
mutation to remove a project from FavoriteProjects in the user DB model
> EVG-7309: remove project from user favorites

- model/host/hostutil.go
- model/host/hostutil_test.go
Settings should be the same between the agent and agent monitor.
> EVG-7264: remove old agent monitor flags and environment

- command/attach_artifacts.go
[EVG-7385](https://jira.mongodb.org/browse/EVG-7385)
> EVG-7385 Add Validation to attach_artifact

- model/lifecycle.go
Spent a really long time looking for this thing that John had actually linked in the ticket.
> EVG-6917 display tasks shouldn't have dependencies

- gqlgen.yml
- graphql/generated.go
- graphql/integration_spec.json
- graphql/models_gen.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/testdata/user.graphql
- rest/model/user.go
https://jira.mongodb.org/browse/EVG-7202
The latest designs only need the displayName field for now
> EVG-7202: Query for user info

- model/generate.go
- model/generate_test.go
Over the shoulder PR'ed by Brian
> EVG-7085 consider generate tasks with parser project flag

- operations/service.go
- operations/service_web.go
JIRA: https://jira.mongodb.org/browse/EVG-7396
> EVG-7396: move local ssh key job

- units/reauthorization_job.go
> EVG-7384: set user ID

- model/host/hostutil.go
- units/provisioning_agent_monitor_deploy.go
JIRA: https://jira.mongodb.org/browse/EVG-7377
> EVG-7377: check for running agent monitor before deploy

- model/project_ref.go
- model/project_ref_test.go
- units/crons.go
- units/periodic_builds.go
- units/periodic_builds_test.go
This is just the back-end, but allows specifying a start time for a periodic build. This start time is updated as the jobs run.
Also fixes an unrelated issue where builds created don't get scheduled
> EVG-7180 support start time for periodic builds

- public/static/js/projects.js
- public/static/js/services/time.js
- public/static/js/settings.js
- public/static/partials/periodic_build_modal.html
- public/static/partials/project_trigger_modal.html
- service/templates/projects.html
- service/templates/settings.html
I really hate that there is a time zone picker here
> EVG-7180 UI to set start time for periodic build

- cloud/cloud.go
- cloud/ec2.go
- cloud/gce.go
- cloud/openstack.go
- cloud/vsphere.go
- rest/model/distro.go
- rest/model/distro_test.go
- rest/route/distro.go
- rest/route/distro_test.go
- service/api_distro.go
- service/distros.go
Implementation now covered in comments.
> EVG-7329 modify distro routes to handle provider settings list

- public/static/js/spawned_hosts.js
JIRA: https://jira.mongodb.org/browse/EVG-7444
The spawn host page is producing a bunch of errors in the console for this.
> EVG-7444: check for undefined curHostData

- model/host/hostutil.go
JIRA: https://jira.mongodb.com/browse/EVG-7377
> EVG-7477: only warn if there are multiple simultaneous agent monitors

- agent/directory.go
- agent/directory_test.go
The test passes without my changes, but hopefully this makes things better and not worse ¯\_(ツ)_/¯
> EVG-7442 change permissions in task directory before deleting

- service/api.go
- service/rest_version.go
This will all be modified in a ticket next sprint anyway but alas
> EVG-6929 consider parser project for agent configs

- rest/model/task.go
- rest/route/build_task.go
- rest/route/service_test.go
- rest/route/task.go
I meant to just add a comment to the ticket but then the fix was simple and then it was done so here we are.
> EVG-7451 include logs/artifacts for previous executions

- service/templates/admin.html
Removed functionality, forgot to remove button.
> EVG-6929 remove admin button

- scripts/indexes.js
- units/generate_tasks.go
2 unrelated changes:
1. Delete 2 indices on the versions collection and re-add one of them with the correct keys (sorry my editor autoformatted the file, but it's easier to read now)
2. Add some logging in the generate.tasks job for timing
> EVG-7406 add logging in generate.tasks

- service/ui.go
Reverts evergreen-ci/evergreen#3129
> Revert "return 200 for options req"

- cloud/cloud.go
- cloud/ec2.go
- cloud/openstack.go
- cloud/spawn.go
- cloud/static_test.go
- cloud/vsphere.go
- model/distro/db.go
- model/distro/distro.go
- model/host/host_intent.go
- public/static/js/services/rest.js
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_details.html
- public/static/partials/user_host_options.html
- rest/data/host_create.go
- rest/data/host_create_test.go
- rest/route/host_create_test.go
- service/spawn.go
If the distro has multiple provider settings configured, allow user to choose from region list.
> EVG-7240 choose region from spawn host page

- public/static/js/admin.js
> EVG-7427: check for undefined multi auth

- command/attach_artifacts.go
revert [this](https://github.com/evergreen-ci/evergreen/pull/3157/files)
> EVG-7503 Allow signing on attach.artifacts files

- service/templates/distros.html
JIRA: https://jira.mongodb.org/browse/EVG-7439
> EVG-7439: check for Windows for root dir on distro page

- cmd/run-linter/run-linter.go
JIRA: https://jira.mongodb.org/browse/MAKE-1149
> MAKE-1149: check for empty args before slicing custom linters

- apimodels/task_log.go
> EVG-7566: Return err if user is nil in GetBuildLoggerLogs

- config.go
- operations/list.go
JIRA: https://jira.mongodb.org/browse/EVG-7581
> EVG-7581: add newline for distro aliases

- rest/route/middleware.go
JIRA: https://jira.mongodb.org/browse/EVG-7599
This is to handle the fact that a distro might be deleted and then aliased to another distro ID. The permissions to access the old distro should still apply to the aliased one. The working assumption here is that if you delete a distro, it'll have a corresponding alias in exactly one other distro that replaces it.
> EVG-7599: allow distro aliases in checking distro permissions

- rest/data/interface.go
- rest/data/project.go
- rest/route/project.go
There will be a migration to fix projects that were missed because of this, but that will be independent of this change
> EVG-7598 update roles when updating projects via API

- units/provisioning_setup_host.go
Back out the changes from #3308 and really fix the issue (the mount failed because the volume wasn't getting formatted).
> EVG-7603 fix home directory formatting

- model/host/hostutil.go
- model/host/hostutil_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7612
> EVG-7612: omit Splunk credentials from spawn hosts

- units/duplicate_task_check.go
JIRA: https://jira.mongodb.com/browse/EVG-7443
> EVG-7443: only log once during duplicate task check

- cloud/spawn.go
- model/user/user.go
- operations/host_spawn.go
- public/static/js/settings.js
- public/static/js/spawned_hosts.js
- rest/data/host.go
- rest/data/host_test.go
- rest/model/user.go
- rest/model/user_test.go
- rest/route/host_create.go
- service/spawn.go
- service/templatefuncs.go
- service/templates/settings.html
- service/templates/spawned_hosts.html
- service/user.go
Populates available defaults from the keys defined in admin settings. Uses the default to choose a starting region on the Spawn Host page.
> EVG-7237 add user-defined default region

- model/host/db.go
- model/host/host.go
- model/host/host_test.go
- units/host_termination_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7635
> EVG-7635: exclude hosts from termination if still provisioning but running tasks

- public/static/js/projects.js
Otherwise, they're just saved with blank values which is both wrong and misleading from the UI.
> EVG-7127 remove private vars before copying project from UI

- cloud/ec2_client.go
- cloud/ec2_integration_test.go
> EVG-7602 filter out intent hosts before describe instances

- public/static/js/spawned_hosts.js
- service/spawn.go
JIRA: https://jira.mongodb.org/browse/EVG-7662
If spawning a host in a deleted distro, select some host with a matching alias.
> EVG-7662: select some aliased distro on spawn host UI

- model/project_parser.go
- operations/validate.go
- self-tests.yml
- validator/project_validator.go
- validator/project_validator_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7689
Also removed windows-64-vs2010 since it doesn't exist anymore.
> EVG-7689: ignore variables field in yaml

- scheduler/utilization_based_host_allocator.go
We already figured out the problem but I think this is still helpful
> EVG-7755 add more logging to host allocaator

- cloud/spawn.go
- model/distro/distro.go
- model/host/host_intent.go
- model/host/volume.go
- public/static/js/services/rest.js
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_options.html
- service/spawn.go
- units/provisioning_setup_host.go
Includes a _host_ of other changes (lol), namely a region fix and validation that a specified volume is in the correct region.
> EVG-7429 set unexpirable for workstations

- cloud/ec2.go
- cloud/mock.go
- config.go
- model/host/db.go
- model/host/volume.go
- operations/flags.go
- operations/host_spawn.go
- operations/volume.go
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_options.html
- rest/client/interface.go
- rest/client/mock.go
- rest/client/rest.go
- rest/model/host.go
- rest/route/host_spawn.go
- rest/route/service.go
Also adds host display names to that CLI.
> EVG-7725 add display names to volumes

- public/static/js/projects.js
> EVG-7732 fix js function typo

- public/static/app/perf/perf.js
- public/static/js/filters/filters.common.js
- public/static/js/filters/filters.test.js
in this scenario the the thread # was not in the metadata, but as part of the cedar data
> EVG-7174 better handle missing data in trend charts

- command/s3_pull.go
- command/s3_push.go
- service/templates/task.html
JIRA: https://jira.mongodb.org/browse/EVG-7816
* Retry HTTP requests.
* Drive-by fix for task sync command in UI.
> EVG-7825: retry task sync for temporary failures

- model/event/host_event.go
- units/host_monitoring_external_termination.go
JIRA: https://jira.mongodb.org/browse/EVG-7878
> EVG-7878: improve external termination event log

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/tests/patchTasks/queries/all-params.graphql
- graphql/tests/patchTasks/queries/count.graphql
- graphql/tests/patchTasks/queries/filter-by-bad-task-name.graphql
- graphql/tests/patchTasks/queries/filter-by-bad-variant.graphql
- graphql/tests/patchTasks/queries/filter-by-base-status.graphql
- graphql/tests/patchTasks/queries/filter-by-multiple-statuses.graphql
- graphql/tests/patchTasks/queries/filter-by-status.graphql
- graphql/tests/patchTasks/queries/filter-by-task-name.graphql
- graphql/tests/patchTasks/queries/filter-by-variant-partial-search-term.graphql
- graphql/tests/patchTasks/queries/filter-by-variant.graphql
- graphql/tests/patchTasks/queries/limit-and-pagination-1.graphql
- graphql/tests/patchTasks/queries/limit-and-pagination-2.graphql
- graphql/tests/patchTasks/queries/no-params.graphql
- graphql/tests/patchTasks/queries/sort-base-status-descending.graphql
- graphql/tests/patchTasks/queries/sort-by-base-status.graphql
- graphql/tests/patchTasks/queries/sort-by-name.graphql
- graphql/tests/patchTasks/queries/sort-by-status.graphql
- graphql/tests/patchTasks/queries/sort-by-variant.graphql
- graphql/tests/patchTasks/queries/sort-descending.graphql
- graphql/tests/patchTasks/results.json
- graphql/util.go
- model/task/task.go
- rest/data/interface.go
- rest/data/task.go
Reverts evergreen-ci/evergreen#3502
> Revert "EVG-7737: add filtered task count field to patch tasks query"

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/tests/patchTasks/queries/all-params.graphql
- graphql/tests/patchTasks/queries/count.graphql
- graphql/tests/patchTasks/queries/filter-by-bad-task-name.graphql
- graphql/tests/patchTasks/queries/filter-by-bad-variant.graphql
- graphql/tests/patchTasks/queries/filter-by-base-status.graphql
- graphql/tests/patchTasks/queries/filter-by-multiple-statuses.graphql
- graphql/tests/patchTasks/queries/filter-by-status.graphql
- graphql/tests/patchTasks/queries/filter-by-task-name.graphql
- graphql/tests/patchTasks/queries/filter-by-variant-partial-search-term.graphql
- graphql/tests/patchTasks/queries/filter-by-variant.graphql
- graphql/tests/patchTasks/queries/limit-and-pagination-1.graphql
- graphql/tests/patchTasks/queries/limit-and-pagination-2.graphql
- graphql/tests/patchTasks/queries/no-params.graphql
- graphql/tests/patchTasks/queries/sort-base-status-descending.graphql
- graphql/tests/patchTasks/queries/sort-by-base-status.graphql
- graphql/tests/patchTasks/queries/sort-by-name.graphql
- graphql/tests/patchTasks/queries/sort-by-status.graphql
- graphql/tests/patchTasks/queries/sort-by-variant.graphql
- graphql/tests/patchTasks/queries/sort-descending.graphql
- graphql/tests/patchTasks/results.json
- graphql/util.go
- model/task/task.go
- rest/data/interface.go
- rest/data/task.go
Reverts evergreen-ci/evergreen#3507
> Revert "Revert "EVG-7737: add filtered task count field to patch tasks query""

- cloud/ec2.go
- cloud/ec2_client.go
- cloud/ec2_util.go
- cloud/spawn.go
- model/host/host.go
- public/static/js/directives/directives.spawn.js
- public/static/js/services/rest.js
- public/static/js/spawned_hosts.js
- public/static/partials/user_host_options.html
- public/static/partials/user_volume_options.html
- rest/route/host_spawn.go
- rest/route/host_spawn_test.go
- service/spawn.go
- service/templates/spawned_hosts.html
- service/ui.go
Disables spawn if a volume size is requested that is larger than what the user has left (this change is also added to the host part).
> EVG-7888 add create volume to volume UI

- model/commitqueue/commit_queue_test.go
- model/event/subscriptions.go
- model/event/subscriptions_test.go
- repotracker/repotracker.go
- scripts/indexes.js
- units/commit_queue.go
- units/patch_intent.go
Forthcoming is a migration to delete subscriptions that we think are expired. I'm open to discussing the approach as well
> EVG-7949 TTL subscriptions

- public/static/partials/user_host_options.html
JIRA: https://jira.mongodb.org/browse/EVG-7962
> EVG-7962: hide checkbox if not possible to pull from task sync

- command/scripting.go
- command/scripting_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7969
> EVG-7969: allow scripting harness to run tests

- service/templates/spawned_hosts.html
Start time is already fixed, just fixing uptime.
> EVG-6982 show uptime only if host is started

- units/provisioning_setup_host.go
- units/provisioning_setup_host_test.go
Writing the device name was causing hosts not to boot when the device name changed
> EVG-7946 write UUID to /etc/fstab

- globals.go
- model/project.go
- model/project_aliases.go
- model/project_ref.go
- model/repository.go
- model/user/db.go
- model/version.go
- model/version_db.go
- repotracker/repotracker.go
- repotracker/repotracker_test.go
- rest/data/aliases.go
- rest/data/build.go
- rest/data/build_test.go
- rest/data/interface.go
- rest/data/project.go
- rest/data/user.go
- rest/data/version.go
- rest/data/version_test.go
- rest/model/project_event.go
- rest/route/github.go
- rest/route/version_create.go
- trigger/project_triggers.go
- units/periodic_builds.go
Branched off of https://github.com/evergreen-ci/evergreen/pull/3566 because of shenanigans
> EVG-7623 add git tags to versions from webhook

- cmd/generate-lint/generate-lint.go
- rest/model/codegen.go
- rest/model/codegen_test.go
- rest/model/templates/field.gotmpl
- rest/model/templates/file.gotmpl
- rest/model/templates/struct.gotmpl
- rest/model/testdata/expected/basic.go
- rest/model/testdata/schema/basic.graphql
- self-tests.yml
There's still a lot that this doesn't handle yet, but I wanted to have this be in easily reviewable chunks. This takes a graphQL schema and generates go structs from the GQL types
> EVG-7826 basic code gen functionality

- model/project_event_test.go
- model/project_ref.go
- public/static/js/projects.js
- rest/model/project.go
- rest/route/github.go
- rest/route/project.go
- service/project.go
- service/templates/projects.html
I can't think of a less wordy but still clear version of this variable 🤷 if you have an alternative feel free to suggest.
> EVG-7625 authorize users to create versions from git tags

- units/crons_remote_five_minute.go
(sorry I missed this in the other PR)
> EVG-7934: activate for batch time less aggressively

- makefile
- self-tests.yml
forgot that we need to do some cygwin path stuff in the makefile
> EVG-7826 fix windows tests

- model/project_aliases.go
- model/project_aliases_test.go
- public/static/app/common/tagInput.html
- public/static/app/common/tagInput.js
- public/static/js/projects.js
- rest/model/project_event.go
- service/project.go
- service/templates/projects.html
> EVG-7624 add git tag version aliases to project

- cloud/userdata_test.go
- config_api.go
- environment.go
- globals.go
- makefile
- model/distro/distro.go
- model/host/hostutil_test.go
- public/static/js/distros.js
- rest/route/distro_test.go
- service/distros.go
- service/templates/distros.html
- service/templates/settings.html
- units/provisioning_convert_host_to_new_test.go
- validator/distro_validator_test.go
> EVG-8022 user friendly binary names

- command/attach_artifacts.go
- command/attach_artifacts_test.go
- command/generate.go
- command/s3_put.go
- glide.lock
- util/file.go
- util/file_test.go
- vendor/github.com/evergreen-ci/utility/file.go
- vendor/github.com/evergreen-ci/utility/file_test.go
- vendor/github.com/evergreen-ci/utility/http.go
- vendor/github.com/evergreen-ci/utility/http_test.go
- vendor/github.com/evergreen-ci/utility/network_test.go
- vendor/github.com/evergreen-ci/utility/parsing.go
- vendor/github.com/evergreen-ci/utility/slice.go
- vendor/github.com/evergreen-ci/utility/slice_test.go
JIRA: https://jira.mongodb.org/browse/MAKE-1339
I just moved `BuildFileList` into github.com/evergreen-ci/utility.
> MAKE-1339: use BuildFileList from utility instead of util package

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/tests/userSettings/queries/user-config.graphql
- graphql/tests/userSettings/results.json
Created a query that will get a users config for display in the authentication card of the CLI tab
> EVG-8066 Add User config query

- units/provisioning_create_host.go
- units/provisioning_setup_host.go
JIRA: https://jira.mongodb.org/browse/EVG-8084
* Fix off by one in checking provisioning attempts.
* Also move host.create error to correct file.
> EVG-8084: decommission immediately when setup host job exceeds max attempts

- units/patch_intent_test.go
> EVG-8102 replace tychoish in unit tests

- trigger/host.go
- trigger/host_test.go
This was already done for the termination modal
> EVG-7715 use host display name in notifications

- model/task_lifecycle.go
- model/task_lifecycle_test.go
[EVG-7918](https://jira.mongodb.org/browse/EVG-7918)
> EVG-7918 Blacklist the commit queue's merge task when a task fails

- public/static/app/common/PerformanceAnalysisAndTriageClient.js
- public/static/app/common/constants.js
- public/static/app/perf-bb/ExpandedMetricsSignalProcessingController.js
- public/static/app/perf-bb/ExpandedMetricsSignalProcessingPage.test.js
- public/static/app/perf-bb/change-points-v2.html
@john-m-liu Relating to the questions asked yesterday. It seems this is sufficient to get the page I care about working; wondering whether this can be done in a better way/if we want to use this corpsecure login more generally in EVG?
> EVG-8111 Not authing against corp secure properly when using performance analysis and triage service

- config.go
- model/project.go
- model/project_test.go
- service/templates/projects.html
I thought this was going to be a lot harder whoops
> EVG-7959 add triggered_by_git_tag expansion

- validator/project_validator.go
JIRA: https://jira.mongodb.org/browse/EVG-8192
> EVG-8192: make variables section optional in project yaml validation

- gqlgen.yml
- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
- model/user/user.go
- rest/model/user.go
Didnt add a test for this flag since the functionality is covered under the user-settings tests.
> EVG-8064 add flag to check if user has used spruce before

- public/static/js/spawned_hosts.js
- public/static/partials/user_host_options.html
- public/static/partials/user_volume_details.html
- public/static/partials/user_volume_options.html
If the user was at their volume size limit the volume size would be set to 0. Since the min was set to 1 the form was invalid and the spawn button was disabled. Also the spawn host and create volume forms had the same name so when we checked if "form" was valid we were checking both.
This PR removes the min and validates the size is greater than 0 separately.
Also fixes some spacing issues.
> EVG-7985 volumes at limit

- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
Cant write local tests for this since the aws config isnt available locally
> EVG-7977 Add aws regions query

- public/static/js/build.js
- public/static/js/version.js
the "object" selector actually needs to be 1 level more specific, because we evaluate the triggers at that level
> EVG-6832 fix some build/version notifications

- public/static/partials/user_host_details.html
- public/static/partials/user_volume_details.html
It's confusing when the message gets split up
> EVG-8044 set nowrap

- public/static/js/projects.js
- rest/route/service.go
- service/middleware.go
- service/project.go
- service/templates/projects.html
[EVG-8042](https://jira.mongodb.org/browse/EVG-8042)
> EVG-8042 Remove the "not admin" error from the project when the user has project view permission

- glide.lock
- vendor/github.com/evergreen-ci/gimlet/CODEOWNERS
- vendor/github.com/evergreen-ci/gimlet/middleware_grip.go
- vendor/github.com/evergreen-ci/gimlet/middleware_grip_test.go
Get changes from https://github.com/evergreen-ci/gimlet/pull/81
> EVG-8182 revendor gimlet

- cloud/docker_client.go
- cloud/docker_test.go
- model/host/host.go
Since this is user specified, I don't think it needs to be added to host.list
> EVG-8134 add ExtraHosts to docker host.create

- makefile
JIRA: https://jira.mongodb.org/browse/MAKE-1363
> MAKE-1363: add retries when curling golangci-lint

- graphql/resolvers.go
- graphql/util.go
- model/commitqueue/commit_queue.go
- model/commitqueue/commit_queue_test.go
- model/event/task_event.go
- model/task_lifecycle.go
- public/static/partials/taskevent.html
- rest/data/commit_queue.go
- rest/data/commit_queue_test.go
- rest/data/interface.go
- rest/route/commit_queue.go
- rest/route/commit_queue_test.go
- rest/route/github.go
- service/build.go
- service/task.go
[EVG-8099](https://jira.mongodb.org/browse/EVG-8099)
> EVG-8099 Evergreen Improve event log for deleted commit queue item

- graphql/resolvers.go
- graphql/util.go
Colors are still off but this gets the correct status now
> EVG-8174 fix more display statuses in spruce

- cloud/cloud.go
- model/distro/db.go
- model/host/host_intent.go
- units/host_allocator.go
The problem with staging is that we were hitting the error at line 231 and never creating hosts.
> EVG-7767 consider multiple regions for non-spawn hosts

- command/scripting.go
JIRA: https://jira.mongodb.org/browse/EVG-9690
> EVG-9690: only set working directory if not explicitly populated

- command/host_create.go
Also snuck in a bit of a refactor
> EVG-8108 create files using O_APPEND for log files

- config.go
- operations/admin.go
- operations/host.go
- operations/host_spawn.go
My only open question is if the key flag should also accept "-i" (because that's what the actual ssh flag is called so maybe what people would expect) or if we want to stick to Evergreen conventions, what do you think @ybrill?
> EVG-8299 wrap ssh command for hosts

- testdata/local/project_aliases.json
I left this file out of #3746 by mistake 😞
> EVG-7952 include missing file

- operations/host_spawn_test.go
JIRA: https://jira.mongodb.org/browse/EVG-9708
The test failures were due to cygwin paths being relied upon for invoking cygwin's rsync.
> EVG-9708: fix Windows host rsync tests

- scheduler/scheduler.go
- scheduler/task_finder_test.go
- scheduler/task_prioritizer.go
- scheduler/utilization_based_host_allocator.go
- scheduler/wrapper.go
JIRA: https://jira.mongodb.org/browse/EVG-7565
Reduce the amount of unnecessary logging in the scheduler. I kept most of the logs that log stats (e.g. number of hosts requested).
> EVG-7565: reduce scheduler logging noise

- validator/project_validator.go
- validator/project_validator_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7749
Check that dependencies defined at task level that specify a buildvariant refer to a valid buildvariant.
> EVG-7749: check variant exists for task dependency

- model/lifecycle.go
- model/task_lifecycle.go
- service/api_task.go
I'm pretty sure the issue is in UpdateDisplayTask but I'm unable to reason about it. This doesn't happen too infrequently though so hopefully some additional logging will give me a clue.
Also includes some unrelated nil checks.
> EVG-7769 add logs for multiple TASK_FINISHED events for display tasks

- validator/project_validator.go
- validator/project_validator_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7762
Don't allow both `patch_only: true` and `patchable: false` on tasks.
> EVG-7762: check that tasks are not both unpatchable and patch-only

- command/attach_artifacts.go
- command/generate.go
- command/s3_put.go
- glide.lock
- vendor/github.com/evergreen-ci/utility/file.go
- vendor/github.com/evergreen-ci/utility/file_test.go
- vendor/github.com/evergreen-ci/utility/io.go
- vendor/github.com/mongodb/jasper/cli/generate.go
- vendor/github.com/mongodb/jasper/glide.lock
- vendor/github.com/mongodb/jasper/metabuild/generator/golang.go
- vendor/github.com/mongodb/jasper/metabuild/generator/golang_test.go
- vendor/github.com/mongodb/jasper/metabuild/generator/make.go
- vendor/github.com/mongodb/jasper/metabuild/model/util.go
- vendor/github.com/mongodb/jasper/process_test.go
- vendor/github.com/mongodb/jasper/remote/process_test.go
JIRA: https://jira.mongodb.org/browse/EVG-8930
Revendor utility to 8a885e291da3d271f58d396ee2b313ab1aec21a8 and fix `BuildFileList()`.
> EVG-8930: revendor utility

- config.go
- operations/service_web.go
JIRA: https://jira.mongodb.org/browse/EVG-8311
> EVG-8311: remove debug logs

- config_test/evg_settings.yml
- config_test/evg_settings_with_3rd_party_defaults.yml
- docs/evg_example_config.yml
- environment_test.go
- operations/model_admin.go
- operations/service_deploy_smoke.go
- scripts/setup-credentials.sh
- testdata/smoke_config.yml
see https://jira.mongodb.org/browse/EVG-12468
> EVG-12468: 8080 - > 9090 port change

- config_test/evg_settings.yml
- config_test/evg_settings_with_3rd_party_defaults.yml
- docs/evg_example_config.yml
- environment_test.go
- operations/model_admin.go
- operations/service_deploy_smoke.go
- scripts/setup-credentials.sh
- testdata/smoke_config.yml
Reverts evergreen-ci/evergreen#3785
> Revert "EVG-12468: 8080 - > 9090 port change"

- globals.go
- model/generate.go
- repotracker/repotracker.go
This turned out to be pretty simple--missed the git tag requester in a spot.
> EVG-12478 ignore batchtime for git tag requester

- service/task.go
There is some old code that seems to allow non-users to view task logs; however newer functions don't allow this and doesn't really make sense with how permissions are given now, so non-users should just be given an Unauthorized user.
I moved things around a little bit while doing this to make it a bit more readable also.
> EVG-12479 authenticate users for all logs

- validator/project_validator.go
- validator/project_validator_test.go
JIRA: https://jira.mongodb.org/browse/EVG-7752
> EVG-7752: do not allow task groups to be defined multiple times

- cmd/scrambled-eggs/scramble.py
- makefile
run it like `make scramble file=cmd/scrambled-eggs/test.json`
This isn't written in go because I need loose type rules. This isn't written in js/ts because I don't want to introduce a nodejs dependency
> EVG-12614 script to sanitize json

- config.go
- config_db.go
- config_test.go
- graphql/tests/siteBanner/data.json
- rest/model/admin.go
- rest/route/admin_settings.go
- rest/route/service.go
- service/templates/admin.html
- service/templates/base_angular.html
- service/ui.go
- testutil/config.go
https://jira.mongodb.org/browse/EVG-9741
These code changes remove Bugsnag from the legacy UI and Evergreen
> EVG-9741: Remove Bugsnag from the legacy UI

- model/event/subscribers.go
- model/notification/notification.go
- public/static/js/subscriptions.js
- public/static/partials/subscription_modal.html
- rest/model/subscriber.go
- rest/model/subscriber_test.go
Alignment is a bit off but I decided to not mess with css since this is in the new UI anyway
> EVG-12471 allow specifying headers for webhook subscriptions

- model/task_queue_service_dependency.go
John removed the log line that was being spammed in [EVG-7592](https://jira.mongodb.org/browse/EVG-7952) (although I think this is the more relevant ticket). This log was being hit even in cases where we don't expect the dependency to exist; instead, we should only log (and also error!) in the case that we DO expect the dependency.
I also removed another debugging line that's hit frequently on success (albeit way less frequently).
> EVG-12635 improve logging logic for new dispatcher

- graphql/tests/host/queries/hostMetadata-no-running-task.graphql
- graphql/tests/host/queries/hostMetadata-running-task.graphql
- graphql/tests/host/results.json
[EVG-12723](https://jira.mongodb.org/browse/EVG-12723)
> EVG-12723  Evergreen Add Provider to Host Test Query

- graphql/generated.go
- graphql/schema.graphql
- graphql/tests/host/queries/hostMetadata-no-running-task.graphql
- graphql/tests/host/queries/hostMetadata-running-task.graphql
- graphql/tests/host/results.json
[EVG-12730](https://jira.mongodb.org/browse/EVG-12730)
Spruce part: https://github.com/evergreen-ci/spruce/pull/330
> EVG-12730 Host Events Query

- graphql/util.go
- model/task/db.go
- rest/data/test.go
somewhat of a drive-by fix of additional places that aren't looking up old tasks correctly
> EVG-8304 look up old tasks in more places

- command/host_list.go
> EVG-12631: allow listed hosts to be greater than or equal to user-defined num_hosts for host.list

- rest/model/task.go
This ticket was to add AMI to the task API but it looks like this was already done :) just a tweak to make sure the json tag is used in the result, and to only look up the host if there's a host ID.
> EVG-12654 tweak how AMI is returned from task API

- command/archive_tarball_create.go
- util/artifacts_tar.go
We talked about handling a retry in the panic handler, but I feel it may make more sense to do it here since all potential panics route here, and I've seen errors handled here elsewhere. This is technically recursive though and I don't know if this is too jank? So let me know what you think, this is probably a WIP.
> EVG-12609 retry on panic in archive.targz_pack

- glide.lock
- vendor/github.com/mongodb/grip/message/generic.go
- vendor/github.com/mongodb/grip/send/generic.go
Revendor grip to include the changes from https://github.com/mongodb/grip/pull/81
I intend to **skip review**. (I just want a record of the patch passing)
> EVG-7251 revendor grip

- repotracker/repotracker.go
This will be removed after I find out what's going on with mongo tool's project. Since most of this logging is contingent on it being a git tag version, the logging will be infrequent.
> EVG-12777 add logging for git tag triggered versions

- model/notification/notification.go
- rest/model/codegen.go
- rest/model/codegen_test.go
This fixes compile as well as adds an unrelated log line to help with debugging something DAG is doing
> EVG-12402 fix compile, add logging

- operations/model.go
The last version of this broke things because apparently the check was being called even for commands that didn't rely on the config file, and then errored. This new check just warns the user if there's a problem at the time of choosing a config file, but doesn't error if it can fall back on a default.
> EVG-9701 warn user when given config file doesn't exist

- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
- model/notification/notification.go
- model/task/task.go
- model/task/task_test.go
- add a query to retrieve data from every execution for a given task
- add a field to the task type that holds its latest execution
> EVG-8304 add more execution queries

- graphql/generated.go
- graphql/schema.graphql
this PR includes code changes from `make gqlgen` with the current gql schema
> EVG-12822: run make gqlgen

- units/host_setup_script.go
- units/util.go
JIRA: https://jira.mongodb.org/browse/EVG-12829
Use the correct home directory depending on the host's distro.
> EVG-12829: use correct home directory for host setup script

- model/task/task.go
I'm not totally sure what's gone wrong in this case: my prevalent theory is that the first attempt to restart failed after the point of archiving, and then after that we hit duplicate key errors when we try to insert into the old tasks collection. I'm not sure that's true though and I'm not sure really what to do with that besides introducing a transaction (oof) so for now just adding some logging so we better understand the problem if we see it again.
> EVG-12422 add logging to task archive

- validator/project_validator.go
JIRA: https://jira.mongodb.org/browse/EVG-12848
> EVG-12848: fix string formatting in project validator

- trigger/host.go
- trigger/host_test.go
- trigger/volume.go
- trigger/volume_test.go
- format the expiration time and localize the time zone
- link to the host/volume page with the host/volume selected
> EVG-8041 host/volume expiration reminder improvements

- agent/background_test.go
The heartbeat tests have been flaky recently. I think the reason is we're not taking into account the overhead in starting the `startHeartbeat` goroutine, starting the timer, the heartbeat select statement waking up, etc.
I've increased the timeout to one second to account for overhead.
> EVG-12843 use larger timeouts

- model/patch/patch.go
- model/patch_lifecycle.go
- model/patch_lifecycle_test.go
- model/project.go
- model/project_parser.go
- model/project_parser_db.go
- model/project_parser_test.go
- model/version.go
- rest/model/patch.go
- rest/model/version.go
- trigger/payloads_test.go
- units/patch_intent.go
- validator/project_validator.go
- validator/project_validator_test.go
The pieces of this project are pretty split up, so this ticket just adds the concept of the parameter/puts defaults in the patch/version. Future tickets will add parameters as actual expansions, and allow for user-defined parameters.
> EVG-12876 allow default parameters for project configs

- model/distro/distro.go
- model/distro/distro_test.go
- model/event/distro_event_test.go
- model/lifecycle_test.go
- model/patch_lifecycle_test.go
- model/project_test.go
- rest/data/host_create_test.go
- service/spawn.go
- service/task.go
Parts of this will be removed in https://jira.mongodb.org/browse/EVG-12964.
> EVG-12807 disallow spawning with unfinished region configuration

- repotracker/repotracker.go
I looked through the logs at the time of when we hit the lock timeout for an extended period of time and didn't see any commands that Max recommended to check, and couldn't figure out what else could be holding a lock. It actually happened again this morning, so it isn't related to the initial syncs we were doing last month. Given that we already retry on all errors, I'm  just adding some backoff so that we're (hopefully) less likely to use up all the retries
> EVG-12814 add backoff in repotracker transaction

- config.go
- operations/list.go
- rest/client/interface.go
- rest/client/mock.go
- rest/client/rest.go
- rest/model/project.go
- rest/route/project.go
- rest/route/service.go
Output example:
```
Name      Default       Description
----      -------       -----------
my_param  hello world!  something to test parameters
```
> EVG-12882 list parameters

- rest/model/host.go
this pr adds a quotation mark missing from the original EVG-12960 PR (https://github.com/evergreen-ci/evergreen/pull/3980)
> EVG-12960: add missing quotation mark

- rest/route/host.go
For simplicity/consistency I decided not to mess with the default new expiration time after setting not unexpirable.
> EVG-12852 modify expiration when offboarding users

- config.go
- model/patch/cli_intent.go
- model/patch/intent.go
- operations/flags.go
- operations/http.go
- operations/model.go
- operations/patch.go
- operations/patch_util.go
- service/api_patch.go
This ticket was originally just to add parameters to the default config, but the two are pretty mixed together so. Tested by creating patches with parameters from different sources.
> EVG-12878 accept parameters from the CLI

- graphql/generated.go
- graphql/schema.graphql
- graphql/tests/spruceConfig/data.json
- graphql/tests/spruceConfig/queries/banner.graphql
- graphql/tests/spruceConfig/queries/uservoice.graphql
- graphql/tests/spruceConfig/results.json
- rest/model/admin.go
- service/templates/admin.html
Fix a typo in the uservoice resolver that caused it to not return the uservoice field
> EVG-12929 Fix typo in uservoice resolver

- graphql/generated.go
- graphql/models_gen.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/ui_plugin_build_baron.go
- service/ui_plugin_build_baron.go
This is the backend part of the ticket.
> EVG-12988  bb Jira URL should be queried from the db since it is configurable

- model/lifecycle.go
- model/project.go
- model/project_parser.go
- model/project_parser_test.go
- model/project_test.go
- validator/project_validator.go
- validator/project_validator_test.go
like patchable: false but "git-taggable: false" (i didn't like git taggable though)
> EVG-12903 allow task to be not reachable for git tag builds

- gqlgen.yml
- graphql/generated.go
- graphql/schema.graphql
- graphql/tests/task/data.json
- graphql/tests/task/queries/oom-tracker.graphql
- graphql/tests/task/results.json
This is the backend part of the ticket.
> EVG-8050 Evergreen Add OOM Tracker info to the new task page

- rest/model/templates/service_methods.gotmpl
- rest/model/testdata/expected/aliases.go
- rest/model/testdata/expected/array_object.go
- rest/model/testdata/expected/array_scalar.go
- rest/model/testdata/expected/basic.go
- rest/model/testdata/expected/object_embedded.go
- rest/model/testdata/expected/object_simple.go
- rest/model/testdata/expected/scalars.go
- rest/model/testdata/expected/thirdparty.go
- rest/model/testdata/expected/type_alias.go
- rest/model/testdata/expected/types.go
My original intent was to generate something robust that you might see on godoc, but since these are only used internally that's overkill, so I added a short comment to the BuildFromService/ToService functions. Even that might be overkill, let me know what you think
> EVG-8095 generate function comment

- rest/model/build.go
- rest/model/generated.go
- rest/model/schema/rest_model.graphql
- rest/model/schema/type_mapping.yml
- rest/model/task.go
- rest/route/project.go
There aren't any real changes, I just did EVG-12453 using the model generator and route snippet
> EVG-12620 redo EVG-12453 with generators

- public/static/js/projects.js
- service/templates/projects.html
Broke up the git tag description in an attempt to be more clear? Open to suggestions about this help text if something else seems better.
> EVG-12902 git tag project page clarifications

- graphql/resolvers.go
- graphql/tests/patchBuildVariants/data.json
- graphql/tests/patchBuildVariants/results.json
https://jira.mongodb.org/browse/EVG-13114
> EVG-13114: sort task square groups by build variant display name

- command/results_xunit.go
- command/results_xunit_parser.go
- command/results_xunit_parser_test.go
- command/testdata/xunit/junit_6.xml
This pr adds a recursive field to the test suite struct which allows deserializing embedded suites, and also will attach results for those in the same way
> EVG-12951 handle embedded junit test suites

- rest/route/distro.go
I think some distro is already wrong and we aren't able to update any of them because of that? Not totally sure but the logging should help.
> EVG-13128 check validation of original distro in modify settings route

- rest/route/patch.go
- rest/route/patch_test.go
A blank description in the request description will now leave the description unchanged. Also using * in the list of tasks will schedule all tasks in that variant
> EVG-13125 fix description in patch configure route, support *

- model/build_variant_history_test.go
- model/generate.go
- model/lifecycle.go
- model/lifecycle_test.go
- model/patch_lifecycle.go
- model/project.go
- model/project_parser.go
- model/project_parser_test.go
- model/project_ref.go
- model/project_ref_test.go
- model/scratch_test.go
- model/task/db.go
- model/task/task.go
- model/task_lifecycle.go
- model/version.go
- model/version_activation.go
- model/version_db.go
- model/version_test.go
- repotracker/repotracker.go
- repotracker/repotracker_test.go
- service/rest_version_test.go
- validator/project_validator.go
- validator/project_validator_test.go
I accidentally deleted some of my changes to generate tasks for this, alas, but decided to split that into another ticket (or maybe not do?), i.e. generated tasks cannot have their own batchtime yet.
Buildvariants and tasks cannot both define batchtime. I think that simplifies things.
> EVG-6586 allow batchtime for tasks

- graphql/generated.go
- graphql/schema.graphql
- graphql/tests/task/queries/hostLink-null.graphql
- graphql/tests/task/queries/hostLink.graphql
- graphql/tests/task/results.json
- rest/model/task.go
After redirecting the host link to the spruce host page, we no longer need the hostLink.
> EVG-13017 Evergreen Redirect the link to a host to Spruce

- cloud/ec2.go
- cloud/ec2_fleet.go
- cloud/ec2_util.go
JIRA: https://jira.mongodb.org/browse/EVG-13214
The request to create the host will fail when the user data size is greater than 16kB.
> EVG-13214:  log when user data size limit is exceeded

- model/generate.go
- model/generate_test.go
- model/lifecycle.go
- model/lifecycle_test.go
- model/patch_lifecycle.go
- model/project.go
- model/project_ref.go
- repotracker/repotracker.go
I switched this to pass around BatchTimeTasks, rather than tasks/variants to activate, because it made way more sense to reason about.
> EVG-13195 consider batchtime for generated task

- command/results_utils.go
- command/results_utils_test.go
- glide.lock
- vendor/github.com/evergreen-ci/timber/buildlogger/basic_sender_test.go
- vendor/github.com/evergreen-ci/timber/testutil/server.go
JIRA: https://jira.mongodb.org/browse/EVG-13130
- revendor timber
- add tests 
- fix spacing bug with grip composer
> EVG-13130: add tests for for buildlogger sender with timber mock sender

- command/s3_put.go
- config.go
JIRA: https://jira.mongodb.org/browse/EVG-13224
I also removed the link because unless it's public read, you probably won't be able to click it.
> EVG-13224: include local file being uploaded in task log

- config.go
- operations/commit_queue.go
I don't think either function should log an error, since if the project/patch is required it will error later on anyway, and it's a bit more confusing that way.
> EVG-13219 use correct cq message function

- graphql/resolvers.go
https://jira.mongodb.org/browse/EVG-13288
The original volume variable was lacking an id field which resulted in a "Document not found" error when attempting to modify the volume. Instead we should be using the volume variable returned from ec2Manager.CreateVolume
> EVG-13288: Unable to set expiration when creating a volume via SpawnVolume mutation

- globals.go
- model/build/build_test.go
- model/patch_lifecycle_test.go
- model/project.go
I'll hold off on merging this until I've finished making sure no one's relying on it.
> EVG-13242 remove push special case

- public/static/app/common/PointsDataService.js
- public/static/app/common/PointsDataService.test.js
- public/static/app/perf/perf.js
- public/static/app/perf/perf.test.js
Including a date range in the queries reduce the load on the database.
> EVG-13327 Update trend charts to limit queries to the visible range of data.

- agent/command/archive_tarball_create_test.go
JIRA: https://jira.mongodb.org/browse/EVG-13241
Fix the agent command tests on Windows because Cygwin's `tar` command requires Unix-style paths.
> EVG-13241: use cygpath to handle Cygwin tar command on Windows

- model/task_annotations/db.go
- model/task_annotations/task_annotations.go
- rest/model/task_annotations.go
[EVG-13333](https://jira.mongodb.org/browse/EVG-13333)
> EVG-13333 Accommodate Design Update to Task Annotation

- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/tests/clearMySubscriptions/data.json
- graphql/tests/clearMySubscriptions/queries/success.graphql
- graphql/tests/clearMySubscriptions/results.json
https://jira.mongodb.org/browse/EVG-13360
this mutation will be used in the Notifications tab on the preferences page. The return value is the number of subscriptions removed.
> EVG-13360: clearMySubscriptions mutation

- model/host/hostutil.go
- units/host_setup_script.go
I think it's better that this take longer than fail frequently (it seems like it can finish all the retries within a minute which is probably too fast) so I've upped some of the numbers, and also added logging so the user knows that time is the issue (it'll be less frustrating for them and easier for us to address).
> EVG-13348 improve host script handling

- graphql/resolvers.go
- graphql/ui_plugin_build_baron.go
- plugin/build_baron.go
- public/static/plugins/buildbaron/js/task_build_baron.js
- service/ui_plugin_build_baron.go
[EVG-13363](https://jira.mongodb.org/browse/EVG-13363)
> EVG-13363 Reconfigure the isBuildBaron check to use TicketSearchProjects instead

- graphql/generated.go
- graphql/schema.graphql
This should resolve the issue where the my volumes query errors out when this field isn't supplied
> EVG-13393 make creation time not nullable

- rest/data/host.go
- rest/route/middleware.go
https://jira.mongodb.org/browse/EVG-13398
Also fix a misspelling.
> EVG-13398: return after error cases in task host middleware

- model/commitqueue/github_merge_generic.go
passing overrides in the merge comment will still override
> EVG-13067 merge with default message for merge commits in cq

- model/distro/distro.go
- rest/model/distro.go
- rest/model/distro_test.go
- rest/route/distro_test.go
- service/templates/distros.html
JIRA: https://jira.mongodb.org/browse/EVG-13285
Create distro setting to enable fetching host provisioning script from the app server instead of putting it in user data. This flag will be used later once the host provisioning code is modified.
> EVG-13285: add distro setting to request user data script from the app server

- cloud/userdata.go
- cloud/userdata_test.go
- environment.go
- mock/environment.go
- model/host/host_test.go
- model/host/hostutil.go
- model/host/hostutil_test.go
- rest/data/host.go
JIRA: https://jira.mongodb.org/browse/EVG-13283
* Add user data script to fetch and execute the host provisioning script within user data.
* Save credentials within REST route that fetches host provisioning script.
* Do some minor updates on test/mock environment infrastructure.
> EVG-13281: request host provisioning script from user data

- agent/command/s3_put.go
- config.go
JIRA: https://jira.mongodb.org/browse/EVG-13326
> EVG-13326: show S3 URL if visibility is unspecified

- service/build.go
oops had the wrong thing selected for the filter
> EVG-12484 redirect build page to correct filter in prs

- agent/task.go
- apimodels/agent_models.go
- config.go
- service/api.go
Turns out nobody is even using this yet 🤦‍♀️
> EVG-13361 set restricted expansions for agent

- cloud/userdata.go
- cloud/userdata_test.go
- model/distro/distro.go
- model/host/hostutil.go
- model/host/hostutil_test.go
- rest/client/mock.go
- rest/data/host.go
- rest/data/host_test.go
- rest/data/interface.go
- rest/model/distro.go
- rest/model/distro_test.go
- rest/model/host.go
- rest/route/distro_test.go
- rest/route/host.go
- rest/route/host_test.go
- service/templates/distros.html
- units/provisioning_user_data_done.go
- units/provisioning_user_data_done_test.go
JIRA: https://jira.mongodb.org/browse/EVG-13427
https://jira.mongodb.org/browse/EVG-13479
This is the exact same as the original PR, but in the old one, I accidentally wrote the setup script to the host provisioning script twice, which caused it to fail since the setup script is non-idempotent.
> EVG-13427, EVG-13479: do not write the setup script twice

- graphql/generated.go
- graphql/schema.graphql
This updates the type for InstanceTag to more closely resemble the underlying struct
> EVG-13517 Make InstanceTag fields non nullable

- units/provisioning_agent_monitor_deploy.go
JIRA: https://jira.mongodb.org/browse/EVG-13590
> EVG-13590: skip running the setup script command if the setup script is empty

- graphql/generated.go
- graphql/models_gen.go
- graphql/schema.graphql
- graphql/tests/patchTasks/data.json
- graphql/tests/patchTasks/queries/execution-tasks.graphql
- graphql/tests/patchTasks/results.json
- graphql/util.go
- model/task/db.go
- model/task/task.go
- rest/model/task.go
the name of the new field is kind of a mouthful, I can change it if you have a suggestion
> EVG-13617 better handling of execution tasks in patch query

- validator/project_validator.go
- validator/project_validator_test.go
[[Jira Ticket](https://jira.mongodb.org/browse/EVG-13441)]
> EVG-13441 Validate project modules set branch field

- config_db.go
- config_serviceflags.go
- rest/model/admin.go
- service/templates/admin.html
- units/crons.go
I'll make another ticket to remove the poller altogether if we haven't heard of any issues in say a month or two.
> EVG-13594 add service flag for github repo poller

- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
[Spruce PR ](https://github.com/evergreen-ci/spruce/pull/562)
> EVG-13170 Add userModifyPermission to Annotation

- units/github_status_api.go
- units/patch_intent.go
> EVG-12725 Report project failing validation as a PR status

- model/project_ref.go
- model/project_ref_test.go
- util/reflect.go
Adapted reflect's IsZero since we can't use it (also thought of a test case I wanted to verify)
> EVG-13470 remove reflect.IsZero

- gqlgen.yml
- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
Combined with the [Spruce PR](https://github.com/evergreen-ci/spruce/pull/595)
> EVG-13167 move annotation permission to task

- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
- model/commitqueue/commit_queue.go
- model/commitqueue/commit_queue_test.go
- model/patch_lifecycle.go
- model/patch_lifecycle_test.go
- model/task_lifecycle_test.go
- model/version.go
- model/version_test.go
- operations/commit_queue.go
- operations/commit_queue_test.go
- rest/data/commit_queue_test.go
- rest/model/commit_queue.go
- rest/route/admin_test.go
- rest/route/commit_queue.go
- rest/route/commit_queue_test.go
- rest/route/github.go
- rest/route/middleware.go
- rest/route/middleware_test.go
- units/commit_queue.go
The only change is to keep checking the project ref setting in the job
> EVG-13725 track cq source in individual items

- rest/route/project.go
- rest/route/project_test.go
I forgot to actually do this 🤦‍♀️
> EVG-13273 remove todo

- model/project_ref.go
- model/project_ref_test.go
- rest/data/project_test.go
Recently fixed this for PRs but forgot commit queues.
> EVG-13273 filter out disabled projects for validation

- model/task/db.go
- model/task/task.go
- model/task/task_test.go
- self-tests.yml
Reverts evergreen-ci/evergreen#4321
> Revert "EVG-13502:write if this is the first time calculating DependenciesMetTime"

- rest/route/aws.go
- rest/route/aws_test.go
JIRA: https://jira.mongodb.org/browse/EVG-13877
If we receive an AWS SNS notification that an agent host is stopped, initiate a status check on the cloud instance.
> EVG-13877: handle stopped agent hosts in AWS SNS notifications

- service/templates/host.html
JIRA: https://jira.mongodb.org/browse/EVG-13833
> EVG-13833: include SSH port number on host page

- rest/route/service.go
- rest/route/stats.go
JIRA: https://jira.mongodb.org/browse/EVG-7778
> EVG-7778: Change REST routes to passthrough to equivalent cedar REST endpoint

- service/api_task.go
I didn't realize we [set next task](https://github.com/evergreen-ci/evergreen/blob/6fe7ded1777f2f6e65069c4134bf6422ed8e5815/service/api_task.go#L518) for a host in the DB before we do the debugging logic, so minTaskGroupOrderNum is set to the next task's order number, so the new logic never gets hit. Since it only pertains to single-host task groups, it makes sense to move up to the first if statement.
> EVG-13555 reorganize task group race logic

- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/tests/host/data.json
- graphql/tests/host/queries/homeVolume-empty.graphql
- graphql/tests/host/queries/homeVolume.graphql
- graphql/tests/host/results.json
- graphql/tests/myVolumes/data.json
- graphql/tests/myVolumes/queries/myVolumes.graphql
- graphql/tests/myVolumes/results.json
https://jira.mongodb.org/browse/EVG-13373
this will help us display a host's home volume display name in the UI if it exists
> EVG-13373: Host homeVolume field & Volume uiDisplayName field

- graphql/resolvers.go
Looks like the abortinfo task id field doesn't get populated when a user manually aborts a task. So we shouldn't try to populate the other fields that depend on it.
> EVG-8229 Dont try to search for non existent abortinfo tasks

- config_commitqueue.go
- rest/model/admin.go
- service/templates/admin.html
this just adds a setting that isn't used anywhere yet
> EVG-13796 add commit queue batch size setting

- service/api_task.go
it's probably not surprising that assigning the next task takes the longest. This moves the logging into there
> EVG-13904 more next_task logging

- service/project.go
> EVG-14137 fix workstation config typo

- apimodels/task_log.go
- public/static/js/task.js
- service/task.go
JIRA: https://jira.mongodb.org/browse/EVG-14225
> EVG-14225: Fix raw test result log route

- graphql/generated.go
- graphql/integration_spec.json
- graphql/models_gen.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/testdata/projects1.graphql
After allot of trial and error with the ProjectSelect component i realized the structure we were using didn't work as well as just adding an isFavorite field to the Individual projects
> EVG-13860 Restructure groupings of projects

- graphql/integration_spec.json
- graphql/util.go
- graphql/util_test.go
- rest/data/test.go
- rest/model/test.go
- rest/route/service_test.go
- rest/route/test.go
JIRA: https://jira.mongodb.org/browse/EVG-14201
> EVG-14201: update /rest/v2/tasks/{task_id}/tests to fetch from cedar

- agent/internal/client/methods.go
JIRA: https://jira.mongodb.org/browse/EVG-14157
> EVG-14157: fix agent client communicator route

- graphql/generated.go
- graphql/schema.graphql
- graphql/tests/taskTests/data.json
- graphql/tests/taskTests/queries/execution-task-group-id.graphql
- graphql/tests/taskTests/queries/lineNum.graphql
- graphql/tests/taskTests/results.json
- rest/model/test.go
https://jira.mongodb.org/browse/EVG-14222
This field is necessary for spruce to generate the test result link to lobster
> EVG-14222: Add lineNum field to TestResult gql type

- agent/agent.go
- agent/agent_test.go
- apimodels/agent_models.go
- config.go
JIRA: https://jira.mongodb.org/browse/EVG-14061
> EVG-14061: Make it apparent when a task can't set up the logger

- model/project_ref.go
- public/static/js/projects.js
- service/project.go
- service/templates/projects.html
- units/patch_intent.go
> EVG-13981 Choose trigger aliases for PRs

- model/task_history.go
- service/task_history.go
Only review the second commit -- apparently ReplaceAll is too new
> EVG-14263 use mongo driver for test_names aggregation

- model/task_lifecycle.go
- units/commit_queue.go
sorry just a couple more fixes
> EVG-14314 more commit queue fixes

- apimodels/task_log.go
JIRA: https://jira.mongodb.org/browse/EVG-13831
> EVG-13831: Remove legacy buildlogger task log fetching code

- service/middleware.go
- vendor/github.com/evergreen-ci/gimlet/middleware_auth.go
the actual route takes on the scale of 50 ms, so the performance problem has to be in the middleware
> EVG-14261 more instrumentation

- trigger/patch.go
- units/patch_intent.go
https://github.com/evergreen-ci/commit-queue-sandbox/pull/83
> EVG-13071: GitHub statuses for downstream patches

- self-tests.yml
JIRA: https://jira.mongodb.org/browse/EVG-14352
> EVG-14352: run tests on newer Windows distro

- globals.go
- graphql/tests/restartTask/data.json
- model/build/build.go
- model/build/db.go
- model/lifecycle.go
- model/patch/patch.go
- model/task_lifecycle.go
- model/task_lifecycle_test.go
- model/version.go
- service/api_task.go
- units/task_monitor_execution_timeout.go
- units/task_monitor_execution_timeout_test.go
Reverts evergreen-ci/evergreen#4529 due to model test failures
> Revert "EVG-12953: UpdateBuildAndVersionStatusForTask reorg"

- model/task_queue_service.go
- model/task_queue_service_dependency.go
- service/api_task.go
Taking a page from your playbook to narrow this down a bit.
> EVG-14148 add logging for RefreshFindNextTask

- model/project.go
- model/project_test.go
- validator/project_validator.go
- validator/project_validator_test.go
the behavior is arguably correct, so this just adds a warning that there might be weird behavior
> EVG-13355 add validation for depending on a patch_only task

- glide.lock
- vendor/github.com/evergreen-ci/certdepot/.golangci.yml
- vendor/github.com/evergreen-ci/certdepot/bootstrap.go
- vendor/github.com/evergreen-ci/certdepot/bootstrap_test.go
- vendor/github.com/evergreen-ci/certdepot/cert.go
- vendor/github.com/evergreen-ci/certdepot/cert_test.go
- vendor/github.com/evergreen-ci/certdepot/cmd/run-linter/run-linter.go
- vendor/github.com/evergreen-ci/certdepot/depot_test.go
- vendor/github.com/evergreen-ci/certdepot/evergreen.yaml
- vendor/github.com/evergreen-ci/certdepot/file.go
- vendor/github.com/evergreen-ci/certdepot/interface.go
- vendor/github.com/evergreen-ci/certdepot/mgo_depot.go
- vendor/github.com/evergreen-ci/certdepot/mongodb_depot.go
- vendor/github.com/evergreen-ci/certdepot/pkix.go
- vendor/github.com/evergreen-ci/certdepot/superset.go
JIRA: https://jira.mongodb.org/browse/EVG-14382
> EVG-14382: revendor certdepot

- model/generate.go
I'm not sure if this will solve the whole ticket, but it will fix there being multiple display tasks named "generator_tasks". I might re-create David's patch to see how much this fixes things after this is merged.
> EVG-14249 check for existing display task when generating project

- self-tests.yml
JIRA: https://jira.mongodb.org/browse/EVG-14486
> EVG-14486: use archlinux-new distros in CI tests

- agent/internal/client/client.go
JIRA: https://jira.mongodb.org/browse/EVG-14514
> EVG-14514: Use a separate HTTP client for the cedar gRPC client connection

- glide.lock
- units/stats_amboy.go
- vendor/github.com/mongodb/amboy/cli/queue_management.go
- vendor/github.com/mongodb/amboy/evergreen.yaml
- vendor/github.com/mongodb/amboy/management/filter_test.go
- vendor/github.com/mongodb/amboy/management/interface.go
- vendor/github.com/mongodb/amboy/management/management_test.go
- vendor/github.com/mongodb/amboy/management/mongodb.go
- vendor/github.com/mongodb/amboy/management/output.go
- vendor/github.com/mongodb/amboy/management/queue.go
- vendor/github.com/mongodb/amboy/pool/abortable.go
- vendor/github.com/mongodb/amboy/pool/helpers.go
- vendor/github.com/mongodb/amboy/pool/rate_limiting.go
- vendor/github.com/mongodb/amboy/queue/dispatcher_test.go
- vendor/github.com/mongodb/amboy/queue/ordered.go
- vendor/github.com/mongodb/amboy/rest/client_management.go
- vendor/github.com/mongodb/amboy/rest/service_management.go
Jira: https://jira.mongodb.org/browse/EVG-14519
* Revendor amboy to reduce logging level on Complete errors.
* Remove `RecentErrors` from amboy stats collection job, which doesn't matter because we disabled collecting amboy remote management stats anyways.
> EVG-14519: revendor amboy

- config.go
JIRA: https://jira.mongodb.org/browse/EVG-14514
> EVG-14514: update agent version

- rest/data/interface.go
- rest/data/task.go
- rest/data/task_test.go
- rest/route/task.go
`http://localhost:9090/rest/v2/tasks/evergreen_ubuntu1604_test_service_patch_5e823e1f28baeaa22ae00823d83e03082cd148ab_5e4ff3abe3c3317e352062e4_20_02_21_15_13_48?execution=0`
`http://localhost:9090/rest/v2/tasks/evergreen_ubuntu1604_test_service_patch_5e823e1f28baeaa22ae00823d83e03082cd148ab_5e4ff3abe3c3317e352062e4_20_02_21_15_13_48?execution=1`
> EVG-14308 Add execution option to /tasks API endpoint

- units/check_blocked_tasks.go
> EVG-14665 add distroID to job

- globals.go
- graphql/tests/restartTask/data.json
- model/build/build.go
- model/build/db.go
- model/lifecycle.go
- model/patch/patch.go
- model/task_lifecycle.go
- model/task_lifecycle_test.go
- model/version.go
- service/api_task.go
- units/task_monitor_execution_timeout.go
- units/task_monitor_execution_timeout_test.go
This has Jonathan's original changes unchanged, except fixes the merge conflict that happened when he pushed it.
> EVG-12953 UpdateBuildAndVersionStatusForTask reorg

- units/crons.go
- units/host_allocator.go
Jira: https://jira.mongodb.org/browse/EVG-14372
* Use per-distro scopes for host allocator job.
* Remove unused environment from host allocator job.
> EVG-14372: use scopes for host allocator job

- units/crons.go
- units/spawnhost_expiration_check.go
- units/spawnhost_expiration_warning.go
- units/volume_deletion_job.go
- units/volume_expiration_check.go
- units/volume_expiration_warning.go
Jira: https://jira.mongodb.org/browse/EVG-14374
* Use scopes for periodic notification jobs.
* Use scopes for spawn host expiration check jobs.
* Use scopes for volume expiration check jobs.
> EVG-14374: use scopes for periodic notifications and spawn host/volume expiration jobs

- units/crons.go
- units/periodic_builds.go
Jira: https://jira.mongodb.org/browse/EVG-14375
Use scopes for periodic build jobs.
> EVG-14375: use scopes for periodic build jobs

- units/host_allocator.go
- units/host_termination.go
- units/periodic_builds.go
- units/scheduler.go
- units/scheduler_alias.go
- units/volume_deletion_job.go
- units/volume_expiration_check.go
Jira: https://jira.mongodb.org/browse/EVG-14373
> EVG-14373: fix fmt.Sprintf in scopes

- rest/client/methods.go
Jira: https://jira.mongodb.org/browse/EVG-14575
Add retries when the host's user data script gets the host provisioning script from the app server.
> EVG-14575: retry the request for host provisioning options

- agent/internal/client/client.go
- config.go
- glide.lock
- vendor/github.com/evergreen-ci/timber/glide.lock
- vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar.go
- vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14557
> EVG-14557: revendor timber 

- self-tests.yml
Jira: https://jira.mongodb.org/browse/EVG-14524
> EVG-14524: remove docker buildvariant from tests

- config.go
- operations/host.go
- operations/host_spawn.go
- rest/client/interface.go
- rest/client/methods.go
- rest/client/mock.go
> EVG-14460 Add cli command that converts an IP address to a host url

- units/provisioning_user_data_done.go
Jira: https://jira.mongodb.org/browse/EVG-14605
> EVG-14605: only log a provisioning error for check user data done if the job has an error

- rest/route/middleware.go
Didn't test but reasoned about 👍
> EVG-14667 error in middleware for invalid patch ID

- agent/command/results_native.go
- agent/command/results_xunit.go
- agent/command/results_xunit_parser.go
- agent/command/results_xunit_parser_test.go
- agent/command/results_xunit_test.go
- config.go
JIRA: https://jira.mongodb.org/browse/EVG-14159
> EVG-14159: Enable duplicate log test names 

- model/project.go
[EVG-14735](https://jira.mongodb.org/browse/EVG-14735)
:llama-panic:
> EVG-14735 check if function is nil before accessing list

- units/provisioning_setup_host.go
Jira: https://jira.mongodb.org/browse/EVG-14738
This seems like some old code that was moved around and never fixed. Copying the host setup script is retryable, so it should not set the host to unprovisioned if it can't copy it - the most likely reason it cannot copy is because sshd isn't ready yet.
> EVG-14738: retry copying setup script for legacy SSH hosts

- units/provisioning_setup_host.go
https://jira.mongodb.org/browse/EVG-14691
The host is only supposed to run the provisioning setup job until it runs out of attempts. If the host runs out of attempts without succeeding, it should be marked as failed provisioning. This makes the host fail faster. Without this check, it'll attempt to run the job again due to cron job population, even if it used all of its attempts previously, until it hits the provisioning timeout.
> EVG-14691: mark the host as failed provisioning if it failed to provision and cannot retry

- auth/auth.go
- config_ui.go
- graphql/tests/spruceConfig/data.json
- rest/model/admin.go
- service/user.go
[EVG-6877](https://jira.mongodb.org/browse/EVG-6877)
This removes dead code. We don't actually set this field anywhere in the UI.
> EVG-6877 Remove unused setting

- rest/model/test.go
> EVG-14751 Update duration calculation for cedar test results

- units/stats_task_end.go
[EVG-14744](https://jira.mongodb.org/browse/EVG-14744)
Cris wanted the project identifier in the task-end-stats report in addition to the project ID.
Run in staging. No errors produced, and task-end-stats now contains project_identifier.
> EVG-14744: get identifier

- config.go
- glide.lock
- vendor/github.com/evergreen-ci/gimlet/app_resolve.go
- vendor/github.com/evergreen-ci/timber/buildlogger/get.go
- vendor/github.com/evergreen-ci/timber/buildlogger/get_test.go
- vendor/github.com/evergreen-ci/timber/glide.lock
- vendor/github.com/evergreen-ci/timber/testresults/get.go
- vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar.go
- vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar_test.go
JIRA: https://jira.mongodb.org/browse/EVG-14757
> EVG-14757: Revendor timber and gimlet

- model/version.go
[EVG-14818](https://jira.mongodb.org/browse/EVG-14717)
Use system requesters in mainline commits query
> EVG-14717 Use correct requester for mainline commits query

- gqlgen.yml
- graphql/generated.go
- graphql/resolvers.go
- rest/model/task_annotations.go
[EVG-14695](https://jira.mongodb.org/browse/EVG-14695)
Break out jira Ticket fetching so that tickets are only fetched when the field is included in the query. 
Manually tested with graphql on staging to make sure it still fetches the Jira tickets.
> EVG-14695 Fix slow page load for display tasks with Jira tickets

- graphql/integration_spec.json
- graphql/resolvers.go
- model/testresult/testresult.go
- rest/model/test.go
- rest/route/service_test.go
JIRA: https://jira.mongodb.org/browse/EVG-13974
> EVG-14723: Fix URLs for legacy test results

- service/rest_version.go
[EVG-14227](https://jira.mongodb.org/browse/EVG-14227)
The way this is written right now we're writing to the file twice.... sigh.
> EVG-14227 add return statement

- graphql/util.go
[EVG-14828](https://jira.mongodb.org/browse/EVG-14828)
Temporary commit to log build variant generation performance for the mainline commits query. 
Will be removed after the necessary data is captured
> EVG-14828 Grip log buildVariant Creation

- service/api.go
[EVG-14783](https://jira.mongodb.org/browse/EVG-14783)
add nil check to v
> EVG-14783 Fix panic in middleware_auth_user.go

- rest/data/task_test.go
The pr was sitting for too long and the test broke because of new changes
> EVG-13893 Fix test

- trigger/payloads_test.go
[EVG-14870](https://jira.mongodb.org/browse/EVG-14870)
> EVG-14870 Fix test-trigger on Race Detector and Ubuntu 16.04

- agent/command/results_gotest.go
- config.go
[EVG-14218](https://jira.mongodb.org/browse/EVG-14218)
does not return error when len == 0
> EVG-14218 Add optional parameter to gotest.parse_files

- glide.lock
- graphql/integration_spec.json
- public/static/js/task.js
- rest/model/test.go
- rest/route/service_test.go
- service/task.go
- service/ui.go
- vendor/github.com/evergreen-ci/gimlet/app_merge.go
JIRA: https://jira.mongodb.org/browse/EVG-14657
> EVG-14657: Add test_log route for fetching all logs of a group id

- model/project_vars.go
- model/project_vars_test.go
- rest/data/interface.go
- rest/data/project.go
- rest/data/project_test.go
- rest/route/project.go
- rest/route/project_test.go
- rest/route/service.go
[EVG-14633](https://jira.mongodb.org/browse/EVG-14633)
The api calls UpdateVarsByValue which calls
GetVarsByValue returns matching projects
then it updates matching variables 
and returns the projects updated
unittest for GetVarsByValue
unittest for GpdateVarsByValue
unittest for route
postman
> EVG-14633 Create api for rotating credentials

- rest/data/interface.go
- rest/data/project.go
- rest/data/project_test.go
- rest/route/project.go
- rest/route/project_test.go
[EVG-14633](https://jira.mongodb.org/browse/EVG-14633)
add logging
added test to TestUpdateProjectVarsByValue
> EVG-14633 Add logging to projects modified by variables/rotate endpoint

- rest/route/distro.go
- rest/route/distro_test.go
[EVG-14921](https://jira.mongodb.org/browse/EVG-14921)
The patch route doesn't log if the distro is modified and it should.
> EVG-14921 log when distro is modified from PATCH route

- service/waterfall.go
[EVG-14594](https://jira.mongodb.org/browse/EVG-14594)
Tests aren't actually being added bc I moved adding the temporary structure t to the list before we do it.
> EVG-14594 add test results to waterfall correctly

- graphql/ui_plugin_build_baron.go
- model/task/db.go
- model/task/task.go
- rest/data/version.go
- service/task.go
- trigger/task.go
JIRA: https://jira.mongodb.org/browse/EVG-14924
> EVG-14924: Fetch cedar test results for display tasks

- config.go
- operations/patch_util.go
> EVG-14154 use default parameters only if they haven't been specified

- graphql/generated.go
- graphql/resolvers.go
There is some leftover unused code that breaks make gqlgen.
> Remove childPatchResolver unused code

- service/api_task.go
- units/stats_task_end.go
Re-Reverts #4812 due to broken task test-service unrelated to this change
> EVG-14823: Revert original PR change back

- graphql/ui_plugin_build_baron.go
- model/task/db.go
- model/task/task.go
- rest/data/version.go
- service/task.go
- trigger/task.go
JIRA: https://jira.mongodb.org/browse/EVG-14972
> EVG-14972: Add back cedar test results fetching code

- config.go
- glide.lock
- vendor/github.com/evergreen-ci/timber/buildlogger/get.go
- vendor/github.com/evergreen-ci/timber/buildlogger/get_test.go
JIRA: https://jira.mongodb.org/browse/EVG-15006
> EVG-15006: Revendor timber 

- agent/internal/client/base_client.go
- config.go
Jira: https://jira.mongodb.org/browse/EVG-14816
The code is supposed to look like this, but because of several Cedar-related reverts yesterday, this got lost.
> EVG-14816: ensure http client exists

- units/provisioning_setup_host.go
[EVG-14090](https://jira.mongodb.org/browse/EVG-14090)
This shouldn't log at error if we're continuing.
> EVG-14090 Reduce retry jasper error to info

- agent/agent.go
- agent/internal/client/base_client.go
- agent/internal/client/host_methods.go
- agent/internal/client/mock.go
- agent/internal/client/pod_methods.go
- config.go
JIRA: https://jira.mongodb.org/browse/EVG-14427
> EVG-14427: Add back cedar grpc conn check with retry instead of sleep

- auth/okta.go
- config_auth.go
- config_test.go
- glide.lock
- public/static/js/admin.js
- rest/model/admin.go
- service/templates/admin.html
- testutil/config.go
- vendor/github.com/evergreen-ci/gimlet/okta/okta.go
- vendor/github.com/evergreen-ci/gimlet/okta/okta_test.go
Jira: https://jira.mongodb.org/browse/EVG-14866
This is identical to #4820, but I reverted to delay the deploy until Monday when we plan to migrate to the new authorization server.
> EVG-14886: use default authorization server for Okta

- makefile
- rest/model/pod.go
[EVG-14915](https://jira.mongodb.org/browse/EVG-14915)
WIP: just wanted to check to see if initial implementation is correct (API model)
> EVG-14915: Implement API model to initialize pod

- glide.lock
- model/pod/pod.go
- rest/model/pod.go
- rest/model/pod_test.go
- units/pod_termination_test.go
- vendor/github.com/evergreen-ci/cocoa/ecs/pod_creator.go
- vendor/github.com/evergreen-ci/cocoa/ecs_pod_creator.go
- vendor/github.com/evergreen-ci/cocoa/ecs_pod_creator_test.go
- vendor/github.com/evergreen-ci/cocoa/internal/testcase/ecs_pod.go
- vendor/github.com/evergreen-ci/cocoa/internal/testcase/ecs_pod_creator.go
- vendor/github.com/evergreen-ci/cocoa/mock/ecs_pod_creator_test.go
Jira: https://jira.mongodb.org/browse/EVG-15108
* Add working directory to pod DB model and REST request model.
* Revendor cocoa to include the working directory change.
I just modified the existing DB/REST tests to include the working directory.
> EVG-15108: add pod working directory

- glide.lock
- vendor/github.com/evergreen-ci/gimlet/parsing.go
- vendor/github.com/evergreen-ci/gimlet/parsing_test.go
[EVG-14923](https://jira.mongodb.org/browse/EVG-14923)
> EVG-14923 Revendor gimlet

- graphql/resolvers.go
[EVG-15100](https://jira.mongodb.org/browse/EVG-15100)
> EVG-15100 Fallback to cedar test results for test count resolvers

- model/patch_lifecycle.go
[EVG-13894](https://jira.mongodb.org/browse/EVG-13894)
more descriptive error
n/a
> EVG-13894 Provide a better error if commit queue encounters a merge conflict in the evergreen.yml

- rest/route/annotations.go
- rest/route/annotations_test.go
[EVG-15030](https://jira.mongodb.org/browse/EVG-15030)
checks task status before creating task annotation 
Added to unittest test
> EVG-15030 Disallow creating annotations for non-failed tasks

- testdata/local/users.json
[EVG-13490](https://jira.mongodb.org/browse/EVG-13490)
> EVG-13490 Add test user to sample data 

- model/pod/db.go
- model/pod/db_test.go
- units/crons.go
- units/crons_remote_minute.go
Jira: https://jira.mongodb.org/browse/EVG-14970
If the pod has been stuck starting for too long without any sign of liveliness, terminate it.
Normal DB query tests.
> EVG-14970: terminate pods that are stuck starting

- graphql/generated.go
- graphql/resolvers.go
- graphql/schema.graphql
- graphql/tests/version/data.json
- graphql/tests/version/queries/baseTaskStatuses.graphql
- graphql/tests/version/queries/taskStatuses.graphql
- graphql/tests/version/results.json
[EVG-13564](https://jira.mongodb.org/browse/EVG-13564)
> EVG-13564 task status resolvers for versions
