evergreen-ci/evergreen

model/build/build.go
model/lifecycle.go
model/project.go
model/project_test.go
model/status_diff.go
model/task/db.go
model/task/task.go
rest/data/version.go
rest/data/version_test.go
rest/model/build.go
rest/route/build.go
service/build.go
service/rest_build.go
service/rest_build_test.go
service/rest_version.go
service/rest_version_test.go
service/stats.go
service/timeline.go
service/version.go
service/waterfall.go
trigger/build.go
trigger/build_test.go

The final goal is the remove most of the build task cache, leaving over just the task ids. (The list of task ids is still helpful because of the sorting and filtering we do when we create the build).
I intend to divide the work into separate PRs/commits: this one replaces references to the task cache with queries against the task collection. After it's burned-in I'll follow up with a separate PR that will remove most of the build cache and all the logic that keeps it in sync with the tasks collection.

EVG-5948 remove references to build's task cache

---

cmd/generate-rest-model/generate-rest-model.go
makefile
rest/model/codegen.go

This makes the code generator finally usable! This just adds a simple cli command that calls the code gen code with some hardcoded file paths. I had to add a package-level variable to hold a path prefix, because this command and the tests call it with different working directories

EVG-12618 make target for code gen

---

command/host_create.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go
rest/route/distro.go
rest/route/distro_test.go
rest/route/host_create.go
rest/route/service.go

https://evergreen-staging.corp.mongodb.com/task_log_raw/mci_ubuntu1604_test_cloud_patch_c2e82da3ba68a0acbe9c8c6cee7fede58bf52314_5f6a552a97b1d3217bdc21c8_20_09_22_19_49_41/3?type=T#L171
Originally I thought about having host.create return AMIs as a result, or adding it to host.list, but it seems we want to know the AMI in the case of error as well (or especially), so that's why I added a separate route.

EVG-12888 log host.create AMI/distro

---

graphql/integration_atomic_test.go
graphql/tests/userSettings/data.json

- more cleanly split up the tests into suite/directory/test. Full test names have not changed
- scope setup code to the appropriate one of the 3 levels. No more starting up a ton of http servers if you want to run 1 test so things should be a lot faster
- clean up the http server, which should prevent too many open file errors
- pretty print the actual query response so you don't need to copy it to another editor to look at

EVG-12967 move setup code within graphql subtests

---

graphql/util.go

This function is only used in the projects resolver of the patch resolver. The projects field is used to to render the configure patch view on the ui. So by preventing non patchable tasks from being returned here it should not show up in the UI

EVG-12407 Dont return patchable:false tasks

---

graphql/resolvers.go
graphql/tests/myHosts/data.json
graphql/tests/myHosts/results.json

https://jira.mongodb.org/browse/EVG-13122
Originally, the host resolver returned an error when a nonexistent volume id is encountered in the Host.Volumes field. [Recently we discovered that mounting a volume to a host may push volume ids to Host.Volumes that don't exist in the Volumes collection](https://jira.mongodb.org/browse/EVG-13119). This PR allows us to continue using this query by ignoring nonexistent volumes by not returning an error upon discovery.

EVG-13122: Ignore nonexistent volume Ids when building the volumes field in the Host GQL type

---

model/host/db.go
model/host/host_test.go
model/task/db.go
units/task_monitor_execution_timeout.go

- separate the interesting part of the stale task queries. This does mean we do multiple queries but they should be pretty fast
- log the reason for staleness
- fix a bug in the undispatched tag case where we were not respecting the cutoff check. If something races such that the heartbeat reaches the server before we mark the task as started, this could cause the problem we saw
- add a sanity check to the running task case that we don't have a heartbeat time of 0

EVG-13116 add logging, fix stale task query

---

model/lifecycle_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go

Add logging to help trace down the cause of (errantly) blocked task group tasks.
In defence of logging the stack trace: it's not really that big. We [log it](https://github.com/evergreen-ci/evergreen/blob/e1a1a040cb99960a0422e85928d280f08e8cb897/service/ui.go#L149) with many UI errors and with panics. It will get logged once for each task group task that gets blocked and has unblocked dependencies.
(The issue we had previously was with logging the display task cache which was huge).

EVG-12923 add logging

---

config.go
operations/http.go
service/api_patch.go

Add an intermediate step before #4030 to push users to update their CLI.
Also stop sending the BackportOf string given we don't need it anymore.

EVG-12872 error on BackportOf

---

rest/data/project_test.go
rest/model/project.go
rest/route/project_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13127
The response returned from `/rest/v2/projects/{project_id}` is missing some fields. I added the project ref settings related to historical stats to the response because they're required for Cedar to run the historical stats job.

EVG-13127: add historical stats settings to REST route for project settings

---

model/task_lifecycle.go

#4036 added logging the stack trace, but the trace itself isn't actually being logged. 😞

EVG-12923 log frames

---

model/task_lifecycle.go
model/task_lifecycle_test.go
model/version.go

We were only scheduling the display task, which means the exec tasks couldn't get scheduled in any way.
Whether or not this fix is temporary depends on what we do with display/execs in the future but 🤷  the fix is done so.

EVG-12433 consider exec tasks when scheduling display task

---

model/lifecycle.go

https://jira.mongodb.org/browse/EVG-12549
This PR adds logging to the RestartVersion function to help me understand which parts may be running slower than desired

EVG-12549: add timing logging for RestartVersion

---

public/static/js/projects.js
service/project.go

It seems it was intentional to leave out private variables, but now it's inconsistent with the API route.

EVG-13139 copy private variables when copying project in UI

---

apimodels/agent_models.go
units/crons.go
units/provisioning_create_host.go

It looks like tasks that fail on host.list for cloud are hitting EC2 InsufficientCapacity errors for host.create (sigh). By default we should retry once it looks like, but there's an off-by-one bug so we don't actually retry. I'm also going to make the retry limit 2 for now? Although that's an arbitrary decision, we could start by fixing the bug and modify the default later. We also retry with different subnets, so it does seem like there's a benefit to retrying.

EVG-13003 modify host create job retries

---

model/task/db.go
model/task_lifecycle.go
model/task_lifecycle_test.go

I initially planned to have a display task with only successful + blocked tasks be a failure, but I'm like 51% sure that it's better to leave as successful. Having something in this state is almost certainly bad configuration. And even though it's theoretically correct, showing failed might make someone look for a red execution task and not find one
- Fix a related bug where the stranded task job is trying to clean up display tasks (these have heartbeats set to that of their execution tasks). This was causing blocked display tasks to get "restarted" and end up in a status of undispatched
- Ignore blocked execution tasks when evaluating the overall status of a display task

EVG-13142 ignore blocked execution tasks for status

---

model/task_lifecycle.go

This logic already exists for task groups so I'm not sure why I didn't also add it to display tasks, but this is function is hit for resetting stranded tasks / other kinds of restarts, and I think it makes sense to allow restarting when there are blocked tasks for all of the cases.

EVG-12936 reset display task if execution tasks are blocked

---

agent/command.go

I suspect that the problem is not actually that we don't try to run setup_group, but that there are somehow unrunnable commands in setup_group

EVG-12966 add logging for blank commands

---

model/task_lifecycle.go

Logging shows a race between resetting a task group and the [scheduler's sanity check](https://github.com/evergreen-ci/evergreen/blob/6d61fdd4be109f73665fa13d1c3fa13d39547193/model/task_queue_service_dependency.go#L544) that blocked tasks are marked blocked. 
My read of the race is that `MarkOneTaskReset` first clears the blocked status from dependencies before it resets the task they depend on. Since clearing the blocked status takes some time (it's recursive and there's a pretty deep call stack for the compile task) there's a significant amount of time where immediate dependencies are marked as not blocked while the task they depend on still has a failed status. This state is what the sanity check is trying to correct, so it calls UpdateBlockedDependencies on the depended-on task.
My …

EVG-12923 reorder reset

---

graphql/ui_plugin_build_baron.go

When maxResult was set to -1 it was interpreted as "maxResults":10000. This times out if the response it too large.

EVG-13069  Evergreen Build Baron related tickets bug

---

cmd/upload-binaries/upload-binaries.go
cmd/upload-s3/upload-s3.go
makefile
self-tests.yml

JIRA: https://jira.mongodb.org/browse/EVG-13238
* Add script to use pail to push `clients` directory to S3 bucket.
* Add task that only runs on the waterfall to push binaries to S3 so they can be used for the deploy.
* When we deploy with commit `abc123`, the agents should also be downloadable from the prefix with `abc123` in S3.
* To avoid pushing the same binaries to the same S3 location (due to the task running in both staging and production), include the project name in the S3 prefix (which is different in each environment).

EVG-13238: upload agent binaries to S3

---

command/exec.go
command/exec_test.go

Otherwise there's unexpected behavior when the expansion value has spaces and should also be split.

EVG-13093 split commands after expansions in subprocess.exec

---

validator/project_validator.go

JIRA: https://jira.mongodb.org/browse/EVG-12482
Convert some warnings that have been in the validator for several months into errors. I can't really check if anyone still has these errors in their projects since `evergreen admin all-configs` only gives you the final parsed configs, but it seems like these project config mistakes would be unlikely to actually happen and are easy to fix.

EVG-12482: convert project warnings to errors

---

command/exec.go
command/exec_test.go
config.go

Take three:
The expansions fix caused issues with the smoke test because we have an arg with two words--we only say we're going to split commands, not args. However thinking further,  KeepEmptyArgs seems like it should apply to args and NOT commands (it looks like cloud only uses it in this way; I'm not sure anyone else uses it)--it isn't documented but I can add documentation along those lines. In that case the original implementation works for args and commands.

 EVG-13093 split commands after expansions in subprocess.exec

---

model/lifecycle.go
model/lifecycle_test.go
model/task/db.go
model/task/task.go
model/task_lifecycle.go

Sorry there's going to be lots of context for this. The immediate problem is that spruce shows both execution and display tasks, and a user can pass those into the restart code. We have handling for restarting display tasks to also restart/archive their children, but since both will be in the list we will try to archive the same execution of a child twice. This fix is a targeted fix for just that to remove execution tasks, so that this is consistent with the old UI
Ideally this should be addressed with EVG-12549, because Arjun found performance problems with the exact code that this is touching, and whatever fix for that will likely have to redo this. I tried a couple things but none worked, so I'm going with something simple just for this problem because people hit this a couple times a …

EVG-12942 fix restarting patches with display tasks from spruce

---

globals.go
graphql/resolvers.go
graphql/tests/patchTasks/data.json
graphql/tests/patchTasks/queries/filter-by-multiple-statuses.graphql
graphql/tests/patchTasks/queries/filter-by-task-name.graphql
graphql/tests/patchTasks/queries/filter-by-variant-partial-search-term.graphql
graphql/tests/patchTasks/queries/filter-by-variant.graphql
graphql/tests/patchTasks/queries/sort-base-status-descending.graphql
graphql/tests/patchTasks/queries/sort-by-base-status.graphql
graphql/tests/patchTasks/queries/sort-by-name.graphql
graphql/tests/patchTasks/queries/sort-by-status.graphql
graphql/tests/patchTasks/queries/sort-by-variant.graphql
graphql/tests/patchTasks/results.json
graphql/util.go
model/task/task.go

https://jira.mongodb.org/browse/EVG-13194
When sorted by status, patch tasks were being sorted alphabetically. Therefore all tasks with status `failed` were sorted to the top, but other failed statuses (test-timed-out and task-timed-out) were sorted to the bottom of the list. 
This PR uses an aggregation pipeline in the patch tasks DB query to sort all tasks with a failure status to the top of the list when being sorted by status.

EVG-13194: sort all patch failures to top when sorting by status 

---

cloud/ec2.go
cloud/ec2_test.go

https://jira.mongodb.org/browse/EVG-13304
the updateVolume mutations calls into this function to update the display name of a volume

EVG-13304: allow ModifyVolume to set volume display name

---

model/host/hostutil.go
rest/client/request.go

JIRA: https://jira.mongodb.org/browse/EVG-13238
Two changes to fix a panic in the agent monitor, which was relying on the agent's API server URL.
1. Remove shell quotes from the command to invoke the agent. There's some possibility that this will be wrong if we ever have paths with spaces in them, but I'm just gonna assume it won't happen.
2. Check the error from `http.NewRequest()` immediately because if `http.NewRequest()` errors and you try to set a field on it, it'll panic the REST communicator.
This didn't arise in the smoke test because it doesn't use shell quotes when it's invoking the agent monitor.

EVG-13236: fix shell quotes and check error from http.NewRequest()

---

model/task/task.go
model/task_lifecycle.go
model/task_queue.go

There was a commit queue patch that got blocked because something broke when trying to clear/reset a stranded task. From splunk, a DocumentNotFound was caught in BlockTaskGroupTasks. I'm assuming this issue came from `dequeue`, because A) the others are more verifiable and B) in the other place we use `dequeue` we do filter out NotFound errors.
I'm also wondering if ClearAndResetStrandedTask should remove commit queue  patches in case of error, to prevent a commit queue patch from getting stuck if it failed to restart, but that might suppress important errors  / be unnecessary since this doesn't happen often so I left it out for now.

EVG-12943 suppress dequeue error for BlockTaskGroupTasks

---

agent/agent_test.go
agent/task.go
config.go

My [previous logging](https://github.com/evergreen-ci/evergreen/commit/ccc1c6eaaff4506460cb647f09e2c8ca0a9ba3bd) turned up nothing, and the fact that BF-18878 exists suggests that the problem is not that we somehow have a blank command. I can't figure out what else it could be and both problems occurred at around the same time, so I'm going to add a bit more logging and hope that this was fixed by something else

EVG-12966 more logging in task setup

---

cloud/ec2.go
globals.go
model/alertrecord/alert_bookkeeping.go
model/host/volume.go
trigger/volume.go
trigger/volume_test.go
units/volume_expiration_warning.go
units/volume_expiration_warning_test.go

Changed the default in this case to be 30 days, with a notification at 3 weeks, 2 weeks, and 1 week.
I _think_ that the existing notification code inserted all notifications regardless of whether or not they failed because we currently only created 2 notifications, but I figure now that there are so many (and because we don't want to accidentally spam people with 3 notifications who currently have unattached volumes expiring in less than a week) we may as well short-circuit when we make a notification.

EVG-13080 extend default volume expiration from terminated hosts

---

model/task/task.go
public/static/js/filters/filters.common.js
trigger/task_jira_test.go

The task in the ticket is in a really weird state where it has everything that a finished task would, except that it's in a non-finished status. I couldn't figure out how it got like that but also think it's not that important to do so given that this is the only case we know of so far. This pr just adds a sanity check to both UIs that shouldn't be hit ever, but if they do then it'll hopefully display something more accurate than before

EVG-13097 extra sanity check in task status displays

---

config_scheduler.go
model/distro/distro.go
model/distro/distro_test.go
public/static/js/distros.js
rest/model/admin.go
rest/model/distro.go
scheduler/planner.go
service/templates/admin.html
service/templates/distros.html

When projects use generate tasks, they basically have to wait twice as long for a task, because first they have to wait for the generator to be scheduled, and then for the generated task to be scheduled. The old scheduler [handled this](https://github.com/evergreen-ci/evergreen/blob/28c66fda6b8f4013ed4e0b3548444b5cf0d09245/scheduler/task_priority_cmp.go#L152) by scheduling  generators faster, so that users essentially only had to wait once for generated tasks, but the new scheduler doesn't seem to consider that, so I added a "factor" for it.

EVG-12693 schedule generators earlier

---

model/host/hostutil.go
model/host/hostutil_test.go
rest/route/distro.go
units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-13315
Check the feature flag set in the DB rather than the cached value in the global environment struct (so that we can dynamically enable/disable this without requiring an app server restart).

EVG-13115: load S3 binary download feature flag from the DB

---

model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle_test.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
service/task_history.go
trigger/version.go

This is only half of the ticket, the second half is a logically different change so it'll be a separate pr
- Remove the FindWithDisplayTasks function. It was problematic for two reasons - it was named in a way that said "task.Find but also includes display tasks in the results" (the regular task.Find does not), and also that the way it added display tasks to its results was inefficient
- For any callers using it as a task.FindAll, switch them to using FindAll. The fact that the function didn't actually link display tasks for a long time suggests that most callers are in this bucket. This part is probably the most bug-prone if I misread what the caller was doing
- For any callers actually using it for its intended purpose, split them into 2 calls - 1 to find tasks, and 1 to link up parent …

EVG-13249 speed up finding parent display tasks

---

model/lifecycle.go
model/task/task.go
model/task/task_test.go

The bulk archive function is supposed to mirror the singular one for the most part, but I forgot to [increment the execution](https://github.com/evergreen-ci/evergreen/blob/94a4db5abec79533344b6cf1574d864efce651f3/model/task/task.go#L1730). This means that after the deploy, if you restart a version or build, we actually overwrite the existing execution data when it executions again. We also add a copy to the old collection. If you try and restart a task that was affected by this, you hit the duplicate key error because we already archived this execution

EVG-13249 be sure to increment executions when restarting

---

model/project_event_test.go
model/project_ref.go
model/repo_ref.go

This is to kick off Projects Track Multiple Branches. Because project ref is used in so many places with so many assumptions, in the design we chose to go forward with a different collection for repo configuration documents to avoid introducing bugs / major refactors. I re-arranged the project ref document to be clearer.

EVG-13268 add repo ref collection

---

globals.go
model/event/commit_queue_event.go
model/event/event_registry.go
trigger/commit_queue.go
units/commit_queue.go

Users will only get this notification if they're subscribed to commit queue notifications. Examples below (I changed "enqueue-failed" to "failed to enqueue" though)
**Slack:**
**Email:**

EVG-7256 send users notification for enqueue cq patch failures

---

gqlgen.yml
graphql/generated.go
graphql/schema.graphql
graphql/tests/spruceConfig/queries/spawnHost.graphql
graphql/tests/spruceConfig/results.json
rest/model/admin.go

https://jira.mongodb.org/browse/EVG-13340
These variables will be used to enforce spawn host/volume limits in Spruce

EVG-13340: SpawnHostConfig gql type

---

agent/command/git_patch_test.go
agent/command/git_push_test.go
agent/command/testdata/attach/plugin_attach_results.yml
agent/command/testdata/attach/plugin_attach_results_raw.yml
agent/command/testdata/attach/plugin_attach_xunit.yml
agent/command/testdata/attach/plugin_attach_xunit_wildcard.yml
agent/internal/task_config.go
agent/internal/testutil/task_config.go
agent/task.go
apimodels/agent_models.go
config.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go
service/api.go
service/api_distro.go

JIRA: https://jira.mongodb.org/browse/EVG-13239
The agent and its commands only use a small number of fields from the distro document, so I changed it to pass only the fields it needs rather than the entire distro. I'm purposely not removing the old route yet so that agents have a chance to roll over before removing it.
I also updated the agent version string but because the version has already been updated today, I just tacked a string onto the date.

EVG-13239: remove agent's hard dependency on distro document

---

model/task_annotations/db.go
model/task_annotations/task_annotations.go
rest/model/task_annotations.go

We are waiting on a discussion with users to determine wether or not we will want to display the source of each issue or suspected link. However, I think it makes sense to make this backend change without waiting on that for the following reasons: 
- We have determined that, since users can edit issues, having a global source for the entire task annotation document is not useful. If we were to remove that, I think it's important for us to have access to the source of edits whether we choose to display it or not. 
- If we determine that displaying the source is indeed unnecessary, since this feature is not in use yet, we might find after some time that we do indeed want to display the source. I think it makes sense to start storing that data in case that happens. 
- It probably makes sense …

EVG-13371  Add source field to notes

---

model/annotations/db.go
model/annotations/task_annotations.go
model/annotations/task_annotations_test.go
model/task/db.go
rest/model/task_annotations.go
rest/route/annotations.go
rest/route/annotations_test.go
rest/route/service.go

This ticket does a couple of other things to improve organization, once I started writing the route and realized some things:
* Changed task_annotations to annotations because a) that's descriptive enough, b) underscores in package names are weird for the make target and also just embedded in the code, and c) task_annotations.TaskAnnotations is soo long 
* Added an enum to distinguish the types of annotations for easier querying (could use constants instead of an enum if preferred, given there are only like three possible states)
* Strayed from the design of returning one document, in lieu of returning a list, which also makes it easier to return multiple executions (rather than a map of taskID to a list of annotation docs)

EVG-13154 add route to get task annotations by build

---

rest/route/annotations.go
rest/route/annotations_test.go
rest/route/service.go

This was pretty simple cause it's basically just the build route but again. Also removed some accidental comments. My only concern is if this should use pagination? Idk how many annotations we really expect to have per build/version. I may ask at the design meeting. I mildly hate pagination so I don't want to implement it if they don't want it.

EVG-13155 add annotation route for version

---

service/api.go
service/api_distro.go

JIRA: https://jira.mongodb.org/browse/EVG-13239
Since the agents have rolled over to use the new distro route, this route can be removed.

EVG-13239: remove old route to get agent's distro

---

model/annotations/db.go
model/annotations/task_annotations.go
model/annotations/task_annotations_test.go
rest/model/task_annotations.go
rest/route/annotations.go
rest/route/annotations_test.go

Choosing to remove a layer of indirection by removing Annotation from being embedded in TaskAnnotation.
Update in the future will need to be modified to update each field of annotation (preferably if that field has been modified) and will also need to populate the source; because no modification routes have been made I think that work will fit better wit those routes, and this refactor unblocks them.

EVG-13402 refactor annotations

---

model/project.go
model/task/task.go
model/task_queue_service_dependency.go
model/task_queue_service_test.go

It's valid for the task queue to not contain tasks that are depended on:
- if the depended on task doesn't exist.
- if the depended on task has already run.
We don't need to validate the existence of the tasks when the depended_on task because it's not an error condition from the perspective of the dispatcher. Skipping the edge is the right thing to do: we don't need to be ordered after a task if the task isn't in the queue. Granted, we shouldn't have dependencies that don't exist, but this shouldn't be the dispatcher's concern.
Also, ignore dependencies that don't exist. We should separately handle why dependencies on tasks that don't exist get created, but they shouldn't cause the task to hang out in the task queue forever. Either we automatically deactivate such a task or allow it to …

EVG-13394 skip adding an edge to a non-existent node

---

model/commitqueue/github_merge_generic.go

@ybrill I'm actually a little confused by this structure. Why are there a list of PRInfos--are they unrelated to each other? In which case if one fails I'd think we could send the status and then just continue to try the others, rather than aborting, so I imagine they are related, but I don't understand how.

EVG-13081 report merge errors for PR cq

---

config.go
operations/commit_queue.go
operations/flags.go
operations/patch.go

Make the help doc for `evergreen commit-queue backport --help` a little more helpful.

EVG-13106 clarify backport help doc

---

model/distro/distro.go
model/host/db.go
model/host/host.go
model/host/host_test.go
public/static/js/distros.js
validator/distro_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13404
* Remove preconfigured images as a distro provisioning method since we never implemented this.
* All distros/hosts at this point have set their provisioning method to a real value, so it's no longer necessary to count the empty string or a nonexistent provisioning method key as legacy SSH. This means we can simplify the host queries filtering by provisioning method.

EVG-13404: remove preconfigured image provisioning option and clean up provisioning method queries

---

units/crons_remote_minute.go

JIRA: https://jira.mongodb.org/browse/EVG-13311
The double commit queue job running bug seems to be happening because each per-minute commit queue job is enqueued in two logically separate queues. They get populated once in the regular remote queue (in the "evg.service.jobs" collection) and then again in the dedicated "service.commitqueue" queue group (which is stored in a separate collection "evg.service.group"). The reason the commit queue job ran twice in the logs is because they apparently _always_ run twice, but I guess usually we're lucky and one finishes fast enough that the duplicate one doesn't interfere.
Evidence: If you look for the job in "evg.service.jobs" (`{"_id": "commit-queue:mongot-master_2020-10-21.15-42-00"}`) and "evg.service.group" (`{"_id": …

EVG-13311: do not populate commit queue jobs in two different Amboy queues

---

model/patch/cli_intent.go
units/patch_intent_test.go

I think this never worked, but hopefully should now
`mci:SECONDARY> db.patches.findOne({"backport_of.patch_id": {$exists: true}})
null`

EVG-13349 fix backporting of patches by patch ID

---

model/project_ref.go
public/static/js/projects.js
public/static/partials/patch_trigger_alias_modal.html
service/project.go
service/templates/projects.html

Users will eventually specify aliases to include tasks from other projects in their patch. This PR allows project admins to define the aliases that users will specify. It's mostly modeled after trigger definitions.

EVG-13050 patch trigger aliases

---

rest/data/host_create.go
rest/data/host_create_test.go
rest/route/host_create_test.go

The [documentation](https://github.com/evergreen-ci/evergreen/wiki/Project-Commands#host-create) says that the default will be the distro security group IDs, but in the code itself we pull from the admin settings default, which isn't even set, so host.create validation doesn't error but the actual host creation doesn't work because no security groups were given to the host.

EVG-8162 host.create should default to distro security group IDs

---

agent/agent.go
agent/task.go
config.go

Not changed in this pr: if a task restarts and runs immediately on the same host, we don't consider that a new task group. That's probably the right behavior, but it may be unintuitive

EVG-12966 redo group setup if switching to a different tg in same build

---

operations/host.go
operations/host_provision.go
operations/host_setup.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go

JIRA: https://jira.mongodb.org/browse/EVG-13282
* Add REST communicator method to get host provisioning script.
* Write CLI command to execute the host provisioning script.

EVG-13282: create CLI command to fetch and execute host provisioning script

---

config.go
model/patch/cli_intent.go
model/patch/patch.go
operations/http.go
operations/model.go
operations/patch.go
operations/patch_util.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go
rest/route/project.go
rest/route/service.go
service/api_patch.go

Thread trigger aliases through from the CLI to the patch document.
The actual work of creating the child patches for those aliases will be implemented later.

EVG-13077 specify patch trigger aliases from the CLI

---

model/project_ref.go
public/static/js/projects.js
public/static/partials/patch_trigger_alias_modal.html
service/templates/projects.html

Allow users to specify multiple sets of "task specifiers" within a single alias. A "task specifier" now consists of either a set of regexes for task and variant or an existing patch alias.
Also fix some bugs from https://github.com/evergreen-ci/evergreen/pull/4172.

EVG-13050 add more ways to select tasks with trigger aliases

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/patchBuildVariants/queries/patch-build-variants.graphql
graphql/tests/patchBuildVariants/results.json

https://jira.mongodb.org/browse/EVG-8324
These code changes will help enable the patch restart modal to filter by tasks' base status.
`PatchBuildVariantTask` is returned from the `patchBuildVariants` query is currently utilized to render the "Build Variants" card and Restart Patch modal checkboxes. 
A difference between the two use cases is that the "Build Variants" card doesn't need base task statuses. It would have been nice to conditionally resolve the baseStatus field so querying `patchBuildVariants` doesn't make superfluous mongodb queries.     
There are 3 other ways we could have done this but they all turned out to be insufficient solutions:
Option 1) `patchBuildVariants` returns the gql type below and conditionally resolves the base field.
```
type PatchBuildVariantsResult { …
```

EVG-8324: Add baseStatus field to PatchBuildVariantTask gql type

---

operations/commit_queue.go
operations/model.go
operations/model_test.go
operations/patch.go
operations/patch_util.go

- instead of prompting for a default project do it automatically
- add a new structure to store default projects per directory, as well as a flag to stop the automatic defaulting
I'll add documentation on this before merging
Output looks something like
john@johns-MacBook-Pro foo % clients/darwin_amd64/evergreen -c ~/.evergreenstaging.yml patch -p mci -y
Patch successfully created.
ID : 5fb43a689dbe32678001c3a0
Created : 2020-11-17 21:02:33.035 +0000 UTC
Description : EVG-12664: wip
Build : https://evergreen-staging.corp.mongodb.com//patch/5fb43a689dbe32678001c3a0
Status : created
Project 'mci' will be set as the one to use for directory '/Users/john/go/src/github.com/evergreen-ci/evergreen'. To disable automatic defaulting, set 'dont_set_default_project' to true.

EVG-12664 set default project per directory

---

model/patch/github.go
model/patch/github_test.go
rest/route/github.go
units/github_status_api_test.go
units/patch_intent_test.go

not only does this allow someone internal pushing to a pr to automatically trigger pr checks, but also person A typing a retry comment on person B's pr will make person A own the patch, so person A gets the notifications

EVG-6833 use event initiator as patch author

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql

To account for abort messages in the UI other than tasks only being aborted by users

EVG-8229: add `newVersion` and `prClosed` to AbortInfo gql type

---

model/host/db.go
model/host/hostutil.go
model/host/hostutil_test.go
model/validate.go
model/validate_test.go
operations/host_provision.go
rest/data/host.go

JIRA: https://jira.mongodb.org/browse/EVG-13286
* Use intent host ID (i.e. the host tag) when checking host ID/secret instead of host ID/Jasper credentials ID (which isn't set yet).
* Put Evergreen client on the host before invoking Evergreen CLI command to provision the host.
* Write the shebang line to host provisioning script.
* Connect stdout/stderr directly to output of host provisioning script rather than storing it in memory and then logging it.

EVG-13286: fix small bugs from test fetching host provisioning script

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/annotationIssue/queries/addIssue.graphql
graphql/tests/annotationIssue/queries/addSuspectedIssue.graphql
graphql/tests/annotationIssue/results.json

For EVG-13158, I chose to use annotationId instead of taskId/execution because we know the annotation already exists, but in this case we don't. Should this return the annotationId for the page reload or does is make sense that we'd look up the annotation again on the UI side?

EVG-13159 add mutation to add annotation issue

---

graphql/resolvers.go
graphql/util.go
model/patch_lifecycle.go
model/project_ref.go
model/project_ref_test.go
rest/data/project.go
rest/data/repotracker.go
rest/route/middleware.go
rest/route/project.go
scheduler/task_finder.go
service/api.go
service/api_patch.go
service/api_task.go
service/middleware.go
service/project.go
service/rest_project.go
service/spawn.go
units/crons.go
units/patch_intent.go
units/periodic_builds.go
units/repotracker.go
units/repotracker_test.go
units/version_activation_catchup.go

There are a few settings with project (detailed in the [design](https://docs.google.com/document/d/1Nrlg_2vZ6Ejr2egQYl4amie_gjv4OcyjHKKjP0Q2mOI/edit#heading=h.2s9zdv6a57gn)) that should be considered at the repo-level, if we're using repo settings. I believe the way to modify the least code is to get the project ref merged with the repo ref, in the instances that we need it.

EVG-13270 get merged project when repo settings are used

---

graphql/integration_atomic_test.go
graphql/integration_spec.json
graphql/resolvers.go
graphql/tests/abortTask/data.json
graphql/tests/abortTask/queries/commit-queue-dequeue.graphql
graphql/tests/abortTask/results.json
graphql/tests/unschedulePatchTasks/data.json
graphql/tests/unschedulePatchTasks/queries/commit-queue-dequeue.graphql
graphql/tests/unschedulePatchTasks/results.json
graphql/util.go
model/task_lifecycle.go
service/task.go

This consolidates some things, but the outstanding parts that aren't consolidated would be more messy if they were I think. Also adds a way to run some additional assertions for the graphql tests

EVG-7382 consolidate calls to remove from commit queue

---

config.go
config_api.go
environment.go
environment_test.go
operations/update.go
rest/data/cli_update.go
rest/model/cli_update.go
rest/route/cli_version.go
service/templates/admin.html

JIRA: https://jira.mongodb.org/browse/EVG-13428
Try downloading the binary from S3 and fall back to downloading from the app server if it fails. The self-updater logic won't take effect until people update their binaries after this commit, so this CLI update will still be downloaded from the app server.

EVG-13428: prefer updating CLIs from S3 URL

---

rest/data/cli_update.go

JIRA: https://jira.mongodb.org/browse/EVG-13428
Small optimization to ensure that if the feature flag is disabled, it won't return the S3 URLs to the client.

EVG-13428: do not return S3 URLs if S3 binary downloads are disabled

---

model/host/hostutil.go
operations/host_provision.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go
rest/data/host.go
rest/data/host_test.go
rest/data/interface.go
rest/model/host.go
rest/route/host.go
rest/route/host_test.go
rest/route/service.go

JIRA: https://jira.mongodb.org/browse/EVG-13455
It appears that when user data runs a PowerShell script on Windows, it hangs after a partial execution of the host provisioning script if it receives too much output from Cygwin's shell. This may or may not be due to Unix line endings not flushing the buffered output on Windows, but I can't find any docs proving that this is the case.
Instead of writing the Jasper credentials to a file (a symptom of the problem), instead, I removed `set -o verbose` from the Windows distro setup script and from the remainder of the host provisioning script.
* Remove verbose output from Windows user data.
* Rename a few things in the host provisioning REST route.

EVG-13455: do not use verbose output when provisioning WIndows hosts

---

agent/util/archive_tar.go
config.go

so I'm not sure this actually fixes it since I can't repro it but I'm optimistic.
I noticed that many of the times when the panic happened it was in pairs. https://github.com/evergreen-ci/evergreen/blob/6c7f57d597bd07a0c6f26e4d489a7287020074ae/agent/command/archive_tarball_create.go#L141 panics with message "index > windowEnd" and https://github.com/evergreen-ci/evergreen/blob/6c7f57d597bd07a0c6f26e4d489a7287020074ae/agent/util/archive_tar.go#L109 panics with an index out of bounds. These shouldn't both be hit with how the code attempts to sort of making the process synchronous, so this pr makes it actually synchronous
highly recommend viewing the diff with the ignore whitespace box checked

EVG-13351 fix race in archive.targz_pack

---

model/project_ref.go
model/project_ref_test.go
model/repo_ref.go
rest/route/project.go
service/project.go

Per our conversation, it seems best for the project ref to use repoID to reference repo. 
I chose this instead of using Owner/Repo to query because in the future, when all projects have repo refs, I actually think Owner/Repo should be removed from projectRef, and this should only be available in the repo ref. That way, if the name of an owner/repo is changed, this affects all project refs without having to update more than the one document.

EVG-13497 use repoID to find repo_ref instead of owner_repo

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/annotationIssue/data.json
graphql/tests/annotationIssue/queries/editNote.graphql
graphql/tests/annotationIssue/queries/editNoteInvalid.graphql
graphql/tests/annotationIssue/results.json
model/annotations/db.go
model/annotations/task_annotations.go

I forgot that we'd be using Upsert for the annotation update, since we wouldn't know yet if the annotation existed, so to verify that the note hasn't been updated already we have to do a find query first. If we aren't concerned about users looking at very inconsistent data, then we can probably drop this extra query, but since this resolver doesn't do much it's not a performance issue or anything.

EVG-13160 add mutation to edit annotation note

---

service/templates/projects.html

This is actually just for our own development; I don't want to confuse users into thinking this does something. (I'm just going to hide it entirely, because we can use the PATCH api route with {"use_repo_settings":<boolean>} to turn it on/off in most cases, and deploy without it hidden to staging/local if we need to test the UI)

EVG-13269 hide use repo settings

---

graphql/resolvers.go
graphql/util.go
rest/route/patch.go
service/patch.go

What I think happened is that if you cancel the request to finalize a patch from the web UI (by navigating away or hitting stop), it will propagate to the db operations. If you time it just right, you can get the data in an inconsistent state where the version is inserted but nothing else, so you'll hit this problem.
The actual fix should maybe be to put this in a transaction, but for now I think keeping the context separate is good enough

EVG-12602 isolate schedule patch context

---

gqlgen.yml
graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/project/data.json
graphql/tests/project/queries/patches-all-params.graphql
graphql/tests/project/queries/patches-default-params.graphql
graphql/tests/project/queries/patches-include-commit-queue.graphql
graphql/tests/project/queries/patches-nonexisting-user.graphql
graphql/tests/project/queries/patches-page-0-limit-3.graphql
graphql/tests/project/queries/patches-page-1-limit-3.graphql
graphql/tests/project/queries/patches-patchName.graphql
graphql/tests/project/queries/patches-statuses.graphql
graphql/tests/project/results.json
graphql/tests/user/data.json
graphql/tests/user/queries/patches-all-params.graphql
graphql/tests/user/queries/patches-default-params.graphql
graphql/tests/user/queries/patches-include-commit-queue.graphql
graphql/tests/user/queries/patches-nonexisting-user.graphql
graphql/tests/user/queries/patches-page-0-limit-3.graphql
graphql/tests/user/queries/patches-page-1-limit-3.graphql
graphql/tests/user/queries/patches-patchName.graphql
graphql/tests/user/queries/patches-statuses.graphql
graphql/tests/user/queries/patches-userId.graphql
graphql/tests/user/results.json
model/patch/db.go
rest/data/interface.go
rest/data/patch.go

https://jira.mongodb.org/browse/EVG-13229
These code changes utilize the existing Project gql type by adding a patches field to it and setting the base model to the ProjectRef struct instead of UIProjectFields (a pared down version of ProjectRef).
These code changes also add a patches field to the User gql type that is modeled after the UserPatches query so the UserPatches query can be removed ([EVG-13508](https://jira.mongodb.org/browse/EVG-13508)). The benefit of replacing gql query definitions with gql types is so developers can understand the type of data that can be queried by examining gql type fields instead of perusing our growing list of query definitions. It also prevents us from overloading queries to handle different resource types or adding additional queries that correlate …

EVG-13229: Query Project Patches 

---

cloud/userdata.go
cloud/userdata_test.go
model/distro/distro.go
model/host/hostutil.go
model/host/hostutil_test.go
rest/client/mock.go
rest/data/host.go
rest/data/host_test.go
rest/data/interface.go
rest/model/distro.go
rest/model/distro_test.go
rest/model/host.go
rest/route/distro_test.go
rest/route/host.go
rest/route/host_test.go
service/templates/distros.html
units/provisioning_user_data_done.go
units/provisioning_user_data_done_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13427
https://jira.mongodb.org/browse/EVG-13479
* Remove the temporary distro setting for fetching the host provisioning script. All distros now fetch the host provisioning script from the app server.
* Rename some host methods for clarity since the provisioning script does not execute directly in user data.
* Clean up some user data provisioning code paths which are no longer needed for tidiness.

EVG-13427, EVG-13479: remove fetch host provisioning script distro setting and clean up host provisioning script

---

rest/data/patch_intent.go
units/patch_intent.go

splunk logs for the date no longer exist so part of this is speculation
we can't be hitting a duplicate key for the _id because that's an object ID, so that leaves the only possible culprit being the github message ID. Github is probably not sending the same message ID twice, but we shouldn't necessarily rely on that. So my approach is to make the inserting a github intent part idempotent, which should get around a potential race in our code

EVG-7460 add some logging for github errors

---

model/patch/patch.go
model/patch_lifecycle.go

A commit queue version was created, but no builds/tasks were created with it, the patch was never marked as Activated, etc. This was a pretty frustrating bug, because this commit blocked the queue for a quite a while, and would be a hard state for us to write an unstick function for, since it's not a consistent state. From the splunk logs, it looks like we deployed or bounced, and this hit in between creating the parser project and creating the builds. A transaction would prevent this inconsistent state from occurring.

EVG-13312 use transaction in finalizePatch

---

thirdparty/github.go

In the previous fix for this, we assume that an APIRequestError has been returned.
https://github.com/evergreen-ci/evergreen/blob/7f3ad0d051fdb88d1b414d9c033c7866a5afcc31/service/api_plugin_manifest.go#L59
However, in the code itself, we hit this error, which is of the form APIResponseError, which has only a message.
https://github.com/evergreen-ci/evergreen/blob/7f3ad0d051fdb88d1b414d9c033c7866a5afcc31/thirdparty/github.go#L155
Really, the response is likely not nil, and if we correctly ran parseGithubErrorResponse(resp) then we would get a format that's more readable, and that the existing error check could understand. For simplicity, I moved this check into the existing initial `resp != nil` check for github functions.

EVG-13406 check for Not Found in manifest error message

---

model/commitqueue/commit_queue.go
model/commitqueue/github_merge_generic.go
model/event/commit_queue_event.go
model/patch/patch.go
model/patch/patch_test.go
rest/model/commit_queue.go
rest/model/commit_queue_test.go
rest/route/github.go
units/commit_queue.go
units/commit_queue_test.go

I am breaking backwards compatibility by removing a field, but I don't think anyone is using this

EVG-13387 use comment body as commit message for pr commit queue

---

cloud/docker_integration_test.go
self-tests.yml

The problem in the ticket is that the security group for the host running docker does not allow communication from static hosts and probably shouldn't. I decided to only run test-cloud on ubuntu since we don't need to test our cloud provider code on anything other than the architecture the servers are running on. I could have split off the docker integration test into a separate package but that would have required making a bunch of random things public

EVG-13446 only run test-cloud on ubuntu

---

service/templates/projects.html

Since we create our own commits with the changes in a CLI queue, handling the 3 merge methods would be different than how we handle them for merging PRs so I'm not implementing that. Also swapped the position of the queue type and merge method to better represent how the settings are hierarchically

EVG-7492 disable merge method for CLI commit queues

---

agent/agent_test.go

[Jira ticket](https://jira.mongodb.org/browse/EVG-12962)
The test currently gives the agent loop a millisecond to exit. Even if the loop goroutine has not yet run we will go on with the next test which races on the agent struct we're using in the loop goroutine this test created.
The best thing to do would be to wait indefinitely for an (hopefully nil) error back from loop, but that could block. Instead, settle for giving it up to 5 seconds to return, returning earlier if loop returns before the deadline.

EVG-12962 give loop more time to exit

---

service/api_patch.go

It's been a while that users submitting backports with an old CLI get an error. It _should_ be safe to silently ignore the backport request now, though we'll never know... 
At this point the alternative is to leave it in forever. I think if it's not removed it will become read-only code: we won't remember what the `data.BackportOf` field meant.

EVG-12872 really remove old backport specification

---

model/distro/distro.go

To begin with, regions were added to all distros with a dummy "ami-1234" AMI. Now that build's scripts are working again, all distros that can support multiple regions have been updated with real AMIs, and all dummy AMIs have been removed, so this is dead code.

EVG-12964 remove support for unconfigured distro regions

---

model/task_queue_service_dependency.go

The general problem was already fixed by https://github.com/evergreen-ci/evergreen/commit/f30bef32b4c99a24b4cd9441e7b256237f764c84 but this is an edge case that was not handled. If you have a generator create only execution tasks that would be blocked eventually without anything else in the display task running, we won't run the logic added in that commit. In this case the generator adds tasks that would be blocked due to a failure from outside the display task. This adds an extra check in a logical spot (where we check dependencies in the task queue).
I kind of hate this approach though. It also adds a small amount of work in a code path that's called a lot. Probably won't noticeably degrade performance at all, but it can add up. Suggestions of alternate approaches are welcome and I'll …

EVG-13418 keep display task in sync when updating blocked dependencies

---

units/crons.go

for some reason, a specific periodic build definition for a project wasn't running its jobs but other periodic builds were. I'm not sure whether readding the definition or a deploy fixed it, but this is just some logging to help debug

EVG-13679 add some logging for periodic builds

---

model/build/build.go
model/build/db.go
model/event/build_event.go
model/event/event_registry.go
model/event/subscriptions.go
model/event/version_event.go
model/lifecycle.go
model/project_aliases.go
model/project_aliases_test.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
public/static/js/projects.js
repotracker/repotracker.go
rest/route/project.go
service/project.go
service/templates/projects.html
trigger/build.go
trigger/build_test.go
trigger/version.go

I switched this over to a new trigger type, so that we wouldn't have to wait for the build/version to finish if the tasks/variants requested in the alias have been completed. (This could result in the github status being sent early, if generated tasks should be part of the alias, but the generator itself isn't part of the alias, but I argue this is unlikely.)
Example of failed:
Example from project page:

EVG-13573 filter tasks/variants for waterfall checks

---

api/host.go
service/host.go
service/host_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13593
When a host (usually a static host but sometimes an EC2 instance) is unquarantined, it might be in a state where it can't run the agent. For example, if the host is quarantined and the underlying host is replaced with a brand new host, it won't have the filesystem state necessary to run the agent monitor. This adds a special case where unquarantining a host and setting it to run again forces it to reprovision to ensure it's in the correct state.
* Reprovision hosts that transition from quarantined to running.
* Fix some weirdness in how the host status update route deals with HTTP status codes and success/error flash messages.

EVG-13593: reprovision unquarantined hosts

---

units/provisioning_create_host.go

prevent small distros from being stranded  when global max hosts is reached

EVG-13629: exception to prevent small distros from being stranded by global MaxTotalDynamicHosts

---

model/task/task.go
service/api.go

It's really hard to tell what's writing so many logs.
Add (temporary?) logging so we can figure it out and ask the culprit to hold off until we finish[ PM-1607](https://jira.mongodb.org/browse/PM-1607).

EVG-13693 add logging for test_logs volume

---

units/crons.go
units/periodic_builds.go

I'm using "RoundPartOfHour" because I like that it lines up with when periodic build jobs would be called. This will prevent deploys from creating periodic build madness.

EVG-13702 use timestamp instead of definition next runtime

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/patchTasks-aborted/data.json
graphql/tests/patchTasks/data.json
graphql/tests/patchTasks/queries/sort-by-base.graphql
graphql/tests/patchTasks/results.json
graphql/util.go
model/task/db.go
model/task/task.go
rest/data/interface.go
rest/data/task.go
rest/model/generated.go
rest/model/schema/rest_model.graphql
rest/model/schema/type_mapping.yml
rest/model/task.go

- Add a new computed field in the task data structure that contains info about its base task. Right now it just includes ID and status but it's easy to add to
- Use this new field in the patchTasks query instead of the old method of adding the base status afterwards. This allows us to be able to filter and sort by base task data.
- Add a new sort parameter to the patchTask query that supports sorting by any of the columns. The old sorting params are kept for 1 deploy to maintain backwards compatibility, but will be removed ASAP (along with supporting code/tests)

EVG-13365 support multiple sorts for patch tasks

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/task_lifecycle_test.go
model/version.go
model/version_test.go
operations/commit_queue.go
operations/commit_queue_test.go
rest/data/commit_queue_test.go
rest/model/commit_queue.go
rest/route/admin_test.go
rest/route/commit_queue.go
rest/route/commit_queue_test.go
rest/route/github.go
rest/route/middleware.go
rest/route/middleware_test.go
units/commit_queue.go

This adds a new source field to commit queue entries and populates it from every entry point that can add to the cq (I think)
The general idea is that we'll use this field instead of the project ref setting to determine how to handle it. No migration is needed because the queue should be empty by the time I switch the logic to look at the field

EVG-13725 track cq source in individual items

---

model/project.go
model/project_parser.go
model/project_ref.go
model/project_ref_test.go
public/static/js/projects.js
rest/data/project.go
rest/model/project.go
rest/route/github.go
rest/route/middleware.go
rest/route/project.go
rest/route/project_copy.go
rest/route/project_copy_test.go
rest/route/project_test.go
service/middleware.go
service/project.go
service/templates/projects.html

Because ID is our internal immutable representation, it doesn't really make sense to have it be user-defined, since the identifier could be changed to something completely different and the ID could become misleading (and it could never be used as an identifier name for a future project). If I missed a spot where we use Identifier when we should use ID, then any new projects (that have different IDs / identifiers) may encounter a bug, and probably the only way to fix would be a hot fix (although it would be a relatively simple fix).
In staging I'd like to switch the mci and yb_mci projects to new projects, so they have different ID / Identifier (I tested some things already with a new yb_mci). Potentially in prod too, although this would switch over our waterfall and etc so maybe not …

EVG-13534 make project ref id separate from identifier

---

units/generate_tasks.go

What happened is that the first execution got terminated externally after the generate.tasks command ran. The timing was just right so that the generate job on the server hit the "task is not running, not generating tasks." However this still marks the task as having run its generators, so on the second execution we noop.
This pr changes this scenario to be an error (I believe this is ok to error, a bit of context on what was here previously in https://github.com/evergreen-ci/evergreen/pull/2684). Also don't mark the generators as having run if there are errors

EVG-12791 don't mark tasks generated if errors

---

config.go
model/host/db.go
operations/scheduler.go
rest/client/interface.go
rest/client/methods.go
rest/data/interface.go
rest/data/scheduler.go
rest/data/scheduler_test.go
rest/model/scheduler.go
rest/route/scheduler.go
scheduler/distro_alias_test.go
scheduler/scheduler.go
service/api_task.go
validator/distro_validator.go

It's most likely that task group tasks are racing when the hosts pick them up (again), but the existing logging doesn't actually imply that, so I added a little bit more logging, and modified the scheduler command to use the tunable logic (I didn't go super deep into that though; fleshing out the reasoning can be done in EVG-13795).

EVG-13555 task group debugging

---

units/generate_tasks.go

This reverts the specific change to make this check an error. While I don't understand why it failed here while the task was running, in the past this has allowed scenarios where a task was stranded to continue generating tasks, so I believe it's appropriate to revert

EVG-13808 make task status check a warning again

---

agent/command/git_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13680
For some reason, the error message from git changed when running on the Docker image (maybe due to some image change). I just updated the error string.

EVG-13680: check for special host key verification message in Docker git test

---

service/api.go
units/task_monitor_execution_timeout.go

I'm actually seeing two issues with the task in this ticket:
1) The version is from Dec 2019, i.e. it has no parser project, but we don't get the version fields necessary for the legacy case of `LoadProjectForVersion`.
2) We mistakenly use the same logic for task groups / display tasks in `cleanUpTimedOutTask`, however they do have different paths. TryResetTask handles the task group case already, we don't need to special case it in `cleanUpTimedOutTask`. This is now consistent with ClearAndResetStrandedTask.

EVG-13780 fix restart single-host task group

---

units/crons.go
units/generate_tasks.go
units/generate_tasks_test.go

- add a scope to generate.tasks with the version ID so that all jobs within that version are serial
- make the job IDs only have the task ID in them (no timestamp), so that we don't enqueue more than 1 job for the same generator
- move the jobs from the group queue to the regular remote queue since there is no need to have them in a group anymore

EVG-13834 add scope to generate.tasks

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_test.go
cloud/ec2_util.go

JIRA: https://jira.mongodb.org/browse/EVG-13874
Include instance and volume tags with the `RunInstances` request for the on-demand provider and no-op the tagging in `OnUp()`, since the resources are already tagged.
For spot instances, we have to keep the existing behavior because the instances can't be tagged in the spot instance request, so we have to wait until the instance ID is available from `GetInstanceStatuses()`. It shouldn't be a problem since we've replace regular spot requests with spot fleet.

EVG-13874: tag on demand hosts in initial request

---

model/task/task.go
model/task/task_test.go

Really EVG-13555 is open to investigate a race condition, but I realized that some of the linked tasks fail because they've been manually scheduled by a user, and the required earlier tasks in the group aren't also scheduled.

EVG-13555 include earlier task group tasks as dependencies

---

model/host/host.go
units/host_status.go
units/host_status_test.go
units/host_termination_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13876
If the host is stopped externally (i.e. because of the reaper), terminate it. I didn't try attempting to just set the host to starting because it'll add complexity for a rare case which should not happen (i.e. dealing with agent monitor deploys, resetting any task that it may have picked up before the reaper stopped it, etc). It's simplest to just treat a stopped host like an externally-terminated spot host.

EVG-13876: terminate stopped hosts in set-cloud-hosts-ready

---

model/host/host.go

JIRA: https://jira.mongodb.org/browse/EVG-13833
The `$unset` portion of the upsert might be empty and MQL doesn't like it when you do `{"$unset": {}}`.

EVG-13833: don't specify unset in host upsert if there are no fields to unset

---

units/host_monitoring_external_termination.go
units/host_monitoring_external_termination_test.go
units/host_status.go
units/task_monitor_execution_timeout.go
units/task_monitor_execution_timeout_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13878
* Treat a stopped host as externally terminated and merge the cases (the host termination job will operate the same on a stopped/terminated instance except it'll also terminate a stopped cloud instance).
* Include an event log for external termination if it's caught by set-cloud-hosts-ready.

EVG-13878: handle stopped host in external termination check

---

cloud/ec2.go
units/host_status.go

JIRA: https://jira.mongodb.org/browse/EVG-13764
* Add logging (including timing info) for potentially long cloud provider requests so we can diagnose if the job is taking a long time to finish its requests.
* Update the comments in set-cloud-hosts-ready to be more precise about what it's doing.

EVG-13764: add logging and improve comments on set-cloud-hosts-ready

---

graphql/tests/patchTasks/results.json
model/task/db.go
model/task/task.go

The only change here is to the stage we had in the aggregation to get tasks for a patch. Instead of just sorting failed above everything else, we instead assign numbers to statuses corresponding to their color in the UI and sort by that

EVG-13882 sort patch tasks by color rather than label

---

service/api_task.go

This task group race occurs when the first task in the group comes after another task group, because then we do this [teardown step.](https://github.com/evergreen-ci/evergreen/blob/b58685992234364395c9a882e55da1a05e4222c1/service/api_task.go#L503) And then the next task doesn't hit any of the dispatch error catches. In my original work for EVG-7903, I tried a strict catch: `if nextTask.TaskGroupMaxHosts == 1 && nextTask.TaskGroupOrder > 1 then it's a race`. This ended up being too strict (if there's any bug with task group restarting, then a task can get stuck on the queue forever), so even though this version requires a DB lookup, it should be a rare enough case, and I believe if a previous task is technically dispatchable, it makes sense for later tasks to wait.

EVG-13555 check if previous task in task group is dispatchable

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/ui_plugin_build_baron.go
model/annotations/db.go
model/annotations/task_annotations.go
rest/model/task_annotations.go
service/ui_plugin_build_baron.go

In a separate ticket, I will create an api endpoint for teams to use to send back the ticket id of the ticket that was created. It will be stored in CreatedIssues. 
@khelif96 and @SupaJoon, I'm adding you because it touches the resolvers and schema but I checked and made sure that it doesn't break Spruce. (I made it nullable, but will probably change it once the Spruce part which I'll do in a separate ticket is deployed). Feel free to skip reviewing this, I just wanted you to be aware of it.

EVG-13166 Backend function that files a ticket

---

rest/route/middleware.go

There was a chicken/egg problem. The changed code checks to see if you're the owner of the commit queue item you're trying to change, and looks for the entry on the commit queue to see if it needs to check the patch author or PR owner. However this also runs before the route that actually puts something on the queue so there's nothing to check. Also I tested this twice in staging and have no idea how that passed, but that's a problem for later

EVG-13750 don't check for existing item in commit queue middleware

---

glide.lock
model/host/host.go
model/host/host_test.go
vendor/github.com/evergreen-ci/certdepot/.golangci.yml
vendor/github.com/evergreen-ci/certdepot/LICENSE
vendor/github.com/evergreen-ci/certdepot/README.rst
vendor/github.com/evergreen-ci/certdepot/cmd/run-linter/run-linter.go
vendor/github.com/evergreen-ci/certdepot/db_test.go
vendor/github.com/evergreen-ci/certdepot/depot_test.go
vendor/github.com/evergreen-ci/certdepot/evergreen.yaml
vendor/github.com/evergreen-ci/certdepot/file.go
vendor/github.com/evergreen-ci/certdepot/glide.lock
vendor/github.com/evergreen-ci/certdepot/interface.go
vendor/github.com/evergreen-ci/certdepot/makefile
vendor/github.com/evergreen-ci/certdepot/mgo_depot.go
vendor/github.com/evergreen-ci/certdepot/mongodb_depot.go
vendor/github.com/evergreen-ci/certdepot/mongodb_options.go
vendor/github.com/evergreen-ci/certdepot/superset.go

JIRA: https://jira.mongodb.org/browse/EVG-13931
Static hosts typically have a hostname as their host ID. The host ID is used the server name and common name on the Jasper gRPC certificates, which is fine when the host ID is a hostname. However, some static hosts might only have an IP address and not a hostname. The gRPC client doesn't seem to be able to connect when the common name is an IP address. This change adds the IP address and hostnames as subject alternative names (SANs) in Jasper certificates, so those will also be valid server names when connecting to Jasper's gRPC service using TLS credentials. It should be backwards compatible since we're just adding SANs to new host certificates.
* Revendor certdepot.
* Include IP addresses and domains in Jasper certificates.

EVG-13931: include hostname and IP addresses in Jasper certificates

---

agent/command/host_list.go
agent/internal/client/interface.go
agent/internal/client/methods.go
agent/internal/client/mock.go
config.go
model/task/db.go
model/task/task.go
model/task/task_test.go
rest/model/listhost.go
rest/route/host_create.go
units/provisioning_create_host.go

I decided to store "host_id" with the error, since that might help us investigate issues that aren't AWS capacity, and also because there might be multiple hosts. 
https://evergreen-staging.corp.mongodb.com/task_log_raw/mci_ubuntu1604_test_cloud_patch_d04dfaa265a05c6e26d704930ca54b63e2f15c36_6019b0cf97b1d3353309a45b_21_02_02_20_06_49/2?type=T#L257

EVG-13724 log host.create errors in host.list

---

agent/command/exec.go
agent/command/exec_test.go
agent/command/shell.go
agent/command/shell_test.go
config.go

JIRA: https://jira.mongodb.org/browse/EVG-13690
I mirrored the behavior of environment variables for `subprocess.exec` in `shell.exec` so they should behave identically with regards to `env`, `add_expansions_to_env` and `include_expansions_in_env`. Both of them set the same default variables (e.g. agent variables, temp dirs, gocache).
One minor change that I did make was I made the agent environment variables override any custom ones set by expansions or an explicit setting in `env`, but I don't think it matters since no project is using these variables for anything. Before, it was possible for expansion variables to override the agent variables.

EVG-13690: add environment variables to shell.exec

---

rest/route/stats.go

I was using go1.15 locally and forgot that go1.9 does not have `http.RequestWithContext`.

EVG-7778: Fix build

---

service/api_task.go

while looking at thresholds for a response time alert, I'm seeing unusually long response times in next_task for specific distros again so I added logging for a specific distro that seems problematic

EVG-13904 temporary logging for next_task

---

agent/command/git_merge_pr.go
agent/internal/client/interface.go
agent/internal/client/methods.go
agent/internal/client/mock.go
config.go
model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/event/subscribers.go
model/event/subscribers_test.go
model/notification/notification.go
model/notification/notification_test.go
model/patch/patch.go
model/task_lifecycle_test.go
operations/commit_queue_test.go
rest/data/commit_queue.go
rest/data/commit_queue_test.go
rest/data/interface.go
rest/model/subscriber.go
rest/model/subscriber_test.go
rest/route/commit_queue.go
service/api_plugin_git.go
trigger/payloads.go
units/commit_queue.go
units/commit_queue_test.go
units/event_notifier.go
units/event_send.go
units/event_send_test.go
validator/project_validator.go

Really the only new thing here is that commit queue entries from prs will now be merged in a task rather than through the notification system. I removed about half of the old code using the notification system, specifically the parts that were adding subscriptions. I left in the parts that process notifications so that unfinished pr merges from when this is deployed will still work

EVG-13932 merge prs in a task

---

rest/route/service.go
rest/route/stats.go

This has no code changes, just recommits what was reverted. Cedar now returns 404s when it cannot find historical test data, which will then cause this route to fall back to the legacy evg test stats lookup.

EVG-7778: Recommit test stats passthrough

---

cloud/ec2_client.go
cloud/ec2_fleet.go
units/host_status.go

JIRA: https://jira.mongodb.org/browse/EVG-13763
I set the max backoff to 10 seconds, in `utility.Retry` it defaults to `min * 2^maxAttempts` which in this case would be 1024 secs.

EVG-13763: Put limits on the max duration for AWS calls

---

graphql/tests/patchTasks/queries/sorts.graphql
graphql/tests/patchTasks/results.json
model/task/task.go

I had left a line of code in from the old sort logic, so that's gone now. I still need to remove the old sort parameter in the schema, but that needs to happen after spruce switches to the new array sorting param on the patch tasks table

EVG-14047 fix wrong sort logic on patch tasks table

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14048
`~/.profile` and `~/.bash_profile` might be owned by root since the user data script runs as root, so change it back to the regular distro  user.

EVG-14048: change owner of shell profile files to distro user

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/patchTasks-aborted/results.json
graphql/tests/patchTasks/queries/all-params.graphql
graphql/tests/patchTasks/queries/sort-base-status-descending.graphql
graphql/tests/patchTasks/queries/sort-by-base-status.graphql
graphql/tests/patchTasks/queries/sort-by-name.graphql
graphql/tests/patchTasks/queries/sort-by-status.graphql
graphql/tests/patchTasks/queries/sort-by-variant.graphql
graphql/tests/patchTasks/queries/sort-descending.graphql
graphql/tests/patchTasks/results.json
rest/data/interface.go
rest/data/task.go

This removes the scalar sortBy and sortDir parameters in favor of the array one. Most of the random test ordering changes were due to the sorting respecting the default sort by ID if nothing else was specified

EVG-14047 remove obsolete sort param

---

rest/route/github.go

Because the retry might take a long time, (and it should, in cases where the tag and the commit are being pushed at the same time, in order to give the version time to be build), iterate through all the projects before handling the retry timing. This is most significant for repos like server that have lots of enabled projects.

EVG-13336 iterate through projects for git tag before retrying

---

model/task/task.go
model/task/task_test.go
units/generate_tasks.go
units/generate_tasks_test.go

my approach was to split the steps to mark that a task has generated tasks with errors from it, so that we can record errors without having to mark generation complete

EVG-14022 record generate.tasks errors

---

config.go
model/patch/cli_intent.go
model/patch/db.go
model/patch/db_test.go
model/patch/github.go
model/patch/intent.go
model/patch/trigger_intent.go
model/project.go
operations/http.go
operations/patch.go
operations/patch_util.go
service/api_patch.go
units/patch_intent.go
units/patch_intent_test.go

This reuses the task/variant definition for the previous scheduled patch (excludes PR and CLI patches).

EVG-12476 add --reuse option for patch definitions

---

agent/command/results_utils_test.go

JIRA: https://jira.mongodb.org/browse/EVG-13464
I missed these broken unit tests because I wrote them off as flaky agent-command tests. Since we are now using the buildlogger protobuf file that takes `[]byte` instead of `string` we need to use `assert.EqualValues` instead of `assert.Equal` in the unit tests when comparing the input and output.

EVG-13464: Fix unit agent-command tests

---

operations/patch.go
validator/project_validator.go

I think I just didn't allow this because I didn't see a reason, and it's the logic we use for other KEY=VALUE pairs, but server has requested to be able to use = in values. I'll update the docs to say = just can't be in the key.
http://evergreen-staging.spruce.s3-website-us-east-1.amazonaws.com/version/6034038db2373615ef3edf12/tasks

EVG-14121 allow = in parameter values

---

model/project_ref.go
model/project_ref_test.go
model/project_vars.go
repotracker/wrappers.go
rest/data/project.go
rest/data/repotracker.go
rest/route/repo_test.go
scheduler/task_finder.go
service/api.go
service/api_task.go
service/project.go
units/crons.go
units/patch_intent.go

If PR testing is set up for the repo, then we still create PRs for branches, even if they aren't enabled. 
I had some trouble deciding if "branch project exists but is disabled" should still create a PR. I decided on yes, because that is still an "untracked branch". 
Potentially RepoRefs should have some option "allow_untracked_branch_prs", as opposed to just checking if it has all the components to run checks, but I'm assuming it doesn't hurt to have checks added? I could be convinced either way. 
"Hidden" projects were an idea from Brian, to avoid lots of skeleton projects, where the PRs aren't attached to each other. i.e. say we do some testing with "new_branch", and then we decide to actually start tracking "new_branch": it would be ideal if the PRs from earlier were still attached to …

EVG-13279 allow PR testing for untracked branches

---

api/host.go
graphql/resolvers.go
makefile
model/host/host.go
service/api_task.go
service/api_task_test.go
service/distros.go
service/host.go
service/host_test.go
units/crons.go
units/util.go

JIRA: https://jira.mongodb.org/browse/EVG-14102
* Enqueue the reprovisioning job ASAP when initiated from a REST request. Before this, the cron job would only check if the job needs to reprovision once an hour, so after clicking the UI button, you would have to wait an hour for it to reprovision.
* Do some small refactoring to unify the logic to enqueue reprovisioning jobs.
* Minor change to the makefile to only set `GOCONVEY_REPORTER` if it's not already set (because sometimes, it's actually helpful to see the output from goconvey).

EVG-14102: enqueue reprovision job immediately within REST request

---

model/task/task.go

Query Execution time for fetching tasks for https://spruce.mongodb.com/version/5ea9c9fc7742ae2842c23bb3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Before this change: 2127 ms
After this change: 435 ms

EVG-13841 Move execution task lookup to later stage of pipeline

---

service/task.go

Other buildlogger fallback code logs at warning.

EVG-14019 Make log levels for buildlogger fallback consistent

---

model/project_ref.go
model/project_ref_test.go
model/project_vars_test.go
model/repo_ref.go
rest/route/project_test.go
rest/route/repo_test.go

This was your idea @john-m-liu but a stakeholder asked recently if something like this would be possible so that works out. If a value is common across all projects (including aliases/variables), then it's assigned to the repo ref as well. This doesn't actually work for embedded structs (i.e. it's not recursive), but I think this is close enough, since it's mostly meant to be helpful.

EVG-13467 assign values to repo ref that are common across branch projects

---

model/patch_lifecycle.go

It only makes sense to `set -o xtrace` in the agent, since the entire output of the shell script is visible. In the patch lifecycle, this executes on the app server. Since the stderr logger is set to the error level, we end up with xtrace debugging output in Splunk. Instead, we should only log to stderr if there really is an error.

EVG-13560 Don't set xtrace in patch lifecycle

---

glide.lock
model/project_ref.go
rest/data/aliases.go
rest/data/interface.go
rest/data/project.go
rest/model/project.go
rest/route/project.go
rest/route/project_test.go
rest/route/repo.go
vendor/github.com/evergreen-ci/utility/http.go
vendor/github.com/evergreen-ci/utility/optional.go
vendor/github.com/evergreen-ci/utility/parsing.go
vendor/github.com/evergreen-ci/utility/slice.go
vendor/github.com/evergreen-ci/utility/time.go

For the patch route testing, we should consider the merged project, so we don't incorrectly error about aliases, for example.
In testing this PR I found a couple of bugs:
- Because the service routes passed the bool pointers directly, changing one bool would also change the other, so I made a new utility function.
- Some of the service functions still return an initialized string slice, rather than a nil string slice, for nil input.
If these changes are approved, I'll make a utility PR for those pieces.

EVG-14080 use merged project in patch route validation

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql

This is the first in a series of PRs that will allow us to migrate all of our subset task fields( `PatchBuildVariantTask`, `TaskResul`t) to be Full fledged Task fields.
This first pr adds a few of the `Task` Fields to the subset task fields. Most importantly `execution` which apollo uses to identify `Task` objects.

EVG-14187 Add necessary fields to allow transition to Task type

---

apimodels/task_log.go
service/task.go

JIRA: https://jira.mongodb.org/browse/EVG-14115
I also had to make a change to specify `ALL` logs for the legacy task log page.

EVG-14115: add group id to test logs route

---

model/task/task.go
model/task_history.go
service/task.go
service/task_history.go

It looks like a number of individuals are using this route ([splunk query](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20%22message%22%3D%22got%20test%20names%22%20OR%20%22message%22%3D%22error%20getting%20test%20names%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-7d%40h&latest=now&workload_pool=standard_perf&sid=1614714013.262064)), so I don't think we should get rid of it, but I think some things can be simplified (especially because this route isn't documented so we haven't made any specific promises).
1) It doesn't seem necessary to get the build variants first; By nature of searching the display name in the second query and sorting by revision, we're already filtering the build variants.
2) Added project name to the …

EVG-14007 simplify test_names query

---

globals.go
model/lifecycle.go
model/lifecycle_test.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go
model/version.go
rest/data/version_test.go

- Looked through the list of fields in the task data model and added more that are reset when you restart a task. The problem with the host not getting cleared was always present on the old task page, but no one reported it
- When a task is restarted, also reset the status of the build and version to "started" if it wasn't that already
- When all tasks in a version are restarted, also reset the status of the version to "started." Both of these status changes can have some non-obvious side effects, but I think they're the right change to make. The inconsistency was not noticeable in the old UI even though the old data model always had this problem, because we did not show a version status at all

EVG-14108 reset more data when restarting tasks

---

model/host/hostutil.go
units/provisioning_agent_deploy.go

JIRA: https://jira.mongodb.org/browse/EVG-13561
* Return both stdout and stderr from SSH commands instead of just stdout.
* Remove the Splunk log for stderr in SSH commands.

EVG-13561: remove extra error log for SSH error

---

model/task_history.go

So we use the index branch_1_r_1_display_name_1_create_time_1

EVG-14007 sort to use correct index

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql

Right now this only applies to the UI. Extending it to the API routes would require messing with the middleware, which is pretty complicated and I argue unnecessary. This is something we could maybe revisit if someone is having an issue, but I don't expect this.

EVG-14221 patch author should have annotation access

---

public/static/js/projects.js
service/project.go
service/templates/projects.html

Rather than add ng-disabled to _every_ box on the legacy page, I added a warning to the top and bottom of the page that it's currently read only, and disabled the save button. I think it's okay to expect users to use the new UI to detach from repo, if they have a need for this page.
Top:
Bottom:

EVG-13305 make legacy page read-only if using repo settings

---

agent/command/git.go
agent/command/git_test.go
config.go

This changes the existing code that checks out github's hidden merge branch to more closely match their recommendation in https://docs.github.com/en/rest/guides/getting-started-with-the-git-database-api#checking-mergeability-of-pull-requests. We poll that (with a timeout of 10 secs) until they either tell us the pr is definitely mergeable or not. If it's mergeable we get the most up-to-date merge hash

EVG-14251 change pr check in git.get_project to handle HEAD moving

---

config_db.go
config_serviceflags.go
model/project_ref.go
rest/model/admin.go
service/templates/admin.html
units/crons.go
units/crons_remote_fifteen_minute.go

Disabled the repo poller a couple of months ago to verify it wouldn't be an issue to take it out. (https://jira.mongodb.org/browse/EVG-13594).

EVG-13655 remove repo poller

---

rest/route/service.go

I'm wondering if this route can actually be combined with the existing /versions route that I didn't know about so I'm just going to remove it for now, since it's not documented yet anyway.

EVG-13777 remove duplicate route

---

model/repo_ref.go
model/repo_ref_test.go

We discussed in DMs making some function that returned roles that had a superset of the resources requested, but I realized that'd be risky given superuser roles and stuff like that. Since we already know what the names of repo roles will be, the safest option would just be to use them.

EVG-14206 update repo roles without using resources

---

cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
cloud/ec2_test.go

Jira: https://jira.mongodb.org/browse/EVG-13889
When you ask AWS for all the instance types supported in an AZ they seem to leave some out. For example, if you run this from the command line
```
aws ec2 describe-instance-type-offerings --location-type availability-zone --filters Name=availability-zone,Values=us-east-1a
```
the list returned doesn't include a1.2xlarge.
Getting all the AZs that support a particular instance type works, though
```
aws ec2 describe-instance-type-offerings --location-type availability-zone --filters Name=instance-type,Values=a1.2xlarge
```
The downside to doing it this way is that we need to do one API call for each instance type as opposed to one for each AZ. This might not make such a difference, though, since distros use the same instance type.

EVG-13889 fetch by instance type

---

model/version.go
model/version_test.go
rest/data/interface.go
rest/data/project.go
rest/model/version.go
rest/route/project.go
rest/route/project_test.go
rest/route/service.go

1. I realized this was doing all versions, not just repotracker versions.
2. If we choose ByBuildVariant, we should filter out versions that don't have that build variant activated, I would guess.
3. I want to drop the task cache if we don't have IncludeTasks, because we aren't guaranteeing that the task cache is accurate.

EVG-13777 tweak versions for project logic

---

agent/command/git_merge_pr.go
config.go
graphql/tests/abortTask/data.json
graphql/tests/unschedulePatchTasks/data.json
graphql/tests/unschedulePatchTasks/queries/commit-queue-dequeue.graphql
graphql/tests/unschedulePatchTasks/results.json
graphql/util.go
model/build/db.go
model/patch_lifecycle.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
rest/data/commit_queue.go
service/build.go
units/commit_queue.go

The bulk of this fixes a problem where the current behavior of unscheduling the entire version when a commit queue task fails causes us to not update github with the failure (the status will remain the yellow circle) because the merge task does not run, and previously the merge task is what updated github with the outcome of the commit queue patch. This moves that logic to the app server.
Also fixed some related bugs I found while testing, which I'll annotate

EVG-14248 send github statuses on app server

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/annotations/queries/moveIssueToSuspectedIssue.graphql
graphql/tests/annotations/queries/moveSuspectedIssueToIssue.graphql
model/annotations/db.go
model/annotations/task_annotations.go
model/annotations/task_annotations_test.go
rest/route/annotations_test.go
self-tests.yml

This would go with https://github.com/evergreen-ci/spruce/pull/687. 
We weren't actually running annotation tests in ubuntu1604, which explains why they only broke in coverage. Because annotation IDs are stored in the DB as object IDs, but we access them as strings, we can't insert annotations the way we currently do in tests. The options were either to 1) switch to using taskId and execution like the other queries, or 2) change annotation IDs to be bson.ObjectIds in the code. Both require a change in spruce and evergreen, so I chose the first for consistency. 
This would need to be deployed with spruce so if we don't do that anymore then I guess we make a separate mutation? I'd argue for just deploying at the same time, since only the "Move Issue" button would be broken until the deploy …

EVG-14146 use taskID and execution for instead of annotation ID

---

graphql/generated.go
graphql/schema.graphql
graphql/tests/taskTests/queries/execution-task-group-id.graphql
graphql/tests/taskTests/results.json

https://jira.mongodb.org/browse/EVG-14222
these fields will be useful in lobster url generation from spruce

EVG-14222: Add execution and taskId fields to TestResults gql type

---

agent/agent.go
agent/agent_command_test.go
agent/agent_test.go
agent/agent_timeout_test.go
agent/logging_test.go
agent/task.go
config.go

Currently we maintain if the setup group needs to be run. This tweaks the definition a bit to maintain if the setup group _has_ been run, and if it hasn't we assume it needs to be run. This is for task groups, where the first task on a host may have system failed for other reasons; we want the next task for that group on the host to try to run setup group.

EVG-13505 mark if setup group has been completed in agent

---

model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/commitqueue/db.go
units/commit_queue.go

- add the processing start time back in to the data model, but it needs to be item-specific now
- add a check that the merge task is scheduled and not blocked in the commit queue job

EVG-13799 more sanity checks in commit queue job

---

rest/route/service.go

so I don't exactly understand the difference between what was there before and now, just that the handler wasn't called before but it is now

EVG-13984 correctly wrap CORS middleware

---

model/task_history.go
service/task_history.go

I'm not sure if this will be faster but we are logging how long the query takes, I can make a graph at some point and see if it improved.
Jonathan recommended using the go driver so that we could cancel if the query takes too long, so we don't get another 71 minute thing. Theoretically that's what SetSocketTimeout was supposed to do, but I couldn't really figure out how anser worked.

EVG-14263 use mongo driver for test_names aggregation

---

service/task_history.go

I want to know how long the query takes even if the context is cancelled or something. Not changing the message name because I want it to match older logs.

EVG-14263 log test_names_query_secs even if error

---

agent/agent.go
config.go
public/static/partials/hostevent.html

It's _possible_ that BF-20000 could be fixed by the recent changes to setup group logic, but I think those changes made setup group _less_ strict, not more strict. I'd like to add logging to figure out why we're deciding to run setup group, when another task in the task group had already run immediately before.

EVG-14151 add setup group logging

---

agent/command/git_merge_pr.go
config.go
model/patch/patch.go
model/patch/patch_test.go
rest/data/commit_queue.go
thirdparty/github.go
units/commit_queue.go

I had thought that github uses the pr title as the commit title if you leave it blank, but apparently this is not always true. I'm now explicitly passing it as the title

EVG-14298 explicitly use commit title in github api

---

rest/route/test.go

This error message was introduced last week in EVG-14201; however, certain scripts rely on this not being an error.

EVG-14299 remove empty tests error from route

---

model/patch_lifecycle.go
model/task_lifecycle.go
units/commit_queue.go

nope, the problem is actually that users are either manually restarting things in the commit queue, or pushing to prs that abort the commit queue merge

EVG-14326 don't restart unstarted versions in commit queue

---

glide.lock
model/project_ref.go
public/static/js/projects.js
service/middleware.go
service/project.go
service/templates/menu.html
service/templates/projects.html
vendor/github.com/evergreen-ci/gimlet/.golangci.yml
vendor/github.com/evergreen-ci/gimlet/cmd/run-linter/run-linter.go
vendor/github.com/evergreen-ci/gimlet/middleware_auth.go
vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager.go
vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager_test.go

This fixes the easier half of the ticket. We're no longer checking all projects to see if the user is the admin of at least 1, to see if the "projects" option should show in the menu. This means that someone who is an admin in no projects still sees the dropdown option which will lead to the "Awkward..." page. It's not the ideal experience but I think it's fine. It should noticeably decrease the load time on every page
Also this exposes an existing bug where someone with no roles will hit a runtime error on the projects page, but someone with no roles would have bigger problems anyway
Ok also added the second half, which reduces the number of queries we do on the project page

EVG-14261 remove project admin check in old UI

---

model/host/host.go
rest/route/host.go
rest/route/host_test.go
rest/route/service.go

I also intended to create a job to terminate the hosts, in case it took too long and the route timed out, but I forgot that we had switched to modifying expiration instead of terminating the host directly, in order to speed up the process. I'd like to push this even more by only modifying the DB NoExpiration field, (Jonathan's [original suggestion](https://jira.mongodb.org/browse/EVG-12852)), so that we don't keep pushing out the expiration date in AWS, and the host/volume will expire naturally. This prevents us from relying on AWS speed at all.

EVG-14147 change input to offboard user route

---

model/status_diff.go
model/task/task.go
public/static/js/task.js
service/task.go

JIRA: https://jira.mongodb.org/browse/EVG-13974
I ran a patch resmoke patch build and realized that the current status diff on the patch task page does not support cedar test results. This fixes it.
@khelif96 I am not sure if this is also the case on the spruce UI, so just wanted to bring it to your attention in case it is.

EVG-13974: Update status diff on the task page to support cedar test results

---

graphql/resolvers.go

Noticed a nil pointer error being thrown when fetching task tests without an execution

EVG-13884 nil pointer dereference fix

---

model/task_queue_service.go
model/task_queue_service_dependency.go

The amount of time RefreshFindNextTask takes unsurprisingly seems pretty correlated to task queue length, and most of this functions seems pretty optimized. This part of the function seems optional though; I'm wondering if we should move this to a job rather than updating right here. We could also increase the TTL so we refresh less often (we refresh this every minute; this has been the standard though).

EVG-14148 log checkUnmarkedBlockingTasks

---

agent/task.go
cloud/docker_client.go
config.go
model/host/hostutil.go
units/provisioning_agent_deploy.go

- consolidate the agent command we use for docker with the one we use for normal hosts
- make a failure to clear the dmesg buffer not fail the task

EVG-14347 correctly pass provider flag for containers

---

rest/data/commit_queue_test.go
units/commit_queue.go
validator/project_validator.go
validator/project_validator_test.go

The problem was that the script which created the generated config had a bug which resulted a distro array with a null entry (in json). You might expect that this hits a type error when we try to unmarshal the json into a struct with a type of []string, but it does not. There is some churn in https://github.com/golang/go/issues/33835 as to whether that's a bug or not and how to handle it, but this validation should work around that and also seems reasonable enough to add

EVG-13554 disallow blank distros in config

---

agent/command/results_utils.go
agent/command/results_utils_test.go
apimodels/test_results.go
config.go
rest/data/interface.go
rest/data/test.go
rest/data/test_test.go
rest/model/test.go
rest/route/test.go

JIRA: https://jira.mongodb.org/browse/EVG-14159
- Set the test name field for cedar test results to a random unique id and set the display test name and log test name to the test file name if they are not already set.
- Add a new parameter `test_id` to the `rest/v2/tasks/{task_id}/tests` to fetch tests by the unique test id (since test names can be duplicated and lobster uses this route to fetch individual test results).

EVG-14159: Allow duplicate test names in cedar test results

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/commitQueue/data.json
graphql/tests/patch-taskStatuses/data.json
graphql/tests/patch/data.json
graphql/tests/patchBuildVariants/data.json
graphql/util.go
model/project_ref.go
rest/data/patch.go
rest/data/patch_test.go
rest/model/patch.go
rest/model/patch_test.go
trigger/patch_test.go
trigger/payloads_test.go
units/crons_event_test.go

For this example, ID is "evergreen" and Identifier is "my_evergreen". This needs to be deployed before the spruce changes.
Patch Page: 
Task Page:
My Patches Page:

EVG-14328 use project identifier for patch workflow

---

model/project_parser.go

I tested this by inserting a "legacy" document into the DB and then running validation; it fails without this change, and passes with it.

EVG-13023 consider legacy parser project case

---

model/lifecycle.go
model/lifecycle_test.go
model/matrix_smoke_test.go
model/patch_lifecycle_test.go
model/project.go
model/project_parser.go
model/project_parser_test.go
model/project_selector.go
model/project_test.go
repotracker/repotracker.go
repotracker/repotracker_test.go
validator/project_validator.go
validator/project_validator_test.go

Revert parser project logic because it won't be backwards compatible. Then we can deploy the real logic on Monday, with this check baked in, in case of revert. This should also fix the existing "must either specify" errors.

EVG-13023 revert merging until backwards compatibility is deployed

---

agent/command/shell.go
config.go

Anna and Jonathan were basically spot on in their explanation of what the problem is. sshing from a script will hijack stdin for the process, but the script itself is being fed to stdin so that will prevent further commands from being fed to the shell
I verified that this works with a test that involves sshing but I don't want to commit a test that uses ssh

EVG-13667 add shell.exec param to execute as string

---

model/lifecycle.go
model/lifecycle_test.go
model/matrix_smoke_test.go
model/patch_lifecycle_test.go
model/project.go
model/project_parser.go
model/project_parser_test.go
model/project_selector.go
model/project_test.go
repotracker/repotracker.go
repotracker/repotracker_test.go
validator/project_validator.go
validator/project_validator_test.go

This reverts commit b3bea4f09c6be8e90eb138b1cd04e7f9fd112f7f.
Backwards compatibility is now baked in, so if we do need to revert this commit, the old code will know how to handle the project saved with "run_on" as opposed to "distros".

EVG-13023 reintroduce merging task and bv task def when parsing project

---

model/lifecycle.go
model/task/task.go
model/task/task_test.go

Part one of this ticket was to make sure the project was stored correctly (i.e. new execution tasks were added to the display task definitions). Now we need to actually add them to the existing display task document; I think that'll be the last step, but the easiest way to test this is with the server project on prod.

EVG-14249 add generated et IDs to existing dts

---

model/task_queue.go
model/task_queue_service.go
model/task_queue_service_dependency.go
model/task_queue_service_test.go
model/task_queue_test.go
service/api_task.go
units/check_blocked_tasks.go

Rational is from [this logging](https://mongodb.splunkcloud.com/en-US/account/login?return_to=%2Fen-US%2Fapp%2Fsearch%2Fsearch%3Fq%3Dsearch%2520index%253Devergreen%2520%2522operation%2522%253D%2522checkUnmarkedBlockingTasks%2522%2520%257C%2520sort%2520-total_duration_secs%26display.page.search.mode%3Dverbose%26dispatch.sample_ratio%3D1%26earliest%3D-24h%2540h%26latest%3Dnow%26workload_pool%3Dstandard_perf%26display.page.search.tab%3Devents%26display.general.type%3Devents%26sid%3D1617978301.626792); sometimes checkUnmarkedBlockingTasks is more than 2 or even 3 minutes; it seems like it's not actually necessary to be done right in the function, since we just continue anyway, so pushing it out to a job should improve things.

EVG-14148 move checking dependencies into a job

---

model/task/task.go

There were lots of inconsistencies between what happens if you restart 1 task vs. restarting many, and the 2 fields in the tickets were among them

EVG-14162, EVG-14262 consistently set fields on restarts

---

service/api.go

yes the double negative is supposed to be there
the problem is that in https://github.com/evergreen-ci/evergreen/blob/50a2312b023bc644415284e0f4d7780f1c2579e6/agent/command/expansion_write.go#L40, we treat having a variable in the private map as being private without checking the value. I didn't want to change that behavior so I instead made the response for patch params consistent with non-private expansions

EVG-14434 don't not set patch params as private

---

agent/util/subtree_linux.go
config.go

- read the executable of the process we're going to kill without actually reading the symlink, which might avoid the error in the ticket
- log the error that's returned to help with debugging

EVG-13566 tweak check for procs to kill in agent

---

model/lifecycle.go
model/task/task.go
model/task/task_test.go

I made a mistake in my previous PR: here I was assuming that any task that has been added to the display task would be a newly generated task, but that's not even the case I'm testing; here it's the generator task itself that's being put into the display task. The [createDisplayTask](https://github.com/evergreen-ci/evergreen/blob/f9f3ae2eb91b28d307064a20f64dbaed0e772428/model/lifecycle.go#L1422) function assumes that every execution task that has an ID in the execTable can be added directly to the display task, so we can make that assumption too.

EVG-14249 add exec tasks without checking if they're newly generated

---

model/task_queue_service_dependency.go

So far not seeing anything significant but I'd like to give it a bit more time before removing the job, since the consequences involve a stuck task (https://jira.mongodb.org/browse/EVG-14465)

EVG-14148 log check unmarked tasks only when significant

---

globals.go
makefile
model/distro/distro.go
self-tests.yml

JIRA: https://jira.mongodb.org/browse/EVG-14488
* Add distro support to use MacOS ARM64 agents.
* Run archlinux tests on go1.16.

EVG-14488: add distro architecture for MacOS ARM64

---

rest/model/task_annotations.go

This is a quick fix that takes the jiraKey from the url to fix this: 
Todo in future tickets: let users leave the display task blank, change how the display text is shown, and validate the key before saving.

EVG-14025 Error loading task when Jira Ticket key does not exist

---

units/duplicate_task_check.go

Jira: https://jira.mongodb.org/browse/EVG-14517
Reduce the log level for this. While this is still a correctness problem and tasks might dispatch multiple times to different hosts, I'm hoping this check can go away, but it requires [EVG-14516](https://jira.mongodb.org/browse/EVG-14516). I'm going to change it to a Splunk alert so that at least we can silence it if it gets too noisy.

EVG-14517: reduce logging level for duplicate task check

---

scripts/verify-agent-version-update.sh

Jira: https://jira.mongodb.org/browse/EVG-14529
The agent update checker didn't detect a change in `agent/internal/client/client.go` because of shell quoting issues.

EVG-14529: fix shell quotes in git diff for verify-agent-version-update

---

config.go
operations/commit_queue.go

I still can't see how this ever worked and went back to about HEAD~1000 to verify that the problem is there too. We clearly don't expect the ref flag to be passed with the commits flag (https://github.com/evergreen-ci/evergreen/blob/433529c8e1a85d82f0fcc98bed808d61be647ce1/operations/commit_queue.go#L142) but the ref flag has a default, so if you pass the commit flag at all we get into a bad state

EVG-14474 don't default compare HEAD when specifying commit range

---

makefile
units/crons.go
units/crons_remote_fifteen_second.go
units/crons_remote_minute.go
units/host_status.go
units/provisioning_user_data_done.go

Jira: https://jira.mongodb.org/browse/EVG-13546
* Use scopes on user data done jobs that apply when the job is enqueued.
* Make the job retryable, enqueue it in the set-cloud-hosts-ready job (which is the provisioning step before the user-data-done job runs), and populate the job less often (because set-cloud-hosts-ready will most likely initiate the job).

EVG-13546: use scopes/retryability in user data done job

---

globals.go
model/project_ref.go
public/static/js/projects.js

This project was completed before we added granular options for auth, which is why users had to specify github usernames and teams directly on the project page. Now we can add this to mana as a regular entitlement (but we should still support the existing workflow). 
I added some changes to a different branch: https://github.com/evergreen-ci/evergreen/compare/main...ablack12:EVG-13787-part2 for after MANA adds the new setting.

EVG-13787 add mana permissions for triggering git tag versions

---

rest/route/github.go
rest/route/github_test.go
thirdparty/github.go

The webhook information we get from Github is inconsistent; sometimes HeadCommit doesn't exist, sometimes it contains the wrong hash, etc. There's an API call that will get us tag information just using the tag name, but the library doesn't have a method for it so I'm calling it directly.
Tested this by pushing a lightweight tag and an annotated tag on staging, and verifying that a version was created from the right commit.

EVG-14357 lookup tagged commit with github API

---

agent/agent.go
agent/command/git.go
agent/command/git_push.go
agent/command/git_test.go
agent/command/testdata/git/test_config.yml
agent/command/util.go
agent/internal/task_config.go
apimodels/agent_models.go
config.go
operations/fetch.go
service/rest_task.go

- expand the module prefix string in git.get_project and git.push
- write the expanded string to the task end details
- modify the fetch CLI command to get the module prefix from the task end details if it's there

EVG-13676 support expansions in module prefixes

---

units/provisioning_create_host.go

Jira: https://jira.mongodb.org/browse/EVG-13548
* Apply scopes on enqueue and use built-in retries for create host job instead of relying on custom logic.
* I changed how MaxTime works so it no longer does this weird math that [sets MaxTime and subtracts a minute](https://github.com/evergreen-ci/evergreen/compare/main...Kimchelly:EVG-13548_create_host_scope_on_enqueue?expand=1#diff-6b133b12148c168c83fab4e96d489178b67f63cf8122f991429464d0c8a331c8L419), but I don't think it's consequential to remove this because it hasn't caused any issues up to now and MaxTime didn't work until recently anyways.
* Add host create errors whenever the job errors rather than when the job fails to re-enqueue. @ablack12 I don't know if populating errors every time the job errors will cause any issues with …

EVG-13548: apply scopes on enqueue and retry in create host job

---

units/host_setup_script.go
units/provisioning_setup_host.go
units/provisioning_user_data_done.go

Jira: https://jira.mongodb.org/browse/EVG-13552
* Use scopes and retries in job that runs a script after task data has been fetched on a host.
* Remove custom retry logic.

EVG-13552: set scope and retries in spawn host task data setup script job

---

model/task_queue_test.go
units/check_blocked_tasks.go

So, this job isn't doing anything right now (it's taking absolutely [no time to execute](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20%22job_type%22%3D%22check_blocked_tasks%22%20%7C%20timechart%20avg(dispatch_secs)%20span%3D15m&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-14d%40d&latest=now&workload_pool=standard_perf&display.page.search.tab=visualizations&display.general.type=visualizations&sid=1619801084.270734) relative to when the job was initially introduced) but I have no idea why really. The function itself is the same as it [was when it was introduced](https://github.com/evergreen-ci/evergreen/commit/18b8936a5109dfce40df16829fa00fd85f919b02), and similar to how it worked in the original function, and similar to how …

EVG-14465-2 add logging to check blocked tasks job

---

model/host/host.go
units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go

Jira: https://jira.mongodb.org/browse/EVG-13549
* Clear the flag indicating that the host still needs to deploy an agent/agent monitor once the respective job succeeds.
* Remove unused atomic variants of methods.

EVG-13549: unset needs new agent/agent monitor flag once deploy succeeds

---

units/crons.go
units/generate_tasks.go
units/generate_tasks_test.go

The logic for this is mostly pulled from #4336.
* Add scope to generate tasks using version ID to serialize generate task jobs within a version.
* Move the job from the queue group to the regular queue.

EVG-13888: add scope and retries to generate tasks job

---

units/check_blocked_tasks.go

Definitely learning a lot about an unfamiliar part of the codebase with this job 🤦‍♀️  Evidently there are multiple "get task queue" functions with different purposes; the one I was using was more specific and it doesn't include dependencies, which is something we explicitly need. Find should do what we need, because it just loads in the whole queue.

EVG-14665 get entire distro queue from DB for job

---

api/host.go
rest/route/aws.go
units/crons.go
units/host_monitoring_idle_termination.go
units/host_status.go
units/host_termination.go
units/provisioning_user_data_done.go

Jira: https://jira.mongodb.org/browse/EVG-14369
* Use scope for host termination job.
* Ignore duplicate job/job scope errors in all places where it's enqueued.

EVG-14369: use scope for host termination job

---

trigger/build.go
trigger/commit_queue.go
trigger/patch.go
trigger/task.go
trigger/version.go

Changed this for all the notifications (this affects the templates [here](https://github.com/evergreen-ci/evergreen/blob/29ab59687b2dcff93f3530d1d8571c7830cb8bd8/trigger/payloads.go#L65) (everywhere with `.Project`)

EVG-14449 use project name in notifications

---

units/crons.go
units/scheduler.go
units/scheduler_alias.go

Jira: https://jira.mongodb.org/browse/EVG-14373
* Add scopes for distro (i.e. primary task queue) and distro alias (i.e. secondary task queue) schedulers.
* Removed unused field from distro scheduler job.

EVG-14373: use scopes in distro scheduler jobs

---

units/crons.go
units/oldest_image_removal.go

Jira: https://jira.mongodb.org/browse/EVG-14370
Use scopes for job to remove oldest image from a Docker parent host.

EVG-14370: use scopes for oldest image removal job

---

units/crons.go
units/generate_tasks.go
units/generate_tasks_test.go

It seems like there are a lot of system failures in the server waterfall caused by timeouts during generate tasks. I don't see anything amiss in amboy itself and the generate tasks jobs are running quickly, so I feel like this is an issue with the version-level lock contention.

Revert "EVG-13888: add scope and retries to generate tasks job (#4640)"

---

agent/internal/client/client.go
agent/internal/client/methods.go
agent/internal/client/mock.go
apimodels/cedar_models.go
config.go
config_cedar.go
glide.lock
rest/model/admin.go
service/api.go
service/api_cedar.go
service/api_cedar_test.go
service/templates/admin.html
vendor/github.com/evergreen-ci/timber/evergreen.yaml
vendor/github.com/evergreen-ci/timber/glide.lock
vendor/github.com/evergreen-ci/timber/makefile
vendor/github.com/evergreen-ci/timber/setup.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/.golangci.yml
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/auth.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/auth_test.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/cmd/run-linter/run-linter.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/dial.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/dial_test.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/glide.lock
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/makefile
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/retry.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/retry_test.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar_test.go

JIRA: https://jira.mongodb.org/browse/EVG-14557
Adds temporary code fallback code that sets up the cedar grpc client connection without TLS first then with TLS if it fails so we don't break a bunch of tasks as we switch over.

EVG-14557: Revendor timber and update cedar client connection

---

config_test/project/mci-test.yml

Some of our tests read this file from github; with yaml-v3, it's an error to have duplicate keys in a map (which seems reasonable). I'd like to make sure all the tests pass on the [yaml revendor](https://github.com/evergreen-ci/evergreen/pull/4638/files) before testing against all configs (if we can't use the new yaml yet because other configs have duplicate keys, then I think we'll have to hold off, but I'd like to make sure there are no other unit testable bugs before going through that process).

EVG-14227 remove duplicate params from test

---

agent/internal/client/client.go
config.go

Jira: https://jira.mongodb.org/browse/EVG-14583
The smoke test is panicking because the system metrics client is attempting to dial into cedar without any credentials. The gRPC call to the health check panics if the connection passed in is `nil`. Therefore, only attempt to dial the health endpoint if `DialCedar` doesn't error.

EVG-14583: avoid panic if dialing cedar errors

---

units/provisioning_convert_host_to_legacy.go
units/provisioning_convert_host_to_new.go
units/provisioning_restart_jasper.go

Jira: https://jira.mongodb.org/browse/EVG-14505
If the static host can't reprovision after 50 attempts, it's probably safe to assume it's in a bad state.

EVG-14505: quarantine static hosts that use up all reprovision attempts

---

graphql/http_handler.go
graphql/integration_atomic_test.go
graphql/integration_test.go

This adds tooling to support query performance analysis in the graphql playground. 
https://github.com/apollographql/apollo-tracing

EVG-14602 Add apollo tracing support to graphql server

---

model/patch/patch.go
trigger/patch.go

The child patches used to appear as evergreen/project/lastFourOfChildPatchId. This didn't work with "evergreen retry" since it creates a new version, and the new child patch didn't overwrite the previous one since the context was different.

EVG-14431 Make githubContext for child patches less unique 

---

glide.lock
model/event/host_event.go
units/host_termination.go
units/provisioning_agent_deploy.go
units/provisioning_setup_host.go
units/provisioning_user_data_done.go
vendor/github.com/mongodb/amboy/interface.go
vendor/github.com/mongodb/amboy/job/base.go
vendor/github.com/mongodb/amboy/queue/dispatcher.go
vendor/github.com/mongodb/amboy/queue/driver_mongo.go
vendor/github.com/mongodb/amboy/queue/limited_serializable.go
vendor/github.com/mongodb/amboy/queue/remote_base.go
vendor/github.com/mongodb/amboy/queue/retry.go
vendor/github.com/mongodb/amboy/queue/retry_test.go

Jira: https://jira.mongodb.org/browse/EVG-14605
If the job to check when user data provisioning is done uses up all its retries, then it's likely that the host failed to provision and the host won't be transitioned from starting to running. In this case, log a host event indicating that provisioning failed.

EVG-14605: log an event when check user data done job fails to verify that a spawn host is provisioned

---

units/provisioning_agent_monitor_deploy.go

Jira: https://jira.mongodb.org/browse/EVG-14621
The agent monitor deploy job checks if the agent monitor is alive first before attempting to deploy a new one. If it's alive, the needs new agent monitor flag should be cleared to prevent further unnecessary deploys.

EVG-14621: clear the agent monitor flag if the agent monitor is still alive

---

graphql/generated.go
graphql/models_gen.go
graphql/schema.graphql
graphql/tests/patch/queries/projectVariantsAndTasks.graphql
graphql/tests/patch/results.json

now that the spruce change is baked in, we can remove the redundant tasks field

EVG-14074 remove obsolete field

---

environment.go
glide.lock
units/host_allocator.go
vendor/github.com/mongodb/amboy/queue/dispatcher.go
vendor/github.com/mongodb/amboy/queue/dispatcher_test.go
vendor/github.com/mongodb/amboy/queue/driver.go
vendor/github.com/mongodb/amboy/queue/driver_mongo.go
vendor/github.com/mongodb/amboy/queue/group_remote_mongo.go
vendor/github.com/mongodb/amboy/queue/group_remote_mongo_single.go
vendor/github.com/mongodb/amboy/queue/queue_test.go
vendor/github.com/mongodb/amboy/queue/remote.go
vendor/github.com/mongodb/amboy/queue/remote_base.go
vendor/github.com/mongodb/amboy/queue/retry_test.go

Jira: https://jira.mongodb.org/browse/EVG-14617
* Revendor amboy to 4ce920c4d6786f247e28dab752b53b478663b9c2.
* Remove unnecessary duplicate check in global environment setup.
* Fix a bug in the host allocator where it can panic because the environment is never initialized.

EVG-14617: revendor amboy

---

self-tests.yml

Jira: https://jira.mongodb.org/browse/EVG-14524
MacOS doesn't run Docker, so skip the cloud provider tests.

EVG-14524: exclude test-cloud from MacOS buildvariant

---

units/provisioning_setup_host.go

Jira: https://jira.mongodb.org/browse/EVG-14637
`runHostSetup` decommissions the host if any of the methods fail, but it should only decommission the host if the setup script fails. When setting up Jasper, the most likely failure reason is because SSH can't establsh a connection yet, so it should retry in that case. I moved the Jasper setup out of `runHostSetup` to account for this.

EVG-14637: retry provisioning setup host job if SSH fails to connect

---

makefile

Jira: https://jira.mongodb.org/browse/EVG-14502
* Upgrade golangci-lint to 1.40.

EVG-14502: upgrade linter

---

self-tests.yml

`add_expansions_to_env: true` in `run-make` caused a breaking collision on windows. Setting `add_expansions_to_env: true` in the individual task command did not work. To work around this, I created a duplicate function specifically for the auth test, which is the only test that requires `add_expansions_to_env: true`.

EVG-14625: fix interaction with windows tests

---

mock/environment.go

Jira: https://jira.mongodb.org/browse/EVG-14649
Setting true vs false here toggles whether or not Jasper's child processes are terminated in the mock environment using cgroups in Linux/job objects in Windows, which might help clean up child processes better. Since we can't even use those features in CI tests, I just disabled them.

EVG-14649: do not track processes in mock environment

---

agent/command/git.go
config.go

Before this change, Execute() called executeLoop() in a loop. executeLoop() created a github.Client if one did not already exist in its receiver. However, to create this github.Client, it first constructed an http.Client by asking for one from the httpClient pool. It deferred putting it back into the pool until the end of executeLoop(). This is a bug. Putting it back in the pool unset its token. The next time the loop in Execute() calls executeLoop(), the http.Client's token was unset.
Separately, this change increases the time between retries for checking the mergeability of a pull request. The GitHub docs explicitly ask that you poll, which we do. However, https://docs.github.com/en/rest/guides/getting-started-with-the-git-database-api does not explain what a reasonable polling interval …

EVG-14522 Return http.Client to pool after github.Client is done

---

graphql/resolvers.go
model/patch_lifecycle.go
rest/route/commit_queue.go

When we enqueue patch commit queue items we don't set patchID, just the Issue (we use patchID for PRs I believe), so we don't display them correctly unless the version is created (in which case versionID is set and we correctly populate patchId here). 
We could just check issue ID in the CommitQueue resolver in addition to version and issue rather than populating patchID, but I think it's confusing to maintain a field that exists for both sources but is only maintained for one.
Context: patchId is the source of this bug because without it we default to the "Pull Request #\<issue\>" format [in Spruce](https://github.com/evergreen-ci/spruce/blob/15f0bc7839be439712b7b597b0cce75c3cda95f7/src/pages/commitqueue/CommitQueueCard.tsx#L74)

EVG-14418 consider the commit queue issue for the patch ID

---

agent/internal/client/request.go
config.go

Legacy test logs and attach files is sometimes returning "unexpected end of JSON input" which is confusing since we're using the same structs on both sides.

EVG-14564 log information about failing API requests

---

globals.go
model/build/build.go
model/generate.go
model/lifecycle.go
model/patch_lifecycle.go
model/project.go
model/project_parser.go
model/project_parser_test.go
model/project_ref.go
model/version.go
model/version_activation.go
repotracker/repotracker.go
validator/project_validator.go
validator/project_validator_test.go

This allows `"activate": true` or `"activate": false` to be provided from a generator or from the yaml. The default for `activate` is `true`. This can be given at the build variant and the task level, where the task configuration overrides the build variant. If a task is a dependency for an activated task or has a batchtime then an `"activate": false` would be ignored. This should also cover https://jira.mongodb.org/browse/EVG-1579 (although it adds a new field rather than having a zero batchtime field, it actually does work by specifying the zero field for batchtime and using the existing batchtime activation logic).
Tested this with different configurations of yaml on sandbox staging, as well as modifying sandbox's evergreen.json.

EVG-14310 add activated option to tasks/variants

---

graphql/ui_plugin_build_baron.go
plugin/build_baron.go
plugin/perf.go

Truly the build baron plugin should use the ID but I'm not sure where that's generated; is it user generated? Do we construct it somewhere? @malikchaya2 may have context on that. If that's something that we can use to use IDs instead of identifiers then we should, because if identifiers change then the plugin project name would also need to change, but if it's not something we can control then we should just both as a "better safe than sorry".

EVG-14676 check identifier and ID when getting build baron

---

service/api.go
validator/project_validator.go

To be deployed ahead of https://github.com/evergreen-ci/evergreen/pull/4701 so if that needs to be reverted, we'll have this baked in to be able to read the ValidationInput format.

EVG-14513 add validator change for backwards compatability

---

agent/command/results_utils.go
agent/command/results_utils_test.go
agent/internal/task_config.go
config.go

JIRA: https://jira.mongodb.org/browse/EVG-14684
This saves the cedar test results ID in the task config, which lasts for the life time of a task run, and uses the id if it already exists to upload test results to cedar.

EVG-14684: Allow test results to be uploaded multiple times

---

trigger/version.go

[EVG-14567 ](https://jira.mongodb.org/browse/EVG-14567 )
Periodic build notifications aren't sending, because non-patches (waterfall builds, periodic builds, git tag versions) don't have patches, so isReady is being set to false.
Not tested; reasoned over.

EVG-14567 skip notifications patch isReady check for non-patches

---

agent/command/results_utils.go
agent/command/results_utils_test.go
agent/internal/client/interface.go
agent/internal/client/methods.go
agent/internal/client/mock.go
apimodels/cedar_models.go
config.go
model/task/db.go
model/task/task.go
model/task_lifecycle_test.go
rest/route/service.go
rest/route/task.go

JIRA: https://jira.mongodb.org/browse/EVG-14159
This sets a new field `CedarResultsFailed` in Task to `true` if any of the test results sent to cedar failed. This way the task can correctly mark itself as `Failed` in `MarkEnd`.
I also ran a task with failing tests in staging and checked the DB to assert that `CedarResultsFailed` was set to `true` and that it was not set for tasks with passing tests.

EVG-14159: Send cedar test results status to task

---

trigger/patch.go
trigger/version.go

[EVG-14700](https://jira.mongodb.org/browse/EVG-14700)
When a status was sent for a notification for a parent patch that waited on a child patch, it only overwrote the status if the child patch failed. However, in cases when the child finished after the parent and the parent failed, the status would show as success if the child succeeded. This change overwrites the status of the notification to be a collective status between the parent and children. It also extracts some duplicate code out to it's own function. 
Created a [pull request](https://github.com/evergreen-ci/commit-queue-sandbox/pull/233) on commit-queue-sandbox with a child patch, added a notification, and made sure the notification was sent after the child was done. Also watched the statuses being set for tasks on the bottom …

EVG-14700 Fix parent patch notifications showing the child status

---

self-tests.yml
validator/project_validator.go
validator/project_validator_test.go

[EVG-14269](https://jira.mongodb.org/browse/EVG-14269)
The work for specifying run_on for a task was actually done in EVG-13023 but we should add this to the validation. I also rearranged this validation a bit so that we can short-circuit if possible.
Added a unit test and [created a patch](https://spruce.mongodb.com/task/evergreen_ubuntu1604_dist_staging_patch_852a461d576e6e63091d465cabc6c58f8f0f0718_60b79fae0ae606776bbfec05_21_06_02_15_12_01/logs?execution=0) with a different run_on set at the task definition level.

EVG-14269 add validation check for task run_on field

---

model/task/task.go

[EVG-14736](https://jira.mongodb.org/browse/EVG-14736)
The field is set when a task has a failing test but not reset when the task is reset so all subsequent executions fail

EVG-14736 unset CedarResultsFailed when the task is reset

---

rest/data/commit_queue.go
rest/data/commit_queue_test.go
rest/route/github_test.go
units/patch_intent_test.go

[EVG-14665](https://jira.mongodb.org/browse/EVG-14665)
I realize the title is silly but I had to.
Some of our tests are failing since we switched out the Github APIs. Really unit tests shouldn't rely on third party libraries, this is part of why we have mocks. One of the failing tests lends itself well to a mock so I created a function for it; the other one relies heavily on Github/isn't really a useful test without it, so I removed it.
Verifying that the failing tests no longer fail.

EVG-14665 make evergreen (ever)green

---

globals.go
model/project_ref.go
model/repo_ref.go
model/user/user.go
rest/model/project.go
rest/route/project.go
rest/route/repo.go
rest/route/repo_test.go
service/project.go
testdata/local/scopes.json

[EVG-13986](https://jira.mongodb.org/browse/EVG-13986)
Sorry this is a kind of complicated PR. Let me know if this explanation could do with an in-person chat.
Right now we have an unrestricted projects scope, with an "all projects" scope parent. The issue is that when we move a project out of the unrestricted scope, we also remove it from "all projects". John said we were evidently also supposed to have a "restricted" projects scope (so the union of restricted & unrestricted would equal all_projects). So when this PR is approved I will add this scope (with the restricted projects) to staging/prod, and add them back to all_projects.
In terms of repos and projects: we want projects that don't have restricted/unrestricted explicitly defined to inherit the repo setting. I handled this by not …

EVG-13986 handle restricted better for repos and projects

---

units/provisioning_agent_monitor_deploy.go

[EVG-14677](https://jira.mongodb.org/browse/EVG-14677)
This PR fixes the error message from displaying data about the agent to displaying data about the agent monitor.
N/A

Fix error message from agent to agent monitor

---

model/generate.go

[EVG-14747](https://jira.mongodb.org/browse/EVG-14747)
This might be a temporary change; right now on the config side it's taking 25 minutes to generate all tasks/variants, which may be unacceptable (David is doing some refactoring to reduce it). We're interested to see how long it takes Evergreen / if it stresses out the system, so we need to increase these limits so that Evergreen actually generates the tasks.

EVG-14747 increase generate tasks task/version limit

---

agent/command/registry.go

[EVG-14056](https://jira.mongodb.org/browse/EVG-14056)
I realized when I was updating shrub that I had forgotten to add it to registry.

EVG-14056 add downstream_expansions.set

---

model/project_ref.go
rest/model/project.go
rest/route/project.go
rest/route/project_test.go
rest/route/repo.go

[EVG-14656](https://jira.mongodb.org/browse/EVG-14656)
We neglected to add PatchTriggerAliases to the APIProjectRef, meaning it can't be modified using the API.
After merging, will add to documentation.

EVG-14656 add patch trigger definitions to API project refs

---

model/project.go
model/project_test.go

[EVG-13919](https://jira.mongodb.org/browse/EVG-13919)
add github_merge_commit to expansion
added unittest
[trying to make pr on commit-queue-merge](https://evergreen-staging.corp.mongodb.com/task/sandbox_ubuntu1604_unit_tests_patch_1796475006a20fc8898fb59f30010631f0ef2784_60c25735b2373644ebd21234_21_06_10_18_18_11)

EVG-13919 Expose triggering Git commit hash as expansion

---

rest/route/aws.go

[EVG-14535](https://jira.mongodb.org/browse/EVG-14535)
This is intended as a more precise version of the SNS alert described in the ticket that we can use to see interruptions by distro. We previously only logged in situations where we terminated the host ourselves, but this logs in all cases where we get an alert and are able to match the alert to a host.

EVG-14535: add logging to interrupt handling

---

model/task/db.go
model/task/task.go
model/task/task_test.go
model/task/task_testresult_test.go
model/task_lifecycle.go
service/waterfall.go

[EVG-14594](https://jira.mongodb.org/browse/EVG-14594)
This PR does two things:
1. Sets a global limit for how many testresults DB calls we can make
2. Caches whether or not we should be looking up testresults at all
Since we're phasing off of storing testresults in the DB, this shouldn't add too much to the DB, but in the meantime it should speed up how the waterfall handles testresults (I decided to do this bc, looking at the data from the last three rows of the nodeJS waterfall, we were calling this function over 2500 times for tasks that don't even have failing tests.
Added a unit test and opened in local to verify the information gets cached as expected.

EVG-14594 store if legacy test results exist for task

---

units/provisioning_setup_host.go

Jira: https://jira.mongodb.org/browse/EVG-14797
* Wait in between attempts to retry setting up the job. Otherwise, it can run too quickly and use up all its attempts.
* Add more attempts in between setup host job attempts to ensure that hosts have at least 10 minutes to set up. If they take longer than that, they'll likely be caught by the idle host or host termination job anyways.

EVG-14797: wait in between setup host attempts

---

config.go
operations/admin_all_configs.go
operations/http.go
service/rest_version.go

[EVG-14227](https://jira.mongodb.org/browse/EVG-14227)
So my previous attempt to test yamls using all-configs with yaml v3 didn't catch the problems because we were using the project that we'd previously parsed and stored in the DB. Instead, we need to fetch the config directly from github so it's untouched.
This will result in a lot of API calls so it might be expensive; I'm going to call it at kind of an off time I think.
Tested via staging.

EVG-14227 fetch all-configs from github

---

model/project_ref.go
service/rest_version.go
thirdparty/github.go
units/periodic_builds.go

[EVG-14807](https://jira.mongodb.org/browse/EVG-14807)
In a couple of places (but not all) we mistakenly don't specify the branch from which to get the github files. I think that this field being called `hash` doesn't help, since it implies a commit specifically.
Not tested, but the docs and other uses of this function indicate that this is correct (testing will take a lot of setup and I'd like to merge this today).

EVG-14807 get github files from correct branch

---

model/project_ref.go
model/project_ref_test.go

[EVG-13303](https://jira.mongodb.org/browse/EVG-13303)
Update was only updating the first project that it found, whereas we want to pull the user from any document.

EVG-13303 use update all to remove admins from project

---

agent/util/archive_tar.go
config.go

[EVG-14451](https://jira.mongodb.org/browse/EVG-14451)
I believe the problem is that `BuildArchive` https://github.com/evergreen-ci/evergreen/blob/b11532bc99dd2151d1f9d835556bc41fcc69ff58/agent/util/archive_tar.go#L20 calls `streamArchiveContents` https://github.com/evergreen-ci/evergreen/blob/b11532bc99dd2151d1f9d835556bc41fcc69ff58/agent/util/archive.go#L43, which returns a channel of `ArchiveContentFile` https://github.com/evergreen-ci/evergreen/blob/b11532bc99dd2151d1f9d835556bc41fcc69ff58/agent/util/archive.go#L16, which contains `os.FileInfo`, which is an interface. This means that `Mode()` panics if the interface points to a nil value https://github.com/evergreen-ci/evergreen/blob/b11532bc99dd2151d1f9d835556bc41fcc69ff58/agent/util/archive_tar.go#L37.
The problem is we don't check …

EVG-14451 Check for empty FileInfo

---

agent/command/git.go
agent/command/git_push.go
config.go

[EVG-14631](https://jira.mongodb.org/browse/EVG-14631)
Sometimes we log exit code 128 with no context. This is likely some internal error, but we were returning before logging the error message that describes the issue, so we haven't been giving any information on if this is something users should be concerned with or not.

EVG-14631 log error output before returning from git push

---

globals.go
model/task/db.go
model/task/task.go
rest/data/task_test.go

[EVG-13893](https://jira.mongodb.org/browse/EVG-13893)
This adds "known-issue" as the display status if there is a task annotation in the task annotation collection that matches the taskId, execution, and has at least one issue in the issue list. 
**Testing**
Tested with both a unit test, and by pushing the changes to staging and querying PatchTasks for  patchId: "6049134597b1d353b0ea9ce5" which has a task with a status of "known-issue". 
[Spruce changes](https://github.com/evergreen-ci/spruce/pull/753)

EVG-13893 Add Known Issue display status to task query

---

units/commit_queue.go

Jira: https://jira.mongodb.org/browse/EVG-14371
It should be invalid for multiple commit queue jobs to run concurrently for the same project. However, since it doesn't have scopes right now and it gets enqueued frequently (once per minute), if a job doesn't run within the minute it was enqueued, another one might be enqueued and run concurrently. Use scopes to ensure this does not occur.

EVG-14371: use scopes in commit queue job

---

config.go
operations/admin_all_configs.go

[EVG-14227](https://jira.mongodb.org/browse/EVG-14227)
When I refactored this, I didn't fix the boolean logic 🤦‍♀️  written as is, we're only downloading the configs for disabled projects.

EVG-14227 skip disabled projects for all configs command

---

globals.go
model/generate.go
repotracker/repotracker.go

[EVG-14855](https://jira.mongodb.org/browse/EVG-14855)
I purposefully only considered Activate for certain requesters to match the behavior of cron and batchtime, however these aren't truly doing the same thing. If our generate tasks does purposefully mark things as not activated, even in a patch build, we should respect that (this will make testing much simpler for DAG).

EVG-14855 consider activate in generate-tasks for all requesters

---

rest/route/patch.go
rest/route/patch_test.go

[EVG-5840](https://jira.mongodb.org/browse/EVG-5840)
This removes an error handling condition where a 404 not found exception was being thrown in the case where no patches for a given project are found.  Since this is a valid case a change has been made to instead return 200 OK and an empty list if this occurs.
Tested with mock data locally where a dummy project had no patches associated and observed that the behavior went from 404 exception to 200 OK after the change was made, and the endpoints behavior for other test projects was not affected.

EVG-5840: Remove 404 exceptions when receiving an empty patch array

---

agent/command/results_gotest.go
config.go

Change OptionalOutput to string and add a corresponding bool variable

EVG-14218 fix: Convert OptionalOutput parameter to string type

---

agent/command/expansion_write.go
config.go
model/generate.go
model/lifecycle.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go

[EVG-14635](https://jira.mongodb.org/browse/EVG-14635)
In a previous commit I added some logic to verify that we step back the generated task only if the tasks haven't been generated yet. However, I realized we also need to remember _which_ tasks to stepback (for example, if taskA is the task we need to stepback, but task_gen sets it to `activate: false` by default, we need to know to ignore that).
Added a unit test, tested in staging: [this failing generated task](https://evergreen-staging.corp.mongodb.com/task/sandbox_ubuntu1604_task_to_add_via_generator_e2023555d09c1bbcfbaa7660361e5a3e9747fc51_21_06_23_15_02_03) stepped back [this generator](https://evergreen-staging.corp.mongodb.com/task/sandbox_release_my_first_generator_9d0a02ad32777f19f22e90b18e41ec9b0b58fbe0_21_06_23_15_00_18) …

EVG-14635 remember which generated tasks need to be stepped back

---

rest/route/middleware.go

[EVG-14767](https://jira.mongodb.org/browse/EVG-14767)
Super unclear why CORS patch requests aren't working for this origin; I imagine if it was broken overall we would have issues with Spruce so? John suggested logging if we're adding this header, in which case something unrelated to us is likely wrong.

EVG-14767 add debugging for CORS requests

---

self-tests.yml

[EVG-14883 ](https://jira.mongodb.org/browse/EVG-14883 )
This removes variants that I believe we don't use:
- Coverage has been broken for a while. No one seems to mind.
- Windows need only run agent tests. Other tasks on Windows are broken without it mattering.
- ARM seems unnecessary. We don't test zSeries or PPC.
- We don't check OSX. I don't think it has ever caught anything.
Given that we don't use cgo, I think it's unlikely we ever need these. Arguably
we could remove Windows entirely, but I opted to leave it.
I ran a full patch to demo https://spruce.mongodb.com/version/60d4e585d1fe075d114393e2/.

EVG-14883 Remove unused variants from YAML

---

graphql/resolvers.go

[EVG-14418](https://jira.mongodb.org/browse/EVG-14418)
We need to always provide a patchId when it's not a PR commit queue patch. I thought I'd caught all of the cases for this, but I missed when a patch is created from an existing patch (which I believe is the case described in this ticket).

EVG-14418 add patchId to commit queue for enqueue button

---

rest/route/middleware.go

[EVG-14767](https://jira.mongodb.org/browse/EVG-14767)
Apparently by default only some methods are allowed (i.e. not patch) so allow more methods.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests
We aren't able to test this in staging so it needs to be deployed.

EVG-14767 add allow-methods header

---

rest/model/patch.go

[EVG-14862](https://jira.mongodb.org/browse/EVG-14862)
This will be a more reliable way for server to get the commit messages for the validate_commit_messages task.
Tested with local.

EVG-14862 add commit messages to patches API

---

rest/route/github.go

[EVG-14509](https://jira.mongodb.org/browse/EVG-14509)
The current retry logic to wait for a version on a given tagged commit does not always wait a sufficient length of time for a version to appear under a given tagged commit.  This could potentially cause a version to not be recognized simply due to not waiting long enough (current logic waits only slightly more than 1 second).  Change has been made to set 30 seconds rather than 1 second as the upper limit to wait before giving up on checking for a version.
Locally tested the current retry options for handling tags and confirmed with time delta print statements that the total retry wait time was typically ~1.3 seconds (accounting for jitter).  Modified the same options locally and confirmed that the new total wait time is ~30 seconds …

EVG-14509: Increase git tag triggered version check interval

---

model/host/stats.go

Not ticket-driven, but I encountered it when writing EVG-14805.
GetProvierCounts -> GetProviderCounts
none

typo GetProvierCounts -> GetProviderCounts

---

model/generate.go
model/lifecycle.go
model/patch_lifecycle.go

[EVG-14821](https://jira.mongodb.org/browse/EVG-14821)
Currently if a task depends on a generator, the task will also depend on the generated tasks. This shouldn't include intentionally unactivated generated tasks, or else we're blocked indefinitely.
Verified [release was blocked](https://evergreen-staging.corp.mongodb.com/task/sandbox_release_test_release_patch_e2023555d09c1bbcfbaa7660361e5a3e9747fc51_60dcaddcb237360b39f8d6db_21_06_30_17_46_28) by the unactivated dependency before changes, and [was not blocked](https://evergreen-staging.corp.mongodb.com/task/sandbox_release_test_release_patch_e2023555d09c1bbcfbaa7660361e5a3e9747fc51_60dcb67097b1d30a9023cb35_21_06_30_18_23_32) after changes.

EVG-14821 add dependencies for activated generated tasks only

---

config_cloud.go
globals.go
model/pod/db.go
model/pod/pod.go
public/static/js/admin.js
rest/model/admin.go
rest/model/admin_test.go
service/templates/admin.html
testutil/config.go

Jira: https://jira.mongodb.org/browse/EVG-14857
Create admin settings specific to pods in AWS that use Secrets Manager and ECS.
Standard admin settings tests. I also tested it manually in local evergreen to verify that the admin page works as expected.

EVG-14818: add admin settings for pods in AWS

---

graphql/ui_plugin_build_baron.go
model/task/db.go
model/task/task.go
rest/data/version.go
service/task.go
trigger/task.go

JIRA: https://jira.mongodb.org/browse/EVG-14924
I updated the task struct in model to also fetch and merge cedar test results wherever we merge new test results. I also fixed the display task test results issue that was causing the original issue from this ticket and cleaned up the legacy UI. 
I tested in staging that the test results are rendered properly with their logs. Upon deploy, we should watch out for display task UI pages since we don't have those in staging.

EVG-14924: Fetch cedar test results for tasks.

---

globals.go
rest/data/host_create.go
rest/data/host_create_test.go

[EVG-13811](https://jira.mongodb.org/browse/EVG-13811)
Users currently need to manually add sg-097bff6dd0d1d31d0 as a security group before running host.create.  To prevent further confusion in the future this has been automatically added as a security group so this no longer needs to be done manually.
Ensured default security group is added in unit test in host_create_test.go

EVG-13811: Ensure default security group is available during host.create

---

agent/command/exec.go
agent/command/expansion_test.go
agent/command/expansion_write.go
agent/command/scripting.go
config.go

[EVG-14670](https://jira.mongodb.org/browse/EVG-14670)
Users are currently able to discover Evergreen's global_github_oauth_token expansion, which if they use can result in our GitHub API limit to be reached.  A change has been made to prevent this expansion to be written to expansion lists in yaml files and from shell.exec. 
Modified unit test in expansion_test.go to include global_github_oauth_token as an expansion and confirm it is not written to any file

EVG-14670: Prevent users from viewing global_github_oauth_token expansion

---

model/event/event_finder.go
model/event/event_registry.go
model/event/pod.go
model/event/pod_test.go
model/pod/db.go
model/pod/pod.go
model/pod/pod_test.go

Jira: https://jira.mongodb.org/browse/EVG-14843
* Add support for logging events for pods.
* Rename `PodID` to `ExternalID` in the pod model to make it obvious that it's an external resource identifier and avoid confusion between `ID` and `PodID`.
Standard DB tests.

EVG-14843: set up event logs for pods

---

model/task_lifecycle.go
model/task_lifecycle_test.go

[EVG-14585](https://jira.mongodb.org/browse/EVG-14585)
Users have frequently been getting duplicate notifications since around the time [EVG-12953](https://jira.mongodb.org/browse/EVG-12953) was deployed, typically when patches are aborted or cancelled by Evergreen or users (one successful, one failed). I believe this is happening because when we abort patches, we first only update the [build activation](https://github.com/evergreen-ci/evergreen/blob/8da959940db4bf5417b3abaef599c68b0a8f1453/model/patch_lifecycle.go#L558). But then when we eventually [update statuses](https://github.com/evergreen-ci/evergreen/blob/bd6c848583d4a65d600c403371d6f65c75ccaf67/model/task_lifecycle.go#L1013) we don't consider [unactivated builds](https://github.com/evergreen-ci/evergreen/blob/bd6c848583d4a65d600c4 …

EVG-14585 update version/patch status only if build has changed

---

graphql/resolvers.go

[EVG-14840](https://jira.mongodb.org/browse/EVG-14840)
If an execution task only runs on the second execution of a display task (when it is restarted), then the execution task's execution will not be the same as the display tasks's execution. 
[Tested on staging](http://evergreen-staging.spruce.s3-website-us-east-1.amazonaws.com/version/60e4620197b1d32239314179/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).

EVG-14840 Fetch latest execution task if the display task's current execution doesn't exist  

---

service/api_task.go
units/stats_task_end.go

[EVG-14823](https://jira.mongodb.org/browse/EVG-14823)
There is currently not a foolproof way to execute a Splunk query that shows only display tasks (rather than execution tasks) and fold in any execution task information under the respective display task entry. Manual queries such as [this](https://mongodb.splunkcloud.com/en-US/app/search/search?earliest=1616370300&latest=1616975100&q=search%20index%3Devergreen%20stat%3Dtask-end-stats%20project%3D%22mongodb-mongo-*%22%20task!%3D%22*burn_in*%22%20requester%3D%22patch_request%22%20build!%3D%22*commit_queue*%22%20task!%3D%22*_gen%22%20%7C%20eval%20task%20%3D%20replace(task%2C%20%22_%5B0-9%5D%2B_%7C_misc_%22%2C%20%22_display_%22)%20%7C%20eval%20task%20%3D%20replace(task%2Cvariant%2C%22%22)%20%7C%20eval%20key%3Dbuild.%22%3A%22.task%20%7C%20st …

EVG-14823: Include display task ID upon execution task completion

---

model/task/task.go
service/task.go

JIRA: https://jira.mongodb.org/browse/EVG-14968
We need to use the correct task id (not the old task id) and execution when fetching test results from cedar for archived tasks.

EVG-14968: Use correct task id and execution when fetching cedar test results

---

service/api_task.go
units/stats_task_end.go

Reverts evergreen-ci/evergreen#4812 due to broken task test-service on Race Detector https://evergreen.mongodb.com/task/evergreen_race_detector_test_service_b8d7c2d5227d17bb9a7f1535c09e52b57a698ca7_21_07_08_18_36_59

Revert "EVG-14823: Include display task ID upon execution task completion"

---

globals.go
model/pod/db.go
model/pod/pod.go
rest/data/impl.go
rest/data/interface.go
rest/data/pod.go
rest/data/pod_test.go
rest/route/middleware.go
rest/route/middleware_test.go

Jira: https://jira.mongodb.org/browse/EVG-14908
* Add secret to pod data model, which will be generated when the pod is created in the container service.
* Add middleware to check pod ID and secret are valid when a pod contacts the app server.
Standard tests for the DB connector and middleware.

EVG-14908: add middleware to check pod secret

---

auth/okta.go
config_auth.go
config_test.go
glide.lock
public/static/js/admin.js
rest/model/admin.go
service/templates/admin.html
testutil/config.go
vendor/github.com/evergreen-ci/gimlet/okta/okta.go
vendor/github.com/evergreen-ci/gimlet/okta/okta_test.go

Jira: https://jira.mongodb.org/browse/EVG-14886
* Revendor Gimlet for Okta authorization server switch.
* Create admin setting for the Okta scopes to request when authorizing the user and pass the scopes to Okta.
Since we're switching to a new authorization server, all the current tokens that we're using to maintain user sessions will be invalid after cutting over. I'll coordinate a time and email for merging this PR, switching over, and logging everyone out once this is approved.
I tested the admin settings in local Evergreen. I also verified that I can log into Evergreen through the new Okta authorization server after logging out.

EVG-14886: use default authorization server for Okta

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/mainlineCommits/queries/commit-taskStatusCounts.graphql
graphql/tests/mainlineCommits/results.json

[EVG-14853](https://jira.mongodb.org/browse/EVG-14853)
* Added a new field called taskStatusCounts to Version. This field is used on the new waterfall page to help display the active commit barcharts. 
* Added a resolver function to calculate taskStatusCounts for a version.
* Added graphql test called `commit-taskStatusCounts` for querying a version's taskStatusCounts field

EVG-14853: Add TaskStatusCounts field to Version resolver

---

agent/system_metrics_test.go
config.go
glide.lock
operations/agent.go
operations/service_deploy_smoke_utils.go
vendor/github.com/evergreen-ci/utility/http.go

Jira: https://jira.mongodb.org/browse/EVG-14816
* Revendor utility to fix `RetryRequest`, which was causing errors in the agent.
* Make the system metrics test work in Windows.
* Clean up some dead code in the agent CLI command.
* Improve the smoke test slightly by preserving the task status in between request attempts.
I ran the smoke test.

EVG-14816: fix smoke test

---

graphql/resolvers.go
rest/model/patch.go

[EVG-13075](https://jira.mongodb.org/browse/EVG-13075)
A patch that has child patches should display a status that reflects the status of the child patches. 
Tested using the graphql playground with the following query: 
`query Patch {
patch(
id: "60ec9d6d9dbe322c63945089"
) {
id
status
childPatches{
id
status
}
}
}`

EVG-13075 Failed Downstream patches should show a failed badge for the upstream patch

---

rest/route/project_copy.go

[EVG-14889](https://jira.mongodb.org/browse/EVG-14889)
Executing the endpoint to copy an existing project over to a new project was seen to result in the newly created project not having the appropriate admin roles set (and users that ought to have been entitled were not able to view the project in Evergreen's UI). The copying action did not re-set the existing admin roles from the old project onto the new project, so the new project had the correct list of names in the Admins property, but those roles were not actually set.  A change has been made to update the roles for the newly copied over project at the end of the copying function.

EVG-14889: Update admin roles when copying over project

---

rest/route/aws.go

[EVG-14830](https://jira.mongodb.org/browse/EVG-14830)
Added logging of number of running hosts in order to better understand the impact of AWS instance interruptions.
Will run in staging before merging

EVG-14830: add running host count to AWS interrupt logging

---

graphql/ui_plugin_build_baron.go
trigger/task.go
trigger/task_test.go

[EVG-14777](https://jira.mongodb.org/browse/EVG-14777)
BFGs are created when spot hosts are taken by AWS (causing the tasks to end in a stranded state), creating a significant amount of noise for the Build Bartender. Since these are generally not action items and are not indicative of a real issue, a change has been made to skip JIRA creations when this occurs
Unit test added asserting that no notification is sent to anyone when a stranded state occurs.

EVG-14777: Do not create BFG ticket for stranded tasks

---

operations/agent.go

Jira: https://jira.mongodb.org/browse/EVG-14897
Set the pod ID and secret from environment variables, which are going to be set when the container runs.

EVG-14897: set agent pod ID and secret from env vars

---

graphql/resolvers.go

[EVG-15025](https://jira.mongodb.org/browse/EVG-15025)
taskStatusCount resolver now sorts result array by status name before returning

EVG-15025: Fix failing taskStatusCounts graphql test by sorting result

---

self-tests.yml

[EVG-14090](https://jira.mongodb.org/browse/EVG-14090)
This adds additional agent builders to verify agent behavior on non-Linux platforms. They are nearly identical to the Windows builder.

EVG-14918 Add macos and arm agent builders

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_test.go
cloud/ec2_util.go
config.go
model/host/db.go
model/host/host.go
operations/host_spawn.go
rest/data/host.go
rest/data/host_create_test.go
rest/model/createhost.go
rest/model/createhost_test.go
rest/route/host.go

[EVG-14850](https://jira.mongodb.org/browse/EVG-14850)
added new field on Hosts struct and a way to insert ipv4 addresses to database 
added ipv4 to relavent unittests 
spawned host in staging
new query works for both ips

EVG-14850 add ipv4 address field to hosts

---

graphql/resolvers.go
model/patch/patch.go
rest/data/patch.go
rest/model/patch.go

[EVG-14976 ](https://jira.mongodb.org/browse/EVG-14976 )
Manually called the routes and the graphql resolver.

EVG-14976  Display a collective statusPatch in patch api routes 

---

model/task/db.go
model/task/task.go

[EVG-14941](https://jira.mongodb.org/browse/EVG-14941)
The tasks table shouldn't return any tasks that aren't activated. This scenario is relevant to generated tasks that are generated with out actually being activated.

EVG-14941 Only return activated generated tasks for the tasks table

---

config_cloud.go
rest/model/admin.go
rest/model/admin_test.go
service/templates/admin.html
testutil/config.go

Jira: https://jira.mongodb.org/browse/EVG-15020
Add admin settings to forward to ECS for the task and execution roles. These allow ECS to interact with external services like Secrets Manager, as well as do useful things like allow you to exec into a running container in an ECS task.
Normal admin REST tests. I also verified in local-evergreen that the fields work.

EVG-15020: add admin settings for pod task and execution roles

---

model/event/pod.go
model/event/pod_test.go
model/pod/pod.go
model/pod/pod_test.go

Jira: https://jira.mongodb.org/browse/EVG-15026
Add event logging when the pod status changes.
I also squashed the error from `LogPodEvent` so it just logs instead of returning an error to the caller. `LogEvent` can error in some uncommon cases (e.g. if insertion fails), but it doesn't seem important enough to actually return errors to the caller, nor is it really actionable since it's not worth retrying an event log insertion. I'm fine with it being a best-effort event log system.
Tests to ensure the event is logged properly when `(*Pod).UpdateStatus` is called.

EVG-15026: add event log for when the pod status changes

---

cloud/pod_util.go
cloud/pod_util_test.go
globals.go
model/pod/pod.go
model/pod/pod_test.go
rest/route/pod_agent.go
rest/route/pod_agent_test.go
rest/route/service.go
testutil/config.go
units/pod_termination.go
units/pod_termination_test.go

Jira:
https://jira.mongodb.org/browse/EVG-14817
https://jira.mongodb.org/browse/EVG-15098
* Add next task REST route, which does nothing other than attempt to clean up the pod since this is the end of the POC's pod lifecycle.
* Rename pod enums to be type-prefixed instead of type-suffixed.
Normal tests for REST routes.

EVG-14817: add pod next task route and rename pod enums

---

graphql/resolvers.go

[EVG-14776](https://jira.mongodb.org/browse/EVG-14776)
Resolves base test statuses when the gql TaskTests query utilizes cedar 
It seems that the best way to test is in staging since our gql test framework cannot talk to cedar

EVG-14776: resolve cedar base test status in TaskTests resolver

---

cloud/pod_util.go
cloud/pod_util_test.go
glide.lock
model/pod/pod.go
rest/data/interface.go
rest/data/pod.go
rest/data/pod_test.go
rest/model/pod.go
rest/model/pod_test.go
rest/route/middleware.go
units/pod_termination_test.go
vendor/github.com/evergreen-ci/cocoa/ecs/pod.go
vendor/github.com/evergreen-ci/cocoa/ecs/pod_creator.go
vendor/github.com/evergreen-ci/cocoa/ecs/pod_test.go
vendor/github.com/evergreen-ci/cocoa/ecs_pod.go
vendor/github.com/evergreen-ci/cocoa/ecs_pod_creator.go
vendor/github.com/evergreen-ci/cocoa/ecs_pod_creator_test.go
vendor/github.com/evergreen-ci/cocoa/internal/testcase/ecs_pod.go
vendor/github.com/evergreen-ci/cocoa/internal/testcase/ecs_pod_creator.go

JIra: https://jira.mongodb.org/browse/EVG-15097
* Add REST API pod model.
* Add data connector method to find pod by ID.
* Include the status when creating a new DB pod from the REST route to create new pods. 
* Slightly modify some of the HTTP status codes returned when checking a pod ID/secret.
* Revendor cocoa.
Normal REST model and data connector tests.

EVG-15097: implement pod REST model

---

repotracker/github_poller.go

[EVG-14925](https://jira.mongodb.org/browse/EVG-14925)
When a user switches branches in their project, Evergreen reports on the project page that the user should enter a new base revision, and provides a base revision for the user who can then choose to confirm on the project page and set the base revision manually. A change has been made in the case that a base revision is found for the new branch, it will be set as the base revision automatically instead of waiting for the user to visit the project page and confirm the revision manually.

EVG-14925: Set base revision when changing branches instead of asking user for confirmation

---

config_cloud.go
globals.go
model/pod/db.go
model/pod/pod.go
rest/data/pod.go
rest/data/pod_test.go
rest/model/admin.go
rest/model/pod.go
rest/model/pod_test.go
rest/route/pod.go
rest/route/pod_agent.go
rest/route/pod_agent_test.go
rest/route/pod_test.go
testutil/config.go
units/pod_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-15092
Split the platform into OS and architecture, which will help us in choosing which agent to download on the host. It's also necessary to know the OS to assign the pod to the correct cluster.
I also fixed some minor issues in the REST route to create pods.
Normal REST and DB model tests.

EVG-15092: convert platform into OS and architecture

---

cloud/pod_util.go
cloud/pod_util_test.go
model/pod/db.go
model/pod/pod.go
model/pod/pod_test.go
rest/model/pod.go
rest/model/pod_test.go
units/pod_termination.go
units/pod_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-15113
* Re-add the pod timing information to the DB model and include it in the REST model.
* Set the relevant pod timing information when the status is updated. 
* Rename the resource ID to external ID for future-proofing, because we're going to have to also store individual container IDs later on. I couldn't really come up with a more appropriate name (pod ID would be confusing, task ID already means something in the Evergreen code base, group ID would also be confusing because there are task groups in ECS).
* Fix some minor BSON tag mismatches.
Updated the existing DB/REST tests.

EVG-15113: re-add pod timing information

---

graphql/resolvers.go

Sometimes this test flakes and switches the order of the results in the return. This sort should ensure they always get returned in the same order.

EVG-15115 Fix flaky test for scheduleUndispatchedBaseTasks

---

cloud/ec2_util.go
rest/route/aws.go
units/host_monitoring_external_termination.go
units/host_status.go

[EVG-13648](https://jira.mongodb.org/browse/EVG-13648)
Translate the stopping AWS status to the stopping instance status
N/A

EVG-13648 add stopping instance state

---

gqlgen.yml
graphql/generated.go
graphql/resolvers.go

[EVG-15134](https://jira.mongodb.org/browse/EVG-15134)
This reverts a significant performance regression  introduced in https://github.com/evergreen-ci/evergreen/pull/4840 
Patch status will only be calculated when viewing a patch/version page and will not be calculated elsewhere such as the mypatches pages.
Calculating patch status on the my patches page is an expensive operation because it needs to query for every visible patches tasks to determine if a patch should have an aborted status. Which lead to significant load on the db. 
Note: the status on the my patches page has the potential to not be in sync with the patch status on the version page, which represents the same behavior as before  the change in #4840 was introduced so this is not a functionality regression.

EVG-15134 Only resolve statuses for base level patches

---

graphql/util.go

[EVG-15099](https://jira.mongodb.org/browse/EVG-15099)
If someone sets the priority for a patch, it should also set the priority for child patches 
This will only update the patch priority if the child patch has already been created. In the case where the child patch waits on the parent to finish in order to finalize, the child patch won't have that priority. I don't know if this is significant enough to warrant a bigger refactor to be able to store the priority and then add it when the child gets created. 
Manually tested on staging.

EVG-15099  Update priority for child patches when updating the parent 

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/task/queries/versionMetadata.graphql
graphql/tests/task/results.json

[EVG-13490](https://jira.mongodb.org/browse/EVG-13490)
Adds a versionMetadata field which resolves versions for tasks. Decided to do it in a backwards compatible way. This will be renamed to version in a follow up PR. Any fields marked deprecated will also be removed in a follow up pr.

EVG-13490 add versionMetadata field which resolves a version

---

graphql/resolvers.go
graphql/util.go
graphql/util_test.go

[EVG-14776](https://jira.mongodb.org/browse/EVG-EVG-14776)
These code changes: 
- fetch base test results before test results and utilizes the correct key (DisplayTestName instead of TestFile) to map a cedar test result to its base test status. 
-  request cedar first and evergreen second for tests and base tests separately. 
- utilizes the latest base task execution to fetch base test results
- handle sorting cedar tests by base status. That feature hasn't existed [based on the original resolver params](https://github.com/evergreen-ci/evergreen/blob/main/graphql/resolvers.go#L1268-L1280) ([Ticket](https://jira.mongodb.org/browse/EVG-15131)). 
The [DisplayTestName field coming from Cedar](https://github.com/evergreen-ci/evergreen/blob/7d87de9adf5fa6d75ba25f73d40add20bf7fcac0/agent/command/ …

EVG-14776: Fetch cedar base test result in TaskTests GQL resolver

---

vendor/github.com/mongodb/grip/send/slack.go

[EVG-15147](https://jira.mongodb.org/browse/EVG-15147)
Don't test slack auth.  This is a temporary fix to ensure that we can deploy the app without slack integration.

EVG-15147 Don't test slack auth

---

public/static/js/task.js
service/task.go
service/templates/task.html

[EVG-14685](https://jira.mongodb.org/browse/EVG-14685)
We use a similar logic in spruce for the tests table [here](https://github.com/evergreen-ci/spruce/blob/main/src/pages/task/taskTabs/testsTable/TestsTableCore.tsx#L276-L278)

EVG-14685: replace Logkeeper lobster links with Evg in the legacy ui task page

---

service/api_task.go

[EVG-15091](https://jira.mongodb.org/browse/EVG-15091)
When tasks are blocked, they aren't marked as unactivated (this is purposeful because they could become unblocked). However, we shouldn't wait on them if later tasks in the group are scheduled. We ran into this error when a later task group task was set to override dependencies; instead it just got stuck at the top of the queue because it was waiting on the previous task group task which was also blocked.
[This task](https://evergreen-staging.corp.mongodb.com/task/evg_ubuntu1604_test_cloud_patch_ccbdfbe1ca4c5e72baed4d0505b6b058566c89b4_61083e9a97b1d31e62c81c7b_21_08_02_18_51_19) was on the queue but not being dispatched (and was logging errors) until I pushed my changes, and then was dispatched.

EVG-15091 consider if tg tasks are blocked before waiting on them

---

rest/route/annotations.go
rest/route/annotations_test.go

[EVG-15163](https://jira.mongodb.org/browse/EVG-15163)
This fetches a task by execution so that the status restriction applies to the execution in question and not the latest one. 
Tested in staging and made sure it doesn't fail with a task that first failed and then didn't.

EVG-15163 Fix cannot annotate tasks that have been retried

---

model/lifecycle.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go

[EVG-15178](https://jira.mongodb.org/browse/EVG-15178)
Robert has a patch where the [display task](https://spruce.mongodb.com/task/mongodb_mongo_master_enterprise_rhel_80_64_bit_dynamic_required_display_generator_tasks_patch_4ce48b4608b0b3e0528b4faba0d1dc0075f71c32_610a7ce89ccd4e1d78c30a2f_21_08_04_11_42_16/execution-tasks?execution=0&sorts=STATUS%3AASC) has no activation time, even though execution tasks ran. I wasn't able to create a minimum viable example of how this happened, but I did some code reading of where Activated gets set (bc that _is_ setfor this task) and found two places where we don't consider activationTime but should. When this is in prod, I can re-create the server patch and see if the problem still occurs (but either way this is a necessary change).
I modified a unit …

EVG-15178 update activation time for display tasks

---

graphql/util.go

[EVG-15118](https://jira.mongodb.org/browse/EVG-15118)
This takes care of scheduling/unscheduling tasks for child patches when it's done for the parent patch. It made more sense to do it ModifyVersionHandler where it handles but scheduling/unscheduling and set priority so that code does not have to be repeated (especially with all the casing). Restart is handled separately because we need to take input from the user. 
Will test in staging

EVG-15118 Modifying a version should also modify the child patches 

---

environment.go

[EVG-15017](https://jira.mongodb.org/browse/EVG-15017)
All notification error messages in Splunk had the “notification_target” field randomly be that of another sender. It was noticed that the [error handler function](https://github.com/evergreen-ci/evergreen/blob/d89485d34a375362759111dea41afe32d1acdbca/environment.go#L633-L647) was a closure around the name variable which gets changed on each iteration of the loop. A fix was made to give each iteration a local copy of the name variable to close around.
Change was deployed to staging and a notification was set up to send a slack message to a nonsensical channel when a task restarted.  When the channel_not_found error was triggered [as expected](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22evergreen-staging …

EVG-15017: Add closure over the value of notification_target string to fix notification logging

---

model/test_log_test.go

Jira: https://jira.mongodb.org/browse/EVG-15191
This test takes several minutes to run locally. I reduced the number of documents tested so it runs in under 30 seconds.

EVG-15191: make TestDeleteTestLogsWithLimit faster

---

globals.go
model/patch/trigger_intent.go

[EVG-14973](https://jira.mongodb.org/browse/EVG-14973)
Add a parent_patch user and use that for child patches so that they don't show up on the myPatches page. 
Tested by adding the parent_patch user to staging, creating a patch with child patches, and making sure that they show up in the right places.

EVG-14973  Hide child patches from showing up as a patch

---

graphql/util.go

[EVG-15197](https://jira.mongodb.org/browse/EVG-15197)
This checks if a child patch is finalized before making modifications to avoid errors. 
Tested by creating a patch with a not finalized child patch in staging and changing the priority with no errors.

EVG-15197  Don't error if child version doesn't exist when modifying

---

model/event/subscriptions.go
model/event/task_event.go
model/task/db.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go
public/static/js/task.js
rest/data/subscription.go
trigger/task.go
trigger/task_test.go

[EVG-14332](https://jira.mongodb.org/browse/EVG-14332)
Notify if the task is failed or blocked. (Could've made this just notify on blocked; I thought a bit about the reporter's use case / general use case for this and I think failed + blocked does make the most sense, but the work to add "just blocked" would be similar to this if it's ever requested in the future.)
Tested in staging on both legacy and spruce for blocked and failed (slack and email).
Spruce
Legacy
Slack
Email

EVG-14332 add notification for failed or blocked task

---

rest/data/patch.go
rest/data/patch_test.go
rest/route/patch_test.go

[EVG-14366](https://jira.mongodb.org/browse/EVG-14366)
FindPatchesByProject can now search even if it's given an identifier
unittest

EVG-14366 Allow FindPatchesByProject to search by ProjectIdentifiers

---

model/task/task.go

[EVG-15192](https://jira.mongodb.org/browse/EVG-15192)
Instead of performing two queries to fetch tasks and to fetch the matching task count. Perform only one query by merging the separate pipelines using `$facet`
Reused existing tests since this is a refactor instead of a feature change.

EVG-15192 Merge getTasksByVersion queries into one

---

graphql/resolvers.go

[EVG-15122](https://jira.mongodb.org/browse/EVG-15122)
The test that calls this resolver has been extremely flaky since we cannot guarantee the return order of the results. This adds a sort to the end to help guarantee the sort order.
I think fixing the flaky tests outweighs the performance hit the sort adds to the resolver. Since it will rarely be called.

EVG-15122 Sort tasks to resolve flaky tests

---

graphql/resolvers.go
graphql/util.go
model/scheduler_stats.go
model/task/db.go
model/task/task.go
model/task_history.go
model/task_json.go
model/task_lifecycle.go
model/validate.go
rest/data/task.go
rest/route/annotations.go
service/api_task.go
service/host.go
service/spawn.go
service/stats.go
service/task.go
service/ui_plugin_perf_json.go
trigger/task.go

EVG-14997: https://jira.mongodb.org/browse/EVG-14997
This replaces task DB functions that merge test results with the "NoMerge" equivalent versions of those functions where test results are not really needed. In a subsequent PR, I will add back the changes to merge cedar test results and we want to avoid making unnecessary calls to cedar (and downloading potentially large test result sets) when we do not need to.
Since this affects the task lifecycle, triggers, and UI I am putting multiple people on the PR for more eyeballs.

EVG-14997: Merge test results audit

---

public/static/app/common/constants.js
public/static/app/perf/perf.js
service/templates/task_perf_data.html

[TIG-3231](https://jira.mongodb.org/browse/TIG-3231)
Adds back the new trend charts iframe, but now handles sizing and url trusting properly. I'm using the same sizing spruce uses for these trend charts (100% of parent container width, 1000px height), for reference.
I was able to get a local version working and saw that this didn't affect the log section showing up. I also did a temporary hack to enable viewing this new panel without it being configured, and that also didn't affect the log section. I think it should be good to go, now.

TIG-3231: Iframe for new trend charts, plus url and sizing fixed.

---

service/task.go

[EVG-15032 ](https://jira.mongodb.org/browse/EVG-15032 )
https://mongodb.slack.com/archives/C866SR2LR/p1629136301026000
Can't use display task since it will be nil if displayTaskId was already set.

EVG-15032 use display task ID after checking if display task

---

rest/route/pod.go
rest/route/pod_test.go
rest/route/service.go
units/crons.go
units/pod_creation.go
units/pod_creation_test.go

Jira: https://jira.mongodb.org/browse/EVG-15248
Enqueue the pod creation job as soon as the pod document is created in the REST route. The periodic cron job will still populate it if the REST route fails to enqueue it (e.g. because the context cancels).
N/A

EVG-15248: enqueue pod creation job in REST route

---

rest/route/pod.go
rest/route/pod_agent.go
units/crons.go
units/crons_remote_minute.go
units/pod_creation.go
units/pod_creation_test.go
units/pod_termination.go
units/pod_termination_test.go

JIra: https://jira.mongodb.org/browse/EVG-15259
Make the naming scheme consistent for the pod jobs and their file names. This is to reduce the amount of confusion for pods that's accrued over the naming scheme of host lifecycle jobs (e.g. the host termination job is `units/host_termination.go`, the create host job is `units/provisioning_create_host.go`, the set cloud hosts ready job is `units/host_status.go`).
The name change won't affect staging or prod because pods are still being tested and neither environment is running these jobs.
N/A

EVG-15259: rename pod lifecycle jobs

---

model/task/task.go
model/task/task_test.go

[EVG-15190](https://jira.mongodb.org/browse/EVG-15190)
If the task has display task ID explicitly set to empty or displayTask is true, we don't have to do the lookup to find out if the task is an execution task, so we use facet to filter those out, and we only lookup execution tasks on the remaining tasks.

EVG-15190 use display task ID and facet to get version tasks

---

model/generate.go
model/lifecycle.go
model/lifecycle_test.go
model/project.go

[EVG-12604 ](https://jira.mongodb.org/browse/EVG-12604)
The bulk of this work was actually to refactor task creation a bit for generated tasks to ensure that stepped back tasks have the correct ActivatedBy set.
Stepped back a [regular task](https://evergreen-staging.corp.mongodb.com/task_log_raw/sandbox_ubuntu1604_unit_tests_1a682bce4da50d4548f3f4de87912e799f85b68f_21_08_16_18_36_57/0?type=T#L68) and verified expansion was set.
Stepped back a generator task and then the [generated task](https://evergreen-staging.corp.mongodb.com/task_log_raw/sandbox_ubuntu1604_task_to_add_via_generator_78f4c89f1e19d153feecf2f7a35a1f9b50ab8f80_21_08_16_19_41_36/0?type=T#L68) and verified expansion was set.

EVG-12604 add expansion to indicate a task was stepped back

---

graphql/ui_plugin_build_baron.go
graphql/util.go
model/context.go
model/scheduler_stats.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task/task_testresult_test.go
model/task_history.go
model/task_json.go
model/task_lifecycle.go
model/task_start_estimation.go
plugin/attach_plugin.go
rest/data/task.go
rest/data/version.go
service/api_task.go
service/rest_task.go
service/spawn.go
service/task.go
service/waterfall.go
trigger/task.go
trigger/task_jira.go
trigger/task_jira_test.go
trigger/task_test.go
units/stats_task_end.go

EVG-14997: https://jira.mongodb.org/browse/EVG-14997
- Lazily fetch test results.
- Remove all test results merging in task DB functions.
- Create new `PopulateTestResults` which populates the task's `LocalTestResults` field (even if it is a display task).
- Add a new local field, `testResultsPopulated`, to the `Task` struct to avoid populating test results more than once.
- Call `PopulateTestResults` where needed (this is the riskiest part of the PR).

EVG-14997: Fetch test results lazily

---

agent/internal/client/pod_methods.go
config.go

JIra: https://jira.mongodb.org/browse/EVG-15273
Implement GetNextTask for the agent's communicator when running in a pod. The REST route already exists, it was just never hooked up to the agent. 
N/A

EVG-15273: implement GetNextTask in agent pod communicator

---

model/project_parser_test.go

[EVG-14953](https://jira.mongodb.org/browse/EVG-14953)
Fix the test because the the build variants may not be added in order
unittest

EVG-14953 Fix flakey TestMergeMultipleProjectConfigsBuildVariant

---

public/static/app/common/constants.js

[TIG-3231](https://jira.mongodb.org/browse/TIG-3231)
Fixing the url for performance tooling, we were using the latest version rather than the stable version.
I verified that https://performance-monitoring-and-analysis.server-tig.prod.corp.mongodb.com is the proper URL to use here.

TIG-3231: Point to stable deployment of performance tooling.

---

agent/stats.go
config.go

[EVG-14219](https://jira.mongodb.org/browse/EVG-14219)
Currently the stats collector doesn't run later commands if an earlier one
fails. This adds the ContinueOnError jasper option so that they all run.
Since this is internal jasper behavior, I did not test this.

EVG-14219 Continue on error in stats collector

---

agent/command/generate.go
agent/internal/client/host_methods.go
config.go
globals.go
rest/data/generate.go

[EVG-15142](https://jira.mongodb.org/browse/EVG-15142)
Right now we noop if we rerun a generator that has already already generated tasks; this can be confusing to users who expected something to happen, so we've decided to add a log for now.
Tested: https://evergreen-staging.corp.mongodb.com/task/evg_lint_generate_lint_ef19ea1fa0e2ca32b375a46402a2b7bae0bb463f_21_08_18_20_45_49

EVG-15142 add log for a generate task noop

---

graphql/resolvers.go
model/project_event.go
model/project_event_test.go
model/project_ref.go
rest/data/aliases.go
rest/data/aliases_test.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/data/subscription.go
rest/data/subscription_test.go
rest/model/project_event.go
rest/model/project_event_test.go
rest/route/host_spawn.go
rest/route/project.go
rest/route/repo.go
rest/route/subscription.go
service/project.go

[EVG-15060](https://jira.mongodb.org/browse/EVG-15060)
In order to use the existing connectors for this function, we need to split the operations by the type of connector it's part of. I made GetProjectSettingsBySection to handle all of the DBProjectConnector operations, and then separately made a new alias function and modified the subscription function, so these can all be called by the resolver. 
(The alternative to this would be to move all the logic for the connectors into model functions and not use connectors at all, but I think that's messier in the long run.)
Added tests to the new project settings function and the alias function.

EVG-15060 save project settings for section

---

graphql/resolvers.go

[EVG-15304](https://jira.mongodb.org/browse/EVG-15304)
Before: 
After:

EVG-15304  Add the parent status to collective status in the version resolver

---

trigger/patch.go

[EVG-15278](https://jira.mongodb.org/browse/EVG-15278)
The original bug reported in the ticket was actually not really a bug. The version resolver accidentally left the parent patch status out of the calculation, so the patch status always showed the child status _only_ instead of a collective status. This mimicked the patch not waiting on the parent, but it wasn't actually the case. Once the resolver was fixed, this "bug" went away. However, in my investigation I noticed something that either has hidden problems or is bound to cause a problem at some point, so I fixed it here. 
I noticed that the parent patch was null in splunk logs where I didn't expect it to be, and after this change, it no longer showed up as null in that case.

EVG-15278 Return parentPatch if available

---

units/cache_historical_test_data.go

[EVG-15166](https://jira.mongodb.org/browse/EVG-15166)
Currently When we're failing to process test stats it's preventing us from processing task stats. Since we return early when we hit an error in the hourly stats, we never actually get to processing daily task results. In one observed case when there was a test name long enough that one of these indexes exceeds the WT 1024 byte limit, and this will continue to cause an error until Evergreen upgrades to Mongo 4.4 from 4.0.  A change has been made to add logging to notify if a certain test stat has failed to process and continue processing the rest of the stats instead of stopping and returning once a single error is found.
Deployed change to staging and enabled the cache historical statistics, and saw that there was not any [unexpected …

EVG-15166: Remove premature return statement from stats iterators

---

cloud/pod_agent_util.go
cloud/pod_agent_util_test.go

Jira: https://jira.mongodb.org/browse/EVG-15301
Use bash to run the shell script command in ECS. `CMD-SHELL` is apparently only available to commands that are specifically for health checks.
Updated existing tests.

EVG-15301: invoke pod agent script with bash

---

cloud/ec2.go
cloud/ec2_fleet.go
cloud/pod_agent_util.go
cloud/userdata.go
cloud/userdata_test.go
model/host/hostutil.go
units/pod_creation.go
units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go
units/provisioning_setup_host.go

Jira: https://jira.mongodb.org/browse/EVG-15302
Pass the service flags into the helper functions that depend on them to avoid having dependencies on global testing state in unit tests. It also avoids the issue where arbitrary functions can ask for the global environment state.

EVG-15302: pass service flags to helper functions

---

rest/route/middleware.go
util/strings.go
util/strings_test.go

[EVG-14767](https://jira.mongodb.org/browse/EVG-14767)
A change has been made to allow regexes when adding CORS, because currently we only apply if a request url exactly matches what we have in the allowedOrigins defined on the admin page.  Now exact strings and regexes will both match and apply CORS.
Added unit test certifying behavior

EVG-14767: Support regex when allowing CORS

---

model/project_event.go
model/project_ref.go
model/project_ref_test.go
rest/data/aliases.go
rest/data/aliases_test.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/route/project.go

[EVG-15060](https://jira.mongodb.org/browse/EVG-15060)
The only thing that really needs to operate differently for RepoRef is the Access section, since we need to use the repo functions and not the project functions. Wasn't sure if I should pass in repo outside of project settings or as a new field 🤔  but in most cases we really can just use the ProjectRef. I think we can re-evaluate refactoring project settings in the future.
Quite a unit test.

EVG-15060 modify save section to work for repo

---

model/pod/db.go
model/pod/db_test.go
model/pod/pod.go
units/crons.go
units/pod_creation.go
units/pod_creation_test.go

Jira: https://jira.mongodb.org/browse/EVG-15262
* Add decommissioned status to mean that the pod intends on terminating.
* Terminate pods that have been initializing for too long without successfully being started in ECS.
* Terminate pods that run out of attempts to start in ECS.
DB tests and Amboy job tests.

EVG-15262: terminate stale initializing pods

---

glide.lock
rest/route/sns.go
vendor/github.com/evergreen-ci/cocoa/ecs/constant.go
vendor/github.com/evergreen-ci/cocoa/ecs/pod_creator.go

JIra: https://jira.mongodb.org/browse/EVG-15336
* Revendor Cocoa.
* Use ECS task status constants instead of hard-coded strings.

EVG-15336: use ECS task status constants

---

model/task/task.go

JIRA: https://jira.mongodb.org/browse/EVG-15353
Not using this function caused a bug in the UI because we were not setting the `TaskID` field.

EVG-15353: Use ConverToOld when converting test results

---

model/lifecycle.go
model/task/task.go
model/task/task_test.go
rest/model/task.go

[EVG-EVG-15274](https://jira.mongodb.org/browse/EVG-15274)
When I made this display task ID change, I didn't think to update tasks that already exist but are only now being made into execution tasks. But also I decided to just refactor this section (which per Julian's retro he mentioned we shouldn't do whoops 😅  but it's a small ish refactor; I'll call out the actual change for the fix in a comment)
Added a unit test. I'm honestly having trouble replicating this bug on staging; I'm not sure if it's the way the tasks are generated on the server project or what. I do suspect this will fix the problem, I've read over it a few times and it does seem like _a_ bug if not _the_ bug so I think it's worth deploying and seeing what happens, but let me know what you think.

EVG-15274 add display task ID to existing execution tasks

---

model/testresult/testresult.go

JIRA: https://jira.mongodb.org/browse/EVG-15353
We need these fields for route generation in the legacy UI. There is also no reason not to project them.

EVG-15353: Project task_id and execution for test results FindByTaskIDAndExecution query

---

public/static/js/projects.js

[EVG-15338](https://jira.mongodb.org/browse/EVG-15338)
Kind of a bandaid, but fixing the backend to always return the error in the same format is more complicated, and this is soon-to-be legacy anyway.
Tested with evergreen local.

EVG-15338 print saving project error correctly

---

model/task/task.go
model/task/task_test.go
rest/data/task_test.go

[EVG-15279 ](https://jira.mongodb.org/browse/EVG-15279 )
Use facet so we don't have to lookup annotations for successful tasks.
Added a test that succeeds before and after changes.

EVG-15279 use facet to conditionally lookup annotations

---

model/task/db.go
model/task/task_test.go
units/host_monitoring_external_termination.go
units/host_status.go
units/provisioning_create_host.go

[EVG-14963](https://jira.mongodb.org/browse/EVG-14963)
Currently hosts that are spawned by a task that are terminated externally cause host.list to timeout since they are not included in the host details property on a task, and when an external termination occurs the terminated host is not included in the list of hosts associated with a given task.  A change has been made to add a host's details to a given task when it is terminated externally.

EVG-14963: Add host create details when host is externally terminated

---

service/patch.go

[EVG-15369](https://jira.mongodb.org/browse/EVG-15369)
- Fix target type of ReadJSON operation; the request includes `description` and `variants_tasks` fields, so it should just be read into type `PatchUpdate`
- Tested on staging

EVG-15369: Fix SchedulePatch in legacy UI

---

cloud/pod_util.go
cloud/pod_util_test.go

JIra: https://jira.mongodb.org/browse/EVG-15382
Export the decommissioned pod status as running (it plans to shut down, but it's still counted as running).
Unit tests.

EVG-15382: export decommissioned pod status

---

rest/data/admin_test.go
rest/route/admin_test.go

JIra: https://jira.mongodb.org/browse/EVG-15305
Clear the admin settings in the DB after they've been modified in admin settings tests. This fixes an issue where updating the DB admin settings in one test can affect unrelated tests that depend on DB state, like service flags.

EVG-15305: reset global config after admin settings test

---

model/project_ref.go
model/project_ref_test.go

[EVG-15053](https://jira.mongodb.org/browse/EVG-15053)
Create function to change owner/repo for project -- validate the new input, remove the project from the previous scope and add it to the new scope ( if the project is attached to a repo), and update the project ref.

EVG-15053 add function to change a project's repo

---

glide.lock
model/task_history.go
service/task_history.go
vendor/github.com/mongodb/anser/db/interface.go
vendor/github.com/mongodb/anser/db/wrapper.go
vendor/github.com/mongodb/anser/db/wrapper_legacy.go
vendor/github.com/mongodb/anser/mock/db.go

[EVG-14028](https://jira.mongodb.org/browse/EVG-14028)
Now that MaxTime is part of anser I redid the effort from #4500 to use it instead of using the driver directly. 
Another consideration is that we will no longer be passing the request's context to the mongo driver, but rather the application context. On the one hand this is bad because it means that if a call to `iter.Next()` (getMore) is taking a long time the operation won't get killed when the request dies but rather when maxtime passes on the server side (i.e. a minute after it starts). On the other hand, routinely killing an operation on the server by killing the driver's context apparently isn't good for server performance (I wrote more about this in [the anser PR](https://github.com/mongodb/anser/pull/43#issuecomment-897110393)) …

EVG-14028 set maxtime for TaskHistory queries

---

agent/command/shell.go
config.go

[EVG-14129](https://jira.mongodb.org/browse/EVG-14129)
User requested to enabled expansions in the shell field for shell.exec commands.  Change has been made to expand the string in the shell field.
Input an expansion for the shell field in self-tests.yml and deployed to staging and confirmed when restarting a task that the field was expanded.

EVG-14129: Allow expansions in the shell field for shell.exec

---

model/task_lifecycle.go
model/task_lifecycle_test.go

[EVG-12547](https://jira.mongodb.org/browse/EVG-12547)
Tasks in single host task groups typically need to run sequentially on the same host in order to work. When we stepback a failed task (to see if it succeeds on a previous version), we currently only activate the one task, which means that single-host task group tasks are bound to fail. Instead we should activate the earlier tasks in the group (we don't need to activate the later ones to determine stepback).
Unit test.

EVG-12547 stepback earlier tasks in single host task group

---

model/task_lifecycle_test.go

[EVG-12547](https://jira.mongodb.org/browse/EVG-12547)
SetActiveState now calls UpdateBuildAndVersionForTask so test needs to be updated.
Fixed test.

EVG-12547 fix merge conflict with SetActiveState

---

glide.lock
rest/route/middleware.go
rest/route/service.go
vendor/github.com/rs/cors/.travis.yml
vendor/github.com/rs/cors/LICENSE
vendor/github.com/rs/cors/README.md
vendor/github.com/rs/cors/bench_test.go
vendor/github.com/rs/cors/cors.go
vendor/github.com/rs/cors/cors_test.go
vendor/github.com/rs/cors/examples/alice/server.go
vendor/github.com/rs/cors/examples/buffalo/server.go
vendor/github.com/rs/cors/examples/chi/server.go
vendor/github.com/rs/cors/examples/default/server.go
vendor/github.com/rs/cors/examples/gin/server.go
vendor/github.com/rs/cors/examples/goji/server.go
vendor/github.com/rs/cors/examples/gorilla/server.go
vendor/github.com/rs/cors/examples/httprouter/server.go
vendor/github.com/rs/cors/examples/martini/server.go
vendor/github.com/rs/cors/examples/negroni/server.go
vendor/github.com/rs/cors/examples/nethttp/server.go
vendor/github.com/rs/cors/examples/openbar/server.go
vendor/github.com/rs/cors/go.mod
vendor/github.com/rs/cors/utils.go
vendor/github.com/rs/cors/utils_test.go
vendor/github.com/rs/cors/wrapper/gin/gin.go
vendor/github.com/rs/cors/wrapper/gin/gin_test.go

[EVG-15384](https://jira.mongodb.org/browse/EVG-15384)
TIPS is having trouble getting POST/OPTIONS requests to work with CORS. We've tried modifying the headers but haven't seen success. This is how cedar apparently handles CORS and TIPS says that it's working correctly so switching to that to see if it fixes anything.
Unfortunately I don't believe we have a way of testing this.

EVG-15384 use library to handle CORS for rest routes

---

model/stats/db.go

JIRA: https://jira.mongodb.org/browse/EVG-15396
- Use display test name in historical test stat calculations.
- Exclude stats of the two affected build variants during the affected period from historical test stat queries.

EVG-15396: Fix historical test stats aggregation to include display test names

---

gqlgen.yml
graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql

[EVG-15330](https://jira.mongodb.org/browse/EVG-15330)
With the previous setup if there was a failure fetching any logs (system, agent, task logs, event logs) the entire resolver would fail and return nothing. This refactors that resolver so that each log type is fetched in its own resolver. And if there is a failure it would be constrained to the resolver. It would also reduce any over-fetching we do on the UI since we can now only conditionally fetch each log type when the user requests it

EVG-15330 Split out tasklog resolvers into individual resolvers

---

units/host_drawdown.go
units/host_termination.go

[EVG-5312](https://jira.mongodb.org/browse/EVG-5312)
We've had a few build failures where a host is decommissioned in-between running tasks in a task group, and then later tasks in the group fail.
I wrote drawdown and termination to be slightly different because I think drawdown is meant more to deallocate when we don't need things (so it's safe to just not deallocate), whereas for termination we may truly want to terminate the host, so in this case I just mark the task group for reset rather than preventing the termination of the host. We can try and implement them more similarly though if this doesn't seem reasonable.

EVG-5312 decommission hosts running task groups carefully

---

cloud/pod_agent_util.go
cloud/pod_agent_util_test.go
cloud/pod_util.go
model/pod/pod.go

Jira: https://jira.mongodb.org/browse/EVG-15173
Modify the script to start the agent in a pod to be compatible with Windows.
Unit tests and tested the batch script in a Windows container. It can't be tested in an end-to-end way with ECS until [BUILD-13642](https://jira.mongodb.org/browse/BUILD-13642) is done.

EVG-15173: provision Windows pods with the agent

---

units/host_termination.go

[EVG-5312](https://jira.mongodb.org/browse/EVG-5312)

EVG-5312 use build ID instead of variant name to find task group

---

globals.go
model/build/build.go
model/lifecycle.go

[EVG-15283](https://jira.mongodb.org/browse/EVG-15283)
Was observed that build and task statuses were not being properly set to inactive when a patch has been dequeued from the commit queue, because the query to retrieve the builds and tasks were querying by an incorrect system activator (apiserver instead of default).  Change has been made to introduce a list of system activators in globals.go and query by all activators in this list instead of a single value.

EVG-15283: Query by all system activator statuses when setting build and task activation

---

agent/command/results_xunit_parser.go
agent/command/results_xunit_parser_test.go
config.go
model/task/task.go
model/test_log.go

[EVG-15436](https://jira.mongodb.org/browse/EVG-15436)
We should not store internal test log URLs for test results since we generate them [here](https://github.com/evergreen-ci/evergreen/blob/main/model/task/task.go#L341).

EVG-15436: Do not store URL in xunit test results

---

gqlgen.yml
graphql/generated.go
graphql/schema.graphql
graphql/tests/patch/data.json
graphql/tests/patch/queries/childPatchAliases.graphql
graphql/tests/patch/results.json
graphql/util.go
model/patch/patch.go
model/patch/patch_test.go
rest/model/patch.go

[EVG-15385](https://jira.mongodb.org/browse/EVG-15385)
- Add `SetTriggerAliases` field to ensure that we are logging the alias associated with each child patch (the `ChildPatches` and `Aliases` field within [`TriggerInfo`](https://github.com/evergreen-ci/evergreen/blob/main/model/patch/patch.go#L193) are zipped/have 1 to 1 correspondence)
- Add `childPatchAliases` GraphQL field to patch to return trigger name with each child patch ID
- Add DB and GraphQL unit tests

EVG-15385: Attach trigger name to patch

---

cloud/pod_util.go
cloud/pod_util_test.go
model/pod/pod.go
rest/model/pod.go
rest/model/pod_test.go

Jira: https://jira.mongodb.org/browse/EVG-15381
* Add REST route options to pass credentials to access private Docker repositories in ECS.
* Updated tests for the REST to DB model conversion and propagating the credentials to Cocoa during pod creation.
* Verified that pulling from a private repository with ECS works as expected in staging.

EVG-15381: add options for pod private repository credentials

---

rest/route/sns.go

Jira: https://jira.mongodb.org/browse/EVG-15333
I originally misconfigured the event rules to send both ECS task state changes and ECS container instance state change, but we only care about state changes related to ECS tasks, not the hosts running in ECS. I fixed the event rule to exclude the host state changes, so we don't need to no-op on this event type anymore.
I verified in the AWS EventBridge console that the event patterns excluded container instance state changes from the events sent to SNS notifications.

EVG-15333: exclude container instance state changes from SNS notifications

---

graphql/generated.go
graphql/integration_spec.json
graphql/resolvers.go
graphql/schema.graphql
rest/model/test.go
rest/model/test_test.go

[EVG-15379](https://jira.mongodb.org/browse/EVG-15379)
Once the spruce UI uses the test log URLs generated by the test results API, we can set `test_file` to the display test name rather than the unique test name used for backend purposes (downstream users do not really need to be aware of these non human readable names).
This PR should not be merged until [EVG-15418](https://jira.mongodb.org/browse/EVG-15418) is completed and spruce is deployed.

EVG-15379: Set the test_file field as the display test name for the test results API

---

rest/route/middleware.go
service/project.go

[EVG-15341](https://jira.mongodb.org/browse/EVG-15341)
Currently all routes that use urlVarsToProjectScopes in the middleware such as this [endpoint](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#get-versions-for-a-project) return a 500 internal server error when a merged project ref is unable to be found. Change has been made to return a 404 in this case instead.
Deployed to staging and confirmed that the route now returns 404 for an invalid project.  Attached screenshot.

EVG-15341: Return 404 when error encountered finding merged project ref

---

cloud/pod_agent_util.go
cloud/pod_agent_util_test.go
model/host/hostutil.go
model/host/hostutil_test.go
model/host/stats_test.go

Jira: https://jira.mongodb.org/browse/EVG-15225
* Remove quotation marks from URL being curled because Windows batch scripts don't allow single quotes. The quotes shouldn't be necessary for the bash/batch script to have valid syntax.
* Fix [a test](https://github.com/evergreen-ci/evergreen/pull/5050/files#diff-2567873892e2fae0771c76fc6d952f51827126e55f8840e253c9e26736268d20R22) that breaks if the `host.running_tasks` unique index exists (which is created by [this test](https://github.com/evergreen-ci/evergreen/blob/0ac37d2251e9fa6833e214944c77058955ea43f3/units/host_monitoring_idle_termination_test.go#L45)). @hhoke 
Updated the unit tests.

EVG-15225: remove single quotes from agent curl command for Windows

---

rest/route/host.go

[EVG-15356](https://jira.mongodb.org/browse/EVG-15356)
There is currently no record in Splunk when we offboard users.  Added logging to track who we offboard and when.

EVG-15356: Send log to splunk when user offboards

---

graphql/generated.go
graphql/integration_spec.json
graphql/resolvers.go
graphql/schema.graphql
rest/model/test.go
rest/model/test_test.go

[EVG-15379](https://jira.mongodb.org/browse/EVG-15379)
This was already tested approved, I just added back the `display_test_name` field to the `APITest` struct and `TestResult` object in the graphql schema for backwards compatibility in spruce.

EVG-15379: Set test_file to display name and keep display_name field temporarily for spruce

---

model/user/db.go
rest/route/service.go
rest/route/user.go
rest/route/user_test.go

[EVG-15430](https://jira.mongodb.org/browse/EVG-15430)
Add a route for mana to use to return all of the users that have a given role.
Added unit test and tested on local.

EVG-15430 add route to get users for role

---

glide.lock
rest/route/middleware.go
rest/route/options.go
rest/route/service.go
rest/route/service_test.go
vendor/github.com/evergreen-ci/gimlet/app_routing.go
vendor/github.com/evergreen-ci/gimlet/app_routing_test.go

[EVG-15384](https://jira.mongodb.org/browse/EVG-15384)
This adds support for [pre-flight OPTION](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) requests for all POST request routes on the `/rest/v2` endpoints.
These requests are used to verify that CORS requirements are satisfied, Before the actual POST requests are sent. 
I've also added a header that should prevent the client from sending this type of request more then once every 10 minutes (Which is the max time i can set)
This is dependent on revendoring https://github.com/evergreen-ci/gimlet/pull/98 
Tested in staging and wrote unit tests

EVG-15384 Support pre-flight options requests for all POST routes.

---

globals.go
model/user/user.go
rest/route/user.go
rest/route/user_test.go

[EVG-15321](https://jira.mongodb.org/browse/EVG-15321)
We made this route for Mana but they were told that we would accept a resource ID, and apparently we don't, which means that no matter what we're deleting a ton of resources for users. We should only delete roles relevant to the resource, and we should ignore the basic roles so that the user can remain a basic user of Evergreen.
Fixed unit test.

EVG-15321 modify delete user route to require resource ID

---

units/pod_termination.go
units/pod_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-15461
Intent pods don't have any backing resources in ECS or Secrets Manager, so there's no way to create a Cocoa pod from an Evergreen intent pod. During pod termination, intent pods can skip the deletion of the backing cloud resources, so all they have to do is be marked as terminated.
Updated the job tests.

EVG-15461: terminate intent pods

---

model/distro/db.go
model/distro/distro.go
model/host/hostutil.go
model/host/hostutil_test.go
rest/model/distro.go
rest/model/distro_test.go
rest/route/distro_test.go
service/templates/distros.html
validator/distro_validator_test.go

Jira: https://jira.mongodb.org/browse/EVG-15466
* Add distro setting for Jasper service max cgroup tasks.
* Tested the distro setting locally.
* Tested that hosts can run with the systemd parameter in staging.

EVG-15466: add distro setting for Jasper service max cgroup tasks

---

agent/command/registry.go
config.go

[EVG-15456](https://jira.mongodb.org/browse/EVG-15456)
Didn't make cmds length an error because we check for this elsewhere and add an error so it would be duplicate info; at this point we should just make sure we don't panic.
Tested with local evergreen.

EVG-15456 check for nil cmds when validating

---

glide.lock
vendor/github.com/evergreen-ci/gimlet/vendor/github.com/urfave/negroni/static.go

[EVG-15423](https://jira.mongodb.org/browse/EVG-15423)
Revendor gimlet (already PR'd) to avoid open redirect issue.
Ran on staging without errors, fixed redirect issue.

EVG-15423: resolve open-redirect issue by merging initial path slashes

---

cloud/pod_util.go
cloud/pod_util_test.go

JIra: https://jira.mongodb.org/browse/EVG-15225
Containers target a particular CPU architecture, so ensure that pods get assigned to compatible hosts.
Updated cloud unit tests.

EVG-15488: constrain pod placement according to compatible CPU architecture

---

environment.go
graphql/ui_plugin_build_baron.go
model/project.go
model/project_parser.go
model/project_parser_db.go
model/project_ref.go
plugin/build_baron.go
plugin/build_baron_test.go
rest/route/annotations_test.go
service/ui.go

[EVG-15212](https://jira.mongodb.org/browse/EVG-15212)
Was observed [here](https://mongodb.slack.com/archives/C0V896UV8/p1630698656157000) that a user was unexpectedly seeing build baron UI panels showing up on all tasks regardless of whether or not they were failed or not.  Rolled back the change and tested locally, found that the UI panel was rendering due to a null pointer exception on the frontend.  Before the rollback a change was made to return a nil object in the case we are unable to retrieve the build baron config settings when rendering the UI panel config.  Change has been made to return a struct with enabled: false to prevent conf.enabled from throwing a null pointer exception when this occurs.  The initial EVG-15212 changes have also been un-reverted.
Checking out the old …

EVG-15212: Fix build baron HTML error for disabled projects

---

cloud/pod_util.go
cloud/pod_util_test.go
public/static/js/admin.js

JIra: https://jira.mongodb.org/browse/EVG-15488
* Fix the placement constraint string to enforce that a pod runs on a host with a particular architecture.
* Fix a bug in the admin page where the delete buttons didn't work for AWSVPC subnets and security groups.

EVG-15488: fix pod CPU architecture constraint

---

rest/model/task.go

EVG-15263: https://jira.mongodb.org/browse/EVG-15263

EVG-15263: Do not expose internal cedar test results fields via task API

---

model/project_parser.go
model/project_parser_db.go
model/project_ref.go
model/project_ref_test.go
plugin/build_baron.go
plugin/perf.go
service/api_task.go

[EVG-15405](https://jira.mongodb.org/browse/EVG-15405)
With the introduction of the Expose Configuration Options to Users project, there are many places where we retrieve a parser project, check if certain properties are defined, and if not default to the settings on the project ref.  Initially it seemed like it would be cleaner to merge the parser project ref into a single entity on the backend, and refer to this merged struct for all project settings related operations.  The work involved in this however would likely require a larger refactoring of both our database schemas and would fundamentally change the way we view projects from a backend standpoint which is out of scope for this project.  
To improve code cleanliness and readability, a new struct has been introduced that holds all …

EVG-15405: Use merged parser project and project ref struct for properties that are shared between them

---

gqlgen.yml
graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
model/task/task.go
model/task/task_test.go
rest/data/task.go

[EVG-15459](https://jira.mongodb.org/browse/EVG-15459)
Refactors GetTasksByVersion query to conditionally include basetask information reducing a $lookup.
Refactors GetTasksByVersion query and moves most of the pipeline into a utility function for reuse.
Use said utility function to create a  new query which calculates task stats in mongodb.
Time to fetch task stats on a patch with >4k tasks 
before: 3.2s
after: 1.2s
Unit tests

EVG-15459 Resolve Task Stats in mongodb instead of go

---

service/templates/projects.html

[EVG-14977 ](https://jira.mongodb.org/browse/EVG-14977)
This was kept hidden till now so that users don't start using it before it is ready. While the feature is not yet fully ready to role out, at this point, a user using it won't break it, and they'll already see the downstream tasks on the patch page. 
none

EVG-14977 Unhide Adding and creating Patch Trigger Aliases

---

graphql/resolvers.go
model/task/db.go
model/task/task_test.go

[EVG-14856](https://jira.mongodb.org/browse/EVG-14856)
Refactors the execution tasks resolver to perform between 1-2 db calls instead of several for each execution task.  
For an improvement of  O(N) -> O(1) db calls in the best case scenario where all executions line up.
And O(2N) -> O(2) when the executions are mismatching. 
Unit tests

EVG-14856 Refactor execution task resolver to perform one query instead of several

---

agent/command/git_merge_pr.go
config.go
graphql/resolvers.go
model/project.go
model/project_parser.go
model/project_parser_merge_functions.go
model/project_ref.go
operations/commit_queue.go
rest/data/commit_queue.go
rest/data/project.go
rest/model/project.go
rest/route/middleware.go
rest/route/project.go
rest/route/repo.go
service/api.go
service/project.go
units/commit_queue.go
units/patch_intent.go

[EVG-15206](https://jira.mongodb.org/browse/EVG-15206)
Parser project struct has been updated to support commit queue configs in the yaml structure and all relevant places where properties are checked on the commit queue configs for a given project will now be checking a merged project ref struct with any necessary overriding properties from the parser project.

EVG-15206: Add CommitQueue to parser project

---

graphql/generated.go
graphql/query_test.go
graphql/resolvers.go
graphql/schema.graphql
graphql/util.go
model/task/task.go
model/task/task_test.go
model/version.go
model/version_test.go

[EVG-14930](https://jira.mongodb.org/browse/EVG-14930)
This works the same way as https://github.com/evergreen-ci/evergreen/pull/5038 But is a little more refined and less error prone.
We will stop fetching mainline commits after we have searched 300 commits. To prevent endlessly checking the versions collections
I wrote some programmatic graphql tests. Instead of the static comparison based ones we use elsewhere

EVG-14930 Fetch unmatching commits 

---

units/util.go

[EVG-15412](https://jira.mongodb.org/browse/EVG-15412)
A pointer to the iterator variable is getting passed into the job which, in the test, is a local queue that runs the actual job in parallel using the host pointer.
I changed it to pass a pointer to the slice so the caller won't be writing to the host variable that the job is reading.
I ran the test locally with the race detector and it didn't detect a race.

EVG-15412 pass a pointer to the slice itself

---

makefile

Jira: https://jira.mongodb.org/browse/EVG-15573
Make sure that the cache environment variables are defined if they're unset. If the environment already explicitly defines them, then use those. Otherwise, fall back to caching within the build directory.

EVG-15573: ensure cache environment variables are set

---

agent/command/git.go
agent/command/git_patch_test.go
agent/command/git_test.go
agent/command/testdata/git/additional_patch.yml
config.go
operations/patch_module.go

https://jira.mongodb.org/browse/EVG-15267
Please see https://github.com/evergreen-ci/evergreen/pull/5083 for a longer discussion. Those fixes are cherry-picked in https://github.com/evergreen-ci/evergreen/pull/5114/commits/4e15e54472fe49a277cea407ef6241108c118cdd. The additional fixes in this ticket are these:
- https://github.com/evergreen-ci/evergreen/pull/5114/commits/8455e47d66a39c20b1dc156073dcc0e3d8474cae  addresses incorrectly handling the directory for modules from earlier in the function where we originally made changes.
- https://github.com/evergreen-ci/evergreen/pull/5114/commits/dd9e8e2363cd71f8b974e422b5597227e54c39a9 fixes a test, as I also removed the "ls" in this ticket, which was extraneous and scheduled to be removed in https://jira.mongodb.org/browse/EVG-15574.
- …

EVG-15267 Apply module patches consistently with cloning them

---

graphql/resolvers.go
graphql/tests/buildVariantsForTaskName/data.json
model/task/db.go
model/task_build_variant_names_test.go

[EVG-15586](https://jira.mongodb.org/browse/EVG-15586)
Fetching build variants  for the `buildVariantForTaskName` query was painfully slow. Since it would check every task ever created for a project through out its entire existence to get the build variants that ran and then it would do a $lookup to fetch the proper display names for build variants. 
This was super slow because the Shier amount of data it needed to check. I opted to limit it to only check the last 50 versions for a project.  Which is the same amount of versions we check on the legacy task history page https://github.com/evergreen-ci/evergreen/blob/0d5ea465c5e102ed76e2648570f61a1fd1f151ba/service/task_history.go#L97
Also added a check to the `taskNamesForBuildVariant` query that should omit execution tasks from being …

EVG-15586 Limit task history to last 50 columns

---

model/project_ref.go
public/static/js/projects.js
rest/model/project.go
rest/route/github.go
service/templates/projects.html
thirdparty/github.go

[EVG-14530](https://jira.mongodb.org/browse/EVG-14530)
Allow teams to require that commits be signed before merging prs. 
With unsigned commits: 
With signed commits:

EVG-14530  Evergreen Require signed commits for commit queue

---

public/static/js/projects.js
service/templates/projects.html

[EVG-15307](https://jira.mongodb.org/browse/EVG-15307)
Ng-repeat can't handle duplicates, so allowing duplicates to be added causes the admin lists to not display correctly. I added some handling for admin fields and will update the ops-manager-kubernetes to not have duplicates so that this problem goes away for them.
Tested all three fields in staging. (Could theoretically add to more fields but purposefully adding duplicates is a pretty rare thing to do and this page is legacy so I think it's not worth that.)

EVG-15307 disallow project admin duplicates

---

model/project_ref.go
model/project_ref_test.go
public/static/partials/periodic_build_modal.html

[EVG-15394](https://jira.mongodb.org/browse/EVG-15394)
We don't actually require an alias here, especially since users can define a completely separate yaml. This is consistent with [documentation](https://github.com/evergreen-ci/evergreen/wiki/Project-and-Distro-Settings#periodic-builds).
Verified I was able to save a periodic build in the DB without error and that it no longer shows up as required on the UI.

EVG-15394 allow periodic build definitions without alias

---

config.go
operations/http.go
operations/patch_module.go
service/api.go
service/api_patch.go

[EVG-14655](https://jira.mongodb.org/browse/EVG-14655)
I think the difficulty with the error is that it doesn't say what project you're using or specify that the project itself may be the problem, so I added some detail.
tested using local.
```
$ ../evergreen/clients/darwin_amd64/evergreen -c ~/.evergreen-local.yml set-module -i 5f74d99ab2373627c047c5e5 -m dsi  -y
module 'dsi' unknown or not found
Project 'evergreen' has no configured modules. Specify different project or see the evergreen configuration file for module configuration.
$ clients/darwin_amd64/evergreen set-module -i 61689cf1c9ec443f692bd8b0 -m dsi -y
module 'dsi' unknown or not found
Could not find module named 'dsi' for project 'spruce'. Specify different project or select correct module from:
evergreen
```

EVG-14655 return clearer errors for set-module

---

globals.go
model/patch_lifecycle.go
model/task/db.go
operations/commit_queue.go
operations/host_spawn.go
operations/patch.go
operations/patch_module.go
operations/patch_util.go
units/generate_tasks.go

[EVG-14205](https://jira.mongodb.org/browse/EVG-14205)
Logging in patch creation and generate tasks. Chose to define the initial number at which we log at as a global, but since we log the num_tasks_activated we can modify what to alert on based on this rather than needing code changes. 
Chose this number based off of some aggregations: the largest waterfall version between October 1 and October 14th had 24545 tasks; for patches this was 13815. A required builders patch build is more likely to be about 5000 activated tasks. I may initially set the Splunk alert for 15,000.

EVG-14205 log when version has large number of activated tasks

---

model/github_hook.go
model/project_aliases.go
model/project_aliases_test.go
rest/data/aliases.go
service/project.go

[EVG-15779](https://jira.mongodb.org/browse/EVG-15779)
Given logging and the fact that we _do_ have a github hook ID in the DB, I kind of feel like this was a github issue, or that errors are now returned to us in ways we don't know how to process, so I'd like to log this body.

EVG-15779 add logging when creating github hook

---

model/project.go
model/project_matrix.go
model/project_matrix_test.go
model/project_parser.go
model/project_parser_db.go
model/project_parser_db_test.go
model/project_selector.go

[EVG-15661](https://jira.mongodb.org/browse/EVG-15661)
Didn't consider that variants can be created from matrix definitions. Included this from translateProject.
I'm a bit put out that I had to slightly learn matrices to unit test this.

EVG-15661 improve fetching expansions for variants (with matrices)

---

rest/data/project_settings.go
rest/model/project.go

[EVG-15671](https://jira.mongodb.org/browse/EVG-15671)
We were having an issue copying and then enabling a project due to PR testing issues; while I was able to replicate this when the issue came up, I wasn't able to today; to be safe, I think we _should_ mark PR testing enabled as false explicitly, since for now we are enforcing that this can only be enabled once per branch.
I also introduced a bug to patch route by incorrectly copying periodic build definitions; this is fixed.
Tested on local.

EVG-15671 fix small bugs with copy and patch project routes

---

units/generate_tasks.go

[EVG-15676](https://jira.mongodb.org/browse/EVG-15676)
We send errors saving to the task logs so we don't need to always log in order to debug tasks; if the job overall fails due to this error we'll still log it to splunk with the job. Also should log at a lower level since this doesn't demonstrate an application error necessarily.

EVG-15676 log generate task errors at a lower level

---

graphql/resolvers.go
graphql/tests/taskNamesForBuildVariant/data.json
model/task/db.go
model/task/task_test.go

[EVG-15764](https://jira.mongodb.org/browse/EVG-15764)
This adds the same limits as #5144 to the taskNamesByBuildVariant query

EVG-15764 Limit taskNamesByBuildVariant query to last 50 versions

---

service/task.go
service/version.go
trigger/payloads.go
trigger/task_jira_test.go

[EVG-14660](https://jira.mongodb.org/browse/EVG-14660)
links now have `?redirect_spruce_users=true`
on staging 
https://evergreen-staging.corp.mongodb.com//task/evg_lint_generate_lint_e47bb73265e2eb443ea129a3b444336a3da1d53b_21_10_22_21_07_36/1/?redirect_spruce_users=true
caused a user not found panic once but im not sure what triggered it

EVG-14660 Update notifications to use new ui link when possible

---

model/task/db.go
model/task/task.go
model/task_build_variant_names_test.go

[EVG-15334](https://jira.mongodb.org/browse/EVG-15334)
We would hit  the 16 mb document limit if we try to load a large version with allot of tasks in the `$facet` stage. 
When we would make non limited/paginated requests to this query all of the returned tasks would be embedded in one document causing it to exceed the 16 mb document limit mongodb imposes.  
We can get around this by not using the `$facet` if the results are not paginated. Instead computing the total count in go (Because we have access to all of the results in this scenario).  
This allows us to preserve the advantages the `$facet` provided (Not needing to perform 2 queries to fetch the count without the pagination) While also avoiding the document size limit in the scenarios where we would run into them.
Staging and …

EVG-15334 Handle 16 mb limit on unpaginated requests

---

agent/command/git.go
agent/command/git_test.go
config.go

[EVG-15680](https://jira.mongodb.org/browse/EVG-15680)
Sometimes the clone directory is absolute. In those cases we shouldn't merge it with the working directory.
I added a unit test for the new directory function, but I didn't see a way to test the full code path.

EVG-15680 Fix join with absolute clone directory

---

model/project_aliases.go
model/project_aliases_test.go
model/project_ref_test.go
rest/data/aliases.go
rest/data/aliases_test.go
rest/route/project_test.go

[EVG-15307](https://jira.mongodb.org/browse/EVG-15307)
I realized there's a bug with how patch aliases work for project/repo; right now we check "do we have a matching alias" and if we don't we check the next level (parser project -> project -> repo). This works for internal aliases like __github_alias, however patch aliases can be named anything. If the project overrides the repo by defining patch alias "alias1" and "alias2", we shouldn't continue to check the repo when "alias3" doesn't show up.
Alternatively we can change the design to have patch aliases work like project variables 😬  But maybe let's start with this and reconsider the design if needed?
Added a unit test case and verified existing tests pass.

EVG-15307 consider patch aliases as overridden even if one doesn't match

---

agent/command/s3_copy.go
config.go

[EVG-15725](https://jira.mongodb.org/browse/EVG-15725)
Right now, we upload files to the test even if s3_copy didn't succeed, or if it succeeded because it's optional, but didn't truly copy over. This is very confusing to users, especially if a file of that name already exists in the destination bucket, but it's not truly related to the test since the copy failed. 
Tested in staging. The first execution failed and has 0 files and the second execution succeeded and has 1 file. 
https://spruce-staging.corp.mongodb.com/task/evg_ubuntu1604_s3_fake_destination_optional_patch_7e0cce4bf0fe845220526732bae0677256643421_618d9094b237364acb006453_21_11_11_21_52_38/logs?execution=0

EVG-15725 Only add files if S3 Copy succeeded

---

agent/command/git_test.go

[EVG-15680](https://jira.mongodb.org/browse/EVG-15680)
Fix windows tests, since Windows uses different slashes.
The test broke. I fixed it.

EVG-15680 Fix windows test

---

makefile
self-tests.yml

Jira: https://jira.mongodb.org/browse/EVG-15847
The linter is very slow on the first task in the lint task group because the lint cache starts out cold on the host.
* Use -large distro so that it runs faster.
* Bump the timeout so the linter can still succeed if it's unavoidably slow.

EVG-15847: reduce likelihood of linter timeout

---

graphql/resolvers.go
model/task/db.go
model/task/task_test.go

[EVG-15738](https://jira.mongodb.org/browse/EVG-15738)
This PR introduces a new function `DisplayTasksByVersion` (in `model/task/db.go`) which finds the display tasks for a given version. This function is used to correct the task count displayed on the front end, which previously mistakenly counted execution tasks in the total task count.
**Note**:  There is no corresponding Spruce PR, as this change automatically affects the numbers displayed on front end.
(Previously, this page would say `1/4 tasks`.)
- Added `TestDisplayTasksByVersion` in `model/task/task_test.go`

EVG-15738 Add DisplayTasksByVersion query to get correct TotalTaskCount

---

cmd/evg-lint/evg-lint.go
cmd/generate-lint/generate-lint.go
go.mod
go.sum
makefile

Jira: https://jira.mongodb.org/browse/EVG-15453
* Add custom evg-lint tool back to linters.
* Track evg-lint as part of Go module dependencies. I used a strategy similar to how [gqlgen](https://github.com/evergreen-ci/evergreen/blob/eb514bf6be86ebcc71eec5b73f22d0f7cdc20f48/cmd/gqlgen/gqlgen.go#L1-L11) is tracked as a tool dependency.
I temporarily modified generate-lint to run on all targets, just to verify that CI tests pass. I'll revert it before merging the PR.
I also did [a test patch](https://spruce.mongodb.com/version/6192985c30661561e3952390/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) to verify that evg-lint was actually running as intended and catching lint issues when I purposely introduced one.

EVG-15453: add evg-lint as linting tool dependency

---

service/api_plugin_s3copy.go

[EVG-15839](https://jira.mongodb.org/browse/EVG-15839)
Whenever s3Copy finds a push event for a file in a version with the status "success" or "pushing", it no-ops instead of trying to push again the same file again. The message it logged to the task: "noop, file filename.tgz exists" was sometimes confusing and inaccurate. If a file was still in the "pushing" state and later failed, the file doesn't truly exist, we are simply not pushing again because we are waiting on that process to finish. 
Tested something similar on staging

EVG-15839 fix confusing s3_copy task log "noop file exists" message

---

agent/internal/client/host_methods.go
config.go

[EVG-15840](https://jira.mongodb.org/browse/EVG-15840)
This returns the response string so that the taskLogger can actually pick it up [here](https://github.com/evergreen-ci/evergreen/blob/main/agent/command/s3_copy.go#L206) when it checks if the response string is there. Until this change, the response string was always "".
[Tested on staging ](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu1604_s3_fake_destination_optional_patch_7e0cce4bf0fe845220526732bae0677256643421_618e278097b1d3305b7dcc04_21_11_12_08_36_31/logs?execution=0)

EVG-15840 Return the response of the s3 copy command

---

service/templates/projects.html

[EVG-13840](https://jira.mongodb.org/browse/EVG-13840)
I took the ticket to handle the backend portion of this work but it turns out it already works (considering [these functions](https://github.com/evergreen-ci/evergreen/blob/a5a7a6a1a3559f21b357be14142871dd3eddd8b4/model/project_aliases.go#L370-L369) are always used).
Added to the legacy UI so that users could stop being blocked on this; will add comments to the figma design to make sure that we do this for the new page.
Tested on local to verify that the information gets saved correctly.

EVG-13840 allow specifying variant tags for project aliases

---

makefile

Jira: https://jira.mongodb.org/browse/EVG-15596
`TMPDIR` is only useful in CI tests where writing outside of the working directory is not advised. For local development, `TMPDIR` is typically set and if not, defaults to `/tmp`, which seems reasonable. For CI tests, `TMPDIR` is set by default in the environment, so it should be safe to run tests without explicitly setting it. Therefore, it's not necessary to point `TMPDIR` to a path within the working directory anymore.
This also fixes `TestMakePatchedConfig` in `make test-model`, which fails if `TMPDIR` is not set and uses the makefile default of `bin/tmp`. That test relies on using git apply, but git apply behaves differently when the path is within an already git-controlled directory (`bin/tmp`) compared to when it's written outside of …

EVG-15596: do not set build directory TMPDIR for makefile

---

makefile

Jira: https://jira.mongodb.org/browse/EVG-15584
This is mostly to reduce noise in the task logs. If the Go binary is not in the PATH (e.g. the mongod setup targets don't set them), setting the GOOS/GOARCH for the local CLI will fail. GOOS/GOARCH only used for the local binary and cross-compilation, so they should only be set for make targets that actually use Go in some way.
I checked that the CI tests pass and don't output the error `make: go: No such file or directory` in the task log.

EVG-15584: only set goos/goarch if the Go binary is available

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/reprovisionToNew/data.json
graphql/tests/reprovisionToNew/queries/empty-array.graphql
graphql/tests/reprovisionToNew/queries/multiple-hosts.graphql
graphql/tests/reprovisionToNew/queries/no-hosts-found.graphql
graphql/tests/reprovisionToNew/queries/single-host.graphql
graphql/tests/reprovisionToNew/queries/user-has-no-permission-to-edit-host.graphql
graphql/tests/reprovisionToNew/results.json

[EVG-13586](https://jira.mongodb.org/browse/EVG-13586)
This PR adds a new mutation function `ReprovisionToNew` to `resolvers.go`, which is called whenever the new button on the Spruce UI is clicked. Note that this button and the functionality for reprovisioning a host already existed for the legacy UI, so all this PR does is call these functions in the `graphql` format.
- Add graphql tests for `reprovisionToNew` mutation in `graphql/tests/reprovisionToNew`
- Unit tests for this functionality already existed

EVG-13586 Add reprovisionToNew mutation

---

self-tests.yml

Jira: https://jira.mongodb.org/browse/EVG-15682
Other Evergreen repos use the `DISABLE_COVERAGE` environment variable to test with code coverage. However, Evergreen performs coverage tests slightly differently, so it doesn't rely on `DISABLE_COVERAGE` when producing `output.%.coverage` files.
N/A

EVG-15682: remove unused DISABLE_COVERAGE flag

---

cmd/verify-mod-tidy/verify-mod-tidy.go
makefile
self-tests.yml

Jira: https://jira.mongodb.org/browse/EVG-15448
Add a helper Go script and CI task to check if go mod tidy has been run, which is important for keeping the go.mod and go.sum clean. If it hasn't been run, the make target and CI task will fail. I ran it locally to check that it works as expected.

EVG-15448: add check for mod tidy

---

model/project_aliases_test.go
model/version_db.go

[EVG-15863](https://jira.mongodb.org/browse/EVG-15863)
If the returned version has errors, try again.
Could also return all the versions right away, but really in almost all cases error _is_ empty, so I think it's reasonable to push the additional work off unless we've actually hit a problem.
Verifying that existing tests pass.

EVG-15863 add loop on error to get version with good config

---

rest/model/patch.go
rest/model/patch_test.go

[EVG-15202](https://jira.mongodb.org/browse/EVG-15202)
It looked like downstream tasks wasn't populating for the api endpoint, but what was really happening was that the downstream patch had no tasks, it only had variant tasks. 
Added to the existing test.

EVG-15202 Add variant tasks to downstream tasks 

---

graphql/util.go
model/lifecycle.go
model/lifecycle_test.go
validator/project_validator.go

[EVG-15837](https://jira.mongodb.org/browse/EVG-15837)
Previously, all taskgroup tasks were showing up on the config page even if they weren't supposed to (ie upload-cli sets patchable to false but still shows up when you create a patch.) The changes fix this problem 
uplad-cli doesn't show up on the config page anymore
https://spruce-staging.corp.mongodb.com/patch/61967796b2373666af059883/configure/tasks

EVG-15837 Update CreateTasksFromGroup to disable correctly

---

repotracker/repotracker.go
repotracker/repotracker_test.go
units/periodic_builds.go

[EVG-15653](https://jira.mongodb.org/browse/EVG-15653)
This creates a stub version when a periodic build version fails so that people who have notifications configured will know that it failed instead of it failing silently. 
tested on staging 
[stub version](https://evergreen-staging.corp.mongodb.com/version/6197aa60b23736685749e4e2)

EVG-15653 periodic builds should create a stub version when there's an error

---

model/task/task.go

[EVG-15709](https://jira.mongodb.org/browse/EVG-15709)
This clears host_create_details and override_dependencies. The ticket comment also also asks to clear task_failure_details: I'm not sure if that refers to task.details which is already being cleared, or something else. 
None, because there is no existing test to add to.

EVG-15709 Clear necessary fields between task executions

---

model/testresult/testresult.go

JIRA: https://jira.mongodb.org/browse/EVG-15285
I tested that I didn't break the filtering on both legacy and spruce staging UIs.

EVG-15285: Filter mongo-stored test results by display test name

---

public/static/js/projects.js

[EVG-15768 ](https://jira.mongodb.org/browse/EVG-15768)
Could make this change more robust but since this is legacy and is mostly just done by our team I think a small fix is best.
Changed logkeeper project to "logkeeper2" and verified that trying to create a new logkeeper returned this error.

EVG-15768 display error when project identifier already exists

---

public/static/js/subscriptions.js
trigger/task.go

[EVG-15739](https://jira.mongodb.org/browse/EVG-15739)
I'm pleasantly surprised with how easy this was to add. The framework is set and the task document already stores build variant so adding it as a selector allows us to case on it.
Added a subscription on the lint variant from the project page. Restarted a lint task and a non-lint task and confirmed that only the lint one sent a notification.
The subscription:
```
{
"_id" : "61a6a497b2373648ab6c4eb1",
"selectors" : [
{
"type" : "project",
"data" : "mci"
},
{
"type" : "requester",
"data" : "gitter_request"
}
],
"regex_selectors" : [
{
"type" : "build-variant",
"data" : "lint"
}
],
"subscriber" : {
"type" : "slack",
"target" : "@annie.black"
},
"owner" : "mci",
"owner_type" : "project",
"trigger_data" : {
"requester" : "gitter_request" …
```

EVG-15739 allow filtering task notifications by build variant

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/version/queries/baseVersion.graphql
graphql/tests/version/results.json

[EVG-13178](https://jira.mongodb.org/browse/EVG-13178)
We need the base version's order number to create links for "Go to last passing version" and "Go to last executed version" on the task page.
Integration tests

EVG-13178: resolve baseVersion on Version gql type

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/util.go

[EVG-15639](https://jira.mongodb.org/browse/EVG-15639)
This is an alternative approach to #5239 which gives us more flexibility when fetching test results and avoids needing to refresh all the data when a new filter is applied.

EVG-15639 Alternative approach Create test result sample resolver

---

self-tests.yml

[EVG-15924](https://jira.mongodb.org/browse/EVG-15924)
This was accidentally committed to main 
Created a [patch](https://spruce.mongodb.com/patch/61b70caec9ec4412edcc263f/configure/tasks). s3-fake-destination-optional is no longer there, but docker-cleanup is .

EVG-15924 Remove s3-fake-destination-optional

---

cloud/docker_client.go
cloud/docker_test.go
cloud/docker_util.go
cloud/gce.go
cloud/gce_client.go
cloud/gce_test.go
cloud/gce_util.go
cloud/vsphere.go
cloud/vsphere_client.go
cloud/vsphere_mock_test.go
cloud/vsphere_test.go
cloud/vsphere_util.go
go.mod
go.sum
thirdparty/docker/docker_cleanup.go
thirdparty/docker/docker_cleanup_test.go

Jira: https://jira.mongodb.org/browse/EVG-15734
Upgrade Docker to the latest tagged version and bump Jasper to be compatible with the latest version. Ordinarily, a Go module would allow multiple major versions of a transient Go module dependency (e.g. this repo can use v1 of github.com/urfave/cli but dependent Go modules can use github.com/urfave/cli/v2 without conflicting with this repo). However, because Docker does not use Go modules, we cannot have multiple different major versions of the Docker SDK (hence why the Go modules has the `+incompatible` tag on it), so Evergreen and all its dependencies must agree to use Docker v20 now.
Verified in staging that the container building process still works.

EVG-15734: Upgrade Docker to v20.10.11

---

trigger/task.go

[EVG-15901](https://jira.mongodb.org/browse/EVG-<number>)
This change prevents BFGs from being created if all subtasks failures are identified as stranded or setup-failed.

EVG 15901 Skip BFG creations if all subtask failures are setup-failed or stranded

---

model/pod/pod.go
rest/data/pod.go

Jira: https://jira.mongodb.org/browse/EVG-15230
I added a field to distinguish the type of pod. While there's only one type of pod today for running agents, it's reasonable to assume that there will be more uses aside from running agents in the future (e.g. spawn pods).
This is future-proofing against the pain point that's arisen with multiplexing many different types of host on a single data model, where the different hosts are distinguished using a variety of fields so that different pieces of code only operate on the "right" type of host. For example, container parents have their own field `HasContainers`, containers have their own field `ParentID`, spawn hosts are distinguished with a combination of fields, hosts running agents are distinguished by checking if the host user is "mci". …

EVG-15230: add field to distinguish pod types

---

units/host_monitoring_idle_termination.go

Jira: https://jira.mongodb.org/browse/EVG-15957
This improves the message formatting in the event logs. The time durations are currently expressed in nanoseconds in the logs, so I changed it to the human-readable hours-minutes-seconds string format (e.g. 5h20m10s).

EVG-15957: improve idle termination message readability

---

model/project_parser.go

[EVG-15948](https://jira.mongodb.org/browse/EVG-15948)
A mistake was made when adding the module functionality to only set RemotePath in that case. I corrected this, and added some logging to make debugging any issues with include easier in the future.
Tested by running validate and creating a patch with an included file, similar to the user's. (Example: https://spruce-staging.corp.mongodb.com/patch/61ba4b7f9dbe327410f3fac6/configure/tasks)

EVG-15948 set remote path correctly for included yamls

---

model/project_ref.go
model/project_ref_test.go
rest/data/project.go
rest/data/project_settings.go
service/project.go

[EVG-15919](https://jira.mongodb.org/browse/EVG-15919)
We partially handled this in https://jira.mongodb.org/browse/EVG-15428 but we didn't handle the case where we exit before even trying to add/remove admins.
Added a case to the test.

EVG-15919 update admins in project ref only if successful

---

rest/route/annotations.go
rest/route/annotations_test.go

[EVG-16005](https://jira.mongodb.org/browse/EVG-16005)
When this endpoint was created, it was only meant to be used in conjunction with a webhook set up to be hooked up to the file ticket button. However, due to a new project to move build failure tickets, a new use case came up that warrants allowing the endpoint to be used independently. 
none

EVG-16005 Remove webhook check from created_ticket endpoint

---

config.go
globals.go
operations/commit_queue.go
operations/http.go
operations/patch_util.go
service/api_patch.go

[EVG-15656](https://jira.mongodb.org/browse/EVG-15656)
There's a lot of detail in the ticket but this adds a flag so that the server bot that creates commit queue patches on behalf of server engineers can specify github usernames, so that the patch will correctly be linked to the real author. 
Because this is a strong ability, I'll create a new bot for the server team to use that will have this permission. If the user doesn't have their github username on their profile, the patch will be listed as authored by "Commit Queue Bot User" or something like that, rather than Ethan Zhang, so still a step up.
I created this patch on Brian's behalf. https://spruce-staging.corp.mongodb.com/version/61bcf01697b1d3404fe84ca3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
He also still received …

EVG-15656 add gated flag to allow specifying cq patch author

---

model/project_parser_db.go
model/task_lifecycle.go
model/task_lifecycle_test.go
service/api.go

[EVG-15960](https://jira.mongodb.org/browse/EVG-15960)
Avoid using LoadProjectForVersion when the ParserProject exists, since we can just look it up directly, and the translation doesn't affect this.

EVG-15960 fetch parameters directly for fetch_vars

---

graphql/resolvers.go
graphql/tests/projectSettings/results.json
graphql/tests/repoSettings/results.json
graphql/tests/saveProjectSettingsForSection/results.json
graphql/tests/saveRepoSettingsForSection/queries/generalSection.graphql
graphql/tests/saveRepoSettingsForSection/results.json
graphql/util.go
rest/data/project_settings.go
rest/data/project_settings_test.go

[EVG-15979](https://jira.mongodb.org/browse/EVG-15979)
After discussion with Sophie, determined that private variables should be redacted before sending to the UI, and the backend save function should ensure that these are still saved correctly. This assumes that private variable values cannot be modified on the UI.
To do this, changed the UpdateProjectVars function to overwrite the existing variables object (i.e. using Upsert instead of FindAndModify) bc since the UI is sending the new variables and not the diff this is actually easier to reason about.
Added to the frontend and backend tests.

EVG-15979 redact private variables in the UI

---

model/pod/pod.go
rest/data/pod.go
rest/data/pod_test.go
rest/model/pod.go
rest/model/pod_test.go
rest/route/pod.go
rest/route/pod_test.go
rest/route/service.go
rest/route/sns_test.go

Jira: https://jira.mongodb.org/browse/EVG-15493
* Add REST route to get a pod by ID. The data model already exists, it just has to be exposed in the API.
* I made it available only for admins for now, since it's not a feature available for production. I'll change it to use looser permissions once the containers initiative is more production-ready.
* Fix the APIPod data model to include the required pod type field.
* Slightly fix mock pod data connector to have the same behavior as the DB connector for `FindPodByID`.
* Added test for REST route.
* Fixed existing REST tests to require pod type.

EVG-15493: add REST route to get pod information

---

validator/project_validator.go
validator/project_validator_test.go

[EVG-15012](https://jira.mongodb.org/browse/EVG-15012)
This PR contains a function that returns warning validation errors if not all tasks have timeouts set.
Modified some unit tests in `project_validator_test.go`

EVG 15012 Return warning errors if tasks have no timeout

---

model/project.go

[EVG-15899](https://jira.mongodb.org/browse/EVG-15899)
If a project does not yet have any versions created for it, it panics when trying to load the event log and waterfall. I added a check to make sure that there is a valid version. 
none

EVG-15899 fix this project's a panic

---

model/task/task.go
model/task_lifecycle.go
service/api_task.go
units/task_stranded_cleanup.go

[EVG-15797](https://jira.mongodb.org/browse/EVG-15797)
Added additional error logging when a task status is set to an empty string, and in these cases set the status to failed in order to preserve UI functionality.  Changed stranded task cleanup job to pass in a hardcoded details struct instead of &t.Details since an initial investigation indicated this might be an issue.

EVG-15797 Handle empty task status errors

---

service/templates/admin.html

[EVG-15217](https://jira.mongodb.org/browse/EVG-15217)
Now that plugin configs are derived from individual project configs, and not from the admin page, we do not need the UI component for plugins on the admin page.
Tested UI locally ensuring no errors.

EVG-15217 Remove legacy plugin UI component

---

trigger/task.go

[EVG-16022](https://jira.mongodb.org/browse/EVG-16022)
Right now, we deliberately don’t create notifications for setup failure. This reverses that.

EVG-16022 Fix setup failure notifications do not work

---

rest/data/subscription.go
rest/data/subscription_test.go

[EVG-16010](https://jira.mongodb.org/browse/EVG-16010)
When copying subscriptions using the rest routes, need to update the selector ID as well, or else we notify using the wrong project (this is already handled in the UI).

EVG-16010 update subscription selector project ID when copying

---

model/task_lifecycle.go

[EVG-15773 ](https://jira.mongodb.org/browse/EVG-15773 )
If a task has a test failure, we want to display "failed" regardless of what the last command type was. 
I'm not sure how to test this, but I'm fairly confident that it will work.

EVG-15773  Do not displays "SETUP FAILURE" when there is a test failure

---

go.mod
go.sum

Include the changes from https://github.com/evergreen-ci/gimlet/pull/114 and https://github.com/evergreen-ci/gimlet/pull/115.
Also included is an unrelated dependabot update from yesterday.

EVG-14198, EVG-15787 bump gimlet to 885442

---

model/lifecycle.go
model/task/task.go

[EVG-16024](https://jira.mongodb.org/browse/EVG-16024)
We explicitly set DisplayTaskId at creation for tasks but not display tasks, which means we go through GetDisplayTask for them even though they won't ever have one. 
We could also check in IsPartOfDisplay that DisplayOnly is false, however I think populating DisplayTaskId as much as possible is best for the UI, and effectively does the same thing in IsPartOfDisplay.

EVG-16024 set displayTaskId to empty for display tasks

---

model/task/task.go

[EVG-16024 ](https://jira.mongodb.org/browse/EVG-16024)
Removing this line possibly caused an issue with the deploy this morning.

EVG-16024 reintroduce shortcircuit for SetHasCedarResults

---

agent/command/registry.go
agent/command/shell.go
config.go
globals.go
validator/project_validator.go
validator/project_validator_test.go

[EVG-14232](https://jira.mongodb.org/browse/EVG-14232)
Modify validateCommands to also return an error when command shell.exec is specified without a script.

EVG-14232 Return error when shell.exec command is specified without a script

---

agent/global.go
agent/task.go
config.go
globals.go
validator/project_validator.go

[EVG-16071](https://jira.mongodb.org/browse/EVG-16071)
Use `DefaultExecTimeout` global variable in agent package in log message

EVG-16071 Use DefaultExecTimeout global variable in agent package

---

model/project.go
model/task/db.go
model/task/task_test.go

[EVG-15970](https://jira.mongodb.org/browse/EVG-15970)
The legacy waterfall has been causing CPU spikes; although we don't want to dedicate a lot of time to fixing the legacy queries, since the spruce UI is almost done, Jonathan identified loading the tasks as a big bottleneck, and we can make that less expensive by filtering out execution tasks, since we only use the display task statuses.
Wrote a unit test.

EVG-15970 filter exec tasks out of waterfall query

---

model/generate_test.go
model/project.go
model/project_parser.go
operations/patch.go
repotracker/github_poller.go
repotracker/github_poller_test.go
repotracker/mock_poller.go
repotracker/repotracker.go
rest/data/host_create.go
rest/data/interface.go
rest/data/project.go
rest/data/version.go
rest/route/github.go
service/api_plugin_manifest.go
trigger/project_triggers.go
trigger/project_triggers_test.go
units/generate_tasks.go
units/generate_tasks_test.go

[EVG-15923](https://jira.mongodb.org/browse/EVG-15923)
There are instances now across the codebase where 4 part function returns are being used (ProjectRef, ProjectParser, ProjectConfig, error).  To clean this up these methods will now be returning ProjectInfo struct which contains a thruple of the 3 aforementioned structs.
Modified existing unit tests

EVG-15923 Refactor multi return arguments for project configs into single ProjectInfo

---

model/host/hostutil.go
service/api_task.go
units/provisioning_agent_monitor_deploy.go

Jira: https://jira.mongodb.org/browse/EVG-16074
* Reduce log level during end task when attempting to shut down the monitor if host ran multiple consecutive tasks that system failed. In this case, the host may be in a bad state, so the host may not even be reachable to shut down the agent monitor in the first place.
* Move a log that checks the number of running agent monitors. This log is a state verification check that there should be at most one agent monitor process running on a task host at any given time. However, this can't be checked without iterating through all the processes returned from `withTaggedProcs` and totaling up the number. Since it requires some iteration, I moved it to the outer functions, which already iterate through the inputs anyways.
N/A

EVG-16074: improve agent monitor logging

---

model/project_ref.go
rest/route/project.go
rest/route/project_test.go
rest/route/repo_test.go
rest/route/service.go

[EVG-15056](https://jira.mongodb.org/browse/EVG-15056)
In my opinion, the PATCH project route is doing too much. To have attach/detach behavior be consistent with what's in the new UI, they work best as their own route. Because no one is using this yet, this won't break any workflows.
Created new tests and modified old tests to use the new routes.

EVG-15056 create new routes to attach/detach repos

---

agent/agent.go
config.go
globals.go
model/distro/distro.go
model/host/host.go
units/host_termination.go
units/host_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-16064
The EC2 instance ID wasn't being sent by agents running in on-demand hosts because I accidentally excluded it from the filter in `(*agent.Agent).getEC2InstanceID`. This caused an issue where the intent host's agent would check in to the app server but wouldn't send its instance ID. Without an instance ID, we can't do anything to the host, so we couldn't do the host doc swap to turn it into a real host to actually run tasks, nor could we terminate it during the host termination job.
* Fix the agent logic to send the instance ID for on-demand hosts. This will also fix the handful of on-demand intent hosts that are currently unable to send an instance ID.
* Retry fetching the instance ID on every agent request for the next task in case previous …

EVG-16064: Ensure on-demand intent hosts send their instance ID

---

cloud/ec2.go
cloud/spawn.go
model/distro/distro.go
model/distro/distro_test.go
model/host/hostutil.go
model/host/hostutil_test.go
rest/data/host_create.go
units/ssh_keys_update_static.go

Jira: https://jira.mongodb.org/browse/EVG-16124
When uploading a public key from a file using the CLI, the file may contain trailing newlines because it's standard for regular files to have a newline at the end. The shell script used to add the public key to the host didn't account for this, so running the script over SSH does not work if there's a newline in the public key text. I trimmed the surrounding newlines in the public key.
I also standardized how the host gets its authorized keys file, since there's a few places where a script adds a public key to the authorized keys file (for host.create, the distro setup script, and this host modification script to add an SSH key). The precedence should be to use the distro authorized key file if explicitly set, or fall back to the default SSH …

EVG-16124: Fix SSH command to add public key to existing host and standardize authorized keys file

---

db/db_utils.go
graphql/integration_atomic_test.go
graphql/integration_test.go
model/testresult/testresult.go
rest/data/test_test.go

[EVG-15966](https://jira.mongodb.org/browse/EVG-15966)
For the /tasks/<task_id>/tests route, we pass in a TestId, which causes mongo to use the _id index (very slow) instead of the task_id / execution index -- ordering the query with TestId last doesn't fix this. Created a new function to hint at the right index to use.
Tested with the commandline that this index _does_ improve queries significantly, tested on staging and confirmed it passes existing tests.

EVG-15966 hint paginated test results queries

---

cmd/load-smoke-data/load-smoke-data.go

[EVG-15966](https://jira.mongodb.org/browse/EVG-15966)
Need index to fix e2e tests and local evergreen.
Ran evergreen-local and verified index exists:
```
MongoDB Enterprise rs0:PRIMARY> db.testresults.getIndexes()
[
{
"v" : 2,
"key" : {
"_id" : 1
},
"name" : "_id_",
"ns" : "evergreen_local.testresults"
},
{
"v" : 2,
"key" : {
"task_id" : 1,
"task_execution" : 1
},
"name" : "task_id_1_task_execution_1",
"ns" : "evergreen_local.testresults"
}
]
```

EVG-15966 add index to local evergreen

---

model/lifecycle.go
model/lifecycle_test.go
model/task_lifecycle.go
rest/data/build_test.go

[EVG-14714](https://jira.mongodb.org/browse/EVG-14714)
New function update version status so we dont have to look up build every time 
unscheduling task now updates version and build status

EVG-14714 Update version status on restart

---

model/project_parser_merge_functions.go
model/project_parser_test.go

[EVG-16154](https://jira.mongodb.org/browse/EVG-16154)
Because we were using pointers to merge build variants, the parserBVs we save to the map are all overwritten to be the last pp.BuildVariants. By not using pointers, we fix this problem and avoid running into it for this operation in the future.
Added a unit test that failed before the fix (bvNew2 didn't exist but bvNew1 existed twice).

EVG-16154 merge buildvariants without using pointers

---

graphql/resolvers.go

[EVG-16148](https://jira.mongodb.org/browse/EVG-16148)
This bit of code technically shouldn't be hit. But since it is causing nil pointer errors i've included this as a fix. I've opened EVG-16149 to look into why we are not finding volumes for some hosts.

EVG-16148 Handle nil pointer dereference for home volumes 

---

model/user/db.go
rest/route/user.go
rest/route/user_test.go

[EVG-16161](https://jira.mongodb.org/browse/EVG-16161)
Some permissions we may choose to only give to bots (for example, https://github.com/evergreen-ci/evergreen/blob/8e010917fc3774e4f32d8c2843c6d23cbed623a5/globals.go#L834) which is breaking mana's assumptions about our permissions. That being said, they don't really need to know about bots so we can just filter them out. Will also add to documentation.

EVG-16161 filter bot users out of users/permissions role

---

model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go

[EVG-16039](https://jira.mongodb.org/browse/EVG-16039)
The Activating interaction can be seen here: task group task 2 was [scheduled by the user](https://evergreen.mongodb.com/task/mongodb_mongo_v4.4_macos_stitch_support_run_tests_a17699e50a4d75d91b5788baa7eb15916341b905_21_12_24_16_20_52/0#/log/EV) but because [task group task 1](https://evergreen.mongodb.com/task/mongodb_mongo_v4.4_macos_stitch_support_install_tests_a17699e50a4d75d91b5788baa7eb15916341b905_21_12_24_16_20_52#/log/EV) had already been scheduled and run successfully a previous day, this wasn't reset and so didn't run with task group task 1.
Also handling the deactivating case (if task group task 1 is deactivated, then task group task 2 should also be deactivated). https://jira.mongodb.org/browse/BF-23865

EVG-16039 schedule/unschedule task group tasks when activating/deactivating one

---

model/patch/patch.go
model/patch_lifecycle.go
model/project_parser.go
model/project_parser_test.go

[EVG-16154](https://jira.mongodb.org/browse/EVG-16154)
Cloud was running into [an error with their PR ](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20metadata.level%3E%3D70%2050266&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=1642715100&latest=1642719600&workload_pool=standard_perf&sid=1642774620.4540347), which was suspicious because this path should only be used for CLI patches.
https://github.com/evergreen-ci/commit-queue-sandbox/pull/332 didn't create a patch until these changes were added to staging.

EVG-16154 check patch type to change where to read included files from

---

model/project_ref.go
model/project_ref_test.go
public/static/js/projects.js
rest/model/project.go
service/project.go
service/templates/projects.html

[EVG-15949](https://jira.mongodb.org/browse/EVG-15949)
Introduced a toggle on the project page when unset, we will not bother to attempt to unmarshal a project's config yaml into new config properties in order to improve performance and preserve resources.
Toggled in staging with toggle unset, confirmed no entry to project_configs DB occurred even when yaml was configured with new props.

EVG-15949 Introduce toggle to allow version control for project configs

---

model/task_lifecycle.go

[EVG-14053](https://jira.mongodb.org/browse/EVG-14053)
We sometimes hit the MongoDB error "$in needs an array" for https://github.com/evergreen-ci/evergreen/blob/e4eaf62332f77d4b25ae49023d42f0bd1cdc480f/model/task_lifecycle.go#L392. I'm having trouble replicating this state in a unit test 🤷‍♀️  but really we should only be able to get here if execution tasks is empty. This is a feasible state since this error is being logged for generated display tasks (so they may not have execution tasks yet).

EVG-14053 skip querying for empty execution tasks

---

units/generate_tasks_test.go
validator/project_validator.go
validator/project_validator_test.go

[EVG-6846](https://jira.mongodb.org/browse/EVG-6846)
Return error if task referenced in a buildvariant is also referenced in a task group in the buildvariant

EVG-6846 Return error if a task referenced in buildvariant is also referenced in taskgroup

---

db/query.go
model/project.go

[EVG-16196](https://jira.mongodb.org/browse/EVG-16196)
Setting a maxTime on the query seems like the most straightforward way to prevent a single app server ending up underwater for hours.
I set the timeout at 90 seconds since the load balancer will have certainly killed the waterfall request by then (a bit longer than one minute in keeping with Annie/John's suggestion [here](https://github.com/evergreen-ci/evergreen/pull/4961#discussion_r693194303)).
I can still load the waterfall in staging. (fwiw)

EVG-16196 set maxTime on fetching tasks for the waterfall

---

public/static/js/projects.js

[EVG-16128](https://jira.mongodb.org/browse/EVG-16128)
Warn users from copying a project with different ID and identifier that they may want to make them the same if relying on Performance. (This is likely a temporary measure, pending https://jira.mongodb.org/browse/EVG-16179, so not currently planning on extending to the new UI).

EVG-16128 warn users about immutable ID if copying perf project

---

cloud/ec2.go

[EVG-15915](https://jira.mongodb.org/browse/EVG-15915)
A user ran into an issue where a host was labeled as running when they tried to click on the trash button of an already terminating host. 
I tried stopping and then pausing a few hosts on staging with and without my changes. The ones that stuck around as running (despite actually being stopped) are ones spawned without my changes.

EVG-15915 Fix terminated spawn host is marked as running

---

config.go
operations/host_spawn.go

Jira: https://jira.mongodb.org/browse/EVG-14645
Allow users to pass whatever flags they want to the SSH binary as additional parameters. I also added a dry run flag to display the SSH command that will run without actually running the command, which is useful for debugging. `evergreen host rsync` has a similar dry run flag.
`evergreen host ssh -i <identity_file>` is now redundant since it's equivalent to `evergreen host ssh --host <host_id> -- -i <identity_file>`, but I kept it for backward compatibility.
SSH is hard to test, so I just manually tested that it still works the way it's used today and the additional arguments are forwarded as expected.

EVG-14645: forward arbitrary SSH args and add dry run flag

---

agent/command/results_xunit_parser.go
agent/command/results_xunit_test.go
config.go

[EVG-16131](https://jira.mongodb.org/browse/EVG-16131)
If a test is skipped, we don't want to upload a log file. 
Existing unit tests -- made sure that the 12 of 12 files is the correct number

EVG-16131 attach.xunit_results shouldn't upload logs if a test is skipped

---

scripts/agent.yml

[EVG-16230](https://jira.mongodb.org/browse/EVG-16230)
This adds more files to the s3copy command so that it can detect problems with looping over files. It also contains a duplicate so that it has to noop. Merging it will make it possible to test [5306](https://github.com/evergreen-ci/evergreen/pull/5306) with a patch build
existing test

EVG-16230 Improve smoke test for s3Copy

---

graphql/generated.go
graphql/schema.graphql

[EVG-16081](https://jira.mongodb.org/browse/EVG-16081)
UseRepoSettings doesn't exist as a field anymore, and also whether or not the project uses repo is handled by a different resolver (AttachToRepo / DetachFromRepo). Also removing Hidden as this is a backend internal field.

EVG-16081 remove UseRepoSettings from project input

---

model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle_test.go
model/task/task.go

Jira: https://jira.mongodb.org/browse/EVG-16168
Add a field to distinguish a task running in a container from a task running in a host. This field is currently set to host mode for any newly-created execution task, although it should eventually be set based on the YAML config.
Updated unit tests to verify that it's set when execution tasks are first created.

EVG-16168: add field for task execution platform

---

model/lifecycle_test.go
model/task_lifecycle.go
rest/data/task.go

[EVG-15724](https://jira.mongodb.org/browse/EVG-15724)
Display tasks can't be restarted if they're currently in progress, but that isn't obvious to users who are using rest routes. Display tasks can be marked to be restarted when the whole thing is finished, so I think that's the right thing to do here.
Unit test.

EVG-15724 handle resetting unfinished display tasks from routes

---

model/generate.go
model/project_matrix_test.go
model/project_parser.go
model/project_parser_db.go
model/project_parser_test.go
model/project_test.go
operations/validate.go
self-tests.yml
util/yaml.go
util/yaml_test.go
validator/project_validator.go
validator/project_validator_test.go

[EVG-15935](https://jira.mongodb.org/browse/EVG-15935)
Before, we passed the project yaml directly to the API server to validate, so CheckYamlStrict worked. Now however, we LoadProjectInto locally in order to capture any included files, so by the time we get to CheckYamlStrict, we have a broken yaml file.
Tested locally with a broken file (using --quiet and without).
```
evergreen (EVG-15935) $ egl validate self-tests.yml
Banner: This is an important notification
WARNING: error unmarshalling strictly: load project error(s): yaml: unmarshal errors:
line 531: mapping key "commands" already defined at line 529
<continues on to validate the file>
```
```
evergreen (EVG-15935) $ egl validate self-tests.yml -q
Banner: This is an important notification
self-tests.yml is valid
```
_Alternatively_ …

EVG-15935 fix unmarshal yaml strict for validator

---

cloud/cloud_status.go
cloud/ec2_fleet.go
service/api_task.go
service/api_task_test.go
units/host_termination.go

Jira: https://jira.mongodb.org/browse/EVG-15936
I was originally going to make it so that hosts that are already marked "terminated" in the DB could be terminated again for intent hosts that are marked terminated before their real hosts come. However, rather than change assumptions around the terminated host state, it seems like it's easier to continue assuming that hosts that are terminated in the DB have also been terminated in the cloud. To maintain the termination assumption, I changed the behavior of a host that checks in after the intent host is already terminated to do the host doc swap and mark the real host as decommissioned, so it actually gets terminated in the cloud.
* Treat terminated intent hosts that are actually alive in the cloud as decommissioned real hosts.
* Log if a …

EVG-15936: improve host termination for intent hosts

---

agent/agent_command_test.go
agent/command/s3_copy.go
agent/command/s3_copy_test.go
agent/internal/client/host_methods.go
agent/internal/client/interface.go
agent/internal/client/mock.go
agent/internal/client/pod_methods.go
config.go
model/push.go
scripts/agent.yml
self-tests.yml
service/api.go
service/api_plugin_s3copy.go

[EVG-15836](https://jira.mongodb.org/browse/EVG-15836)
This was merged to main before because it broke the smoke test. After testing, we realized that the source of that break was the added lines to the smoke test. [EVG-16241](uhttps://jira.mongodb.org/browse/EVG-16241) was created to address that. This PR merges what was merged before (the first commit), plus a removal of the additional lines to agent.yml, and a removal of a test in self-test.yml that shouldn't have been committed. 
Tested with patches on staging. 
[smoke test patch](https://spruce-staging.corp.mongodb.com/version/61fab1cfb237367ee0cbcfb6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[a patch with a fake key that should fail](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu1604_copy_should_succeed_patch_1e78e1f484 …

EVG-15836 Fix s3_copy

---

repotracker/repotracker_test.go
rest/route/test.go
service/api.go
validator/project_validator.go
validator/project_validator_test.go

[EVG-7310](https://jira.mongodb.org/browse/EVG-7310)
Kind of snuck this into the epic, but right now we print projectId for most validation; this isn't super useful because in many cases there isn't a project Identifier (since people use validation from the CLI), so we just print `project ''` which is pretty useless (also in non-CLI cases we typically error with the project id anyway). 
I did add printing the project ID for the settings that rely on it (i.e. task sync).

EVG-7310 remove projectId from validation errors

---

model/task/db.go
model/task/task.go
model/task/task_test.go
scheduler/host_allocator.go
scheduler/scheduler.go
scheduler/task_finder.go
scheduler/task_finder_test.go
units/scheduler_alias.go

Jira: https://jira.mongodb.org/browse/EVG-16170
* Check for host execution platform in distro scheduler queries. I'm going to build the relevant indexes in staging/prod after this is approved but before it's merged.
* Rename some task find functions to clarify that they're only for host tasks.
* Add/fix some documentation in the scheduler package.

EVG-16170: only consider host tasks for the distro scheduler

---

globals.go
graphql/resolvers.go
graphql/util.go
model/audit.go
model/build/db.go
model/host/db.go
model/lifecycle.go
model/task/db.go
model/task/task.go
scheduler/task_finder_test.go
service/stats.go
trigger/build.go
trigger/task.go

[EVG-16175](https://jira.mongodb.org/browse/EVG-16175)
I added a TaskContainerAllocated status to differentiate between container tasks that were ready to run but waiting for a container, and that are ready to run with the container allocated. This required several downstream changes, which will be made in parts. 
https://spruce.mongodb.com/version/61fbe1f02fbabe23af018894/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

EVG-16175: (partial) addition of new task status and concomitant changes for trigger, scheduler, and graphql

---

graphql/resolvers.go
model/testresult/testresult.go

[EVG-16245](https://jira.mongodb.org/browse/EVG-16245)
Sorting by TaskID mysteriously broke the /tests routes for display tasks, since we rely on pagination of the ID (this is more performant than using the page skip). Not looking to refactor this too much since it's moving towards being legacy.

EVG-16245 sort by taskIDkey only for UI test routes

---

model/project_parser.go

[EVG-16292](https://jira.mongodb.org/browse/EVG-16929)
it seems that every time we try to go into the task scheduler for a specific patch it tries to parse a nonexistent yml in sandbox and spams the error. Just getting rid of it should be fine
nothing breaks

EVG-16292 Remove critical logging for LoadProjectInfo

---

environment.go
model/event/event_finder.go
model/event/event_test.go
units/crons.go
units/crons_event_test.go
units/crons_remote_minute.go
units/event_notifier.go

Jira:
https://jira.mongodb.org/browse/EVG-16251
https://jira.mongodb.org/browse/EVG-16260
This is supposed to make the more efficient by reducing the duplicate events processed during times when there are a lot of unprocessed events, while also throttling the max number of events that can be simultaneously processed in parallel to avoid overloading the DB.
This change is risky, so I'm going to do the deploy after it's merged. If this doesn't work (e.g. the parallel processing limit is too high/low), the only work to rollback should be reverting this change and marking some jobs in the queue group complete.
* Process individual events instead of batches of events in the event notifier.
* It now ignores the event processing batch size. This batch size can be removed from the admin settings …

EVG-16251, EVG-16260: reduce duplicate event processing and limit the max parallel events processed

---

model/project_configs.go
model/project_configs_test.go
model/project_ref.go
model/project_ref_test.go
operations/model.go

[EVG-16243](https://jira.mongodb.org/browse/EVG-16243)
Commit queue params and several toggles related to github project configurations have been removed from the newly exposed set of configurations, since enabling these properties via version control may lead to unexpected behavior when restarting old tasks that have their config yaml version conflicting with what is set on the project page.  Two toggles have been kept: perf enabled and deactivate previous, since it looks as though keeping these under version control would not be problematic.
Modified existing unit tests.

EVG-16243 Remove CQ and several toggles from project configs

---

cloud/ec2.go
graphql/util.go
units/spawnhost_modify.go
units/spawnhost_start.go
units/spawnhost_stop.go
units/spawnhost_terminate.go

Jira: https://jira.mongodb.org/browse/EVG-16066
The unexpirable spawn host ended up in an unusual state because the user attempted to terminate and stop the host at the same time. The host ended up being terminated in AWS but marked as running in the DB. I changed the jobs that allow users to manually modify spawn hosts so that only one can happen at a time. For example, if the user tries to terminate the host in the UI, any attempt to stop/start the host from the UI will error while it's in progress.
* Use scopes to ensure host start/stop/terminate requests from the user do not cause host concurrency problems when modifying the host.
* User-initiated spawn host termination now happens asynchronously in a job rather than synchronously with the UI request.
* Clean up a bunch of copy-pasted …

EVG-16066: prevent concurrent user-initiated spawn host modifications

---

agent/command/s3_copy.go
config.go

[EVG-16315](https://jira.mongodb.org/browse/EVG-16315)
Because we logged a push event before checking if the build variant will run, in the case where a build variant was skipped, by the time it got to the build variant that was truly trying to push the file, it would no-op, because the db thought that the task already pushed. 
None right now, but will coordinate with the right people to get this tested once it's deployed.

EVG-16315 Fix build variants logging as pushing when being skipped

---

units/data_cleanup_testresults.go

[EVG-16157](https://jira.mongodb.org/browse/EVG-16157)
This will reduce the size of the collection, and will make it easier to delete once we migrate to cedar.
I did not

EVG-16157: 6 months TTL on test_results

---

units/data_cleanup_testresults.go

Reverts evergreen-ci/evergreen#5320 due to poor naming

Revert "EVG-16157: 6 months TTL on test_results"

---

units/spawnhost_modify.go
units/spawnhost_start.go
units/spawnhost_stop.go

Jira: https://jira.mongodb.org/browse/EVG-16066
Remove unneeded fallback fields for spawn host modification jobs. They should not be necessary since the actual change (#5382) is now deployed.
N/A

EVG-16066: remove spawn host modification fallback

---

cmd/evergreen/evergreen.go
config.go
operations/model.go
operations/patch_util.go
operations/update.go

[EVG-6496](https://jira.mongodb.org/browse/EVG-6496)
New property has been added in client settings to optionally automatically update the evergreen CLI before any command is run.
Built CLI locally with new client settings to auto update and tested manually.

EVG-6496 Auto update CLI if it is set in client settings before each command

---

globals.go
graphql/resolvers.go
graphql/util.go
model/task/task.go

[EVG-16095](https://jira.mongodb.org/browse/EVG-16095)
If a user includes "all" in a task filter they want all of the matching task statuses so we should ignore that field in the `$match` stage of the pipeline since we don't want to filter anything out.

EVG-16095 Ignore all filter for statuses

---

units/event_notifier.go

Jira: https://jira.mongodb.org/browse/EVG-16260
* Remove the fallback check used for backward compatibility with the old event notifier.
* Add an error when the event is not found.
N/A

EVG-16260: remove event notifier fallback

---

operations/fetch.go
service/task.go
service/version.go

[EVG-14348](https://jira.mongodb.org/browse/EVG-14348)
We were correctly fetching user changes for hosts created from patches but not from pull requests because the requester check was too limited. Also fixed this for some non-fetch occurences.
Created a host before and after changes and verified that the host before didn't have any user changes, and the host after did.

EVG-14348 case correctly on patch requesters for fetch

---

config_alerts_notify.go
config_test.go
model/event/event_test.go
model/task_lifecycle_test.go
rest/model/admin.go
service/templates/admin.html
units/crons_event_test.go
units/spawnhost_expiration_warning_test.go
units/volume_expiration_warning_test.go

Jira: https://jira.mongodb.org/browse/EVG-16331
Since the event notifier change in #5377 seems to have succeeded, the event notifier no longer batch processes events, so the flag is unnecessary.
Updated tests that depended on default batch size.

EVG-16331: remove event notifier batch size setting

---

model/project_parser_db.go
service/api.go

[EVG-16358](https://jira.mongodb.org/browse/EVG-16358)
Users should be able to define parameter descriptions without requiring a default, in which case we shouldn't overwrite existing ones.
No existing test to update here.

EVG-16358 prevent un-specified parameters from overwriting expansions

---

gqlgen.yml
graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/githubProjectConflicts/data.json
graphql/tests/githubProjectConflicts/queries/conflicts.graphql
graphql/tests/githubProjectConflicts/queries/no-conflicts.graphql
graphql/tests/githubProjectConflicts/results.json
model/project_ref.go
rest/data/project.go
service/project.go

[EVG-16194](https://jira.mongodb.org/browse/EVG-16194)
Added backend function and resolver to get github conflicts for a project. Used this new function in some existing backend functions. 
Also fixed a bug where we query the ProjectRef collection for branch directly (whereas this can be set from the repo as well).
Added unit tests and ensuring existing tests pass.

EVG-16194 add resolver for conflicting refs

---

units/data_cleanup_test_logs.go

Since we changed the test results TTL to 6 months, we should also change the test logs TTL.

EVG-16157 Change test logs TTL to 6 months

---

makefile
self-tests.yml

[EVG-16253](https://jira.mongodb.org/browse/EVG-16253)
* Change the db versions for each variant to 4.2.18. Because mongo doesn't package a precompiled tarball for 4.2 on Ubuntu16.04 ARM I changed that variant to Ubuntu 18.04 ARM. There's also no tarball for Arch. We could experiment with using one of the tarballs for another Linux distro but (as Brian noted on the ticket) there's no compelling reason to run race-detector on Arch so it will run on Ubuntu. It made sense to me to run on Ubuntu 16.04 because the app servers run on it and we're running the non-race tests on it already.
* Use the current distro names for ubuntu1604 (small instead of test and large instead of build). It means the same thing at the end of the day, but why not use the distros' proper names?
* Set the fCV of the …

EVG-16253 upgrade mongodb version for tests

---

model/lifecycle.go

[EVG-16318](https://jira.mongodb.org/browse/EVG-16318)
activatedBy was empty at task creation unless it was a stepback task 
now it will be populated 
started a task on staging 
https://evergreen-staging.corp.mongodb.com/rest/v2/tasks/sandbox_ubuntu1604_bynntask_patch_82cbc667ad4bc2f073b2e43e138b039f792cdc6b_620ab1cdb2373605bcc860e1_22_02_14_19_47_30?execution=0

EVG-16318 Update task activatedBy at task creation

---

service/rest_version.go

[EVG-16155](https://jira.mongodb.org/browse/EVG-16155)
Generated variants might not exist yet for the most recent version, so erroring if they aren't present isn't correct behavior. Instead we should just let the query handle it.
Not sure there's a great way to get the staging lock while slack is down but I will test on staging before merging.

EVG-16155 prevent last-green from erroring for nonexistent variants

---

cloud/spawn.go
cloud/spawn_test.go
model/host/host.go

[EVG-15335](https://jira.mongodb.org/browse/EVG-15335)
Previous behavior: 
does not allow hosts to be extended 30 past their creation dates
can only extend up to 2 weeks from the current time 
Now: 
only checks that you can't extend the host beyond 30 days after creation

EVG-15335 Update host extension error messages

---

model/distro/distro.go

[EVG-13527](https://jira.mongodb.org/browse/EVG-13527)
Removed two unused distro functions.
Confirmed test still passing.

EVG-13527 Remove unused distro code

---

model/task/db.go
model/task/task.go
model/task/task_test.go

[EVG-15934](https://jira.mongodb.org/browse/EVG-15934)
add hint to unschedule underwater tasks because using the wrong index was slowing it down 
ran the query on db 
unit tests

EVG-15934 Add hint to UnscheduleStaleUnderwaterTasks

---

util/strings.go

[EVG-16418](https://jira.mongodb.org/browse/EVG-16418)
Slashes in version and task names break a lot of things.
validated on staging https://spruce-staging.corp.mongodb.com/version/620d357597b1d34aca2b71d1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

EVG-16418 replaces /s in git tags

---

rest/data/project_settings.go
rest/data/project_settings_test.go

[EVG-16338](https://jira.mongodb.org/browse/EVG-16338)
The UI handles this but we're adding to the backend in case things race and just to be careful. Enabling a project or a toggle, or changing owner/repo/branch are things that could affect this.
Added a test.

EVG-16338 error saving a project if github conflicts exist

---

graphql/resolvers.go

[EVG-16415](https://jira.mongodb.org/browse/EVG-16415)
I made the dumb mistake and used project identifier to find tasks instead of the id and wrongfully blamed matrices. Crisis averted.

EVG-16415 Use project id instead of identifier for history queries

---

graphql/tests/saveSubscription/results.json
model/event/subscriptions.go
model/event/subscriptions_test.go
rest/data/subscription.go
rest/model/subscriptions.go
rest/model/subscriptions_test.go
rest/route/subscription_test.go

[EVG-16397](https://jira.mongodb.org/browse/EVG-16397)
Add a Filter subdocument to subscription documents. 
My objective is outlined in the ticket. I think this subdocument can be supported by a new, large, compound index. It has an additional advantage that we can just pass regexes to the db instead of fetching everything for the regular selectors and filtering on regexes in the application.
I plan to do this in four stages 
1. This PR duplicates the selectors in a subdocument I think could be supported by an index.
2. I will do a migration to do the same for existing subscription documents.
3. I will open a second PR to change the subscriptions query to use the new field.
4. I will open a third PR to stop saving the selectors array.
I don't plan to remove the selectors array from …

EVG-16397 set new filter field

---

service/waterfall.go
service/waterfall_test.go

[EVG-16196](https://jira.mongodb.org/browse/EVG-16196)
If a user specifies a non-existent bv filter on the legacy waterfall we currently loop on fetching all the versions, builds, and tasks for that project until the dawn of time. This is especially an issue when users iterate on the bv filter until they get one they're satisfied with.
The new UI's solution for this was to [introduce a limit for how many versions we load for an individual waterfall request](https://github.com/evergreen-ci/evergreen/blob/f3df1ec1805054beb3d457e4ff82df8ea6e30bf8/graphql/resolvers.go#L3635-L3642). I adapted this solution for the legacy UI. 
Added unit tests. 
Deployed to staging and verified changes made us not load all the way back to the beginning of time.

EVG-16196 don't let the waterfall query go back to the beginning of time

---

graphql/util.go
model/patch_lifecycle.go
model/task/db.go
model/task_lifecycle.go
model/task_lifecycle_test.go
service/api_task.go
service/api_task_test.go
service/build.go
service/version.go

[EVG-14450](https://jira.mongodb.org/browse/EVG-14450)
* Added stepback to the commit queue: this is described more in the ticket but if previous versions on the queue haven't run yet, we don't know if the failure is due to that commit or not, so dequeuing the current version may be the wrong thing to do, and then the user has to go through the process again.
* Lightly refactored some code to have less duplication and to possibly fix errors where we aren't restarting versions because we dequeue the item before looking for which versions to restart.
Added a test to cover all the scenarios I can think of, will also try to test at least one or two of them on staging.

EVG-14450 add stepback to the commit queue

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/defaultSectionToRepo/data.json
graphql/tests/defaultSectionToRepo/queries/defaultSectionToRepo.graphql
graphql/tests/defaultSectionToRepo/queries/noAdmin.graphql
graphql/tests/defaultSectionToRepo/queries/unattachedProject.graphql
graphql/tests/defaultSectionToRepo/results.json

[EVG-16435](https://jira.mongodb.org/browse/EVG-16435)
- Add GraphQL mutation for calling `DefaultSectionToRepo`
- Added unit tests
- Tested manually in GraphQL playground

EVG-16435: Add DefaultSectionToRepo mutation

---

model/lifecycle_test.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go
service/api_task.go

Jira: https://jira.mongodb.org/browse/EVG-16239
Rename some dispatch/undispatch task functions that only apply to tasks running in hosts. Instead of "undispatched", tasks that are waiting to run on a container use the "container-unallocated" status. Tasks that are sent to a container to run will still enter the "dispatched" state, but will require slightly different logic.
N/A

EVG-16239: rename host task dispatch functions

---

graphql/util.go

[EVG-14828](https://jira.mongodb.org/browse/EVG-14828)
This value should have been in milliseconds as well

EVG-14828 Use milliseconds for total time

---

public/static/app/waterfall/waterfall.jsx
public/static/dist/js/waterfall/waterfall.js

[EVG-16196](https://jira.mongodb.org/browse/EVG-16196)
I noticed that as I was typing a bv filter on the legacy waterfall almost every keystroke made another request for waterfall data (and the results of all but the last are discarded). 
It makes more sense to me to only request the data when the user is done typing. The debounce function is supposed to do this, but 100ms is too short. This PR extends it to a second.
When I deployed this to staging the wait after I finished typing seemed appropriate.

EVG-16196 longer debounce

---

units/host_termination.go
units/host_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-16291
If the cloud host status check fails because the context errors, the host should not be marked as terminated in the DB. The job will be re-enqueued to retry terminating the host later.
There's no tests due to the difficulty of testing context cancellation behavior at a specific line in the job, but it's not difficult to verify correctness just by inspection. Testing with the mock provider is difficult since it ignores the context and doesn't make network requests, but using a real cloud provider would also be difficult to simulate.

EVG-16291: check for context errors during host status check

---

model/host/host.go
model/host/host_test.go

Jira: https://jira.mongodb.org/browse/EVG-16448
Host termination does two updates - one to set the status, and another to set the termination time and unset the volumes. Since it's not atomic, it's possible for the host to be terminated in the DB, but no termination time is set yet. This temporary mismatch can cause [this](https://github.com/evergreen-ci/evergreen/blob/2406d863f1422c46b46ebd4abd2e9f19a12cad74/service/api_task.go#L500-L506) to log spuriously when the agent requests the next task.
* Atomically update the host to terminated using a single update.
* Refactor `SetStatus` to handle setting additional fields in the update.
Added unit tests for `SetStatusAndFields`.

EVG-16448: atomically update host during termination

---

model/project_vars.go
service/api.go

[EVG-16447](https://jira.mongodb.org/browse/EVG-16447)
allow repotracker requesters to access admin only vars
took away minna's admin role and verified that her patches cant access admin vars but commits can 
https://evergreen-staging.corp.mongodb.com/task/sandbox_ubuntu1604_bynntask_14619adff2ad781b915772f1a1a5107e9f397ff9_22_03_03_17_02_44

EVG-16447 Update admin only variable access to mainline commits

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/projectSettings/data.json
graphql/tests/projectSettings/queries/project-settings-project.graphql
graphql/tests/projectSettings/results.json
graphql/tests/repoSettings/data.json
graphql/tests/repoSettings/queries/repo-settings-project.graphql
graphql/tests/repoSettings/results.json
rest/data/project_settings.go
rest/model/project.go
rest/route/project_test.go

[EVG-16410](https://jira.mongodb.org/browse/EVG-16410)
Also changed TaskSpecifierInput items to be nullable, because on the legacy UI it's either patchAlias OR taskRegex and variantRegex, but if that seems wrong I'll change it back!

EVG-16410 modify PatchTriggerAliasInput to accurately reflect the input

---

graphql/generated.go
graphql/schema.graphql

Relates to UI ticket [EVG-15086](https://jira.mongodb.org/browse/EVG-15086)
- Make `gitClone` nullable to support projects that default to repo
- Disallow null entry in `setupCommands` array
- Tested manually

EVG-15086: Update WorkstationConfigInput

---

config.go
operations/http.go
operations/patch_module.go

[EVG-1822](https://jira.mongodb.org/browse/EVG-1822)
set-module now defaults to the user's latest patch when not given a patch id
added evergreen as module patch to spruce patch
https://spruce.mongodb.com/version/6229a92261837d493fdce229/changes?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

EVG-1822 Update set-module command to not require patch id

---

graphql/tests/patch/data.json
graphql/tests/patch/results.json
model/task/db.go
model/task/task_test.go

[EVG-16070](https://jira.mongodb.org/browse/EVG-16070)
- Only return activated tasks for a patch's total task count; this mimics the query used to calculate the numerator task count [here](https://github.com/evergreen-ci/evergreen/blob/825c4a9103cfd1fb1fa1cf7465185c66f3cdc187/model/task/task.go#L3347-L3350)
- Tested manually in staging: [this patch](https://spruce-staging.corp.mongodb.com/version/622babb2b23736672ef563e7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) has one generated task that I marked as "activated: false"
- With changes, the page shows 55/55 (correct)
- Without changes it shows 55/56 (i.e. incorrectly calculates the count for displayed tasks)
- Update unit tests that use query

EVG-16070: Fix task count

---

graphql/tests/saveSubscription/results.json
model/event/subscriptions.go
model/event/subscriptions_test.go
rest/data/subscription_test.go
rest/model/subscriptions.go
rest/model/subscriptions_test.go
rest/route/subscription_test.go
service/project.go

[EVG-16397](https://jira.mongodb.org/browse/EVG-16397)
It was overly ambitious to think the regex selector matching could be pushed to the db. I got confused by the direction: we aren't matching a regex to a string in the document. Rather, we're matching a string to a regex in the document.
It's possible we can do something down the line with [$regexFind](https://docs.mongodb.com/manual/reference/operator/aggregation/regexFind/) but it's a 4.2 feature.
My plan is to 
1. deploy this
2. run `db.subscriptions.updateMany({}, {$unset: {filter:""}}` (maybe starting with a few to make sure I'm not dropping the db) to clear all the filter fields
3. rerun the migration script with the lines to set the regex field removed
None.

EVG-16397 remove regex selectors from filter

---

graphql/generated.go
graphql/schema.graphql

Partially undo change introduced in #5483
- PatchTriggerAlias is used outside of project settings, and these components do not use status or parentAsModule. They should remain nullable.
- Tested manually

EVG-15085: Fix PatchTriggerAlias type

---

cmd/sign-executable/go.mod
cmd/sign-executable/go.sum
cmd/sign-executable/sign-executable.go
makefile
self-tests.yml

[EVG-12802](https://jira.mongodb.org/browse/EVG-12802)
Add a go script to call the notary client to sign the macOS clients. Developers at their desks can still run `make dist` without signing because the makefile only signs the executables when the `SIGN_MACOS` variable is set in the environment.
I really wanted to include the notary client as a go module in the signing script, but it lives in a private org and its owner wasn't comfortable moving it somewhere public. Instead the script downloads the appropriate release from s3 and cmd.Exec's it.
I added the variables to staging, built a dist, deployed it to staging, and downloaded the CLI. My laptop was able to run the CLI.

EVG-12802 notarize cli for macOS

---

model/patch/cli_intent.go
model/patch/db.go
model/patch/github.go
model/patch/intent.go
model/patch/trigger_intent.go
model/patch_lifecycle.go
model/task/db.go
operations/http.go
operations/patch.go
operations/patch_util.go
service/api_patch.go
units/patch_intent.go
units/patch_intent_test.go

[EVG-15171](https://jira.mongodb.org/browse/EVG-15171)
Introduce repeat-failed, a flag on the CLI patch command that will repeat only the failed tasks and build variants from the most recent patch (if any).
Tested in staging on sandbox project when the most recent patch was failed, and saw the previously failed tasks were automatically selected.

EVG-15171 Implement restart-failed

---

model/task_lifecycle.go
model/task_lifecycle_test.go

[EVG-16411](https://jira.mongodb.org/browse/EVG-16411)
We don't consider dispatched/started tasks when we calculate task status, which means that we keep the top sorted task status (which could be started) but we still update finishTime since we don't have any more new tasks to dispatch. Instead, we should consider dispatchable + running tasks.
Modified test -- failed without changes, passes with changes.

EVG-16411 consider started exec tasks when updating disp task status

---

model/event/subscriptions.go
repotracker/repotracker.go
rest/data/subscription.go
service/project.go

[EVG-16397](https://jira.mongodb.org/browse/EVG-16397)
I didn't do due diligence in #5431 and I missed several places where the filter field wasn't being set 😳 . Hopefully this PR catches them all.
I toyed with the idea of validating the filter field matches the selectors in [Upsert](https://github.com/evergreen-ci/evergreen/blob/1adeffd04b411b798ec9cb29c8c8b2b68cf8df0b/model/event/subscriptions.go#L289), but I'm not sure we want to include validation logic in a db operation. Once this merges and I do the migration I can check manually in prod after a bit to make sure there aren't any new ones that don't have it set. It doesn't protect us from future developers adding subscriptions that don't set filter, but I'm not sure of a good way to do that.
None...

EVG-16397 set filter where it's not set

---

service/api_task.go

Jira: https://jira.mongodb.org/browse/EVG-16494
There's two different issues that I've found as part of the investigation:
* Some agents stay alive for much longer than expected (on the order of days), well after the cloud provider has said the host is shutting down/terminated. This seems like an issue on the cloud provider side and not something we can do anything about, so it's not a bug on our end. At least we aren't being billed for these instances since they're in the terminated state.
* A single intent host somehow started two cloud hosts. We got one instance ID back from the API request (`RunInstances`), which we recorded as the cloud host created from the intent host, but a second doppelganger cloud host also started an agent. Since they share the same intent host ID, they're …

EVG-16494: reduce logging level for agents on already-terminated hosts

---

model/container_task_queue.go
model/container_task_queue_test.go
model/task/db.go
model/task/db_test.go
units/host_termination.go

Jira: https://jira.mongodb.org/browse/EVG-16166
* Add queue wrapper to get the next container task to be allocated a container.
* Add query to get tasks that need allocation.
* Check project ref to ensure the task is allowed to run. I mostly duplicated [the host scheduler's existing checks](https://github.com/evergreen-ci/evergreen/blob/1adeffd04b411b798ec9cb29c8c8b2b68cf8df0b/scheduler/task_finder.go#L68-L147).

EVG-16166: implement container task queue

---

self-tests.yml

[EVG-16589](https://jira.mongodb.org/browse/EVG-16589)
The signing service is being flaky. Let's stop signing until we can figure out how to mitigate the fallout from signing failing.

EVG-16589 disable signing

---

rest/route/project.go

[EVG-6963 ](https://jira.mongodb.org/browse/EVG-6963)
When there is a race, users can see "duplicate key error collection: amboy.evg.service.jobs". This checks if it's a duplicate error and if it is, returns a more descriptive error. 
I was not able to duplicate this error.

EVG-6963 return a client error instead of a database duplicate key error

---

model/version_db.go
model/version_db_test.go
trigger/task.go

[EVG-16398](https://jira.mongodb.org/browse/EVG-16398)
We fetch the version for every task event when all we really need is the author id. I don't think this will make a huge difference. Maybe it could matter if lots of tasks fail at the same time... Like a mongodb-mongo-* version could be 1.5MB these days.
```
mci:SECONDARY> Object.bsonsize(db.versions.findOne({_id:"mongodb_mongo_v5.2_bfdbbb2a3ce0bfa598ea89a5d8e80a9d683e3931"}))
1425573
```

EVG-16398 just get authorID

---

rest/data/project_settings.go
rest/data/project_settings_test.go
rest/model/project_event.go

[EVG-16452](https://jira.mongodb.org/browse/EVG-16452)
Wasn't considering before that the UI would pass values in as PrivateVarsList. Also added a clause to ensure that we don't overwrite the value in the case that the value is purposefully deleted / re-added.
Tried to break manually and also modified unit test (didn't work without my changes).

EVG-16452 ensure private variables aren't overridden

---

units/patch_intent.go
units/patch_intent_test.go
units/schedule_patch.go

[EVG-16496](https://jira.mongodb.org/browse/EVG-16496)
It looks to me like the parent's changes aren't being applied to spruce because the alias doesn't specify the module they should be applied as. I think we want it to look like this:
This was broken, though, for the case of finalizing the patch from the CLI. When we went looking for the parent patch [here](https://github.com/evergreen-ci/evergreen/blob/f64f66e3635f1711d483ad65dac155c386281032/units/patch_intent.go#L857) it wasn't there because [it only got inserted after](https://github.com/evergreen-ci/evergreen/blob/f64f66e3635f1711d483ad65dac155c386281032/units/patch_intent.go#L359-L365). This PR switches the order of when the child intents get processed and when the parent patch is inserted. This necessitated updating the parent …

EVG-16496 reorder patch insertion and trigger processing

---

cloud/ec2.go
cloud/ec2_fleet.go
public/static/js/distros.js
service/templates/distros.html

[EVG-16159](https://jira.mongodb.org/browse/EVG-16159)
Add two options to distros using Fleet: 
1. use the capacity-optimized [allocation strategy](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-fleet-allocation-strategy.html). I'd like to experiment with this option for distros that are getting interrupted a bunch to see if it would be a cheaper alternative to going to on-demand. For example, I spawned three ubuntu1604-small hosts 1) on-demand 2) spot with the regular (lowest-cost) allocation strategy and 3) spot with capacity-optimized. The on-demand host cost $.17/hr, the regular spot cost $0.073/hr and the capacity-optimized was $0.0816/hr. It's not a huge spread with such a small instance (c5.xlarge), but with larger instance types it could net a bigger difference (like a …

EVG-16159 add Fleet options

---

cmd/generate-lint/generate-lint.go

Jira: https://jira.mongodb.org/browse/EVG-16577
Don't use a single-host task group for patches unless there's only 1 task. The single-host task group behavior is undesirable for patches containing multiple packages to lint, since it prevents other packages from being linted if any lint task fails.
N/A

EVG-16577: do not limit max hosts for generate-lint

---

agent/agent.go
agent/command/assume_ec2_role.go
agent/command/assume_ec2_role_test.go
agent/command/expansion_write.go
agent/command/registry.go
agent/internal/task_config.go
agent/task.go
apimodels/agent_models.go
config.go
service/api_status.go

[EVG-16052](https://jira.mongodb.org/browse/EVG-16052)
added project command that calls assume role given ARN and returns credentials as expansions
very basic unit test
https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu1604_bynntask_patch_33f13782b26be2bd33a48d378fb2293db7316034_6234f34bb237367d9ac27d7c_22_03_18_21_02_10/logs?execution=0
testing secrets manager

EVG-16052 Add project command for assume role

---

mock/environment.go
model/container_task_queue.go
model/container_task_queue_test.go
model/pod/db.go
model/pod/db_test.go
units/crons.go
units/crons_remote_fifteen_second.go
units/crons_remote_minute.go
units/pod_allocator.go
units/pod_allocator_test.go

Jira: https://jira.mongodb.org/browse/EVG-16231
* Add some helper methods to container task queue.
* Populate pod allocator jobs in remote queue group from container task queue.
* Add service flag for disabling pod allocation.
* Respect max parallel pod request limit in cron populator and in the pod allocator job itself. 
* I noticed an oddity where the mock.Environment uses the mock DB sessions but allows the usage of a real MongoDB client, so I just switched it to use the MongoDB client session.
Added unit tests. Also added an integration test between the container task queue, cron populator, and pod allocation.

EVG-16231: populate the pod allocator jobs

---

model/patch/patch.go
model/patch_lifecycle.go
rest/data/commit_queue_test.go
rest/model/patch.go
trigger/payloads_test.go

[EVG-16350](https://jira.mongodb.org/browse/EVG-16350)
Add MorgedFrom field so that when you enqueue patch from cli or ui, it will contain the patch id of the original patch it was based off
unit test
tested on spruce 
https://evergreen-staging.corp.mongodb.com/rest/v2/patches/623b949e97b1d310aeb0b06d
on cli 
https://evergreen-staging.corp.mongodb.com/rest/v2/patches/623cbaa19dbe3216e5c60c76

EVG-16350 Add MergedFrom to commit queue merge patches

---

graphql/generated.go
graphql/schema.graphql
model/project_ref.go
rest/model/project.go

[EVG-16605](https://jira.mongodb.org/browse/EVG-16605)
- Expose `VersionControlEnabled` and allow it to be saved
- Note that I assumed that projects can default to repo values for this setting, i.e. `VersionControlEnabled` can be null. Let me know if this is not the case!
- Tested manually in GraphQL playground

EVG-16605: Expose VersionControlEnabled via GraphQL

---

rest/data/project_settings_test.go
rest/model/project.go

[EVG-16541](https://jira.mongodb.org/browse/EVG-16541)
Allow empty list for workstation commands instead of setting back to nil.
New unit test which failed without changes.

EVG-16541 allow empty list for workstation commands

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/task/data.json
graphql/tests/task/queries/mainlineCommits-baseTask.graphql
graphql/tests/task/results.json
graphql/tests/version/data.json
graphql/tests/version/queries/previousVersion.graphql
graphql/tests/version/results.json
model/task/db.go
model/task/task.go
model/task/task_test.go
model/version_db.go

[EVG-16574](https://jira.mongodb.org/browse/EVG-16574)
The base task field will now return the previously run commits status for a particular task for mainline commits
On staging and locally and with tests

EVG-16574 Return Previous commit status for base commits on mainline Commits

---

rest/route/service.go

[EVG-16401](https://jira.mongodb.org/browse/EVG-16401)
This removes the createProject middleware which is what makes user require superUser access to use the copyProject route. We don't want that, we want anyone with admin access to be able to copy a project. 
none

EVG-16401 Lower permission requirements for copy projects API

---

rest/data/project_settings.go
rest/model/project.go

[EVG-16636](https://jira.mongodb.org/browse/EVG-16636)
- Validate periodic build definition (notably add ID if one is not provided)
- Fix bug where periodic builds were not accurately constructed in BuildFromService and subsequently not included in GraphQL responses
- Tested manually

EVG-16636: Fix periodic builds

---

graphql/resolvers.go
mock/environment.go
model/container_task_queue.go
model/event/pod.go
model/event/pod_test.go
model/event/task_event.go
model/event/task_event_test.go
model/pod/db.go
model/pod/dispatcher/db.go
model/pod/dispatcher/dispatcher.go
model/pod/dispatcher/dispatcher_test.go
model/pod/pod.go
model/pod/pod_test.go
model/project_ref.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
service/api_task.go
service/project.go
testutil/config.go

Jira: https://jira.mongodb.org/browse/EVG-16233
* Add method to dispatch the next task to a pod. For now, there are no task groups, so the dispatcher should only ever have at most one task to dispatch.
* If a task is found to be undispatchable (e.g. the user disabled the task after a pod was already requested for it), remove it from the queue when looking for next task to dispatch and revert its status to container-unallocated.
* This is still missing a bit of correctness functionality around 1. double-checking if dependencies are still met when dispatching ([EVG-16549](https://jira.mongodb.org/browse/EVG-16549)) and 2. ensuring display tasks get updated when the execution task is dispatched ([EVG-16631](https://jira.mongodb.org/browse/EVG-16631)).
* Rename some methods that are specific …

EVG-16233: add method to dispatch next container task

---

rest/route/stats.go

[EVG-16407](https://jira.mongodb.org/browse/EVG-16407)
when task stats returns nothing, it now looks up when the last time they were generated and returns 503 if it has not been run in the last 24 hours 
https://evergreen-staging.corp.mongodb.com/rest/v2/projects/sandbox/task_stats?tasks=thistaskdoesn%27texistlol

EVG-16407 Update task_stats route to check last_run

---

trigger/task.go
trigger/task_test.go

[EVG-16101](https://jira.mongodb.org/browse/EVG-16101)
Right now we have a lot of special logic to avoid creating certain Jira tickets for the build baron, however the build baron logic has since been moved to their new tool so we no longer need this.
Removed the relevant unit test.

EVG-16101 remove special JIRA build baron handling

---

repotracker/repotracker.go
rest/data/commit_queue.go
service/api.go
units/commit_queue.go
units/patch_intent.go
validator/project_validator.go
validator/project_validator_test.go

[EVG-16539](https://jira.mongodb.org/browse/EVG-16539)
Added a warning saying that project config fields are not set when version control on the project ref is enabled (indicating the user might want to specify them), and a warning that version control is not enabled when project config fields are set (indicating the user might want to toggle VC).
Added unit test certifying new warnings for both scenarios.

EVG-16539 Warn when version control enabled with no project config and vice versa

---

model/patch/patch.go
operations/patch_util.go
units/patch_intent.go

[EVG-6274](https://jira.mongodb.org/browse/EVG-6274)
goes through all changed files and doesnt create patches when all the changes are in the ignore for github prs 
still works for normal patches 
https://github.com/evergreen-ci/commit-queue-sandbox/pull/346

EVG-6274 Update github PR patches to support ignore options

---

graphql/resolvers.go
graphql/util.go
graphql/util_test.go
model/event/subscriptions.go
model/event/subscriptions_test.go
model/user/user.go
model/user/user_test.go
rest/data/user.go
units/commit_queue.go

[EVG-16645](https://jira.mongodb.org/browse/EVG-16645)
If a user clicks the big red button we should shield their implicit (patch finish, build break, etc.) subscriptions from getting deleted.
The old UI's corresponding button didn't clear them because [they were filtered from the list of IDs](https://github.com/evergreen-ci/evergreen/blob/88d45f4e8d0de025d89c9d75683a2d99cde96d2d/public/static/js/notifications.js#L28-L39) sent to the application.
Added unit tests. 
Verified on staging that before these changes implicit subscriptions were removed and with the changes they aren't removed.

EVG-16645 shield implicit subscriptions

---

model/project.go
model/project_configs.go
model/project_ref.go
model/project_ref_test.go
public/static/js/projects.js
repotracker/repotracker_test.go
rest/model/project.go
service/project.go
service/templates/projects.html

[EVG-16428](https://jira.mongodb.org/browse/EVG-16428)
Added a form on the projects page allowing users to define default container resource sizes that are referenced by an alias. These can be saved to the project ref. Then, when the 'size' property is set on a container in YAML, the resource specs from the same name will be retrieved from the project ref at runtime.

EVG-16428 Allow custom container resource aliases defined on project page and in yaml

---

model/distro/distro.go
model/distro/distro_test.go
model/event/distro_event.go
model/event/distro_event_test.go
model/event/event_finder.go
model/host/host.go
model/host/host_test.go
model/task_queue.go
model/task_queue_service.go
model/task_queue_service_dependency.go
model/task_queue_service_test.go
rest/model/task.go
rest/route/distro.go
rest/route/distro_test.go
service/api_task.go
service/distros.go
service/event_log.go
units/host_monitoring_idle_termination.go

[EVG-12806](https://jira.mongodb.org/browse/EVG-12806)
When a distro has it's image updated, it's frustrating for engineers that new tasks they create may still be using the old image, if those hosts haven't been decommissioned yet. However, it's expensive to decommission all running hosts when AMI is updated. This change instead considers when a task has been created, and if it's been created since the AMI was updated, we wait for a new host (eventually old hosts will be decommissioned as idle when there are no more old tasks to run).
This may negatively impact new task wait times in these cases, however it would improve correctness. 
(Also, I chose to use events to determine if AMI has been updated because storing that in the Distro collection seemed a bit wrong, but I can still pivot …

EVG-12806 skip assigning task to host if the AMI is outdated

---

graphql/http_handler.go

[EVG-16581](https://jira.mongodb.org/browse/EVG-16581)
Adds a request id to gql splunk errors. This request id is also shared with splunk gql traces

EVG-16581: Add request id to gql splunk error

---

agent/command/assume_ec2_role_test.go

[EVG-16624](https://jira.mongodb.org/browse/EVG-16624)
test fails because the map is not ordered 
test now specifies what we want each time 
test passes in both orders

EVG-16624 Fix ec2 role test

---

cloud/spawn.go
graphql/resolvers.go
model/distro/db.go
model/distro/distro.go
model/distro/distro_test.go
model/host/host.go
model/scheduler_stats_test.go
model/task/task.go
model/task_queue_service.go
rest/data/distro.go
rest/data/distro_test.go
rest/data/host_create.go
rest/data/scheduler.go
rest/route/admin_test.go
rest/route/distro.go
rest/route/distro_test.go
rest/route/host_spawn_test.go
rest/route/middleware.go
scheduler/utilization_based_host_allocator.go
scheduler/wrapper.go
service/api_task.go
service/distros.go
service/spawn.go
service/task.go
units/host_monitoring_parent_decommission.go
units/scheduler_alias.go

[EVG-16559](https://jira.mongodb.org/browse/EVG-16559)
distro.FindOne works differently from other model FindOne functions in that it has no check for if adb.ResultsNotFound(err) in it, so a nil distro would also cause an error to return, and it returns a Distro object instead of a pointer which makes nil checks more difficult.
Changed to 1) no longer treat a nil distro as an error, and  2) return a distro pointer in distro DB functions.
Tests remain passing

EVG-16559 Refactor distro DB functions to fit convention

---

model/host/db.go
model/host/host_test.go
rest/route/host.go

[EVG-16554](https://jira.mongodb.org/browse/EVG-16554)
change find host by ip query to only find running hosts 
unit test
finding terminated hosts returns nothing

EVG-16554 Update find host by ip to only return running hosts

---

api/host.go
rest/route/sns.go
rest/route/sns_test.go
units/crons.go
units/host_monitoring_external_termination.go
units/host_monitoring_idle_termination.go
units/host_status.go
units/host_termination.go
units/host_termination_test.go
units/provisioning_user_data_done.go

Jira: https://jira.mongodb.org/browse/EVG-15358
If the host is externally terminated, skip the cloud host status check and termination. This assumes that the host really will terminate on its own without our intervention.
* Skip cloud host termination if host is externally terminated.
* Slightly refactor host termination job options.

EVG-15358: skip cloud host termination if host is externally terminated

---

cloud/ec2_client.go

[EVG-16576](https://jira.mongodb.org/browse/EVG-16576)
Following the suggestion from [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html) to pass a unique client token with each retry for the operations that support it. It's not abundantly clear from the docs what's valid as a token, but from what I saw the length and range of characters of [utility.RandomString](https://github.com/evergreen-ci/utility/blob/d16eb64796e67d3bbf2463eb9df94aa48911b0ff/random.go#L18-L21) (32 characters in the [0-9a-f] range) should be fine.
I spawned [a host](https://spruce-staging.corp.mongodb.com/host/i-094d53f450cc0bc17) on staging that (fortuitously) [retried a few times](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen-staging%20ap …

EVG-16576 use clienttoken in EC2 requests that accept it

---

model/project_aliases.go
rest/data/aliases.go
rest/data/aliases_test.go
rest/data/project.go
rest/route/alias.go
rest/route/project.go
rest/route/project_test.go
rest/route/repo.go
service/project.go

[EVG-16540](https://jira.mongodb.org/browse/EVG-16540)
Projects that have active aliases in their config yaml currently do not have them show up in the API response for the project.  Updated the project get route to display these aliases if the boolean url parameter 'includeProjectConfig' is set. Updated the documentation for the route specifying this: https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#get-a-project
Added unit testing and tested api responses locally with a project with set project config aliases.

EVG-16540 Show project config aliases in API response

---

model/task/task.go

[EVG-16699](https://jira.mongodb.org/browse/EVG-16699)
TaskTimedOut and TaskTestTimedOut had the same value, which means they would be arbitrarily prioritized making sorts inconsistent. I TaskTestTimedOut so that it is consistent. 
@mvankeulen94 Please let me know if you think we should instead prioritize TaskTimedOut over TaskTestTimedOut in sorts.

EVG-16699  Fix Non Deterministic behavior in display task status determination

---

agent/agent.go
config.go
globals.go
graphql/resolvers.go
model/container_task_queue_test.go
model/pod/dispatcher/db.go
model/pod/dispatcher/db_test.go
model/pod/dispatcher/dispatcher.go
model/pod/dispatcher/dispatcher_test.go
model/task/db.go
model/task/db_test.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
scheduler/task_finder_test.go
service/waterfall.go
units/pod_allocator_test.go

Jira: https://jira.mongodb.org/browse/EVG-16706
The container-unallocated and container-allocated states were used to represent different phases of container allocation for undispatched tasks, but the task lifecycle is logically simpler and requires fewer changes and less if-else checking if both host and container tasks use undispatched as the initial task state. Instead, there's a separate field for container tasks to indicate whether the container has been allocated to it yet or not for an undispatched task. The only downside is that some indexed queries that are specific to host/container tasks might be less than optimal, but it shouldn't be a major performance issue right now.
* Convert "container-unallocated" and "container-allocated" task statuses into a boolean field.
* Use …

EVG-16706: convert container allocation statuses into separate field

---

model/task_queue_service_dependency.go
model/task_queue_service_test.go

[EVG-16679](https://jira.mongodb.org/browse/EVG-16679)
If someone manages to create a dependency cycle or a loop in the dependency graph we shouldn't let it put the dispatcher out of commission. 
This PR 
1.  replaces a simple graph with a multigraph so we can model loops in the dependency graph
2. logs an unorderable error instead of returning
I'd thought to disable to tasks when we see they're part of a cycle so they won't keep coming up in the distro's queue, but opted not to. My thinking is that today the dispatcher is exclusively concerned with dispatching tasks and reaching into the task lifecycle to disable a task seems like it violates separation of concerns. Some mitigating factors are that [eventually](https://github.com/evergreen-ci/evergreen/blob/c2a10070a720bc20018b7a0bed8b40b …

EVG-16679 don't error for cycles/loops

---

model/task/db.go
model/task/task.go
model/task/task_test.go
units/host_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-16549
* Check that parent dependencies are met before allocating a container for a task and before dispatching. Since dependency children depend on the latest execution of a task to decide if dependencies are met, the parent dependency could become unsatisfied at any point in the container task pipeline (e.g. the dependency parent is restarted after a container was already allocated for the dependency child, so the dependency child no longer has fully met dependencies).
* Rename a few container task related functions.
* Fix a host termination job test that wasn't resetting the global mock cloud provider state.

EVG-16549: double-check dependency satisfaction during allocation and dispatch

---

model/project.go
model/project_ref.go
model/project_ref_test.go
model/version.go
rest/data/project.go
rest/route/project.go
rest/route/project_test.go
rest/route/service.go

[EVG-16073](https://jira.mongodb.org/browse/EVG-16073)
New route was created allowing users to get recent versions of a task for a specific project. Allows for filtering on build variant, starting revision number, and limit on the number of results returned.
Added new unit tests for the DB function and rest route.

EVG-16073: Add an end point to get recent running versions of a task

---

rest/route/project_test.go

Jira: https://jira.mongodb.org/browse/EVG-16718
#5555 caused a regression by setting `evergreen.SetEnvironment` so I removed it.
* Remove `evergreen.SetEnvironment` in test.
* Fix more usages of background contexts in tests.

EVG-16718: fix global env state for regression

---

model/generate.go
model/generate_test.go
model/lifecycle.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/project_parser.go
scripts/verify-merge-function-update.sh

[EVG-16625](https://jira.mongodb.org/browse/EVG-16625)
Intermediate step to using transactions (might only need to use them in a couple of places now). Store whether the parser project has already been updated by this generator and only update it if it hasn't been. The Save function actually already handles very well the cases where tasks/variants already exist; don't need to add any special casing to make this more specific.
Also refactored getting existing builds to make this more performant.
A risk I can see with this is: if generatorA runs, fails halfway (but the parser project is updated), and then generatorB runs, it would theoretically generate un-generated tasks/variants _if_ the variant is modified by both generators. That feels pretty specific though and maybe a worthwhile risk. …

EVG-16625 save un-generated tasks/variants in future iterations of generate.tasks

---

rest/route/host.go

Jira: https://jira.mongodb.org/browse/EVG-16718
I swapped out `evergreen.GetEnvironment()` in the host provisioning options REST route for #5569 but forgot that the Gimlet route handler internally makes a copy of the route using `Factory`. This should properly set the env so that the actual route handler used is populated with the environment.

EVG-16718: set environment for host provisioning options handler factory

---

graphql/generated.go
graphql/schema.graphql

Schema update for UI ticket [EVG-15087](https://jira.mongodb.org/browse/EVG-15087)
- Remove `definitionID` since this field is only used internally
- Remove `command` and `generateFile` fields in light of [EVG-16720](https://jira.mongodb.org/browse/EVG-16720)
- Require `project` (not sure if there was a particular reason this was nullable)
- Tested in GraphQL playground

EVG-15087: Update TriggerAlias schema

---

globals.go
model/event/host_event.go
model/event/host_event_test.go
model/event/pod.go
model/event/pod_test.go
model/pod/dispatcher/db.go
model/pod/dispatcher/db_test.go
model/pod/dispatcher/dispatcher.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/version.go
model/version_test.go
service/stats.go

Jira: https://jira.mongodb.org/browse/EVG-16307
This is mostly to do with activation/deactivation but I fixed some tech debt and style issues that I spotted along the way.
* Ensure task activation/deactivation works for both container and host tasks.
* Fix how the container task allocated time so that it's set/unset when the container is allocated/deallocated.
* Make `(task.Task).HostId` field omitempty since it's only relevant to host tasks.
* Include task execution when logging that a task is dispatched to a pod. The task ID is not sufficient to uniquely identify which task execution a pod ran, so it must include the task execution for the event logs. Host tasks currently do a thing where they retroactively set the execution number, but I would prefer to just set the execution when it's …

EVG-16307: support activating/deactivating container tasks

---

model/task_lifecycle.go
model/task_lifecycle_test.go

[EVG-16735](https://jira.mongodb.org/browse/EVG-16735)
The github check field got lost in a refactor, meaning that UpdateVersionGithubStatus wasn't using the right field.
Added unit test (which failed pre-changes).

EVG-16735 fetch github status field to calculate check status

---

rest/model/task.go

[EVG-16732](https://jira.mongodb.org/browse/EVG-16732)
Forgot to do this for previous executions

EVG-16732 Fetch AMI and projectIdentifier for previous executions

---

model/pod/dispatcher/db.go
model/pod/dispatcher/db_test.go
model/pod/pod.go
model/task/db.go
model/task/task.go
model/task/task_test.go

Jira: https://jira.mongodb.org/browse/EVG-16618
Rather than doing pod/task DB updates directly inside the dispatcher package, I moved them into their proper packages for better code organization.
Added unit tests for exported functions.

EVG-16618: move dispatcher updates for other models into respective packages

---

model/task/task.go

JIRA: https://jira.mongodb.org/browse/EVG-16682
Update the task log URL generation function to correctly check for deprecated Logkeeper-hosted Lobster links.
N/A

EVG-16682: correctly detect legacy lobster URLS

---

cloud/ec2_client.go

Jira: https://jira.mongodb.org/browse/EVG-16562
Fix an issue where logging an AWS API error mutates the `message.Fields`, causing the message to spuriously show an error if there's a retry that's successful.
Didn't change any automated tests since we don't test our logging code and this issue only manifest as a log with incorrect fields.

EVG-16562: do not reuse AWS API log message between retries

---

graphql/resolvers.go

[EVG-16748](https://jira.mongodb.org/browse/EVG-16748)
This was throwing an error since we were passing a reference to buildFromService

EVG-16748 Pass pointer to buildFromService in upstreamProject Resolver.

---

model/patch/cli_intent.go
model/patch/patch.go
model/project.go
model/project_test.go
operations/flags.go
operations/http.go
operations/model.go
operations/patch.go
operations/patch_util.go
service/api_patch.go
units/patch_intent.go

[EVG-6741](https://jira.mongodb.org/browse/EVG-6741)
users can now pass in regex to regextasks and regexvariants flag 
unit test 
tested on staging with command 
`~/go/src/github.com/evergreen-ci/evergreen/clients/darwin_amd64/evergreen -c ~/.evergreen-staging.yml patch -u -v ".*" -t ".*"` 
to schedule all patchable 
also tested with: 
-v all -t all (still works)
-v ".*" -t all (and vise versa)
-v ".*" -t "task$" 
leaving it empty
all works as expected

EVG-6741 Update cli patch command to take regex

---

globals.go
model/lifecycle.go
model/task/db.go
model/task/task.go
model/task/task_test.go
units/crons.go
units/pod_allocator_test.go

Jira: https://jira.mongodb.org/browse/EVG-16309
Disable container tasks that have spent too long without being dispatched. This isn't intended to catch a lot of tasks since after [PM-2617](https://jira.mongodb.org/browse/PM-2617), tasks are supposed to give up on allocating after they've failed a few attempts. However, it does put a cap on the max time a container task could possibly spend waiting for dispatch.
The host task scheduler has [similar functionality](https://github.com/evergreen-ci/evergreen/blob/fa60e78f57c7591334b16f884e62e069c1a65999/model/task/task.go#L1261-L1285), but that implementation is slightly less correct since it doesn't consider its effects on dependencies  (e.g. does disabling the task block another task), doesn't update the display task status, and doesn't log …

EVG-16309: disable stale undispatched container tasks

---

model/pod/dispatcher/dispatcher.go
model/pod/dispatcher/dispatcher_test.go
model/task/task.go
model/task/task_test.go

Jira: https://jira.mongodb.org/browse/EVG-16631
Update display task after the container task is dispatched. I did it outside the transaction since it's not critical to update the display task and to avoid having to change `UpdateDisplayTaskForTask` to make it work with the transaction context.
If it errors while updating the display task, the task is still considered dispatched according to the DB. The agent protocol will deal with re-attempting to update the display task in the error case (to be written in [PM-2616](https://jira.mongodb.org/browse/PM-2616)).
Added unit tests for dispatcher.

EVG-16631: update display task when dispatching container execution task

---

cloud/spawn.go
cloud/spawn_test.go
globals.go
operations/keys.go
public/static/js/directives/directives.spawn.js
public/static/partials/user_host_options.html
rest/route/keys.go
rest/route/keys_test.go

[EVG-13451](https://jira.mongodb.org/browse/EVG-13451)
add 2 extra types of ssh keys that we allow 
unit test 
created host on staging using new key type
spruce
https://github.com/evergreen-ci/spruce/pull/1226

EVG-13451 Support modern ssh key types

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/util.go

[EVG-16769](https://jira.mongodb.org/browse/EVG-16759)
Previously the buildVariants resolver would always fetch the base tasks for the build variants query even if they were not used. This adds an option to exclude fetching it for situations where we don't need it. 
I chose to include it by default to maintain the same behavior it currently exhibits to avoid any backwards compatibility issues with the UI. 
This helps reduce response times in the UI by simplifying the query when the additional fields are not needed.

EVG-16759 Add option to exclude base tasks from buildVariants resolver

---

model/host/host.go
model/host/host_test.go
model/host/hostutil_test.go
units/building_container_image.go
units/host_drawdown.go
units/host_monitoring_idle_termination.go
units/host_monitoring_parent_decommission.go
units/host_termination.go

[EVG-16076](https://jira.mongodb.org/browse/EVG-16076)
Right now we sometimes have a race where Evergreen assigns a task to a running host, but then Evergreen decommissions it because our local host document doesn't show this running task yet. This is an issue when the task is part of a task group, since we shouldn't be decommissioning that host.
Since we check when assigning a task that the status is running in the query itself, it makes sense to also check the task group field when decommissioning, since that would eliminate the race.

EVG-16076 disallow Evergreen from decomissioning hosts running task groups

---

service/templates/admin.html

[EVG-15945](https://jira.mongodb.org/browse/EVG-15945)
We usually use this field in an emergency so it's helpful for it to be clear about whether it uses EST, user configured timezone, or UTC. (Since this is legacy and only admin I don't think we need to actually change the existing functionality).
Verified that it is actually EST.

EVG-15945 clarify timezone on admin page

---

graphql/resolvers.go
model/task_lifecycle.go
rest/model/version.go

[EVG-16731](https://jira.mongodb.org/browse/EVG-16731)
version and build aborted field now dynamically reflects whether we should show the status as aborted or not 
normal patch with success and abort will show abort 
will show failure if tasks are abort and failure 
works with child patches 
https://spruce-staging.corp.mongodb.com/version/613b92639dbe323620f081ab/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

EVG-16731 Update version aborted field

---

apimodels/test_results.go
rest/data/interface.go
rest/data/test.go
rest/data/test_test.go
rest/route/service.go
rest/route/test.go

JIRA: https://jira.mongodb.org/browse/EVG-16033
Add new API endpoint `rest/v2/tasks/<task_id>/tests/count` to return the number of tests for a given task ID. Once this is merged and deployed, I will add documentation to the Evergreen wiki.
- Unit tests for fetching the test count from either Cedar or the database, depending on where the tests live.
- Tested this in staging with both test results in Cedar and in the database.

EVG-16033: Expose number of tests belonging to a task 

---

units/host_allocator.go

[EVG-16725](https://jira.mongodb.org/browse/EVG-16725)
It looks like the eventInfo itself should be right even though legacy stuff has been removed but let me know if that seems untrue.

EVG-16725 reintroduce stats needed for dashboard

---

units/patch_intent.go

[EVG-16680](https://jira.mongodb.org/browse/EVG-16680)
A log like this would help a lot with debugging things like EVG-16680 going forward.

EVG-16680 add log for ignored patches

---

rest/data/aliases_test.go

[EVG-16719](https://jira.mongodb.org/browse/EVG-16719)
A couple BF tickets (linked above) were generated from test TestFindProjectAliasesMergedWithProjectConfig due to it returning an unsorted list of aliases, although the test makes assertions about individual indices of the returned slice which caused the test to occasionally flake.  Solved by sorting aliases in the test.
Ran tests several times with no indication of flakiness.

EVG-16719 Sort aliases in TestFindProjectAliasesMergedWithProjectConfig

---

model/project.go
model/project_test.go

[EVG-6412](https://jira.mongodb.org/browse/EVG-6412)
cli patch command can now take tags 
unittest
running 
❯ clients/darwin_amd64/evergreen -c ~/.evergreen-staging.yml patch -v all -t .linter

EVG-6412 Update cli patch command to take tags

---

graphql/resolvers.go

[EVG-16731](https://jira.mongodb.org/browse/EVG-16731)
Avoid nil pointer deference when calculating version status

EVG-16731: avoid nil pointer dereference

---

public/static/js/projects.js

[EVG-16664](https://jira.mongodb.org/browse/EVG-16664)
a typo was causing the legacy project page to not load the admin variables correctly 
there was also an issue with deleting the admin vars so i fixed that as well 
staging

EVG-16664 Update project page to handle admin-only vars

---

model/project_ref.go

Follow up to https://github.com/evergreen-ci/evergreen
- Permit adding a project with a new owner when 0 valid GitHub organizations are specified

EVG-15658: Allow empty GitHub orgs list

---

model/event/host_event.go
model/host/db.go
service/api_task.go
units/provisioning_create_host.go
units/spawnhost_modify.go
units/spawnhost_modify_test.go
units/spawnhost_start.go
units/spawnhost_start_test.go
units/spawnhost_stop.go
units/spawnhost_stop_test.go

Jira: https://jira.mongodb.org/browse/EVG-16750
The host event logs currently only say whether a spawn host modification succeeded or failed. This adds the error reason to the host event logs so that users can see why the modification failed.
Updated existing unit tests for spawn host modification jobs to check event logs.

EVG-16750: add error logs to event when host modification fails

---

units/periodic_builds.go
units/periodic_builds_test.go

[EVG-16762](https://jira.mongodb.org/browse/EVG-16762)
Add revision to periodic build using the latest revision (this is what using branch does anyway, but using revision throughout also makes this more consistent, in case a new version is pushed while we're still adding included files).
Tested on staging: https://evergreen-staging.corp.mongodb.com/rest/v2/versions/62729bffb2373669f3e4715c

EVG-16762 add revision to periodic builds

---

graphql/errors.go
graphql/resolvers.go
model/project_vars.go
rest/data/project_settings.go
rest/data/project_settings_test.go

[EVG-16784](https://jira.mongodb.org/browse/EVG-16784)
- When a project has successfully copied but some fields were unable to be copied, return both data _and_ error from the `copyProject` resolver. This enables us to redirect the user to the new project, but still warn them that some errors were encountered.
- Add new `PartialError` GraphQL error type
- Add unit test, tested in GraphQL playground

EVG-16784: Return partial error from copyProject

---

service/ui.go

[EVG-16386](https://jira.mongodb.org/browse/EVG-16386)
These code changes set httpOnly true for the `mci-session-cookie` which is used for legacy ui banners. `mci-project` cannot be set to httpOnly because it's accessed manipulated by spruce js. [newrelic](https://newrelic.com/termsandconditions/cookie-policy/cookie-table) 3rd party cookies can be disabled only. AWS 3rd party cookies can be [configured](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html#enable-sticky-sessions-application) from the aws cli if necessary. 
Tested by making sure a banner appears when stopping a host locally and in staging.

EVG-16386: Set HttpOnly flags for evergreen cookies

---

agent/background.go
config.go

[EVG-16103](https://jira.mongodb.org/browse/EVG-16103)
Removing log statement that is running at the end of each task and brought up discussion in the [users channel](https://mongodb.slack.com/archives/C0V896UV8/p1651753009912469)

EVG-16103 Remove "Heartbeat ticker canceled, aborting task" from agent logs

---

rest/route/test.go

[EVG-16040](https://jira.mongodb.org/browse/EVG-16040)
adding latest=true will give the most recent execution and default behavior is not modified
only works if execution is not specified 
staging
https://evergreen-staging.corp.mongodb.com/rest/v2/tasks/evg_race_detector_test_model_pod_4a1ed094bee959b235b34f3a2cffd71a43586e02_22_05_04_14_10_29/tests?latest=true

EVG-16040 Update test endpoint to return latest execution

---

service/api_task.go

Found this bug through investigating [these logs](https://mongodb.splunkcloud.com/en-US/app/search/search?s=%2FservicesNS%2Fannie.black%2Fsearch%2Fsaved%2Fsearches%2Funblocked%2520dependencies%2520that%2520aren%2527t%2520re-blocked&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&q=search%20index%3Devergreen%20%22message%22%3D%22unblocked%20dependent%20tasks%22%20%22ticket%22%3D%20%22EVG-12923%22&earliest=1651723200&latest=1651896000&sid=1651846628.1336415). If a single host task group task fails, we block all subsequent tasks in the group. However, we clear the host's running task first, so it sometimes picks up the later task group task before it's actually marked as blocked. We should add these …

EVG-12923 block task group tasks before clearing host's running task

---

globals.go
model/generate.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/pod/pod.go
model/pod/pod_test.go
model/project.go
model/task/task.go
repotracker/repotracker.go
units/pod_allocator.go
units/pod_allocator_test.go
validator/project_validator.go
validator/project_validator_test.go

Jira: https://jira.mongodb.org/browse/EVG-16371
* Resolve the task's container config when creating the DB task. The container config cannot be changed once the task is created.
* This is necessary to avoid some extra work later on. The container definitions only exist in the `model.Project` (the YAML model) and not in a DB model. Therefore, resolving the container options when creating the DB task avoids the need to re-read the whole YAML into a `model.Project` to get the container definitions in the pod lifecycle.
* Resolving the container options at task creation time also has an implication for container sizes - since container sizes can be defined in the project ref, they can change dynamically. I decided that it's better to snapshot the container size at task creation time and …

EVG-16371: propagate container options from task to pod

---

units/stats_task_end.go

[EVG-16789](https://jira.mongodb.org/browse/EVG-16789)
task-end-stats were not properly logging out display task IDs as a part of the implementation done in https://jira.mongodb.org/browse/EVG-14823.  The log statement was referencing DisplayTask instead of DisplayTaskId on the passed in task.  Since the task end stats job re-retrieves the task from DB at runtime, DisplayTask will be nil because GetDisplayTask() only saves DisplayTaskId to DB.
Tested in staging

EVG-16789 Use DisplayTaskId instead of DisplayTask.Id for task-end-stats

---

cloud/cloud_status.go
cloud/docker.go
cloud/docker_client.go
cloud/ec2.go
cloud/ec2_fleet.go
units/host_status.go
units/host_termination.go

[EVG-16713](https://jira.mongodb.org/browse/EVG-16713)
Discovered two things in this ticket:
1) We double log everything that we both grip and add to the job's errors, so I reduced this so we only log once.
2) We have special handling for EC2 instances not being found, but not for docker. It's weird to do this for an interface also, since docker has errors formatted differently, so I thought a new status could make sense, and I looked at usages of GetInstanceStatus to verify terminations would still happen where needed. 
If this seems like an issue, I could change it to case on EC2 errors _or_ docker errors but I think it makes sense to move that logic out.
Not sure how to test besides putting in staging and doing some things and verifying no breakage.

EVG-16713 refactor handling of nonexistent containers

---

model/task/db.go
model/task/task_test.go

[EVG-16749](https://jira.mongodb.org/browse/EVG-16749)
This PR fixes an issue where the execution tasks were being returned incorrectly. You can see in the video below that when I go through different executions in this [version](https://spruce.mongodb.com/task/mongodb_mongo_v4.4_windows_display_multiversion_319d8d8145fb5893ab3bf5d077730226f3f2af7c_22_04_06_18_31_56/execution-tasks?execution=0&sortBy=STATUS&sortDir=ASC&sorts=STATUS%3AASC), I start getting multiple copies of the execution tasks (there should only ever be four). 
https://user-images.githubusercontent.com/47064971/167049541-b0c120ed-b52e-442d-b8c5-dd1cd2fcd966.mov
The reason this happens is that there is an error in the query for fetching execution tasks. Specifically, the problem comes from the fact that we find old tasks …

EVG-16749: Fix incorrect logic for fetching old execution tasks

---

model/task/task.go

[EVG-16810](https://jira.mongodb.org/browse/EVG-16810)
Noticed that we're logging with an empty ID.

EVG-16810 fix dependency log message

---

units/patch_intent.go

[EVG-16304 ](https://jira.mongodb.org/browse/EVG-16304 )
Dependabot patches should be automatically authorized. I was torn about whether to make dependabot a constant, or have this be definable via admin settings. However, dependabot is something of a special case, and we aren't intending to allow any other non-members to be authorized, so I think making this an editable admin setting field would be misleading.
Don't have a good way to test this; may make an alert for myself on the new log message and will close when it triggers (i.e. the code is validated).

EVG-16304 authorize dependabot patches

---

model/task_lifecycle.go
service/api_task.go
units/host_termination.go

Gave myself a headache reading through scheduler code to think through this:
I think blocking task group tasks isn't quite enough because we depend on the task queue to handle removing unattainable dependencies. However, we only refresh the task queue on hosts [every one minute](https://github.com/evergreen-ci/evergreen/blob/bbef382d237202a8074f0113bdf5214abb21c386/service/api.go#L60). So even later task group tasks are blocked and dequeued, this will only take affect for hosts [once they refresh their task queues](https://github.com/evergreen-ci/evergreen/blob/5e8f49dfb8a290050cdc226571c2a02922c7d367/model/task_queue.go#L753-L756). 
PS: I believe the reason regular tasks don't hit this is because they already _have_ the dependencies …

EVG-12923 consider in nextTask if a task is currently blocked

---

globals.go
model/lifecycle.go
model/project.go
model/project_test.go
model/task/dependency_graph.go
model/task/dependency_graph_test.go
model/task/task.go
validator/project_validator.go
validator/project_validator_test.go

[EVG-16679](https://jira.mongodb.org/browse/EVG-16679)
When I was looking to validate that generate tasks doesn't create dependency cycles I wrote a thing to abstract away the graph computer sciencey stuff and used it to simulate the new dependency graph before actually adding the dependencies. The case to use the DependencyGraph in other places seemed compelling so I began refactoring other places to use it too. 
This PR includes the DependencyGraph itself and applying it to two problems in the project validator. Future PRs will use it to validate adding dependencies on generated tasks, getRecursiveDependencies (down and up), and for the DAG dispatcher.
Unit testing

EVG-16679 dependency graph

---

model/container_task_queue.go
model/pod/db.go
model/pod/dispatcher/db.go
model/pod/dispatcher/db_test.go
model/pod/dispatcher/dispatcher.go
model/pod/pod.go
model/pod/pod_test.go
rest/route/pod_agent.go
rest/route/pod_agent_test.go
units/crons.go
units/pod_allocator.go
units/pod_creation.go

Jira: https://jira.mongodb.org/browse/EVG-16803
I had to plug in the dispatcher to the pod next task route since it was necessary for logging. It doesn't actually make the agent run the task for now, but it does log that the necessary DB changes were made to indicate the task is considered dispatched.
We're most interested in timing how long each step takes from the moment the task starts waiting to run (when it's activated) to when it actually run. I changed it to log timing statistics when:
* Container task queue is generated.
* Pod allocation jobs are being enqueued (so we know how many parallel pod requests there are currently).
* Task is allocated a pod.
* Task's pod is actually requested from the cloud provider.
* Agent makes first contact with the app server.
* Task is dispatched …

EVG-16803: log statistics for container task pipeline performance

---

service/task.go

[EVG-16855 ](https://jira.mongodb.org/browse/EVG-16855 )
Evergreen should use the correct link for redirecting old executions.
Tested locally that an old execution now opens in Spruce.

EVG-16855 use correct task ID in new UI link

---

api/host.go

Jira: https://jira.mongodb.org/browse/EVG-16863
If the user terminates the host with a note from the host event page, the note should eventually show up in the event logs.
Didn't seem that critical enough to test, and I didn't feel like unit testing all this existing untested code.

EVG-16863: populate host termination reason from note

---

model/lifecycle.go
model/lifecycle_test.go

[EVG-16831](https://jira.mongodb.org/browse/EVG-16831)
[We intend](https://github.com/evergreen-ci/evergreen/pull/3896) that when a generated task is activated the tasks it depends on should also be activated. I think maybe later when we added [task level activation](https://github.com/evergreen-ci/evergreen/pull/4679) we didn't also update this logic. So currently if a generated task is `activate: false` but its build isn't its dependencies are still activated.
The changes here should activate just the dependencies for activated generated tasks.
I contrived a set of tasks on the sandbox project. [inactivated_task0](https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu1604_inactivated_task0_patch_a2139a208d54a9a11b2911c72ba24d0bc438163a_627d7466b237364e8395eac5_22_05_12_20_56_11) is …

EVG-16831 activate dependencies for activated tasks

---

graphql/resolvers.go
graphql/util.go
graphql/util_test.go
model/patch/patch.go

[EVG-16818](https://jira.mongodb.org/browse/EVG-16818)
This refactors calculating collective statuses with aborted to avoid passing an empty array. 
Tested on staging and added a unit test

EVG-16818 Refactor aborted collective status

---

model/project_ref.go
model/project_ref_test.go
model/repo_ref.go
rest/data/project_settings.go

[EVG-16848](https://jira.mongodb.org/browse/EVG-16848)
We want to try to make sure that a project doesn't get attached or change owner/repo and suddenly introduce project conflicts on the UI that prevent the page from being usable, and makes it ambiguous in the backend which project is being used. 
I had this silently update conflicts. For AttachToRepo this definitely makes sense, since any new conflicts would be due to defaulting to repo, so explicitly setting to false is pretty much the same as what they had before. For AttachToNewRepo this may not be clear, however I don't anticipate this being used often (if at all) except to rename existing repos, and returning an error in the conflict case would require some refactoring and also may not be clear anyway. (I can change this if there …

EVG-16848 handle Github conflicts in more places

---

graphql/tests/mainlineCommits/queries/variant-displayname.graphql
graphql/tests/mainlineCommits/results.json
model/task/task.go
model/task/task_test.go

[EVG-16918>](https://jira.mongodb.org/browse/EVG-16918)
Build Variant Display Names were not included in this query which broke matching on them.
I was unable to write a unit test for this function due to a dep cycle. But i wrote  a graphql test

EVG-16918 Fix Build Variant display names not being resolved in HasMatchingTasks query.

---

model/patch/github.go
model/patch/github_test.go
testutil/github.go
units/github_status_api_test.go
units/patch_intent.go
units/patch_intent_test.go

[EVG-16615 ](https://jira.mongodb.org/browse/EVG-16615 )
Right now we purposefully use the first commit's base hash as the base commit. This seems really misleading since future commits can be rebased on a new HEAD, so their base commits should reflect that.
I created this PR: https://github.com/evergreen-ci/commit-queue-sandbox/pull/349
The 1st commit is a control; the base revision is correctly [a2139a208d](https://spruce-staging.corp.mongodb.com/version/sandbox_a2139a208d54a9a11b2911c72ba24d0bc438163a/tasks).
The second commit is without my changes; you can see that even though we've merged HEAD, the base revision doesn't change.
(The 3rd commit had a bug so skipping it)
The 4th commit is with my changes; now the base revision is correctly the new revision, …

EVG-16615 use most recent base revision for PRs

---

makefile

[EVG-16930](https://jira.mongodb.org/browse/EVG-16930)
install lint directly instead of using goreleaser 
will be making this change in these repos 
https://spruce.mongodb.com/version/6286971132f4175495e7282e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

EVG-16930 Deprecate goreleaser

---

model/task/task.go

[EVG-16940](https://jira.mongodb.org/browse/EVG-16940)
Came across his while looking at other things; we can match on display status after we calculate it so we don't need to include base tasks and other info for unneeded tasks.

EVG-16940 match on display status before aggregation lookup

---

testdata/local/github_hooks.json

[EVG-16958](https://jira.mongodb.org/browse/EVG-16958)
- Add github_hooks collection so that local projects have webhooks enabled for testing
- Verified in local dev environment that `githubWebhooksEnabled` field is returned as true for evergreen-ci/evergreen and evergreen-ci/spruce projects

EVG-16958: Add webhook documents

---

graphql/resolvers.go

[EVG-16954](https://jira.mongodb.org/browse/EVG-16954)
Default nil values for unattached projects.
Verified through testing that unset booleans before the change had no radio box highlighted, and after the change the Disabled one was highlighted.

EVG-16954 default nil values

---

rest/data/task.go
rest/route/service_test.go

[EVG-16125](https://jira.mongodb.org/browse/EVG-16125)
[This slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1653473341506469) raised the issue that our endpoint to [list tasks by commit](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#list-tasks-by-project-and-commit) no longer works when putting a project identifier in its path, but rather expects the project id itself which for many projects is distinct from the identifier. Change has been made to modify the options passed into the DB function for this route to lookup project id from its identifier passed into the path.
Modified unit tests to use separate project identifiers and project id when testing this route.

EVG-16125 Accept project identifier rather than project id in 'tasksByProjectHandler'

---

config.go
rest/client/methods.go
rest/route/commit_queue.go
rest/route/commit_queue_test.go
rest/route/service.go

[EVG-16693](https://jira.mongodb.org/browse/EVG-16693)
Modification to the commit queue delete route, making it accept just a single commit queue item and do a project DB lookup on the server side rather than on the client side where it is currently invalid.
Testing in staging env (attached)

EVG-16693 Remove project param from delete CQ route

---

model/host/host.go
model/lifecycle.go
operations/host_spawn.go
repotracker/repotracker.go
units/host_status.go

[EVG-16858](https://jira.mongodb.org/browse/EVG-16858)
Alas, Find omits display tasks, which means the check for existing display tasks at 1705 - 1707 never works. 
I also noticed we still have "sanity check" used throughout the codebase, which is not super PC these days so I went ahead and changed those.

EVG-16858 include display tasks when checking existing generated tasks

---

api/host.go
cloud/ec2.go
public/static/js/hosts_admin.js

[EVG-16833](https://jira.mongodb.org/browse/EVG-16833)
Increases retries but adds a max delay since I think multiple minutes in between checks causes user experiences such as what Jason mentioned [here](https://mongodb.slack.com/archives/C0V896UV8/p1653489578489349?thread_ts=1653488793.700029&cid=C0V896UV8) (I looked at his host a few minutes prior and it had already been moved to stopping in AWS. Let me know if this seems like the wrong approach or limit.
I also added Stopped to the host panel (and will open a corresponding spruce PR) so that we can edit host statuses more easily.

EVG-16833 improving moving a host from stopping to stopped

---

model/project.go
model/project_ref.go
public/static/js/projects.js
rest/model/project.go
service/project.go
service/templates/projects.html
validator/project_validator_test.go

[EVG-16815](https://jira.mongodb.org/browse/EVG-16815)
The ProjectRef now has a section to set username/password pairs as credentials to a private image repository and give them a name which can then be referenced in the project YAML. Upon submitting these new credentials to the ProjectRef, we will later implement a change to store these credentials in AWS Secrets Manager at the time they are submitted as changes on the ProjectRef. This will allow projects to reuse the same credential over and over for every pod it creates in the future rather than having to generate a new credential each time a pod is created (which would be expensive and breach API limits).
Tested modify project route in staging to confirm credentials were properly set. Updated unit tests for validating credential …

EVG-16815 Reference repo credentials in YAML from credentials set on the ProjectRef

---

model/host/host.go
model/host/host_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
model/task_queue.go
rest/route/host.go
units/check_blocked_tasks.go

The couple of times we run into this now seem valid; we don't 100% guarantee that task group tasks will run on the same host (for example, if something happens to host1, then everything else can try to run on host2). That means sometimes funny races will happen. One I've found is when host1 is running a task group but is quarantined, host2 will start running the task group, but then the quarantined host starts running again and thinks it can continue with the task group since that was its last running task, even though host2 has now taken over (headache yet?).
Whereas before improvements were made we hit this error many times a day, we now only hit it a couple of times a week, and always for cases like the above where it makes sense …

EVG-12923 remove re-computing dependencies and reset last running task

---

rest/route/pod_agent.go
rest/route/pod_agent_test.go
rest/route/service.go

Jira: https://jira.mongodb.org/browse/EVG-16881
Instead of running the shell script directly as the container command, I moved it to a REST route. I copied most of the logic from [here](https://github.com/evergreen-ci/evergreen/blob/698add52308336caf4e8b56f6e0e9c3e118be296/cloud/pod_agent_util.go#L12-L117). I didn't change the container command itself yet, so this route will be unused until [EVG-16882](https://jira.mongodb.org/browse/EVG-16882).

EVG-16881: implement agent pod provisioning route

---

graphql/resolvers.go
rest/data/interface.go
rest/data/test.go
rest/data/test_test.go
rest/route/service_test.go
rest/route/test.go

[EVG-17014](https://jira.mongodb.org/browse/EVG-17014)
Right now, we check if we're using cedarResults using the task from the project context, rather than the correct task for that task/execution pair. If we're querying an old execution and the newest execution is running, then the projCtx.Task.CedarResults returns false, which means we query using the legacy method for old tasks (which correctly would've had CedarResults set to true if we used the right document).
Refactored so we'd only ever need to query the task document once.
Tested on staging; https://evergreen-staging.corp.mongodb.com/rest/v2/tasks/evg_ubuntu1604_test_model_manifest_78708dfdbd1f5c4e517a61ebc5734f9b54de1323_22_05_31_21_59_52/tests?execution=0 didn't work after restarting before changes, and did work after …

EVG-17014 use correct task to determine test results type
