graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/version/data.json
graphql/tests/version/queries/manifest.graphql
graphql/tests/version/results.json
testdata/local/manifest.json

[EVG-13902](https://jira.mongodb.org/browse/EVG-13902)
This will resolve the manifest field for a version 
graphql tests

EVG-13902 Create resolver for manifest

---

public/static/app/common/constants.js
public/static/app/perf/perf.js
service/templates/task_perf_data.html

[TIG-3231](https://jira.mongodb.org/browse/TIG-3231)
Include the new trend charts on evergreen's task data page.
I have not, since I'm not able to run evergreen locally.

TIG-3231: New trend charts in evergreen

---

model/project_ref.go
model/project_ref_test.go
rest/data/project.go
rest/model/project.go

[EVG-15058](https://jira.mongodb.org/browse/EVG-15058)
Created constants for each of the sections, and unset or deleted anything relevant (projectRef variables that aren't set use the value from the repoRef). Also logged, and made sure to log even if we were somehow only able to complete part of the update.
Added unit test. This isn't used anywhere yet to test elsewhere.

EVG-15058 add DefaultSectionToRepo function

---

rest/data/patch.go
rest/data/patch_test.go
rest/route/patch_test.go
service/templates/admin.html

[EVG-15231](https://jira.mongodb.org/browse/EVG-15231)
- Add pod init section to admin settings page
- local evergreen testing

EVG-15231: Add Pod Init to admin settings HTML page

---

model/project.go
model/project_parser.go
model/project_parser_test.go
model/project_test.go

[EVG-14953](https://jira.mongodb.org/browse/EVG-14953)
Commented out parts give errors and I'm not sure why! (marked with a comment)
Create merge function for multiple project configs
unittest

EVG-14953 Create merge function for multiple project configs

---

model/project_ref_test.go
model/repo_ref.go
model/user/user.go
model/user/user_test.go
service/project.go

[EVG-15050 ](https://jira.mongodb.org/browse/EVG-15050)
The work for this is pretty much the same as what we do in the old UI so I just refactored. 
Added unit test and modified an existing one to verify that repo admins _do_ also have edit access to projects.

EVG-15050 get list of viewable projects by user

---

model/lifecycle.go
model/project_aliases.go
model/project_aliases_test.go
repotracker/repotracker.go
service/project_test.go

[EVG-13272 ](https://jira.mongodb.org/browse/EVG-13272 )
While investigating EVG-15059, found places where we should be checking the repo. Made the project function private to make it harder to make this mistake in the future.

EVG-13272 consider repo for github check aliases

---

cloud/pod_util.go
cloud/pod_util_test.go

[EVG-15249](https://jira.mongodb.org/browse/EVG-15249)
- Set working directory in pod container definition
- Add field into existing test

EVG-15249: Set working directory for pod

---

model/pod/pod.go
rest/model/pod.go

JIra: https://jira.mongodb.org/browse/EVG-15252
* FIx BSON tag on pod status.
* Remove unused struct in pod API models.
N/A

EVG-15252: fix BSON tag on pod status

---

rest/data/pod.go
rest/data/pod_test.go

JIra: https://jira.mongodb.org/browse/EVG-15251
Add the agent-specific pod ID and secret when initializing the pod document.
Data connector tests.

EVG-15251: set agent-specific settings when initializing pod document

---

cloud/pod_util.go
cloud/pod_util_test.go
units/pod_creation.go

JIra: https://jira.mongodb.org/browse/EVG-15256
* Include required prefixes for secrets and task definitions. We need these because our IAM role only has permissions to use resources containing those prefixes.
* Set agent's container name.
Updated tests.

EVG-15256: include secret and task definition prefixes

---

rest/route/github.go
rest/route/github_test.go

[EVG-15002](https://jira.mongodb.org/browse/EVG-15002)
do not grip anything for unknown event type `pull_request_reveiw_thread`
unit test

EVG-15002 Silence unknown github event error

---

config_scheduler.go
model/distro/distro.go
model/distro/distro_test.go
rest/model/admin.go
scheduler/planner.go
service/templates/admin.html

[EVG-15183](https://jira.mongodb.org/browse/EVG-15183)
Add stepback task factor to admin page
the factor saves on local evergreen

EVG-15183 Change stepback tasks to have a configurable priority above mainline commits

---

cloud/pod_util_test.go
config_cloud.go
public/static/js/admin.js
rest/model/admin.go
rest/model/admin_test.go
service/templates/admin.html
testutil/config.go

JIra: https://jira.mongodb.org/browse/EVG-15261
Add admin settings for AWSVPC subnets and security groups.
Updated existing tests and tested in local Evergreen.

EVG-15261: add AWSVPC network settings

---

apimodels/test_results.go
glide.lock
vendor/github.com/evergreen-ci/timber/testresults/get.go
vendor/github.com/evergreen-ci/timber/testresults/get_test.go

JIRA: https://jira.mongodb.org/browse/EVG-15254

EVG-15254: Revendor timber

---

agent/agent.go
agent/task.go
config.go

JIRA: https://jira.mongodb.org/browse/EVG-15016
Tested this in staging.

EVG-15016: Fix system metrics collector race condition

---

model/task/db.go
model/task/task_test.go

[EVG-15096](https://jira.mongodb.org/browse/EVG-15096)

EVG-15096 Fix blocked tasks showing as will run

---

model/project_parser.go
operations/evaluate.go

[EVG-14955](https://jira.mongodb.org/browse/EVG-14955)
added type to opts
local test

EVG-14955 Update evaluate to return the merged project

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
rest/data/interface.go
rest/data/patch.go

[EVG-15345](https://jira.mongodb.org/browse/EVG-15345)
This adds childVersions to the version resolver 
Tested on the graphql playground on staging.

EVG-15345 Add childVersions to the Version resolver

---

public/static/js/projects.js

[EVG-15338 ](https://jira.mongodb.org/browse/EVG-15338 )
womp

EVG-15338 use valid js syntax

---

environment.go
graphql/ui_plugin_build_baron.go
model/project.go
model/project_parser.go
model/project_parser_db.go
model/project_ref.go
plugin/build_baron.go
plugin/build_baron_test.go
rest/route/annotations_test.go
service/ui.go

This reverts https://github.com/evergreen-ci/evergreen/pull/4959

Revert EVG-15212

---

thirdparty/github.go

[EVG-14603](https://jira.mongodb.org/browse/EVG-14603)
Brian added logging to figure out who was calling github client to the point where we're hitting limits. I'm not seeing anything suspicious so far but it looked like we missed the cases that don't use getGithubClient.

EVG-14603 capture more github usage logging

---

graphql/tests/scheduleUndispatchedBaseTasks/data.json
model/task_lifecycle.go
model/task_lifecycle_test.go

[EVG-14601](https://jira.mongodb.org/browse/EVG-14601)
updates status on setActiveState now
https://spruce-staging.corp.mongodb.com/version/6137a8299dbe322c5de92d93/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

EVG-14601 Update statuses after tasks are aborted

---

rest/route/project_copy.go

[EVG-15222](https://jira.mongodb.org/browse/EVG-15222)
oof

EVG-15222 create new project ID for copy route

---

rest/data/patch_intent.go

[EVG-14178](https://jira.mongodb.org/browse/EVG-14178)
Since `FindOneProjectRefByRepoAndBranchWithPRTesting` already logs a debug message, I just deleted it
n\a

EVG-14178 Log cannot map pull request to project at a lower level

---

graphql/generated.go
graphql/integration_spec.json
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/attachProjectToRepo/data.json
graphql/tests/attachProjectToRepo/queries/attachProjectToRepo.graphql
graphql/tests/attachProjectToRepo/queries/badProject.graphql
graphql/tests/attachProjectToRepo/results.json
graphql/tests/detachProjectFromRepo/data.json
graphql/tests/detachProjectFromRepo/queries/badProject.graphql
graphql/tests/detachProjectFromRepo/queries/detachProjectFromRepo.graphql
graphql/tests/detachProjectFromRepo/results.json
model/project_ref.go
model/project_ref_test.go

[EVG-15043](https://jira.mongodb.org/browse/EVG-15043)
Added resolvers for this; discussed the return value with Mohamed and learned about the cache 😇 

EVG-15043 add attach/detach project mutation resolvers

---

model/event/subscriptions.go
model/event/task_event.go
model/event/task_event_test.go
public/static/js/task.js
trigger/payloads.go
trigger/task.go
trigger/task_test.go

[EVG-14593](https://jira.mongodb.org/browse/EVG-14593)
new trigger for notifications task-started
made a ticket for the front end portion
https://jira.mongodb.org/browse/EVG-15390
added to unit test

EVG-14593 Add new notification type for task started

---

units/host_drawdown.go

[EVG-5312](https://jira.mongodb.org/browse/EVG-5312)
Forgot to include this in the last PR.

EVG-5312 extend improvement to host drawdown

---

model/generate.go
model/project_parser.go
model/project_parser_merge_functions.go
repotracker/mock_poller.go
repotracker/repotracker.go
repotracker/repotracker_test.go

[EVG-14959](https://jira.mongodb.org/browse/EVG-14959)
Merging errors create a stub version now
added a unit test 
created one on staging 
https://evergreen-staging.corp.mongodb.com/version/sandbox_9db9a2dd3155a2f1145cca6fb9f16db4136513d4#/0

EVG-14959 Create stub versions for merging errors

---

operations/validate.go
self-tests.yml
service/api.go

[EVG-14958](https://jira.mongodb.org/browse/EVG-14958)
validate to use local read
include file doesn't exist
include file has duplicate build variant 
function doesn't exist
duplicate uncommitted file

EVG-14958 Verify validate project configs

---

graphql/resolvers.go

[EVG-15484](https://jira.mongodb.org/browse/EVG-15484)
Noticed some panics and wrongfully returned errors in a few places

EVG-15484 Fix panics and errors

---

model/project_ref.go
model/project_ref_test.go
model/repo_ref.go
rest/data/project.go
rest/data/project_test.go

[EVG-15355](https://jira.mongodb.org/browse/EVG-15355)
does not return on error while adding admins
unit test

EVG-15355 continue adding project admins on error

---

agent/agent_test.go
agent/background_test.go
agent/internal/client/mock.go
agent/internal/task_config_test.go
config.go
graphql/util.go
model/generate_test.go
model/lifecycle_test.go
model/matrix_smoke_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/project_parser.go
model/project_parser_test.go
model/testutil/api.go
operations/evaluate.go
operations/http.go
operations/list.go
operations/validate.go
repotracker/repotracker_test.go
rest/data/project.go
rest/data/version.go
rest/data/version_test.go
rest/route/version_create.go
service/api.go
service/rest_version.go
units/periodic_builds.go
validator/project_validator_test.go

[EVG-14960](https://jira.mongodb.org/browse/EVG-14960)
Update LoadProjectInto to take opts pointer
compiles

EVG-14960 Update LoadProjectInto to take opts pointer

---

model/event/subscriptions.go
rest/data/subscription_test.go

[EVG-15413](https://jira.mongodb.org/browse/EVG-15413)
Disallow jira comment subscriptions to all tasks in a project
unit test

EVG-15413 Hide jira comment subscription option on waterfall page

---

rest/data/commit_queue.go
rest/route/commit_queue.go

[EVG-15126](https://jira.mongodb.org/browse/EVG-15126)
I changed it to not return an internal error but I'm not sure if this is correct 

EVG-15126 Improve error message from /addtional patches route

---

gqlgen.yml
graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/project/queries/create-project.graphql
graphql/tests/project/results.json
rest/route/project.go

[EVG-15039](https://jira.mongodb.org/browse/EVG-15039)
This adds the CreateProject resolver. The design only shows it taking it name, owner, and repo. Should we be taking in a branch name as well? 
Tested locally in the playground and added a graphql test.

EVG-15039 Add a Create Project resolver

---

config.go
operations/admin_all_configs.go
operations/http.go
service/rest_version.go

[EVG-15583](https://jira.mongodb.org/browse/EVG-15583)
Only we can really use this but we should remove this flag now that it's not needed, since it could be expensive.

EVG-15583 remove all-configs fetch flag

---

model/github_hook.go
service/project.go

[EVG-15779](https://jira.mongodb.org/browse/EVG-15779)
Same PR that @malikchaya2 approved but without all the stuff that doesn't compile 🙃

EVG-15779 add logging when creating github hook (real)

---

rest/route/middleware.go

[EVG-15669](https://jira.mongodb.org/browse/EVG-15669)
wasn't sure what to do beyond adding a nil check

EVG-15669 Check for nil test

---

graphql/generated.go
graphql/schema.graphql
graphql/tests/spruceConfig/queries/defaultProject.graphql
graphql/tests/spruceConfig/results.json

[EVG-15783](https://jira.mongodb.org/browse/EVG-15783)
Spruce will use this default project to load the waterfall in case a project cookie does not exist in the client

EVG-15783: Resolve default project

---

graphql/schema.graphql
model/project_ref.go
model/project_ref_test.go

[EVG-15334](https://jira.mongodb.org/browse/EVG-15334)
In anticipation of a plugin component in the new UI, graphql resolver functions have been modified to accept a modification section for inputs on the plugin section on the frontend.
Added casing on plugin section to existing unit tests for testing save project by section.

EVG-15334: Add collection update for plugins section

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/saveProjectSettingsForSection/queries/generalSection.graphql
graphql/tests/saveProjectSettingsForSection/queries/varsSection.graphql
graphql/tests/saveRepoSettingsForSection/queries/generalSection.graphql
graphql/tests/saveRepoSettingsForSection/queries/varsSection.graphql
graphql/util.go
model/project_ref.go
rest/data/project_settings_test.go

[EVG-15828](https://jira.mongodb.org/browse/EVG-15828)
- Replace strings with enums for added type safety on the front end ahead of EVG-15642

EVG-15828: Replace strings with enums in save mutation

---

agent/command/archive_auto_extract.go
agent/command/archive_tarball_create.go
agent/command/archive_tarball_extract.go
agent/command/archive_zip_create.go
agent/command/archive_zip_extract.go
agent/command/attach_artifacts.go
agent/command/downstream_expansions_set.go
agent/command/expansion_update.go
agent/command/expansion_write.go
agent/command/generate.go
agent/command/git.go
agent/command/git_push.go
agent/command/git_test.go
agent/command/host_create.go
agent/command/host_list.go
agent/command/perf_send.go
agent/command/results_gotest.go
agent/command/results_native.go
agent/command/s3_get.go
agent/command/taskdata_get.go
agent/command/taskdata_history.go
agent/command/taskdata_send.go
agent/command/util.go
agent/command/util_test.go
config.go

https://jira.mongodb.org/browse/EVG-15829

EVG-15829 Fix join with workdir for absolute case

---

agent/command/s3_copy.go

This reverts commit 0ed2d109b634cf845ceaf31a37c696838ed84500.
Update posted in https://jira.mongodb.org/browse/EVG-15725

Revert "EVG-15725 Only add files if S3 Copy succeeded (#5189)"

---

model/project_ref.go

[EVG-15856](https://jira.mongodb.org/browse/EVG-15856)

EVG-15856 comment out parser project merge usage

---

model/project_ref.go
model/project_ref_test.go

[EVG-15856](https://jira.mongodb.org/browse/EVG-15856)
I need to start waiting for tests to pass 🤦‍♀️

EVG-15856 fix test

---

model/task/db.go
model/task/task.go
rest/model/task.go

[EVG-15154](https://jira.mongodb.org/browse/EVG-15154)
this isn't stored anywhere and is only used in the ui so doesn't need to be apart of the db struct

EVG-15154 remove ExecutionTasksFull fields from task type

---

model/task_lifecycle.go

[EVG-15765](https://jira.mongodb.org/browse/EVG-15765)
add a nil check for display task 
n/a

EVG-15765 Verify that display task is not nil

---

graphql/util.go

[EVG-15774](https://jira.mongodb.org/browse/EVG-15774)
This PR resolves the issue where it became impossible for users with elevated permissions to set the priority of their patch above `100` (max priority for a regular user).
Tested on staging by setting my own patch to have priority `999`:

EVG-15774 Respect admin permissions in SetPatchPriority resolver

---

apimodels/test_results.go
go.mod
go.sum

[EVG-15729](https://jira.mongodb.org/browse/EVG-15729)
The last step of the process: fetch the failed test samples on the evergreen side.

EVG-15729 get failed samples

---

graphql/generated.go
graphql/schema.graphql
graphql/tests/projectSettings/data.json
graphql/tests/projectSettings/queries/project-settings-project.graphql
graphql/tests/projectSettings/results.json

[EVG-15898](https://jira.mongodb.org/browse/EVG-15898)
Add field required for access settings page
- Tested in sandbox
- Added unit test

EVG-15898: Return restricted field

---

graphql/generated.go
graphql/tests/project/results.json
graphql/util.go
model/project_aliases.go
model/project_aliases_test.go
model/project_ref.go
model/project_ref_test.go
model/project_vars.go
model/project_vars_test.go
model/repo_ref.go
rest/data/project_settings_test.go
rest/model/project.go
rest/route/project.go
rest/route/project_test.go
rest/route/repo_test.go
service/project.go

[EVG-15852](https://jira.mongodb.org/browse/EVG-15852)
Remove the useRepoSettings and replace it with useRepoSettings() which checks the RepoRefId field. 
Existing tests should still pass.

EVG-15852 Remove useRepoSettings

---

model/host/db.go
units/provisioning_create_host.go

Jira: https://jira.mongodb.org/browse/EVG-15930
This is a follow on to [EVG-15022](https://jira.mongodb.org/browse/EVG-15022) (#5232).
The order of operations during host creation and agent startup _should_ be this:
provisioning-create-host job creates host that starts the agent on its own -> provisioning-create-host finishes -> agent checks in to next task
But in some cases appear to be this:
provisioning-create-host job creates host that starts the agent on its own -> agent checks in to next task -> provisioning-create-host finishes
The second order of operations means the provisioning-create-host job can race with the agent REST route to swap the intent host with the real host. particularly if the transaction takes a long time. I'm unsure why it takes a long time, but the Splunk logs …

EVG-15930: handle race between provisioning-create-host and agent

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
model/project_ref.go

[EVG-16015](https://jira.mongodb.org/browse/EVG-16015)
Given a new use case for created tickets, we need to check if there is a createTicketProject set up instead of checking if a webhook is configured. 
Tested locally

EVG-16015  Add  bbTicketCreationDefined to the task resolver 

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/ui_plugin_build_baron.go

[EVG-16015](https://jira.mongodb.org/browse/EVG-16015)
bbTicketCreationDefined is easier to use in when it's in BuildBaron than in Task.

EVG-16015 Move ticketCreationDefined

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/ui_plugin_build_baron.go

Reverts evergreen-ci/evergreen#5279

Revert "EVG-16015 Move ticketCreationDefined"

---

model/lifecycle.go
model/lifecycle_test.go

[EVG-15882](https://jira.mongodb.org/browse/EVG-15882)
https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#task-groups
these 4 params will overwrite the ones in project tasks 
unit test

EVG-15882 Update CreateTasksFromGroup to pass in params from project task

---

model/generate_test.go
model/lifecycle.go

[EVG-15855](https://jira.mongodb.org/browse/EVG-15855)
added build variant to test tasks to be able to find them 
test passes

EVG-15855 Update TestSaveNewTaskWithExistingExecutionTask

---

service/templates/admin.html

[EVG-15217](https://jira.mongodb.org/browse/EVG-15217)
Removing lingering plugin references on admin page.

EVG-15217 Remove plugins from sidebar and admin plugin flag from HTML

---

agent/agent_command_test.go
agent/command/s3_copy.go
agent/command/s3_copy_test.go
agent/internal/client/host_methods.go
agent/internal/client/interface.go
agent/internal/client/mock.go
agent/internal/client/pod_methods.go
config.go
model/push.go
self-tests.yml
service/api.go
service/api_plugin_s3copy.go

[EVG-15836](https://jira.mongodb.org/browse/EVG-15836)
This includes the previously merged and reverted s3copy fix, as well as a fix for the smoke test (the second commit). 
patch: https://spruce.mongodb.com/version/61dc5fdf850e6134cad323fc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

EVG-15836 Fix s3_copy with fixed smoke test

---

public/static/plugins/buildbaron/js/task_build_baron.js
public/static/plugins/buildbaron/partials/task_build_baron.html
service/ui.go
service/ui_plugin_build_baron.go

[EVG-16058](https://jira.mongodb.org/browse/EVG-16058)
Display tickets that were filed using the custom ticket api endpoint. 
Tested locally

EVG-16058 Display tickets filed with the created_tickets URL in the build baron

---

units/provisioning_create_host.go

Jira: https://jira.mongodb.org/browse/EVG-16041
The host could be moved from the "building" to the "starting" state by either the host creation job or the agent next task route, whichever one does the host doc replacement first. If the agent gets to it first, it'll log that the host is started, so the host creation job should not log that the host started a second time.

EVG-16041: deduplicate successful host start event logs

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql

[EVG-16008](https://jira.mongodb.org/browse/EVG-16008)

EVG-16008 Dependency returns STARTED for running task deps.

---

repotracker/repotracker.go
rest/data/commit_queue.go
service/api.go
units/commit_queue.go
units/patch_intent.go
validator/project_validator.go
validator/project_validator_test.go

[EVG-15927](https://jira.mongodb.org/browse/EVG-15927)
Refactor syntax and semantics validator groups into relevant error / warning groupings
Modified unit tests

EVG-15927 Refactor syntax and semantic validators

---

config.go
operations/export.go
operations/flags.go
operations/host_spawn.go
operations/patch_list.go

[EVG-14646](https://jira.mongodb.org/browse/EVG-14646)
Add option to print out list of hosts in json format.

EVG-14646 Add json option to evergreen host list

---

model/task_lifecycle.go

To help take over investigation of this, adding some logging (namely the dependency in question, and the stack trace). Also logging at a lower level.

EVG-12923 tweak single-host task group dependencies logging

---

agent/agent_command_test.go
agent/command/s3_copy.go
agent/command/s3_copy_test.go
agent/internal/client/host_methods.go
agent/internal/client/interface.go
agent/internal/client/mock.go
agent/internal/client/pod_methods.go
config.go
model/push.go
scripts/agent.yml
self-tests.yml
service/api.go
service/api_plugin_s3copy.go

Reverts evergreen-ci/evergreen#5306

Revert "EVG-15836 Fix s3_copy "

---

environment.go
go.mod
go.sum

Jira: https://jira.mongodb.org/browse/EVG-15931
Upgrade Amboy and update the refactored fields.
I tested that the remote queue and remote queue group was working as expected in staging.

EVG-15931: upgrade Amboy

---

agent/agent_command_test.go
agent/command/s3_copy.go
agent/command/s3_copy_test.go
agent/internal/client/host_methods.go
agent/internal/client/interface.go
agent/internal/client/mock.go
agent/internal/client/pod_methods.go
model/push.go
scripts/agent.yml
self-tests.yml
service/api.go
service/api_plugin_s3copy.go

[EVG-<number>](https://jira.mongodb.org/browse/EVG-<number>)

Evg 15836 rewrite

---

scripts/agent.yml

[EVG-16230](https://jira.mongodb.org/browse/EVG-16230)
This removes duplicate files because it breaks on the waterfall. 
existing test

EVG-16230 Improve smoke test for s3Copy without duplicates 

---

scripts/agent.yml

[EVG-16230](https://jira.mongodb.org/browse/EVG-16230)
This undoes the agent.yml improvements because it breaks the smoke test

EVG-16230  reset agent.yml

---

makefile
model/task/db.go
model/task/task.go
model/task/task_test.go
self-tests.yml

[EVG-15934](https://jira.mongodb.org/browse/EVG-15934)
aded hint to the query
query doesnt hang in shell

EVG-15934 Add hint to UnscheduleStaleUnderwaterTasks

---

makefile
model/task/db.go
model/task/task.go
model/task/task_test.go
self-tests.yml

This reverts commit c3dd1d6ce3bd305ee6a6f1f68d585f340f6fbc85.
[EVG-<number>](https://jira.mongodb.org/browse/EVG-<number>)

Revert "EVG-15934 Add hint to UnscheduleStaleUnderwaterTasks (#5345)"

---

model/task/db.go
model/task/task.go
model/task/task_test.go
scheduler/host_allocator.go
scheduler/scheduler.go
scheduler/task_finder.go
scheduler/task_finder_test.go
units/scheduler_alias.go

Reverts evergreen-ci/evergreen#5362

Revert "EVG-16170: only consider host tasks for the distro scheduler"

---

apimodels/agent_models.go
model/project_event_test.go
model/project_ref.go
model/project_vars.go
model/project_vars_test.go
public/static/js/projects.js
rest/data/project.go
rest/model/project_event.go
rest/route/project_copy.go
service/api.go
service/project.go
service/templates/projects.html

[EVG-16046](https://jira.mongodb.org/browse/EVG-16046)

EVG-16046 Add a New Variable Type for Admins Only

---

model/annotations/task_annotations.go
model/annotations/task_annotations_test.go
rest/model/task_annotations.go
rest/route/annotations.go
rest/route/annotations_test.go

[EVG-14185](https://jira.mongodb.org/browse/EVG-14185)
added the confidence score field in issue links stored in task annotations
unit tests

EVG-14185 Add confidence score field in task annotations

---

graphql/generated.go
graphql/schema.graphql
graphql/tests/projectSettings/data.json
graphql/tests/projectSettings/queries/project-settings-project.graphql
graphql/tests/projectSettings/results.json
graphql/tests/repoSettings/data.json
graphql/tests/repoSettings/queries/repo-settings-project.graphql
graphql/tests/repoSettings/results.json
graphql/tests/saveProjectSettingsForSection/data.json
graphql/tests/saveProjectSettingsForSection/queries/cqSection.graphql
graphql/tests/saveProjectSettingsForSection/queries/varsSection.graphql
graphql/tests/saveProjectSettingsForSection/results.json
graphql/tests/saveRepoSettingsForSection/data.json
graphql/tests/saveRepoSettingsForSection/queries/cqSection.graphql
graphql/tests/saveRepoSettingsForSection/results.json

[EVG-16257](https://jira.mongodb.org/browse/EVG-16257)
Add requireMerged to commitQueueParams and input.
Added to existing queries and added a mutation test.

EVG-16257 add require signed to graphql commit queue

---

repotracker/repotracker.go

[EVG-16209](https://jira.mongodb.org/browse/EVG-16209)
Remove logging that was committed by mistake 
none

EVG-16209 Remove some excessive logging

---

model/pod/pod.go

[EVG-16234](https://jira.mongodb.org/browse/EVG-16234)
RunningTask field was added, analogously with the host document.
None

EVG-16234: Add field for pods currently running task

---

units/data_cleanup_testresults.go

6 months TTL on testresults 

---

graphql/util.go

[EVG-16351](https://jira.mongodb.org/browse/EVG-16351)
I think i broke the conditional for the time calculation.

EVG-16351 Fix time comparison

---

model/project_ref.go
rest/data/project_settings_test.go

[EVG-16081 ](https://jira.mongodb.org/browse/EVG-16081 )
Third times the charm 🤞 
Added a line to verify this doesn't break anything

EVG-16081 remove resetting repoRefId for general page

---

model/task/db.go
model/task/task.go
model/task/task_test.go
scheduler/host_allocator.go
scheduler/scheduler.go
scheduler/task_finder.go
scheduler/task_finder_test.go
units/scheduler_alias.go

Reverts evergreen-ci/evergreen#5369

Revert "Revert "EVG-16170: only consider host tasks for the distro scheduler""

---

gqlgen.yml
graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/projectSettings/data.json
graphql/tests/projectSettings/queries/project-settings-vars.graphql
graphql/tests/projectSettings/results.json
model/project_vars.go
rest/model/project_event.go

[EVG-16406](https://jira.mongodb.org/browse/EVG-16406)
updated resolver to handle admin only variables with adminOnlyVarsList for the ui
graphql test
ran locally on spruce 
https://github.com/evergreen-ci/spruce/pull/1114

EVG-16406 Add adminOnlyVars to project resolver

---

model/host/host.go
units/host_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-16296
Log host events after the DB update itself has succeeded.
Not easily testable/worth testing.

EVG-16296: log host events after the DB update succeeds

---

graphql/generated.go
graphql/schema.graphql
graphql/tests/attachProjectToRepo/queries/attachProjectToRepo.graphql
graphql/tests/attachProjectToRepo/queries/badProject.graphql
graphql/tests/attachProjectToRepo/results.json
graphql/tests/detachProjectFromRepo/queries/badProject.graphql
graphql/tests/detachProjectFromRepo/queries/detachProjectFromRepo.graphql
graphql/tests/detachProjectFromRepo/results.json

[EVG-16081](https://jira.mongodb.org/browse/EVG-16081)
womp

EVG-16081 remove use repo settings from schema

---

units/data_cleanup_test_logs.go

Reverts evergreen-ci/evergreen#5411

Revert "EVG-16157 Change test logs TTL to 6 months"

---

units/data_cleanup_testresults.go

Reverts evergreen-ci/evergreen#5398

Revert "6 months TTL on testresults "

---

graphql/tests/projectSettings/results.json
service/templates/projects.html

[EVG-16048](https://jira.mongodb.org/browse/EVG-16048)
delete the hide

EVG-16048 Unhide admin only option

---

graphql/tests/projectSettings/results.json
service/templates/projects.html

Reverts evergreen-ci/evergreen#5427

Revert "EVG-16048 Unhide admin only option"

---

model/task/db.go
model/task/task.go
model/task/task_test.go

Reverts evergreen-ci/evergreen#5424

Revert "EVG-15934 Add hint to UnscheduleStaleUnderwaterTasks"

---

graphql/integration_atomic_test.go
graphql/resolvers.go
graphql/tests/projectSettings/data.json
graphql/tests/projectSettings/queries/project-settings-admin-private-vars.graphql
graphql/tests/projectSettings/results.json
service/templates/projects.html

[EVG-16048](https://jira.mongodb.org/browse/EVG-16048)
Delete ng-show 
var resolver now returns sorted list

EVG-16048 Unhide admin only vars in project page

---

rest/model/patch.go

[EVG-15393](https://jira.mongodb.org/browse/EVG-15393)
We get the `branchName` for patch code changes from `ModulePatch.ModuleName`, but it is usually empty. In this case we use the project ID for the `branchName`, but this often results in ugly project ID hashes: 
<p align="center">
</p>
This PR makes it so that we use the project identifier for the `branchName` instead.
<p align="center">
</p>
- Tested on staging (The images above are from staging)

EVG-15393: Use project identifier for patch code changes

---

config.go
operations/before.go
operations/commit_queue.go
operations/create_version.go
operations/evaluate.go
operations/export.go
operations/last_green.go
operations/model.go
operations/patch.go
operations/patch_finalize.go
operations/patch_module.go
operations/patch_util.go
operations/update.go
operations/validate.go

[EVG-6496](https://jira.mongodb.org/browse/EVG-6496)
When retrieving client settings, if autoupdate fails an error will no longer be returned.

EVG-6496 Do not let autoupdate ever return an error

---

graphql/resolvers.go
graphql/util.go
model/task/task.go
rest/data/task.go

[EVG-16339](https://jira.mongodb.org/browse/EVG-16339)
BuildVariantDisplayName will only get added to the GetTasksByVersion Pipeline if it is explicitly needed.

EVG-16339 Conditionally enable buildVariantDisplayName in query

---

go.mod
go.sum
units/host_termination.go

Jira: https://jira.mongodb.org/browse/EVG-16450

EVG-16450: upgrade utility

---

service/task.go
service/version.go

[EVG-16334](https://jira.mongodb.org/browse/EVG-16334)
show spruce link for not just patch tasks and versions

EVG-16334 Add spruce link to mainline tasks and versions

---

graphql/generated.go
graphql/schema.graphql

As part of UI ticket [EVG-15086](https://jira.mongodb.org/browse/EVG-15086)
- fix casing before it's too late

EVG-15086: Fix workstation config capitalization

---

service/api_task.go

Jira: https://jira.mongodb.org/browse/EVG-16494
We're still seeing hosts where we log that the EC2 TerminateInstances call succeeded and included the host in the list of hosts that are terminating, but the agent mysteriously starts requesting new tasks days later. This adds logging to see what IP address is checking in to help with investigation.
Logging change, didn't test it.

EVG-16494: log IP address for zombie terminated hosts

---

model/host/db.go
model/host/host.go
model/host/host_test.go

Jira: https://jira.mongodb.org/browse/EVG-16405
The spawn host notifications field seems like dead code, so I removed it.
N/A

EVG-16405: remove unused spawn host notifications field

---

agent/command/s3_get.go
agent/command/s3_get_test.go
agent/command/s3_put.go
agent/internal/task_config.go
agent/task.go
apimodels/agent_models.go
config.go
model/project_event_test.go
model/project_ref.go
model/project_ref_test.go
model/project_vars.go
model/project_vars_test.go
public/static/js/projects.js
rest/data/host_create.go
rest/data/project.go
rest/model/project_event.go
rest/route/project_copy.go
service/api.go
service/project.go
service/templates/projects.html

[EVG-16045](https://jira.mongodb.org/browse/EVG-16045)
deprecate restricted vars 
all existing tests pass

EVG-16045 Remove restricted variables

---

rest/data/project.go

[EVG-16368](https://jira.mongodb.org/browse/EVG-16368)
Need to add blank project variables in order for this button to be useable. 
Tested that a created project can be visited on Spruce, and tested that the copy project route still works.

EVG-16368 fix project creation for new project page

---

globals.go
model/project.go
model/project_parser.go
model/project_parser_db.go
model/project_parser_merge_functions.go
model/project_parser_test.go

[EVG-16423](https://jira.mongodb.org/browse/EVG-16423)
Added containers struct into parser projects detailing the data model detailed in the design doc for this epic.
Updated existing unit tests and created new test asserting correctness of container parsing.

EVG-16423 Define container models and integrate into parser project

---

db/db_utils.go
db/db_utils_test.go
go.mod
go.sum
graphql/directive_test.go
graphql/integration_atomic_test_util.go
model/pod/dispatcher/db_test.go
units/pod_allocator_test.go

Jira: https://jira.mongodb.org/browse/EVG-16402
Replace usages of `CreateCollection` in tests to use the Anser helper.
Replaced its usages in tests and added an idempotency test.

EVG-16402: add method to create collection

---

graphql/generated.go
graphql/schema.graphql

[EVG-16380](https://jira.mongodb.org/browse/EVG-16380)
Need this value for jump to commits on the history page

EVG-16380 Resolve task order number

---

graphql/generated.go
graphql/schema.graphql
graphql/tests/projectEvents/data.json
graphql/tests/projectEvents/queries/getBranch.graphql
graphql/tests/projectEvents/results.json
graphql/tests/projectSettings/queries/project-settings-project.graphql
graphql/tests/projectSettings/results.json
graphql/tests/repoEvents/data.json
graphql/tests/repoEvents/queries/getBranch.graphql
graphql/tests/repoEvents/results.json
graphql/tests/repoSettings/queries/repo-settings-project.graphql
graphql/tests/repoSettings/results.json
model/project_event.go
model/project_event_test.go
model/project_ref.go
rest/data/project_test.go
rest/model/project_event.go
rest/model/project_event_test.go
service/project.go

[EVG-16208](https://jira.mongodb.org/browse/EVG-16208)
This looked like a bug causing the event log data to be overwritten. However, it was an error with the data. 
Added vars to getBranch 
Added print statement to the GithubWebhooksEnabled resolver and made sure that they get called.

EVG-16208 Fix data and add vars to getBranch

---

model/task_lifecycle.go
units/check_blocked_tasks.go

1) Reduce logging by not logging entire stack trace.
2) Add some additional helpful logging info (task Ids, executions)

EVG-12923 update blocked dependencies logging

---

model/project_parser.go
model/project_parser_merge_functions.go
model/project_parser_test.go

[EVG-16479](https://jira.mongodb.org/browse/EVG-16479)
allow users to add tasks to bv before defining it in one of the include files
unit test

EVG-16479 Update merge logic for build variants

---

agent/internal/task_config.go
agent/internal/task_config_test.go
config.go

[EVG-15980](https://jira.mongodb.org/browse/EVG-15980)
This is the behavior we mention in the documentation so it's confusing to users.
Added to unit test.

EVG-15980 default task group timeout to project-level

---

graphql/util.go
model/patch/db.go
rest/model/patch.go

[EVG-15233](https://jira.mongodb.org/browse/EVG-15233)
Refactor fetching all child patches to use one query instead of many.

EVG-15233 refactor fetching all child patches

---

model/task/task.go

[EVG-16571](https://jira.mongodb.org/browse/EVG-16571)
This log shows up for stranded tasks but it's not really a problem that this is empty. I don't really see other cases so I don't think this log is really necessary. Also rearranged to be consistent between what we store locally and what we store in the DB.
Existing unit tests for this function succeed.

EVG-16571 remove empty task details log

---

graphql/resolvers.go

[EVG-15650](https://jira.mongodb.org/browse/EVG-15650)
Fix panic on host resolver.

EVG-15650 handle panic for host resolver

---

graphql/generated.go
graphql/schema.graphql

[EVG-15089](https://jira.mongodb.org/browse/EVG-15089)
For the sake of accuracy 
https://github.com/evergreen-ci/spruce/pull/1207

EVG-15089: Use RepoRef in RepoEventSettings

---

agent/command/shell.go
config.go

[EVG-16311](https://jira.mongodb.org/browse/EVG-16311)
Added a task debug log if the script was changed after expanding 
https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu1604_bynntask_patch_b14644c4918e0a8f632efe00e4d4e8ccc344b327_624cb29db237365d2511851e_22_04_05_21_20_48/logs?execution=1

EVG-16311 Add warning when using expansions in script

---

gqlgen.yml
graphql/generated.go
graphql/resolvers.go
rest/model/task.go
rest/route/build_task.go
rest/route/service_test.go
rest/route/status.go
rest/route/task.go
rest/route/task_abort.go
rest/route/task_project.go
rest/route/task_restart.go

[EVG-16732](https://jira.mongodb.org/browse/EVG-16732)
Move host ami lookup out of build from service

EVG-16732 Move host AMI lookup and project identifier lookup out of task build from service

---

model/annotations/db.go
model/annotations/task_annotations.go
model/annotations/task_annotations_test.go
rest/route/annotations.go
rest/route/service.go

[EVG-16099](https://jira.mongodb.org/browse/EVG-16099)
add patch route 
Note and Meta data field will be overwritten if it is specified in the body 
Issues will be added on 
unit test

EVG-16099 Add patch route for task annotations

---

operations/patch_util.go

[EVG-14888](https://jira.mongodb.org/browse/EVG-14888)
adds detail to error

EVG-14888 Update merge base error message

---

trigger/task.go

[EVG-16763](https://jira.mongodb.org/browse/EVG-16763)
Need to include task timed out for triggers.

EVG-16763 include task timed out in trigger failures

---

agent/command/shell.go
config.go

[EVG-16752](https://jira.mongodb.org/browse/EVG-16752)
remove faq and check for warning is fixed
https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu1604_bynntask_patch_b14644c4918e0a8f632efe00e4d4e8ccc344b327_625de82f97b1d30d902fc0e3_22_05_04_20_33_35/logs?execution=2

EVG-16752 Remove mention of evergreen faq

---

operations/http.go
rest/client/methods.go
rest/client/request.go
rest/route/middleware.go
rest/route/middleware_test.go

[EVG-16809](https://jira.mongodb.org/browse/EVG-16809)
We have a middleware that checks that commit queue submissions are being submitted by the author, which isn't true if the `--author` flag is used. However, that flag has restricted access so we should check if the user has that permission.
(PR also looks big bc I changed how we handle "Unauthorized" since it swallows real errors and can be confusing.)
Tested on staging using the same credentials that the code review bot uses, and added a unit test.

EVG-16809 check if user has patch submission permission

---

rest/data/repotracker.go

[EVG-16834](https://jira.mongodb.org/browse/EVG-16834)

EVG-16834 Don't error for invalid GitHub org

---

thirdparty/github.go

[EVG-16914](https://jira.mongodb.org/browse/EVG-16914)
Adding to tweak splunk alert to consider how much longer we have on the alert.

EVG-16914 add num minutes remaining to github alert

---

agent/command/git.go
config.go

[EVG-15976](https://jira.mongodb.org/browse/EVG-15976)
add warning log when applying fails
n/a

EVG-15976 Add warning when applying patch fails

---

agent/command/git_test.go

[EVG-15976](https://jira.mongodb.org/browse/EVG-15976)

EVG-15976 Fix test

---

rest/route/service.go
rest/route/task.go
rest/route/task_test.go

[EVG-6845](https://jira.mongodb.org/browse/EVG-6845)
checked splunk and saw that it hasn't been once at least in the last year so i deleted it 
no documentation to delete

EVG-6845 Remove project/{project_id}/versions/tasks route

---

public/static/app/common/ApiV2.js
public/static/app/common/constants.js

[EVG-16550](https://jira.mongodb.org/browse/EVG-16550)
the route was already removed 
deleting some references to it 
existing tests pass

EVG-16550 Remove references to deleted versions/tasks route

---

go.mod
go.sum
rest/route/middleware.go
units/host_monitoring_idle_termination.go
util/strings.go
util/strings_test.go

Jira: https://jira.mongodb.org/browse/EVG-17128
* Upgrade utility.
* Use utility library functions instead of util package functions.
N/A

EVG-17128: use utility functions

---

service/templates/projects.html

[EVG-17061](https://jira.mongodb.org/browse/EVG-17061)
It is currently misleading that container resource / secret configs have UI components on the project settings page despite the fact that they are not in use at this time.
I've created https://jira.mongodb.org/browse/EVG-17134 to track uncommenting this section from the HTML once we'd like to expose containerized tasks to users.

EVG-17061 Hide container configs until container tasks are available

---

graphql/resolvers.go
model/distro/db.go
model/distro/distro.go
rest/data/commit_queue.go
rest/model/commit_queue.go
rest/model/commit_queue_test.go
rest/model/distro.go
rest/model/distro_test.go
rest/model/notification.go
rest/route/distro.go
rest/route/notification.go
thirdparty/github.go
units/provisioning_setup_host.go

[EVG-17167](https://jira.mongodb.org/browse/EVG-17167)
Decided to do this in chunks to keep code reviews lil and arbitrarily chose these chunks because they interacted with each other. Considered making BuildFromService work differently entirely (i.e. return the API model rather than destructively modify it) but I do think this is what we're now used to and that would be a bigger change.
Also renamed Icecream to IceCream because my new computer has more aggressive green syntax squiggles and I must tame them. (Although this doesn't match the bson tags as well so if you want me to switch it back I'll get it)
Existing unit tests.

EVG-17167 simplify service fns for cq, distro, and notifications

---

rest/data/generate.go
rest/route/task_generate.go

[EVG-17163](https://jira.mongodb.org/browse/EVG-17163)
We don't really need to log this error here since we log to the task logs if there's actually a problem.

EVG-17163 remove error generating tasks log

---

cloud/ec2.go

This reverts commit 052858683dfe154adc59092971dc391557f65667.

Revert "Added gp3 to existing valid volume types (#5761)"

---

model/event/event_logger.go
model/event/host_event.go
model/event/host_event_test.go
model/task/task.go

[EVG-17215](https://jira.mongodb.org/browse/EVG-17215)
Looking for ways to improve restarts and this would drop a bunch of queries. @ybrill has okayed that this change has baked in.

EVG-17215 remove updateHostTaskExecutions

---

go.mod
go.sum

Jira: https://jira.mongodb.org/browse/EVG-17144
Upgrade Amboy to suppress debug logging when dispatch fails due to contention.

EVG-17144: upgrade Amboy

---

model/repo_ref.go
rest/route/repo_test.go

[EVG-17192](https://jira.mongodb.org/browse/EVG-17192)
This fix will only impact new repos; will tweak the data in staging to fix the current ones.

EVG-17192 fix repo permissions

---

model/user/db.go
model/user/user_test.go
rest/route/host.go

[EVG-17140](https://jira.mongodb.org/browse/EVG-17140)
This was causing issues for returning users, specifically the github user Id. 
Added a unit test for the db function.

EVG-17140  Remove user settings as part of offboarding job.

---

config.go
config_registry.go
config_splunk.go
config_test.go
model/host/hostutil.go
model/host/hostutil_test.go
rest/data/admin_test.go
rest/model/admin.go
rest/model/admin_test.go
rest/route/admin_test.go
rest/route/agent_test.go
rest/route/pod_agent.go
rest/route/pod_agent_test.go
service/api_status.go
service/templates/admin.html
testutil/config.go
units/provisioning_restart_jasper.go
units/provisioning_setup_host.go

[EVG-14471](https://jira.mongodb.org/browse/EVG-14471)
1. the admin events route was broken because of presto so i do a manual check now 
2. created a new splunkconfig struct to make it more similar to the other configs
3. it now saves splunk config as a separate document in the admin collection 
unit tests

EVG-14471 Fix admin events page

---

service/project.go

[EVG-17317](https://jira.mongodb.org/browse/EVG-17317)
Project settings page redirects to spruce
Event log redirects to project event log page

EVG-17317 Redirect to new ui for project settings

---

units/patch_intent.go

[EVG-16615](https://jira.mongodb.org/browse/EVG-16615)
Forgot to actually make a ticket to follow up on removing this :( but stumbled across it so adding to the original.

EVG-16615 remove getting merge base using github call

---

testdata/local/roles.json

[EVG-17281](https://jira.mongodb.org/browse/EVG-17281)
Depended on by https://github.com/evergreen-ci/spruce/pull/1382

EVG-17281: Test data for project settings access page e2e test

---

units/crons.go

Jira: https://jira.mongodb.org/browse/EVG-17370
For generate tasks jobs, use one queue per version instead of one queue for all versions. This improves the turnaround time for generate tasks jobs across versions because generate tasks in one version does not need to wait in line behind generate tasks jobs in another version.
Spot checked in staging that it behaved as expected.

EVG-17370: use one job queue per version for generate tasks

---

graphql/tests/saveProjectSettingsForSection/queries/generalSection.graphql
model/project_ref.go
model/project_ref_test.go

[EVG-17376](https://jira.mongodb.org/browse/EVG-17376)
- Verify GitHub owner appears in list of valid orgs when saving a project
- Add unit test, test in GraphQL playground

EVG-17376: Validate owner and repo

---

agent/util/subtree_windows.go
model/build_variant_history.go
model/push.go
model/task_history.go
model/task_log.go
model/task_queue.go
model/test_log.go
plugin/attach_plugin.go
plugin/plugin_ui.go
plugin/plugin_ui_test.go
scheduler/task_prioritizer.go

[EVG-16825](https://jira.mongodb.org/browse/EVG-16825)
Golang conventions specify that functions attached to structs not label with 'this'/'self'. This is a refactor for functions that currently use self to not.
Unit tests

EVG-16825 Rename self in functions attached to structs

---

agent/internal/client/base_client.go
agent/internal/client/host_client.go
agent/internal/client/host_methods.go
agent/internal/client/pod_methods.go
agent/internal/client/request.go
agent/internal/client/request_test.go
config.go

This reverts commit cc4ebed85d5d7138047b2b621c166c3fe9d920a8.
[EVG-<number>](https://jira.mongodb.org/browse/EVG-<number>)

Revert "Agent-side v2 upgrades (#5867)"

---

units/stats_amboy.go

Jira: https://jira.mongodb.org/browse/EVG-17456
Log job stats for queues in the queue group. I'm going to make a Splunk alert for queues that are unusually long.
Tested in staging that it works as expected.

EVG-17456: log remote queue group stats

---

CONTRIBUTING.md

Jira: https://jira.mongodb.org/browse/EVG-17559
Add file for external contributors.

EVG-17559: add CONTRIBUTING.md

---

graphql/generated.go
graphql/schema/types/volume.graphql
model/host/volume.go
rest/model/host.go

[EVG-17484](https://jira.mongodb.org/browse/EVG-17484)
- Add `Migrating` field to volumes to be used as a flag when the volume is migrating
- Queried a volume via GraphQL playground and successfully returned the field as `false`

EVG-17484: Add migrating field

---

self-tests.yml

[EVG-17462](https://jira.mongodb.org/browse/EVG-17462)
Move the `activate: false` to the correct place.

EVG-17462 activate: false correctly

---

model/task/task.go

[EVG-17555](https://jira.mongodb.org/browse/EVG-17555)
add IsRestartFailedOnly that checks ResetFailedWhenFinished is true and ResetFailedWhenFinished is false
N/A

EVG-17555 Add failed only check function

---

agent/command/git.go
agent/internal/client/base_client.go
config.go
rest/data/commit_queue.go
rest/route/commit_queue.go

[EVG-15126](https://jira.mongodb.org/browse/EVG-15126)
internal error would make us retry 
not sure how to test

EVG-15126 Return error 400 for additional patches route

---

service/templates/task_perf_data.html

[EVG-17643](https://jira.mongodb.org/browse/EVG-17643)
🤞

EVG-17643 remove perf sample check

---

model/pod/db.go
model/pod/db_test.go
units/crons.go
units/crons_remote_five_minute.go
units/pod_creation_test.go
units/pod_health_check.go
units/pod_health_check_test.go
units/pod_termination.go
units/pod_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-16884
Add job to check pod health when it has not had any communication recently.
Added unit tests for job.

EVG-16884: add pod health check job

---

model/patch_lifecycle.go
repotracker/repotracker.go
rest/data/commit_queue.go
rest/route/github.go
thirdparty/github.go
units/commit_queue.go
units/github_status_api.go

[EVG-17205](https://jira.mongodb.org/browse/EVG-17205)
Add logging to usages of grip's status sender to augment our Github logging. Also removed a repeated function.

EVG-17205 add logging to grip calls

---

public/static/js/task_timing.js

[EVG-17232](https://jira.mongodb.org/browse/EVG-17232)
Add redirects for task_timing page.
Tested on staging.

EVG-17232 add redirects to task_timing

---

rest/route/project_copy.go
rest/route/project_copy_test.go

[EVG-17971](https://jira.mongodb.org/browse/EVG-17971)
Extending this behavior will be really useful for setting up repos.
Added a unit test and will test locally.

EVG-17971 extend copy variables route to handle repos

---

model/task/db.go
model/task/task.go
units/generate_tasks.go

[EVG-16617](https://jira.mongodb.org/browse/EVG-16617)
Removing unused GeneratedJSON task field since GeneratedJSONAsString has replaced GeneratedJSON and old task generators don't get picked up anymore by Amboy.

EVG-16617 Remove GeneratedJSON from task

---

trigger/build.go
trigger/commit_queue.go
trigger/host.go
trigger/host_spawn.go
trigger/host_spawn_test.go
trigger/patch.go
trigger/payloads.go
trigger/process.go
trigger/project_triggers.go
trigger/task.go
trigger/task_jira.go
trigger/version.go
trigger/volume.go

Jira: https://jira.mongodb.org/browse/EVG-16501
This is the last one, I promise!
Update error message style in trigger package.

EVG-16501: clean up error message style in trigger package

---

units/task_monitor_execution_timeout.go

Jira: https://jira.mongodb.org/browse/EVG-17644
This is some pre-work to log how often and for which reasons `host.FindStaleRunningTasks` (the expensive query) detects a task that `task.ByStaleRunningTask` does not. This will be helpful in assessing which of the calls to `host.FindStaleRunningTasks` can possibly be removed immediately, and whether or not the follow-up code changes I'm going to make can obviate all usages of this query.
Not that important for a temporary logging change.

EVG-17644: log when FindStaleRunningTasks detects unique stale task

---

rest/data/task.go

[EVG-17897](https://jira.mongodb.org/browse/EVG-17897)
verify that it wasnt logging on splunk

EVG-17897 Remove debug from EVG-17338

---

service/host.go

[EVG-17503](https://jira.mongodb.org/browse/EVG-17503)
Link to new ui for host pages

EVG-17503 Add link to new ui on legacy host pages

---

graphql/testdata/user.graphql

[EVG-<18000>](https://jira.mongodb.org/browse/EVG-18000)
This fixes a test

EVG-18000 Fix user test 

---

rest/data/project_settings_test.go

[EVG-18086](https://jira.mongodb.org/browse/EVG-18086)
- Fix failing test in `rest/data/project_settings_test.go` by clearing the correct event log collection

EVG-18086: Fix failing rest/data test

---

units/task_monitor_execution_timeout.go

Jira: https://jira.mongodb.org/browse/EVG-17644
This removes 2 of the 3 expensive queries from the task execution timeout which seem to do nothing. From Splunk logs over a couple weeks, it seems like these removed queries never find a task that the later (cheap) query doesn't already get.
The last expensive query that I didn't remove seems to find unique tasks every so often, but I believe it _may_ be unnecessary because the stale heartbeat job seems to no-op with those tasks. To be on the conservative side, I'm going to leave the last one in until I have enough data to be sure that the last query can be removed.
* Remove unused expensive queries.
* Add logging to the stale heartbeat job to make it more traceable and know when/why it decides to no-op.

EVG-17644: remove unused portions of expensive stale heartbeat query

---

config.go
operations/admin.go
operations/admin_all_configs.go
operations/agent_monitor.go
operations/cli_integration_test.go
operations/commit_queue.go
operations/commit_queue_test.go
operations/create_version.go
operations/fetch.go
operations/host_provision.go
operations/host_spawn.go
operations/http_test.go
operations/keys.go
operations/last_green.go
operations/list.go
operations/model.go
operations/notification.go
operations/patch.go
operations/patch_cancel.go
operations/patch_finalize.go
operations/patch_list.go
operations/patch_module.go
operations/pull.go
operations/scheduler.go
operations/subscriptions.go
operations/update.go
operations/validate.go
rest/client/client.go
rest/client/client_test.go
rest/client/methods.go

Jira: https://jira.mongodb.org/browse/EVG-12865
Require the API server URL when using the REST client for the CLI.
Added test for passing API server URL to constructor.

EVG-12865: check API server host is provided for REST client

---

go.mod
go.sum

Jira: https://jira.mongodb.org/browse/EVG-17378
Upgrade Amboy to d43fb169e5cadbe982799f8fa8a30600bc4197b4.
N/A

EVG-17378: upgrade Amboy

---

cloud/pod_util.go
go.mod
go.sum
rest/route/sns.go
units/pod_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-17270
Upgrade Cocoa and fix existing struct/function/method names for refactor.
N/A

EVG-17270: upgrade Cocoa

---

go.mod
go.sum

Add hint for Amboy next query since the query planner is using an inefficient index.
Hopefully this just works?

Upgrade Amboy to include next query hint

---

cloud/pod_util.go
cloud/pod_util_test.go
go.mod
go.sum
model/pod/definition/definition.go
model/project_ref.go
units/container_secret_cleanup.go
units/container_secret_cleanup_test.go
units/pod_definition_cleanup.go
units/pod_definition_cleanup_test.go
units/pod_definition_creation_test.go

Jira: https://jira.mongodb.org/browse/EVG-17516
Upgrade Cocoa for tag refactor and fix affected code.
Existing tests should pass.

EVG-17516: upgrade Cocoa

---

model/project.go
units/patch_intent.go
units/patch_intent_test.go

[EVG-18034](https://jira.mongodb.org/browse/EVG-18034)
taskgroups werent being taken into account for --repeat-failed 
unit testing 
staging 
https://spruce-staging.corp.mongodb.com/patch/633f44e397b1d3368cc303be/configure/tasks

EVG-18034 Add taskgroup tasks to get tasks by variant

---

agent/command/exec.go
agent/command/shell.go
config.go

[EVG-18203 ](https://jira.mongodb.org/browse/EVG-18203 )
Only log if there's actually an error.

EVG-18203 remove erroneous command error logging

---

model/project_parser.go
service/admin.go

[EVG-18349](https://jira.mongodb.org/browse/EVG-18349)
admin page no longer crashes

EVG-18349 Fix Parser Project panic on admin page

---

graphql/mutation_resolver.go
graphql/tests/editSpawnHost/data.json
graphql/tests/editSpawnHost/queries/error-add-key-spawn-host.graphql
graphql/tests/editSpawnHost/results.json

[EVG-18115](https://jira.mongodb.org/browse/EVG-18115)
only allow key adding if host status is running
graphql test

EVG-18115 Validate host status before adding ssh key

---

graphql/mutation_resolver.go
graphql/tests/editSpawnHost/results.json

EVG-18115 Fix GraphQL test

---

environment.go
go.mod
go.sum
migrations/anser.go
units/host_drawdown_test.go
units/host_monitoring_idle_termination_test.go
units/provisioning_create_host.go

Jira: https://jira.mongodb.org/browse/EVG-16651
* Upgrade Amboy.
* Fix tests that rely on toy queue implementation.
* Remove unused option to order the remote queue.

EVG-16651: upgrade Amboy

---

go.mod
go.sum

[EVG-18240](https://jira.mongodb.org/browse/EVG-18240)
Update amboy to get the changes from https://github.com/mongodb/amboy/commit/3b8bb747721c2f8181de2424e2cc5377930d9bbf

EVG-18240 update amboy

---

util/webhook_grip.go
util/webhook_grip_test.go

[EVG-17448](https://jira.mongodb.org/browse/EVG-17448)
The changes in #6089 have a bug that retries have an empty body. The reason for this is that the body of the request is a reader that gets advanced to the end the first time we send the request. This PR moves making the request so that it gets made anew for each retry.

EVG-17448 reset webhook request between retries

---

go.mod
go.sum

[EVG-18240](https://jira.mongodb.org/browse/EVG-18240)
#6114 was reverted because the amboy changes had a bug. 
The bug was fixed in https://github.com/mongodb/amboy/pull/309 so this will try again with that.

EVG-18240 update amboy again

---

trigger/patch.go

[EVG-14528](https://jira.mongodb.org/browse/EVG-14528)
Fix panics 
reasoned about it

EVG-14528 fix panics 

---

model/lifecycle_test.go
model/task/task.go
model/task/task_test.go

[EVG-16746](https://jira.mongodb.org/browse/EVG-16746)
execution tasks are now updated with display task
staging https://spruce-staging.corp.mongodb.com/version/638a617097b1d375e8784289/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
unit tests

EVG-16746 Disable execution tasks with display task

---

trigger/version.go

[EVG-14528](https://jira.mongodb.org/browse/EVG-14528)
Tying up loose ends

EVG-14528: Check event type in version completion triggers 

---

graphql/tests/projectSettings/data.json
graphql/tests/projectSettings/results.json
graphql/tests/repoSettings/data.json
graphql/tests/repoSettings/results.json
rest/data/subscription.go

[EVG-18546](https://jira.mongodb.org/browse/EVG-18546)
This conversion will no longer be needed after the spruce pr linked is merged. 
Existing tests 
[1574](https://github.com/evergreen-ci/spruce/pull/1574)

EVG-18546 Remove outcome to family-outcome conversion 

---

units/host_monitoring_external_termination.go
units/host_monitoring_external_termination_test.go

Jira: https://jira.mongodb.org/browse/EVG-18388
`GetInstanceStatus` will return `cloud.StatusNonExistent` if the host never existed or it has been terminated for so long that the cloud provider has no info on it anymore. In this case, we treat a nonexistent host as an externally-terminated one.

EVG-18388: handle nonexistent hosts during external termination check

---

validator/project_validator.go
validator/project_validator_test.go

[EVG-18502](https://jira.mongodb.org/browse/EVG-18502)
we werent checking task groups when validating projects
unit tests

EVG-18502 Update validate build variant fields to handle task groups

---

graphql/generated.go
graphql/schema/types/task.graphql
rest/model/task.go

[EVG-12434](https://jira.mongodb.org/browse/EVG-12434)

EVG-12434 Expose ResetWhenFinished field

---

model/project_ref.go
model/project_ref_test.go

[EVG-18191](https://jira.mongodb.org/browse/EVG-18191)
limit was off by 1
staging and unit test

EVG-18191 Fix off by one for get tasks by project limit

---

graphql/generated.go
graphql/schema/types/project.graphql
graphql/schema/types/repo_ref.graphql
graphql/tests/projectSettings/queries/project-settings-project.graphql
graphql/tests/projectSettings/results.json
graphql/tests/repoSettings/queries/repo-settings-project.graphql
graphql/tests/repoSettings/results.json
graphql/tests/saveProjectSettingsForSection/queries/cqSection.graphql
graphql/tests/saveProjectSettingsForSection/results.json
graphql/tests/saveRepoSettingsForSection/queries/cqSection.graphql
graphql/tests/saveRepoSettingsForSection/results.json
model/project_ref.go
rest/model/project.go
rest/route/github.go
thirdparty/github.go

[EVG-18766](https://jira.mongodb.org/browse/EVG-18766)
This adds a project setting that checks if a PR got a certain amount of reviewers. This is still missing the front end. Currently, if a setting is changed on the commit queue page, the number of required reviewers is reset to 0. I will check to make sure this is fixed when working on the front end. 
Tested on staging with different variations.

EVG-18766 Add Required Reviewers to Commit Queue Project Settings 

---

agent/agent.go
config.go

[EVG-17939](https://jira.mongodb.org/browse/EVG-17939)
change the context to cancel in heartbeat because it was not ending before
tested on staging to make sure timeout works
https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu1604_bynntask_patch_7ac7bc95d6b92fe95e934a1859792407acf40be9_63d0ad1e9dbe3232f3912bcf_23_01_25_04_16_40/logs?execution=0

EVG-17939 Update agent to cancel heartbeat correctly

---

model/project_ref.go
rest/data/project_settings.go

[EVG-18856](https://jira.mongodb.org/browse/EVG-18856)
update to not use cached config
also update to not error if config isnt set 
staging

EVG-18856 Update SaveProjectPageForSection to not use cached config

---

model/task_lifecycle.go

[EVG-17306](https://jira.mongodb.org/browse/EVG-17306)
Added a log line I would like for future investigating.

EVG-17306 augment stranded host logging

---

model/generate.go
model/project.go
model/project_parser.go

[EVG-18294](https://jira.mongodb.org/browse/EVG-18294)
This field isn't documented anywhere and isn't used except for functions that check non-empty.

EVG-18294 remove push from parser project

---

model/task_lifecycle.go
rest/route/host_agent.go

[EVG-18685](https://jira.mongodb.org/browse/EVG-18685)
delete CheckAndBlockSingleHostTaskGroup because it's not needed anymore 
existing tests pass 
no

EVG-18685 Delete CheckAndBlockSingleHostTaskGroup

---

agent/internal/client/base_client.go
agent/internal/client/host_methods.go
agent/internal/client/pod_methods.go
config.go
rest/client/methods.go
rest/client/request.go
util/http.go

[EVG-<number>](https://jira.mongodb.org/browse/EVG-<number>)
< if yes then where >

EVG-18931 Move RespErrorf from utility to util

---

docs/pull_request_template.md

This is trivial, but the random whitespaces were bothering me.

Trim trailing whitespace from PR template

---

graphql/generated.go
graphql/schema/types/task.graphql
graphql/task_resolver.go
graphql/tests/pods/data.json
graphql/tests/task/data.json
graphql/tests/task/queries/pod.graphql
graphql/tests/task/results.json

EVG-19015
Adds a resolver for task.pod if a task is running on a container
Unit tests
No

EVG-19015 Add Task.pod graphql resolver

---

units/event_send.go

EVG-18931
add grip logging of what were sending in event send job

EVG-18931 Add debug statement for github status issue

---

graphql/generated.go
graphql/host_resolver.go
graphql/schema/types/host.graphql
graphql/tests/host/data.json
graphql/tests/host/queries/ami.graphql
graphql/tests/host/results.json

EVG-5829
Exposes the AMI field for hosts

EVG-5829 Expose AMI field for hosts

---

model/project_matrix.go
model/project_parser_storage.go

EVG-18701
I added some logging based on my end-to-end testing that I think will be helpful for debugging any future issues. Also fixed a spelling mistake I noticed while testing.
N/A
N/A

EVG-18701: add log when parser project is first put in S3

---

units/event_send.go

EVG-18931
adding more discussion as we discussed

EVG-18931 Add more debugging to event send

---

graphql/mutation_resolver.go

EVG-19109
fix panic accessing nil volume in error

EVG-19109 fix panic accessing nil volume

---

units/github_status_refresh.go

EVG-19136 improve refresh comment logging

---

util/webhook_grip.go

[EVG-19138](https://jira.mongodb.org/browse/EVG-19138)
We're looking to get more insight on whether we're actually succeeded in sending webhooks and what the response is when we send it. 
N/A
N/A

EVG-19138 add webhook explicit success logging

---

go.mod
go.sum

EVG-19145
Upgrade `grip` to support improved error handling for the notification senders.
N/A
N/A

EVG-19145: upgrade grip

---

graphql/generated.go
graphql/schema/types/project.graphql
graphql/schema/types/repo_ref.graphql
graphql/tests/projectSettings/queries/project-settings-project.graphql
graphql/tests/projectSettings/results.json
graphql/tests/repoSettings/queries/repo-settings-project.graphql
graphql/tests/repoSettings/results.json
graphql/tests/saveProjectSettingsForSection/queries/cqSection.graphql
graphql/tests/saveProjectSettingsForSection/results.json
graphql/tests/saveRepoSettingsForSection/queries/cqSection.graphql
graphql/tests/saveRepoSettingsForSection/results.json
model/project_ref.go
rest/data/commit_queue.go
rest/model/project.go
thirdparty/github.go

[EVG-18885](https://jira.mongodb.org/browse/EVG-18885)
Now that we check to make sure that all branch protection rules are met, users that want signed commits or required approvals to be enforced should set them in branch protections, not in project settings.
Existing tests.
Yes

EVG-18885 Remove Require Signed and Require Approval 

---

model/user/user.go
service/templates/projects.html

EVG-19236
The html page wasn't included in the last PR so i updated 
Also added comment to HasProjectCreatePermission
n/a
no

EVG-19236 Fix legacy project page

---

rest/route/github.go
rest/route/github_test.go

EVG-15417 fix merge conflict

---

graphql/tests/githubProjectConflicts/data.json
model/project_ref.go
model/project_ref_test.go
model/repo_ref.go

EVG-19245
We were still trying to read enabled from the repo projects for some functions so i deleted that 
staging 
no

EVG-19245 Remove reading merged enabled from repo refs

---

thirdparty/github.go
units/patch_intent.go

EVG-18975 
Because we're moving to using Github apps, can't just check if the bot is a member of the organization. Instead, check all installed apps for the org and return true if it's the right permission.
Can't think of a good way to test end-to-end but [verified the Github API call and shape via Splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen-staging%20%22EVG-18975%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=1679588520&latest=1679590337&workload_pool=standard_perf&sid=1679591196.2404273).
Will see if we have any documentation about bot users; if not will add a stack overflow for it.

EVG-18975 check if PR submitted by installed app

---

config.go
docs/Commit-Queue.md
operations/commit_queue.go

EVG-18152
Add clarity to commit queue item and fixed some squiggles around function comments.
Yes and added!

EVG-18152 add clarity to commit queue item flag

---

units/pod_health_check.go

EVG-19274
Temporarily downleveling this to reduce noise when filtering `metadata.level >= 70` in staging since we're aware of this issue.
N/A

EVG-19274 Downlevel ECS Pod LatestStatusInfo failures to warning level

---

graphql/generated.go
graphql/mutation_resolver.go
graphql/schema/mutation.graphql
graphql/tests/mutation/setAnnotationMetadataLinks/queries/setAnnotationMetadataLinks.graphql
rest/model/task_annotations.go
rest/route/annotations.go

EVG-18937
Made more sense to call metadataLinks from the ui instead of an api esque value

EVG-18937 Rename apiMetadataLinks to metadataLinks

---

go.mod
go.sum

EVG-19268 Update Grip

---

model/patch/patch.go
trigger/version.go

EVG-19227
More context provided in ticket comment -- basically wanted to log this circumstance to see when/why it happens. Also fixed a bug with declaring a new variable in an if statement.

EVG-19227 introduce logging for notification color bug

---

docs/02-Test with Evergreen/01-Configure a Project/01-Project-Configuration-Files.md

Add an example re this discussion https://mongodb.slack.com/archives/C0V896UV8/p1681319015985999

docs: add multiple args example to function

---

model/task/expected_duration.go
model/task/expected_duration_test.go
model/task/task.go

EVG-19293
After introducing some logging for EVG-19293, looking for ways to improve this. Remove unnecessary function.

EVG-19293 only compute standard deviation when needed

---

service/api.go

EVG-19619
add nil check for projectRef
staging 
called api without panic

EVG-19619 Add nil check for projectRef

---

config.go
operations/before.go

EVG-17975
Remove now-dead function.
N/A
N/A

EVG-17975: fix lint-operations

---

rest/data/commit_queue.go

EVG-19680
Logging the state of PRs we try to merge will help us with debugging.

EVG-19680 Add logging for PR mergable state 

---

trigger/task_jira.go

EVG-19768
Ticket creation not working for MHOUSE with "request failed. Please analyze the request body for more details. Status code: 400". Adding some logging to see this issue better (and will add some logging to grip to try and include the response).

EVG-19768 add some logging to ticket creation

---

go.mod
go.sum

EVG-19768
Upgrade grip to improve our jira logging (don't actually need this anymore to diagnose this ticket but will likely help overall).

EVG-19768 upgrade grip

---

model/lifecycle.go
model/project.go
model/project_test.go

EVG-19707
these 2 functions were doing the same thing so we made them the same function
added some nil checks
existing tests pass

EVG-19707 Consolidate GetSpecForTask and FindProjectTask

---

go.mod
go.sum

EVG-19819 Update utility library

---

rest/data/commit_queue.go

EVG-19827
add logging to see how often this happens
will be deleted after investigation

EVG-19827 Add logging to refresh in commit queue

---

units/pod_termination.go
units/pod_termination_test.go

EVG-19884
Some pods were found to be in a decommissioned state with a task still specified in their `TaskRuntimeInfo`, but the task was marked as deallocated, preventing the termination job from succeeding, saying `cannot deallocate a container task if it's not currently allocated` ([logs](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22evergreen-staging%22%20%22cannot%20deallocate%20a%20container%20task%20if%20it%27s%20not%20currently%20allocated%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-30d%40d&latest=now&sid=1684167348.432188)).
While the root cause that allowed this bad state to happen was likely fixed by this [PR](https://github.com/evergreen-ci/evergreen/pull/6426) (these were old pods erroring), …

EVG-19884 No-op stranded container task cleanup if task is already deallocated

---

docs/Project-Configuration/Project-and-Distro-Settings.md

Fix docs that talk about buttons to click in Spruce.

docs: fix project trigger instructions

---

config.go
operations/commit_queue.go

EVG-18078
Tweak the backport help text a bit. 
We have this documented already; vetted this for clarity and I think it's fine.

EVG-18078 clarify the backport command

---

graphql/generated.go
graphql/schema/types/project_settings.graphql
graphql/tests/mutation/saveProjectSettingsForSection/queries/views_and_filters_section.graphql
graphql/tests/mutation/saveProjectSettingsForSection/results.json
model/project_ref.go
model/project_ref_test.go

EVG-19876
- Save project health view setting when Views & Filters page is updated
- Add field to save unit test
N/A

EVG-19876: Save project health view

---

self-tests.yml

EVG-20003 
Now that containers zooms, would be helpful to have dist-staging on here. Will test in the PR patch. Is patch-only bc it's in the task definition.

EVG-20003 add dist-staging to container variant

---

graphql/generated.go
graphql/mutation_resolver.go
graphql/schema/mutation.graphql
graphql/tests/mutation/deleteSubscriptions/data.json
graphql/tests/mutation/deleteSubscriptions/queries/success.graphql
graphql/tests/mutation/deleteSubscriptions/results.json

EVG-19999
- Add mutation to delete subscriptions with IDs passed to the resolver. This will facilitate deleting selected subscriptions in EVG-19904.
- Add unit test
N/A

EVG-19999: Add DeleteSubscriptions mutation

---

rest/route/patch.go

EVG-20063
The issue of getting 500s from `/patches/{patch_id}/configure` is still ongoing, but interestingly enough, none of the logs in the route handler actually logged when we repro'd the issue, which makes me think that the error is happening before the route handler even runs. I added more logs to see if it's an error in parsing (I'm also a bit doubtful of this).
If this doesn't log in the next deploy, the only thing I can think is it must be an issue in the auth middleware, but I don't see a place in the middleware where it would return 500, nor could I reproduce it (I tried the route with my user credentials and my own patch, but it had no issue authing me).

EVG-20063: add more debug logs

---

rest/route/github.go

EVG-19734
Re discussion in https://mongodb.slack.com/archives/G979SL0HM/p1686334591674529, sometimes it seems like Github doesn't send us push events when they should, so we don't run the repotracker for the version until after the push event. Reordering these hopefully will allow us to have the version ready to put a tag on (assuming that [this job](https://github.com/evergreen-ci/evergreen/blob/94d9e76fe8c3ff742603f9bbde62d06fe9a690d4/rest/route/project.go#L586) gets processed fast enough)
Wasn't really able to replicate this since the events came in the right order when I pushed them together https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen-staging%20push%209cd8a2532bcddf58369aa82eb66ba88e2323c056%20%22github%20hook%22&display.page.search.mode=verbose …

EVG-19734 preemptively run repotracker for git tag pushes

---

docs/Project-Configuration/Commit-Queue.md

docs: Update commit queue force flag docs

---

go.mod
go.sum

EVG-19189
Upgrade grip to get the changes from https://github.com/mongodb/grip/pull/146.
I'll merge this as soon as the tests pass.

EVG-19189 upgrade grip

---

agent/command/git.go
agent/command/git_test.go
agent/internal/task_config.go
config.go
docs/decisions/2023-06-05_github_merge_queue.md

(cherry picked from commit 0631a28c986b7a268d395523c7037ee6ed4108b5)
EVG-20076
This PR is a cherry pick of a previously opened PR. I opened it to double-check
that tests pass before merging.

EVG-20076 Clone for GitHub merge queue (closes #6667)

---

config.go
environment.go

EVG-18855
adds function comment to clarify when each funciton should be used

EVG-18855 Clarify difference between Settings() and GetConfig()

---

config.go
config_auth.go
rest/model/admin.go
service/templates/admin.html
thirdparty/github.go

EVG-20103
moving default owner and repo to admin settings 
works on staging

EVG-20103 Add default owner and repo for github app to admin settings

---

model/task/task.go

EVG-20120
Catch self-edge and log the stack and some info to understand what happened here. Will add an alert on the function name.

EVG-20120 catch panic from adding self-edge

---

go.mod
go.sum

[EVG-20337](https://jira.mongodb.org/browse/EVG-20337)
Updating gimlet to get the changes from https://github.com/evergreen-ci/gimlet/pull/154.
If/when the build succeeds (mod the smoke tests since they're broken) I'll merge.
Hopefully tests pass.

EVG-20337 update gimlet

---

model/task/task.go

EVG-20120
Kim noticed that this was logging all the time and not just when there's an error.

EVG-20120 log panic only in case of error

---

model/task/db.go

EVG-20372
this was causing a panic so we added a len check

EVG-20372 Add len check to GetTaskStatusesByVersion

---

config.go
units/patch_intent_test.go

EVG-20406
surfacing an error and adding a debug to investigate a bug

EVG-20406 Add debug lines for CreateInstallationToken

---

agent/agent.go
config.go

EVG-20311
This removes the LOOP label because just continue keyword does the same thing.

EVG-20311 Remove agent loop labels

---

agent/command.go
agent/command_test.go

Reverts evergreen-ci/evergreen#6798

Revert "EVG-20276  Unset function vars after the function is done "

---

agent/util/subtree_unix_test.go

EVG-20525
This test is very occasionally flaky, most likely because the processes are starting in the background, but the test needs the processes being running before checking the PIDs. I fixed this timing issue by polling for the desired PIDs rather than checking them once.
Ran the test hundreds of times on my computer with the race detector enabled. If we never see this test flake again on the waterfall, we can assume it's fixed.
N/A

EVG-20525: fix flaky PID detection test

---

docs/Project-Configuration/Task_Traces.md

[EVG-19251](https://jira.mongodb.org/browse/EVG-19251)
https://github.com/evergreen-ci/evergreen/pull/6844 fixed some things in the trace doc. There were issues with the Python code that this fixes.

EVG-19251 fix trace doc fixes

---

model/version.go
rest/route/task_project.go

EVG-20130
Add a few small fields to the project versions route, and artifacts to the project tasks route.

EVG-20130 add fields to rest routes

---

docs/Project-Configuration/Project-and-Distro-Settings.md

EVG-19225
just making it more clear to go on the ui

docs: Update periodic builds doc

---

config_jira.go
config_test.go
rest/model/admin.go
service/templates/admin.html

EVG-19814
add email field for jira admin settings
tested on local evergreen and unit test

EVG-19814 Add JIRA email to admin settings

---

docs/Project-Configuration/Project-Configuration-Files.md

Fix link name to the correct header.

docs: fix links to dependency override hierarchy

---

self-tests.yml

EVG-20653
This adds unset_function_vars to self-tests  so that we can use it as an example.

EVG-20653 Add unset_function_vars to self-tests 

---

units/patch_intent.go

EVG-20666
All the github functions already have a fallback built in so having a fallback at this level just duplicates it and makes logging more noisy 
went through every function that passed in the token and made sure there weren't any uses that relied on falling back here 
also tested that patches are made and finalized on staging

EVG-20666 Remove duplicate GitHub app fallback

---

docs/Reference/Comparison.md

EVG-18912
This adds a comparison with other CI systems, copied from [this doc](https://docs.google.com/document/d/1uCp6di_Xq5S-siTdE3-LtpbNY3852-PsD3-nG0cwk54/edit), to help users coming from other CI systems.

EVG-18912 Add CI comparisons to docs

---

docs/Project-Configuration/Project-Commands.md

EVG-19126
In hindsight I don't think this needed to be an App ticket (or a ticket at all, can just update the docs at the time of responding to Stack Overflow since the info is all written out). Feel free to modify if anything here changes in the future.

EVG-19126 add lifecycle policy to docs

---

agent/agent.go
agent/agent_test.go
agent/agent_timeout_test.go
agent/background.go
agent/background_test.go
agent/command.go
agent/global.go
config.go
docs/Project-Configuration/Project-Configuration-Files.md
model/project.go

This reverts commit c638d4a4734917483f20a41641a4af261c63145b.

Revert "EVG-20281: improve callback timeout behavior (#6894)"

---

docs/Project-Configuration/Materialized-Intelligence.md

EVG-18270: Update Materialized-Intelligence.md with task stats

---

docs/API/REST-V2-Usage.md

EVG-18270: Update Task Stats API documentation with deprecation note

---

docs/decisions/2023-06-05_github_merge_queue.md
thirdparty/github.go
thirdparty/github_test.go
units/patch_intent.go

EVG-20633
Please see the added section in the ADR in this PR.
I added unit tests for the new functions this PR depends on. I will also test
the new pending behavior in staging.
Edited ADR.

EVG-20633 Send pending status for merge queue variants

---

docs/Project-Configuration/Project-Configuration-Files.md

to answer a question in an #evergreen-users thread

docs: Add more detail to OOM docs

---

rest/route/service.go
rest/route/version_create.go

EVG-20823
Updating version create route to pass in the connector it needs to initialize.

EVG-20823 Pass in data connector to make versions route

---

config.go
operations/patch.go

EVG-20448
Tweaked wording to avoid confusion

EVG-20448 indicate that --include-modules is a boolean

---

go.mod
go.sum
model/testresult/testresult.go
taskoutput/tasklogs/task_logs.go

EVG-20020
New field to store log info for a test result.
Not needed yet.
N/A

EVG-20020:  Add new test log info field to the test result model

---

graphql/generated.go
graphql/schema/types/config.graphql
graphql/tests/query/spruceConfig/data.json
graphql/tests/query/spruceConfig/queries/jira.graphql
graphql/tests/query/spruceConfig/results.json

EVG-19784
- Expose JIRA email field added in https://github.com/evergreen-ci/evergreen/pull/6861 via Spruce Config resolver
- Update unit test
N/A

EVG-19784: Expose JIRA email field via GraphQL

---

rest/data/commit_queue.go

EVG-20924
As discussed in ops, increase timeout and see how that goes.

EVG-20924 add higher context cancel for commit queue

---

agent/command/git.go
config.go

This reverts commit d6e1a19083a54e7d3a1c19b8cde784fcdd22b1a8.

Revert "EVG-20317 Stop on error if module cloning fails (#7076)"

---

agent/command/git.go
config.go

This reverts commit 2dd969a8c597ba2ce401c673bafdf3e112e38078.

Revert "Revert "EVG-20317 Stop on error if module cloning fails (#7076)" (#7078)"

---

config.go
config_test.go
trigger/patch_test.go

EVG-20184
This reverts [4689](https://github.com/evergreen-ci/evergreen/pull/4689) because we will not be using it.

EVG-20184 Remove round-robin code

---

github_app.go

EVG-21092
we werent properly passing in the installation id after getting it previously 
staging
made a patch on a project with no installation id to see that it did not error and cached it correctly
https://spruce-staging.corp.mongodb.com/task/private_sandbox_git_env_test_bynntask_patch_a95ba03b40ce0076c039db9e4e15af44e7e634cc_652eb101b23736fbe668f04e_23_10_17_16_06_38/logs?execution=3&logtype=task

EVG-21092 Pass in installation token to GitHub client

---

model/task_lifecycle_test.go

EVG-20788 
Add generated tasks test to eval bisect stepback test
Unit tests

EVG-20788 Add generated tasks test

---

model/task_lifecycle.go

[EVG-20792](https://jira.mongodb.org/browse/EVG-20792)
Add simple logging to bisect stepback
Existing unit tests. Secondary ticket [EVG-20794](https://jira.mongodb.org/browse/EVG-20794) is going to test bisect stepback algorithm.

EVG-20792 Add logging to bisect stepback

---

model/project_ref.go

EVG-20296
Followup, to #7062, need to include the push trigger as part of the project trigger validation function.
Tested on local evergreen

EVG-20296 Add push type to trigger validation

---

agent/command/s3_get.go
agent/command/s3_get_test.go
config.go
docs/Project-Configuration/Project-Commands.md

This reverts commit 4139a1e56d2796433dcc71ba0ebce10eddd7d56d.
DEVPROD-1734
Reverting the change due to a panic and it'll go in with the daily deploy.

Revert "EVG-19801 add optional param to s3.get (#7163)"

---

docs/Project-Configuration/Merge-Queue.md

A couple users have asked me about missing statuses.

docs: Add FAQ about missing statuses

---

model/task_lifecycle.go

DEVPROD-975
Stepback bisection carries over information only if there is information present. 
Existing tests and manual testing in stage here is staging proof (https://docs.google.com/presentation/d/1rgqsLS2TzicM1fiiFgGfsxgOjwyHattntLj9V-aY7_4/edit?usp=sharing)

DEVPROD-975 Stepback bisection carries over information if it is present

---

rest/route/host_spawn.go

DEVPROD-993 
This was so easy with swaggo!!

DEVPROD-993 document host stop/start routes

---

go.mod
model/project.go
model/project_test.go

DEVPROD-968
Add ReadAndValidateOutputPath to read from the given output path, validate it according to the design and return an object with output parameters. 
Added a unit test

DEVPROD-968 Add a function to read a checkrun output path and validate

---

rest/model/task.go

DEVPROD-980
Adds a nil check to make sure an unwanted exception is not thrown
Existing unit tests

DEVPROD-980 Initialize stepback info if it does not exist before copying over to API

---

agent/internal/task_config.go
agent/internal/task_config_test.go
config.go

DEVPROD-997 
Add a function that returns a bool if a task specified check run. This will be used as part of the "Support Github Checks API" project. 
Added a unit test

DEVPROD-997 Create taskHasCheckRun

---

agent/command/s3_copy.go
config.go

DEVPROD-751
removed unused s3copy params 
made sure that there wasn't any code using the parameters
nothing breaks

DEVPROD-751 Remove unused s3Copy parameters

---

graphql/generated.go
graphql/schema/types/distro.graphql
graphql/tests/mutation/saveDistro/data.json
graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql
graphql/tests/mutation/saveDistro/queries/save.graphql
graphql/tests/mutation/saveDistro/queries/validation_error.graphql

[DEVPROD-1661](https://jira.mongodb.org/browse/DEVPROD-1661)
https://github.com/evergreen-ci/spruce/pull/2157 required adding the mountpoints field to the distro mutation.

DEVPROD-1661 add mountpoints to the distro mutation

---

.drone.yml

[DEVPROD-2466](https://jira.mongodb.org/browse/DEVPROD-2466)
Add just the .drone.yml to main so we can get drone to start a build that we can then build on in https://github.com/evergreen-ci/evergreen/pull/7267
N/A

DEVPROD-2466 add .drone.yml

---

agent/agent_test.go
agent/command_test.go
agent/directory_test.go
agent/logging_test.go
docs/Project-Configuration/Project-Configuration-Files.md
model/project_parser.go
model/project_parser_test.go

DEVPROD-764 
Switch oom tracker to be true by default. Will send out an email to communicate this.
Updated doc

DEVPROD-764 enable oom tracker by default

---

model/project_ref.go
rest/data/commit_queue.go

DEVPROD-NNNNN
add description, context, thought process, etc

DEVPROD-3068 add error for CLI only commit queue items

---

apimodels/agent_models.go
config.go
graphql/generated.go
graphql/schema/types/task.graphql
rest/model/task.go
scripts/verify-agent-version-update.sh

[DEVPROD-1661](https://jira.mongodb.org/browse/DEVPROD-1661)
When this field was added it wasn't included in the API version.
This PR rectifies that oversight.

DEVPROD-1661 add disk devices to task end detail

---

thirdparty/github_test.go

DEVPROD-3187
Commits to the sample repo broke this test

DEVPROD-3187 Fix test-thirdparty failure

---

model/task_lifecycle.go

DEVPROD-1122
This moves some logic to block setting some fields when stepback is happening
Tested via staging manually with the UI ticket that uses this code

DEVPROD-1122 Set stepback information only when continuing bisect stepback or it has finished

---

model/lifecycle.go
model/project.go
model/task/task.go

DEVPROD-3613
Add a HasCheckRun field to tasks that indicate if the task should create a checkrun

DEVPROD-3613 Add HasCheckRun field to task

---

cloud/pod_util.go
docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-3173 Defintion -> Definition spelling fix

---

rest/model/project.go
rest/model/project_event.go
rest/model/subscriptions.go
rest/route/project.go

DEVPROD-3159
* Include sample input body schema for modifying a project.
* Write more detailed docs on the input fields to modify a project. I skipped a couple fields that seemed unimportant and I couldn't tell what they were supposed to do without going on a long slog through the code.
Checked that the docs outputted by `make swaggo` produced reasonable-looking docs for the project modify route.

DEVPROD-3159: document project modify inputs

---

docs/Reference/Limits.md

DEVPROD-3710 
Add a docs page on limits. 
I shall not 
Yes

DEVPROD-3710 Add limits doc

---

model/project_parser.go
model/project_parser_db.go

DEVPROD-749
This field is not called anywhere!
It compiles!

DEVPROD-749 Remove unused project parser field

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-3714
Fix module format

DEVPROD-3714 Fix module format

---

agent/command/git.go
config.go

Reverting as older version of sys-perf are running into errors cloning modules.

Revert "DEVPROD-1931 Error on module clone failure (#7379)"

---

config.go
config_db.go
model/event/host_event_finder.go
model/taskstats/db.go
operations/admin_from_mdb.go

DEVPROD-3884
cursor was never closed

DEVPROD-3884 Close cursor after accessing db

---

github_app.go

DEVPROD-4024
This pr adds some nil handling for the github api response.

DEVPROD-4024 Handle panic from nil resp from github api

---

agent/agent.go
config.go

DEVPROD-4216
There was some weird merging shenanigans resulting from not merging or rebasing changes with/on HEAD. This fixes the build.
N/A
N/A

DEVPROD-4216: import missing package in agent

---

agent/command/expansion_test.go
agent/command/expansion_write.go
config.go

DEVPROD-4482
Add temporary exception to expansions.write redaction for sys-perf.
N/A

DEVPROD-4482: add temporary exception to expansions.write redaction for sys-perf

---

model/artifact/artifact_file.go

hotfix: don't panic if string.lastIndex() doesn't find it 

---

model/artifact/artifact_file.go

While hotfixing a panic today we realized that this function would be easier to understand with a function comment.

Add comments to EscapeFiles

---

graphql/generated.go
graphql/schema/types/task_logs.graphql
model/event/task_event.go
model/task/task.go
rest/model/event.go

DEVPROD-773
More information was requested on the blocked task event so I added which tasks are unattainable to the event 
Now has a blocked_on field

DEVPROD-773 Add blocked tasks to BLOCKED_TASK event

---

go.mod
go.sum

DEVPROD-2918
update dependency manually

DEVPROD-2918 Update otlpmetricgrpc

---

docs/Project-Configuration/Project-Configuration-Files.md

[Slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1707763122311109)
A user asked about its behavior, and I've heard people in the past also be confused about `cron`'s behavior.

docs: provide better explanation for cron

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-4063
document clarification

DEVPROD-4063 Document exec timeout

---

model/task/db.go
model/task/db_test.go

DEVPROD-1739
Fixes a bug where it's not possible to filter for _different_ status and base status on the task page. (e.g. `opts.Statuses = ["failed"]`, `opts.BaseStatuses = ["success"]`)
This is caused by a logical error in the pipeline. The pipeline first gets all version tasks and their base tasks. Then the pipeline filters out tasks that don't have a status that matches `opts.Statuses`. This is not correct because the pipeline is still operating on the base tasks at this point, so it will remove all base tasks that don't match `opts.Statuses`. `opts.Statuses` should not apply to the base tasks at all.
Moving this stage later in the pipeline fixes the problem because the base task is now embedded in each task and will not match the filter.
- On staging
- Added a test that fails without …

DEVPROD-1739: Fix status filter behavior in getTasksByVersionPipeline

---

docs/Project-Configuration/Project-Commands.md

[DEVPROD-3346](https://jira.mongodb.org/browse/DEVPROD-3346)

DEVPROD-3346 Add command display name to docs 

---

model/dependency.go

DEVPROD-4739
Follow-up from #7534 to remove the temporary debug log. I only used it verify that the change didn't cause any unexpected side effects.

DEVPROD-4739: remove debug log

---

agent/agent.go

DEVPROD-3246
Adds the host id to the agent panic logs to help ops

DEVPROD-3246 Add host/pod id to agent panics

---

config.go

DEVPROD-4989
We rotated the key so we need to rollover the agents to get the new key.
N/A
N/A

DEVPROD-4989: rollover agent for new mci key

---

operations/patch.go

DEVPROD-2251
Makes the json flag in the patch command more clear.

DEVPROD-2251 Patch json flag help information

---

cloud/ec2.go
model/host/host.go
model/host/host_test.go

DEVPROD-4700
Improve debugging for Brian McCarthy and also our future (so bright)
added a unit test

DEVPROD-4700 log previous and next subnet ID when retrying

---

graphql/generated.go
graphql/schema/types/user.graphql
model/user/user.go
rest/model/user.go

DEVPROD-838
- Add time format field so that users can save their preference on Spruce
- Queried and updated value in local sandbox

DEVPROD-838: Add time format user preference

---

docs/API/GraphQL-API.md

DEVPROD-4939 Update Evergreen GraphQL API documentation

---

agent/command/expansion_test.go
agent/command/expansion_write.go
config.go

DEVPROD-4483
Remove this logic per the agreement to keep it for 1 month.
N/A

DEVPROD-4483: remove temporary exception to expansions.write redaction for sys-perf 

---

agent/agent.go
agent/agent_test.go
config.go
model/lifecycle.go
model/task/task.go

DEVPROD-5292 
Allow users to create check runs with no outputs
Added a unit test

DEVPROD-5292 Allow users to create check runs with no outputs

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-5269
Documents the `preserve_path` field and also makes parsley disclaimer bold

DEVPROD-5269 Update documentation for s3.put 

---

rest/route/github.go

DEVPROD-4723
tasks that are re-run through github had an outdated url so I updated it
this check run was restarted on GitHub and has an updated link
https://github.com/evergreen-ci/commit-queue-sandbox/pull/617/checks?check_run_id=21350875510

DEVPROD-4723 Update details url when task restarted through GitHub

---

go.mod
go.sum
rest/route/service.go

DEVPROD-5545
Add handler wrapper to compress task and test logs.
N/A

DEVPROD-5545: add compression handler to test/task log routes

---

agent/agent.go
agent/command/archive_auto_create.go
agent/command/archive_auto_extract.go
agent/command/archive_tarball_create.go
agent/command/archive_tarball_extract.go
agent/command/archive_zip_create.go
agent/command/archive_zip_extract.go
agent/command/attach_artifacts.go
agent/command/downstream_expansions_set.go
agent/command/expansion_update.go
agent/command/expansion_write.go
agent/command/generate.go
agent/command/git.go
agent/command/git_push.go
agent/command/host_create.go
agent/command/host_list.go
agent/command/perf_send.go
agent/command/results_gotest.go
agent/command/results_native.go
agent/command/s3_get.go
agent/command/util.go
agent/command/util_test.go
config.go

DEVPROD-967
This fixes the agent not finding the output file 

DEVPROD-967 Fix agent not finding output file

---

rest/route/project.go

[DEVPROD-5680](https://jira.mongodb.org/browse/DEVPROD-5680)
This fixes a panic in prod

DEVPROD-5680 Fix panic in prod

---

agent/command/results_gotest.go
agent/command/results_native.go
agent/command/results_utils.go
config.go

DEVPROD-5775
Server is still using this field.
Staging.
N/A

DEVPROD-5775: add back support for raw task logs in test results

---

units/crons.go

DEVPROD-733
Just opening this ticket to summarize a conversation with Kim, to avoid changing this in the future.

DEVPROD-733 add comment about resiliency

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-3871
Add some explanation around teardown and post commands not being guaranteed.

DEVPROD-3871 Add clarification to docs about why teardown group may not run 

---

rest/route/agent.go
service/templates/admin.html

DEVPROD-5963
Now that the project has been closed out, this is not longer needed.

DEVPROD-5963 Remove feature flag for check runs

---

rest/route/distro_test.go
validator/distro_validator.go
validator/distro_validator_test.go

[DEVPROD-4798](https://jira.mongodb.org/browse/DEVPROD-4798)
In https://github.com/evergreen-ci/evergreen/pull/7725 I missed removing this check.
With this check removed the distro save works locally with https://github.com/evergreen-ci/ui/pull/41

DEVPROD-4798 remove key check from validator

---

docs/Project-Configuration/Stepback-Bisection.md

DEVPROD-3375
The navigation documentation is a little outdated, this updates it to the latest features

DEVPROD-3375 Update navigation documentation for stepback bisection

---

validator/project_validator.go
validator/project_validator_test.go

DEVPROD-730
added more charcters to disallow in task and bv names 
unit test
made sure all existing configs pass

DEVPROD-703 Validate task names to not allow special characters

---

config_task_limits.go
rest/model/admin.go
service/templates/admin.html

DEVPROD-6066
add field to admin setting
tested locally

DEVPROD-6066 Add max pending generated tasks to admin settings

---

.github/dependabot.yml

DEVPROD-6963
Add gonum to ignore

DEVPROD-6963 Add gonum to ignore

---

github_app.go

DEVPROD-6580
This wraps the client in a simple wrapper that adds a close method that checks for nil, then closes the client.

DEVPROD-6580 Close the github client's internal http client

---

rest/route/project.go

DEVPROD-6791
This fixes the REST route description for the get project tasks route

DEVPROD-6791 Fix get project tasks route docs

---

agent/command/git.go
config.go

DEVPROD-6820
Changes git clone error log from info level to error level

DEVPROD-6820 Change git clone error log from info level to error level

---

docs/Reference/Limits.md
service/templates/admin.html

DEVPROD-4263 add help text  explaining that tasks Per Version includes unselected tasks

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-7272
This parameter was missing from the documentation, but is supported
No testing needed
Fixed!

DEVPROD-7272: document region param in s3 commands

---

model/project_ref.go

DEVPROD-7378
Add nil check to prevent panic

DEVPROD-7378 Add nil check to GetProjectRefForTask

---

go.mod
go.sum

[DEVPROD-7468](https://jira.mongodb.org/browse/DEVPROD-7468)
Update to get the changes from https://github.com/mongodb/amboy/pull/341 
Will merge once tests pass (unless someone suggests something more to do).

DEVPROD-7468 update amboy

---

model/host/db.go

DEVPROD-3949
Fix sleep schedule panic

DEVPROD-3949 fix sleep schedule modified count panic

---

go.mod
go.sum

DEVPROD-7334
Update Amboy for  https://github.com/mongodb/amboy/pull/340
Code compiles and passes existing tests.
N/A

DEVPROD-7334: update Amboy

---

docs/Project-Configuration/Project-Configuration-Files.md
model/project.go
model/project_test.go

DEVPROD-7321
Add trigger version default expansion
Updated unit test
Updated doc

DEVPROD-7321 add trigger version default expansion

---

graphql/README.md

DEVPROD-7582
Adds some docs for running the graphql integration tests locally

DEVPROD-7582 Add documentation for running Graphql tests

---

go.mod
go.sum
units/host_setup_script.go
units/migrate_volume.go
units/pod_creation.go
units/pod_definition_creation.go
units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go
units/provisioning_convert_host_to_legacy.go
units/provisioning_convert_host_to_new.go
units/provisioning_create_host.go
units/provisioning_restart_jasper.go
units/provisioning_setup_host.go
units/provisioning_user_data_done.go
units/reauthorize_user.go
units/spawnhost_start.go
units/spawnhost_stop.go

DEVPROD-7311
Use the helper written in https://github.com/mongodb/amboy/pull/342 to simplify checks that look for the last job attempt.
N/A

DEVPROD-7311: use helper to check for last job attempt

---

docs/Reference/Limits.md

DEVPROD-6806
This documents the new max hourly patch tasks scheduling feature.

DEVPROD-6806 Document new task scheduling limit

---

trigger/host.go
trigger/host_test.go
trigger/volume.go
trigger/volume_test.go

DEVPROD-7692 
These links currently just redirect to spawn/host but better to just point to the right place

DEVPROD-7692 fix volume/host expiration links

---

graphql/generated.go
graphql/schema/types/host.graphql
graphql/schema/types/spawn.graphql
graphql/tests/mutation/spawnHost/queries/spawn_host.graphql
graphql/tests/mutation/spawnHost/results.json

DEVPROD-7517
- Expose beta flag in order to develop toggle feature on the UI
- Also expose next start/stop times
- Update unit test
N/A

DEVPROD-7517: Expose more sleep schedule fields

---

config.go
operations/validate.go

Reverts evergreen-ci/evergreen#7963

Revert "DEVPROD-4090 Error when receiving a server error when validating config"

---

config.go
operations/validate.go

DEVPROD-4090
Unreverting since it's safe.
The original PR is here: https://github.com/evergreen-ci/evergreen/pull/7963

DEVPROD-4090 Error when receiving a server error when validating config

---

agent/agent.go
config.go
globals.go

DEVPROD-1662
Add attribute for task failure type, if relevant.
Available spans not documented but will comment in ticket

DEVPROD-1662 add attribute for task failure type

---

.github/dependabot.yml

DEVPROD-6963
A small update to wrap in asterisks since it was recently ignored and an update came through- updating the project.

DEVPROD-6963 Update gonum ignore wrapped in asterisks

---

docs/Home.md
docs/Project-Configuration/Project-Configuration-Files.md

Wanted to add something about serial task execution, and then also wanted to very mildly shore up stepback help text. The stepback text could be a lot better but I think we should defer until we determine next steps for this feature this week (cc @ZackarySantana)

docs: tweak home docs

---

agent/agent_test.go

DEVPROD-5988
From renaming some variables, I forgot to remove the 2 at the end of the new variables.

DEVPROD-5988 Rename AgentSuite test variables to be single rather than 2

---

go.mod
go.sum

Upgrade for https://github.com/mongodb/amboy/pull/344

DEVPROD-8844: upgrade Amboy

---

docs/decisions/2024-07-10_include_file_limits.md

DEVPROD-3509
doc for updating our include limits

DEVPROD-3509 Add decision doc for include limits

---

graphql/generated.go
graphql/schema/types/task.graphql
graphql/task_resolver.go
graphql/tests/task/imageId/data.json
graphql/tests/task/imageId/queries/image_id.graphql
graphql/tests/task/imageId/results.json
model/distro/distro.go
model/distro/distro_test.go

DEVPROD-7650
Added imageId to task type and completed corresponding resolver. Added GetImageIdFromDistro function to distro.go 
Added GraphQL test.

DEVPROD-7650: Resolve imageId from GraphQL Task type

---

go.mod
go.sum

DEVPROD-8738
Upgrade Amboy for https://github.com/mongodb/amboy/pull/345.
Tests compile.

DEVPROD-8738: upgrade Amboy

---

units/host_termination.go

DEVPROD-8798 remove terminated host warning

---

trigger/host.go

DEVPROD-9048 use correct body for temporary exemption emails

---

gqlgen.yml
graphql/generated.go
graphql/image_resolver.go
graphql/image_test.go
graphql/models_gen.go
graphql/query_resolver.go
graphql/schema/types/image.graphql
rest/model/image.go
thirdparty/runtime_environments.go
thirdparty/runtime_environments_test.go

DEVPROD-7645
Add GraphQL support for the following fields: packages(opts: PackageOpts!): [Package!]!
Use the getPackages method to fetch packages for an image. It should support pagination & filters.
Added testing function image_test.go. Cannot do standard Go test because data can change over time.

DEVPROD-7645: Resolve Packages from GraphQL Image Type

---

docs/FAQ.md
docs/Project-Configuration/Controlling-when-tasks-run.md
docs/Project-Configuration/Project-Configuration-Files.md
docs/Project-Configuration/Project-and-Distro-Settings.md

DEVPROD-4690
This adds a new page documenting the differences between the three with short examples.

DEVPROD-4690 document cron, batchtime and periodic build 

---

rest/route/build.go
rest/route/distro.go
rest/route/patch.go
rest/route/select.go
rest/route/task.go

DEVPROD-9488
When I try to generate the client code, I get some errors. Then, if I try to use the code, it errors out on not finding some import. It does find the interface I'm trying to import, but not the thing that it tries to import itself:
My import:
from openapi_server.ownership.get_owners import get_owners
File "/Users/ron.neuman/mms/scripts/services_common_tools/openapi_server/ownership/get_owners.py", line 39, in <module>
The tasks api I was importing was found:
from evg_openapi_client.openapi_client.api.tasks_api import TasksApi
The AdminApi that is trying to be imported from the task api.... not found
File "/Users/ron.neuman/mms/scripts/services_common_tools/evg_openapi_client/openapi_client/__init__.py", line 20, in <module>
from openapi_client.api.admin_api import AdminApi …

DEVPROD-9488: fix some of the annotations that break during openAPI generation

---

config_cloud.go
config_test.go
rest/data/admin_test.go
rest/model/admin.go
rest/model/admin_test.go
rest/route/admin_test.go
service/templates/admin.html
testutil/config.go

DEVPROD-9390
Create admin settings sub-section for Parameter Store.
* Tested in local Evergreen that the UI worked.
N/A

DEVPROD-9390: create admin settings for Parameter Store

---

model/annotations/db.go
model/build/db.go
model/event/event_finder.go
model/patch/db.go
model/task/db.go
model/version_db.go

DEVPROD-7802
findallQ never returns the results not found error so it was never being hit.
existing tests pass

DEVPROD-7802 Remove unneeded results not found check

---

cmd/build-cross-compile/build-cross-compile.go

Reverts evergreen-ci/evergreen#8175

Revert "DEVPROD-9714 use cgo on macOS"

---

graphql/image_resolver.go
graphql/image_test.go

DEVPROD-9743
Regular users should not be able to see admin distros.
- Updated Go tests

DEVPROD-9743: Hide admin distros for non-admin users in image.Distros resolver

---

graphql/generated.go
graphql/image_resolver.go
graphql/image_test.go
graphql/models_gen.go
graphql/schema/types/image.graphql

DEVPROD-7658
Add count field to Image events resolver

DEVPROD-7658: Add count field to Image events resolver

---

agent/agent.go
agent/internal/client/base_client.go
config.go

DEVPROD-10035
the err being returned would always be nil because the err was being redefined within the loop 
also added a nil check to verify it will not happen

DEVPROD-10035 Return get project error properly

---

cmd/build-cross-compile/build-cross-compile.go
config.go
self-tests.yml

[DEVPROD-9915](https://jira.mongodb.org/browse/DEVPROD-9915)
vert of https://github.com/evergreen-ci/evergreen/pull/8207, this time fixing the notary client download link.
I will add a signing task to the patch created for this PR.

DEVPROD-9915 cgo for mac

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-7433
evergreen's id is needed for trust policies for assume role

DEVPROD-7433 Document Evergreen's  account ID

---

docs/Hosts/Developer-Workstations.md

DEVPROD-9982
says workstation has passwordless sudo access

DEVPROD-9982 Document workstation has sudo access

---

config_amboy.go
environment.go
rest/model/admin.go
rest/model/admin_test.go
rest/route/admin_test.go
service/templates/admin.html

[DEVPROD-7013](https://jira.mongodb.org/browse/DEVPROD-7013)
This is not being used and can be removed. 
Priority is being removed from Amboy [here](https://github.com/mongodb/amboy/pull/339).

DEVPROD-7013 Remove unused amboy priority

---

docs/Project-Configuration/Github-Integrations.md

DEVPROD-10358 
I'm expecting these docs to have a lot of eyes on them soon. I want users to know that this will change so that they can make decisions with that consideration.

DEVPROD-10358 Add docs note about dynamic github token defaulting to repo soon

---

docs/Project-Configuration/Project-Configuration-Files.md
model/lifecycle.go
model/project.go
model/project_parser.go
model/project_parser_test.go
model/project_test.go
service/stats.go
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-7736
this is unused and broken so we are removing it

DEVPROD-7736 Remove inline task groups

---

model/patch/patch.go
units/github_status_refresh_test.go
units/patch_intent.go

Reverts evergreen-ci/evergreen#8246

Revert "DEVPROD-2749 remove patch.DisplayNewUI"

---

rest/route/host_agent_test.go

DEVPROD-5177
This adds some extensive testing of different scenarios to the assign next task tests.
Unit test

DEVPROD-5177 Update and add more tests to assign next task

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-10493 Make "needs configuration" more prominent for github.generate_token

---

docs/FAQ.md

DEVPROD-10431 
I ran into this while I was doing some testing and I think it could be helpful for users to know this.

DEVPROD-10431 Add a doc note to the FAQ about repository not found

---

model/task/db.go
model/task/db_test.go
model/task/task.go
model/task/task_test.go

DEVPROD-2423
Seems like we didn't intend to have to set this in these places long-term since we set it when checking dependencies.

DEVPROD-2423 remove special updates for unattainable dependencies

---

rest/route/degraded_mode.go
rest/route/degraded_mode_test.go

DEVPROD-6083
Do a best-effort attempt of setting an info banner when degraded mode toggles, mentioning its effect for large YAML files.
Updated unit test

DEVPROD-6083 Set banner when setting degraded mode

---

docs/Project-Configuration/Evergreen-Data-for-Analytics.md

JIRA: https://jira.mongodb.org/browse/DPLATFORMS-140

DPLATFORMS-140: Update docs with new swap data fields in Trino tables

---

docs/Project-Configuration/Project-Configuration-Files.md

Clarify this behavior of what a base commit is for PR patches

Docs: document revision PRs

---

docs/FAQ.md

DEVPROD-11598 Add to generate token FAQ about go private modules

---

config_pod_lifecycle.go
graphql/host_resolver.go
graphql/util.go
model/event/event.go
model/generate.go
model/project_event.go
model/task/db.go
model/task_lifecycle.go
rest/data/commit_queue.go
rest/data/project.go
rest/data/scheduler.go
rest/route/host_agent.go
testutil/testing.go
thirdparty/github.go

DEVPROD-11398
Updating a few todos, for tickets that are closed or EVG.  (Didn't update everything, just quick wins really)

DEVPROD-11398 update TODO ticket numbers

---

rest/route/select.go

DEVPROD-11629
Follow-up to #8356 - Reduce to debug log and link ticket to remove this log eventually.

DEVPROD-11629: link test selection ticket

---

model/task/db.go
self-tests.yml

[DEVPROD-10025](https://jira.mongodb.org/browse/DEVPROD-10025)
I really ought to have done this before the upgrade, but here we are...
♾️

DEVPROD-10025 upgrade tests to 8.0

---

operations/fetch_test.go

DEVPROD-11945 Fix cloning test 

---

model/task/task.go

Reverts evergreen-ci/evergreen#8377

Revert "DEVPROD-7676 Filter set tasks scheduled time in memory"

---

agent/command/git_patch_test.go
cloud/parameterstore/fakeparameter/fake_parameter.go
config.go
config_db.go
config_test.go
config_test/evg_settings.yml
config_test/evg_settings_with_3rd_party_defaults.yml
model/event/admin_event_test.go
model/githubapp/github_app_auth.go
model/githubapp/github_app_test.go
operations/cli_integration_test.go
public/static/js/admin.js
rest/data/admin_test.go
rest/data/host_create_test.go
rest/model/admin.go
rest/model/admin_test.go
rest/route/agent_test.go
scripts/setup-credentials.sh
scripts/setup-smoke-config.sh
self-tests.yml
service/templates/admin.html
testutil/config.go
testutil/testing.go
thirdparty/github.go
units/github_status_api_test.go

DEVPROD-1429
This removes the smoke test's reliance on a github token in settings.

DEVPROD-1429 Remove GITHUB_TOKEN from smoke test 

---

docs/Hosts/Spawn-Hosts.md

DEVPROD-10380
remove beta test mention since it's no longer relevant

DEVPROD-10380 Remove mention of unexpirable host schedule beta period from docs

---

docs/FAQ.md

Add a bullet point for the Client.Timeout header for the generate token command.

Docs: Add to FAQ

---

go.mod
go.sum

[DEVPROD-12355](https://jira.mongodb.org/browse/DEVPROD-12355)
Get the changes from https://github.com/mongodb/anser/pull/95
Intend to merge if/when existing tests pass.

DEVPROD-12355 update anser

---

model/project_ref.go
model/project_test.go
rest/route/project.go

DEVPROD-8756
Hidden projects shouldn't be accessible to users or Mana.
Edited unit test.
updated text for route

DEVPROD-8756 filter hidden projects from all projects route

---

graphql/generated.go
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/queries/no_filters.graphql
graphql/tests/query/waterfall/results.json
model/task/db.go
model/waterfall.go
model/waterfall_test.go

DEVPROD-12509
Add aggregation pipeline stage to include task's display status
Add unit test

DEVPROD-12509: Return task display status in waterfall

---

docs/FAQ.md

DEVPROD-12505
Add docs with guidance on which permissions to request for github apps.

DEVPROD-12505 Write docs with tips on how to request app permissions

---

cloning.yml

DEVPROD-6063: update to macos 14
We want to get rid of MacOS 1014!

DEVPROD-6063: update to macos 14

---

model/project_event.go

DEVPROD-12861
Similar to #8489 but for GitHub apps instead of project vars - we're eventually going to stop storing the GitHub app private key in the DB, so the BSON tag on `GithubAppAuth.PrivateKey` will be removed. However, the event log still needs to keep track of when the private key changes so it can display when the private key is modified in the event log. To maintain changes to the private key in the event log, I split the data model for GitHub app auth into a separate one for the event log.
Existing tests for GitHub app auth in the event logs pass.
N/A

DEVPROD-12861: split project events model from GitHub app auth

---

docs/Project-Configuration/Task-Runtime-Behavior.md

From https://mongodb.slack.com/archives/C0V896UV8/p1731614787068029

docs: add agent logs to process cleanup

---

agent/command/archive_tarball_create.go
config.go

DEVPROD-12257
log something when nothing was archived in case they expected something

DEVPROD-12257 Log when archive tarball doesn't archive any files

---

rest/data/project.go
rest/data/project_test.go

DEVPROD-11534
Update text to use new process, as requested.
Updated unit test

DEVPROD-11534 fix text for ticket

---

rest/model/project.go
rest/route/project.go

Tweak text, from conversation in this thread 
https://mongodb.slack.com/archives/C0V896UV8/p1733773216965099

docs: improve project ref fields

---

docs/Project-Configuration/Notifications.md
globals.go
model/event/host_event.go
model/host/hostutil.go
trigger/host_spawn.go
trigger/host_spawn_test.go
units/host_setup_script.go
units/host_status.go
units/host_status_test.go
units/provisioning_setup_host.go

DEVPROD-3983
A re-staging of #8525 with the conflict introduced by #8520 resolved.

DEVPROD-3983 Spawn host setup script notifications

---

docs/Reference/Data-Retention.md

DEVPROD-13482
Document data retention policies for evergreen. Taken from this [doc](https://docs.google.com/document/d/1sj7cgjClhO7CutZZw19s912u7YQqULIxjIX6J1SdjEw/edit?tab=t.0#heading=h.dilpllcveq90).

DEVPROD-13482 Document data retention policy

---

model/project_parser_s3.go

DEVPROD-13440 Fix degraded mode typo

---

docs/Project-Configuration/Parameterized-Builds.md

DEVPROD-8166
Add a few more words about this, just to be safe.

DEVPROD-8166: clarify further that parameters are public in docs

---

scheduler/wrapper.go

DEVPROD-13371 
Skip task queue error if the document doesn't exist.

DEVPROD-13371 skip task queue error for disabled distros

---

api/host.go
rest/route/host.go
units/deco_host_notify.go
units/host_monitoring_check.go
units/provisioning_convert_host_to_legacy.go
units/provisioning_convert_host_to_new.go
units/provisioning_restart_jasper.go
units/util.go

DEVPROD-11693
Runtime Environments asked that we log the user who made the changes. It'll also be set to "mci" if we made the change.
I'll comment in the ticket and tag them so they know.

DEVPROD-11693 include user in decommissioned host notify log

---

config.go
config_db.go
config_sections.go
config_single_task_distro.go
rest/model/admin.go
rest/model/admin_test.go
service/templates/admin.html
testutil/config.go

DEVPROD-13369
add single distro settings to admin backend 
there is another ticket to add it to the legacy UI page
unit test

DEVPROD-13369 Add single task distro settings to backend

---

docs/FAQ.md

DEVPROD-13681
documenting a git error in faq

DEVPROD-13681 Document no merge base error

---

docs/Project-Configuration/Github-Integrations.md

DEVPROD-9660
ticket requested that we change a feature but we cannot change certain things due to validation constraints and not breaking current behavior so I updated the docs with recommended usage and specified some things (will update on ticket once closed)

DEVPROD-9660 Update check run documentation to be more specific

---

model/task/task.go
model/task_lifecycle.go

DEVPROD-13826
This switches to the exported function and renames it to CalculateDisplayStatus

DEVPROD-13826 Switch to exported function and rename to CalculateDisplayStatus

---

model/task_lifecycle.go

DEVPROD-12090
this was causing a lot of noise so now the function no-ops and warns

DEVPROD-12090 Warn on stepback errors

---

graphql/generated.go
graphql/schema/types/project.graphql
graphql/schema/types/repo_ref.graphql
graphql/tests/projectSettings/projectRef/queries/project_ref.graphql
graphql/tests/projectSettings/projectRef/results.json
model/project_ref.go
rest/model/project.go
rest/route/github_test.go
service/api.go

DEVPROD-13862
Merge queue usage removed in a previous PR, so removing now. Created a spruce PR as well. 
https://github.com/evergreen-ci/ui/pull/562

DEVPROD-13862 remove unused MergeQueue field

---

model/host/host.go
model/task_queue.go
scheduler/utilization_based_host_allocator.go
scheduler/utilization_based_host_allocator_test.go
units/host_allocator.go

DEVPROD-14145
No functional change. Add variable documentation and comments to better illustrate what decisions the host allocator is making when spinning up hosts (mostly for myself 😅)

DEVPROD-14145 Document and comment host allocator

---

docs/Project-Configuration/Project-Commands.md

Discussed in https://mongodb.slack.com/archives/C0V896UV8/p1737577456483889?thread_ts=1737572620.717349&cid=C0V896UV8

docs: add policy recommendation for assume role

---

docs/Project-Configuration/Project-Configuration-Files.md
docs/Project-Configuration/Task-Runtime-Behavior.md

DEVPROD-14403 Document task status route limits

---

model/artifact/artifact_file.go
model/artifact/otel.go

DEVPROD-13976
Reapplies: #8673

DEVPROD-13976 Add otel to presign file func

---

cloud/ec2_client.go

DEVPROD-11286 
A little bit of tech debt clean up.
Verify existing tests pass.

DEVPROD-11286 remove unused interface methods

---

service/ui.go

DEVPROD-14593
Most network requests in evergreen don't properly respond to the [`accept-encoding`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) header and won't compress responses
Before:
After:

DEVPROD-14593 Ensure graphql requests respect gzip encoding

---

trigger/project_triggers.go

DEVPROD-14613
Need to pass in the identifier of the project ref as well.

DEVPROD-14613: Fix downstream trigger version error message

---

docs/Project-Configuration/Project-Commands.md

Add example of the expansions.update input YAML file.

docs: add example for expansions.update file

---

units/host_monitoring_idle_termination_test.go

DEVPROD-13424
Fix an issue where the idle host termination tests were racing. They should be reliably passing after this change.
The tests in this file were racing because of a combination of 1. reusing host IDs across different tasks, 2. using the global test env, and 3. the fact that the idle host termination job is implemented by enqueueing host termination jobs. The host ID `host1` was reused across two tests ([here](https://github.com/evergreen-ci/evergreen/blob/6bbd5468ab64f8d7dbfc50e95dd0879cd8a09c65/units/host_monitoring_idle_termination_test.go#L555) and [here](https://github.com/evergreen-ci/evergreen/blob/6bbd5468ab64f8d7dbfc50e95dd0879cd8a09c65/units/host_monitoring_idle_termination_test.go#L874)). The [first test](https://github.com/evergreen-ci/evergreen/blob/6bbd5468ab64f8d7 …

DEVPROD-13424: fix flakiness in idle host termination tests

---

graphql/generated.go
graphql/models_gen.go
graphql/query_resolver.go
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/queries/no_filters.graphql
graphql/tests/query/waterfall/results.json

DEVPROD-13933
- Return the order number of the most recent version in the project for caching purposes
Update GraphQL unit test

DEVPROD-13933: Return most recent order number in pagination

---

docs/FAQ.md

This has been moved to confluence.

docs: update FAQ wiki link

---

units/provisioning_create_host.go

DEVPROD-14692
We actually have 6 subnets in us-east-1, might as well use all of them

DEVPROD-14692 Add one more retry to host create job

---

model/alertrecord/alert_bookkeeping.go
model/event/subscriptions.go
model/githubapp/github_app_installation_db.go
model/notification/db.go
model/patch/cli_intent.go
model/patch/db.go
model/patch/github.go
model/user/db.go

DEVPROD-14861 
This is just some quick cleanup that I noticed.

DEVPROD-14861 Remove nolint and unused Bson tags

---

docs/CLI.md

Update CLI docs to clarify behavior of `--skip_confirm` flag.

Update cli docs

---

go.mod
go.sum

DEVPROD-14445
Update jasper to use latest version with nil check

DEVPROD-14445 Update Jasper

---

agent/agent.go
agent/status_test.go
cloud/parameterstore/fakeparameter/fake_parameter.go
config.go

DEVPROD-2307
we could potentially run things like teardowntaskgroup with no logger in the tc so this PR adds a default logger for them
n/a

DEVPROD-2307 Add default logger for task context in agent

---

rest/route/project_copy.go
rest/route/project_copy_test.go

DEVPROD-12467
This is just a quick-win to be consistent (i.e. log that the project has been modified) rather than adding new functionality (like a new event type for the copied project or anything).  
Updated existing tests.

DEVPROD-12467 log project modified when variables are copied

---

self-tests.yml

DEVPROD-15047
`use_scalar` was recently added as an option for git.get_project. This adds it to our self-tests.

DEVPROD-15047 Self Test Scalar

---

graphql/generated.go
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/queries/variants.graphql
graphql/tests/query/waterfall/results.json
model/waterfall.go

DEVPROD-14986
Return build activated status to facilitate omitting inactive builds from filter results.
Update GraphQL unit test

DEVPROD-14986: Return build activated status

---

cloud/ec2_util.go

DEVPROD-15025
Simple switch of the default volume from Gp2 -> Gp3

DEVPROD-15025 Switch from Gp2 volume default to Gp3 default

---

config.go
operations/flags.go

DEVPROD-14764
Tried to make the description more explicit.

DEVPROD-14764 Clarify --ref CLI flag description

---

docs/Hosts/Spawn-Hosts.md

DEVPROD-11580 
The UI already uses this verbiage.

DEVPROD-11580 use uptime schedule instead of sleep schedule in docs

---

config.go
operations/patch_util.go
operations/patch_util_test.go

DEVPROD-14761
Disallow evergreen patch with --ref and --uncommitted
Added a test.

DEVPROD-14761 Disallow evergreen patch with --ref and --uncommitted

---

rest/model/generated_converters.go
rest/route/middleware.go
thirdparty/api_models.go
thirdparty/github.go

DEVPROD-14637
Remove dead code.

DEVPROD-14637 Remove Dead Code 

---

docs/Project-Configuration/Repo-Level-Settings.md

DEVPROD-8672
Added more explicit instructions for first time migrations.

DEVPROD-8672 More explicit docs for untracked projects

---

rest/route/host.go

[DEVPROD-12125](https://jira.mongodb.org/browse/DEVPROD-12125)
Update patch hosts route documentation

DEVPROD-12125 Update patch hosts route documentation

---

docs/Project-Configuration/Create-a-Project.md

DEVPROD-14714
I tried to put "don't be chaotic" into more concrete terms. Please let me know if there's anything else you think would be helpful to add. 
yes

DEVPROD-14714 Add documentation on what to consider before creating a project

---

operations/patch_util.go
operations/patch_util_test.go

Reverts evergreen-ci/evergreen#8758

Revert "DEVPROD-14761 Disallow evergreen patch with --ref and --uncommitted"

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-12787
Add docs with special considerations for dependencies for single host task groups

DEVPROD-12787 document how single-host task dependencies work

---

operations/patch.go

Reverts evergreen-ci/evergreen#8769

Revert "DEVPROD-13915 Fix json output for patch-file command"

---

units/host_termination.go
units/provisioning_create_host.go

DEVPROD-13573
just logs extra information for host creation and termination

DEVPROD-13573 Add single task distro logging for host creation and termination

---

cloud/ec2.go

DEVPROD-15228
These extra logs are producing noise and these same errors are captured when the create host job fails anyway.
Existing tests

DEVPROD-15228 Reduce insufficient capacity error logs

---

gqlgen.yml
graphql/generated.go
graphql/redacted_fields_gen.go
graphql/schema/types/config.graphql
graphql/tests/query/spruceConfig/data.json
graphql/tests/query/spruceConfig/queries/single_task_distro.graphql
graphql/tests/query/spruceConfig/results.json
rest/model/admin.go

DEVPROD-15352
These code changes resolve single task distro allowed task data from graphql

DEVPROD-15352: Resolve the SpruceConfig.singleTaskDistro GQL field

---

testdata/local/admin.json

DEVPROD-15349: Add testdata for Single Task Distro page 

---

docs/Project-Configuration/Controlling-when-tasks-run.md

DEVPROD-14849
users wanted more clarity on docs

DEVPROD-14849 Clarify activate documentation

---

rest/route/host_agent.go

DEVPROD-53
Changes alerts in host_agent.go to errors.

DEVPROD-53 Change alerts in host_agent.go to errors

---

model/host/host.go
repotracker/repotracker.go
rest/route/project_validate.go

DEVPROD-15932
identifier was always being set to "" for validate 
local testing verified it gets passed in correctly now

DEVPROD-15932 Pass in project identifier for validate

---

repotracker/repotracker.go
rest/route/project_validate.go

Reverts evergreen-ci/evergreen#8851

Revert "DEVPROD-15932 Pass in project identifier for validate"

---

config.go
config_single_task_distro.go
operations/validate.go
rest/route/host_agent.go
service/api.go
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-15935 
the team testing this feature requested the ability to whitelist by bv and entire project so I added that to the validation 
deployed to staging and made sure it worked

DEVPROD-15935 Update single task distro validation

---

testdata/local/admin.json

DEVPROD-16104: Add testdata for Single Task Distro Page

---

model/generate.go
model/project_parser_db.go
units/generate_tasks.go

DEVPROD-14799
This adds some more otel for generate.tasks, I think I've narrowed it down to something in our saving of the parser project logic, so I focused on adding more otel on it
Unit tests

DEVPROD-14799 Add more OTel for generate.tasks Amboy job

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-14648
Fix a couple broken docks links.

DEVPROD-14648 Fix broken links

---

units/provisioning_create_host.go

DEVPROD-13577
grip for single task distros so we can make a splunk alert

DEVPROD-13577 Grip error for single task distros

---

config.go
operations/patch_util.go
operations/patch_util_test.go

DEVPROD-15635
Consider regex tasks/variants when looking at whether to use defaults.
Refactored this out since the logic is used a couple of times.
Added a test.

DEVPROD-15635 consider regex when determining defaults

---

self-tests.yml

DEVPROD-15806
There was a regression after https://github.com/evergreen-ci/evergreen/pull/8927/files was merged so I'm putting this back for now.

DEVPROD-15806 Put the temporary fix back 

---

config.go
rest/client/methods.go

DEVPROD-16958
Method to get the patch and modules has copy-pasted errors from the method above it.
N/A

DEVPROD-16958: fix copy-pasted error messages

---

agent/agent.go
agent/agent_test.go
config.go
docs/Project-Configuration/Task-Runtime-Behavior.md

DEVPROD-13248 
Thank you @Kimchelly for noticing that I consistently did a very silly thing.

DEVPROD-13248 fix netrc typo

---

config.go
go.mod
go.sum

Reverts evergreen-ci/evergreen#8959

Revert "DEVPROD-16983: update to latest pail version"

---

docs/Hosts/Spawn-Hosts.md
docs/Project-Configuration/Project-and-Distro-Settings.md

DEVPROD-16932
* Add documentation for project spawn host setup script.
* Add documentation for Windows-specific considerations when writing the script.

DEVPROD-16943: add documentation about project-level spawn host setup script

---

rest/model/admin.go

DEVPROD-17456
Delete a no-op code block that I spotted in the REST admin model.

DEVPROD-17456: delete dead if block in admin REST model

---

repotracker/repotracker.go

DEVPROD-17562
Delete commented-out code, seems like leftover from a previous PR.

DEVPROD-17562: delete commented-out session context

---

model/distro/distro.go
model/distro/distro_test.go

DEVPROD-17116
Release mode has been disabled on both prod and staging. Let me know if there are any other fields we think would be good to start with!
Added to unit test.

DEVPROD-17116 use release mode settings if enabled

---

rest/route/middleware.go

DEVPROD-17764
We no longer need this and shouldn't log this.

DEVPROD-17764 Stop logging headers

---

docs/Project-Configuration/Project-and-Distro-Settings.md

DEVPROD-15237
specify a requirement in docs

DEVPROD-15237 Document requirement for repotracker

---

docs/Project-Configuration/Merge-Queue.md

DEVPROD-17235 
People get confused that changes need to be made in two places, so adding this as an FAQ question.

DEVPROD-17235 add FAQ for adding branch protection rule

---

docs/Project-Configuration/Project-Configuration-Files.md
model/project.go
model/project_test.go

DEVPROD-17204
adding new expansion
unit test
added to default expansions

DEVPROD-17024 Expose activated by as expansion

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-17508
Fixes a doc link for AWS accounts.

DEVPROD-17508 Fix doc link for AWS accounts

---

docs/Project-Configuration/Controlling-when-tasks-run.md

DEVPROD-18087
add extra clarification

DEVPROD-18087 Clarify cron behavior

---

config_db.go
config_serviceflags.go
rest/model/admin.go
service/templates/admin.html
testutil/config.go

DEVPROD-18223
just adds feature flag to admin settings to turn off parameter store for admin settings if needed
works on staging

DEVPROD-18223 Add feature flag for admin parameter store

---

docs/Project-Configuration/Controlling-when-tasks-run.md

DEVPROD-18177 Document cron example

---

config.go
config_auth.go
config_cedar.go
config_cloud.go
config_jira.go
config_runtime_environments.go
config_slack.go
config_ssh.go

DEVPROD-18227
just adds a new tag to fields that should be secret in admin settings

DEVPROD-18227 Mark admin secrets

---

docs/Project-Configuration/Project-Configuration-Files.md
model/task/task.go
model/version.go

DEVPROD-18205
This cleans up our docs around the trigger values and trigger expansions.

DEVPROD-18205 Document trigger_id

---

cloud/volume.go
config_test.go
environment_test.go
globals.go
graphql/integration_atomic_test_util.go
testutil/testing.go

DEVPROD-16428 Add comment to hard coded testing variable

---

units/crons.go

DEVPROD-18775
update description to mention single task hosts

DEVPROD-18775 Update host termination message

---

units/stats_amboy.go

DEVPROD-17289
Uses correct app context for this job.
Existing tests

DEVPROD-17289 Use correct context for amboy stats job

---

rest/route/github.go
units/schedule_patch.go

DEVPROD-17819
Switched to maintaining the parent context.

DEVPROD-17819 use parent context to preserve traces

---

agent/command/git.go
agent/globals/globals.go
apimodels/agent_models.go
cloud/docker_mock.go
config.go
globals.go
model/artifact/db.go
model/event/subscriptions.go
model/event/task_event.go
model/repository.go
model/task/sorter.go
model/version_db.go
model/waterfall.go
operations/flags.go
rest/route/pod_agent_test.go
thirdparty/github.go

DEVPROD-19594
Delete a bunch of dead constants.

DEVPROD-19594 Delete dead constants

---

agent/command/host_create_test.go
model/distro/distro_test.go
model/project_parser_test.go
rest/data/patch_test.go
rest/route/annotations_test.go
service/patch.go
thirdparty/github.go
thirdparty/github_test.go
thirdparty/jira.go
util/url_test.go

DEVPROD-19600
Get ahead of some potential nil dereferences.
Existing tests

DEVPROD-19600 Address potential nil dereferences

---

rest/route/service.go

Reverts evergreen-ci/evergreen#9209

Revert "DEVPROD-15741 Don't require edit permissions to view distro"

---

docs/Project-Configuration/Github-Integrations.md

DEVPROD-18856
document the automatic base change event

DEVPROD-18856 Document new githook action

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-12157 Add documentation to the script param in the shell.exec project command

---

docs/FAQ/Dynamic-Github-Tokens-FAQ.md
docs/Project-Configuration/Github-Integrations.md

DEVPROD-19956
This adds documentation for where to request a github app and fixes some links.

DEVPROD-19956 Add documentation for requesting github apps

---

docs/FAQ/Dynamic-Github-Tokens-FAQ.md

DEVPROD-19956
This fixes a markdown lint error

DEVPROD-19956 fix lint

---

config.go
config_test.go
rest/data/admin.go
rest/data/admin_test.go
testutil/config.go
testutil/testing.go

DEVPROD-18230
read secrets from parameter store if settings is enabled
unit testing
existing tests shoud pass

DEVPROD-18230 Read admin secrets from parameter store

---

docs/FAQ/Static-Token-Deprecation-FAQ.md

docs: update static token deprecation FAQ

---

graphql/schema/types/other.graphql
graphql/tests/mutation/saveAdminSettings/queries/other.graphql
graphql/tests/mutation/saveAdminSettings/results.json

[DEVPROD-19040](https://jira.mongodb.org/browse/DEVPROD-19040)
https://github.com/evergreen-ci/ui/pull/983 frontend pr

DEVPROD-19040: Add fix for other seciton of admin settings

---

config.go

DEVPROD-20812
increases timeout so we stop getting context cancelled errors so often

DEVPROD-20812 Increase timeout for parameter store

---

docs/Project-Configuration/Github-Integrations.md

DEVPROD-20836
gets rid of whitespace

DEVPROD-20836 Fix lint markdown

---

agent/command/s3_put.go
agent/command/s3_put_test.go
config.go

DEVPROD-20997
Follow up to #9308. I forgot the struct tag.
Added a unit test to cover this

DEVPROD-20997 Expand s3.put permissions parameter

---

config.go
config_db.go
config_serviceflags.go
graphql/integration_atomic_test_util.go
graphql/mutation_resolver.go
graphql/schema/types/config.graphql
graphql/tests/mutation/saveAdminSettings/data.json
graphql/tests/mutation/saveAdminSettings/queries/service_flags.graphql
graphql/tests/mutation/saveAdminSettings/results.json
graphql/tests/query/adminSettings/data.json
graphql/tests/query/adminSettings/results.json
rest/data/admin.go
rest/model/admin.go
service/templates/admin.html
testutil/config.go

DEVPROD-18235
removes fallback and service flag
existing tests pass 
all functionality is good

DEVPROD-18235 Remove parameter store fallback

---

service/templates/task_log.html

DEVPROD-21409
Deleted `task_log.html` but it's being used by `task_log_raw` route, so we need to keep it for now

DEVPROD-21409: Add `task_log.html` back to fix HTML task logs

---

model/version.go
model/version_test.go
rest/route/project.go

DEVPROD-19406
allows users to get versions for projects with time 
unit testing 
staging
works on postman
added to API docs

DEVPROD-19406 Expose get versions by project with time

---

go.mod
go.sum

DEVPROD-687
Adding in the diff from [here](https://github.com/evergreen-ci/gimlet/pull/183)

DEVPROD-687 Update gimlet

---

agent/otel.go

[DEVPROD-21298](https://jira.mongodb.org/browse/DEVPROD-21298)
This moves the disk usage out of the disk loop, which will reduce our column usage. I looked in to doing one that checked for the space per mountpoint- but it uses a lot of columns and probably wouldn't be that useful as we don't typically mount many things on our hosts.
Deployed to staging, got [this](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/rYk4vrMSEKu?expd_asc=true&expd_back=true&expd_col=_hny.ts&expd_fwd=false&expd_id=qgDFcLBi2Mx&expd_page=25&omitMissingValues=&tab=explore):
My PR removes the usage, available, and utilization off of other drives and just makes the aggregate- so you will only see it this once.

DEVPROD-21298 Move disk usage metrics to root attribute

---

gqlgen.yml
graphql/image_resolver.go
graphql/image_test.go
graphql/models_gen.go
graphql/schema/types/image.graphql
rest/model/image.go
thirdparty/runtime_environments.go
thirdparty/runtime_environments_test.go

DEVPROD-19140
DevProd Infra team requested to start tracking files on images. This is the backend PR to be able to do that.
* Unit tests
* Testing via GraphQL playground on staging

DEVPROD-19140: Create `Image.Files` resolver

---

agent/agent.go
config.go

[DEVPROD-22016](https://jira.mongodb.org/browse/DEVPROD-22016)

DEVPROD-22016 Fix panic in rotateLogger

---

model/lifecycle.go
repotracker/repotracker.go

DEVPROD-22453
Adding greater verbosity as we close in on the issue. It's getting stuck somewhere right after build creation.

DEVPROD-22453 Add even finer detail logs to build creation

---

agent/command/test_selection_get.go
config.go

DEVPROD-22546
pass in the strategies param to TSS

DEVPROD-22546 Pass in strategies to TSS

---

docs/Hosts/Developer-Workstations.md
docs/Hosts/Spawn-Hosts.md

DEVPROD-12258
Add documentation on mounting volumes to hosts after they have been attached

DEVPROD-12258 Add Spawn host mounting instructions

---

graphql/generated.go
graphql/schema/types/task.graphql
graphql/tests/query/task/data.json
graphql/tests/query/task/queries/task.graphql
graphql/tests/query/task/results.json
rest/model/task.go

DEVPROD-21702
Exposes this field so it can be used by the frontend.

DEVPROD-21702: Expose `Task.TestSelectionEnabled` field from GraphQL
