evergreen-ci/evergreen

units/patch_intent.go
[EVG-16678](https://jira.mongodb.org/browse/EVG-16678)
add githash
will reenable github trigger pr after merge and deploy 
tested on staging evg using sandbox module 
https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu1604_unit_tests_patch_41a9fa3c35db31e2c7323cbe048b409688f47e7a_6299184d97b1d307abd53ab6_22_06_02_20_06_38/logs?execution=0
=> Update githash for downstream tasks

model/project_ref.go, rest/data/project_settings.go
[EVG-16797](https://jira.mongodb.org/browse/EVG-16797)
Testing PR #1 !! Should use the before project ref to test Github conflicts since the UI only passes in general settings. Also fixes copying project with github checks.
Discovered in staging, tested locally.
=> EVG-16797 handle merge conflicts on general section correctly

agent/command/generate.go, apimodels/agent_models.go, config.go, model/generate.go, model/generate_test.go, model/task/dependency_graph.go, model/task/dependency_graph_test.go, model/task/task.go, rest/data/generate.go, rest/data/generate_test.go, rest/route/task_generate.go, units/generate_tasks.go
[EVG-16679](https://jira.mongodb.org/browse/EVG-16679)
Cherry pick the changes from #5677 that were reverted and fix the problem.
The fix is just the second commit (https://github.com/evergreen-ci/evergreen/commit/78270ed7918252620792cd480953cd29b2cb768c)
Generate tasks [works in staging](https://spruce-staging.corp.mongodb.com/version/6290ff22b237364300b7b73f/tasks). Without the fix this would have also been broken.
=> EVG-16679 fix generate tasks retry loop

graphql/resolvers.go, model/distro/distro.go, model/event/task_event.go, model/task/task.go, public/static/js/task.js, scheduler/planner.go
[EVG-16650](https://jira.mongodb.org/browse/EVG-16650)
In order to whittle down the event_log collection I'm going to open a few PRs to reduce the daily write volume to the collection. [We've set a 90 day TTL on the events with a TASK r_type](https://jira.mongodb.org/browse/EVG-15227), but even with the TTL task events are still a significant part of the bulk of the collection. The bulk of these are TASK_SCHEDULED events which don't really need to be in the db. Logging these to Splunk instead will reduce the size of the collection over time.
Once we're already logging to Splunk, include additional information about the parameters that determined each task's position in the queue. This way we'll finally have visibility into why a particular task ranked before another task in the queue. …
=> EVG-16650 send task scheduled events to Splunk instead of the db

cloud/pod_util.go, cloud/pod_util_test.go, config_cloud.go, globals.go, public/static/js/admin.js, rest/model/admin.go, rest/model/admin_test.go, rest/route/sns_test.go, service/templates/admin.html, testutil/config.go, units/pod_creation_test.go
Jira: https://jira.mongodb.org/browse/EVG-17026
Add admin settings to map a capacity provider name to the OS/arch that it can run. I also renamed a couple fields in the ECS cluster admin settings, which I fixed in staging (the only place using the ECS settings). I'm going to make a follow-up PR to actually set the capacity provider based on the container's required OS/arch.
Added unit tests. Also tested the admin settings page in local-evergreen.
=> EVG-17026: add admin setting for ECS capacity providers

graphql/resolvers.go, service/templates/projects.html
[EVG-16797](https://jira.mongodb.org/browse/EVG-16797)
Two things found while testing:
1) Added back in the restricted option to the legacy page, which was removed accidentally in https://github.com/evergreen-ci/evergreen/commit/c55a71bdcc27f5f94d485f58cdbc9483f80f172e (cc @bynn )
2) Stepback on save doesn't exist on the new UI so I added the resolver; the front end can be done in https://jira.mongodb.org/browse/EVG-17044 but should be v simple
=> EVG-16797 add stepback resolver and removed field

cloud/ec2.go, cloud/ec2_client.go, cloud/ec2_test.go, cloud/ec2_util.go, units/provisioning_create_host.go
[EVG-16635](https://jira.mongodb.org/browse/EVG-16635)
This change updates our spot instance creation creation fallback logic in order to handle UnfulfillableCapacity errors that we sometimes get back from spot instance creation requests. It also refactors the code to pull the fallback logic into the EC2 cloud manager, so that we don't mix levels of abstraction in provisioning_create_host.go. 
Primarily I added the ability to return errors to our awsClientMock, so that when I pulled the code into our ec2 cloud manager, we could verify that we made the appropriate calls when an error was returned from our AWS client.
=> EVG-16635: Update EC2 spot instance creation to handle UnfulfillableCapacity Errors

agent/command/shell.go, config.go
[EVG-17007](https://jira.mongodb.org/browse/EVG-17007)
remove the expansion warning 
adding a message for only the cases when it doesn't find an expansion is more refactoring than it seems to be worth
=> EVG-17007 Removed confusing error message about expansions

units/crons_remote_fifteen_second.go, units/crons_remote_minute.go
Jira: https://jira.mongodb.org/browse/EVG-17028
Move the pod creation cron populator from the normal remote queue into the remote queue group. This is important because pod creation is performance-sensitive. In the normal remote queue, these jobs would have to wait behind other Amboy jobs and Evergreen should avoid making users wait for longer than necessary for their task to run a container. Moving it to its own dedicated queue within the queue group ensures that pod creation jobs only wait behind other pod creation jobs and not other miscellaneous background jobs.
* Move pod creation cron populator to queue group.
* Move cron period from per minute to per 15 seconds so that it enqueues jobs more frequently.
Didn't write a test for it since it's just changing the Amboy queue, which we …
=> EVG-17028: move pod creation jobs to queue group

model/project_aliases.go, operations/list.go, rest/model/project_event.go, self-tests.yml
[EVG-15871](https://jira.mongodb.org/browse/EVG-15871)
Users have external descriptions of their aliases and instead they should be able to view descriptions set to aliases. The backend was modified to accept descriptions in to the struct (defaulting to an empty string) and in the CLI, to output this description.
As of now, a user cannot create a patch alias with a description. To test, a description was added to the database inside the alias record in the staging database. Then running the command using the staging configuration, you are able to see the description put in. As well, the description shows up nicely on the rest API.
(Please excuse the commits, I had to cherry-pick them from my branches and I'm still getting used to handling them!)
=> EVG-15871 Added description output to the CLI and description to the backend API

model/build/build.go, model/build/db.go, model/lifecycle_test.go, model/task/task.go
[EVG-15622](https://jira.mongodb.org/browse/EVG-15622)
Builds have an issue where the time taken is derived as (finish time -  start time).  However start time does not update with each restart of a build, hence some builds that have multiple restarts over a few days have far too high `time_taken_ms`.
Change has been made such that if a build has been restarted, then calculate time taken as (finish time - activated time) since activated time keeps up with each restart. Otherwise we still calculate time taken as (finish time - start time).
Updated existing unit test. Added cases
=> EVG-15622 Take activated as starting time for builds that have restarted once or more

service/patch.go
[EVG-16293](https://jira.mongodb.org/browse/EVG-16293)
We currently panic  [here](https://github.com/evergreen-ci/evergreen/blob/fa0e2d13b1a7065724e7ebfe36e8d36c298ce382/service/patch.go#L81) if we've hit an error [here](https://github.com/evergreen-ci/evergreen/blob/fa0e2d13b1a7065724e7ebfe36e8d36c298ce382/graphql/util.go#L361-L363). This fixes it.
=> EVG-16293 Add return so that loading a project doesn't panic 

units/check_blocked_tasks.go
[EVG-16810](https://jira.mongodb.org/browse/EVG-16810)
There are tasks with dependencies that don't exist that are hard to identify or reproduce. It looks like they all belong to one user. This PR adds the user to the logging so that we can filter on it. 
Will add a splunk alert once this is merged.
=> EVG-16810 Add error with activated_by to check_blocked_tasks

public/static/js/projects.js, service/project.go, service/templates/projects.html
EVG-14878: https://jira.mongodb.org/browse/EVG-14878
We will now be forcing all projects  except for the mongodb-mongo-* projects to use Cedar test results.
I checked in staging and the Test Results section is no longer on the page.
=> EVG-14878: Remove checkbox to enable Cedar test results from project settings page

model/pod/dispatcher/dispatcher.go, model/pod/dispatcher/dispatcher_test.go
Jira: https://jira.mongodb.org/browse/EVG-16879
This fixes two issues with `removePodsAndTasks`.
1. The [RemovePod test](https://github.com/evergreen-ci/evergreen/blob/8918ac1aae8755d218c8a5ef252e91cc56916cb4/model/pod/dispatcher/dispatcher_test.go#L458) is flaky because [utility.StringSliceSymmetricDifference](https://github.com/evergreen-ci/evergreen/blob/8918ac1aae8755d218c8a5ef252e91cc56916cb4/model/pod/dispatcher/dispatcher.go#L332) is not stable, meaning that when we remove pods/tasks using it, the pods/tasks might be returned in a different order. Since the pods are a set and order in the slice doesn't matter for them, I changed the test to use `assert.ElementsMatch` so it checks set equality instead of slice order equality.
2. Because `utility.StringSliceSymmetricDifference` is …
=> EVG-16879: fix test-model-pod-dispatcher

config.go, service/api.go
[EVG-17062](https://jira.mongodb.org/browse/EVG-17062)
Waited some time for agents to roll over before removing this route after the default cedar config route was migrated to v2. Removing the v1 route would not have been backwards compatible with agents on hosts that were started before [this commit](https://github.com/evergreen-ci/evergreen/pull/5707) was deployed.
=> EVG-17062 Remove legacy cedar config route

model/task_lifecycle.go
[EVG-17097](https://jira.mongodb.org/browse/EVG-17097)
This debug log is no longer needed since [EVG-12923](https://jira.mongodb.org/browse/EVG-12923) has been closed.
=> EVG-17097 Remove single-host task group debug logging

globals.go, model/pod/dispatcher/dispatcher.go, model/pod/dispatcher/dispatcher_test.go, model/task_lifecycle.go, model/task_lifecycle_test.go, units/pod_allocator.go, units/pod_creation.go, units/pod_termination_test.go
Jira: https://jira.mongodb.org/browse/EVG-16880
This is a follow-on to #5720, which added a counter to track each task's number of allocation attempts. When a pod is being terminated and cleaned up, we have to re-allocate new pods for any task that it was supposed to run but could not. However, we don't want to try allocating a container for a task past a certain number of failed attempts, so mark tasks that try to exceed that limit as system-failed. Since we don't support task groups yet, each task gets its own dedicated pod to run it (i.e. there's a 1:1 mapping between container tasks and pods). The implication of this assumption is that if a pod gets terminated (for whatever reason) before it finishes running the task, the one task it was allocated for needs to have at least one more …
=> EVG-16880: system-fail tasks that try to exceed the container allocation limit

graphql/tests/mainlineCommits/data.json, model/task/db.go, model/task/task.go, model/task_build_variant_names_test.go
[EVG-16888](https://jira.mongodb.org/browse/EVG-16888)
Refactors AddBuildVariantDisplayName to use the cached value in the task struct that was introduced in #5715 if it exists. If the field does not exist (On older task documents) We will use the `$lookup` method to get the build variant display name.
Tested locally and staging and as a stand alone db query. Old unit tests should be sufficient as well.
=> EVG-16888 Refactor addBuildVariantDisplayName to use cached field if it exists

globals.go, repotracker/repotracker.go, rest/data/version_test.go
[EVG-17086](https://jira.mongodb.org/browse/EVG-17086)
This adds the Periodic Build requester to MainlineCommits query so that it can be viewed on the UI. 
[Tested on staging](http://localhost:3000/commits/mci?requester=all,gitter_request,git_tag_request,trigger_request,ad_hoc&skipOrderNumber=7828) on the mci project. 
[1340](https://github.com/evergreen-ci/spruce/pull/1340)
=> EVG-17086 Add Support for Periodic Build requester to MainlineCommits Query

model/project_aliases_test.go, model/project_event_test.go
[EVG-17171](https://jira.mongodb.org/browse/EVG-17171)
In ticket [EVG-15871](https://jira.mongodb.org/browse/EVG-15871), a description field to patch aliases was added. This ticket adds that description field to tests.
Unit testing inside of patch_aliases_test.go (adding proper description(s) and testing for its existence after parsing and usage of certain methods). In the 'project_event_test.go', the test compares the aliases and compares the description through it as well.
=> EVG-17171 Added testing for the description field in patch aliases

model/pod/pod.go, model/pod/pod_test.go, rest/route/pod_agent.go, rest/route/pod_agent_test.go
Jira: https://jira.mongodb.org/browse/EVG-17169
I couldn't reproduce the issue where the agent would not check into the app server. When I tested with a container task, it successfully started the agent and asked for the next task. Since the container task lifecycle seems to be working as expected (up until the task actually runs on the agent), I did some small improvements for the next task route. Only the first one is actually necessary from a correctness perspective, but the second one is a nice to have.
* Set the pod status to running once the agent requests the next task.
* Ensure that setting the running task is a no-op if that task has already been assigned to the pod.
Tested that [a container task](https://spruce-staging.corp.mongodb.com/task/evg_lint_generate_lint_patch_353be1934d …
=> EVG-17169: transition pod state and fix dispatch idempotency during next task

service/host.go, service/task.go, service/task_history.go, service/version.go, service/waterfall.go, trigger/payloads.go, trigger/task_jira.go
[EVG-17047](https://jira.mongodb.org/browse/EVG-17047)
BF tickets don't redirect with every link to the spruce UI. This adds the parameter to the BF ticket links to redirect to the spruce UI and adds the redirection logic to the pages associated that did not have it. As well, updated redirection logic to be consistent with new methods.
Created a BF ticket and tested all the links that should have changed (host, project- waterfall/project health, task history). [This is the BF created in testing.](https://jira.mongodb.org/browse/EVG-17188)
=> EVG-17047 Redirect users to spruce UI in BF ticket links

agent/command/generate.go, agent/internal/client/mock.go, apimodels/agent_models.go, config.go, rest/route/task_generate.go
[EVG-16977](https://jira.mongodb.org/browse/EVG-16977)
#5693 replaced the `Errors` field with an `Error` field. Now that that's been live for a while (it was deployed 6/14) it's a (near?) certainty that there are no hosts still running a task with the old agent.
=> EVG-16977 remove errors field

model/task/task.go, model/task_lifecycle.go
[EVG-16755](https://jira.mongodb.org/browse/EVG-16755)
This is addressing a subset of the issues with [this task](https://spruce.mongodb.com/task/mongodb_mongo_v4.4_windows_display_multiversion_319d8d8145fb5893ab3bf5d077730226f3f2af7c_22_04_06_18_31_56/execution-tasks?execution=0&sortBy=STATUS&sortDir=ASC&sorts=STATUS%3AASC) (a display task that has been generated from its execution task, but the execution task fails/strands on first execution). This PR addresses the fact that despite the display task's execution tasks have system failed, the display task's first execution simply reads `failed` with no relevant failure details.  
What looks like happened is an empty `status_details` got passed into `MarkEnd`, and when this happens we assign the task's status to simply `failed`. I've added …
=> EVG-16755 Add debug logging to detect ending of display tasks with no failure details

cloud/ec2.go
[EVG-16655](https://jira.mongodb.org/browse/EVG-16655)
Workstations currently don't allow gp3, to use gp3 as a volume type, it can be added to the volume types. The Spruce UI still needs compatibility, I made a ticket linked to this one relating to it.
Deployed on staging and made a volume with gp3 as the type (before this change, gp3 would result in an error message and a list of valid types. Now it is allowed and invalid types are responded with an error message including gp3). I added screenshot on JIRA ticket as showing of the test.
=> EVG-16655 Add gp3 to existing valid volume types

cloud/ec2.go
[EVG-16655](https://jira.mongodb.org/browse/EVG-16655)
Workstations currently don't allow gp3, to use gp3 as a volume type, it can be added to the volume types. The Spruce UI still needs compatibility, I made a ticket linked to this one relating to it.
Deployed on staging and made a volume with gp3 as the type (before this change, gp3 would result in an error message and a list of valid types. Now it is allowed and invalid types are responded with an error message including gp3). I added screenshot on JIRA ticket as showing of the test.
(Reopen after revert due to bad merge commit message)
=> EVG-16655 Add gp3 to existing valid volume types 

model/pod/dispatcher/dispatcher.go, model/task/task.go, model/task/task_test.go, units/pod_termination.go, units/pod_termination_test.go
Jira: https://jira.mongodb.org/browse/EVG-17195
When a pod is about to terminate, tasks that are waiting to be dispatched to that pod are de-allocated to indicate that they need a new pod to run them. However, in the case that a pod is about to be terminated but it has already been dispatched to the pod, that stranded container task also has to be de-allocated so that when it restarts with a new execution, it gets allocated a new container to run it. I added some logic to ensure that the stranded task is re-allocated when the pod is abruptly terminated.
=> EVG-17195: deallocate stranded container task during pod termination

model/task_lifecycle.go, model/task_lifecycle_test.go
[EVG-16772](https://jira.mongodb.org/browse/EVG-16772)
Although I was not able to emulate this error in staging I have noticed some logic in `UpdateDisplayTaskForTask` where the display task's start time is set to the lowest value of all of its execution tasks' start times. What seems to be happening is some execution tasks have nil / zero start time set are being detected as the "lowest" start time and updating the display task as such. Small change has been made to not update the display task's start time if the execution task we are inspecting has a nil / zero start time.
Added case to unit test for `UpdateDisplayTaskForTask`
=> EVG-16772 don't set display task start time for exec tasks that have zero start time

scripts/verify-client-version-update.sh, self-tests.yml
[EVG-13262](https://jira.mongodb.org/browse/EVG-13262)
linter now checks that we change the client version when something in the operations package is edited 
made a patch with a change in operations and agent and verified that both checks failed 
https://spruce.mongodb.com/version/62c4515f7742ae4c1f3580ec/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> EVG-13262 Add check for CLI version string update

model/project_ref.go, model/project_ref_test.go, rest/route/service.go, rest/route/stats.go, rest/route/stats_test.go
EVG-17099: https://jira.mongodb.org/browse/EVG-17099
- Remove the Cedar test stats middleware.
- Remove the `presto` query parameter from the test stats route.
- Add temporary method that returns if a given identifier is a Server/Resmoke project (anything that beings with `mongodb-mongo-` or `mongosync`).
- Use the Presto client to fetch all non-Server/Resmoke projects.
I tested that this works in staging.
=> EVG-17099: Use Presto test stats for all non-Server projects

config.go, model/patch/cli_intent.go, operations/patch_util.go
[EVG-16866](https://jira.mongodb.org/browse/EVG-16866)
Enables users to use the finalize flag with regex tasks/variants and mixing regex tasks with a list of variants or regex variants with a list of tasks.
Running `evergreen patch --rv '.*' --rt '.*' -f` results in an error saying that no tasks/variants are listed. After these commits, running the same command will give a patch link that has all the tasks on all variants to be ran (the regex provided is all). If you run `evergreen patch -t generate-lint --rv lint -f` works and schedules the task 'generate-lint' on the 'lint' variant.
=> EVG-16866 Allow finalize flag with regex tasks/variants

service/api_task.go
[EVG-17250](https://jira.mongodb.org/browse/EVG-17250)
I'm not sure why we had this logging to begin with but stack is large to log, and this route hasn't been a problem area where we've needed to see logging for so we should remove it.
=> EVG-17250 remove error logging for assign next task

rest/route/pod_agent.go, service/api_task.go
[EVG-17242](https://jira.mongodb.org/browse/EVG-17242)
Changes in [this PR](https://github.com/evergreen-ci/evergreen/pull/5737) were made to use `IsPartOfDisplay` to reduce the amount of DB calls used when retrieving display task info for ending tasks, because it will only call `GetDisplayTask` for older tasks that have a nil `DisplayTaskId`.
However in cases where `DisplayTaskId` is set but `DisplayTask` is nil, this code may panic. Changed code to no longer make use of `DisplayTask`.
=> EVG-17242 Use DisplayTaskId field for showing end task stats in splunk

apimodels/agent_models.go, model/task/task.go, model/task_lifecycle.go
[EVG-16755](https://jira.mongodb.org/browse/EVG-16755)
There were [a few](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22evergreen%22%20%22detail%20status%20was%20empty%2C%20setting%20to%20failed%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-30d%40d&latest=now&sid=1657039406.1594061) occurrences of the debug statements put in place in [this PR](https://github.com/evergreen-ci/evergreen/pull/5759/files) that caught display tasks ending with a nil `TaskEndDetails` property, resulting in a generic "failed" status shown in API and UI despite the fact that the parent status should be something else. Here is [one such task](https://spruce.mongodb.com/task/mongodb_mongo_master_enterprise_rhel_80_64_bit_multiversion …
=> EVG-16755 remove debug logging and modify checkResetDisplayTask

makefile
[EVG-16945](https://jira.mongodb.org/browse/EVG-16945)
When you run `dist-staging` it's always to build a dist for staging. Since no one should be downloading the executable from staging it makes sense to skip signing on staging.
Separately, switch the explicit make invocation for $(MAKE) since that's what [the docs](https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html#MAKE-Variable:~:text=Recursive%20make%20commands%20should%20always%20use%20the%20variable%20MAKE%2C%20not%20the%20explicit%20command%20name%20%E2%80%98make%E2%80%99) recommend.
Running
```
SIGN_MACOS=1 make dist-staging
```
Does not attempt to sign the executable. It continues to only build the staging platforms.
=> EVG-16945 clear SIGN_MACOS for staging dist

model/task/task.go, model/task_lifecycle_test.go
[EVG-17297](https://jira.mongodb.org/browse/EVG-17297)
Blocked is used all over the place to determine statuses and ordering but doesn't actually consider OverrideDependencies. This results in confusing statuses/API results, and prevented us from scheduling an unblocked task: https://github.com/evergreen-ci/evergreen/blob/799b017d6c69d387981fae3322bfcf0b0854d79c/service/api_task.go#L689-L710
Checking that existing tests pass and added a test for display status that would fail without the change.
=> EVG-17297 consider overrideDependencies when checking if task blocked

graphql/generated.go, graphql/project_vars_resolver.go, graphql/schema/types/project_vars.graphql
[EVG-17926](https://jira.mongodb.org/browse/EVG-17926)
The `PrivateVars` and `AdminOnlyVars` resolvers construct lists from [maps](https://github.com/evergreen-ci/evergreen/blob/1c0d68ff52d836fd7fcca4df84beb745afd1db10/rest/model/project_event.go#L39-L40) to return to the front end. This results in no guaranteed order, with a differently ordered list sent in each `ProjectEventLogs` request. This change in ordering caused privateVars updates to appear in every event log entry.
To fix, return alphabetically sorted private and admin only vars so that we do not inaccurately report an event.
Before:
After:
- Tested updated backend with current `main` branch of Spruce in staging
=> EVG-17926: Sort private and admin only vars

agent/command/s3_copy.go, agent/command/s3_get.go, agent/command/s3_put.go, config.go, service/api.go
[EVG-17010 ](https://jira.mongodb.org/browse/EVG-17010 )
The fact that the “host not assigned to run tasks” errors are coming from the /files endpoint is a red herring. Based on both Splunk logs for the host and host event logs, it’s task timeouts that are the Issue: the host ran the older task, timed out, then ran the newer task. The /files endpoint is simply the last thing to run on the task so it’s what was likely running when they timed out.
If the agent has already moved on to a new task we don't want it to keep doing things for a previous task, because that can cause issues for later tasks. We therefore want the agent s3 commands to respect the context passed to them rather than use context.Background(). That way, if it's making requests to the S3 API, the app server won't know that …
=> EVG-17010 Fix "host not assigned to run task" errors

graphql/query_resolver.go, graphql/tests/buildVariantsForTaskName/data.json, model/task/db.go, model/task_build_variant_names_test.go
[EVG-17040](https://jira.mongodb.org/browse/EVG-17040)
Given that `FindUniqueBuildVariantNamesByTask` looks back no more than 50 versions and build variant display names have been cached in structs for the past 30 days, it seems appropriate now to directly read the `BuildVariantDisplayName` on a task when reading variant data for the task history page rather than performing a facet/lookup combination.
Augmented existing unit tests given new assumptions when retrieving BV display name, and tested in staging that task history page remains accurate.
=> EVG-17040 Remove pipeline stage looking for tasks without BV display name set

model/project_ref.go, model/project_ref_test.go
[EVG-17331](https://jira.mongodb.org/browse/EVG-17331)
I discovered this during local setup, since local setup's development fixtures don't set a default project. This occurs for anonymous users without any cookies hitting the waterfall endpoint
Added unit tests to verify that the function doesn't fail. Also verified locally by clearing cookies and hitting localhost:9090
=> EVG-17331: Use proper sort key in FindFirstProjectRef.

service/build.go, service/host.go, service/task.go, service/task_history.go, service/user.go, service/waterfall.go
[EVG-17239](https://jira.mongodb.org/browse/EVG-17239)
Update all places which RedirectSpruceUsers uses a variable (like build or task) to check for nil before execution.
Same testing as RedirectSpruceUsers, just moving nil checks.
=> EVG-17239 Update nil dereferences in code relating to RedirectSpruceUsers

config.go, config_db.go, config_test.go, rest/model/admin.go, rest/model/admin_test.go, testutil/config.go
[EVG-14769](https://jira.mongodb.org/browse/EVG-1469)
added instance role section on the admin settings 
not adding to the legacy ui (we can add it to the new admin page later)
unit tests
=> EVG-14769 Add instance role to admin settings

model/alertrecord/alert_bookkeeping_test.go
Jira: https://jira.mongodb.org/browse/EVG-17318
I fixed this test. This test is being flaky because the rounded timestamps could be rounded up or down, which could lead to differing timestamps. For example, if the alert time is recorded as 10:25:00.490 and the assertion is checked at 10:25:00.510, the alert time will round down to 10:25:00 and the assertion's `time.Now()` will be rounded up to 10:25:01. The new check correctly verifies that the alert time and `time.Now()` are within a second of each other.
N/A
=> EVG-17318: fix flaky alertrecord test

config_presto.go, environment.go, mock/environment.go, model/stats/presto_query.go, rest/route/service.go
EVG-17241: https://jira.mongodb.org/browse/EVG-17241
This change sets up the Presto DB client once in the environment, similar to how we set up the Mongo client.
I tested that this works in staging.
=> EVG-17241: Fix goroutine leak from the Presto DB client

model/lifecycle.go, model/lifecycle_test.go
[EVG-17006](https://jira.mongodb.org/browse/EVG-17006)
build wasnt being updated when things were being unscheduled 
https://spruce-staging.corp.mongodb.com/version/62e42a31b237363212bb7a51/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
version updated now 
unit test
=> EVG-17006 Fetch build ids for deactivating version

config_amboy.go, environment.go, go.mod, go.sum, public/static/js/admin.js, rest/model/admin.go, rest/model/admin_test.go, service/templates/admin.html, testutil/config.go
Jira: https://jira.mongodb.org/browse/EVG-17370
Add admin settings to apply Amboy queue settings to named queues using a regexp instead of exact name match.
Added admin settings unit tests and tested the settings in local Evergreen.
=> EVG-17370: add option to apply Amboy queue settings for queues matching a regexp

model/project_ref.go, model/project_ref_test.go
[EVG-17366](https://jira.mongodb.org/browse/EVG-17366)
We don't want to set the repo identifier to the project's identifier. 
Added to existing unit test.
=> EVG-17366 Don't set repo identifier

model/project_ref.go, model/project_ref_test.go
[EVG-17362](https://jira.mongodb.org/browse/EVG-17362)
Because the function set the project to an empty struct when defaulting to repo, it ended up resetting the identifier, display name, and disabled field as well. This adds some casing to avoid that. 
Added to unit test and tested on staging.
=> EVG-17362 Fix project disappearing when defaulting to repo 

makefile
Jira: https://jira.mongodb.org/browse/EVG-17386
Allow re-compiling if the Go module dependency files are changed. I also did some small tidying up of make variables.
I'm going to also apply this same change to all the PLT repos that use Go modules once it's approved.
I re-compiled and it depended on modifications to go.mod/go.sum.
=> EVG-17386: ensure compilation make recipe depends on go module files

config_presto.go, rest/model/admin.go, service/templates/admin.html
EVG-17390: https://jira.mongodb.org/browse/EVG-17390
This fixes a bug that was causing the presto config section to be wiped in the DB every time the admin settings were updated. 
- Add the Presto settings to the UI and the API settings model.
- Remove the field `SessionProperties` since it was not being used / not needed and just made the UI more complicated.
- Remove[ Bynn's workaround](https://github.com/bynn/evergreen/blob/766a2deb8469c1f6b627991f2dad615dd0a2a16a/rest/model/admin.go#L2393-L2394) to skip the Presto config section when updating the admin events page.
I tested that the Presto settings both load correctly and are updated in the UI in staging.
=> EVG-17390: Add Presto admin settings to the UI

graphql/util.go, model/task/task.go, model/version_modification.go
[EVG-16730](https://jira.mongodb.org/browse/EVG-16730 )
UnschedulePatchTasks follows a pretty simple/reused path so it's not clear to me why this is reported to occasionally take 15 minutes for large patches. It looks like this only seems to happen for aborted tasks also. I've added some logging to try and pinpoint what part is causing an issue.
=> EVG-16730 add debugging to understand long unschedule times

service/task.go, service/task_test.go
Currently we don't return the error, but we also send an error
response globally, causing this to 500 in the event of a Cedar
outage. This changes the logic so that we will return no test
results if Cedar is down but otherwise continue to process the
response.
[EVG-16490](https://jira.mongodb.org/browse/EVG-16490)
This updates getTestResults to not send a 500 response if for some reason Cedar is down. It now silently logs the error and the request continues to process normally.
I added testing to make sure that we do in fact return a nil list of results if Cedar is unavailable. Also, the function no longer has access to the response and request objects so it is impossible for it to send a 500 response code header.
=> EVG-16490: Don't return 500s when getting test results fails.

model/project_ref.go, model/project_ref_test.go
[EVG-17395](https://jira.mongodb.org/browse/EVG-17395)
Duplicate project didn't work because verifyOwner would make sure that the owner and repo weren't nil, which wasn't true if a project was defaulted to the repo. I updated the function to also check the repo. 
=> EVG-17395 Fix verify owner/repo 

graphql/mutation_resolver.go, model/project_ref.go, model/project_ref_test.go, rest/data/project_settings.go, rest/model/project.go, rest/route/project.go, rest/route/repo.go, service/project.go, validator/project_validator_test.go
Jira: https://jira.mongodb.org/browse/EVG-16908
This updates the model for container secrets so that they're suitable for Secrets Manager. They don't actually store the secrets in Secrets Manager until [EVG-16913](https://jira.mongodb.org/browse/EVG-16913).
The gist of how it's going to work is that, through the REST model, the user can either send Evergreen a secret to store or ask Evergreen to give them their secret in plaintext. If they ask us to store a repo cred, this is a special case because it must be stored in Secrets Manager as a JSON-encoded string. The JSON-encoded credentials will then be stored (in [EVG-16913](https://jira.mongodb.org/browse/EVG-16913)) in Secrets Manager. After it's stored, if Evergreen ever needs to retrieve the secret value in plaintext to give back to …
=> EVG-16908: create model for container secrets

model/lifecycle.go, model/lifecycle_test.go, model/task/db.go, model/task/db_test.go, model/task/task.go, model/task/task_test.go, model/task_lifecycle.go
[EVG-17126](https://jira.mongodb.org/browse/EVG-17126)
_(This is a boat load of investigation context and I apologize for that)_
We have been seeing occasional [radical spikes](https://mongodb.splunkcloud.com/en-US/app/search/search?display.page.search.mode=verbose&dispatch.sample_ratio=1&q=search%20index%3Devergreen%20metadata.level%20%3E%3D%2070%20%22wrong%20secret%22%0A%7C%20timechart%20count&earliest=1654117800&latest=1657833600&workload_pool=standard_perf&display.page.search.tab=visualizations&display.general.type=visualizations&sid=1658259124.1997534) of 'wrong task secret' error rates on specific days, where the occurrences can reach 100,000+ errors rapidly whereas most other days have far fewer occurrences around 1,000 total.
Looking at the bulk of problematic tasks during these …
=> EVG-17126 Do not allow resetting non-complete tasks

environment.go
Jira: https://jira.mongodb.org/browse/EVG-17370
I drive-by noticed a small bug while doing outage things (which has nothing to do with the outage). This should properly apply the queue options when using a regexp instead of a name to match the queue.
N/A
=> EVG-17370: do not skip queue regexp settings

rest/data/generate.go
[EVG-17340](https://jira.mongodb.org/browse/EVG-17340)
doesnt repeat because it returns 400 instead of 500
https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22evergreen-staging%22%20%20nothing_here_release_my_first_generator_patch_edc6cd0b9f8a1b8481bcf14bc75f0a819a71aa7a_62f42d929dbe3237cc395d3f_22_08_10_22_13_44%20bynnbynn&display.page.search.mode=fast&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1660240440&latest=1660240500&sid=1660240751.6284612
doesnt repeat 
and is sucessful 
https://spruce-staging.corp.mongodb.com/task/nothing_here_release_my_first_generator_patch_edc6cd0b9f8a1b8481bcf14bc75f0a819a71aa7a_62f42d929dbe3237cc395d3f_22_08_10_22_13_44/logs?execution=1
=> EVG-17340 Update status code for task already generated error

agent/internal/client/base_client.go, agent/internal/client/host_client.go, agent/internal/client/host_methods.go, agent/internal/client/pod_methods.go, agent/internal/client/request.go, agent/internal/client/request_test.go, config.go
[EVG-17450](https://jira.mongodb.org/browse/EVG-17450)
Following the merge of[ server-side](https://github.com/evergreen-ci/evergreen/pull/5860) changes to the agent routes in an effort to reduce the chance of agent errors during deployment, this PR represents the agent-side changes that were a part of [EVG-16989](https://github.com/evergreen-ci/evergreen/pull/5811/files).
Ran tasks and versions in staging.
=> EVG-17450 Agent-side v2 upgrades

model/project_ref.go, model/project_ref_test.go
[EVG-17518](https://jira.mongodb.org/browse/EVG-17518)
- Because some queries depend on a project having an owner/repo, we shouldn't clear these fields when "Default to Repo" is clicked on the General settings page
- Allow owner/repo to be empty only if project is disabled
- Updated unit tests, tested on UI
=> EVG-17518: Don't clear owner or repo when defaulting project

config.go, operations/agent.go
Jira: https://jira.mongodb.org/browse/EVG-17519
Add a new flag so we can check the agent revision of a particular binary. This is helpful when diagnosing host provisioning issues because it can be hard to tell what particular version the agent is running on.
This seemed like a minor change, so I only checked that it worked locally using `evergreen agent --version`.
=> EVG-17519: add flag to print current agent version

model/container_task_queue.go, model/pod/dispatcher/dispatcher.go, model/project_ref.go, service/project.go
[EVG-17387](https://jira.mongodb.org/browse/EVG-17387)
Attached projects in the project dropdown were displaying their repo's display name when they did not have one set (i.e. empty string in the db). This is because the function to fetch the projects (`FindProjectRefsByIds`) was merging the projects with their repos, resulting in the displayName field being overwritten. To fix:
- Rename `FindProjectRefsByIds` to `FindMergedProjectRefsByIds`
- Added a new `FindProjectRefsByIds` that does not merge the projects and repos
- Replace all existing uses of `FindProjectRefsByIds` with `FindMergedProjectRefsByIds` to maintain previous functionality
Front end now renders attached project names correctly. If a project lacks a display name, its identifier is used.
=> EVG-17387: Fix project dropdown naming

model/task_lifecycle.go, model/task_lifecycle_test.go
[EVG-16983](https://jira.mongodb.org/browse/EVG-16983)
Adds checks to test if a display task has ResetFailedWhenFinished set to true (overriden by RestartWhenFinished)
Existing unit tests and TBA testing
=> EVG-16983 Update stranded restarts to account for ResetFailedWhenFinished

graphql/directive_test.go, graphql/resolver.go
[EVG-17558](https://jira.mongodb.org/browse/EVG-17558)
Probably my fault this wasn't caught before; there's a special permission for project creation we should test instead of what we test here.
Removed the older permission that was being checked from the test to verify that the actual permission needed is enough.
=> EVG-17558 fix create project directive

graphql/mutation_resolver.go, model/project_ref.go, model/project_ref_test.go, rest/data/project.go, rest/data/project_settings.go, rest/route/project.go, service/templates/projects.html
[EVG-17556](https://jira.mongodb.org/browse/EVG-17556)
Check webhooks during project creation and when owner/repo changes.
Created https://github.com/evergreen-ci/spruce/pull/1407 to fix spruce text.
Tested with a local project and verified that we attempted to setup webhooks with a new project.
=> EVG-17556 check webhooks at more places

model/task/task.go, model/task/task_test.go, model/task_lifecycle_test.go
Jira: https://jira.mongodb.org/browse/EVG-17550
I'm splitting up this ticket so there will be a follow-up PR to re-assess the task's container allocation state during pod allocation to avoid unnecessarily giving a task more pods to run it. For now, just resetting the container allocation state when the task finishes should be good enough to allow tasks to restart in the normal way, barring edge cases like tasks whose agents abruptly stop (which is supposed to be handled in [EVG-16883](https://jira.mongodb.org/browse/EVG-16883) and [EVG-16884](https://jira.mongodb.org/browse/EVG-16884)).
=> EVG-17550: unset container allocation when task finishes

model/pod/dispatcher/db.go, model/pod/dispatcher/db_test.go, units/pod_allocator.go
Jira: https://jira.mongodb.org/browse/EVG-17550
This is the follow-up PR to #5878 to ensure that we do not wastefully allocate more pods when tasks are deallocated. If the task does not need another pod allocated to it, the task is just re-marked as allocated without giving it another pod.
Updated pod allocator unit tests.
=> EVG-17550: check number of pods allocated before allocating more

agent/command/generate.go, agent/command/generate_test.go, agent/internal/client/mock.go, config.go
[EVG-16837](https://jira.mongodb.org/browse/EVG-16837)
Since the merging of [this PR](https://github.com/evergreen-ci/evergreen/pull/5507) the generate tasks job uses scopes and has been moved to a single queue within the queue group. Some of the retry logic within the agent was structured to retry on error in case of a race between jobs. Now, if an error is encountered in generate.tasks the command will fail without retry.  
I did not remove the entire retry block, and we are still checking for the successful completion of a spawned generate tasks job for the given task. 
Tested generate.tasks in staging successfully. Added new unit test and mock property to test a failure response from polling generate.tasks.
=> EVG-16837 Remove generate tasks retry logic

graphql/generated.go, graphql/schema/types/user.graphql, model/user/user.go, rest/model/user.go
[EVG-15841](https://jira.mongodb.org/browse/EVG-15841)
Adds a date format field for a user this will be used to persist the date formatting a user decides to view dates in.
=> EVG-15841 Add dateFormat field to user struct

agent/agent_command_test.go, agent/agent_test.go, agent/agent_timeout_test.go, agent/command/archive_auto_extract_test.go, agent/command/archive_tarball_create_test.go, agent/command/archive_tarball_extract_test.go, agent/command/archive_zip_create_test.go, agent/command/archive_zip_extract_test.go, agent/command/attach_artifacts_test.go, agent/command/generate_test.go, agent/command/git_push_test.go, agent/command/git_test.go, agent/command/host_create_test.go, agent/command/s3_pull_test.go, agent/command/s3_push_test.go, agent/command/s3_put_test.go, agent/command/util_test.go, agent/directory_test.go, agent/internal/client/timeout_sender_test.go, agent/logging_test.go, agent/util/archive_tar_test.go, model/host/hostutil_test.go, operations/agent_monitor_test.go, operations/fetch_test.go, operations/host_spawn_test.go, operations/host_test.go, operations/metabuild/model/golang_test.go, operations/model_test.go, operations/patch_util_test.go
[EVG-17574](https://jira.mongodb.org/browse/EVG-17574)
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := os.MkdirTemp("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
Most of the tests that I modifed can be run locally without issues. Some tests required the `evg_settings.yml` which I …
=> EVG-17574: use `T.TempDir` to create temporary test directory

rest/route/stats.go
[EVG-17433](https://jira.mongodb.org/browse/EVG-17433)
Make sure we have the actual ID for the task/test stat routes. The test one is a bit ugly but I think is fine since we won't need to get the identifier forever.
=> EVG-17433 check project id for stats routes

go.mod, go.sum, model/pod/definition/db.go, model/pod/definition/db_test.go, model/pod/definition/definition.go, model/pod/definition/definition_test.go, units/crons.go, units/crons_remote_hour.go, units/pod_creation.go, units/pod_definition_cleanup.go, units/pod_definition_cleanup_test.go, units/pod_definition_creation.go, units/pod_definition_creation_test.go
Jira: https://jira.mongodb.org/browse/EVG-16900
Create job to clean up stale unused pod definitions after they pass a TTL. I arbitrarily set it to 30 days, but we could change it if it's too low/high.
=> EVG-16900: clean up stale pod definitions

agent/agent_test.go, agent/command/s3_put_test.go, agent/logging_test.go
Jira: https://jira.mongodb.org/browse/EVG-17582
In Windows, deleting a directory will fail if there's a process that's actively using it or there's an unclosed file handle (which is a resource leak). I had to tweak the tests where this was relevant.
* One failing agent test is checking the expected behavior of the agent that if a command times out, the agent should continue on without waiting for the command to finish. Since the command exits asynchronously, there will be a race between the asynchronous command exiting and the main testing thread attempting to clean up that command's directory when the command may not be exited yet. I just reverted this to its previous temporary directory usage since there's no easy way to wait until the command finishes. As to why removing the directory …
=> EVG-17582: fix flaky Windows tests

model/event/pod.go, model/event/pod_test.go, model/pod/db.go, model/pod/db_test.go, model/pod/pod.go, model/pod/pod_test.go, rest/route/pod_agent.go, rest/route/pod_agent_test.go, rest/route/sns.go, units/pod_creation.go, units/pod_creation_test.go, units/pod_definition_creation.go, units/pod_termination.go
Jira: https://jira.mongodb.org/browse/EVG-17562
* Decommission pods that have no tasks to dispatch. This is just small extra safety in case enqueueing the pod termination job fails to ensure that the pod will refuse to dispatch tasks until it's terminated.
* Allow pod status to be updated with optional reason indicating why the status got updated. The reason makes it more traceable in the event logs why the system took particular actions on the pod.
=> EVG-17562: decommission pods that have no tasks to dispatch

cloud/pod_util.go, cloud/pod_util_test.go, go.mod, go.sum, rest/route/sns_test.go, units/container_secret_cleanup.go, units/container_secret_cleanup_test.go, units/pod_allocator.go, units/pod_allocator_test.go, units/pod_definition_cleanup_test.go
Jira: https://jira.mongodb.org/browse/EVG-16902
* Add a job to clean up container secrets that were created but never stored in Evergreen's DB.
* Fix a flaky pod definition cleanup test.
Added unit tests. I also spot checked that running the job cleaned up stranded secrets in Secrets Manager.
=> EVG-16902: clean up stranded container secrets

units/crons.go, units/crons_remote_hour.go, units/pod_definition_cleanup.go, units/pod_definition_cleanup_test.go, units/pod_definition_creation_test.go
Jira: https://jira.mongodb.org/browse/EVG-16901
* Add more cleanup to the pod definition cleanup job to delete any pod definitions that are not tracked in Evergreen's DB.
* Add cron populator for cleanup jobs and put it behind a feature flag until prod has the necessary infrastructure and admin settings to actually run the jobs.
=> EVG-16901: clean up stranded pod definitions

model/project_aliases.go, model/project_configs_test.go, service/project.go, validator/project_validator.go, validator/project_validator_test.go
[EVG-17510](https://jira.mongodb.org/browse/EVG-17510)
The modify project route returns an error when PR testing is enabled and the PR patch definition list is empty.  Since PR patch definitions can now be defined in YAML, this change ignores that error if "version control" is enabled on the project page.
Also fixed a few things in project validation including a missing nil check for build baron plugins and automatically infer alias names to YAML defined aliases so that things like `alias: github_pr` aren't necessary to write in YAML.
Updated existing unit tests. 
Enabled version control on the sandbox project in staging and emptied the PR patch definitions, and replaced them with YAML definitions. Staged a few PRs using this YAML to confirm it was working.
[Example …
=> EVG-17510 Allow emptying Github PR aliases when PR testing is enabled

agent/command/assume_ec2_role.go, config.go
The [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) API has the following pattern constraint:
```
[\w+=,.@-]*
```
`time.Now().String()` returns a string like the following:
```
2009-11-10 23:00:00 +0000 UTC m=+0.000000001
```
Which does not match the pattern constraint.
Using `time.Now().Unix()` matches the pattern constraint and should mitigate the `ValidationError` returned by the AWS API.
See [EVG-17606](https://jira.mongodb.org/browse/EVG-17606)
=> fix(EVG-17606): assume role session name

agent/command/results_native.go, config.go
[EVG-16886](https://jira.mongodb.org/browse/EVG-16886)
Currently multi-line log files are uploaded on a single line in the attach.results command.  This causes the HTML log page to highlight the entire document as the "first line". Change has been made to split these logs accordingly.
Deployed to staging and ran attach.results on the sandbox project with two sample raw logs, one delimited by `\n` line breaks and one delimited by `\r\n` line breaks and checked that both html log pages were divided by line appropriately.
=> EVG-16886 Split raw test logs by line breaks

config_cloud.go, model/pod/pod.go, model/pod/pod_test.go, model/project_ref.go, rest/model/admin.go, rest/model/admin_test.go, service/project.go, service/templates/admin.html, testutil/config.go, validator/project_validator.go, validator/project_validator_test.go
Jira: https://jira.mongodb.org/browse/EVG-17388
* Add admin setting for max CPU and memory for ECS. This is to ensure that users can't specify a CPU/memory value that exceeds the amount available for the EC2 instance type.
* Check CPU and memory limit during validation.
* Check CPU and memory limit during pod creation. This is to ensure that the limit is enforced even if the limit changes after the task already exists (such as restarting a very old task that may exceed the current limits).
Added unit tests. I checked with local Evergreen that the admin settings work in an e2e way.
=> EVG-17388: ensure pods cannot exceed max global CPU/memory

model/pod/dispatcher/dispatcher_test.go, model/pod/pod.go, model/pod/pod_test.go, rest/route/pod_agent_test.go
Jira: https://jira.mongodb.org/browse/EVG-17572
Add an extra safety check to ensure that we do not try running more tasks on a pod once it's been assigned a task. This is only meant as a temporary measure and will probably need more complex logic once task groups are supported to decide when a pod can no longer be reused.
=> EVG-17572: decommission pods once they have been assigned a task

rest/route/pod_agent.go, rest/route/pod_agent_test.go
[EVG-17224](https://jira.mongodb.org/browse/EVG-17224)
Change made to terminate a pod when task dispatching is disabled, since it is an unnecessary cost to keep pods alive that are not going to actually be running any tasks.
Added testing confirming that when dispatching is disabled that the pod termination job enqueues and terminates the pod successfully.
=> EVG-17224 Terminate pod when task dispatching is disabled

rest/data/project.go, rest/data/project_settings.go
Jira: https://jira.mongodb.org/browse/EVG-16907
This is a small bugfix to ensure that newly-created projects that don't have an ID have their new pod ID populated correctly. Originally, the container secrets were copied before inserting it into the DB, but [for new projects that don't explicitly set an ID, the ID is not set until `Add` populates it](https://github.com/evergreen-ci/evergreen/blob/04dae53af29c217ae84b6dbd8d13620c893c977d/model/project_ref.go#L459-L461). I moved it so that the container secrets are set after the project is inserted so the project ID is set.
Existing tests should be sufficient.
=> EVG-16907: handle creating project secrets for new projects without an ID

rest/data/project.go, rest/route/project.go
Jira: https://jira.mongodb.org/browse/EVG-16907
I forgot about [the nil interface checking rule](https://mangatmodi.medium.com/go-check-nil-interface-the-right-way-d142776edef1), so checking for a non-nil Secrets Manager client is insufficient because an interface (`cocoa.SecretsManagerClient`) wrapping a nil pointer (`*BasicSecretsManagerClient`) is not nil. It seems like setting up container secrets _should_ happen (or else the project can't run container tasks), but we have to wait until Secrets Manager is available to production.
Not really testable, so I just did it by inspection.
=> EVG-16907: fix temporary nil interface check

model/host/host.go, model/task_lifecycle.go, units/task_monitor_execution_timeout.go, units/task_stranded_cleanup.go
Jira: https://jira.mongodb.org/browse/EVG-16883
This is some pre-work to actually handle stranded container tasks because of some tech debt in the stranded task jobs. There will be a follow-up PR to actually handle stranded container tasks in these jobs.
I still think these jobs have some issues in term of having overlapping (and not quite correct) functionality, but I didn't want to address all those issues in this cleanup PR. I'll include some notes in the follow-up PR on how we might clean up these jobs further, because I believe the task heartbeat timeout job might subsume all of the stranded task job's functionality.
* Use Amboy retryable job features rather than manually re-enqueueing task heartbeat timeout jobs.
* Remove unused fields (such as task execution number) from task …
=> EVG-16883: refactor existing stranded task job logic

units/host_allocator.go
[EVG-17379](https://jira.mongodb.org/browse/EVG-17379)
If a distro is disabled we shouldn't run the host allocator for it. I think it makes sense to run the beginning half of the job, though, since we still want to clean up stale initializing hosts (like if it was just disabled) etc.
This PR will have it continue to run the job for every non-container pool distro but we'll exit early if the distro is disabled.
=> EVG-17379 return early if the distro is disabled

model/event/admin_event.go, model/event/event_finder.go
[EVG-17217](https://jira.mongodb.org/browse/EVG-17217)
Modify the query to use the same index many of the other event queries use. This avoids us needing a special index for this one uncommon query.
I deployed these changes to staging and removed the guid index from the staging db. Reverting an event was still performant so it ostensibly used the shared index.
=> EVG-17217 use shared index for admin events

rest/data/task.go, rest/data/task_test.go
[EVG-17338](https://jira.mongodb.org/browse/EVG-17338)
We currently error when the start_at task is not found for the projects/{project_id}/revisions/{hash}/tasks route 
I'm not super sure why we error at this point but I think we can log something at this point instead of returning a 404 and investigate if it keeps coming up 
(I was also not able to recreate this bug myself)
=> EVG-17338 Remove error when starting task is not found

service/task.go
[EVG-17627](https://jira.mongodb.org/browse/EVG-17627)
We should be returning a content-length header for all http responses. We will need this header to indicate download progress.
Tested through Postman
=> EVG-17627 Return content-length headers for taskLogRaw

model/pod/pod.go, model/pod/pod_test.go, rest/data/pod.go, rest/data/pod_test.go, rest/route/pod.go, rest/route/pod_agent.go, units/pod_creation.go
Jira: https://jira.mongodb.org/browse/EVG-16884
This is pre-work for detecting when a pod is potentially unhealthy. This design is much the same as how hosts work in terms of showing liveliness. There will be a follow-up PR to actually find and handle those unhealthy pods.
* Update pod last communicated time when first starting the pod and whenever it successfully auths.
* Move around some existing tests in the pod data connector.
=> EVG-16884: set pod last communicated time

agent/internal/client/base_client.go, agent/internal/client/host_client.go, agent/internal/client/host_methods.go, agent/internal/client/pod_methods.go, agent/internal/client/request.go, agent/internal/client/request_test.go, config.go, rest/route/middleware.go, rest/route/service.go
[EVG-17450](https://jira.mongodb.org/browse/EVG-17450)
Context: https://mongodb.slack.com/archives/C866SR2LR/p1660676410998359
We have some agent-side v2 REST upgrades and in the past when we deploy, legacy Windows SSH hosts start failing, constantly retrying to deploy the agent, never succeeding, and then ultimately terminating the EC2 hosts.  After some digging, what seems to be the culprit is a difference between how `requireHost` works for v1 vs v2.  On v1, we [update the last communicated time](https://github.com/evergreen-ci/evergreen/blob/main/service/api.go#L168) for the host whereas on v2 we do not (probably because host based agent routes were not on v2 until recently).  So, when a host finishes running tasks and enters an idle polling period for `next_task`, it wasn't updating …
=> EVG-17450 Move host agent routes to requirePodOrHost middleware

go.mod, go.sum
[EVG-17615](https://jira.mongodb.org/browse/EVG-17615)
Re-vendor grip so that it includes [this change](https://github.com/mongodb/grip/pull/118#pullrequestreview-1112576008) and the slack sandbox can be used. 
Before this change, the app couldn't start with the slackbox token because it failed the auth test. Here is why I believe it wasn’t working 
- with the old type of token, it works if you add the authorization token with token : <the_auth_token> 
- with the new type of slack token, it only works if you add the header as Authorization: Bearer <the_auth_token>
- evergreen was using [bluele/slack](https://github.com/bluele/slack) which is deprecated. The grip change switched it over to [slack-go/slack](https://github.com/slack-go/slack) after which …
=> EVG-17615: Re-vendor grep 

service/api.go, service/project.go
https://jira.mongodb.org/browse/EVG-17927
This just ensures that the project ref does not get unset from the project page UI and the global default is set when appropriate on all project_ref routes used by the agent.
I tested in staging that the field is not unset when saving the project page and that if the logger is unset in the project ref, the global default logger is set properly.
=> EVG-17927: Do not clear default logger from project ref and set the global correctly on all project_ref routes

model/test_log.go, model/test_log_test.go, model/testresult/testresult.go, model/testresult/testresult_test.go, units/crons.go, units/data_cleanup_test_logs.go, units/data_cleanup_testresults.go
[EVG-17640](https://jira.mongodb.org/browse/EVG-17640)
As the TSE explained, the db is suffering from these cleanup jobs since the deletes are each racing for the same document and the losers have an expensive backoff algorithm. Looking over the timing in Splunk, it doesn't appear that there are multiple instances of the job running simultaneously. Rather, each job fires off 100k parallel deletes in a bulk write. Still, I added scopes to make sure there wouldn't be more than one job running at once.
I considered parallelizing the id reads with the deletions. When I tried it out locally it took roughly the same time either way (i.e. most of the time was for the deletions) so the additional complexity seemed unjustified.
We'll have to keep an eye on how this affects the deletion rate. The …
=> EVG-17640 data cleanup efficiency

model/patch_lifecycle.go, rest/data/project_settings.go, thirdparty/github.go, trigger/commit_queue.go
[EVG-17920](https://jira.mongodb.org/browse/EVG-17920)
Redirect links to spruce and also fix a project settings bug.
https://github.com/evergreen-ci/commit-queue-sandbox/pull/358 has a commit queue link that redirects to spruce.
=> EVG-17920 redirect commit queue links to spruce

config.go, operations/before.go
Jira: https://jira.mongodb.org/browse/EVG-17946
It seems like the auto upgrade CLI option for the user Evergreen YAMLs isn't working because it's checking the sub-command's CLI context flags (e.g. the flags immediately following `evergreen patch` or `evergreen commit-queue list`), but it should be checking the root CLI context flags (i.e. the flags immediately after `evergreen` but before any subcommand).
After this is deployed, we'll have to announce that any person using the `auto_upgrade_cli` option in their YAML with an `evergreen --version` older than 2022-09-21 (containing this fix) has to manually run `evergreen update` to get the correctly auto-updating CLI.
* Enabled `auto_upgrade_cli` in my YAML.
* Compiled the Evergreen CLI with an older CLI date date (2022-09-10) using what's …
=> EVG-17946: fix auto update CLI context

model/host/host.go, model/host/host_test.go
[EVG-17928](https://jira.mongodb.org/browse/EVG-17928)
- Add ability to unset home volume on stopped host (for internal use only). This will facilitate the migration of volumes between hosts by allowing a volume to be detached without requiring termination of the host.
- Add unit test
- Spruce failure appears to be a flaky test
=> EVG-17928: Add ability to unset home volume

model/host/host.go, model/host/host_test.go, model/project.go, model/project_aliases.go, model/project_aliases_test.go, model/project_configs.go, rest/data/aliases.go, service/api.go, service/project.go, units/patch_intent.go, validator/project_validator.go, validator/project_validator_test.go
[EVG-17335](https://jira.mongodb.org/browse/EVG-17335)
User made a case that commit queue aliases are important enough that they should be validated if they don't match anything. Wrote a change to do this, and it included some refactors.
Open question @hadjri : I think it would be cool to validate all aliases but its tricky thinking of how that would work, in terms of joining all the aliases together. Should we just validate all aliases since it's only warnings anyway? But then we'd probably need to show the source (maybe that's okay though).
Added unit test and tested locally:
```
commit-queue-sandbox [new-branch] $ ../evergreen/clients/darwin_amd64/evergreen -c ~/.evergreen-local.yml validate -p spruce evergreen.yml 
WARNING: Commit queue alias matching variant regexp 'nothing' has no …
```
=> EVG-17335 validate commit queue aliases

config.go, operations/evaluate.go
Jira: https://jira.mongodb.org/browse/EVG-17963
Some people use the Evergreen CLI in CI testing to do automated stuff. `evergreen evaluate` doesn't require the `~/.evergreen.yml` file to exist to evaluate the YAML, so it should be fine to remove the auto-upgrading functionality temporarily. We can evaluate re-adding it and possibly improving the way it logs to interfere with scripting in a follow-up.
I bumped both the CLI and agent versions because this command is being used for CI tests, so we have to force the agents to roll over to the latest version.
N/A
=> EVG-17963: remove auto-upgrade CLI check from 'evergreen evaluate'

model/pod/db.go, model/pod/dispatcher/dispatcher.go, model/pod/dispatcher/dispatcher_test.go, model/pod/pod.go, model/pod/pod_test.go, model/task_lifecycle.go, model/task_lifecycle_test.go, rest/model/pod.go, rest/model/pod_test.go, rest/route/pod_agent.go, rest/route/pod_agent_test.go, units/pod_termination.go, units/pod_termination_test.go
Jira: https://jira.mongodb.org/browse/EVG-17698
I made the task/pod lifecycle interaction a bit safer by ensuring that if the pod lifecycle tries to make a decision based on its currently running task, it also accounts for the execution number. Before, it would assume that the pod was definitely running the latest execution of a task, but there are some cases (such as restarting a task and aborting currently running tasks) where the pod might end up having an archived task execution assigned to it, in which case it should act based on its own task execution and not assume it's the latest. I'd like to avoid that entirely if possible by always acting on the exact task execution that the pod was assigned to run.
* Add new struct to hold information about current/previous tasks run by a pod …
=> EVG-17698: consistently check execution number for tasks assigned to pods

rest/model/project.go, rest/route/project.go, rest/route/project_test.go
Jira: https://jira.mongodb.org/browse/EVG-16910
Expose an option for REST requests to manually rotate the project's pod secret value (or create if it doesn't exist). When the pod secret is rotated, pods that are already running will still authenticate just fine, but newly-created pods will use the new credentials.
Updated unit test for the project modify route.
=> EVG-16910: support manually rotating project pod secret

go.mod, go.sum
[EVG-17615](https://jira.mongodb.org/browse/EVG-17615)
Re-vendor grip so that it includes [this change](https://github.com/mongodb/grip/pull/118#pullrequestreview-1112576008) and the slack sandbox can be used. Despite the previous attempt, prod is not currently on the latest version.
=> EVG-17615: Re-vendor grip

model/container_task_queue.go, model/host/stats.go, model/pod/db.go, model/pod/db_test.go, model/task/task.go, model/task_lifecycle.go, rest/route/pod_agent.go, units/crons.go, units/pod_allocator.go, units/pod_creation.go, units/pod_termination.go, units/stats_pod.go
Jira: https://jira.mongodb.org/browse/EVG-17655
* Add metadata information for logs that are relevant to the [container task health dashboard](https://mongodb.splunkcloud.com/en-US/app/search/evergreen_container_task_health). I added a `usage` field as a signal that these logs are depended on to populate the dashboard.
* Add job to periodically collect stats on pods and container tasks. This has the equivalent purpose to the [host stats collector](https://github.com/evergreen-ci/evergreen/blob/c5abc064bc679a5063ab4cbe5ce14af5cad1287c/units/stats_host.go).
=> EVG-17655: add logging for container task dashboard

model/notification/notification.go, rest/route/notification.go
[EVG-17480](https://jira.mongodb.org/browse/EVG-17480)
When available, use the slackMemberId and not the userName. 
Tested on staging and the slack sandbox.
=> EVG-17480 Update Slack API calls 

model/task/db.go, model/task/task.go
[EVG-17638](https://jira.mongodb.org/browse/EVG-17638)
This query is currently slow because the current `distro_1_status_1_activated_1_priority_1` index doesn't have any sorting on the `depends_on.unattainable` key which causes us to return many index keys for some queries which we then have to filter down. Now that the `distro_1_status_1_activated_1_priority_1_override_dependencies_1_depends_on.unattainable_1` index has been created in prod we'll need to update our hint for this function to use the new index.
In Compass I constructed manually the aggregation used by this query and ran it with and without the new index, and noticed a significant reduction in returned index keys. (screenshots attached).
=> EVG-17638 Use new index for UnscheduleStaleUnderwaterHostTasks

agent/command/s3_put.go, config.go, model/container_task_queue.go, model/project_ref.go, model/project_ref_test.go, scheduler/task_finder.go, units/pod_allocator.go, units/pod_allocator_test.go
Jira: https://jira.mongodb.org/browse/EVG-17457
Before allocating a pod, check whether a task will be allowed to dispatch based on project ref settings. If it's not allowed, don't allocate it.
* Add check for project ref against the task to ensure it can dispatch before allocating a pod.
* Reduce some copy-pasted identical project ref checks between host and container task schedulers.
=> EVG-17457: check project ref for dispatchability during pod allocation

model/pod/definition/definition.go, model/pod/dispatcher/db.go, model/pod/dispatcher/db_test.go, model/pod/dispatcher/dispatcher.go, model/pod/dispatcher/dispatcher_test.go
Jira: https://jira.mongodb.org/browse/EVG-17656
Pod dispatchers are only supposed to be used for the brief period of time that they're dispatching tasks and afterwards serve no purpose to keep around (even if they are used again after a long period of time to dispatch a task, they can simply be re-created). Therefore, we can apply a TTL to them once they haven't been used for a while.
* Add a field indicating the last time the pod dispatcher was updated. This will be the key for a TTL index for the collection.
=> EVG-17656: add TTL field for pod dispatchers

rest/route/host_agent.go
Jira: https://jira.mongodb.org/browse/EVG-17644
Fix the log format for the dispatch race reason. `message.Fields` does not show the error message when  the field value is an `error` object because Splunk can't JSONify it, so use the error message string.
N/A
=> EVG-17644: fix log format for dispatch race

model/task_lifecycle.go, model/version.go
[EVG-17305](https://jira.mongodb.org/browse/EVG-17305)
I plan to restart some tasks in some of [these patches ](https://spruce.mongodb.com/user/didier.nadeau/patches?commitQueue=true) and try to see if these logs shed some light. I tried to restart some tasks already and the version remains in "running".
=> EVG-17305  Add debug logging for patch finished but status is still "started" in DB

model/task_history.go
[EVG-6938](https://jira.mongodb.org/browse/EVG-6938)
Only include build variants in the query if the list is not empty.
=> EVG-6938 Avoid a collection scan by eliminating an empty build variants list  

graphql/generated.go, graphql/mutation_resolver.go, graphql/schema/mutation.graphql, rest/data/project_settings.go, rest/data/project_settings_test.go
[EVG-17693](https://jira.mongodb.org/browse/EVG-17693)
- Add function + resolver for promoting variables from a project to the repo to which it is attached. Variables are removed from projects as part of this operation. This solves the problem where users could not move secret variables (where the value is no longer known to them) to their repo settings.
- Note that the ticket wasn't specific about whether or not variables should be removed from the project or simply copied to the repo. I opted for the former, but am open to the other approach too if it seems preferable!
- Add unit tests
- Test resolver via GraphQL playground
=> EVG-17693: Promote variables from project to repo

model/project_aliases.go
[EVG-17608](https://jira.mongodb.org/browse/EVG-17608)
The original problem hasn't recurred in a few weeks (but also isn't likely to come up often since it requires copying a project) so I'd like to keep this logging but remove the ticket number, since I think the logging itself will still be helpful in this case.
=> EVG-17608 remove ticket from debug logic

public/static/partials/subscription_list.html
[EVG-18064](https://jira.mongodb.org/browse/EVG-18064)
This adds help text to the notifications page to help users debug why they are not receiving notifications. 
Tested on staging 
[1466](https://github.com/evergreen-ci/spruce/pull/1466)
=> EVG-18064 Add help text for re-inviting the slack bot

agent/internal/client/mock.go, apimodels/agent_models.go, config.go, rest/route/task_generate.go
[EVG-17561](https://jira.mongodb.org/browse/EVG-17561)
Now that agents have had sufficient time to roll over, this should be safe to remove.
=> EVG-17561 Remove ShouldExit field from GeneratePollResponse

globals.go, model/task/db.go, model/task/task.go, model/task_lifecycle.go, model/task_lifecycle_test.go, rest/route/host_agent.go, rest/route/task_test.go, units/task_monitor_execution_timeout.go
[EVG-16860](https://jira.mongodb.org/browse/EVG-16860)
This is a follow up to this [previous PR](https://github.com/evergreen-ci/evergreen/pull/5996).  There are some instances in the code when resetting a version / build where the version/build's running tasks are marked as aborted and the finished tasks are reset.  With the previous PR's changes to set the failed status at the same time as setting the aborted field, an issue arose where Evergreen now thought that these tasks are in a state where we can reset them - which is not the case. This is because when we reset these tasks their secrets get reset, which prevents the agent from performing its normal function of calling `"/end"` on a task once it sees it has been aborted - which is essential task ending logic.
As it stands aborted …
=> EVG-16860: Set task doc as failed due to abort immediately upon aborting

model/host/db.go, units/provisioning_create_host.go
Jira: https://jira.mongodb.org/browse/EVG-18131
Hosts that are already running a task should be excluded from the self-throttle count of provisioning hosts. If they're already running a task, they're already provisioned.
There's no unit tests for this query or for the self-throttling behavior, so I didn't think it was worth improving this test coverage issue here for such a tiny change.
=> EVG-18131: exclude hosts running tasks from self-throttle

rest/route/sns.go, rest/route/sns_test.go
Jira: https://jira.mongodb.org/browse/EVG-18140
Preserve the warning that SNS gave us (before acking it) by decommissioning the host.
=> EVG-18140: decommission task host when SNS notifies of stop/termination

config.go, go.mod, model/generate.go, model/project_matrix_test.go, model/project_parser.go, model/project_parser_db.go, model/project_parser_test.go, model/project_test.go, operations/flags.go, operations/http.go, operations/validate.go, service/api.go, util/yaml.go, validator/project_validator.go
Jira: https://jira.mongodb.org/browse/EVG-17291
This is related to #6002 and adds a more user-friendly means to check if a project YAML will be invalidated by the upcoming YAML upgrade. Since we're not sure how many projects are affected by the change to how the YAML module treats nested maps (especially `params`) and I'm not sure people will know what to look for, I added a temporary flag to `evergreen validate` so users can conveniently check if their YAML is still valid using the upgraded YAML version. If their project YAML passes with `--use_upgraded_yaml`, their project config is still valid after the YAML upgrade; otherwise, they'll have to fix their YAML. We'll provide a grace period for them to fix the nested map merging dependency.
Tested `evergreen validate` against staging …
=> EVG-17291: add CLI option to validate against upgraded YAML version

rest/route/build.go, rest/route/build_test.go
[EVG-17358](https://jira.mongodb.org/browse/EVG-17358)
The build route was erroring out because it only had 1 display task. 
The task.Find method automatically filters out display tasks.
We now use findall which will return display only tasks as well but still gets rid of the extra check
unit
=> EVG-17358 Return display tasks in get build by id route

units/crons.go, units/generate_tasks.go, units/generate_tasks_test.go
Jira: https://jira.mongodb.org/browse/EVG-18111
Remove the flag on using a scope for the generate tasks job. There was originally a feature flag on it, but it's been removed and the job always uses scopes now, so the lingering boolean is unnecessary.
=> EVG-18111: remove generate tasks scope feature flag

rest/data/generate.go, rest/data/generate_test.go, rest/route/github_test.go, rest/route/host_agent_test.go, rest/route/service.go, rest/route/task_generate.go, rest/route/task_generate_test.go, service/service.go
Jira: https://jira.mongodb.org/browse/EVG-18206
As far as I can tell, the EC2 SNS test is being flaky for reasons unrelated to this particular test. From what I can see, the test DB is spending a ton of time trying to clean up some state as a result of dropping a bunch of collections/DBs in other unrelated tests in the REST route package, which is holding the lock on the DB and preventing any reads/writes to it. There are [logs in the test](https://evergreen.mongodb.com/task_log_raw/evergreen_ubuntu1604_test_rest_route_cddfabfb14478c7534a9f94dc140e1fda860412c_22_11_02_20_19_23/0?type=T#L7614) to back up this hypothesis since they're fixing collections that were dropped in other tests using `DropCollections`.
* Remove some unused parameters to reduce the need to drop the Amboy test DB in a …
=> EVG-18206: remove dependence on dropping databases in REST route tests

mock/environment.go, rest/route/host_test.go, rest/route/sns_test.go, units/util.go
Jira: https://jira.mongodb.org/browse/EVG-18206
Alright, apparently, I didn't re-run my previous PR (#6044) enough times because the test timed out for the same reason when committed to the waterfall... I suspect that the `TimestampMonitor` cleaning up dropped collections from the previous PR is a symptom and not the cause - the DB might only doing that because it's detected that it's idle (due to the test hanging for another reason).
My second best guess (which I verified by running it even more times) is that the test is flaky because `queue.NewLocalLimitedSize` has an undiagnosed deadlock somewhere in it, resulting in the call to `queue.Stats(ctx)` to hang until Go times out the test. I don't really see _how_ it could deadlock, but I don't totally trust that the implementation is …
=> EVG-18206: prevent potential deadlock in EC2 SNS test

globals.go, model/task/results.go, rest/data/version_test.go, rest/route/status_test.go, scheduler/task_finder_test.go
[EVG-17203](https://jira.mongodb.org/browse/EVG-17203)
Remove unstarted task status; we've previously verified that this isn't really used for anything except the recent_tasks rollup, for which unscheduled will work just as well (not changing that output from "unstarted" to "unscheduled" though since that would be a breaking change and it's not super necessary).
=> EVG-17203 remove unused unstarted task status

model/patch_lifecycle.go
[EVG-18231](https://jira.mongodb.org/browse/EVG-18231)
author_email was not previously included in versions that were created from a patch. This now includes the email from their git account by default if not it falls back to the email included in gitinfo. 
Example doc of a patch I created on staging
=> EVG-18231 Include author_email in patch created versions

rest/route/admin_events.go, rest/route/build_task.go, rest/route/distro.go, rest/route/host.go, rest/route/patch.go, rest/route/project.go, rest/route/project_events.go, rest/route/reliability.go, rest/route/stats.go, rest/route/task_project.go
[EVG-16771](https://jira.mongodb.org/browse/EVG-16771)
Gimlet defaults to OK / json already so this is unnecessary. 
https://github.com/evergreen-ci/gimlet/blob/main/framework_response.go#L75
=> EVG-16771 remove redundant gimlet formatting

model/host/host.go, units/migrate_volume.go, units/migrate_volume_test.go
[EVG-18217](https://jira.mongodb.org/browse/EVG-18217)
- Fixes a bug where home volumes that were attached to a workstation that was terminated would fail to migrate because the initial host could not be found.
- At present, these volumes can still be attached to a new workstation by adding them during the spawn host stage. However, migration should be supported too as it is in some ways a more obvious workflow.
- Tested on staging
- Add unit test for this case
=> EVG-18217: Allow migration of volumes with previously terminated hosts

config.go, operations/commit_queue.go
[EVG-17124 ](https://jira.mongodb.org/browse/EVG-17124 )
Shouldn't use the commit queue patch description, since it sends users to the commit queue page, which is confusing since backports don't go there to begin with.
=> EVG-17124 display correct patch description for backports

model/task_lifecycle.go, model/task_lifecycle_test.go
[EVG-16671 ](https://jira.mongodb.org/browse/EVG-16671 )
Continue stepping back on system failures, _if_ we were already stepping back (otherwise we're going to be starting a bunch of new step backs, in which case it'd probably be better to just not do this at all). 
Added to existing test.
=> EVG-16671 continue stepback for system failures

config.go, operations/admin.go, operations/admin_all_configs.go, operations/cli_integration_test.go, operations/commit_queue.go, operations/commit_queue_test.go, operations/create_version.go, operations/fetch.go, operations/host_spawn.go, operations/http_test.go, operations/keys.go, operations/last_green.go, operations/list.go, operations/model.go, operations/notification.go, operations/patch.go, operations/patch_cancel.go, operations/patch_finalize.go, operations/patch_list.go, operations/patch_module.go, operations/pull.go, operations/scheduler.go, operations/subscriptions.go, operations/update.go, operations/validate.go
[EVG-17968](https://jira.mongodb.org/browse/EVG-17968)
Removed getSetupCommunicator since it's not immediately obvious when to use get vs setup (since a lot of CLI setup ends up being copy paste, having a boolean makes it more likely that engineers will consider its value). 
Ensured client still works, and used list-patches to audit the JSON flag (with it, we don't print banner).
=> EVG-17968 suppress messages from CLI when relevant

model/commit_queue.go, rest/data/commit_queue.go, units/commit_queue.go
[EVG-18084](https://jira.mongodb.org/browse/EVG-18084)
In testing this to verify we get the right PR number, I also confirmed that this feature doesn't do what we say it does. It looks to me like this is meant to merge all modules https://github.com/evergreen-ci/evergreen/wiki/Commit-Queue but i don't see anywhere where we handle merges in the existing code for this: https://github.com/evergreen-ci/evergreen/blob/4487dbd483f9e1a593a82b079941cb573736cc2e/agent/command/git_merge_pr.go#L98 I'm also not convinced we correctly test with the module changes. 
I think it's worth breaking that investigation into two new tickets (or one), and I can update the documentation with the tickets to indicate that the feature won't work until then. 
All of the above can be seen here: …
=> EVG-18084 reference correct PR number for module merges

model/lifecycle.go, model/task/db.go, model/task/task.go, model/task_queue.go, model/task_queue_service.go, rest/route/distro_test.go, rest/route/host_agent.go, scheduler/distro_alias_test.go, scheduler/scheduler.go, units/check_blocked_tasks.go, units/crons.go
[EVG-15148](https://jira.mongodb.org/browse/EVG-15148 )
Longer rational included in ticket; TLDR s that "alias" is already used to give distros multiple names so shouldn't be used for "secondary queue" as well.
Didn't change bson tags to avoid migrations.
=> EVG-15148 rename distro alias queue to secondary queue

globals.go, model/task/db.go, model/task/task.go, model/task/task_test.go
[EVG-17497](https://jira.mongodb.org/browse/EVG-17497)
Currently in both legacy and spruce UI, you can disable a task, and then subsequently manually hit "Schedule".  This sets the status of the task to "Will Run" as expected but the priority remains at -1 and the task will actually never get scheduled (screenshot attached).  Change has been made such that when we activate a task, if it is set as disabled, reset its priority to zero.  
Updated unit test and deployed to staging to confirm that manually scheduling a disabled task in the UI resets its priority and lets the task actually get scheduled.
=> EVG-17497 Reset priority when activating task

units/provisioning_create_host.go
Jira: https://jira.mongodb.org/browse/EVG-18222
There's an option exposed in host.create to specify the number of times that a host.create host is allowed to retry. All I did was make it so that the number of retries they specify means number of times to try again after an initial failure, rather than total number of attempts, which seems more intuitive based on the option name.
Didn't seem that applicable since host creation retries are a minor thing.
=> EVG-18222: add one host creation attempt for initial try

cloud/cloud.go, cloud/cloud_status.go, cloud/ec2.go, cloud/ec2_fleet.go, cloud/ec2_fleet_test.go, cloud/ec2_test.go, cloud/mock.go, units/host_status.go, units/host_status_test.go
Jira: https://jira.mongodb.org/browse/EVG-18139
Looking through the logs, AWS did an unexpectedly new thing with `DescribeInstances` that we haven't seen before. In the past, when we requested at least 1 instance ID that AWS has no knowledge of, it would return an `InvalidInstanceID.NotFound` error (e.g. because the instance never existed or it was terminated a long time ago), which we handle already by terminating it. This time, it behaved in a different way - it had no status for some of the requested IDs (and those instances did not exist in AWS), but instead of producing the `InvalidInstanceID.NotFound` error, it simply returned no instance reservation for them (i.e. no status). I updated the logic to be more resilient to the possibility that either it will return …
=> EVG-18139: gracefully handle nonexistent hosts when checking statuses

units/migrate_volume.go, units/migrate_volume_test.go
[EVG-18297](https://jira.mongodb.org/browse/EVG-18297)
- Prevent panic when MigrateVolume job is invoked with a volume ID not found in the database. The job was still attempting to call `volume.SetMigrate(false)` to wrap up the job, so skip this if the volume doesn't exist.
- I am not sure how a user started a job on a volume that doesn't exist 😳 
- Add unit test
=> EVG-18297: Fix volume migration job panic

cloud/ec2.go
[EVG-18050](https://jira.mongodb.org/browse/EVG-18050)
Iops is required for io1 so adding that; using 3000 because this is the default (if changing types, according to AWS) and I don't think anyone is going to want/need more than that.
Tested that creating io1 works now on staging.
=> EVG-18050 add iops to io1 volumes

graphql/util.go, model/generate_test.go, model/patch_lifecycle.go, model/project.go, model/project_aliases.go, model/project_configs_db.go, model/project_parser.go, model/project_ref.go, model/project_test.go, rest/data/commit_queue.go, rest/data/host_create.go, rest/model/patch.go, rest/route/agent.go, service/patch.go, service/rest_patch.go, units/generate_tasks.go, units/generate_tasks_test.go, units/patch_intent.go, units/patch_intent_test.go
[EVG-17275](https://jira.mongodb.org/browse/EVG-17275)
Exact same as the original except added a missing return in the second commit 🤦‍♀️ 
Tested by running set-module on a scheduled patch.
Before:
egss set-module -m evergreen -i 6375292c9dbe32575c2026e3 
load project error(s): unmarshalling parser project from YAML: invalid configuration file: yaml: control characters are not allowed
After:
Success
=> EVG-17275 check parser project collection if patched parser project is empty

config.go, operations/commit_queue.go, operations/host_spawn.go, operations/patch.go, operations/patch_module.go, operations/patch_util.go, operations/prompt.go
[EVG-17504](https://jira.mongodb.org/browse/EVG-17504)
User asked that "set default" prompts default to no bc typing no is annoying. I actually think this is meant to be the default generally since we use the "y/N" terminology for defaults, and not doing something is never the risk, default yes is the one we have to be careful about. 
Tested using a command with a default Yes and default No.
```
Set test as the default alias for project 'evg'? (y/N) 
Enter a description for this patch (optional): 
config.go                  |  2 +-
operations/commit_queue.go | 11 ++++++-----
operations/host_spawn.go   |  6 +++---
operations/patch.go        |  2 +-
operations/patch_module.go |  2 +-
operations/patch_util.go   |  8 ++++----
operations/prompt.go       |  5 +++++
7 files changed, 21 …
```
=> EVG-17504 have CLI prompts that don't default yes default no"

apimodels/agent_models.go, rest/route/agent.go
[EVG-17505](https://jira.mongodb.org/browse/EVG-17505)
Removing as a follow up from [this PR](https://github.com/evergreen-ci/evergreen/pull/5853) now that all hosts have rolled over.
=> EVG-17505 Remove WorkDir from DistroView

model/generate.go, model/lifecycle.go, model/project.go, model/project_parser.go, model/project_ref.go, model/project_ref_test.go, repotracker/repotracker.go
[EVG-16982](https://jira.mongodb.org/browse/EVG-16982)
Activation right now checks activate but not disabled. Additionally, there are a few places where we short circuit if cron/batchtime aren't defined, but we don't check either activate or disabled before we do that.
Added a test.
=> EVG-16982 respect disabled for cron

graphql/generated.go, graphql/mutation_resolver.go, graphql/schema/mutation.graphql, graphql/tests/deactivateStepbackTask/results.json, model/task/task.go
[EVG-18356](https://jira.mongodb.org/browse/EVG-18356)
The mutation `deactivateStepbackTasks` is no longer called by the frontend, so we can remove it. This means we can also remove `LegacyDeactivateStepbackTasksForProject`.
- Existing tests should pass
=> EVG-18356: Remove legacy stepback function

model/task/task.go, model/task_lifecycle.go, model/task_lifecycle_test.go, units/util_test.go
[EVG-17033](https://jira.mongodb.org/browse/EVG-17033)
There is currently a bug where ending stranded tasks rather than resetting them (either because they have breached the unschedulable threshold or they have breached the max execution) causes `MarkEnd` to return early and not perform the necessary steps of updating dependencies, updating build/version statuses, updating display task statuses, etc.  
Change has been made to not call `MarkSystemFailed` before calling `MarkEnd` in these cases because it would result in a premature return [here](https://github.com/evergreen-ci/evergreen/blob/c2844d0184381b161f61402ddc599253c2b9a248/model/task_lifecycle.go#L477-L483). Passing stranded system failure details to `MarkEnd` will allow it to perform the same function as `MarkSystemFailed` in …
=> EVG-17033 End max execution and unschedulable stranded tasks before marking system failed

service/templates/task.html
[EVG-18393](https://jira.mongodb.org/browse/EVG-18393)
I accidentally exposed the links to parsley on the legacy UI in [this PR ](https://github.com/evergreen-ci/evergreen/pull/6085/files). This just hides them until we are ready to launch. Once we launch this commit can just be reverted.
=> EVG-18393 Hide parsley links on legacy ui

model/project_parser.go, model/version_db.go, model/version_db_test.go, rest/route/version_create.go, units/periodic_builds.go
[EVG-18391](https://jira.mongodb.org/browse/EVG-18391)
This periodic build was defined with an error, so we created a stub version.
https://evergreen.mongodb.com/version/637d2a40a4cf472bcc36d583
However, the stub version ends up having no revision since we don't add it to the metadata. (This is also why https://jira.mongodb.org/browse/EVG-18390 occurred, because we use the revision for the link.) 
Because we just get the latest version (instead of the latest version with a valid config), we end up getting the broken periodic build, which has an empty revision, and so when we call GetGithubFile we get the master branch yaml instead of the v6.1 yaml. 
Not tested but reasoned about.
=> EVG-18391 use latest commit version for periodic build creation

service/rest_patch.go
[EVG-17275](https://jira.mongodb.org/browse/EVG-17275)
use yaml because the header is yaml
will run the set-module command on something
=> EVG-17275 use yaml when yaml is expected

globals.go, model/event/patch_event.go, model/event/subscriptions.go, model/event/version_event.go, model/patch/patch.go, model/task_lifecycle.go, rest/data/patch.go, rest/data/subscription.go, trigger/patch.go, trigger/registry.go, trigger/version.go
[EVG-14528](https://jira.mongodb.org/browse/EVG-14528)
Before this change, when a patch or version was done, we would check in the trigger outcome to see if the children are done, and if they were not, we would exit.
What this does instead, is it creates an event when the children and parent are both done and subscribes on that event in situations where we only want to do something once everything is done. 
Now that the family trigger is set up, the way we process Github child patch triggers can be optimized as well. I created [EVG-18381](https://jira.mongodb.org/browse/EVG-18381) to track that. 
In order for patch outcome notifications (the ones set up [here](https://spruce-staging.corp.mongodb.com/preferences/notifications)) to work after this change, the existing subscription db …
=> EVG-14528 Add TriggerFamilyOutcome type to events

model/lifecycle.go
[EVG-17305](https://jira.mongodb.org/browse/EVG-17305)
This solves the bug we were seeing where patches remained in the "running" status despite having finished running. 
A patch with the same setup [before](https://spruce-staging.corp.mongodb.com/version/6386871297b1d36bb9fbf1e0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and [after](https://spruce-staging.corp.mongodb.com/version/6387b174b237365ae87d5f9d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) the changes.  The problem is more visible in the legacy UI where you can see the build variants with inactive tasks.
=> EVG-17305 Deactivate BVs with no active tasks when generating tasks 

model/version_db.go
[EVG-18391](https://jira.mongodb.org/browse/EVG-18391)
We forget to actually sort so we aren't necessarily getting the latest revision for the project.
We actually already have a test that covers multiple revisions but theoretically it would only fail flakely. Verified via shell for the project in question.
=> EVG-18391 sort revisions for project

model/project_ref.go, model/project_ref_test.go, rest/data/admin.go, units/crons.go, units/periodic_builds.go
[EVG-18398](https://jira.mongodb.org/browse/EVG-18398)
Fixes three problems:
1) We update the repo with the wrong ID 
2) We update the repo even if the definition is actually in the project (and we used the merged project so there wasn't a good way to distinguish between the two)
3) We  find the periodic builds using an aggregation, but then we reference the definitions, which isn't handled via aggregation. The aggregation was really just meant to find IDs (which I clarified for the commit queue version), and isn't really worth it for this use -- just grabbed all projects and added only the ones that had definitions.
Beefed up the unit tests a lot.
=> EVG-18398 fix periodic builds for repo projects

model/event/subscribers.go, model/event/subscribers_test.go, model/notification/notification.go, rest/model/subscriber.go, rest/model/subscriber_test.go, util/webhook_grip.go, util/webhook_grip_test.go
[EVG-17448](https://jira.mongodb.org/browse/EVG-17448)
Allow users to configure retries and timeout for a webhook notification.
We thought to just make it retry by default, but that would have caused minor issues with the pr bot.
My plan is to open a UI ticket to surface the new fields in the project settings. In the meantime, I'll set them in the db for the subscriptions referenced in the ticket.
I skipped adding the new fields to the old UI. I think this is our current posture? If not I can add them there.
Unit tests for the new fields in the subscriber/API subscriber and for retries.
I'll try it out in staging when I see an opening there.
=> EVG-17448 configurable webhook retries

cloud/mock.go, units/host_status_test.go, units/host_termination.go, units/host_termination_test.go
Jira: https://jira.mongodb.org/browse/EVG-18827
There was an assumption that a host that's building would never be sent directly to the host termination job and would instead be [marked as building-failed first by the host allocator before going to the host termination job](https://github.com/evergreen-ci/evergreen/blob/46c9842829d6dba1d8fa7b194660a7199bc6c5f2/units/host_allocator.go#L123). This assumption of building -> building-failed -> terminated isn't really necessary, so I relaxed some of the logging in the host termination job to not warn when a building host is being terminated.
* Do not log warnings in host termination job for terminating a building host.
* Slightly improve the host termination job to ensure that the event log populates the original reason for termination rather …
=> EVG-18827: allow building hosts to be terminated

agent/agent.go, agent/directory.go, agent/directory_test.go, config.go
Jira: https://jira.mongodb.org/browse/EVG-18001
When the agent starts up, it tries to clean up its working directory before running tasks. This is useful for static hosts, which keep reusing the same directory repeatedly to run tasks, to avoid slowly filling up the disk over time. However, some tasks may create read-only files (e.g. the Go mod cache) and `os.RemoveAll` does not have permission to delete these. Using the `removeAll` helper edits the read-only files to be writeable so that they can be cleaned up.
Updated existing unit test.
=> EVG-18001: allow agent to clean up working directory containing read-only files

cloud/pod_util.go
Jira: https://jira.mongodb.org/browse/EVG-18443
Allowing `aws ecs exec` is convenient so that we can debug containers when they encounter issues. Ideally, we'll have a better logging setup in the future so that we can debug with logs rather than rely on exec'ing into containers.
This isn't really something that can be tested since it's an ECS feature for running containers.
=> EVG-18443: enable pod debugging

model/github_hook.go, repotracker/github_poller.go, thirdparty/github.go, thirdparty/github_test.go
Jira: https://jira.mongodb.org/browse/EVG-17571
Based on [the logs](https://jira.mongodb.org/browse/EVG-17571), the test is flaking because it hits the 10 second timeout in `GetGithubMergeBaseRevision`. I changed the GitHub API helper functions to just rely on the passed-in context rather than hard-code a specific timeout within the functions themselves, to make it easier for tests to configure their own
* Reduce GitHub API test flakiness by increasing timeout.
* Move context timeouts out of the GitHub helper functions and into the callers to allow tests to specify their own timeouts.
Existing test should pass. Flakiness due to slow API responses shouldn't happen as often anymore.
=> EVG-17571: fix test-thirdparty flaky test

model/version.go, repotracker/repotracker_test.go
Jira: https://jira.mongodb.org/browse/EVG-18208
`TestBatchtimeForTasks` was being flaky because it checked if the `time.Now()` timestamp was strictly after the task's `ActivateAt`. Sometimes, the Go test will run so quickly, that the `time.Now()` when `ActivateAt` is set (right before calling `model.ActivateElapsedBuildsAndTasks`) was identical to the `time.Now()` comparison timestamp in `model.ActivateElapsedBuildsAndTasks`. To fix this timing issue, I made the `ActivateAt` timestamp slightly before `time.Now()` to ensure that it gets activated.
* Fix `TestBatchtimeForTasks`.
* Remove redundant zero time check (because `utility.IsZeroTime` checks both Unix and Go zero time already).
Ran `TestBatchtimeForTasks` locally a bunch to ensure it's really not flaky anymore.
=> EVG-18208: fix flaky repotracker test

graphql/mutation_resolver.go, model/project_ref.go, model/project_ref_test.go, model/repo_ref.go, rest/data/project.go, rest/data/project_settings.go, rest/data/project_settings_test.go
[EVG-18436](https://jira.mongodb.org/browse/EVG-18436)
This ticket highlighted a couple of projects that didn't get TracksPushEvents set for the project or repo, because we'd create the hook but not update the project with it (the new UI neglects to set this field entirely). Made modifications to both update the repo structure when a project is attached/detached and to update the project ref when we check webhooks.
Will need to manually update repos that don't have this field set to ensure that testing works correctly.
Added to unit tests; verified on staging that modifying the general page updates the field correctly (i.e. doesn't update it unless checking the changed owner/repo field -- used https://spruce-staging.corp.mongodb.com/project/annie-copy2/settings/general)
=> EVG-18436 set if projects track push events more carefully

model/patch/patch.go, model/version.go, trigger/patch.go, trigger/patch_test.go
[EVG-14528](https://jira.mongodb.org/browse/EVG-14528)
=> EVG-14528 Filter out aborted patches from the RunChildPatchSubscriberType subscription generation 

graphql/tests/task/results.json, graphql/util.go, graphql/util_test.go
[EVG-16853](https://jira.mongodb.org/browse/EVG-16853)
When "Abort" is hit in the UI, it marks the task as `abort: true`, but does not fail the task immediately. It is the agent that fails the task once it sees it was aborted, and this usually takes a few seconds. Hence, if you click "Abort" and then immediately click "Restart", the agent might not have had time to fail the task that had its aborted field set and we get the error that is screenshotted on the ticket.
Change introduced will cause the "Restart" button to be greyed out for aborted tasks until the agent actually finishes the task (which you'd be able to tell from the logs as well).
Tested on local evergreen
=> EVG-16853 Don't allow restarting non-finished aborted tasks

model/dependencies.go, model/generate.go, model/patch_lifecycle.go, model/patch_lifecycle_test.go, model/project.go, repotracker/repotracker.go, units/generate_tasks_test.go
[EVG-18413](https://jira.mongodb.org/browse/EVG-18413)
Currently, generated dependencies of generated tasks that don't have their variant defined in the generator JSON get activated by default, because the way Evergreen determines the activation of a generated task is from the generated JSON, i.e. setting `"activate": false` on a variant.  If Evergreen can't find the variant, it assumes the variant will be active.
Change has been made to determine which generated dependency tasks do not have their variant defined in the generated JSON, and if the generated tasks that depend on them are all deactivated, then it is safe / necessary to also deactivate this newly generated variant.
Tested in staging and confirmed that a generated task that isn't set anywhere in the original generated JSON …
=> EVG-18413 Do not activate generated tasks that depend on explicitly inactive variants

model/project.go, model/project_ref.go, model/project_ref_test.go, rest/route/project.go, rest/route/project_test.go
[EVG-18116](https://jira.mongodb.org/browse/EVG-18116)
added flags to only show mainline or patch tasks to get tasks by project endpoint
unit tests
=> EVG-18116 Add requesters to project tasks route opts

graphql/generated.go, graphql/schema/types/version.graphql, graphql/version_resolver.go
[EVG-18394](https://jira.mongodb.org/browse/EVG-18394)
This would panic whenever options would not be passed in because we try to access some of its sub-fields. options should probably always be passed in.
=> EVG-18394 Make options fields required to prevent panics

model/dependencies.go, units/generate_tasks_test.go
[EVG-18413](https://jira.mongodb.org/browse/EVG-18413)
In the[ previous PR](https://github.com/evergreen-ci/evergreen/pull/6111) to address this ticket, the change was to not activate generated tasks that depend on explicitly inactive tasks.  This works in the standard cases I was testing for, but it's not sufficient in the more complex case where the tasks that get deactivated _generate further dependencies_ within the same variant.  
Ex:  
If `generator` generates `taskA` in `variantA` which is set `activate: false`, which has a dependency in the YAML on `taskB` in `variantB`, which then has a dependency on `taskB2` in `variantB`, then the previous PR will correctly prevent `taskB` from being activated, but `taskB2` gets activated incorrectly since `taskB` has not been added to the list …
=> EVG-18413 Also deactivate the dependencies of newly deactivated dependencies

cloud/pod_util.go, cloud/pod_util_test.go, go.mod, go.sum, model/pod/pod.go, model/pod/pod_test.go, units/pod_definition_creation_test.go
Jira: https://jira.mongodb.org/browse/EVG-18036
The reason the tasks were not reusing the same pod definition was because the pod definition also included the pod ID environment variable, which is unique to each pod. The pod ID can simply be moved to the override options so that pod definitions do not have any pod-unique parameters. The general steps now are to 1. create the pod definition (with no environment variables set initially), then 2. set the environment variables when the pod is started from the template pod definition (to set the pod ID environment variable).
* Upgrade Cocoa.
* Move environment variables so that they're set when the pod is started (via override options) instead of setting them on the pod definition.
I updated the automated tests to remove the assumption that …
=> EVG-18036: move container environment variables from pod definition to override options

trigger/patch.go
[EVG-16663](https://jira.mongodb.org/browse/EVG-16663)
Users do not wish to receive notifications for aborted patches from the general patch notification setting. 
The only notification related to patch outcomes  that someone can sign up for is patch-finish, which is handled by the function changed in this PR. So they will continue to receive notifications if they explicitly sign up for it by clicking on notify me on that specific version page. 
Tested the behavior on staging.
=> EVG-16663 Suppress general notifications for aborted patches

model/project_configs.go, model/project_ref.go, model/project_ref_test.go, validator/project_validator.go, validator/project_validator_test.go
[EVG-18410](https://jira.mongodb.org/browse/EVG-18410)
Periodic build in project config doesn't work, and isn't something we can fix really since run_time needs to be defined somewhere global that we can keep updated and reference. Theoretically if we wanted to support this we could have a new collection that holds onto periodic build run times and require a unique ID for periodic builds but that would be complex, not a great experience for users, and not worth it without further investigation into EVG-16867 considering the main use case people seem interested in for version control are aliases at the moment.
Verified this isn't in use, and will update documentation.
Verify tests pass and merging project ref / project config correctly uses the project ref periodic build.
=> EVG-18410 remove periodic build from project config

config.go, model/project.go, operations/evaluate.go
Jira: https://jira.mongodb.org/browse/EVG-18518
Apologies for the long description, but this change has a bunch of context. The tl;dr is that `evergreen evaluate` now produces output consistently and also outputs more fields.
This is a follow-on to #6002 and is related to #6017. The downside of #6017 was that `evergreen validate` can only check if the upgraded YAML passes validation, but can't check that some runtime values (like expansions) would be exactly the same pre-upgrade and post-upgrade. Unfortunately, the YAML upgrade _may_ change the YAML parsing behavior such that the YAML is still syntactically valid, just different. Users would be most interested in knowing if their YAML is parsed _differently_, rather than simply knowing if their YAML is valid, because this can result in …
=> EVG-18518: produce diffable YAMLs via evergreen evaluate

cloud/ec2_client.go, cloud/ec2_fleet.go, cloud/ec2_fleet_test.go
[EVG-18285](https://jira.mongodb.org/browse/EVG-18285)
The Splunk error is not the reason why the host was not removed. Based on the conversation with @Kimchelly, the background cleanup job that was supposed to clean up these hosts doesn't handle the InvalidInstanceID.NotFound error yet. We already have a ticket - [EVG-18388](https://jira.mongodb.org/browse/EVG-18388) to fix this.
In this case, the error is reported even though `InvalidInstanceID.NotFound` is handled. I have fixed this part. This will fix the wrong Splunk error.
=> EVG-18285: Spinning our wheels on host/task cleanup

model/event/subscribers.go, model/event/subscriptions.go, trigger/patch.go, units/patch_intent.go
[EVG-18381](https://jira.mongodb.org/browse/EVG-18381)
We no longer need to subscribe on all github pr child patches so that we can wait on it. We can use the family-outcom trigger instead. 
[Tested on staging ](https://github.com/evergreen-ci/commit-queue-sandbox/pull/376)
=> EVG-18381 Refactor Github child patch subscriptions

graphql/generated.go, graphql/mutation_resolver.go, graphql/schema/mutation.graphql, graphql/tests/restartTask/queries/error-invalid-task_id.graphql, graphql/tests/restartTask/queries/success.graphql
[EVG-15703](https://jira.mongodb.org/browse/EVG-15703)
- Make `failedOnly` param non-nilable now that the front end is including it in `restartTask` function calls.
- Update unit tests
To be deployed after https://github.com/evergreen-ci/spruce/pull/1582
=> EVG-15703: Require failedOnly argument in restartTask mutation

config.go, operations/patch.go, operations/patch_util.go, operations/patch_util_test.go
Jira: https://jira.mongodb.org/browse/EVG-18218
When referencing a local alias (i.e. using `evergreen patch --alias <alias>`), setting the local alias also unsets the `patchParams.Alias field`, which makes the CLI command [later fall back to also adding the default variants/tasks](https://github.com/evergreen-ci/evergreen/blob/604a52175507056ab009f0acecdd409d311784a4/operations/patch_util.go#L391-L393). It seems like what we actually want it to do is for the local alias to take precedence - if the alias matches a local alias, then use the variants/tasks defined for that local alias, instead of the default alias/variants/tasks.
I also fixed some tiny issues with the local aliases, such as not logging an error when it fails to load local aliases, and removing some unnecessary local aliases …
=> EVG-18218: fix local alias interaction with default variants/tasks

config.go, operations/model.go
[EVG-17206](https://jira.mongodb.org/browse/EVG-17206)
It's easy to forget which directory you have to log which command in. This help text should be helpful if someone runs set-module in the wrong project directory.  
Ran one of the commands locally
=> EVG-17206 Add help text to set-module and patch-set-module

config.go, operations/patch.go
[EVG-17302](https://jira.mongodb.org/browse/EVG-17302)
Do not allow aliases when --reuse or --repeat failed is used.
Tested locally
=> EVG-17302 Do not allow aliases when --reuse or --repeat failed is used

agent/command/shell.go, agent/command/shell_test.go, config.go, validator/project_validator.go, validator/project_validator_test.go
[EVG-17605 ](https://jira.mongodb.org/browse/EVG-17605)
I think we didn't make this required bc at the time it would've affected a lot of projects? But it's only v4.0 and curatorbin now; reached out to those project owners. (Added https://github.com/evergreen-ci/curatorbin/pull/9 for curatorbin)
Updated test.
=> EVG-17605 upgrade warning for empty shell.exec script to error

rest/route/project.go, rest/route/service.go
[EVG-17118](https://jira.mongodb.org/browse/EVG-17118)
I guess I forgot to test this end to end 🤦‍♀️  tasks/executions conflicts with the tasks/{task_name} route so renaming.
Tested using evergreen local.
=> EVG-17118 rename route to avoid conflict

model/build_test.go, model/lifecycle.go, model/lifecycle_test.go, model/task/db.go, rest/route/build.go, rest/route/build_test.go, service/build.go
[EVG-16480](https://jira.mongodb.org/browse/EVG-16480)
- `RestartVersion` has special logic for restarting single host task group tasks in that instead of archiving/restarting them immediately, it marks the task group to reset when all tasks in the group finish, so they can restart together. `RestartBuild` does not have any of this logic although it should, so I've modularized the logic of `RestartVersion` into some helper functions that can be used by both.  
- Made a change to `AbortTasksForBuild` to mark the in-progress tasks it is aborting to restart when they are finished. This is how it works for `RestartVersion`, whereas when we restart a build we simply abort the in-progress tasks (which results in a partial restart of the build which is incorrect).
- Removed …
=> EVG-16480 Refactor build restarts to share functionality with RestartVersion

model/version_db.go, model/version_db_test.go
[EVG-18673](https://jira.mongodb.org/browse/EVG-18673)
There is an [issue](https://mongodb.slack.com/archives/C0V896UV8/p1673021506764289) in the way activating tasks based on batchtime / cron works because the version activation job looks for the most recent version with one of the `SystemVersionRequesterTypes` which also includes periodic builds, git tags and triggers.  
If a non-repotracker version is the most recent one found at the time of version activation, and it doesn't contain the cron / batchtime tasks, then the cron / batchtime tasks from the most recent repotracker version will get skipped and will never be activated.
Updated to only look for repotracker versions.
Updated unit test.
=> Ignore non-repotracker versions when activating versions

service/host.go
[EVG-18417](https://jira.mongodb.org/browse/EVG-18417)
The "Open Page in New UI" link on the legacy host page incorrectly links to Spruce's `/hosts/<host_id>` path. It should link to the `/host/<host_id>` path instead.
- Manually on staging
=> EVG-18417: Use correct Spruce link on legacy host page

model/lifecycle_test.go, model/task_lifecycle.go
[EVG-18567](https://jira.mongodb.org/browse/EVG-18567) 
We hit an edge case on an aborted patch with a deactivated and aborted build. When a task in that build was restarted, because the build was not reactivated, it appeared as though the version is in a "done" state, triggering a children_finished event to be logged. 
This change fixes that edge case by checking in updateBuildStatus if a build that was previously deactivated needs to be activated. 
=> EVG-18567 Avoid triggering a children_finished event when a task is restarted 

agent/command/git_push.go, agent/command/git_push_test.go, config.go
[EVG-12819](https://jira.mongodb.org/browse/EVG-12819)
When pushing with `git push origin <name>`, it can refer to either a branch name or a tag name. Since the push command specifically uses the branch name, we should use `git push origin refs/heads/<name>` instead so that it specifically refers to the branch only. 
Merged something on staging to make sure it still works as expected.
=> EVG-12819 Disambiguate the push command 

thirdparty/github.go
[EVG-14416](https://jira.mongodb.org/browse/EVG-14416)
There's already a mergeable check in commit queue tasks, so there's no need to check it here. Checking here can make it so that enqueuing very quickly after pushing a commit fails to enqueue
=> EVG-14416 Skip mergeable check when submitting to the commit queue

model/patch/patch.go, trigger/patch.go, trigger/version.go
[EVG-18561](https://jira.mongodb.org/browse/EVG-18561)
Every now and then a PR will send a notification with the wrong collective status. The bug is not reproducible. The bug doesn't even happen again if the problematic patch is restarted. 
Checking the collective status before sending the notification will hopefully solve it. 
=> EVG-18561 Fix wrong collective status

service/templates/admin.html
[EVG-18634](https://jira.mongodb.org/browse/EVG-18634)
Tried clarifying this behavior once but left it vague enough it needed clarifying again. Verified start/finish behavior [in query](https://github.com/evergreen-ci/evergreen/blob/502403c1ceee7548e323a9f130fb5967e57a433b/model/task/db.go#L645).
Verified timezone by playing around in staging but didn't actually find how this works 🤔
=> EVG-18634 clarify admin restart text (take two)

config.go, operations/patch.go, operations/patch_util.go
[EVG-15470](https://jira.mongodb.org/browse/EVG-15470)
Introduced `auto-description` flag name, which is a bool flag and if set will retrieve the most recent commit message for a `patch` command and skip the description prompt altogether. If this patch is enqueued to the commit queue later this description carries over as well. Lastly, made it such that the `auto-description` and `description` flag are mutually exclusive.
Built and tested CLI locally
=> EVG-15470 Introduce auto-description flag to the CLI

model/patch/db.go, model/patch_lifecycle_test.go, model/task/db.go, model/task_lifecycle.go, model/task_lifecycle_test.go
[EVG-18634 ](https://jira.mongodb.org/browse/EVG-18634 )
It looks like I originally very purposefully made this query only check for things that either started in range or failed in range but had no start time? I don't understand than scenario 😅 and I don't see anything enlightening [in the PR](https://github.com/evergreen-ci/evergreen/pull/2472). 
=> EVG-18634 change range to consider started or failed within time range

scripts/agent.yml, self-tests.yml
Jira: https://jira.mongodb.org/browse/EVG-17588
I'm also going to clean up some of the smoke test checking logic in a follow-up PR.
* Add expansions.write to the smoke tests.
* Add a grep test to verify that expansions.update and expansions.write works as expected.
* Fix an issue where expansions.write was giving the expansion key-value pair using incorrect syntax (it wasn't actually updating any expansions before this).
* Don't ignore changes to the `scripts` directory since that contains a lot of testing-relevant files.
I tried pointing the smoke test to use my fork's branch with the updated agent.yml. The task itself timed out, but [it did run the grep check successfully](https://parsley.mongodb.com/evergreen/evergreen_ubuntu1604_smoke_test_host_task_patch_1710c8ecaefa268fe34e7f54464f1f …
=> EVG-17588: add smoke test for expansions.write

agent/command.go, config.go
Jira: https://jira.mongodb.org/browse/EVG-18735
The full command string that's shown when a command starts/ends (e.g. `Running 'subprocess.exec' (step 1 of 1)`) is weirdly inconsistent when it comes to using the display name (e.g. `("The display name goes here") 'subprocess.exec' (step 1 of 1)`), using the function name, and mixing up single and double quotes. It's not a big deal, but I feel like it does trip me up a bit over "what's this command called", "is this the function name or the command's display name", "why does a command in a function not show the display name", etc. all the time. My proposal is to display it as something more like this:
`Running 'subprocess.exec' (step 1 of 1).`
`Running 'Wao such cool display name' ('subprocess.exec') (step 1 of 1).`
`Running 'Wao such cool …
=> EVG-18735: standardize the command name in the task log

model/project.go, model/project_aliases.go, model/project_aliases_test.go
[EVG-18221](https://jira.mongodb.org/browse/EVG-18221)
deleted shouldExit variable when checking for aliases because that was causing us to never search project configs for patch aliases 
New alias behavior that I'm proposing : 
Instead of ignoring everything in project configs when a patch alias is defined on the UI,  we still check the project configs.
The UI will still take precedence over the project config patch alias if an alias with the same name is redefined.
My reasoning for that being that users can more easily change the names of custom patch aliases for their specific patch to not match an existing one if they really wanted. 
staging
unit tests
=> EVG-18221 Update to search patch aliases

units/host_termination.go
[EVG-18507](https://jira.mongodb.org/browse/EVG-18507)
We used to increment the idle time of a host when we terminated it so the time from when the last task to run until termination time was included in the tally. Right now, though, I think we only increment when we start a task.
I think this might have been a regression in https://github.com/evergreen-ci/evergreen/commit/4a7a32041d8bd02f4784321820eb2655f7476df2 (specifically [here](https://github.com/evergreen-ci/evergreen/commit/4a7a32041d8bd02f4784321820eb2655f7476df2#diff-6dd488a00c797fb521cd37e03c8869d4fb82c17ee75a9c79eec5648ed8f7a05bL364-L366)).
I'll try it out in staging when I get a chance 😄
=> EVG-18507 increment idle time

cloud/ec2_test.go, cloud/ec2_util.go, cloud/ec2_util_test.go
[EVG-18731](https://jira.mongodb.org/browse/EVG-18731)
Right now Evergreen thinks that Windows is billed by the hour so [we hesitate to terminate idle Windows hosts that aren't close to the end of an hour boundary](https://github.com/evergreen-ci/evergreen/blob/ad9cef43a0f7452cd0ea15aed2565a511429f36d/units/host_monitoring_idle_termination.go#L240-L245). This, in turn, motivates us to limit the Windows host pools so we can minimize idle time. This creates a poor user experience for Windows testing.
We've discovered that AWS switched Windows billing to by-the-second. This PR will make Evergreen terminate them at will. Once this goes in we will be able to raise max hosts for Windows.
Just the unit test. I'll try to get access to the billing info so I can check that this isn't making us …
=> EVG-18731 by the second billing for windows

agent/command.go, cmd/load-smoke-data/load-smoke-data.go, config.go, makefile, model/task/expected_duration.go, operations/service_deploy_smoke_utils.go, scripts/setup-smoke-config.sh, self-tests.yml, testdata/smoke_config.yml
Jira: https://jira.mongodb.org/browse/EVG-17588
This is a mish-mash of improvements to the smoke test.
* Refactor the smoke test logic for readability, including cleaning up the many loops and simplifying down some unnecessarily complicated old logic.
* Add a bunch of doc comments on what the smoke test is testing and how it expects those tests to work in terms of mental model.
* Fix some issues where the smoke test logs things repeatedly, which can lead to confusion when reading the smoke test's task logs.
* Upload the test app server's log file to S3 so that devs can read it to cross-reference what the app server is doing during the smoke test.
* Add some indexes that the app server needed to run some queries. This was producing some spurious errors in the app server logs.
* Remove a …
=> EVG-17588: refactor and improve smoke test debugging experience

self-tests.yml
Jira: https://jira.mongodb.org/browse/EVG-17588
I didn't account for the fact that the s3.put command after the smoke test doesn't upload if the smoke test fails, so I moved it to the `post` block.
Checked in a patch that it still uploaded even if the smoke test fails.
=> EVG-17588: upload smoke test app server logs even if it fails

agent/command/git_merge_pr.go, config.go, units/commit_queue.go
Jira: https://jira.mongodb.org/browse/EVG-18739
When testing a PR in the commit queue, the merge task doesn't need to clone the project since it's just calling the GitHub API to merge the PR.
* Remove unneeded `git.get_project` when merging GitHub PRs.
* Remove unused `URL` parameter from `git.merge_pr`.
Tested with [a PR in the commit queue sandbox](https://github.com/evergreen-ci/commit-queue-sandbox/pull/417) in staging that the merge task succeeded without the `git.get_project` and without the URL parameter.
=> EVG-18739: remove git clone for GitHub PR merges

rest/data/project_settings.go, rest/data/project_settings_test.go
[EVG-18738](https://jira.mongodb.org/browse/EVG-18738)
If an old project enabled the commit queue on the new project page, the commit queue document wasn't being created. This boolean needs to be flipped. 
Reasoned about it.
=> EVG-18738 Fix commit queue document not being created for old projects 

cloud/cloud.go, cloud/docker.go, cloud/ec2.go, cloud/ec2_fleet.go, cloud/ec2_test.go, cloud/gce.go, cloud/mock.go, cloud/openstack.go, cloud/static.go, cloud/vsphere.go, model/distro/distro.go, model/host/host.go, scheduler/scheduler.go
Jira: https://jira.mongodb.org/browse/EVG-8093
The distro-level Docker settings are unused because they distro information is stored in the host document as `DockerOptions`. This is sort of breaking the abstraction layer between the distro provider settings and the host document, but I'm inclined to leave it as-is because we'll be removing the distro container pool feature at some point once the container initiative is generally available.
* Remove unused distro Docker settings.
* Remove unused `GetSettings` method from cloud provider interface.
* Drive-by add a couple small comments in some places for provider settings logic.
* Drive-by clean up a few error messages in the host scheduler.
The distro Docker settings is unused/dead code, but I tested in local Evergreen that the distro …
=> EVG-8093: remove distro Docker settings

model/version.go, model/version_db.go, repotracker/repotracker.go, rest/data/interface.go, rest/data/mock_impl.go, rest/data/version.go, rest/data/version_test.go, rest/route/github.go, rest/route/version_create.go, trigger/process_test.go, trigger/project_triggers.go, trigger/project_triggers_test.go, units/periodic_builds.go
[EVG-18775](https://jira.mongodb.org/browse/EVG-18775)
It was always the behavior that we activated triggered versions right away since we ignore batchtime for them, but for some reason we did this with DoProjectActivation instead of just activating everything when we create the version so this broke when we changed DoProjectActivation to only consider repotracker things.
Did a little refactor to also activate everything when we create the version for other things that call this (git tags, rest created versions, and periodic builds).
Added activate to unit test (failed before adding changes). Will verify existing unit tests pass.
=> EVG-18775 activate triggered versions at creation time

model/host/hostutil.go
Jira: https://jira.mongodb.org/browse/EVG-18794
When setting up a Windows host (of any kind, like a spawn host or task host), part of the provisioning process requires that we create a service user that runs background services (i.e. Jasper) and processes (i.e. the agent monitor and the agent). As part of running services with that user, we have to know its password.
I originally set up this user to have an unexpirable password (the default password expiration is 42 days for our Windows AMIs) because we initially thought we might use this service user after provisioning was finished (e.g. to run processes on long-running hosts like unexpirable hosts). That idea never really panned out and we still just SSH into those hosts. Therefore, we don't need an unexpirable password because …
=> EVG-18794: remove passwordexpires from Windows host provisioning

thirdparty/github.go
[EVG-18811](https://jira.mongodb.org/browse/EVG-18811)
We rely on the list of reviews to know if there is the required number of approvals. The default that listReviews returns is 30. On rare occasions, there will be PRs with more than 30 reviews. For example, today we saw a PR with 37 reviews, and the approval being the 37th. This increases the amount of reviews returned to 100.
=> EVG-18811  Fix approval being hidden 

config_commitqueue.go, globals.go, graphql/mutation_resolver.go, graphql/util.go, model/lifecycle_test.go, model/pod/dispatcher/dispatcher.go, model/task_lifecycle.go, model/task_lifecycle_test.go, rest/model/admin.go, rest/route/host_agent.go, rest/route/pod_agent.go, rest/route/task_restart.go, scheduler/planner.go, service/task.go, service/templates/admin.html, trigger/build.go, units/host_termination.go, units/pod_allocator.go, units/pod_termination.go, units/task_monitor_execution_timeout.go, units/task_stranded_cleanup.go, units/util.go
[EVG-16926](https://jira.mongodb.org/browse/EVG-16926)
We've seen a situation where a task in the commit queue ran a full 10 times because it caused system unresponsive failures, which caused the next batch to wait practically overnight. To avoid situations like that, we want to lower the amount of times system failed tasks can be restarted on the commit queue. This will be configurable on the admin page, and will be set to 5 to start out with.  
Set to five and merged something on staging to make sure it didn't break it.
=> EVG-16926  Make max retries configurable for system failed tasks on the commit queue 

agent/command/s3_put.go, agent/command/s3_put_test.go, config.go
[EVG-17334](https://jira.mongodb.org/browse/EVG-17334)
For users that rely on symlinks, adding all files that match a filter to one root folder breaks those links. I added this as an option instead of changing the existing behavior because users who are currently using may rely on the current behavior. 
Added a test
=> EVG-17334 Add and option to preserve the folder structure for s3 put 

graphql/mutation_resolver.go, model/commitqueue/commit_queue.go, rest/data/commit_queue.go, rest/data/interface.go, rest/data/mock_impl.go, rest/model/patch.go, rest/route/github.go
[EVG-14186](https://jira.mongodb.org/browse/EVG-14186)
Same implementation as the [previous PR](https://github.com/evergreen-ci/evergreen/pull/6198/files/d50817b174f9d1dbd8c5af4c2b9bfacf339ea2dc), with the only difference being that [checkSignedCommit](https://github.com/evergreen-ci/evergreen/pull/6198/files/d50817b174f9d1dbd8c5af4c2b9bfacf339ea2dc#r1082854073) has been reverted to its old behavior of using `&&` rather than `||`.
Created [EVG-18824](https://jira.mongodb.org/browse/EVG-18824) to take a look into the behavior we observed where some commits retrieved were coming up empty.
=> EVG-14186 Allow PR commit queue enqueuing in UI (revert checkSignedCommit)

agent/command/archive_tarball_create.go, agent/command/results_xunit.go, agent/command/s3_copy.go, agent/command/s3_get.go, agent/command/s3_put.go, config.go
[EVG-18006](https://jira.mongodb.org/browse/EVG-18006)
Some agent commands utilize blocking channels when performing key operations, without protection from the possibility that a value may never get sent to the channel. This would cause an indefinite blocking of the command.
Introduced a `select` statement to these goroutines to handle potential context cancellation.
=> EVG-18006 Use select statement for agent commands at risk of blocked goroutines

agent/command/s3_put_test.go
[EVG-17334](https://jira.mongodb.org/browse/EVG-17334)
This test fails on the repotracker but passes on the patch. The logging should help with debugging.
=> EVG-17334 Add logging to test 

agent/command/s3_put_test.go
[EVG-18828](https://jira.mongodb.org/browse/EVG-18828)
This test was failing on windows because the file structure is different. 
Tested on windows in a patch
=> EVG-18828 Fix failing test 

rest/model/commit_queue.go, rest/model/commit_queue_test.go
[EVG-14441](https://jira.mongodb.org/browse/EVG-14441)
Long commit queue messages don't get wrapped which is poor for readability in `git log`.  Made it such that every 72 characters the message will wrap in a way that prevents words from being chopped up in an inconvenient way. Chose 72 characters since it seems to be a [common reccommendation](https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting).
Added new unit tests confirming that long messages will get wrapped cleanly regardless of extra whitespace.
=> EVG-14441 Wrap long commit queue commit messages

agent/agent_command_test.go, agent/agent_test.go, agent/command.go, agent/internal/client/testdata/pre_error.yaml, config.go
[EVG-17650](https://jira.mongodb.org/browse/EVG-17650)
There is currently a bug where if a task fails due to a `pre` command failure, the task itself will get marked as `setup.initial` being the command that failed, which is incorrect. This is because pre & post commands do not ever get set as the current command.
Added a change so that if a task is configured to fail if its pre/post block fails, set each pre & post task as the current command when it runs so that its failure details get correctly propagated up.
Added unit test confirming a failed `pre` command with `pre_error_fails_task` set results in a failure based off the specific `pre` command.
In staging, recreated a simple version of the problem in the ticket. System failure [without …
=> EVG-17650 enable "setup failed" statuses for tasks that fail their pre-commands

model/project_ref_test.go
[EVG-18856](https://jira.mongodb.org/browse/EVG-18856)
the test was failing because we no longer read cached config so I added what we need to the db
tests pass
=> EVG-18856 Fix test and add testing config to db

model/commitqueue/commit_queue.go, model/commitqueue/commit_queue_test.go, model/commitqueue/db.go, operations/commit_queue_test.go, rest/route/host_agent_test.go, units/commit_queue.go
[EVG-17307](https://jira.mongodb.org/browse/EVG-17307)
In order for [these CQ item processing logs](https://github.com/evergreen-ci/evergreen/blob/main/units/commit_queue.go#L193) to show the updated state of the commit queue item, we need to pass it as a pointer to updateVersion. 
Existing tests
=> EVG-17307 Use pointer in UpdateVersion so that logs are up to date 

rest/data/project.go, rest/data/project_test.go
[EVG-14549](https://jira.mongodb.org/browse/EVG-14549)
This is primarily to guard against an accidental overwrite of a private variable fetched from the GET route, but also we don't allow empty private variables (on the UI anyway, although it doesn't really matter since they don't do anything) and we have the "delete" option for that.
Will add to the documentation.
Added to unit test
=> EVG-14549 avoid overwriting variable with the empty string

model/event/commit_queue_event.go, model/task_lifecycle.go, model/task_lifecycle_test.go
[EVG-18530](https://jira.mongodb.org/browse/EVG-18530)
Unlike Github PRs where we [explicitly check](https://gist.github.com/hadjri/fbb86d69df6cf83c05e03106282d5772#file-github-go-L942) if GitHub has created a valid merge commit without conflicts, there is currently nothing stopping us from staging a CLI patch with a merge conflict in it, and enqueuing it to the commit queue. If this happens, the merge task will fail on the first `git.get_project` command of the task, resulting in a [setup failure](https://spruce-staging.corp.mongodb.com/task/sandbox_commit_queue_merge_merge_patch_patch_c23d49c536277965b729fc5c86c75d86a339ab26_63daecc99dbe32c5d5f54b86_23_02_01_22_51_08/logs?execution=0) with errors in the logs saying `patch does not apply`.
The logic behind this change is, rather than …
=> EVG-18530 Suggest a merge conflict is likely if an enqueued CLI patch fails on setup

self-tests.yml
[EVG-15892](https://jira.mongodb.org/browse/EVG-15892)
Let's make sure 5.0 doesn't break anything in advance of upping staging's db version.
=> EVG-15892 upgrade db to 5.0 in self-tests

model/task/db.go, model/task/task.go, rest/data/task_test.go, rest/route/task_project.go
[EVG-16962](https://jira.mongodb.org/browse/EVG-16962)
Add build variant regex filtering to /projects/{project_id}/revisions/{commit_hash}/tasks. Will update documentation once approved. 
tested on staging and added a unit test
=> EVG-16962 Add build variant regex filtering to /projects/{project_id}/revisions/{commit_hash}/tasks 

model/project.go, model/project_test.go
[EVG-18760](https://jira.mongodb.org/browse/EVG-18760)
Right now we only add this expansion for PRs but we should also add it for commit queue items added from PRs.
Added to test.
=> EVG-18760 add github_pr_number expansion to cq patches

model/patch_lifecycle.go, model/project_parser.go, model/project_parser_s3.go, model/project_parser_storage.go, model/project_parser_test.go, scripts/setup-credentials.sh, self-tests.yml, testutil/testing.go, util/yaml_test.go
Jira: https://jira.mongodb.org/browse/EVG-18537
* Implement parser project storage in S3. It's not used anywhere for now, there will be a follow-up to actually use it.
* Add some more docs about the `model.ParserProject` and how it's different from the `model.Project`.
* Add integration tests for storing/retrieving parser projects from S3.
* Tested in staging by making a patch that kept its parser project in S3, then verified that generate.tasks worked with the S3 parser project.
=> EVG-18537: implement parser project S3 storage

model/project_ref.go, model/project_ref_test.go, rest/data/project.go, rest/route/project.go, rest/route/project_test.go, service/project.go
[EVG-18863](https://jira.mongodb.org/browse/EVG-18863)
patch project route has validation now
The ui server does not ask for repo and owner to create/copy project so, so I decided not to add validation there. (even if we did, it would only warn and not error because it would never be enabled. )
I added validation to the modify project ui service so users will not be able to enable projects if it does not pass validation
staging
=> EVG-18863 Add validation to project modify routes

model/generate.go, model/project.go, model/project_parser.go, model/project_ref.go, model/project_test.go, repotracker/repotracker.go
[EVG-18365](https://jira.mongodb.org/browse/EVG-18365)
A query on the DB indicates that this field is not used, probably due to the fact that it was not documented on the Wiki. [I've since added it](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#build-variants) to the BV section and the [limiting when tasks will run](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#limiting-when-a-task-will-run) section.
I expect this renaming to be a safe operation and we won't need to support `disable` and `disabled` concurrently during a deprecation phase.
=> EVG-18365 Rename parser BV "disabled" to "disable"

graphql/query_resolver.go
[EVG-18900](https://jira.mongodb.org/browse/EVG-18900)
I don't know why it was working better on 4.2 (maybe it really does have to do with [the change in sort algo](https://www.mongodb.com/docs/manual/release-notes/4.4/#-sort-changes)). It's interesting that with 6.0 it was also working for me without the change in this PR. I didn't see anything in the intervening release notes that looked related. 🤷 
It seems like the issue is the sort on the entire distro doc (they get compared with [this](https://www.mongodb.com/docs/manual/reference/bson-type-comparison-order/#objects)) vs. a sort on the distro id. I think the sort on distro id is what we're really after anyway.
In local-evergreen the distro sort fails without the change and succeeds with the change.
No
=> EVG-18900 sort hosts on distro _id

model/project.go, model/project_test.go
Jira: https://jira.mongodb.org/browse/EVG-18940
This is a small follow-on to [EVG-18760](https://jira.mongodb.org/browse/EVG-18760). Instead of populating just the PR number for PR commit queue items, add the other GitHub PR expansions as well.
Yes, going to update [the default expansions in the wiki](https://github.com/evergreen-ci/evergreen/wiki/Project-Configuration-Files#default-expansions) once it's merged.
=> EVG-18940: populate GitHub PR expansions for PR commit queue items

testdata/local/admin.json
Facilitates [EVG-18288](https://jira.mongodb.org/browse/EVG-18288)
- Override Logkeeper URL in test environment. This facilitates e2e testing on Spruce by allowing GraphQL to reach a local Logkeeper server with test data.
No
=> EVG-18288: Add local logkeeper URL

units/host_termination.go
[EVG-18744](https://jira.mongodb.org/browse/EVG-18744)
Add `started_by` to the `host successfully terminated` message so we can filter out non-`mci` started hosts when looking at idle time. Add `user_host` so we can differentiate between non-`mci` hosts that are started by users from those started by tasks.
=> EVG-18744 add more host fields to termination logging

config.go, operations/before.go, operations/commit_queue.go
[EVG-7029](https://jira.mongodb.org/browse/EVG-7029)
Currently the `commit-message` flag available in the `enqueue-patch` CLI command does not provide any error that unused parameters have been passed in.  For example, running `enqueue-patch --commit-message hello world` will result in the commit message being just "hello".
Added a change to check if there are more than 1 arguments passed to the `commit-message` flag, and error if so.
Built CLI locally and confirmed that passing in a commit message phrase without quotes causes an error, and succeeds otherwise.
N/A
=> EVG-7029 Error when multi-word commit message is provided without quotes in CLI

model/user/db.go, model/user/user_test.go, rest/route/host.go
[EVG-18956](https://jira.mongodb.org/browse/EVG-18956)
We don't delete the user doc to keep pages from breaking but we don't need to keep the roles; removing them keeps the results from querying for users of a role clean.
Will add to the documentation for the offboard route.
=> EVG-18956 clear roles when offboarding user

model/patch_lifecycle.go
Jira: https://jira.mongodb.org/browse/EVG-18957
This timeout is used to put a deadline on the process of fetching all the GitHub YAML files (i.e. the main YAML and its includes) and apply the patch diff to them. 10 seconds seems kind of short, especially since YAMLs can be split across many files, so increasing the timeout should reduce such flakiness.
Not really something that's testable since it's a timeout against a third-party app.
N/A
=> EVG-18957: increase timeout for fetching project files

go.mod, go.sum
[EVG-18931](https://jira.mongodb.org/browse/EVG-18931)
update grip
no
=> EVG-18931 Upgrade dependencies to use latest version of grip

docs/pull_request_template.md
I added a bit of auto-linking magic to the GitHub settings so that if you just enter the Jira ticket number, it'll automatically link to the Jira ticket if you fill in the number, without needing to write a Markdown-style link. This only works for EVG tickets.
=> Add auto-linked Jira tickets to PR template

graphql/mutation_resolver.go, model/project_ref.go, model/project_ref_test.go, rest/data/project.go, rest/data/project_settings.go, rest/data/project_test.go, rest/route/project.go, service/project.go
[EVG-18784](https://jira.mongodb.org/browse/EVG-18784)
when creating/copying projects on spruce, users will now receive a warning toast 
the validation function has been updated to return an error code and handle all edge cases that it didn't handle before 
(test has been added for that)
staging
creating and copying projects that are at the limit will warn the users
eventually (there is a ticket for create project documentation)
=> EVG-18784 Warn users when creating/copying projects at limit

graphql/generated.go, graphql/integration_atomic_test_util.go, graphql/models_gen.go, graphql/schema/query.graphql, graphql/schema/types/task.graphql, graphql/schema/types/task_logs.graphql, graphql/task_resolver.go, graphql/tests/task/data.json, graphql/tests/task/queries/taskLogs-allLogs.graphql, graphql/tests/task/queries/taskLogs-unstarted.graphql, graphql/tests/task/results.json
[EVG-18385](https://jira.mongodb.org/browse/EVG-18385)
Updated atomic test suite code to give better errors on what the problem is.
Refactored `taskLogs` resolver to fall under `task.taskLogs`
graphql tests    
No
=> EVG-18385 Refactor taskLogs resolver to fall under task

rest/model/project.go, rest/route/project.go
EVG-17690
This ticket was made to super restrict what's returned from this route. I think that's not actually needed -- most things in project settings really don't need to be secret, it's mostly variables that need to be kept apart and those already aren't returned from this route. Modified the route a bit to also hide a few more variables. Theoretically it would be reasonable to extend this thinking to the project permissions and the other project routes but I think that's pretty low priority right now and we'd just end up not getting to that work. I can add it as a future project idea however.
Ensured existing tests pass.
Yes, I'll add this to the project page documentation and the project rest route documentation.
=> EVG-17690 ensure some fields can't be accessed by non project admins

model/lifecycle.go, model/task_lifecycle.go, model/task_lifecycle_test.go, model/version_db_test.go, repotracker/repotracker.go, rest/route/host_agent_test.go, thirdparty/github.go
[EVG-7440](https://jira.mongodb.org/browse/EVG-7440)
The [previous PR](https://github.com/evergreen-ci/evergreen/pull/6155) decoupled PR status updating from the `UpdatePatchStatus` function for understandability purposes, yet when the new `checkUpdateBuildPRStatus` was placed in `UpdateBuildAndVersionStatusForTask` it would only perform the PR status update if the task's [build status had changed](https://github.com/evergreen-ci/evergreen/pull/6155/files#diff-4bef865c41d6d16e1056e61806c23fb8bbc896b3739472dd60f0dd463ef5d2b9R1377), not if the patch status had changed.  This means that every time a build in a PR changed status (whether it was a restart, or simply `MarkEnd` calling) we were calling the GitHub checks API, rather than only when the overall PR changed status. 
Although I think …
=> EVG-7440 Do not call checks API on MarkEnd unless patch status changes

units/github_status_api.go, units/patch_intent.go
EVG-18732
Right now we log if a patch isn't created bc files are ignored but we don't tell the user; this is really confusing and often means we need to look at splunk logs to tell the user what happened. We should instead return a successful status with a message.
Cleaned up some other stuff as I went.
Tested with a PR https://github.com/evergreen-ci/commit-queue-sandbox/pull/448
Document that no patch will be created for a PR containing only ignored file changes.
=> EVG-18732 surface if a patch isn't created bc all files are ignored

units/generate_tasks.go
EVG-18929
Add timeout for saving the new configuration, builds, and tasks during generate.tasks. I looked at stats for the maximum runtime in the past month and the slowest runtime for saving was 15 minutes, so I doubled it for padding. This timeout is probably too generous, but I'm not looking to optimize the performance of saving in this PR, just prevent it from running forever.
N/A
N/A
=> EVG-18929: put timeout on saving generated tasks

rest/route/commit_queue.go
EVG-18724
Based on Splunk, users seem to be receiving multiple commit queue merge notifications because the agent gets a 500 from this route and retries the request (which results in an event log for each error attempt). I don't know specifically which line in `ConcludeMerge` is causing the 500, so I added a debug log so that the next time it happens, I can see what errored.
N/A
N/A
=> EVG-18724: add debug log for conclude merge 500 error

service/rest_patch.go
EVG-18700
I missed that `getPatchConfig` in the legacy route depends on the `PatchedParserProject`, and that route is used by the legacy CLI client to get parser project info.
This function already doesn't have testing, I don't want to add tests for a hotfix.
N/A
=> EVG-18700: get project config with unfinalized patches from legacy route

service/rest_patch.go
EVG-18700
Small fix to use the actual project context patch field, rather than use the nilled project context version.
=> EVG-18700: fix patch project method usage

self-tests.yml
[EVG-18584](https://jira.mongodb.org/browse/EVG-18584)
https://github.com/evergreen-ci/evergreen/commit/e1789d96a1729ae60ad9dd48d6401bb9a2f16cd5 changed the go version to a version that's not present on our old windows version. This will move us to a more recent version.
=> EVG-18584 upgrade our windows distro

model/project_ref.go
EVG-18878
Change to set all incoming created projects as `Private: true` by default.
=> EVG-18878 Initialize newly created projects as private

cmd/build-cross-compile/build-cross-compile.go, makefile
EVG-17642
For usage of Delve, passing compiler flags `-gcflags="-N -l"` is necessary to disable compiler optimizations, which enables breakpoints and running the application in debug mode. Essentially this ensures that the compiled dist retains all of the necessary debugging information, such as variable names and function boundaries, and that the code behaves more predictably during debugging.
Since we're only debugging staging, I changed the `dist-staging` command to use these flags.
Ran `make dist` and `make dist-staging` and confirmed only the latter was compiled with the custom flags.
N/A because kernel-tools still needs a PR before remote debugging docs can be written.
=> EVG-17642 Use debug compile flags for dist-staging

model/lifecycle.go, repotracker/repotracker_test.go
EVG-19082
The version activation done by repotracker jobs has a [bug](https://gist.github.com/hadjri/dc7854c1bc80233cf3252684ca5eebef#file-lifecycle-go-L135) where it does not ignore disabled tasks when doing activation. Therefore,  setting `priority: -1 in YAML` would not have any effect for mainline versions because they get [un-disabled ](https://gist.github.com/hadjri/3e7b9681daeebadb310db6bc0fc3b2e8#file-db-go-L2687)during activation, which is behavior we don't want. Reproduced this bug in staging.
Added a change to not query disabled tasks when performing activation.
Added new unit test affirming this, also tested in staging.
N/A
=> EVG-19082 Do not activate disabled tasks in repotracker job

model/build/build.go, model/build/build_test.go, model/patch/db.go, model/patch/db_test.go, model/patch/patch.go, rest/route/github.go, rest/route/github_test.go, trigger/build.go, trigger/build_test.go, trigger/patch.go, trigger/payloads.go, trigger/task.go, units/github_status_api_test.go, units/github_status_refresh.go, units/github_status_refresh_test.go
EVG-16349
Add `github status` to allow for refreshing checks. I'm torn between status, checks, and refresh for the language here. Any preferences?
Refactored a number of trigger things so they could be used in units.
Tested a lot on staging. 
Created to test general functionality https://github.com/evergreen-ci/commit-queue-sandbox/pull/448
and https://github.com/evergreen-ci/commit-queue-sandbox/pull/449 to test child patches.
Added &refreshed_status=true to these to make it clearer that they were just generated.
(Build links aren't correct here but that was fixed in cleanup and isn't a huge deal either way)
Yes -- I don't think we have a documentation page about evergreen github commands; if not I'll add one, otherwise i'll add to it.
=> EVG-16349 add github comment to refresh status

rest/data/commit_queue.go, rest/data/mock_impl.go, thirdparty/github.go
[EVG-18812](https://jira.mongodb.org/browse/EVG-18812)
This will block a pr from getting enqueued to the commit queue if branch protection rules are not met. 
yes: [EVG-19096](https://jira.mongodb.org/browse/EVG-19096)
=> EVG-18812 Force the commit queue to respect branch protection rules 

self-tests.yml
[EVG-18584](https://jira.mongodb.org/browse/EVG-18584)
https://github.com/evergreen-ci/evergreen/pull/6285 moved the remaining stuff off archlinux because it doesn't have go1.19 on it (because it's hard for build to build images for). It missed dist-staging. This PR moves dist-staging to ubuntu2004.
I'll add dist-staging to this PR
N/A
=> EVG-18584 run dist-staging on ubuntu

rest/data/commit_queue.go, thirdparty/github.go
EVG-19098
We added the `evergreen refresh` comment which will be cool but it would also be cool if we automatically refreshed this if we see that a merge is blocked but the patch is successful (this may over-refresh since a merge can be blocked on other things but since this is manually triggered I don't expect it to be too much).
Tested with a PR, where the first merge fails because PR status sending is disabled, and the second merge succeeds.
https://github.com/evergreen-ci/commit-queue-sandbox/pull/453
Will add to the `evergreen merge` documentation
=> EVG-19098 refresh status if commit queue merge is blocked

thirdparty/git.go
EVG-19135
Improve error messages when `git apply --numstat` fails to make it more clear to users why their patch fails.
[Slack archive](https://mongodb.slack.com/archives/C0V896UV8/p1678303811935539)
N/A
No.
=> EVG-19135: Improve patch validate error message

util/webhook_grip.go, util/webhook_grip_test.go
[EVG-19138](https://jira.mongodb.org/browse/EVG-19138)
https://github.com/evergreen-ci/evergreen/pull/6313 introduced explicit logging when a webhook is sent. It was reverted because [test-util was failing](https://spruce.mongodb.com/task/evergreen_ubuntu2004_test_util_a023440dc412a3870b9a6177c189296f0e4c412a_23_03_09_16_50_32/tests?execution=1&sortBy=STATUS&sortDir=ASC). This was because the test uses a mock transport that sends a `nil` body. Since [the actual transport guarantees the body will never be nil](https://pkg.go.dev/net/http#Response) it makes sense to me to make the mock consistent with that and return the same thing the http transport will.
This PR cherry-picks the previous change and fixes the test.
The test-util test passes now (hopefully it will pass in evergreen too 😅) …
=> EVG-19138 reintroduce webhook logging

rest/route/service.go, rest/route/test.go
[EVG-19162](https://jira.mongodb.org/browse/EVG-19162)
In https://github.com/evergreen-ci/evergreen/pull/6269 we removed [the test count route](https://github.com/evergreen-ci/evergreen/wiki/REST-V2-Usage#get-the-test-count-from-a-task). I think this was inadvertent so this PR will restore the route using the new framework for test stats.
I'll put it up in staging when staging becomes available. I intend to try it out for a task that ran before the re-architecture and a task that ran after it.
N/A
=> EVG-19162 restore the test count route

rest/route/service.go, service/task.go
EVG-18632
Clean up TODOs from ticket.
- Removes cedar test results agent route now that all agents are updated.
N/A
N/A
=> EVG-18632: TODO clean up

makefile
EVG-19132
(Part of a skunkworks security initiative! 😇 )
This PR adds a checksum verification for the Go lint installer script. This reduces the probability of running a malicious script. (For a recent example of such an attack, see https://blog.aquasec.com/codecovs-breach-supply-chain-attack.)
`make lint-util` passes locally. Also ran following [these instructions](https://github.com/evergreen-ci/evergreen/pull/6315#issuecomment-1466621446).
No
=> EVG-19132 Add checksum verification for Go lint installer

cloud/ec2.go, cloud/ec2_fleet.go, cloud/ec2_fleet_test.go, cloud/ec2_util.go
EVG-19187
Spawning spot hosts via fleet can result in `noReservationError` when the instance no longer exists, so `GetInstanceStatus` has to handle that explicitly.
No.
=> EVG-19187: treat no reservation as nonexistent when getting fleet instance status

graphql/mutation_resolver.go, rest/data/project.go, rest/data/project_test.go
EVG-18950 
it adds a reporter to the jira ticket that is created requesting the s3 creds from build
staging
successfully created ticket with reporter and got an email
https://jira.mongodb.org/browse/BUILD-16917?jql=project%20%3D%20BUILD%20ORDER%20BY%20created%20DESC
will be part of the document the project ticket
=> EVG-18950 Add reporter to jira tickets created by s3 cred request

graphql/directive_test.go, graphql/generated.go, graphql/permissions_resolver.go, graphql/resolver.go, graphql/schema/directives.graphql, graphql/schema/mutation.graphql, model/user/user.go, public/static/js/projects.js, service/project.go, service/templates/projects.html, service/ui.go
EVG-18267
Created a new directive for the create and copy project mutations. 
The create project button will show up for anyone who is an admin for a project 
Users will not be permitted to duplicate a project that they are not admins for.
Changing this for our rest routes would require new gimlet functions so I think the work should be done in another ticket 
I also think that we shouldn't allow users to create projects on the legacy page anymore because they use a ui project route that we can get rid of
Staging 
I can now see create project and duplicate project buttons without super user perms but can only duplicate project that I am an admin in 
Update it with doc ticket for this project
=> EVG-18267 Update project creation permissions for UI

docs/graphql.md
EVG-19025
Adds documentation for the GraphQL API. Summarizing the comments from the scope of PM-3106. 
Yes, on the docs site. Tagging @bsamek  to ensure this gets added to the docs site.
=> EVG-19025 Add documentation for GraphQL API

trigger/task.go
EVG-18830 
User requested that it be clearer that our regression catcher has only potentially caught a regression (bc of flaky tasks and etc)
=> EVG-18830 clarify that found regressions aren't confirmed

rest/route/github.go, rest/route/github_test.go
EVG-15417
Realized a couple of things about the help text as I started documenting.
1) even though `evergreen retry` and `evergreen patch` technically do the same work in the backend, we only do the action based on what's enabled in the project, so separated these commands and added some context.
2) added consideration for if there are no enabled PR testing projects for the branch, but the repo is enabled, since we do allow PR testing then.
Added unit tests
Yes added to https://github.com/evergreen-ci/evergreen/wiki/Github-Integrations
=> EVG-15417 add handling for repos to help text

rest/data/commit_queue.go
EVG-19234 
Originally only refreshed checks under the assumption that checks would rely on the whole version, but that isn't the case. Not concerned about Github limit for this since it still has to be user triggered.
Probably on the Github integrations page.
=> EVG-19234 always refresh checks for a blocked merge

go.mod, graphql/mutation_resolver.go, graphql/patch_resolver.go, graphql/query_resolver.go, graphql/util.go, graphql/version_resolver.go, model/task/db.go, model/task/db_test.go, model/task/task_test.go
EVG-19080
The GetTasksByVersion query was failing despite only returning 10 entries due to a large generated_json field in each document. This projects that field out to prevent the query from OOMing.
Also passes context to the queries so they can be picked up in the OTEL traces. (Helped me narrow down the bug) 
Tested the patch in the ticket and it now works.
=> EVG-19080 Prevent tasks query from failing on large generated tasks.

cloud/ec2.go, cloud/ec2_fleet.go, cloud/ec2_fleet_test.go, cloud/ec2_test.go
[EVG-18607](https://jira.mongodb.org/browse/EVG-18607)
This is the Vert (revert of the [revert](https://github.com/evergreen-ci/evergreen/pull/6354)) for "EVG-18607 Include the IamInstanceProfile field in the RunInstancesInput struct" with the addition of a check that makes sure we are not trying to launch something with an empty ARN. 
Tested on staging with 3 different scenarios. 
no
=> Vert: "EVG-18607 Include the IamInstanceProfile field in the RunInstancesInput struct" 

agent/command/exec.go, agent/command/exec_test.go, agent/command/shell_test.go, config.go
Reverts evergreen-ci/evergreen#6342 due to an issue where a project was relying on `XDG_CACHE_HOME`.
=> Revert "EVG-18630: set default value for XDG_CACHE_HOME in agent commands"

graphql/query_resolver.go, model/task/db.go, model/task/db_test.go, model/version.go, model/version_test.go
EVG-19270
Dove down a honeycomb rabbit hole and wanted to instrument the mainline commits query to get better performance insights. Passes context to the db calls so they can be tracked as part of the same span.
=> EVG-19270 Pass context to mainline commits db queries

config_db.go, config_test.go, config_tracer.go, environment.go, go.mod, go.sum, public/static/js/admin.js, rest/data/admin_test.go, rest/model/admin.go, rest/model/admin_test.go, service/templates/admin.html, testutil/config.go
[EVG-19189](https://jira.mongodb.org/browse/EVG-19189)
Send spans for calls to external services, such as GitHub. 
Add a list of hosts we're interested in tracking to admin settings. This is because 
1. it was looking really excessive to send spans for every single log message we send to Splunk.
2. in some cases this library's spans might not add much since other instrumentation will have us better covered. E.g calls to the AWS API might be superfluous once we do [EVG-19211](https://jira.mongodb.org/browse/EVG-19211).
An alternative could be to make it a list of excluded hosts, but being explicit about what we wanted to track made sense to me. We could always go the other way later.
Works in staging:
Yielded a trace that included two calls to the GitHub API.
N/A
=> EVG-19189 use tracer client for external API calls

config.go, operations/commit_queue.go, operations/flags.go, operations/http.go, operations/patch.go, operations/patch_util.go, service/api.go, service/api_patch.go
EVG-19103 
To support a simpler profiling workflow, Jeff's team needs a way to re-run tasks with different parameters; we settled on creating a new patch with an existing diff, and allowing them to pass in the patch author (as the person who clicks the button to run this workflow). 
Created https://spruce-staging.corp.mongodb.com/version/6421fb86b23736777fc2d89e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC using `egss patch-file --diff-file  test_diff_file --param hello=world --base 0c0255c06 --variants ubuntu2004 --tasks test-model --project evg --author bynn.lee` (egss -> staging shortcut). This command failed before I added permissions to myself to submit on behalf of other users.
No bc CLI command but I'll add some details to the ticket for Jeff
=> EVG-19103 add param and author flags to patch-file

agent/command/git_merge_pr.go, agent/command/registry.go, config.go, thirdparty/github.go
EVG-18971
Attempted to fix this already by using getGithubClientRetry but didn't realize this only retries in certain cases. Adding an explicit retry to the merge command will more reliably always retry on error. 
added some comments
=> EVG-18971 fix retry logic for merging cq items

agent/command/git.go, config.go
EVG-19176
This runs git clone in verbose mode on the last two retries. I only added it on the last two because if it only retries 2 or 3 times and passes, then I'm guess that the verbose logs are not necessary. And if it does retry the full five times and then fails, it's probably nice to have two iterations of verbose logs to look at in case there's any variation between them. I'm open to feedback on when we should start using verbose mode. 
Tested on staging 
NA
=> EVG-19176  Add “verbose mode” to git clone retries

docs/02-Test with Evergreen/01-Configure a Project/01-Project-Configuration-Files.md, docs/02-Test with Evergreen/01-Configure a Project/02-Project-Commands.md, docs/02-Test with Evergreen/01-Configure a Project/03-Project-and-Distro-Settings.md, docs/02-Test with Evergreen/05-Use the API/01-REST-V2-Usage.md, docs/04-Modify Evergreen/01-Using-Degrade-Mode.md
Docs have a bunch of markdown formatting mistakes, I fixed some of them.
* Remove incorrect escapes of single/double quotes.
* Remove some leftover rst formatting.
* Fix markdown table formatting (I have a plugin to automatically do this, I didn't do it by hand).
=> docs: fix some markdown formatting errors

model/patch/patch.go, model/project.go, trigger/payloads.go, units/github_status_refresh_test.go
EVG-19059
child patch links were not correctly redirecting users 
the link in this pr correctly links child patches
https://github.com/evergreen-ci/commit-queue-sandbox/pull/464
=> EVG-19059 Route child patch links correctly

model/lifecycle_test.go, model/task/task.go
EVG-18598
Verified through testing that restarting an individual task already sets disabled task priorities to 0 when they're restarted, so this only affects version restarts.
Added to a unit test.
=> EVG-18598 reset disabled priorities when restarting version

docs/02-Test with Evergreen/05-Use the API/01-REST-V2-Usage.md
EVG-18934
Documenting the [implementation](https://github.com/evergreen-ci/evergreen/commit/f509cb0771728f5cfbfa1448f469f8adce5ecaad) of this PR (will include `.md` file changes of PRs from now on - was used to the pattern of updating docs manually in the wiki post merge)
=> Add to task annotations docs

model/task_lifecycle.go
EVG-19293
https://mongodb.slack.com/archives/C866SR2LR/p1681160462265489
Let's see how long this takes and if it's making mark end problematic.
=> EVG-19293 introduce logging to understand end task stats implications

config.go, operations/http.go, service/api_patch.go
EVG-19029
When we return an "unauthorized" label we wrap advice on re-logging in via the UI. We return unauthorized for a few situations where that's not actually the case, it's just the project isn't configured for it, so modified this. Also improved how the message itself looks (right now the sentences run right into each other).
Original: 
```Unexpected reply from server (401 Unauthorized): 400 (Bad Request): patching is disabledPossibly user credentials are expired, try logging in again via the Evergreen web UI.```
New: 
```Unexpected reply from server (400 Bad Request): 400 (Bad Request): patching is disabled```
=> EVG-19029 improve when/how we provide auth advice via CLI

self-tests-staging.yml
EVG-19305
GraphQL tests are currently failing with a ["cannot create namespace"](https://evergreen-staging.corp.mongodb.com/task_log_raw/evg_ubuntu1604_container_test_graphql_0e89303b82adbfb5351dd3e36c56ba5dc91a74a1_23_04_11_13_17_36/2?type=T#L453) error, which is a byproduct of using MongoDB 4.2, which will not automatically create namespaces if they do not exist.
Furthermore, our container variant is still on Ubuntu 16.04, preventing it from running mongoDB versions 5 (and 6 in the future), which is what we're currently using for our tests in production.  Rather than bumping the container version of MongoDB from 4.2 to 4.4, I've bumped it up to 5.0 and created a [new Docker image](https://hub.docker.com/r/hadjri/evg-container-self-tests) running on Ubuntu 20.04 along with necessary …
=> EVG-19305 Upgrade containerized variant to Ubuntu 20.04 and Mongo v5

agent/command/results_xunit.go, agent/command/results_xunit_parser.go, agent/command/results_xunit_parser_test.go, agent/command/testdata/xunit/junit_1.xml, agent/command/testdata/xunit/junit_3.xml, config.go
EVG-19262
Added some `SysOut` and `SysErr` fields to test cases for `attach.xunit_results`, similarly to how we do it for test suites.
The large line change diff comes from me doing a (Cmd + L) file reformat in Goland IDE because the file was hard to read.
Confirmed sysout and syserr are showing up in logs for test cases in staging now. Added unit tests
n/a
=> EVG-19262 Add system logging to testCase

model/task/task.go, model/task/task_test.go
EVG-19620
When creating the `testresult.TaskOptions` make sure we are using the `OldTaskID` field for archived tasks.
Added more unit tests and tested in staging. 
N/A
=> EVG-19620: fix archived task test result fetching

graphql/tests/mutation/saveRepoSettingsForSection/queries/general_section.graphql, model/project_ref.go, model/project_ref_test.go, rest/data/project_settings.go, rest/data/project_settings_test.go, rest/route/project_test.go, rest/route/repo_test.go
[EVG-19597](https://jira.mongodb.org/browse/EVG-19597) 
Realized from Bynn's scope that Lisbeth was able to track a personal Github org. After some investigation, it looks like the workflow "change owner -> enable repo -> enable project" is a loophole, since we don't validate this for projects attached to repo, since we assumed that the repo had to be valid. This would also be true for attach to new repo. 
Fixed both of these functions to validate, and updated the save page to validate strictly.
Added some unit tests; tested in staging
=> EVG-19597 always validate github org when attaching to repo / saving page

service/version.go
EVG-19269
The legacy version page was failing but Spruce wasn't so I updated it so that we redirect to Spruce early and this should hopefully unblock cloud.
I also added some logging so we could figure out why this is happening. 
There is also a chance that this change will not fix the issue but that will also be made clearer by the logging.
=> EVG-19269 Reroute version page to spruce before checking for project

model/task/expected_duration.go, model/task/expected_duration_test.go, model/task/task.go, model/task_lifecycle.go
EVG-19293 
Removing standard deviation didn't make this computation more expensive. I don't see that dashboards are using it or see an argument that it's worth logging so I think we should drop this to keep EndTask efficient.
=> EVG-19293 remove logging average historic runtime from end stats

model/patch_lifecycle.go
EVG-19631
I forgot to remove a piece of code as part of EVG-18700. It should be safe to remove, since the if block is redundant.
Existing unit tests pass and submitted a patch in staging to double check that things are working.
N/A
=> EVG-19631: remove fallback logic for inserting parser project during patch finalization

go.mod, go.sum, graphql/query_resolver.go, graphql/util.go, model/testresult/cedar_service.go, model/testresult/local_service.go, model/testresult/local_service_test.go, model/testresult/testresult.go, rest/model/task.go
EVG-14306, EVG-19287
- Update timber and the test results interface to enable multi sort logic
- Apply multi sort logic to the Task.tests resolver
- Add the legacy `HasCedarResults` field to the API task model to fix the bug in the Task.tests resolver where older tasks using said field would not return tasks. 
Added unit tests and tested that single sort logic works in staging. I confirmed using the graphql playground that the Task.tests resolver returns tests for older tasks using the `HasCedarResults` field.
N/A
=> EVG-14306, EVG-19287: Apply mutli sort logic to test resolvers and set HasCedarResults field in the API task model

makefile
EVG-19670
Currently, unless you have DEBUG_ENABLED set on your local environment variables, the staging dist will not compile with the right flags needed for Delve to attach.
Making a makefile change to make this step unnecessary, to make it more convenient to setup remote debugging.
Manually tested to confirm.
=> EVG-19670 Remove need for setting DEBUG_ENABLED env var for remote debugging

cloud/cloud.go, cloud/docker.go, cloud/ec2.go, cloud/ec2_fleet.go, cloud/gce.go, cloud/mock.go, cloud/openstack.go, cloud/static.go, cloud/vsphere.go, model/host/host.go
EVG-19334
Delete the host ID field from the host's volume attachment. The host ID is only used in a single error check and is never persisted in the DB, so it seems like it should just be removed.
* Delete host ID from volume attachment model.
* Change return type in cloud provider so it can still return the host ID for the one error check.
It's not used except in one error case, so it only has to compile and pass existing tests.
N/A
=> EVG-19334: delete host ID field from volume attachment

trigger/patch.go, trigger/version.go
EVG-19630
child patch statuses were not updating correctly on gituhb because we were passing in a collective status instead 
updated to pass in the correct status
staging sandbox pr updates statuses correctly 
https://github.com/evergreen-ci/commit-queue-sandbox/pull/467
=> EVG-19630 Update correct child patch status to github

model/lifecycle.go, model/patch/patch.go, model/patch/patch_test.go, model/patch_lifecycle.go, model/project.go, model/project_test.go, rest/data/commit_queue.go, units/commit_queue.go, units/commit_queue_test.go
EVG-19631
There was apparently one remaining place that was dependent on setting the `PatchedParserProject` (which is deprecated) to add the merge task to the commit queue patch. I removed that dependency, so nowhere in the code base sets the `PatchedParserProject` on the patch doc anymore. After this is deployed, I'm going to re-apply #6409, which should be safe once the pre-deploy commit queue patches all finish running.
Ran existing tests, and ran a commit queue merge in the sandbox.
N/A
=> EVG-19631: remove commit queue merge dependence on patched parser project

rest/data/commit_queue.go, rest/data/commit_queue_test.go
EVG-18876
For PR CQ items, we create the patch slightly differently such that commit_messages isn't populated. 
[tested on staging](https://evergreen-staging.corp.mongodb.com/rest/v2/patches/6440287cb23736ed76eda692) / added to unit test
=> EVG-18876 include commit messages for PR items

model/patch_lifecycle.go
This reverts commit 91b30e3ed3954126394a71d071e34108b153a894.
EVG-19631
This is re-applying #6409 as-is. Now that #6423 is complete, no place in the code base should depend on storing `PatchedParserProject` in the patch doc, so it should be safe to simplify the finalization logic.
Double checked that submitting a commit queue patch in the staging sandbox worked as expected (https://github.com/evergreen-ci/commit-queue-sandbox/pull/469).
N/A
=> Revert "Revert "EVG-19631: remove fallback logic for inserting parser project during patch finalization (#6409)""

agent/command/testdata/generated.json, config.go, operations/service_deploy_smoke_utils.go, scripts/agent.yml
EVG-17589
Added a generate.tasks command to the `agent.yml` that the smoke tests use, and modified some logic in the smoke test itself to check that the generated tasks are created properly and succeed. I'd expect this patch to fail because the `agent.yml` changes are not yet in the main branch, but attached evidence of the task passing when I pointed it to my forked branch.
Task [succeeded in staging](https://spruce.mongodb.com/task/evergreen_ubuntu2004_smoke_test_host_task_patch_b83cfc0b5578f8cfad5b8bfaf6c7db977caf1a23_64469437850e61d595b5aa1b_23_04_24_14_37_56/logs?execution=0&logtype=task)
=> EVG-17589 Add generator to smoke config

model/task_lifecycle.go
EVG-19293
Calculating task end stats looks a lot better now so removing this logging.
=> EVG-19293 remove logging

agent/agent_test.go, agent/command.go, agent/command/git.go, agent/internal/task_config.go, config.go, globals.go
[EVG-19201](https://jira.mongodb.org/browse/EVG-19201)
When the task traces went live we noticed additional attributes that would be helpful.
[Works in staging](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen-agent/result/Hm6V92CB3qX/trace/ZCed9RtmQA?fields[]=c_name&fields[]=c_service.name&span=d6ba0a0d05188b2f). Adding the task attributes to the error lets us do stuff like [this](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen-agent/result/7LEM7qK3Tf2). They aren't added automatically since the HC span processor [only adds the attributes to the span itself](https://github.com/honeycombio/honeycomb-opentelemetry-go/blob/3c99d6a5ed156936da680c6e4051ce472cab89eb/baggage_span_processor.go#L37-L42).
=> EVG-19201 add more attributes

repotracker/repotracker.go, repotracker/repotracker_test.go
EVG-18278
The slack target for build break notifications didn't include the "@" like it should have. I opted to fix this instead of removing it because it's used by a lot of projects and only the slack (and not email) target was broken. Additionally, this was already fixed for most slack users when we switched to using memberIds for slack. 
Expanded existing tests.
=> EVG-18278 Fix slack target for build break notifications for admins 

rest/data/commit_queue.go
[EVG-19581](https://jira.mongodb.org/browse/EVG-19581)
This updates the evergreen merge error message for added clarity. 
Tested on sandbox
=> EVG-19581 Improve messaging for pr is not mergeable

cloud/pod_util.go, cloud/pod_util_test.go, config_cloud.go, rest/model/admin.go, service/templates/admin.html, testutil/config.go
EVG-19716
Saw that container tasks were suddenly unable to start at all since OTEL changes have been added to the agent. 
Turns out it's because [Opentelemetry's](https://gist.github.com/hadjri/11fca9d9e9629347a2257706709b6e5c#file-ecs-go-L153) implementation that parses ECS task definitions sends an error if the log stream is not specified in the ECS log options, causing our agents to fail and exit without running tasks with the following error: `[p=emergency]: constructing agent: initializing tracer provider: making otel resource: detecting resources: [the ECS Metadata v4 did not return a AwsLogStream name]`
Added "awslogs-stream-prefix" as a mandatory option to our ECS log configuration since OTEL requires it. It also makes the stream names more readable in ECS so that is a plus too. …
=> EVG-19716 Add log stream prefix to ECS options to fix OTEL error

graphql/tests/mutation/saveProjectSettingsForSection/queries/general_section.graphql, graphql/tests/mutation/saveRepoSettingsForSection/queries/general_section.graphql, model/project_ref.go, model/project_ref_test.go, model/repo_ref.go, rest/data/project_settings.go, rest/data/project_settings_test.go
EVG-19698
- Prevent users from saving an enabled project with no branch (front end validation is also being added in https://github.com/evergreen-ci/spruce/pull/1802)
- New projects no longer default to `main` branch (empty string instead)
- Added unit test and tested on the UI
N/A
=> EVG-19698: Improve branch project settings validation

docs/02-Configure-a-Project/01-Project-Configuration-Files.md, model/generate.go, model/generate_test.go, model/lifecycle.go, model/lifecycle_test.go, model/project.go, model/project_parser.go, model/project_parser_test.go, model/project_test.go, repotracker/repotracker.go, validator/project_validator_test.go
EVG-18405
The original ticket asks for being able to specify `patch_only` and `disable` at the build variant level. This is half of the requested change and only includes `patch_only`. `disable` already exists but it appears to be non-functional (it also has some problems in that it's not a pointer, so there's no way to distinguish between it being unset and it being set to false). To reduce the riskiness of these changes, I'm going to include a follow-up PR to fix build variant level `disable`.
For completeness' sake, I will also have a follow-up PR to support other fields at the build variant level, such as `patchable`, `allow_for_git_tag` and `git_tag_only`.
* Refactor parser project translation to ensure that the build variant task unit's `Variant` is always set when it's translated …
=> EVG-18405: support build variant patch_only

config.go, operations/service_deploy_smoke_utils.go
EVG-19708
Since generate.tasks has been added to the smoke tests, they do more work and have occasionally been [timing out](https://spruce.mongodb.com/version/644833a661837db984a8c099/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) since they're not able to always verify the tasks have succeeded within 30 attempts. Increasing the task check attempts from 30 to 40 which should help alleviate this.
Submitted a few smoke test patches and have not been able to reproduce the timeouts since
=> EVG-19708 Increase smoke test task check attempts

units/commit_queue.go, units/commit_queue_test.go
EVG-18405
Based on [Splunk logs](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20EVG-18405&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1682959680&latest=1682961498&sid=1682961944.3287592), there's exactly one place that doesn't follow the "all build variant task units are created by project translation" rule, and it's because the commit queue job manually edits the project model to add in the merge task group. I don't believe that the missing `Variant` has any effect on the merge task's behavior, but I'd like to remove [this fallback behavior](https://github.com/evergreen-ci/evergreen/blob/762e83e5c8beb3990eb4965d3380cd8f9e6287dd/model/project.go#L1551-L1561).
Added to commit queue unit tests.
N/A
=> EVG-18405: set variant in commit queue merge task group

rest/route/patch.go
EVG-19622
Copy paste error broke this route. 
Tested on staging with https://evergreen-staging.corp.mongodb.com/rest/v2/patches/64503bc9b237363a1c5db3ad/raw
=> EVG-19622 fix patches raw route

rest/route/service.go
EVG-19793
checking for project permissions was panicking because rotate route doesnt have to be attached to a project
switched to super user settings
staging
=> EVG-19793 Update middleware for rotate route

model/project_ref.go, rest/data/project.go, rest/data/project_settings.go, rest/route/project.go, rest/route/project_test.go
EVG-18260 
Moved project variable creation into Add() since we assume that both project ref and project var must exist for any project in lots of places.
In thinking through this, realized we should gate hidden projects from being modifiable via route or UI since they're meant to be backend only skeleton projects.
Verified in staging that a hidden project could be accessed via rest API if the variables doc existed.
=> EVG-18260 verify that hidden project can be accessed via rest API

cloud/ec2.go, globals.go, model/event/host_event.go, model/host/db.go, model/host/host.go, model/host/host_test.go, units/provisioning_create_host.go
EVG-19042
This PR provides some fixups and improvements to the host creation job so that it's more traceable.
* Add event logs when host creation fails.
* Remove some duplicate/unnecessary error logs from `SpawnHost`. These already get logged by the host creation job, so the cloud provider doesn't need to log them.
* When hosts get self-throttled (i.e. due to max host limitations), set them to a failed state rather than removing the document. This makes it easier to trace what happened to them via event logs.
* Actually pass the transaction context like you're supposed to for host creation. This isn't that related to the rest of the PR, but the host creation transaction is supposed to pass the context to the client function and it seemed like a convenient PR to just do it.
Existing tests …
=> EVG-19042: improve host creation traceability

graphql/tests/patch/results.json, rest/model/patch.go, rest/model/patch_test.go, service/patch.go, service/templates/file_diff.html
EVG-18346
Currently, HTML diff links only accept a filename parameter when templating the data. This means for commit queue merge patches that have multiple commits as part of their changes panel such as [this one](https://spruce.mongodb.com/version/637ba3350305b9100cee7294/changes?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC), if the same file is changed between both commits, they will point to the same diff, i.e. the first one matching the filename in the full diff file.
Introduced a change to track which commit we are on in the templating logic and serve the data accordingly. Also did a drive-by change fixing a bug I noticed where for multi-commit diffs the beginning of the next commit bleeds into the top of the preceding commit's changes …
=> EVG-18346 Point to different links for multi-commit merge patch diff links

agent/otel.go, config.go
[EVG-19813](https://jira.mongodb.org/browse/EVG-19813)
When the traces weren't making it to the collector I didn't see any errors in the agent logs. I think the reason is that by default the errors go to stdout and we don't capture that in the agent logs. I probably could have found them in the systemd logs, but I hadn't looked there. In any case, it makes sense to add these errors to the agent logs so they'll be together with all the rest of the agent's logging.
We could have the errors go to Splunk if we set the level to `Alert`, but I think we've usually tried to keep those messages to a minimum.
I mangled the collector endpoint in admin settings and when it tried to send traces/metrics I saw this in the admin logs
```
[evergreen.agent] 2023/05/08 16:53:47 [p=error]: encountered otel …
```
=> EVG-19813 log agent otel errors

model/project.go
EVG-18985
these fields are only being set and just checked in testing 
i put a deprecation notice on the fields just in case we need them for the github project that im working on (i don't think so though)
nothing should break
=> EVG-18985 Deprecate unused project fields

globals.go, model/container_task_queue.go, model/task/task.go, model/task_lifecycle.go, rest/route/pod_agent.go, units/crons.go, units/pod_allocator.go, units/pod_creation.go, units/pod_termination.go, units/stats_pod.go
EVG-17996
`execution_platform` needs to be a part of this log for it to be reflected in the "Container Tasks Finished by Status" dashboard.
=> EVG-17996 Add exec platform to system failed logs

graphql/generated.go, graphql/schema/types/project_settings.graphql, graphql/schema/types/repo_settings.graphql
EVG-19804
- Step 2 of changing the type of the `subscriptions` field: now that the UI is querying `projectSubscriptions` instead of `subscriptions` (https://github.com/evergreen-ci/spruce/pull/1830), update the return type of `subscriptions`
=> EVG-19804: subscriptions fields return type GeneralSubscription

model/pod/pod.go, units/task_monitor_execution_timeout.go, units/task_monitor_execution_timeout_test.go
EVG-19851
When a task fails due to heartbeat, the agent is no longer in healthy communication with the app server and the end_task endpoint (which typically clears a pod's running task) does not therefore run. This causes these pods to retain their task runtime information even after the task they were running was cleaned up due to timeout.
Added change to clear pod's running task in this case so that the pod can be picked up by the termination job.
Updated unit test.
=> EVG-19851: Clear running task of pods upon task timeout cleanup

rest/data/commit_queue.go
EVG-19265
Evergreen currently only sends a GitHub status back when commit queue enqueueing fails for specific reasons (e.g. branch protections not met), but it seems like users would just want to know whatever is the enqueue error without asking us to sift through Splunk for it. This change ensures that for all the error cases (except specifically one where we can't get the PR's information), we return some kind of error message back to the GitHub status.
Tested in staging with the commit queue sandbox (https://github.com/evergreen-ci/commit-queue-sandbox/pull/485) that it propagated the errors back to the GitHub status, and that merging still worked properly. Not really that unit testable since the GitHub API has no mocking.
N/A
=> EVG-19265: set GitHub PR status for all commit queue enqueue errors

model/host/db.go, model/host/host.go, model/host/host_test.go, rest/route/agent.go, units/host_monitoring_idle_termination_test.go, units/host_termination.go
[EVG-19091](https://jira.mongodb.org/browse/EVG-19091)
The same motivation as #6501. The solution proposed here is to expand the `IdleEphemeralGroupedByDistroID` query to include user data hosts that have contacted the app to ask for a task. This is also idle in the sense that these hosts are cleared to run tasks from this time. Also adjust `h.IdleTime()` accordingly.
Another adjustment to `h.IdleTime()` is to not count the time before the host is provisioned as idle time for the purposes of idle termination. That time still counts as `WastedComputeTime` so that logic was left as its own function. This is necessary since if we count the time since the host came online the host will have that much less time before it's considered idle. And especially now that user data hosts won't have the …
=> EVG-19091 include starting hosts in idle hosts

model/task/task.go, model/task/task_test.go
EVG-19752
We observed `OverrideDependencies` wasn't being respected for container tasks. Turns out that the `ShouldAllocateContainer` function which determines whether a task should be allocated a container would always check the `DependsOn` field even if it's supposed to be skipped.
Confirmed fix in staging, added some unit test cases.
=> EVG-19752 Include OverrideDependencies when determining container dispatchable

model/task/db.go, model/task/db_test.go, units/task_monitor_execution_timeout.go
EVG-17680
Any task that isn't dispatched by 2 x time also would've not had a heartbeat for 1 x time, so would've been caught already. 
Verified that we never find tasks with this query [in Splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20%22message%22%3D%22found%20stale%20tasks%22%20%22reason%22%3D%22no%20heartbeat%20since%20dispatch%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=-30d%40d&latest=now&workload_pool=standard_perf&sid=1684353107.894773).
(Alternatively we could change this behavior to not consider dispatched in the first query, but I don't know that we've had trouble with how this has been working already.)
Modified existing test.
=> EVG-17680 remove redundant stale query

config.go, config_auth.go, config_test.go, globals.go, go.mod, go.sum, rest/model/admin.go
EVG-19749
adds function to connect to GitHub client with GitHub app auth 
what it does: 
first, we check if we have the settings set to even use this method (app id and private key) 
then we use those things to connect to a jwt client. this client can only call certain functions, one being requesting the installation id of a repo. (this does not use up any rate limit) 
then using the installation id, we create a new client where we can actually call functions 
tested that the client functions by calling it on a test and making sure it returns values i expected it to 
token, err := settings.CreateInstallationToken(context.Background(), "evergreen-ci", "commit-queue-sandbox")
s.NoError(err)
a, _, err := GetGithubCommits(context.Background(), token, "evergreen-ci", "commit-queue-sandbox", …
=> EVG-19749 Add auth method for github apps

agent/otel.go, config.go
[EVG-19780](https://jira.mongodb.org/browse/EVG-19780)
Honeycomb combines metrics into events when the following conditions are met:
- they were received as part of the same OTLP request
- their timestamps are equivalent when truncated to the second (we truncate metric timestamps to the second for improved compaction)
- they have the same set of resource attribute keys and values
- they have the same set of data point attribute keys and values (sometimes these are also called “tags” or “labels”)
(from [here](https://docs.honeycomb.io/manage-data-volume/metrics/))
We're already covered on the first three: we send the metrics in the same request with the same timestamp and they all have the same resource. Previously we were putting a bunch of different attributes on each data point (e.g. …
=> EVG-19780 wider metrics events

rest/data/commit_queue.go
EVG-19753
Move the PR mergeability check so that it happens before checking actual commit queue enqueueing validation (i.e. user authorization and GitHub mergeable state). I don't think the project ref lookup needs the refreshed `github.PullRequest` info from `checkPRIsMergeable` since the base branch should remain the same.
Existing unit tests pass.
N/A
=> EVG-19753: check project ref for commit queue disablement before other checks

agent/otel.go, config.go
[EVG-19780](https://jira.mongodb.org/browse/EVG-19780)
https://github.com/evergreen-ci/evergreen/pull/6522 added a loop where we go over all the disk instruments and register callbacks for capturing metrics. I noticed this error output over and over again in the smoke test (e.g. [this one](https://evergreen.mongodb.com/task_log_raw/evergreen_ubuntu2004_smoke_test_host_task_cfa46091f860b5de9026272edc5e28bb3da23fcd_23_05_19_14_44_44/0?type=T#L2455)), for different device names:
```
[2023/05/19 14:32:08.026] [agent] 2023/05/19 14:32:08 [p=trace]: 2023/05/19 14:32:08 internal_logging.go:58: "msg"="failed to record" "error"="observable instrument not registered for callback" "name"="system.disk.io.loop1.read" "description"="" "unit"="By" "number"="int64"
[2023/05/19 14:32:08.026] [agent] …
```
=> EVG-19780 fix callback closure

agent/otel.go, config.go
[EVG-19356](https://jira.mongodb.org/browse/EVG-19356)
If we returned [here](https://github.com/evergreen-ci/evergreen/blob/7b9bc9ae82961b033d1de8422abac9b896b673ec/agent/otel.go#L55-L58) because the endpoint wasn't set (such is the case in the smoke tests because they use [this config](https://github.com/evergreen-ci/evergreen/blob/f81ded5bceb8bf71c37b026aa259ba7417b6fd27/testdata/smoke_config.yml)) we should also skip setting up metrics. It seems like a good idea to make sure the connection is set up anyways.
It will be telling if we see [this line](https://evergreen.mongodb.com/task_log_raw/evergreen_ubuntu2004_smoke_test_host_task_2f5ac478fb793fdd72a90174ecab8f56cbcdaf58_23_05_18_20_18_00/0?type=T#L1911) in the smoke logs.
> doing meter provider: failed to upload metrics: context …
=> EVG-19356 return if there's no connection

docs/API/REST-V2-Usage.md, docs/CLI.md, docs/Hosts/Spawn-Hosts.md
Document the maximum amount of time you can extend an expirable spawn host's duration and mention that you can get notifications for expiring spawn hosts.
=> EVG-19889: document spawn host expiration

docs/Project-Configuration/Project-and-Distro-Settings.md
Making a doc to link to for the newsletter.
Not adding a screenshot bc this should change in EVG-16363 but will make a note in that ticket to add it.
preview:
=> docs: add metadata links

gqlgen.yml, graphql/generated.go, graphql/models_gen.go, graphql/schema/types/project.graphql, graphql/schema/types/project_settings.graphql, graphql/tests/mutation/saveProjectSettingsForSection/queries/ui_section.graphql, graphql/tests/mutation/saveProjectSettingsForSection/queries/views_and_filters_section.graphql, graphql/tests/mutation/saveProjectSettingsForSection/results.json, graphql/tests/projectSettings/data.json, graphql/tests/projectSettings/queries/project-settings-project.graphql, graphql/tests/projectSettings/results.json, model/project_ref.go, model/project_ref_test.go
EVG-19877, EVG-19882
Allow saving Parsley filters through the `SaveProjectSettingsForSection` mutation. Validation for Parsley filters will be added in the next ticket.
- GraphQL and unit tests
=> EVG-19877, EVG-19882: Enable saving Parsley filters via GraphQL

graphql/generated.go, graphql/schema/types/user.graphql
EVG-18330 (required by https://github.com/evergreen-ci/spruce/pull/1834)
- Expose the subscription IDs of the a user's configurable global subscriptions via GraphQL. These are [used](https://github.com/evergreen-ci/evergreen/blob/e455d35619878389ac71003b8c4f97b436e71c2f/public/static/js/notifications.js#L28-L39) to distinguish one-off subscriptions from global subscriptions.
=> EVG-18330: Expose user's global subscription ID fields

go.mod, self-tests.yml
This is pretty straightforward, but we need to update ubuntu arm64 to version 20.04 so that we can have the new Go version.
EVG-19967
Updates to Go 1.20
Mainly depending on compilation and unit tests for these changes. 
N/A
=> EVG-19967: Update to Go 1.20.

rest/model/task.go, rest/model/task_test.go
EVG-19281
Fix an issue where the log links were using the archived task ID (i.e. with the `_<execution_num>` appended) instead of the original task ID.
Added unit test and checked in staging that the log URLs worked for an old task execution.
N/A
=> EVG-19281: fix broken log links for archived task executions

agent/agent.go, agent/otel.go, config.go, environment.go, go.mod, go.sum
[EVG-19188](https://jira.mongodb.org/browse/EVG-19188)
https://github.com/mongodb/amboy/commit/082f8fd5857e799b8f4665c389c009965f71c68b creates a trace for each amboy job. Update amboy to use it in evergreen. Also update utility to get the `attributeSpanProcessor` from https://github.com/evergreen-ci/utility/commit/4d91d64f59fb653893f0f0b0f301971ce050b389, and use it for the app and agent's `TracerProvider`s.
The spans won't be too interesting yet unless we have a job that happens to pass its context to its db calls. But it'll let us do stuff like [EVG-19918](https://jira.mongodb.org/browse/EVG-19918).
On staging this created traces like [this one](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/trace/fC9Kgznzk3Y) for the `patch-intent-processor` job.
=> EVG-19188 instrument amboy jobs

docs/Project-Configuration/Project-Configuration-Files.md
https://mongodb.slack.com/archives/G64DEE8DA/p1685027879808909
Validated: https://spruce.mongodb.com/task/evergreen_ubuntu2004_container_test_expansions_patch_d713dadd127865fa88193c33eed21b16f8b2eae3_646f808c0305b9ddaa5d8fb5_23_05_25_15_36_47/logs?execution=0
Chose HelloWorld over helloworld
=> docs: add that expansions are case-sensitive

self-tests.yml
[EVG-18898](https://jira.mongodb.org/browse/EVG-18898)
In https://github.com/evergreen-ci/evergreen/pull/6542 we missed moving lint to ubuntu2204.
Hopefully it'll pass in this PR's patch.
=> EVG-18898 move lint to ubuntu22.04

graphql/generated.go, graphql/schema/types/repo_ref.graphql, graphql/tests/mutation/saveRepoSettingsForSection/queries/general_section.graphql, model/project_ref.go, rest/data/project_settings.go, rest/data/project_settings_test.go
EVG-19842
- Remove `branch` field from RepoRef and RepoRefInput. This field is removed from the front end in https://github.com/evergreen-ci/spruce/pull/1845.
- Don't set the repo's branch field when defaulting a page to the repo.
- Update unit tests
N/A
=> EVG-19842: Remove branch for repos

config_db.go, config_serviceflags.go, rest/model/admin.go, service/project.go, service/templates/admin.html, testutil/config.go
EVG-19774
Added Spruce redirect functionality for the legacy project page, along with an admin flag to turn it on. The redirect will not be active until we toggle it.
Tested locally.
Has been documented via email and banner that the legacy project page will be deprecated in 3 weeks (June 13).
=> EVG-19774 Add legacy project page redirect logic

model/event/project_event.go, model/project_event.go, model/project_ref.go, model/project_ref_test.go
EVG-19702
The [repo](https://spruce.mongodb.com/project/634d56d3850e610cacfe7e0b/settings/event-log) in question from the ticket has no event logs because it was created by "attach to repo" being clicked for an existing project, copying over all settings and variables to the repo. By the time the button was clicked, the project had undergone changes and had event logs, but the repo was initialized with no event logs.
This is a bit confusing, because in the DB there is nothing acknowledging the existence of the created repo at all, so I added two changes to allow us to keep a better paper trail of what's happening:
- Logging a `PROJECT_ADDED` event when a repo is newly created from the "attach to repo" command
- Created two new events to log for a project, for when it attaches to / …
=> EVG-19702 Log event when repo is created, add events for repo attachments

rest/data/commit_queue.go
EVG-19906
removing logs because there was never an instance where the automatic refresh trigger from the commit queue changed the status of a pr from block to unblocked
=> EVG-19906 Remove debug logging for commit queue refresh

docs/Project-Configuration/Best-Practices.md, docs/Project-Configuration/Project-Configuration-Files.md, docs/Project-Configuration/Project-and-Distro-Settings.md
EVG-19994
Apparently, links in Pine to headers that contain a period need to omit the period. I only confirmed this by clicking a bunch of links in the docs.
There's also a bug where the timeout.update link is not being generated properly by Docusaurus despite being written the same way as all the other (working) links, which is being investigated in [RDPL-352](https://jira.mongodb.org/browse/RDPL-352).
=> EVG-19994: fix broken links for project commands

model/project_ref.go, model/project_ref_test.go, model/project_vars_test.go, repotracker/github_poller.go, rest/data/project.go, rest/data/project_test.go, rest/route/middleware_test.go, rest/route/project.go, rest/route/project_test.go, service/project.go
EVG-19825
* If a project is not already explicitly set to public/private, set it to private during all upserts.
* Consolidate `Update()` into `Upsert()` since they're pretty much the same thing.
* Reduce usage of upsert in places where the logic can do single field updates. I couldn't remove it from some places though (such as hiding a project), because they relied on doing whole-document updates.
N/A
=> EVG-19825: make project upsert safer

agent/status.go, config.go
EVG-20010
Remove the route that terminates the agent within the host. From the original context, it seems like it was introduced in EVG-1888 so that there would be a way to mass terminate agents across hosts. I don't really see a good reason why we would need to do this as opposed to just terminate hosts (and I believe nobody's ever needed such functionality in all the years of firefighting/outages), so it seems best to just remove.
I also don't think users would ever have a good reason to intentionally terminate the agent, so it seems safe to remove if we're not using it.
N/A
N/A
=> EVG-20010: remove agent self-termination route

config.go, operations/agent.go
EVG-20009
The agent closer currently runs in a defer, but deferred functions do not run if the program exits (e.g. via `os.Exit`). I just manually called it when the goroutine exits the process.
Not really a testable condition since it's a signal catcher, but I verified in a Go playground that it behaves as expected.
N/A
=> EVG-20009: close agent when signalled

rest/data/project.go, rest/route/project.go, rest/route/project_test.go
[EVG-20030](https://jira.mongodb.org/browse/EVG-20030)
This removes a temporary warning and conditional, now that the project is ready for it.
=> EVG-20030 Remove Secrets Manager warnings

docs/Project-Configuration/Project-Configuration-Files.md
A user asked about using an expansion that contains another expansion. It seems like expansions are only one-level deep, so I updated the docs.
=> docs: mention no recursive expansions

model/task/db.go, model/task/task.go, model/task/task_test.go, model/task_lifecycle.go
[EVG-19998](https://jira.mongodb.org/browse/EVG-19998)
The [schedulableHostTasksQuery](https://github.com/evergreen-ci/evergreen/blob/fbbbd42cd673b24b9e12e9eb810674a7c389c1b2/model/task/db.go#L708) is inefficient if there are many documents that have a mix of blocked and unblocked dependencies. The reason for this is that we filter out tasks with blocked dependencies [here](https://github.com/evergreen-ci/evergreen/blob/fbbbd42cd673b24b9e12e9eb810674a7c389c1b2/model/task/db.go#L720), but the index can only be used to filter out tasks that have **all** their dependencies blocked. For tasks that have some unblocked dependencies we need to fetch the actual documents and filter the array[^1]. Some distros have many (~200k) tasks like this, and potentially long dependency arrays to look …
=> EVG-19998 cache unattainable task status

self-tests.yml
[EVG-18898](https://jira.mongodb.org/browse/EVG-18898)
Given the issues with js-test aren't related to the upgrade to ubuntu22.04 it shouldn't need to be a variant unto itself.
=> EVG-18898 js-test to ubuntu-2204

graphql/patch_resolver.go, graphql/util.go, model/task/task.go, model/task/task_test.go, trigger/patch.go
EVG-18670
This standardizes how the time taken is formatted to avoid a very large integer in notifications for cases where there is no start time or an end time. 
Additional unit test plus existing tests
=> EVG-18670 Standardize time taken formatting between patch finish notification and Spruce UI

model/task/db.go, model/task/db_test.go, model/task_lifecycle.go, model/task_lifecycle_test.go
EVG-19648
[This ticket](https://spruce.mongodb.com/task/mms_v20230412_deploy_gate_PACKAGE_CLOUD_DEPLOY_GATE_8d625c0f9fdc195431b5824995467764d6149181_23_04_17_17_30_16/logs?execution=0&logtype=event&sortBy=STATUS&sortDir=ASC) was unscheduled because a dependent task was deactivated because of [a previous success](https://spruce.mongodb.com/task/mms_v20230412_code_health_CHECK_PROM_ALERT_fe010402187c7649a2bfc7e7c2c11080854229ab_23_04_17_18_18_19/logs?execution=0). 
This PR (1) checks dependencies, and (2) removes legacy logic to include display task execution tasks (SetActiveState handles that). 
Verified existing tests pass, and added a test to verify that a task with an active dependent task wouldn't be deactivated.
=> EVG-19648 avoid deactivating previous tasks if they're depended on

docs/API/REST-V2-Usage.md
Changes:
- Fix the endpoint for getting a patch by its patch_id.
- Document the base URL explicitly.
=> docs: Update doc for REST v2 API

.github/dependabot.yml
EVG-17174
This is pretty much the same configuration as https://github.com/mongodb/jasper/pull/260, but for Evergreen.
This enables Dependabot automatic upgrades for Go modules. Dependabot will periodically check all dependencies in `go.mod` for newer stable versions (it doesn't upgrade unversioned repos like our evergreen-ci ones) and open a PR to bump them. This initial merge will also trigger Dependabot to do an immediate check for new dependency versions and I suspect many of our dependencies are out of date, so merging this may trigger a lot of Dependabot PRs to be opened.
My proposed workflow is that once every quarter or so, someone is assigned to review the open Dependabot PRs; if they pass, they can just be merged. If not, we'll have to open tickets and triage when to fix them to …
=> EVG-17174: use Dependabot for automated dependency upgrades

agent/command/shell_test.go, scripts/verify-agent-version-update.sh
EVG-18916
This was flaking out because the `shell.exec` command didn't have an explicit shell defined, and the shell is only defaulted if you call `ParseParams` (which this test didn't). The test would occasionally flake out due to a race between the command running (with invalid input due to the lack of shell) and the context timing out (which is detected in a separate goroutine).
Ran the test in a patch 100 times before and after my fix. Before the fix, it's flaky. After the fix, no flakiness.
N/A
=> EVG-18916: fix flaky shell.exec test

graphql/schema/types/project.graphql, graphql/tests/mutation/saveProjectSettingsForSection/queries/views_and_filters_section.graphql, graphql/tests/mutation/saveProjectSettingsForSection/results.json, graphql/tests/projectSettings/results.json, model/project_ref.go
EVG-19891
- I introduced a mismatch in string values in https://github.com/evergreen-ci/evergreen/pull/6540: the GraphQL enum uses an uppercase string and the golang const uses lowercase. We should use uppercase strings in the database to align with GraphQL enum conventions and [gqlgen patterns](https://gqlgen.com/reference/name-collision/). I spoke with @khelif96 and we think it makes most sense to stick with enums here rather than reverting to a string (and going forward, we can adopt this pattern in other places where we've previously returned `String!` and added enums on the front end).
- Once this ticket is deployed, 6 project_ref documents in the database will need to be updated to convert `failed` to `FAILED`:
```
db.project_ref.updateMany({project_health_view: "failed"}, {$set: …
```
=> EVG-19891: Update project health view string value

rest/route/github.go, rest/route/github_test.go, rest/route/middleware.go, rest/route/service.go
EVG-18002
This adds a middleware that makes sure that the github payload is valid. While this adds some duplication, middleware is still the right place to handle auth, and parsing the body shouldn't be expensive. 
Testing by creating a PR on staging and ensuring that we can still receive webhooks.
=> EVG-18002 Add a middleware for Github payload validation 

model/patch_lifecycle.go
EVG-14117
I believe there's currently two bugs, one of which I addressed here, which is that commit queue merges aren't being marked finished because they're marked essential (`evergreen.IsGithubRequester` includes the merge requester). Unfortunately, the actual bug was re-opened before #6521 was committed/deployed, so this is not the primary cause of the issue. There will be a follow-up PR to fix the other bug (which is a race).
It seemed like a small enough change to just do it by inspection.
N/A
=> EVG-14117: do not make commit queue tasks essential

rest/data/host_create.go, rest/data/host_create_test.go
EVG-19867
Functions that include `host.create` that pass in variables have those variables get ignored when `Also start any hosts this task started (if applicable)` is set in the UI and `CreateHostsFromTask` is run. If the distro value is set there, it will cause the spawn host command to fail, saying that no distro was specified.
The git diff is treating it weirdly but `WithCommandVars` is the new test case. I also refactored some of the looping logic at the beginning of the function to be more succinct.
Test-driven approach, wrote initially failing tests and added change to fix them.
n/a
=> EVG-19867 Allow host.create to use function vars

model/task/task.go, trigger/task.go
EVG-19296 
In this ticket, Jeff mentioned that some system failures still aren't being logged. Looking for example at [this task](https://spruce.mongodb.com/task/mongodb_mongo_master_enterprise_rhel_80_64_bit_dynamic_all_feature_flags_required_display_sharding_clustered_collections_e8b6fe12d6a962e537ef2503a22789936f507a3f_23_04_06_05_57_13/execution-tasks?execution=9&sorts=STATUS%3AASC), the [notification is nil for the subscription](https://mongodb.splunkcloud.com/en-US/app/search/search?earliest=1680753600&latest=1680926400&q=search%20index%3Devergreen%20%22642f064a562343b05d90779d%22%7C%20spath%20subscription_id%20%7C%20search%20subscription_id%3D61bcf367c9ec443c5b7e9fd1&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&display.page.search.tab=events&d …
=> EVG-19296 correctly consider system unresponsive tasks for notifications

model/host/db.go, model/host/host.go, model/host/host_test.go, units/crons.go, units/host_monitoring_idle_termination_test.go
[EVG-20112](https://jira.mongodb.org/browse/EVG-20112)
Upgrading the db to 6.0 caused this query to stop using the expected index and the query was getting stuck. It seems that the sort on `creation_time` was causing it to prefer the `creation_time_1` index instead of using the `started_by_1_status_1`.
The explain plan is much better now. I'll take it for a spin in staging to make sure it works.
=> EVG-20112 hint for IdleEphemeralGroupedByDistroID

graphql/generated.go, graphql/schema/types/project.graphql, graphql/schema/types/project_settings.graphql
EVG-17141
- Expose fields via GraphQL. These fields will be made required (`!`) after the front end is updated to fetch/save `description`.
=> EVG-17141: Expose project alias description field

cmd/load-smoke-data/load-smoke-data.go, model/host/db.go, model/host/host.go, model/host/host_test.go, units/host_monitoring_idle_termination_test.go
[EVG-20112](https://jira.mongodb.org/browse/EVG-20112)
#6637 added a hint for the `IdleEphemeralGroupedByDistroID` query but missed a test and the smoke tests. This PR adds the index for that test and for the smoke test.
Ostensibly test-units will pass now.
=> EVG-20112 build the host index in tests

model/project_ref.go, model/project_ref_test.go
EVG-17957
A pod is supposed to be able to have at most one pod secret, but I was able to set two pod secrets for the same project without an error because the validation we do for secrets to update only checks the new list of secrets and doesn't first check if there are existing pod secrets.
Wrote initially failing test, and confirmed it now passes
=> EVG-17957 Check for multiple pod secrets across new and original lists

go.mod, go.sum
EVG-19926
Update grip to get the new gopsutil version.
I'd probably defer this to the next time we upgrade grip, but it seems like it'd be good to have an update with just this.
I'll merge this once tests pass.
=> EVG-19926 upgrade grip

units/commit_queue.go
EVG-20168
Bynn and I have discussed this ticket a ton; overall we think that patches are being marked as "finished" too early because we aren't properly handling AllTasksBlocked for merge tasks. For now, adjusting how the unstick job behaves here should alleviate this.
=> EVG-20168 use merge task to determine if patch is stuck

model/task/db.go, model/task/task.go, model/task/task_test.go
[EVG-19998](https://jira.mongodb.org/browse/EVG-19998)
#6570 added the `UnattainableDependency` field to a task which caches whether the task is blocked on a dependency. The changes were deployed on 6/7. After a week any tasks that have not run will have been deactivated by the scheduler ([here](https://github.com/evergreen-ci/evergreen/blob/68ed1ad907490e58d66203bc619f19123dc50655/model/task/task.go#L1248-L1276)). So by Friday all schedulable tasks will have this field set and we're all clear to use the new field in the query.
I'll make sure this doesn't get deployed until Monday. We'll need to build the index on prod before it's deployed.
I built the index in staging and the query used the index as expected. When the code was deployed to staging the scheduler picked up my task and …
=> EVG-19998 use UnattainableDependency field for the schedulable tasks query

agent/agent.go, config.go
EVG-20135
For agents already running inside containers, the Docker daemon is not available because Docker is itself the process running the container. Therefore, the container agent can simply skip any Docker-related cleanup.
This isn't an easily testable condition because the Docker daemon cannot be easily tested/mocked. The conditional seems simple and sound enough that it seems like testing it wouldn't be worth the effort.
N/A
=> EVG-20135: skip Docker cleanup for agents running in containers

agent/agent.go, config.go
EVG-20140
This deferred context cancellation is not needed because there's already a deferred cancel [above it](https://github.com/evergreen-ci/evergreen/blob/59d70cb3f4bfa05574ebbe50246fcf9e6fd51bf4/agent/agent.go#L518).
N/A
N/A
=> EVG-20140: remove duplicate deferred context cancellation

config_test/evg_settings.yml, docs/decisions/2023-06-05_github_merge_queue.md, globals.go, model/patch/github_merge.go, model/patch/github_merge_test.go, model/patch/patch.go, model/patch_lifecycle.go, model/patch_lifecycle_test.go, model/version.go, rest/data/patch_intent.go, rest/route/github.go, service/api_patch.go, testutil/testing.go, thirdparty/github.go, units/patch_intent.go, units/patch_intent_test.go
EVG-20073
This adds support to the patch-intent-processor amboy job for GitHub merge queue
items.
This tests the new requester type by running similar integration tests for the
patch-intent-processor job as currently exist for other requester types.
Light edits to the ADR. There are not user-facing changes yet, so I have not
added public docs.
=> EVG-20073 Create versions for GitHub merge queue

docs/Project-Configuration/Project-Configuration-Files.md
Keeping this pretty light since the tags section also goes through examples, but want to make sure they're linked.
=> docs: add some info about tags to dependencies

model/task_lifecycle.go, model/task_lifecycle_test.go, units/task_monitor_execution_timeout_test.go
EVG-20168
Build was setting all_tasks_blocked but never unsetting it when the dependent tasks were restarted 
That was causing patches to mistakenly believe they were complete and unschedule tasks 
created a patch on staging and saw that the build now updates when you restart tasks that are dependent 
even if they were previously blocked 
https://spruce-staging.corp.mongodb.com/version/648cae22b2373620e2ba9d00/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> EVG-20168 Update dependent build and version after restarting a task

rest/route/pod_agent.go, rest/route/pod_agent_test.go
EVG-20202
Container tasks are exiting with the error `Incorrect Usage. flag provided but not defined: -output`, the flag needs to be renamed.
Downloaded the CLI locally and tested with the new command that `provisioning_script` and error was gone.
=> EVG-20202 Rename pod provisioning script output flag name

globals.go, scheduler/planner.go, scheduler/planner_test.go
EVG-20079
This takes advantage of existing code to give commit queue tasks higher
priority. It treats Evergreen commit queue tasks and GitHub merge queue tasks identically.
I added a unit test to ensure that adding a GitHub merge queue task yielded the
same priority as adding an Evergreen commit queue task.
=> EVG-20079 Support GitHub merge queue in scheduler

docs/API/REST-V2-Usage.md
A user pointed out there's a typo in the docs.
=> docs: fix REST route for getting tasks in a mainline commit

model/host/hostutil.go
EVG-20138
#6664 left a small TODO for after agent versions had rolled over to actually use the newly-introduced CLI flag. Now that agents have rolled over to the newer version (i.e. the one that has the `--log_output` option), we can explicitly set the log output option.
I verified with [the recent tasks endpoint](https://evergreen.mongodb.com/rest/v2/status/recent_tasks?minutes=1440&by_agent_version=true) that agents have rolled over to the newer version, so setting this flag is safe.
N/A
=> EVG-20138: explicitly set logging output

config.go, rest/route/github.go
EVG-20204
got webhooks to work through github app and not the one on the repo 
had to remove an error from install tokens because it's only installed on commit queue and not evergreen repo but this is temporary 
using the same github webhook secret as the one we were already using for the current webhook
staging
1. comment on pr, triggered new patch, retry etc 
2. pushing commit triggers repo tracker 
3. statuses are updated correctly
=> EVG-20204 Temporarily remove token error to support multiple repos

globals.go, graphql/directive_test.go, graphql/generated.go, graphql/models_gen.go, graphql/resolver.go, graphql/schema/directives.graphql, graphql/schema/types/distro.graphql
EVG-19932
- Add `@requireDistroAccess(DistroSettingsAccess)` directive to gate future distro resolvers.
- The technical design identified multiple directives that would be added for various permissions, but I remembered that we can use an argument to specify the permission level and use just one directive.
- I also noticed that we distinguish between create and admin permissions for distros, so I added a fourth permission level. I'll update the project tickets to reflect these changes.
- Add unit tests for various permission levels with the directive
N/A
=> EVG-19932: Add distro permissions directive

model/project.go, model/project_test.go
EVG-20072
Stakeholders explained that it would be more useful to have a unified expansion,
since they plan to have the same behavior regardless of which commit queue the
version runs from, since from a stakeholder perspective the commit queues are
equivalent. Having an additional expansion for the GitHub merge queue is not useful.
This is unit tested in the same way as the additional expansion, but now it
tests for only a single expansion.
=> EVG-20072 Unify merge queue expansions

agent/agent.go, agent/agent_test.go, agent/command.go, agent/command/git.go, agent/command/git_patch_test.go, agent/command/git_test.go, agent/command/interface.go, agent/command/keyval_test.go, agent/command/registry.go, agent/command/registry_test.go, agent/command/results_gotest_test.go, agent/command/results_native_test.go, agent/command/results_xunit_test.go, agent/command_test.go, agent/task.go, config.go, validator/project_validator.go
EVG-20139
EVG-20141
In the UI: `'shell.exec' in "my-func-name" (#5) in "pre"`
Which has the format: `'COMMAND_NAME' in "FUNC_NAME" (#COMMAND_NUMBER) in "BLOCK_NAME"`
In the task logs: `'shell.exec' in function 'my-func-name' (step 5.12 of 8)`
Which has the format: `'COMMAND_NAME' in function 'FUNC_NAME' (step COMMAND_NUMBER.FUNC_SUBCOMMAND_NUM of TOTAL_COMMANDS_IN_BLOCK)`
Some problems with the current command format:
* The "failing command" and the task logs represent the failing command in different formats, making it difficult to deduce which task log lines correspond to the actual failing command.
* The UI display name doesn't mention what the context of the failing command is, so it's unclear if the func name is a function or if it's the command block section in which it failed.
* …
=> EVG-20139, EVG-20141: standardize command display names and rename some functions

agent/command/git.go, config.go, model/patch/patch.go, rest/route/agent.go, rest/route/agent_test.go, thirdparty/github.go
EVG-20161
This is a rework of the idea from #6672 
When the base branch has new commits that are not in the PR branch, Github can create a new merge commit for the merging of the PR. This means that the `merge_commit_sha` would be different from the last commit in the PR branch.
This is relevant for long commit queues where items get their `merge_commit_sha` cached on their patch doc upon queueing, but tasks won't get started until changes from the batch of size N ahead of them get merged into the base branch, at which point `merge_commit_sha` will have changed. This means that the [field](https://gist.github.com/hadjri/f3b3da7de0431c03b71a66abf378ac08#file-github-go-L100) we store on the patch to save the commit sha is subject to become invalid, and since it's a static & unchanging field …
=> EVG-20161 Try patch doc's cached merge commit SHA upon the first fetch attempt

docs/Project-Configuration/Project-Commands.md
EVG-19661
Made sure that the installation token was accessible as an expansion
=> DOCS: Add github_app_token to one of the expansions that cannot be written

model/project_parser.go
EVG-20306
* Mention the build variant name when there are multiple conflicting tasks defined under a build variant.
* Change formatting so it includes the field names in the error message when the deep equality check fails.
=> EVG-20306: improve error message for conflicting definitions in parser project

operations/service_deploy_smoke_utils.go, scripts/agent.yml
EVG-20314
The smoke test is failing spuriously because it's checking for string output that is too ambiguous/short (i.e. someone made a commit that coincidentally included the word "first" in it, and the smoke test is wrongly thinking that's the relevant output of the smoke test). I made the strings much more unique so there's a much lower chance that the test coincidentally fails because it happened to output a conflicting string.
I just changed some strings, and the smoke test can't pass because it's using the `agent.yml` committed to main. This will be substantially reworked in EVG-19590, but for now, there's no way to easily get it to pass. It seems easier to just commit this and check the (currently red) smoke test turns green.
N/A
=> EVG-20314: improve smoke test string checks

operations/service_deploy_smoke_utils.go, scripts/agent.yml
EVG-20314
Revert the smoke test configuration and smoke test for the container task back to what it was before. The reason it doesn't work with the change in #6697 is because if you change the container task configuration in `agent.yml`, you must also manually change `testdata/smoke/parser_projects.json` to reflect the modified YAML. I didn't think it was worth it to try fixing the container task's smoke test data, so I'm just gonna revert it back to how it was before and leave it to EVG-17658 to improve it.
I also fixed an issue in the `smoke-test-host-task` where the expected string is missing "the".
I read the smoke test logs for `smoke-test-container-task` and reasoned about how it's supposed to work.
N/A
=> EVG-20314: revert smoke test for container back to its original configuration

model/patch_lifecycle.go, model/patch_lifecycle_test.go
EVG-20304
The event doesn't provide a list of commits from the virtual branch, so there isn't something to put in this field.
Edited test.
=> EVG-20304 Don't include titles in GitHub merge queue description

agent/agent.go, apimodels/agent_models.go, config.go, graphql/generated.go, graphql/schema/types/task.graphql, rest/model/task.go
[EVG-19743](https://jira.mongodb.org/browse/EVG-19743)
We'd like to display a link to a task's trace on the task page. This PR captures the trace ID when it's generated and sends it back to the app in `TaskEndDetails`.
Ran a task on staging and [its trace id](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/trace/oYyGctRbicg?fields[]=c_name&span=44e2f925a4f73544) was persisted to the task document.
=> EVG-19743 capture trace ID for a task

model/pod/pod.go, model/pod/pod_test.go, model/project_ref.go, units/patch_intent_test.go, units/pod_allocator.go, validator/project_validator.go, validator/project_validator_test.go
EVG-20097
We have been modifying this field frequently and will probably continue to do so, changing so that we dynamically fetch the allowed images and don't require a prod bounce for the changes to take effect.
Ran a container task in staging based off of a new image and the task went through and succeeded without error.
=> EVG-20097 Use non-cached admin settings for containers validation

model/patch_lifecycle.go, model/patch_lifecycle_test.go
EVG-20374
users were able to create an empty patch by passing in a task that didnt exist 
this forbids that
=> EVG-20374 Error when patches finalize with no tasks

globals.go, model/task/db.go
EVG-20395
Logs the aggregation name in the trace span to make it easier to identify certain expensive db queries.
Example honeycomb trace.
https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen?query=%7B%22time_range%22%3A600%2C%22granularity%22%3A0%2C%22breakdowns%22%3A%5B%5D%2C%22calculations%22%3A%5B%7B%22op%22%3A%22COUNT%22%7D%2C%7B%22op%22%3A%22AVG%22%2C%22column%22%3A%22duration_ms%22%7D%5D%2C%22filters%22%3A%5B%7B%22column%22%3A%22service.name%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22evergreen%22%7D%2C%7B%22column%22%3A%22db.aggregationName%22%2C%22op%22%3A%22%3D%22%2C%22value%22%3A%22GetTasksByVersion%22%7D%5D%2C%22filter_combination%22%3A%22AND%22%2C%22orders%22%3A%5B%5D%2C%22havings%22%3A%5B%5D%2C%22limit%22%3A1000%7D
=> EVG-20395 add aggregation name to trace spans

agent/agent.go, agent/agent_test.go, agent/task.go, config.go
EVG-20279
`killProcs` runs in various different contexts, and it's not really that clear when/why it runs just from agent logs. I made it a little easier to trace why `killProcs` is running in the agent logs.
* Log reason why `killProcs` is called in agent logs.
* Drive-by cleanup agent tests a tiny bit.
* Drive-by rename a context since it didn't seem worth it to open a ticket just for it.
Didn't seem worth it to unit test just an execution log addition, especially because the existing tests can't easily read from the agent logs. I tested in staging that the new `killProcs` log appears as expected.
N/A
=> EVG-20279: log why killProcs runs

service/templates/admin.html
[EVG-19147](https://jira.mongodb.org/browse/EVG-19147)
https://github.com/evergreen-ci/evergreen/pull/6742 removed the Alerts section from the admin page but didn't remove the link from the sidebar.
=> EVG-19147 remove Alerts link from admin page

agent/otel.go, config.go, environment.go
[EVG-20419](https://jira.mongodb.org/browse/EVG-20419)
If the client fails to upload spans it will log the error with the otel error handler. By default this just goes to stdout which ends up in the service logs on the host. It would make things a lot easier if they went with the rest of our logging to Splunk.
We already do this for the agent [here](https://github.com/evergreen-ci/evergreen/blob/0b38c0c784757ca57aa54a8ced532d02c49435db/agent/otel.go#L89-L91).
=> EVG-20419 log otel errors

docs/Project-Configuration/Project-and-Distro-Settings.md, graphql/generated.go, graphql/schema/types/project.graphql, graphql/tests/projectSettings/data.json, graphql/tests/projectSettings/queries/project-settings-project.graphql, graphql/tests/projectSettings/results.json, graphql/tests/version/externalLinksForMetadata/data.json, graphql/tests/version/externalLinksForMetadata/queries/external_links_unmatching_requester.graphql, graphql/tests/version/externalLinksForMetadata/results.json, graphql/version_resolver.go, model/project_ref.go, rest/model/project.go
EVG-16363
The purpose of this ticket is to allow users to specify where metadata links will show up. The `requesters` field is going to be used for that specification (so you can choose to show external links on commits, patches, both, etc).
Note: Following this ticket, I will need to update all existing external links definitions to have requesters of `["patch_request", "github_pull_request", "merge_test"]`. This is because we currently show external links for patches only (i.e. anything that matches [`IsPatchRequester`](https://github.com/evergreen-ci/evergreen/blob/20a22068d7cd254c667ca8d7c3d51982d59f3c4b/globals.go#L901)).
- Added GraphQL tests
- Updated Metadata Links section
=> EVG-16363: Add requesters field to external links

.github/dependabot.yml
EVG-20358
Since we're absorbing Dependabot into the weekly support rotation, I tuned it so that it no longer pings evg-app (it's on the person on support to review the Dependabot PRs) and reduce the number of open PRs to limit the amount that a single person on rotation has to review. Eventually, we'll get to a point where there's very few Dependabot PRs, but for now, our dependencies are very outdated.
=> EVG-20358: update Dependabot for support rotation

rest/data/commit_queue.go, rest/route/github.go, rest/route/github_test.go
EVG-20434
This executes the correct merge queue behavior (Evergreen or GitHub) based on
the field in the project ref.
I added a unit test for the behavior.
TBD in a later ticket.
=> EVG-20434 Toggle merge queue with project ref

environment.go
[EVG-20419](https://jira.mongodb.org/browse/EVG-20419)
One of the reasons spans are getting dropped between the application and the collector is that [the default](https://github.com/open-telemetry/opentelemetry-go/blob/fdfc821bac8357ec1eac271c50454606c318d8de/sdk/trace/span_limits.go#L20-L22) is to allow attributes to be unlimited in length. The `db.statement` attribute in particular is often long ([Honeycomb](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/nCEPHXq5ogr)). Interestingly, the [MAX](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/6xVMS9dmqTD) is capped at around 65k, which might be the cause/result of the "event exceeds max event size of 100000 bytes, API will not accept this event" errors on …
=> EVG-20419 impose max length on string attributes

rest/data/distro.go, rest/data/distro_test.go
Fixes collision introduced in #6764 for EVG-19937
- #6732 added context across distro DB methods. Since #6764 did not have the latest changes, it lacked the context argument for these methods
=> EVG-19937: Add context to distro db methods

agent/agent.go, agent/agent_test.go, agent/background.go, agent/command_test.go, agent/internal/client/mock.go, config.go, docs/Project-Configuration/Project-Configuration-Files.md
EVG-20286
If the task gets an abort signal from the heartbeat, the agent is still expected to run the post task, so it should still heartbeat back to the app server to indicate that the task is alive. The heartbeat will continue to receive the abort message from the app server on later heartbeats, but the agent only needs to process the abort message once.
* Continue attempting to heartbeat after a task receives the abort signal.
* Drive-by clean up some existing agent tests.
Added unit tests and tested in staging to verify that a long sleep in post continued running after the heartbeat timeout ([example](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2204_test_util_patch_b6222da4640b0199bb11a37c93f6b8192ff473dc_64aef970b2373697b2ba2c69_23_07_12_19_05_21/logs?execution=1&logtype=ag …
=> EVG-20286: continue heartbeating after abort

graphql/tests/mutation/attachProjectToRepo/results.json, graphql/tests/mutation/defaultSectionToRepo/results.json, graphql/tests/mutation/detachProjectFromRepo/results.json, graphql/util.go
EVG-20459
The RequireProjectAccess would take in 3 different argument types and look up the project id in only one of the cases. This could be problematic due to the differences between how ids vs identifiers are treated as seen in this thread: https://mongodb.slack.com/archives/C0V896UV8/p1689352076642169
At some point, we should consolidate the argument types for these mutations so that they are consistent in the argument naming.
=> EVG-20459 Lookup project id for RequireProjectAccess directive variables

config.go, model/patch_lifecycle.go, units/patch_intent.go
EVG-20456
GitHub app was failing because owner/repo field wasn't set for all types of patches 
this was caught in a unit test when i return an error that is currently being suppressed by fallback
the unit test is correctly passing now
=> EVG-20456 Add owner/repo field to all patches 

model/manifest/manifest.go, rest/data/manifest.go, rest/data/manifest_test.go, rest/route/task_manifest.go
EVG-19971
Instead of returning 500 when the task has no manifest, return 404. I also moved the function into the REST data package to be more consistent with the other data connector functions.
Our API already generally returns 404 for REST requests for nonexistent resources, so I didn't think it was worth documenting the status codes just for this one route.
=> EVG-19971: return 404 when task has no manifest

model/task/db.go, model/task/db_test.go, model/task/task.go, model/task/task_test.go, model/task_lifecycle.go
#6703 fixed the UnattainableDependency field. The fix was incorrect for certain updates because they weren't using an [aggregation-pipeline-style update](https://www.mongodb.com/docs/manual/tutorial/update-documents-with-aggregation-pipeline/). Instead, the field was getting set to the literal document:
```
{ '$anyElementTrue': '$depends_on.unattainable' },
```
When I checked in prod it looked like there were ~1k schedulable tasks that matched this description. We won't be able to do [EVG-19998](https://jira.mongodb.org/browse/EVG-19998) before they are addressed. We could either migrate them or wait until there aren't any because they've either run or gotten unscheduled [by the …
=> EVG-18734 fix task updates

graphql/query_resolver.go, model/task/db.go, model/task_build_variant_names_test.go
EVG-20477
Missed removing this one. We no longer need to look up the build variant display name the legacy way because of the TTL
=> EVG-20477 Remove no longer necessary legacy build variant display name lookup

graphql/tests/mutation/scheduleUndispatchedBaseTasks/data.json, model/lifecycle.go, model/task/db.go, model/task/task.go, model/task/task_test.go
I'm looking to track the time it takes from when a task is activated until the time begins to run. This will allow us to evaluate timing improvements that we can't see today. I ran into cases where tasks were getting activated after they were already activated, sometimes even after a task has started to run, and it was throwing off the numbers.
This PR makes activating an already activated task a noop. If there's an issue with this I could add a separate field to track the last time it was actually activated, but if not it seemed to make sense to only activate a deactivated task.
Idk if we want to do the same for deactivating tasks, but I'm happy to if someone suggests they should be consistent. 
Added to the `ActivateTask` test.
=> EVG-18734 only activate deactivated tasks

graphql/generated.go, graphql/models_gen.go, graphql/mutation_resolver.go, graphql/schema/directives.graphql, graphql/schema/mutation.graphql, graphql/schema/types/distro.graphql, graphql/tests/mutation/deleteDistro/data.json, graphql/tests/mutation/deleteDistro/queries/delete_distro.graphql, graphql/tests/mutation/deleteDistro/results.json, rest/data/distro.go, rest/data/distro_test.go, rest/route/distro.go, rest/route/distro_test.go
EVG-19938
This PR adds the `DeleteDistro` mutation.
The reason why the input & output of the mutation is an object despite it only containing one item is because of [this article](https://www.apollographql.com/blog/graphql/basics/designing-graphql-mutations/) that was shared in the UI channel. (Summary of the article: it makes it easier to change the mutation in the future since we can just add more items to the object.)
- Augmented the existing tests in rest/data/distro_test.go
- Added GraphQL test
=> EVG-19938: Add DeleteDistro mutation

rest/route/agent.go
It would be good to be able to use the `task-start-stats` message to evaluate how long it's taking end-to-end from when a task is activated until it's started (the `activated_latency_secs` field). It would only be useful, though, if we could case on whether there are dependencies (in which case the task was waiting from when the dependencies finished running) or not (in which case it was waiting since the task was activated).
=> EVG-18734 log number of dependencies

agent/agent.go, config.go
EVG-17125
I read the original context for why this was added (in #4508) and it seems like it was temporary debug logging to diagnose an issue where setup group was running when it should not have. Also, the debug log appears in the agent's previous task log (instead of the current task log) because it logs before we set up the current task's logger. It seems safe to remove the debug log entirely.
N/A
N/A
=> EVG-17125: remove debug log for setup group

model/task_queue.go, model/task_queue_test.go, units/crons.go
With https://github.com/evergreen-ci/evergreen/pull/6797 in production we can see the query is much faster and we shouldn't need to throttle the scheduler any more. 
This is a vert of #6628 which removed the throttling. Because it's already been reviewed I will skip asking for a review, assuming tests pass.
=> EVG-18734 remove scheduler throttling (#6628)

agent/agent.go, agent/agent_test.go, agent/global.go, config.go
[EVG-20310](https://jira.mongodb.org/browse/EVG-20310)
The opts AgentSleepInterval and MaxAgentSleepInterval were ready but never set (except for one test). They were removed to simplify the code. 
Existing tests
=> EVG-20310 Remove unused agent opts

repotracker/repotracker.go, trigger/process.go, trigger/process_test.go, trigger/project_triggers.go
EVG-20473
Each trigger definition creates the same version ID. For triggers that run off of a successful build in an upstream version, multiple requests to create the same version with the same ID will run. Normally this doesn't cause a problem because they all fail with "duplicate key" errors, but we recently ran into an issue where these duplicate requests wiped the update a `generate.tasks` command performed on the version's parser project.
This was because the build triggers were ignoring the `SatisfiedTriggers` field, unlike the task triggers. Also did a drive by fix removing an unused field in a helper function.
Created new unit test confirming this prevents the second run for the build triggers from erroring
=> EVG-20473 Prevent the same trigger from trying to create the same version twice

units/crons.go
A bunch of the crons that are supposed to be running every fifteen seconds were actually running once a minute. This is because [RoundPartOfMinute](https://github.com/evergreen-ci/utility/blob/ea9a6354cebb635c026d8dbc7621c35622bb10c4/time.go#L87) rounds down to the nearest minute if n is 0. Providing `n == 15` will do what we want: floor to the previous 15 second interval.
On staging the scheduler, alias scheduler, and host allocator jobs ran [every 15 seconds](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/4yzKaJQWYpE) instead of [every minute](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/hvreU5BzWoM).
=> EVG-18734 run fifteen second jobs every fifteen seconds

units/host_monitoring_idle_termination.go
[EVG-19918](https://jira.mongodb.org/browse/EVG-19918)
The OTel traces revealed that the job was slow because we were calling GetConfig in a loop (once for each idle host). Since GetConfig makes ~30 synchronous round trips to the db this was adding up.
I'll take it for a spin on staging before I merge it to make sure the job is not broken.
=> EVG-19918 get only scheduler config and get it only once

model/project_ref.go, validator/project_validator_test.go
EVG-20301
The container can't start if you don't give it a working directory, so I added validation to ensure it's set.
N/A
=> EVG-20301: validate container working directory

service/middleware.go, service/ui.go
[EVG-19190](https://jira.mongodb.org/browse/EVG-19190)
Now that the settings fetch is taking a context it gets cancelled if the request is terminated in the middle and the find returns an error. There are two places where we aren't returning in the error case. These are fixed by this PR.
=> EVG-19190 handle nil from error cases

units/crons.go, units/crons_remote_fifteen_second.go, units/crons_remote_minute.go
[EVG-19917](https://jira.mongodb.org/browse/EVG-19917)
Now that the idle-host-termination job is consistently faster than 15s (https://github.com/evergreen-ci/evergreen/pull/6790) we can run it more frequently. Hopefully this will help us to decrease idle time without a corresponding increase in wait time. I'll need to check on this a day or two after it deploys.
In staging these changes made the job run [every fifteen seconds instead of once a minute](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/32rYi4CRRvi).
=> EVG-19917 run idle-host-termination more frequently

agent/command/git.go, agent/command/git_test.go, config.go
EVG-20515
It turns out that the merge group branch does not use the concept of "/head"
like the GitHub PRs do. I did not discover this in my testing, because my
staging testing used a project that did not clone. While dogfooding with the
Evergreen team, we discovered this, and I validated this by fetching the merge
group branch manually.
I edited the unit tests to validate the branch pattern that I found in manual
testing.
N/A
=> EVG-20515 Fix merge group clone suffix

units/patch_intent.go
EVG-20516
This fixes a bug introduced by
https://github.com/evergreen-ci/evergreen/pull/6778. That PR always attempted to
set owner and repo using the project name. However, only CLI and trigger types
already set a name. GitHub PR and merge group types do not set a name until
later in the process. This means that the code was finding a project by passing
an empty identifier.
Note that this PR also adds some returns, whereas before we continued on error.
This PR also passes the GitHub merge group data instead of PR data to the update 
message.
Ran existing unit tests.
N/A
=> EVG-20516 Only search for project when one is known

config.go, docs/Project-Configuration/Merge-Queue.md, operations/commit_queue.go, service/api.go
EVG-20299
If the merge queue is set to GitHub, you must merge from a GitHub PR. This PR
returns an error to the user if they try to merge with the Evergreen CLI while
the queue is set to GitHub.
I didn't see a straightforward way to test this. This code does not appear to be
directly under test, and it makes some API calls that would make it difficult to mock. I think the change is small enough that the cost of writing new tests is not worth it.
Added a sentence about this constraint.
=> EVG-20299 Disable CLI commit queue when GitHub merge queue is on

db/errors.go, graphql/patch_resolver.go, graphql/query_resolver.go, graphql/version_resolver.go, model/task/db.go, model/task/db_test.go
EVG-19960
On certain very large patches, there is a chance  that the `getTasksByVersion` aggregation encounters the following error `(Location4031700) PlanExecutor error during aggregation :: caused by :: document constructed by $facet is 104858682 bytes, which exceeds the limit of 104857600 bytes`  
This error stumped me because it lead me to believe that this was something that could be resolved by toggling the `allowDiskUsage` flag to get around MongoDB's 100mb stage limit. In reality, this is actually a limitation with the `$facet` stage that is described in [SERVER-59837](https://jira.mongodb.org/browse/SERVER-59837)
In order to get past this I decided to introduce an additional parameter that will not use the optimization introduced in EVG-15279 - #4997 and instead fallback to …
=> EVG-19960 Create fallback for annotation lookup when it hits the $facet size limit

docs/Project-Configuration/Task_Traces.md
[EVG-19251](https://jira.mongodb.org/browse/EVG-19251)
User testing showed that the two changes from this PR are necessary for test spans to hook into their task's trace.
Specifically:
~- specify a `service.name` that's the same as the task trace's~
- set the `FlagsSampled` trace flag so it isn't dropped along the way
=> docs: EVG-19251 task trace doc fixes

validator/project_validator.go, validator/project_validator_test.go
EVG-18861
If a task lists a dependency, the build variant of the task and its dependency are implicitly the same. Therefore, the dependency of the task must also be listed in the build variant task list. There was no validation for the case of an implicit build variant for a dependency, so I added a warning.
* Added unit test for implicit dependency.
* Tested in staging with `evergreen validate` that a task that depended on another task in the same implicit build variant produced a validation warning.
N/A
=> EVG-18861: warn for missing dependencies with same implicit build variant

go.mod, go.sum, graphql/generated.go, graphql/models_gen.go, graphql/schema/types/task.graphql, graphql/util.go, model/testresult/cedar_service.go, model/testresult/local_service.go, model/testresult/local_service_test.go, model/testresult/testresult.go
EVG-20445
This updates the test results service's `FilterOptions` to include and pipe through the new field `ExcludeDisplayNames` as well as update the graphql schema to include said field in the `TestFilterOptions` input. When set, the new field excludes display names when matching on the test name regex, the default behavior will continue to favor matching on display test name—so the changes are backwards compatible. 
Tested in staging that this works with parsley, does not break existing filtering functionality on spruce (which is uses the default filtering on display test name), and added unit tests for the new field in local test results service.
N/A
=> EVG-20455: add new `ExcludeDisplayNames` field for test result filtering

model/task/task.go
EVG-19650 
We were getting tasks logged to task-end-stats that said they'd been running for 53 years, i.e. the start time was set to the zero time. It looks like this isn't unexpected for tasks that are stranded after dispatching, and we have handling for it in the MarkEnd function, but we don't do that for systsem failures, so modified this to call it, and verified we don't update a task to be finished anywhere else.
=> EVG-19650 use mark end for system failed tasks

model/testresult/testresult.go
EVG-20455
This updates the test result's Parsley log URL generation to use the unique test name instead of the log test name after [EVG-20443](https://jira.mongodb.org/browse/EVG-20443). I also added url encoding to be safe.
Tested in staging against Parsley.
N/A
=> EVG-20455: update Parsley test log URL to use the unique test name instead of the log test name

config.go, operations/patch.go
EVG-20545
Fix a panic in `evergreen patch-file` due to dereferencing a nil raw patch pointer. The raw patch are only available if we're submitting a patch from an existing patch ID, not if we're patching with a local diff file.
Ran `evergreen patch-file` command and it no longer panics. This CLI command doesn't have any unit tests already, so I didn't think it was worth it to add.
N/A
=> EVG-20545: check raw patch before dereferencing in patch-file

model/container_task_queue.go, model/container_task_queue_test.go, model/task/task.go
EVG-20087
Set first schedule time for container tasks. This is analogous to the host scheduler first schedule time.
N/A
=> EVG-20087: set container task first scheduled time

agent/command/exec.go, agent/command/exec_test.go, agent/command/shell.go, config.go, docs/Project-Configuration/Project-Commands.md, makefile
EVG-19601
* Extend the places where `subprocess.exec` can search for a `binary` to run. First, try finding binary to run for `subprocess.exec` from either the agent's `PATH` (i.e. the current behavior), then fall back to searching the command's `PATH` (if any).
* Slightly refactor how `env` is handled for `PATH`. (No behavioral change, just reorganization)
* Tested in staging that `subprocess.exec` behaved the same as it did before when no `PATH` is given, but additionally searches the command `PATH` for matching executables.
Updated docs for `subprocess.exec` and its special interaction with `PATH`. I also improved docs for how `add_to_path` actually works.
=> EVG-19601: allow subprocess.exec binary to search command PATH

apimodels/agent_models.go, model/log/sender.go, rest/route/agent.go, rest/route/agent_test.go
EVG-20017
This passes through the admin bucket config settings for agent setup to enable the new bucket logging directly from the agent. The agent will use existing S3 keys for auth or, more idealistically, some instance role permission.
Updated the unit tests for the agent setup route.
N/A
=> EVG-20017: pass through bucket config in agent setup

agent/command/exec.go, agent/command/exec_test.go, config.go, docs/Project-Configuration/Project-Commands.md, makefile
EVG-19601
Fixes two things, only one of which is actually directly due to the PR:
1. I noticed [the Windows build variant was failing to compile the Evergreen CLI](https://evergreen.mongodb.com/task_log_raw/evergreen_windows_test_agent_command_f6657e434aaabf8816f02ddc2f4f22a514930caa_23_08_04_20_30_08/2?type=T#L509), which is necessary for the agent command unit tests to test `subprocess.exec`. Unfortunately, it seems like Windows in Evergreen CI was having difficulty compiling because the Evergreen hosts run commands in Cygwin (which follows the Unix convention for file paths rather than Windows convention), but `build-cross-compile` only allows Windows executable paths, not Cygwin paths. I fixed it so that `build-cross-compile` uses the native Windows path to the Go binary, not the …
=> EVG-19601: fix cross-compilation on Cygwin and file path handling

agent/agent_test.go
EVG-20586
This rewrites the test to check the task missing a secret condition using the processNext function instead of relying on the agent loop context to test the condition which is more error prone.
=> EVG-20586 Fix flaky test-agent on OSX 

model/task/task.go
EVG-17126
Removing these logs that were intended to be temporary and only for debugging / verification purposes.
=> EVG-17126 Remove temporary debug logs

model/generate.go, model/generate_test.go, units/generate_tasks.go
EVG-20440
Currently, the command runs `getNewTasksWithDependencies` twice: once when simulating dependencies to check for cycles, and another time when actually creating the generated tasks, with the only difference being that the latter call passes in the generator's activation info, which determines if tasks are created in an active or inactive state, but since that doesn't matter for computing dependency cycles, it's fine to consolidate the two calls.  For large JSONs, this step can take a solid chunk of time (~30 seconds or more), so running this function once and saving its output to the generator struct will speed things up.
Created a dummy generated JSON in the sandbox project with ~20,000 tasks and 20 variants to emulate what server does. Honeycomb trace shows a reduction in …
=> EVG-20440 Move getNewTasksWithDependencies to its own function

config.go, config_auth.go, config_test.go, rest/data/patch_test.go, rest/route/github.go, rest/route/github_test.go, rest/route/testdata/pull_request.json, thirdparty/github.go, thirdparty/github_test.go, units/commit_queue_test.go, units/testdata/pull_request.json
EVG-20597
github events from apps are now ignored if app auth is not set up 
also deletes the admin setting validation for the GitHub section because it seems irrelevant 
created a staging pr and made sure that none of the events went through 
adding the app id back to the settings lets the event go through again
=> EVG-20597 Only process one GitHub webhook event depending on app settings

docs/Project-Configuration/Project-Commands.md
EVG-17598
Add documentation for `perf.send`'s expected file format for test results file.
`perf.send` loads this file into a `Report` struct instance (with empty fields except for the `Tests` field, which contains test results as Test struct instances) [here](https://github.com/evergreen-ci/evergreen/blob/4c96f9920b8c9ad045774bb4951f03b1bbffb3d1/agent/command/perf_send.go#L65) using [poplar's `LoadTests`](https://github.com/evergreen-ci/poplar/blob/3b666933139b7a56487da387c9f56f3adf8dfb00/report_read.go#L58). Here's the [Godoc for the `Report` struct](https://pkg.go.dev/github.com/evergreen-ci/poplar#Report) (I left it out of the PR because it's not pertinent to the file format). Godoc links to the `Test` struct and its internal structs are included in the PR. The Godoc page contains …
=> EVG-17598 - Document perf.send's test results file format more explicitly

.gitattributes
EVG-20615
Github support suggested using the following attributes to try to ensure that our go files don't get incorrectly tagged as generated
Email
> Hi Mohamed,
> 
> Thank you for your patience. I've heard back from our engineering team, and it does not appear that you can turn off linguist-generated tags. Indeed, our help docs only show turning it on, and [more specific Linguist documentation](https://github.com/github-linguist/linguist/blob/master/docs/overrides.md#using-gitattributes) suggests you can only flag it as generated, but not as not-generated.
> 
> That said, the Linguist docs point at some other things you might try as a workaround though, specifically marking it linguist-detectable and maybe giving it a language as well, i.e. linguist-language=go. Combining that I'd …
=> EVG-20615 Use linguist detectable flag for non generated files

agent/agent.go, agent/agent_test.go, config.go
EVG-20608 
If the agent encounters a task that is missing a secret, there is no point in immediately trying to get another task, because it will keep getting the same task with the missing secret until enough time has passed. Instead, we should make it sleep for longer to reduce the amount of times it logs "task response missing secret". 
Added to the unit test.
=> EVG-20608 Reduce the noise for the task missing secret condition

apimodels/agent_models.go, model/task/db.go, model/task/task.go, model/task/task_test.go, service/task.go, service/templates/task.html
EVG-20018
This is just cleans up the `Task` model by removing the unused `Logs` field.
Updated unit tests and checked that task logs are loaded successfully in staging.
N/A
=> EVG-20018: remove unused `Logs` field from the `Task` struct

model/event/distro_event.go, service/distros.go
EVG-20621
- An existing bug set `newDistro` to equal the pointer of `oldDistro` when making a distro update. This meant that applying the user's changes to `newDistro` also applied them to `oldDistro`. In the updated distro modified event logger from #6878, we stop logging if the "before" and "after" structs are equal, so an event was not being added.
- I also removed the equality check for safety in the meantime (without it, the legacy distro event log functions correctly since it does not rely on a comparison between the old and new structs)
- Tested manually since there's no test for `modifyDistro()`
N/A
=> EVG-20621: Fix old distro pointing to new distro struct

agent/command.go, config.go
EVG-20593
If an expansion updates a function var and we want to persist it, there's no need to update the saved previous list to the current value. We can just delete the key so that it doesn't get reset. 
There are two existing tests for this condition
=> EVG-20593 Delete Previously set function key instead of updating it

agent/agent_test.go
EVG-20652
This test was passing, but it also hit an unrelated error of the build variant missing from the project. This adds a check to make sure that it's not exiting for other reasons so we know that it's exiting because shouldExit is true. 
The test itself
=> EVG-20652 TestAgentEndTaskShouldExit should pass because shouldExit is true 

cloud/pod_util.go, cloud/pod_util_test.go, go.mod, go.sum, rest/data/pod.go, rest/data/project.go, rest/data/project_settings_test.go, rest/data/project_test.go, rest/route/project.go, rest/route/project_test.go, rest/route/sns.go, rest/route/sns_test.go, units/container_secret_cleanup.go, units/container_secret_cleanup_test.go, units/pod_allocator.go, units/pod_creation.go, units/pod_definition_cleanup.go, units/pod_definition_cleanup_test.go, units/pod_definition_creation.go, units/pod_definition_creation_test.go, units/pod_health_check.go, units/pod_termination.go
[EVG-19211](https://jira.mongodb.org/browse/EVG-19211)
Upgrade cocoa for https://github.com/evergreen-ci/cocoa/pull/109 and https://github.com/evergreen-ci/cocoa/pull/110. This will make spans for the AWS API calls cocoa is making (e.g. [this trace](https://ui.honeycomb.io/mongodb-4b/environments/staging/trace/Ag5NPXZkVgx)).
Ran [a containerized task in staging](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2004_container_test_auth_patch_1e2de6c2077425d29d40f90aa8c31c8039f8fc45_64da7ed5b237365853752a14_23_08_14_19_22_05/logs?execution=0).
=> EVG-19211 upgrade cocoa

agent/command.go, agent/command_test.go, config.go, model/project.go, model/project_parser.go, model/project_parser_db.go, model/project_parser_merge_functions.go, model/project_parser_test.go
EVG-20653
This allows users to specify `unset_function_vars: true` in their project yaml to test how they will be affected by this change. 
unit test 
An email will be sent out. This will not be formally documented because it's temporary
=> EVG-20653 Add a temporary flag that lets projects to test unsetting FunctionVars

globals.go, units/host_allocator.go, units/host_termination.go, units/provisioning_create_host.go
[EVG-20365](https://jira.mongodb.org/browse/EVG-20365)
Add metrics to the job spans that we can then query and turn into a dashboard.
This will let us do queries like:
- [task queue length and time to empty](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/5XLjchiQu6K)
- [host counts (running tasks, idle, new requested)](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/sZuLwCTxLx9)
- [host spawn count](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/9LvRiroUvpC)
- [termination stats](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/m4PAtb3STSv) (e.g. total idle time, billable time)
=> EVG-20365 distro Honeycomb dashboard

model/patch/github_merge.go, model/patch/github_merge_test.go, units/patch_intent_test.go
EVG-20531
This PR fixes an issue where the base commit links are sometimes undefined for GitHub merge patches. The base commit is [looked up using the revision](https://github.com/evergreen-ci/evergreen/blob/c638d4a4734917483f20a41641a4af261c63145b/graphql/version_resolver.go#L46), so it's important that the revision is correct.
There was an error in that the revision was being set to itself (the head hash) rather than the base commit (the base hash). This PR sets the revision to the base hash instead of the head hash. I believe this is what we usually do, based on the following examples ([1](https://github.com/evergreen-ci/evergreen/blob/ec428ff16dc9772d116871e17fa1849845e9c497/model/patch/patch.go#L1203), [2](https://github.com/evergreen-ci/evergreen/blob/2fac0bebf32538a259d6ff116ba1fee4 …
=> EVG-20531: Set revision to base SHA for GitHub merge patches

units/host_termination.go
[EVG-20365](https://jira.mongodb.org/browse/EVG-20365)
This would give us insight into how many tasks the hosts are running before getting terminated. For example, we would want to know if there are a lot of hosts starting and not running any tasks.
=> EVG-20365 add task count

agent/command.go, agent/command/downstream_expansions_test.go, agent/command/expansion_test.go, agent/command/expansion_update.go, agent/command/testdata/git/test_expansions.yml, agent/command_test.go, agent/internal/task_config.go, config.go, self-tests.yml, util/expansion.go
EVG-20673
Function vars wouldn't unset any vars whose values were changed by expansions.update. However, if it was set to the same value as the function var, it didn't work. We don't want that to be the case because we want users to be able to do this to persist function vars. 
Unit test and tested on staging.
=> EVG-20673 Allow expansions.update to set expansions to the same value as function vars

agent/command/git.go, config.go
EVG-20683
Reduce the amount of verbose logging that is shown when `git clone` fails and retries. We could have kept the verbose logging if we had a newer version of git on all the machines (the auth header is only an issue in old versions of git which RHEL 7.x comes with by default), but older versions of RHEL can't get newer git versions (without compiling it from source).
I tested this in a spawn host and confirmed that the verbose logs don't show the auth header.
N/A
=> EVG-20683: remove GIT_CURL_VERBOSE

agent/agent.go, agent/agent_test.go, agent/agent_timeout_test.go, agent/background.go, agent/background_test.go, agent/command.go, agent/global.go, config.go, docs/Project-Configuration/Project-Configuration-Files.md, model/project.go
This reverts commit c3d3980edc258b9c3f8e944f6f82e63912312e32 and fixes an issue where `getCallbackTimeout` double acquires the task context read lock.
[`RLock` docs](https://pkg.go.dev/sync@go1.21.0#RWMutex.RLock) say recursive read locks can deadlock when there's another goroutine calling `Lock` right before the recursive RLock.
=> Revert "Revert "EVG-20281: improve callback timeout behavior (#6894)" (#6922)"

model/lifecycle.go
EVG-20705
Apologies for the essay, this was a journey.
Although initially it seemed that the act of inserting many tasks into the DB was the bottleneck during task generation for large JSONs, after setting up more detailed honeycomb traces it appears that although the amount of time `tasks.insert` runs for is significant, but looking at the bottom of [this trace](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/aB58Z3FGywQ/trace/kfgs2RUsrid?fields[]=c_name&fields[]=c_service.name&span=67e50313e32f064c), for example, there appears to be something else happening in between each iteration of the loop where we perform `tasks.insert` that is taking a lot of time.
To investigate further I set up more detailed spans inside the bottlenecking `add-new-builds` span, …
=> EVG-20705 Remove expensive grip statement

graphql/tests/mutation/promoteVarsToRepo/data.json, graphql/tests/mutation/promoteVarsToRepo/queries/promote_vars.graphql, graphql/tests/mutation/promoteVarsToRepo/results.json, rest/data/project_settings.go
EVG-20469
- The GraphQL resolver provides the project identifier, not ID, when calling `PromoteVarsToRepo`. To successfully complete the operation, we need to first look up the ID and use it in place of the identifier.
- Add unit test demonstrating successful execution of the resolver when a project identifier is provided
N/A
=> EVG-20469: Use project ID when promoting vars to repo

agent/command.go, agent/command/expansion_test.go, agent/command/expansion_update.go, agent/command_test.go, agent/internal/task_config.go, agent/internal/task_config_test.go, config.go, util/expansion.go
EVG-20703
This addresses all the comments in [6911](https://github.com/evergreen-ci/evergreen/pull/6911). Some of the open threads are no longer relevant because it was switched from a pointer to a struct. 
One more test and existing tests.
=> EVG-20703 Expand testing and improve style for expansions.update

graphql/distro_resolver.go, graphql/generated.go, graphql/models_gen.go, graphql/schema/types/distro.graphql, graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql, graphql/tests/mutation/saveDistro/queries/save.graphql, graphql/tests/mutation/saveDistro/queries/validation_error.graphql, graphql/tests/query/distros/queries/distro.graphql, graphql/tests/query/distros/results.json
EVG-19945
- Use an enum for more predictable typing of a distro's provider field. This PR is in the same vein as #6896 and #6913
- Update unit test
N/A
=> EVG-19945: Use enum for distro provider

agent/global.go, config.go, docs/Project-Configuration/Project-Configuration-Files.md
EVG-20629
I had a thought about this and decided that we should give the server (the only project that hits the 15 minute post timeout limit today because of one particularly slow function) some time to adjust their YAMLs to set the new post timeout setting if they want to use it. I reduced the default timeout to 30 minutes for the interim, so post can run for at most 15 minutes more than previously.
=> EVG-20629: temporarily reduce default post timeout

rest/route/service.go, service/api_patch.go
EVG-20474 
Added permission check for the submit patch (originally we had a SubmitPatch middleware, but Kim removed this since it didn't work, bc it relied on the query parameters). Since this is a pretty special case and the APIServer routes are already a bit wild west I think adding this to the route directly is fine.
Will create a patch with and without permissions to test.
=> EVG-20474 add validation to submit patch

units/provisioning_create_host.go
EVG-20400
This test began racing because of a few changes:
* The test is set up to use [a local queue group](https://github.com/evergreen-ci/evergreen/blob/63cc5d7f42e4f2c74ecaf550c53490c3cd7a9df8/rest/data/host_create_test.go#L134-L137). This behaves differently from the remote queue because in the local queue, all jobs are stored in-memory (unexported fields like the `evergreen.Environment` do not get cleared in between the job enqueueing and the job running because there's no roundtrip through the DB).
* The [host creation job is enqueued immediately](https://github.com/evergreen-ci/evergreen/blob/63cc5d7f42e4f2c74ecaf550c53490c3cd7a9df8/rest/data/host_create.go#L448-L450) when host.create inserts the host document.
* The job runs in the local queue, and multiple jobs run in parallel …
=> EVG-20400: fix race in test-rest-data

units/patch_intent.go
EVG-20633
I'd like to use this debug logging to check to see what projects, if any, either aren't setting branch protection rules or don't have permission for Evergreen to view them. This will help with the migration.
None needed. It's debug logging.
N/A
=> EVG-20633 Log for default merge queue status

agent/background.go, agent/internal/client/interface.go, config.go
EVG-20287
TaskConflict can be removed because it's no longer being used.
=> EVG-20287 Remove TaskConflict 

cloud/docker_integration_test.go, rest/data/host_create_test.go, self-tests.yml, thirdparty/docker/docker_cleanup_test.go
EVG-20733
This feels a tad bit silly, but this is actually the simplest solution to DockerHub's rate limit - all the others that I tried to continue using the DockerHub image but test less often resulted in a lot of special configuration for our self-tests YAML and reorganization of the cloud package tests. It seemed not worth it to add more complexity to our testing setup, given that we plan to sunset Docker `host.create` (and will therefore one day remove all this code). The new image being tested is the same as the one on DockerHub, just from a different registry.
ECR allows [1 unauthenticated pull per second](https://docs.aws.amazon.com/AmazonECR/latest/public/public-service-quotas.html), compared to DockerHub's 100 unauthenticated pulls per 6 hours, so with retries, this is unlikely …
=> EVG-20733: use ECR image instead of DockerHub for Docker tests

docs/API/REST-V2-Usage.md, docs/Project-Configuration/Evergreen-Data-for-Analytics.md
It's unclear what materialized intelligence means. The new name makes it clearer that it's evergreen data to be used for analytics.
=> Rename materialized intelligence to Evergreen Data for Analytics.

model/pod/pod.go, model/project_ref.go, util/strings.go
EVG-20609
To prevent a bloated "allowed image" list where a new entry is put for every ECR repo's immutable tag, we can change the validation to treat the allowed list as an allowed list of image uri prefixes, which should be safe because publishing a new immutable tag for a project requires approval via PR approval in [this repo](https://github.com/evergreen-ci/container-initial-offering-dockerfiles)
Tested in staging with `557821124784.dkr.ecr.us-east-1.amazonaws.com/evergreen/production-ecs` as an allowed image and confirmed that e.g. `557821124784.dkr.ecr.us-east-1.amazonaws.com/evergreen/production-ecs:1635b8ecdd264fb4f5fde38d88931b4e9a677b06` works
=> EVG-20609 Validate images by prefix rather than full string

agent/util/subtree_unix_test.go
EVG-20700
The test output shows that some machines are occasionally slow at running `ps` to get the running process, so it's hitting the 5-second context timeout. Just bumping the timeout and checking for no context timeout seems sufficient to stop the test from flaking.
* Increase flaky test timeout.
* Refactor agent process-related tests a little bit.
I ran it locally, but if it's really fixed, we will no longer see this test flake on the waterfall.
=> EVG-20700: bump timeout for flaky ps tests

graphql/generated.go, graphql/schema/types/project.graphql, graphql/schema/types/project_settings.graphql, graphql/tests/projectSettings/data.json, graphql/tests/projectSettings/queries/project-settings-project.graphql, graphql/tests/projectSettings/results.json
EVG-20650
Following this [PR](https://github.com/evergreen-ci/evergreen/pull/6864), looking to add the `unscheduleDownstreamVersions` field on project triggers to the resolvers, and will add to Spruce afterwards
Modified unit testing
=> EVG-20650 Add unscheduleDownstreamVersions to GQL

model/version_db.go, rest/route/middleware.go, rest/route/middleware_test.go
EVG-20474
This change is a bit risky, since if it's being called somewhere where we aren't actually using urlVars then this will start failing, whereas before it just succeeded using an empty project identifier. However after auditing our code base for it, I believe I've caught the cases.
Can't really test every route, but will poke around in staging.
=> EVG-20474 check if project is empty for middleware

graphql/distro_resolver.go, graphql/generated.go, graphql/models_gen.go, graphql/schema/types/distro.graphql, graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql, graphql/tests/mutation/saveDistro/queries/save.graphql, graphql/tests/mutation/saveDistro/queries/validation_error.graphql
EVG-19951
This just adds more enums for the host settings page, in a separate PR since these fields are thematically in the same group.
I'm pretty sure that the `DEFAULT` values means that the values will be [inherited](https://github.com/evergreen-ci/evergreen/blob/2c322c18832281119433281f9026724975e9a74a/model/distro/distro.go#L665C1-L673) from Evergreen settings (see the "Scheduler" section in the admin settings).
=> EVG-19951: Use enums for host allocator fields

config.go, docs/Project-Configuration/Project-Configuration-Files.md, globals.go, model/generate.go, model/project.go, model/project_parser.go, model/project_parser_test.go, model/project_test.go, repotracker/repotracker.go, validator/project_validator.go, validator/project_validator_test.go
EVG-20622
This adds a new project YAML configuration, which lets a user enumerate the particular requesters (e.g. GitHub PR, git tag version, periodic build) for which they want to run a task. This is a generalization of the filters currently provided by `patchable`, `patch_only`, `allow_for_git_tag` and `git_tag_only` (e.g. `git_tag_only: true` is equivalent to `allowed_requesters: ["github_tag"]`). We have no plans to actually deprecate the boolean requester options though; I chose to instead add a warning that mixing requester booleans with `allowed_requesters` is incompatible.
There will be a follow-up PR to update Shrub for `generate.tasks` after this is merged.
* Add `allowed_requesters` configuration.
* Add some helpers to translate the user-facing requesters that we expose via …
=> EVG-20622: support allowed requesters list

docs/Project-Configuration/Project-Configuration-Files.md
`allowed_requesters` can potentially conflict with the variants/tasks selected for project settings like periodic builds and GitHub PR patches, so I mentioned how they interact.
=> docs: mention how allowed_requesters interact with conflicting project settings

config.go
EVG-20738
Github sometimes returns 500 or server errors when creating tokens so we should retry 
verifies it still works
=> EVG-20738 Update client in CreateInstallationToken to retry

environment.go, mock/environment.go, model/patch_lifecycle.go, thirdparty/github.go, units/event_send.go, units/github_status_api.go, units/github_status_api_test.go, units/github_status_refresh.go
EVG-20744
GitHub apps don't support cross-org authentication so you need to generate a new access token for every owner. 
This change makes senders for each owner and caches it to the env.
GitHub app tokens expire after 1 hour so we re-create the token and sender after it expires 
Can't test on staging as the staging github app is only installed on 1 org so I can't test the cross-org authing 
But confirmed that the fallback works and we use the legacy global sender when the app fails to create a sender
=> EVG-20744 Add unique senders for github apps

agent/command/archive_auto_extract.go, agent/command/archive_tarball_create.go, agent/command/archive_tarball_extract.go, agent/command/archive_zip_create.go, agent/command/archive_zip_extract.go, agent/command/attach_artifacts.go, agent/command/downstream_expansions_set.go, agent/command/exec.go, agent/command/expansion_update.go, agent/command/expansion_write.go, agent/command/generate.go, agent/command/git.go, agent/command/git_push.go, agent/command/host_create.go, agent/command/host_list.go, agent/command/perf_send.go, agent/command/results_gotest.go, agent/command/results_native.go, agent/command/s3_get.go, agent/command/s3_pull.go, agent/command/s3_push.go, agent/command/shell.go, agent/command/util.go, agent/command/util_test.go, agent/internal/task_config.go, agent/internal/task_config_test.go, config.go
EVG-20654
The agent commands that need to work in a directory can use either `GetWorkingDirectory` or `getJoinedWithWorkDir`, both of which accomplish the general goal of resolving a working directory. The major difference is that `getJoinedWithWorkDir` allows absolute paths outside of the task working directory, whereas `GetWorkingDirectory` will force all paths to be prefixed by the task working directory, even if they're specified like absolute paths. For example, if you set a working directory of `/home/mci/directory`, `getJoinedWithWorkDir` would keep it as-is while `GetWorkingDirectory` would convert this into `${workdir}/home/mci/directory`.
Since `GetWorkingDirectory` behaves differently for absolute paths and is also used in `subprocess.exec` and `shell.exec`, it would be …
=> EVG-20654: deprecate duplicate GetWorkingDirectory

model/task/task.go, model/task_lifecycle.go
EVG-19285
For Archive, we check if archiving has a duplicate key error, I believe to avoid races. This doesn't work for ArchiveMany bc transactions don't respect error handling, they just abort if there's an issue (GODRIVER-1721).
We only actually are hitting this error for ArchiveMany for display tasks that have multiple execution tasks fail heartbeat (i.e. all of them are racing to archive the display task). 
I think we should just avoid erroring in the case that the display task actually was restarted, since there's no error here. Open question I have is whether we should log something special in this case.
Hard to test since it requires a specific race; going to reason over and keep an eye out for this error for a week or so.
=> EVG-19285 avoid unneeded error for fixing stale display task

docs/Project-Configuration/Project-Commands.md
EVG-19099 
Added some docs to try and explain the behavior of module revision/ref/branch in the git.get_project docs. This isn't perfect -- I don't totally understand why ref isn't used for patches (although it's user confirmed and already mentioned in documentation) but I believe it has to do with the manifest, which is checked before ref -- but I think addresses the problem that spawned this ticket.
=> EVG-19099 update module git.get_project docs

model/event/task_event.go, model/lifecycle.go
EVG-20052
We are not logging events when versions (or builds) are changed in priority. This adds the event logs when either are changed in priority.
I added it to the build priority change call as well although I think that is only used via a REST endpoint and the old UI, but it was an identical change and might help us debug in the future niche cases.
Existing tests already test these functions. Tested (before and after) setting priority of a version and looking at event log of individual tasks (locally and in staging)
Example of setting priority for a version and it showing up in the event logs for a task:
https://github.com/evergreen-ci/evergreen/assets/64446617/33813def-9a0d-4f09-9d00-7d02f3ac240d
=> EVG-20052 Add event logs when a build/version's priority changes 

rest/data/host_create.go, rest/route/host_create.go, rest/route/host_create_test.go
EVG-20675
The error that rises from a host.create distro not being compatible with a docker provider should be considered an improper request, not an internal server error on Evergreen's end. The fact that it is currently intertwined with the `MakeHost` means that [this retry loop](https://gist.github.com/hadjri/f0f75045653f4043b7805a1f86a96211#file-http-go-L331-L350) in the agent will keep looping until it times out, rather than returning the error immediately as it should. 
Made a refactor to separate the distro retrieval / validation from the actual host creation function to keep this as part of the route parsing logic.
Verified in staging that the `distro '%s' provider must support Docker but actual provider is '%s'` error now is shown when host.create tries to use the docker provider …
=> EVG-20675 Move distro retrieval for create host to separate function

docs/Project-Configuration/Project-Configuration-Files.md, docs/Project-Configuration/Task-Runtime-Behavior.md
This adds a page describing how a task is supposed to run from the user's perspective. It's possible to infer a lot about how a task runs just from the project YAML docs, but you wouldn't be able to deduce much more than the basics from just those docs.
You can view how the markdown will render [here](https://github.com/evergreen-ci/evergreen/blob/385c56df79b3a59336064ba221526e752a0b33af/docs/Project-Configuration/Task-Runtime-Behavior.md).
* Add doc page for details on task runtime behavior.
* Move some docs out of project YAML docs since they're not really related to YAML configuration.
=> docs: describe task runtime behavior

model/task/db.go, model/task/task.go, model/task/task_test.go
EVG-19128
It's possible for some versions to increment the order number value used to keep track of the order of commits. This query would sometimes fail because we only compared against order number - 1 and if the previous order number was a non-mainline commit this query would fail. This change adds a `$lt` so that we attempt to fetch the most recent `gitter_request` commit
Wrote unit tests.
=> EVG-19128 Case on non mainline commits for FindTaskOnPreviousCommit calculation

docs/CLI.md, units/patch_intent.go
EVG-19885
The patch command ouputs warnings when it runs in to an error. Instead, the patch command should only output errors- never warnings. If users want to view present warnings, they can run `evergreen validate` or look at the UI.
Makes a change to filter by errors only at the 'error' level and only output's those at that 'error' level.
Forced warnings/errors in staging and it displays only the error- not the warning.
Before
(Shows error, invalid patched config, and version control for project warnings)
After:
(Shows only error)
Add documentation for patch command not displaying warnings and to use the validate command if you want to see warnings.
=> EVG-19885 Show errors correctly for patch command

model/patch/github.go, model/patch/github_test.go, rest/data/patch_intent.go
[EVG-20174](https://jira.mongodb.org/browse/EVG-20174)
We incorrectly use the push time for create time, but we have the actual create time. This is important for patches made via comment.
Tested using an old PR on staging:
https://github.com/evergreen-ci/commit-queue-sandbox/pull/567
https://spruce-staging.corp.mongodb.com/version/64f8a8139dbe32fa25b98240/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
=> EVG-20174 use intent create time for github patch create time

agent/command/git.go, config.go, docs/Project-Configuration/Project-Commands.md
EVG-20812
This is to ensure consistent behavior among the merge queues.
I am intending to manually test. The existing commit queue case is not under test.
Edited.
=> EVG-20812 Clone head of modules in merge queue

docs/Project-Configuration/Project-Commands.md
Per the requests to improve the documentation from [this slack discussion](https://mongodb.slack.com/archives/C0V896UV8/p1693942801957519).
=> DOCS: Add SSH and host setup information for host.create

model/lifecycle.go, model/project_ref.go, model/project_ref_test.go, repotracker/repotracker.go
EVG-20612
I looked into adding an index for this query but it'd be very expensive. I also started digging into some of the traces and it looks like these queries don't return any versions, which shouldn't be the case; I'm wondering if there's a bug in the code so that we're calling this function too often or something but it's hard to know without more info, so my next thought is to add some info to continue investigating.
=> EVG-20612 add logging to understand batchtime calls

validator/distro_validator.go
EVG-20846
- All other distro "factor" fields are enforced to be between 0 and 100, but GenerateTaskFactor had missing validation. It is enforced [here](https://github.com/evergreen-ci/evergreen/blob/dbc32765171d9a78a42e7ed4105241e489dbfadf/service/templates/distros.html#L268-L269) on the legacy front end, but we should have back end validation too.
- Verified in GraphQL sandbox; field was saved when 0 <= n <= 100 and threw an error if not.
N/A
=> EVG-20846: Add validation for GenerateTaskFactor

model/project_ref.go, repotracker/repotracker.go
EVG-20612
1) Fix the main problem of running the query when there's no reason to
2) Log the stack (with string so it logs correctly) to understand why we'd be doing this in the first place
3) Log how long the query takes in the case that we _are_ supposed to be running it
=> EVG-20612 avoid querying if we don't need last activation time

globals.go, model/project.go, model/project_parser.go, model/project_parser_test.go, model/project_test.go, validator/project_validator.go, validator/project_validator_test.go
EVG-20622
I forgot that the commit queue does a weird thing where [it takes the already-translated project, converts it to YAML, adds more YAML configuration to add the merge task, and re-translates the already-translated project again as if it's a parser project](https://github.com/evergreen-ci/evergreen/blob/bb4161f86a67469d8d696f7d88e769c8b4045756/units/commit_queue.go#L622-L653). This is not really supposed to be done since it requires that the project can be subbed in at any place where a parser project is supposed to be used, but I don't feel like it's worth trying to fix the commit queue given that the commit queue is going to go away soon. Instead, I changed project translation so that it does not translate the user-facing requester into the internal requester.
For example, …
=> EVG-20622: do not translate user requester for project

makefile
EVG-20866
The golangci-lint installation occasionally flakes out and causes linter failures. I'm pretty sure it's something getting stuck in the install script, like a flaky network operation. Unfortunately, we can't tell what is the cause at this point since there's no output, so I changed it to show its install output so we can diagnose the next time it flakes.
Ran it locally to verify the output wasn't overly noisy.
=> EVG-20866: show output from golangci-lint installation

model/project.go, model/project_aliases.go, model/project_aliases_test.go
EVG-20856
There's a bug in `FindAliasInProjectRepoOrConfig` in the project config retrieval step as it passes a `projectID` to `getMatchingAliasForVersion` which prevents the project config from being retrieved correctly.
Changed `getMatchingAliasForVersion` to accept both a project ID and an optional version ID, allowing it to retrieve the project config by id if version ID is provided, and otherwise default to the most recent project config for the given project.
Confirmed [without change](https://evergreen-staging.corp.mongodb.com/version/65009595b237360dc882e498), periodic build does not respect the alias defined in config, and that [with the change](https://evergreen-staging.corp.mongodb.com/version/65009911b2373618aa36ba17) the alias is respected.
=> EVG-20856 Fix getMatchingAliasForVersion to take in project and version

model/host/db.go, units/host_monitoring_idle_termination.go
EVG-19715
We discussed in the ticket terminating idle hosts more aggressively. Right now we wait for a minute, which is a long time if the queue isn't empty / has a lot of tasks that started. I arbitrarily dropped it to 5 seconds.
If we don't think this is enough, then we could alternatively mark all hosts as decommissioned when an AMI is updated.
=> EVG-19715 terminate oudated AMI hosts faster

makefile
EVG-20870
Tests occasionally flake out while downloading MongoDB for CI tests because of transient network issues. I made all curl usages use the same retry logic as the linter to reduce the issue.
N/A
N/A
=> EVG-20870: make MongoDB download less flaky

rest/data/project.go, rest/data/project_settings.go, rest/data/project_test.go
EVG-20670
Since Spruce uses the project identifier in the project settings URL and there's currently no character limitations on the identifier, we have to either 1. prevent special characters from being used for project identifiers, or 2. percent-encode the project ID/identifier in Spruce project settings URLs. I chose to just do option 1.
For valid characters, I referred to the RFC, which describes that [reserved characters should be percent-encoded for safety](https://www.rfc-editor.org/rfc/rfc3986#section-2.2):
>   If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed.
And then chose a regexp pattern that matches [the set of unreserved …
=> EVG-20670: check project ID/identifier has valid characters

config.go, config_test.go, rest/route/github.go
EVG-20867
the github webhooks are currently skipped for orgs without the github app if the github app is defined in the evergreen admin side.
instead of just checking that the app is defined on the evergreen side, we should check that the specific repos are able to create a token, meaning that the app can actually be used by the repo
made sure that the app still worked
=> EVG-20867 Update shouldSkipWebhook to check if token can be created

rest/route/github.go, rest/route/github_test.go
EVG-20838
merge group seems to be sending 2 events with different actions 
1. checks_requested
2. destroyed
it says that github will send the destroy event when a pull request is removed from a queue in the docs 
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=checks_requested#merge_group
it looks like the merge group destroy event is sent if there's only 1 PR in the queue and it merges successfully (couldn't find documentation for this behavior) 
I updated the githook to only look at the checks_requested action for merge_group events
=> EVG-20838 Update githook to only handle checks required merge group events

agent/background.go, agent/background_test.go, agent/global.go, config.go
EVG-20701
* Follow-up to #7014 to actually stop the heartbeat after gathering enough data to verify that this only occurs in exceptional cases.
* I also increased the default timeout because `killProcs` was quite slow - in two tasks ran over the past 4 days, it took more than 8 minutes to complete (but it did complete).
I wrote a unit test.
I also investigated the prod logs to see if the heartbeat timeout logged to Splunk. It did log the alert once, but in a very exceptional case where timing out was the appropriate action. The [one case where it logged](https://mongodb.splunkcloud.com/en-US/app/search/search?s=Heartbeat%20timeout&now=1694772000&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&q=search%20index%3Devergreen%20%22Heartbeat%20has%20hit%20max …
=> EVG-20701: stop heartbeat on timeout

docs/Project-Configuration/Project-Configuration-Files.md
Update the ${branch_name} expansion description to clarify that this refers to the branch that the project tracks. There was confusion by users around whether referred to the branch name of the PR in Github patches.
=> DOCS: clarify ${branch_name} expansion description

cloud/pod_util.go, go.mod, go.sum, units/pod_termination_test.go
EVG-20886
Ran `go get github.com/evergreen-ci/cocoa@69a3ef4b69a0964b1f1ac59c613296a06ecaea5a`.  Upticking the cocoa version on the Evergreen side as a followup to [EVG-17274](https://jira.mongodb.org/browse/EVG-17274)
=> EVG-20886 Uptick cocoa version

units/spawnhost_start.go, units/spawnhost_stop.go
EVG-20751
Spawnhost start and stop sometimes get hanged up with deploy and users cannot stop or start a host themselves on spruce, so this functionality adds retries to both jobs.
Forced spawnhost_stop to have a retryable error and deployed to stage, stopped a host, collected corresponding logs to show that the job retries every 30 seconds (which it does fail stopping since it has already stopped from the initial execution, since the retryable error is non-blocking).
Splunk logs: https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22evergreen-staging%22%20spawnhost-stop%7C%20spath%20job_id%20%7C%20search%20job_id%3D%22spawnhost-stop.zackary.santana.i-05636488b8dfbf329.2023-09-20.20-29-27%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=stand …
=> EVG-20751 Add retryable to spawnhost start and stop

model/artifact/artifact_file.go, model/artifact/artifact_file_test.go, rest/route/agent.go
EVG-18354
We saw an example of a [task](https://spruce.mongodb.com/task/mms_e2e_cypress_E2E_CYPRESS_UI_patch_6a989832deb87ea30ff5c117945cc10c2d96b25b_637ce21d32f417389e6c7f9a_22_11_22_14_52_17/files?execution=2&sortBy=STATUS&sortDir=ASC) where the first file gad a broken link because the "#" character was not escaped correctly. This change ensures that the "#" at the end of the link is replaced with "%23" so that the file loads properly.
Added a unit test for the function and [tested it on staging ](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2204_dist_staging_patch_a1e18399674027393f3f71e1de87cf079617b66a_650b6f1c97b1d3bc9cd5b382_23_09_20_22_16_18/files?execution=0) with a file with # in the link.
=> EVG-18354 Escape file names when attaching to tasks 

model/generate.go, model/generate_test.go, model/lifecycle.go, model/project.go, validator/project_validator.go
EVG-20369
The user's patch was not activating their generated tasks because they explicitly set `activate: true` in their generate.tasks JSON. The logic in generate.tasks assumed that if `activate` is set to anything, it must have specific activation conditions. However, this is only true if `activate` is set to false - a generated task that sets `activate: true` should just activate by default, the same as if `activate` was not specified at all. This only affected new BVs that explicitly set `activate: true` because existing BV definitions can't be modified.
* Fix handling of `activate: true` in new BVs for generate.tasks.
* Fix a small bug I spotted where the task creation logic didn't filter out requesters for which batchtime doesn't apply.
* Added more unit tests for generate.tasks …
=> EVG-20369: allow activate: true for new build variants in generate.tasks

agent/command/git.go, config.go
EVG-20317
Now returning an err upon failure to clone a module rather than continuing the task's execution. 
The ticket's discussion mentions introducing a feature flag in case that this breaks some behavior server is depending on, but since this is an agent side change I believe we should just be ready to revert if needed.
=> EVG-20317 Stop on error if module cloning fails

model/task_lifecycle.go
EVG-20098
Remove WithFields usage from status updates -- fetching individual fields was reasonable when this operation took very little work, but now it's very likely to be the source of hard-to-solve bugs, and task/build documents aren't so big that it's really needed.
=> EVG-20098 remove withFields usage for status updates

docs/Project-Configuration/Task-Runtime-Behavior.md
[Slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1695654507588729)
We occasionally get user questions about whether Evergreen cleans up the host file system, so might as well document it.
=> docs: describe task directory cleanup behavior

docs/Project-Configuration/Project-Commands.md
[Slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1695410142917209)
Someone asked for an example of the output format for the `expansions.write` file. Also, there's already [a test for the exact output format](https://github.com/evergreen-ci/evergreen/blob/ded75d09f9a7ac790d11fe0dd42dad9e712b6a0d/agent/command/expansion_test.go#L76), so we don't need to add any new tests for this.
=> docs: add example of expansions.write output

rest/data/patch.go, rest/data/patch_test.go
EVG-20821 
If a patch has no changes (such as 64ef4f6ad6d80a0b27a2281a), it won't have the githash store in the Patch field of the doc, which we use for determining the githash for the `patch-file` command. We should just return the patch githash, since that's what this is.
Added a unit test to test GetRawPatches, and tested the patch-file workflow on staging (using [this patch](https://spruce-staging.corp.mongodb.com/version/650e01fe9dbe32be8dba4ccb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with no changes, `evergreen patch-file --diff-patchId 650e01fe9dbe32be8dba4ccb` errored without changes, and created [a patch](https://evergreen-staging.corp.mongodb.com/patch/650e02db97b1d3cc9cd2e3da?redirect_spruce_users=true)
with them)
=> EVG-20821 return githash with raw patch data for patch-file command

docs/Project-Configuration/Project-Commands.md
We mention in best practices you should use subprocess.exec, but we don't mention it on the command page itself.
https://github.com/evergreen-ci/evergreen/blob/d22ad631effdf1301dbe3e7ea2b25a392791dce4/docs/Project-Configuration/Project-Commands.md
=> docs: add links for shell.exec command

rest/data/commit_queue.go
EVG-20971
This makes it more obvious to users who are used to typing `evergreen merge`
what to do instead.
Currently it looks like this, which doesn't tell the user what to do.
String-only change, so no testing needed.
N/A
=> EVG-20971 Add more helpful message to merge error

service/task.go
EVG-18454
To facilitate printing error lines in red on Parsley, add a `priority` param to the raw task log route, which will include the line's severity at the start of each line. Calls to this route without the param will continue to omit priority.
On Parsley, the [`AnsiiRow` component](https://github.com/evergreen-ci/parsley/blob/main/src/components/LogRow/AnsiiRow/index.tsx) will be updated to:
- Strip the `[P: NN] ` prefix
- If appropriate, apply a color based on the [severity level](https://github.com/evergreen-ci/evergreen/blob/fb5b3fee0932f24caa2b6eac231bbc5581d081fb/apimodels/task_log.go#L57), as is [done in Spruce](https://github.com/evergreen-ci/spruce/blob/62a296c4030f744759f47baa897b92b8e928afaa/src/pages/task/taskTabs/logs/logTypes/logMessageLine/LogLines.tsx#L9-L28).
- With …
=> EVG-18454: Add priority param to task_log_raw route

model/project_parser.go, model/project_parser_test.go
EVG-20924
Getting files serially from GitHub was causing projects with many file includes
to exceed a timeout.
This is a refactor, so it should be tested by existing tests.
N/A
=> EVG-20924 Get project file includes asynchonously

docs/Project-Configuration/Repo-Level-Settings.md, model/project_ref.go, model/project_ref_test.go
EVG-19841
Stemming from the finding in the comment of this ticket, return an error if a repo has PR testing enabled but has an empty remote config path when creating PR patches for untracked branches.
In staging, confirmed that an[ error surfaces](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22evergreen-staging%22%20%7C%20spath%20%22metadata.level%22%20%7C%20search%20%22metadata.level%22%3D70%7C%20spath%20repo%20%7C%20search%20repo%3D%22commit-queue-sandbox%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1696002688&latest=1696003588&sid=1696004850.5318722) when attempting to create a PR patch for an untracked branch when the remote config path is set to empty.
Updated docs.
=> EVG-19841 Error on adding github intent for repos with no config path

apimodels/cedar_models.go, taskoutput/task_log.go, taskoutput/test_log.go
EVG-20014
Implement Cedar-backed log fetching for the new `TaskOutput` interface.
Nothing will actually start using this yet until EVG-20019 is complete.
N/A
=> EVG-20014: Implement Cedar-backed log fetching for task and test log output

rest/data/project_settings.go, rest/data/project_settings_test.go
EVG-20483
Include the conflicting identifiers in the error message when GitHub settings conflict between projects that have the same owner/repo. There is a very small concern that this technically doesn't follow the permissions model since it can allow a user to deduce the project GitHub settings of a project that they don't have access to, but assuming no malicious user intent, I thought it was too small a concern to actually be exploitable in any meaningful way.
N/A
=> EVG-20483: show project identifiers with conflicting GitHub settings

docs/Project-Configuration/Project-Configuration-Files.md, model/project_parser.go
EVG-19706
A bunch of task fields (like priority, stepback, etc.) can be defined at the task group level. However, they don't do anything, I'm not aware of any users asking to use these fields, and I verified with `evergreen admin all-configs` + `yq` that nobody is using these fields. Therefore, I just removed them all.
Compile and existing tests pass.
Removed mentions of it from the docs.
=> EVG-19706: remove dead task group fields

model/version.go
EVG-21033
A user noticed that they were unable to schedule a patch because it was timing out getting the commit. I also noticed that this same timeout has been hit before in the past, so it's just not this patch affected by the timeout. Bumped it higher and made the timeout per-module to see if it'll resolve the patch scheduling problem.
* Increase timeout for getting commits for modules.
* Move existing logic to helper function for cleanliness + to avoid defer cancelling in a for loop.
Existing tests pass. The timeout increase didn't seem significant enough a change to explicitly test.
N/A
=> EVG-21033: increase timeout for getting commit for manifest

agent/command/attach_artifacts.go, agent/command/attach_artifacts_test.go, agent/command/host_create_test.go, config.go, docs/Project-Configuration/Project-Commands.md
EVG-19086
Introducing a new `exact_file_names` flag on the attach.artifacts command, which will cause the command to match exact file names rather than performing regex style matching on the entire work directory.
Added some new unit tests to the attach artifacts test suite.
Added a piece to the attach.artifacts documentation for this new field and its functionality.
=> EVG-19086 Introduce option to match attach.artifacts with exact file names

model/patch/patch.go, model/patch_lifecycle.go, model/patch_lifecycle_test.go
EVG-20795
Discovered that when we update description only (using the lil UI pencil) we overwrite existing patch task/variant definitions.
Considered making a new mutation instead, but that would be a lot more work and I think would just leave the technical debt of potentially hitting this bug with how SchedulePatch is written. 
Added a unit test, and [tested on staging](https://evergreen-staging.corp.mongodb.com/rest/v2/patches/650e02db97b1d3cc9cd2e3da) that the fields weren't erased after updating a description, and were before.
=> EVG-20795 avoid overwriting patch task/variants

model/user/db.go, model/user/user_test.go
EVG-20892
Recent returning interns have had their settings wiped when offboarded which caused them to use the old ui when they returned. This prevents that issue in the future by setting the spruce UI setting when offboarding a user.
Unit tests
=> EVG-20892 Set users setting for spruce UI when clearing them

model/distro/aliases.go
EVG-21066
From the ops-alerts channel, we panicked appending the distro aliases. Seems like this could happen if a distro was deleted?
=> EVG-21066 catch error finding distro

model/project.go
EVG-19725
[Splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20EVG-19725&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1696996800&latest=1697083200&display.events.timelineEarliestTime=1697054400&display.events.timelineLatestTime=1697058000&sid=1697057289.828061) shows there's [a single case](https://github.com/evergreen-ci/evergreen/blob/4f0849f6a717202b7fc5ba8de25b81422a175e3f/model/lifecycle.go#L1154) where `IsGroup` is being used incorrectly. `buildVarTask` is a task within a task group, but `GetTaskNameAndTags` only handles task groups, not tasks within task groups. I filed EVG-21068 for that issue, and added a bit more logging to ensure that my understanding of the bug is correct.
Once I have …
=> EVG-19725: add more logging for IsGroup and GitHub checks alias

docs/API/REST-V2-Usage.md
From slack thread, this should be clearer. Also ticketed doing something about this route.
To view file: https://github.com/evergreen-ci/evergreen/blob/2cfd38efa32c83ffbb79333d41e18382d3412d17/docs/API/REST-V2-Usage.md#notifications
=> docs: clarify slack notification recipient formatting

docs/Project-Configuration/Project-Commands.md
EVG-21075
This would prevent task authors from seeing the underlying issue or bug in their usage of the script.
docs only
docs only
=> EVG-21075 Remove recommendation to redirect ssh stderr to /dev/null when checking outcome of host.list

graphql/version_resolver.go, model/version.go, repotracker/repotracker.go, trigger/process.go, trigger/process_test.go, trigger/project_triggers.go
EVG-20987
This PR is a required precursor to [this Spruce PR](https://github.com/evergreen-ci/spruce/pull/2098). 
Spruce's construction of links pointing to upstream triggers is dependent on the [UpstreamProject](https://gist.github.com/hadjri/a00d402d3f674bf0301cfe0752b71a48#file-version_resolver-go-L374) resolver, which requires both `TriggerType` and `TriggerID` to be populated for the downstream version. For downstream versions triggered by builds / tasks, this TriggerID is set to the upstream task ID or upstream version ID respectively, but for push level triggers there is no Spruce page that can be associated with a github commit so prior to this change `TriggerID` was empty.
I've made a change to assign the upstream project ID as the `TriggerID` when creating versions from push …
=> EVG-20987 Add push trigger sha to version doc

model/dependency.go, model/lifecycle.go, model/lifecycle_test.go, model/project.go, model/project_parser.go, model/project_test.go, validator/project_validator.go, validator/project_validator_test.go
EVG-19725
Follow-up from #7133 and #7125 to complete the transition away from `IsGroup`'s double meaning by splitting into `IsGroup` and `IsPartOfGroup`.
* Only set `IsGroup` if it's representing a task group. Use `IsPartOfGroup` when checking a task in a task group.
* Remove temporary logs.
* Update doc comments to clarify when a task unit can represent a task group vs. a task in a task group.
* Monitored prod for usages, they all seemed to align with my understanding.
* Updated tests.
N/A
=> EVG-19725: do not set IsGroup for a task in a task group

agent/command/git_test.go, config.go, go.mod, go.sum
EVG-20984
Some tests manually check the index of many items in a slice when the test itself only cares about the order in which the elements in the slice appear. This rewrites some tests to use a couple utility functions in our utility package that don't care about the index but care about the order in which the elements appear. 
I groomed through some of our other tests (by searching for tests that use a high index) and I didn't find many other tests that take a similar anti-pattern of checking index + order but only require order, so the scope of tests that changed were only in one file.
Existing unit tests and unit tests in utility package for the utility functions used.
=> EVG-20984 Update to latest utility package and replace some tests with utility function

docs/Containers/Container-Tasks.md
Per our slack [discussion](https://mongodb.slack.com/archives/G0140JMM73N/p1697659855876299), updating some wording on the doc to make it less likely to scare users away while still being clear that the feature is new, subject to change, and not likely suited for critical workflows until it matures further.
=> docs: change wording on container task warning section

docs/Project-Configuration/Project-Commands.md
EVG-20851
Adds documentation to s3.put on how to ensure task-uploaded files are viewable in Parsley
=> EVG-20851 Add task uploaded file in parsley documentation to s3.put

agent/command/results_xunit.go, config.go, docs/Project-Configuration/Project-Commands.md
EVG-20973
This caused some user confusion in the past -- we log about number of files but use the number of logs, which makes it seem like we didn't successfully find the file.
Added a line about logs only being generated in the failure case, since we say that in our own comments but not in the logs, and this also confused the user.
=> EVG-20973 fix attach.xunit_results log about logs

validator/project_validator.go, validator/project_validator_test.go
EVG-19763
Refactored the warning validations to respect the [override hierarchy](https://docs.devprod.prod.corp.mongodb.com/evergreen/Project-Configuration/Project-Configuration-Files#task-fields-override-hierarchy) for requester-level settings by checking the merged `BuildVariantTaskUnit` rather than the non-merged `ProjectTask `
Added a new unit test that checks for all 3 of the levels described here to be respected when checking requester level fields like patchable, patch_only, etc.
=> EVG-19763 Validate requester-level fields with override hierarchy

model/project.go, model/project_parser.go, model/project_parser_test.go
EVG-20948
This adds the  ‘create_check_run’ field to the build variant task unit, and validates the parameters. This will allow users to specify it in their yamls like so: 
Added tests
-  Some things changed and we decided not to support users passing in credentials as part of this project 
- I played with it some more and decided against adding validation to check if the path field is provided. Doing so won’t protect against instances where someone just adds `create_check_run:` and nothing else because then it’s null and validation doesn’t kick in. It only picks it up when another field is specified, such as  
```
create_check_run:
github_app_id: "some_id"
``` 
However, for the case when another field is provided we can just not make the path a pointer and it’ll be set to “” …
=> EVG-20948 Add ‘create_check_run’ field and validate parameters

rest/route/agent.go
EVG-17647
Since the host idle data job was refactored directly into the start task route as part of #6214 , rather than creating a new cron job to collect idle pod data, this change instead:
- Refactors start task logging to support pod and host tasks
- Uses the time since the ECS pod gets created (reflected by `TimeInfo.Starting`) rather than doing anything extra to calculate the idle time between tasks as we do for hosts, because one pod only ever runs one task and is then immediately decommissioned
=> EVG-17647 Include seconds since pod creation in start task logs

agent/command/s3_get.go, agent/command/s3_get_test.go, config.go, docs/Project-Configuration/Project-Commands.md
EVG-19801
First commit is the same, second fixes the panic.
The main change is tested in the original PR; the panic change is untested since it's harder to hit but we may be able to unit test this in the future ([DEVPROD-1746](https://jira.mongodb.org/browse/DEVPROD-1746), [DEVPROD-1747](https://jira.mongodb.org/browse/DEVPROD-1747))
=> EVG-19801 add optional param to s3.get

docs/Project-Configuration/Github-Integrations.md, docs/decisions/2023-11-01_reduce_unwanted_skip_ci.md, rest/route/github.go
DEVPROD-964
Some Dependabot PRs were not running Evergreen PR tests because the PR description occasionally happened to include the label `skip ci` in the commit list (I didn't type out the actual `skip ci` label or else Evergreen will skip CI testing on this PR...). For example, in [this PR](https://github.com/evergreen-ci/spruce/pull/1985), if you toggle the commit list, you'll see one of the commits in the upgrade has the `skip ci` label, so Evergreen skips CI testing for the Dependabot PR (even though `skip ci` was only intended for the dependency repo's testing, not ours).
I considered removing the ability to put `skip ci` in the description since it could be very ambiguous (using the PR description to skip CI is not something that I've seen other CI system offer, likely for this …
=> DEVPROD-964: fix ambiguous skip CI interaction with Dependabot PRs

config_repotracker.go
The smoke test's cached admin settings are [set in a YAML when loading the app server](https://github.com/evergreen-ci/evergreen/blob/26a9c74fb94c21556995b848c5ae9fd6b4a20192/smoke/internal/testdata/admin_settings.yml#L79-L81), but they weren't being respected because the YAML tags on the repotracker didn't match. I made the YAML tags match the existing BSON/JSON ones.
I verified that changing the YAML tags doesn't affect any other test, only the repotracker for the smoke test.
Ran a patch and verified that the app server logs said searched the now-correctly-configured number of revisions.
=> DEVPROD-705: fix YAML tags on repotracker settings

docs/Project-Configuration/Project-and-Distro-Settings.md
Updating the project triggers docs to mention the new trigger level. Also added an entry for status as it was missing.
=> Docs: Update project triggers to mention push triggers

self-tests.yml
[DEVPROD-1717](https://jira.mongodb.org/browse/DEVPROD-1717)
Let's go to 7.0 in test in advance of upgrading the db to 7.0. Upgrade mongosh while we're at it.
Spruce PR to follow.
I'll add tests from each variant to this PR's patch.
=> DEVPROD-1717 upgrade the db version

model/project_ref.go, model/project_ref_test.go
DEVPROD-948
- `FindMergedProjectRef` should return a merged list of repo- and project-level Parsley filters (similar to how variables are merged) instead of the default "if null then use repo settings" pattern
- Update unit test
N/A
=> DEVPROD-948: Return repo level filters with project

model/task/task.go, taskoutput/test_log.go
DEVPROD-2230
This line panics because test logs can sometimes be nil so this just adds a check.
=> DEVPROD-2230 Add nil check for taskoutput

rest/route/task_generate.go, units/crons.go, units/crons_event_test.go, units/crons_remote_fifteen_second.go, units/crons_remote_minute.go, units/event_notifier.go, units/generate_tasks.go, units/provisioning_create_host.go
[DEVPROD-69](https://jira.mongodb.org/browse/DEVPROD-69)
This is the same as what we did with the 15 seconds jobs in https://github.com/evergreen-ci/evergreen/pull/6917. I'm particularly excited to see if there's an effect on the amboy db's performance as a result of batching the insertion of jobs to process events.
In staging a task sent a notification when it finished.
=> DEVPROD-69 PutMany for minutely jobs

rest/route/service.go
DEVPROD-1958
Since #7199 has been deployed and the agents have rolled over, we can delete the duplicate routes as they are not used.
Verified in Honeycomb that agents have rolled over to the new version.
N/A
=> DEVPROD-1958: remove duplicate agent routes

docs/API/REST-V2-Usage.md, rest/route/user.go
DEVPROD-1450
This PR does three things
1. Finish documenting the routes. I'm not sure why I thought the remaining couldn't be documented.
2. Remove the use-case guide. I think these notes are redundant and not useful.
2. Remove the right-side table of contents. I think this makes the screen busy, and squeezes the contents horizontally.
You can view the results in [staging](https://docs.devprod.staging.corp.mongodb.com/evergreen/API/REST-V2-Usage/), and compare it to [production](https://docs.devprod.prod.corp.mongodb.com/evergreen/API/REST-V2-Usage/).
=> DEVPROD-1450 Finish generated docs

trigger/build.go, trigger/task.go
DEVPROD-961
As frequently happens, caching only some statuses makes it easy to have bugs happen -- because we're caching these task docs to be used wherever, and task docs aren't large, there's no reason to just grab some statuses.
Also used the correct GetDisplayStatus, as referenced by Kim in the ticket comment. Not too important if all statuses are caught by the "toHumanSpeak" since there's a catch all.
=> DEVPROD-961 improve build notification failed task attachments

thirdparty/github.go
DEVPROD-957
100 was too small a page limit here; increasing to something larger. I'm hesitant to say we should need pagination here; I don't expect us to have so many installations that we can't handle it in a call. 
No testing needed
=> DEVPROD-957 increase GitHub installation page limit

rest/route/host.go, units/deco_host_notify.go
DEVPROD-2285
Makes Decomissioned Host tickets go to the DEVPROD Jira project (Setting will be updated in admin settings)
Assigns to the runtimeEnvironments team
https://jira.mongodb.org/browse/DEVPROD-2474
cc @brooookemiller
=> DEVPROD-2285 Create Decomissioned Host tickets in DEVPROD project

model/testdata/project.yml
DEVPROD-982
Currently we use an external repo for some tests, this is the first step in removing it (second step is pointing to the commit hash that this creates on main)
TBA in a 2nd PR after a commit hash is created with this project yaml in main
=> DEVPROD-982 Add project yaml to replace external repository in tests

makefile
DEVPROD-2483
This does 2 things:
1. Put swaggo's invocations on a single line, because "If you specify several
goals, make processes each of them in turn, in the order you name them"
([source](https://www.gnu.org/software/make/manual/html_node/Goals.html)).
2. Use `$(MAKE)` instead of `make`. This is the canonical way of calling `make`
recursively, and forwards `-n`, making the output more pleasant to use.
I ran the commands locally.
=> DEVPROD-2483 Fix up makefile for swaggo

model/task_lifecycle.go, model/task_lifecycle_test.go
DEVPROD-959
`ClearAndResetStrandedContainerTask` and `FixStaleTask` redundantly update the blocked dependencies of the task, because their following logic will always either:
1. update the blocked dependencies again in the end task logic
2. immediately reset the task, which renders updating blocked dependencies unnecessary.
`ClearAndResetStrandedContainerTask` already has cases that check for proper behavior of blocked task dependencies, but added them to the test cases for `FixStaleTask`.  I also did check that commenting out the end task logic where blocked dependencies get updated causes the tests to fail.
=> DEVPROD-959 Remove UpdateBlockedDependencies from stale/stranded task cleanup

docs/Project-Configuration/Best-Practices.md, docs/Project-Configuration/Project-and-Distro-Settings.md
DEVPROD-137
We needed to cross reference the internal wiki and the evergreen docs. It was decided to specifically link the best-practices page and Project-and-Distro-Settings page
I pulled down pine, changed config.yml, make website-build ; make website-serve
This is a docs change
=> DEVPROD-137 add wiki reference for distro guidelines

docs/Project-Configuration/Merge-Queue.md, model/patch/github_merge.go, model/patch/github_merge_test.go, model/patch_lifecycle.go, model/patch_lifecycle_test.go, model/project_test.go, service/api_patch.go, thirdparty/github.go, units/patch_intent.go
DEVPROD-2494
This adds the title of the HEAD PR to merge queue versions.
Edited the unit test for the title.
Added some docs and comments because the behavior is useful but potentially
confusing.
=> DEVPROD-2494 Add title to GitHub merge

config.go, docs/Project-Configuration/Project-Commands.md, docs/Project-Configuration/Project-Configuration-Files.md, model/project.go, operations/patch_module.go
DEVPROD-1000
`set-module` actually does already work the way that was requested in the ticket (as it will [override](https://gist.github.com/hadjri/a061cb18107bd6043cb91da240ccf223#file-git-go-L686-L711) the manifest module revision if it exists), with the caveat that a diff must be staged on the module repo first. 
I don't see any issue with allowing empty module patches as we already allow empty regular patches, so I allowed set-module to allow a patch to use the user's local checked out module revision regardless of a diff present.
Also deleted a block of unused code that I stumbled across for a struct that we don't ever save to the DB
Ran `evergreen -c ~/evergreen-staging.yml set-module -m evergreen -i 6551caf69dbe328b3cf21b34` in staging with no staged evergreen changes for a sandbox …
=> DEVPROD-1000 Allow empty set-module patches

model/task_lifecycle.go
DEVPROD-712
Follow-on from #7229.
I read through the Splunk logs post-deploy and most of the display task update races are due to the fact that the execution tasks tend to all start around the same time and fight to update the display from undispatched -> dispatched -> starting (because the execution tasks start very soon after being dispatched). To reduce the update conflicts, I optimized it a little bit with the following reasoning - if the updated status is anything _other than_ undispatched _and_ the updated status is what's already in the DB, the update will succeed without needing to try again (because the update won't change the status anyways).
For updating to undispatched, we can't apply the above reasoning about the status update because an undispatched display task must also …
=> DEVPROD-712: allow display task updates if the updated status matches the current status

github_app.go
DEVPROD-2669
Erroring on no documents causes new repos to never cache installation IDs
=> DEVPROD-2669 Update getInstallationIDFromCache to not error on no documents

model/task_lifecycle_test.go
DEVPROD-1966
The test was triggering the race detector because `UpdateDisplayTaskForTask` was called on the same underlying task, and created a race to set the cached display task. This only affects the goroutine setup in the test, the update logic itself wouldn't have multiple goroutines modifying the same execution task.
Ran the race detector locally a bunch of times and scheduled it in the PR patch.
N/A
=> DEVPROD-712: fix race in display task concurrency test

docs/Project-Configuration/Project-Configuration-Files.md
DEVPROD-962 
Realized that the behavior I'm seeing is actually what I see elsewhere in the docs, namely that we take an _intersection_ of all the criteria in the variant. So it's the example case we gave that was broken rather than the feature itself.  This matches the behavior I saw while testing.
Doc change only
=> DEVPROD-962 clarify dependency space-separation logic

agent/command/git.go, config.go
DEVPROD-2665
The one project that used an https url for modules switched over to specifying an owner/repo, and our docs no longer show an https example (removed in [7191](https://github.com/evergreen-ci/evergreen/pull/7191/files)). We therefore no longer need to support it.
=> DEVPROD-2665 Deprecated https urls for modules

model/event/subscriptions.go, trigger/task.go, trigger/task_test.go
DEVPROD-981
This allows projects to set up notifications for a task succeeding a duration only if the task is successful. 
Tested on staging 
The UI change to add the option to the dropdown will be merged after this backend change is merged. 
PR: [2155](https://github.com/evergreen-ci/spruce/pull/2155)
=> DEVPROD-981 Support notifications when SUCCESSFUL task exceeds some duration

config.go, operations/flags.go, operations/validate.go
DEVPROD-759
adds a flag to evergreen validate to treat warnings as errors
Tested locally
`❯ evgs validate self-tests.yml
[evergreen] 2023/11/20 01:36:24 [p=warning]: Couldn't find configuration file, falling back on default.
Couldn't find configuration file, falling back on default.
WARNING: no project specified; validation will proceed without checking project settings
WARNING: no project specified; validation will proceed without checking alias coverage
self-tests.yml is valid with warnings`
`❯ evgs validate -w self-tests.yml
[evergreen] 2023/11/20 01:36:33 [p=warning]: Couldn't find configuration file, falling back on default.
Couldn't find configuration file, falling back on default.
WARNING: no project specified; validation will proceed without checking project settings
WARNING: no …
=> DEVPROD-759 Add error on warnings flag to evergreen validate

model/project_ref.go, model/project_ref_test.go, rest/data/project_settings.go, rest/data/project_settings_test.go
DEVPROD-1771
This is just tech debt cleanup. Moving the validation logic to the respective function and keeping the save function clean of all validating.
Existing unit tests and TBA testing on stage to make sure validation still functions as expected.
=> DEVPROD-1771 Separate all validation and saving in to their respective functions

agent/logging_test.go
DEVPROD-2652
This fixes `test-agent` on windows where an open file descriptor prevents the task directory from getting cleaned up.
[Passing unit tests on windows.](https://spruce.mongodb.com/version/655d11de32f417fe8e5144dd/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
N/A
=> DEVPROD-2652: close task logger after testing file logger

docs/Project-Configuration/Project-and-Distro-Settings.md
DEVPROD-769
We don't have a doc section for this, so adding something small. I thought about adding screenshots and etc but I don't think we should need that -- these are small enough that the page itself should be explanatory, and that increases the risk of things getting outdated, so keeping it simple.
=> DEVPROD-769 add doc change for project page flags

docs/Project-Configuration/Task_Traces.md
On GitHub, this link previously expanded to https://github.com/evergreen-ci/evergreen/blob/main/docs/Project-Configuration/Project-Configuration/Project-Configuration-Files.md#default-expansions, which is incorrect.
=> [doc] Fix link to default expansions and remove whitespace in Task Traces doc

agent/command/testdata/plugin_s3_copy.yml, globals.go, model/project_matrix_test.go, validator/distro_validator.go
DEVPROD-753
Nobody uses 32-bit architecture distros anymore, so we can delete this.
=> DEVPROD-753 Remove 32-bit Windows and Linux architecture options

agent/command/host_create.go, agent/internal/client/base_client.go, config.go
DEVPROD-963
- Fix error where `GetDockerStatus` panics on a nil error (which is already handled in earlier logic)
- Fix error noticed along the way where the host Id is nil for `GetDockerStatus` causing the request to always fail because its format is always `/rest/v2/hosts//status`
Confirmed the command [panics](https://evergreen-staging.corp.mongodb.com/task_log_raw/sandbox_ubuntu2004_unit_tests_patch_d631380317a8478b879cc27d6171508dea2b11df_6566317497b1d30a5e2119dd_23_11_28_19_19_38/0?type=T#L38) without the change, and [no longer panics ](https://evergreen-staging.corp.mongodb.com/task_log_raw/sandbox_ubuntu2004_unit_tests_patch_d631380317a8478b879cc27d6171508dea2b11df_6566561c97b1d31bc0262a66_23_11_28_21_05_44/0?type=T#L37)with the change (though now checking for docker logs times …
=> DEVPROD-963 Remove panic from docker status err status code

docs/Project-Configuration/Project-and-Distro-Settings.md, model/version.go, repotracker/repotracker.go, repotracker/repotracker_test.go, rest/route/agent.go, trigger/process_test.go, trigger/project_triggers.go
DEVPROD-2921
- When triggering a downstream patch via upstream push, set the downstream patch's manifest to the revision of the upstream project push, if the upstream project is a module of the downstream project.
- Refactored CreateManifest to just take in a list of modules for simplicity.
Note: While this would be doable by adding `auto_update: true` to the module in YAML, it would also mean that it would no longer be possible for users to make patches off of old versions in a way that replicates the old version's behavior fully, as its module would pull from the most recent revision rather than the module revision that existed at time of the base revision.
Confirmed [before](https://spruce-staging.corp.mongodb.com/version/sandbox_6d59ba219b13b10cce97beec439977bc88639aa6_c6db985b8c9ffb23 …
=> DEVPROD-2921 Use SHA of push trigger if it is a module of the downstream project

docs/Project-Configuration/Project-and-Distro-Settings.md
DEVPROD-762 
We renamed this UI section to Ticket Creation, and these tickets are no longer strictly build failure. 
Also added docs that we didn't have before.
=> DEVPROD-762 remove doc mentions of build baron / build failure

agent/command/git.go, agent/command/git_test.go, config.go
DEVPROD-732
The server was temporarily using `clone_params` to pass special git CLI flags to try making clones faster but apparently, it didn't work out. Since we never documented this and it was only used for that one experiment, we can remove it now.
Existing git.get_project tests should pass.
N/A - This parameter was never documented.
=> DEVPROD-743: delete clone params

service/templates/admin.html
[DEVPROD-2473](https://jira.mongodb.org/browse/DEVPROD-2473)
https://github.com/evergreen-ci/evergreen/pull/7292 removed the amboy username/password setting from the db but neglected to remove the setting from the admin page. This PR removes it.
=> DEVPROD-2473 remove amboy db user/password setting

model/task/generated_json_storage.go, rest/data/generate.go, rest/route/patch_test.go, rest/route/task_generate.go, rest/route/task_generate_test.go, service/templates/admin.html, units/generate_tasks.go, units/generate_tasks_test.go
DEVPROD-1758
Follow-up from #7287 to allow a task to submit input JSON files larger than 16 MB to generate.tasks. If the input file can be stored in the task collection document, it'll do that (same as how it has always done it). Otherwise if it's too large to put in a DB document, it'll be stored in S3.
* Integrate the logic from the original PR into generate.tasks.
* Fix a couple small bugs in the logic from the original PR.
* Add admin setting to UI for generated JSON S3 prefix.
* Added unit and integration tests.
* Tested in staging to verify that [a sample patch](https://spruce-staging.corp.mongodb.com/task/evg_lint_generate_lint_patch_3c10c5e814535dc8e6d06553cce69a60e4f58c91_6573926197b1d3283b562278_23_12_08_22_02_10/logs?execution=0) used S3 to store the file when the generated …
=> DEVPROD-1758: support large JSON files for generate.tasks

docs/Project-Configuration/Project-Configuration-Files.md
[Slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1702404548148869)
Change the wording a bit to make it clearer that the version manifest only appears in Spruce when there are modules defined.
=> docs: clarify version manifest behavior when no modules are defined

docs/Hosts/Developer-Workstations.md, docs/Project-Configuration/Project-and-Distro-Settings.md, docs/Project-Configuration/Task-Runtime-Behavior.md
A user asked some questions about how to set up a project for workstations, so I added some clarification.
* Add more links to make it clearer on how to use workstation commands defined in the project settings.
* Fix a couple links (that I wrote) that hard-code the link to the docs website rather than use relative paths.
=> docs: add more links for workstation commands

agent/command/host_create_test.go, apimodels/agent_models.go, config_cloud.go, docs/Project-Configuration/Project-Commands.md, rest/model/admin.go, rest/route/admin_banner_test.go, rest/route/task_test.go, service/templates/admin.html
DEVPROD-714
The agent validates the user's host.create inputs, but if the user uses Docker host.create without specifying a distro, it will fail because the validation logic tries to query the admin settings, even though the agent doesn't have access to the DB. Rather than try to fix a very small convenience feature and given the fact that the default distro is blank in both staging and prod, I decided it's better to remove the default distro and have the user always specify one for Docker host.create.
It's never explicitly stated how the `distro` parameter to host.create interacts with Docker, so I clarified the wording so the user knows they have to give a distro for Docker host.create.
=> DEVPROD-714: remove default distro setting for Docker host.create

model/event/host_event.go, model/host/db.go, model/host/host.go, model/host/host_test.go, rest/data/host.go, rest/data/host_create.go, scheduler/scheduler.go, trigger/host_spawn.go, units/migrate_volume.go, units/migrate_volume_test.go, units/provisioning_user_data_done.go
Reverting because it's causing us to hit [fetching data for event '%s' (resource type: '%s', event type: '%s')](https://github.com/evergreen-ci/evergreen/blob/main/trigger/process.go#L35)
Reverts evergreen-ci/evergreen#7313
=> Revert "DEVPROD-979: terminate spawn hosts that fail to spawn"

config_task_limits.go, model/project_parser.go, model/project_parser_test.go, rest/model/admin.go, service/templates/admin.html
DEVPROD-731
add limit for the number of includes users can specify 
local evergreen saves 
unit tests 
staging with low include number to fail
=> DEVPROD-731 Add include limits to admin settings

model/version.go
DEVPROD-3166
The commit queue (both the CLI queue and the PR queue after https://github.com/evergreen-ci/evergreen/pull/7310, unless auto update is set to true, gets the module revision from the base manifest. Instead, we should fetch the latest.
Otherwise, if the module has moved ahead, it can be outdated.
=> DEVPROD-3166 Commit Queue should use the latest module revision 

charts/values.yml, config.go, globals.go
[DEVPROD-2470](https://jira.mongodb.org/browse/DEVPROD-2470)
In Kanopy we won't want to log to stdout since that'll just land up in Splunk and we already have it in Splunk 😄 .
There's maybe a marginal benefit to having the logs go to Splunk from stdout since there the Kanopy control plane is handling sending the logs so maybe even if our logs don't make it to Splunk those will, but the volume of logs would probably make it prohibitive. Fallback logs (when sending to Splunk/Slack) will still go to stderr and end up in Kanopy splunk.
In staging application logs went to [our Splunk index](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen-staging%0A%7C%20stats%20count%20by%20host&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_ …
=> DEVPROD-2470 skip stdout logging

model/patch_lifecycle.go, model/patch_lifecycle_test.go
DEVPROD-3092
[This logic](https://github.com/evergreen-ci/evergreen/blob/main/model/project_parser.go#L692-L726) for processing the includes of a version uses workers/goroutines that can potentially run in multiple parallel threads on the same machine.
For patches that change a large number of included files at once, this is problematic as the same directory on the app host can get [cleaned](https://github.com/evergreen-ci/evergreen/blob/main/model/patch_lifecycle.go#L424) before another goroutine has the chance to later apply its [patch command](https://github.com/evergreen-ci/evergreen/blob/main/model/patch_lifecycle.go#L448), resulting in flaky errors like this:
```
error: etc/evergreen_yml_components/variants/in_memory.yml: No such file or directory
```
Since getting files serially …
=> DEVPROD-3092 Use unique directory for app server patch application

globals.go
No ticket, since this is a minor comment change.
The ad_hoc version requester is used both by triggers *and* by the create version endpoint, which was confusing at first when I was considering opening a ticket about improving the create version endpoint, so I wanted a couple words to the comment.
N/A
N/A
=> Fixup: Document ad_hoc as also for create version API

agent/agent.go, agent/agent_test.go, config.go
DEVPROD-3230
The shouldKill function relies on the taskConfig to know if the task is not part of a taskgroup and should therefore kill processes. If makeTaskConfig fails, the taskConfig will be nil, and then when it eventually get's to a.shouldKill() via handleSetupError, it will panic when it tries to check tc.taskConfig.TaskGroup. 
There's no good way to test this, and the changes are simple enough so I think we are okay without it.
=> DEVPROD-3230 Fix shouldKill panics when makeTaskConfig errors 

model/event/host_event.go, model/host/db.go, model/host/host.go, model/host/host_test.go, rest/data/host.go, rest/data/host_create.go, scheduler/scheduler.go, trigger/host.go, trigger/host_spawn.go, units/migrate_volume.go, units/migrate_volume_test.go, units/provisioning_create_host.go, units/provisioning_user_data_done.go
DEVPROD-979
This is the same as #7313 except:
* I changed the host trigger processor to deal with the fact that intent hosts are deleted and re-inserted into the DB (with a different `_id`) when the host starts in EC2. A host event's resource ID could be either its intent host ID (i.e. the original `_id` for the host) or its EC2 instance ID (i.e. the new `_id` after the host doc is replaced), so it now handles both interchangeably.
* I changed it to log a new event type (`HOST_CREATED_ERROR`) instead of reusing the existing event type (`HOST_CREATED`). This is a small optimization to reduce the amount of events that the notification system has to process. Instead of having to process all host created events (1 per host), it only processes host creation errors (which only happen if the …
=> DEVPROD-979: terminate spawn hosts that fail to spawn

docs/Project-Configuration/Project-Configuration-Files.md, units/github_status_api.go, units/patch_intent.go
DEVPROD-766
For PRs with only ignored changes, changed the Github check status sending logic to report success for all evergreen-specific branch protection rules, instead of just for `evergreen`.
Configured sandbox to have 3 required checks:
- evergreen
- evergreen/evg
- evergreen/ubuntu2204-small
Confirmed that before this change, an ignored PR [only reports passed for evergreen](https://github.com/evergreen-ci/commit-queue-sandbox/pull/625), but after this change, an ignored PR [reports all checks as passed](https://github.com/evergreen-ci/commit-queue-sandbox/pull/632).
Slightly updated doc wording
=> DEVPROD-766 Send success for all branch protection rules for ignored PRs

graphql/tests/task/taskLogs/results.json, graphql/tests/task/taskLogs/task_output_data.json
[DEVPROD-3423](https://jira.mongodb.org/browse/DEVPROD-3423)
[task_logs_all.graphql](https://spruce.mongodb.com/task/evergreen_ubuntu2204_test_service_graphql_patch_adb6e7ef31c0deda9b9b7bc520d389e4f7d91911_659495f9306615d965b72326_24_01_02_23_02_20?execution=0&sortBy=STATUS&sortDir=ASC) sometimes fails because these two log lines are out of order. It seems that the reason is that they have identical timestamps so the order depends on the order of keys in the iterator map, which is supposed to be non-deterministic.
Hopefully the test continues to pass.
=> DEVPROD-3423 use easier timestamps

config.go, environment.go, environment_test.go, thirdparty/github_test.go
DEVPROD-1943
Fixes two issues with the GitHub status sender:
* Ensure GitHub app tokens are refreshed well in advance of when they actually expire. GitHub senders are cached to reduce the amount of tokens requested, but the TTL is currently set to the same duration as the token's total lifetime (1 hour). This would cause very occasional flakes when using a token that's close to expiring. For example, if Evergreen is trying to send a GitHub status back to a PR but the sender it got back had a token that was going to expire in 1 millisecond, it would use the almost-expired sender, the token would expire, and GitHub would reject the request.
* The GitHub status sender didn't set the fallback error handler like the rest of the senders do, so it wouldn't send errors to Splunk. Any errors …
=> DEVPROD-1943: do not use expired tokens for GitHub status sender

docs/Project-Configuration/Project-and-Distro-Settings.md
The URL was translated weirdly in the rst->md transition, so it should look as expected now.
Verified in a markdown viewer that it looks good.
=> docs: fix formatting on GitHub check URL

docs/Project-Configuration/Project-Configuration-Files.md
DEVPROD-2255
While these links were working in the github viewer, they weren't working on the docs site because they were resolving to `/CLI.md#operating-on-existing-patches `instead of `/CLI#operating-on-existing-patches. `
This is hard to test completely, but in the viewer, the link opens to `https://github.com/evergreen-ci/evergreen/blob/main/docs/CLI/#operating-on-existing-patches`, so I am guessing this will solve the issue by opening `https://docs.devprod.prod.corp.mongodb.com/evergreen/CLI#operating-on-existing-patches` once it's deployed.
=> DEVPROD-2255 Fix broken doc links 

agent/agent.go, agent/agent_test.go, config.go
DEVPROD-3230
This reopens https://github.com/evergreen-ci/evergreen/pull/7334 with a fix. The first four commits are from the original PR. The last commit is new. 
I would have loved for this to be a mysterious quirk or an elusive bug, but alas, it is not. It was an `||` in place of an `&&`.
=> DEVPROD-3230 Agent hitting repeated panics after outage

graphql/generated.go, graphql/schema/types/distro.graphql, graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql, graphql/tests/mutation/saveDistro/queries/save.graphql, graphql/tests/mutation/saveDistro/results.json, graphql/tests/query/distros/queries/distro.graphql, graphql/tests/query/distros/results.json, model/distro/distro.go, rest/model/distro.go
DEVPROD-782
- Add boolean field indicating distro is admin-only. Linked tickets will add this field to distro settings and hide it from user-facing menus across Spruce.
- Updated unit tests
N/A
=> DEVPROD-782: Add adminOnly distro field

agent/command/git.go, config.go
DEVPROD-1931
This has been reverted in the past because DSI had broken module dependencies. 
They have since fixed the issue so we are now (presumably) safe to error on module clone failure.
=> DEVPROD-1931 Error on module clone failure

thirdparty/github_test.go
DEVPROD-3615
This fix uses a user that is in the organization. An argument can also be made to remove this test now. More information in the ticket. 
The test itself.
=> DEVPROD-3615 fix test-thirdparty on Ubuntu 22.04

graphql/tests/task/taskLogs/results.json, graphql/tests/task/taskLogs/task_output_data.json, model/log/basic_iterator.go, model/log/chunk.go, model/log/chunk_iterator.go, model/log/iterator_interface.go, model/log/iterator_test.go, model/log/merging_iterator.go, model/log/reader_test.go, model/log/service_interface.go, model/log/service_test.go, model/log/service_v0.go
DEVPROD-2717
- Merge logs deterministically in the Evergreen logger
- Revert changes from https://github.com/evergreen-ci/evergreen/pull/7359 (we want repeating timestamps in these tests so we know lines from different logs are merged deterministically) 
- Fix a bug where the merging iterator was not respecting the line limit and tail options passed in to `LogService.Get`
- Refactor and enhance existing testing as well as add new tests
Added and updated unit tests.
N/A
=> DEVPROD-2717: Merge logs deterministically

agent/command/assume_ec2_role.go, docs/Project-Configuration/Project-Commands.md
DEVPROD-2783
The external_id field is not set by the user.
=> DEVPROD-2783 Fix ec2.assume_role docs

docs/Project-Configuration/Project-and-Distro-Settings.md
Using backslash in markdown isn't generally the right approach and in most cases (including this one), it renders the backslash as-is, so I removed them. The random backslashes should no longer appear in this case.
=> docs: fix angle brackets in git tag format

docs/API/REST-V2-Usage.mdx, self-tests.yml
DEVPROD-3716
It seems that indentations and triple backticks are not created equal for code blocks in MDX 3, so I made this change in our single MDX file.
Confirmed that Pine builds locally with Docusaurus v3 once these changes are made!
=> DEVPROD-3716 (Part 2): Convert indentation to triple backtick for code blocks

docs/Project-Configuration/Project-and-Distro-Settings.md
DEVPROD-932
This is just to make the list be in the same order as Spruce project settings page. As well as renaming 'definition file' to 'config file' to be more consistent with what we call it in other places (I haven't seen definition file anywhere else...)
EDIT: here is [the spruce PR ](https://github.com/evergreen-ci/spruce/pull/2222)that affects what the ticket is targeted towards
=> DEVPROD-932 Consistent naming for config in project trigger docs

docs/Project-Configuration/Notifications.md, docs/Project-Configuration/Project-and-Distro-Settings.md
DEVPROD-3140
* Clarify that the notifications section in the docs is for user notifications.
* Add docs and links to project-level notifications.
Checked the rendered Markdown looked reasonable.
=> DEVPROD-3140: document notifications in project settings

config.go, docs/Project-Configuration/Commit-Queue.md, operations/commit_queue.go
DEVPROD-761
A user was attempting to specify commit-sha for a different repository than the project they were using it on, which caused the sha not to be found
=> DEVPROD-761 Specify backport commit-sha option only allows from same github project

model/project_parser.go
DEVPROD-3733
Noticed it in a user thread. Use the build variant name in the error message (instead of the build variant task unit's name).
Didn't seem worth testing a tiny error message bug.
N/A
=> DEVPROD-3733: fix error message for conflicting definitions

config.go, operations/version.go, self-tests.yml
[DEVPROD-3473](https://jira.mongodb.org/browse/DEVPROD-3473)
Add an option to the `evergreen version` command to print the BuildRevision. This is necessary for [the deploy emails PR](https://github.com/evergreen-ci/evergreen-deploys/pull/2).
Also, the staging only build needs to include linux_arm64 since the apps will be running on arm.
=> DEVPROD-3473 buildrevision version

rest/route/user.go, service/service.go
DEVPROD-678
Documents our 3 service user-specific REST routes via swaggo. Screenshots attached. Will link in the dev guide once merged.
=> DEVPROD-678: Document service user routes

config.go
[DEVPROD-2470](https://jira.mongodb.org/browse/DEVPROD-2470)
https://github.com/evergreen-ci/evergreen/pull/7332 was supposed to make that we don't log to stdout when `disableLocalLoggingEnvVar` isn't set or if it's set to false. There was a mistake in the logic: as is it won't log if it's unset, which isn't what we want.
`make local-evergreen` spits out logs to stdout.
=> DEVPROD-2470 log to stdout again

agent/internal/taskoutput/test_log.go, config.go, self-tests.yml
DEVPROD-3779
Use a `time.Timer` instead of `time.Sleep` to throttle the test log directory watcher loop. This should improve goroutine clean up and avoid leaks.
Also added the `taskoutput` package tests to CI since they never got added. 
Put the `TestTestLogDirectoryHandler` test in a loop and ran it across a bunch of platforms to ensure that it is not flakey.([patch build](https://spruce.mongodb.com/version/65a6b794d6d80a7ced34fbc0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC))
N/A
=> DEVPROD-3779: Use timer instead of sleep for the test log directory watcher loop

agent/internal/task_config.go, agent/task_context.go, config.go
DEVPROD-741
More details in ticket but we were validating task configs twice for no reason other than tests. Should be fine to delete if all tests pass
all existing tests pass
staging works
=> DEVPROD-741 Delete unnecessary validation for task config

trigger/process.go, units/event_notifier.go
DEVPROD-3743
* Add logs for resource ID and resource type in event notifier job to make it easier to trace in Splunk when a resource has its subscriptions/notifications processed (e.g. a task finishes, and that event sends a Slack notification).
* Reduce the noisiness of the event notifier logs when there's no notifications to create from an event.
I verified in staging that the logs for the job have the fields.
N/A
=> DEVPROD-3743: make it easier to trace event logging

rest/route/agent.go, taskoutput/task_output.go
DEVPROD-1723
Add temporary logic to enable the evergreen logger for a single project (evergreen) while the global default logger is set to "buidlogger". Once we are confident that the evergreen logger works in prod, we can set the global default logger to "evergreen" and remove the logic introduced here.
Tested in staging with the mci project.
N/A
=> DEVPROD-1723: enable evergreen logger for a single project

agent/internal/client/base_client.go, config.go, taskoutput/evergreen_sender.go
DEVPROD-1723
This sets the log level and flush interval for the evergreen task logger.
The previous flush interval was set to 15 seconds and the max buffer size 1000 bytes. This uses the default evergreen log sender buffer size of 10MB.
N/A
=> DEVPROD-1723: set log level and flush interval for evergreen task logger

docs/Project-Configuration/Project-and-Distro-Settings.md
DEVPROD-834
Updates docs based on a change that I'm making on the UI.
- evergreen-ci/spruce/pull/2230
=> DEVPROD-834: Update docs for metadata links

config.go, operations/patch.go, operations/patch_util.go
DEVPROD-3739
In order to avoid potential complexity with v7.1 and v7.2 of server (where engineers may run into this error on submitting patches), temporarily downgrading this to a warning. This also requires we revert the [loadGitData](https://github.com/evergreen-ci/evergreen/pull/7311/files#diff-8b8cc6bdad49868ce616124c6c2b682e973c6db9e89111473a319bbefda656a2R624) function change from #7311 with the understanding that it'll need to be added back along with the changes from DEVPROD-3740.
Tested locally and confirmed warning outputs.
In sandbox, I set my local remote and origin to point to my fork, `hadjri/commit-queue-sandbox` rather than the original repo. Confirmed that without this change, the patch fails to be created, and after this change, patch creation succeeds.
(i.e., my locally …
=> DEVPROD-3739: Downgrade incorrect git remote to CLI warning

agent/internal/client/interface.go, agent/internal/client/mock.go, agent/internal/client/timeout_sender_test.go, config.go
DEVPROD-3911
This data race was caused because the mock implementation for `Communicator.GetLoggerProducer` was passing the task pointer into the append line function (after my changes in #7420), which is called to add lines to the in-memory task logs cache by the underlying sender. The agent test suite stores a task and agent struct which are reset on every call to `SetupTest`. If an async agent process is running that accesses the logger producer while the next test is getting set up, the append line function reads the task pointer that has since been written to, hence the data race.
I fixed this by setting a variable with the task's ID and using that in the append line function which, while a safer implementation, masks that these tests are likely leaking goroutines if they are not …
=> DEVPROD-3911: fix data race in agent tests

graphql/query_resolver.go, model/annotations/task_annotations.go, model/context_test.go, model/event/host_event_finder.go, model/host/host.go, model/host/host_test.go, model/lifecycle.go, model/lifecycle_test.go, model/task/db.go, model/task/db_test.go, model/task/task.go, model/task/task_test.go, model/task_lifecycle.go, model/task_lifecycle_test.go, model/user/db.go, model/user/user.go, model/user/user_test.go, rest/route/agent_test.go, rest/route/annotations_test.go, rest/route/host_agent.go, rest/route/task_test.go, rest/route/user.go, trigger/task_test.go, units/check_blocked_tasks.go, units/commit_queue.go, units/commit_queue_test.go, units/provisioning_create_host.go
DEVPROD-810
Removed invocations of app-level context throughout the `model/` directory as indicated in the ticket.
Here were a few that proved too tricky to remove—let me know if they are crucial enough to revisit as part of this fix. I don't know much about how context is created in the application so apologies in advance.
- [`user.GetOrCreateUser`](https://github.com/evergreen-ci/evergreen/blob/812185e19e4e118b685086162c92f9e86ca8d6c6/model/user/db.go#L306) - function signature is defined as in [Gimlet](https://github.com/evergreen-ci/gimlet/blob/e7de42b0623c008a8eeca167a7190edcc364ac51/auth_interfaces.go#L72) so I couldn't add `ctx`
- [`model.GetFailedTests`](https://github.com/evergreen-ci/evergreen/blob/812185e19e4e118b685086162c92f9e86ca8d6c6/model/task_history.go#L236) - only used …
=> DEVPROD-810: Avoid using app-level context for GraphQL queries

agent/command/archive_auto_extract.go, agent/command/archive_auto_extract_test.go, agent/command/archive_zip_extract.go, agent/command/archive_zip_extract_test.go, config.go, docs/Project-Configuration/Project-Commands.md
DEVPROD-777
* Document `archive.auto_extract`, `archive.zip_create`, and `archive.zip_extract` commands.
* Remove some random dead/non-working parameters from the newly-documented archive functions. It looks like they were never implemented, so it's not worth keeping them around.
Smoke test already tests these commands, and it still passes.
=> DEVPROD-777: document missing archive commands

agent/command/s3_copy.go, agent/command/s3_get.go, agent/command/s3_put.go, agent/command/s3_put_test.go, apimodels/s3copy.go, config.go, docs/Project-Configuration/Project-Commands.md, go.mod, go.sum, model/artifact/artifact_file.go
DEVPROD-774
This adds support for passing temporary AWS credentials to S3 commands. I also chose to not allow combining temporary credentials with pre-signed URLs - this is because artifacts with `visibility: signed` can only work if the credentials live forever. URLs are lazily signed only when the user clicks the link in the task artifacts, and the link is only valid for one day. Therefore, if the user tries to click the link after the temporary credentials have already expired, the signing will fail and the user won't be able to access the artifact.
There will be a follow-up PR to add this parameter to Shrub.
* Upgrade Pail to support AWS session tokens.
* Allow temporary AWS session tokens for S3 commands.
* Remove some dead code from pre-signed URL functionality.
* Added unit test …
=> DEVPROD-774: allow AWS session tokens for S3 commands

model/host/host.go
DEVPROD-3943
Add host fields for sleep schedule data model.
These fields don't do anything, so there's nothing to test.
N/A
=> DEVPROD-3943: add data model for host sleep schedule

model/patch_lifecycle.go, model/patch_lifecycle_test.go, model/project_parser.go, model/testdata/include1.yml, model/testdata/renamed_patch.diff
DEVPROD-3085
Currently if you try to submit a CLI patch that changes the name of an included config file, the patch will fail to be created because Evergreen is trying to apply a patch to a file that does not yet exist remotely (because it was just renamed to something else).
Modified the `MakePatchedConfig` logic to detect if the patch includes a rename for the remote file in question, and if so, retrieve the old file name remote config, and apply the patch to that instead.
Added unit tests and test files.
Tested in staging and confirmed that without this change, if I submit a patch with include file name changes I get the following error: `retrieving file for include 'renamed.yml': patching remote configuration file: running patch command (possibly due to merge conflict on evergreen …
=> DEVPROD-3085 Check for renamed includes when creating diff patch

agent/command/perf_send.go, agent/command/perf_send_test.go, agent/internal/client/base_client.go, agent/internal/client/interface.go, agent/internal/client/mock.go, config.go
DEVPROD-2961
Stop sending performance results to the Data-Pipes service from the agent.
This needs to be done before we remove support for Data-Pipes on the Evergreen app (https://github.com/evergreen-ci/evergreen/pull/7456) to avoid breaking running performance tasks after a deploy.
Updated relevant unit tests.
N/A
=> DEVPROD-2961: stop sending perf results to the Data-Pipes service

model/project_ref.go
DEVPROD-1648
Updating the host configure command to use HTTP cloning 
Upon investigation, this is the command what server uses to set up their virtual workstations. 
In theory, having this command use ssh cloning was okay because server setup workflow dictates that they add their own SSH keys before running this command since other workflows may be relying on this, we decided to update this command 
staging
=> DEVPROD-1648 Use HTTP cloning for host configure CLI command

config_amboy.go, config_test.go, environment.go, rest/model/admin.go, rest/model/admin_test.go, service/templates/admin.html, testutil/config.go
[DEVPROD-3861](https://jira.mongodb.org/browse/DEVPROD-3861)
Add another URL for connecting to amboy when the app is running inside Kanopy. This is necessary because it's a different private link and thus a different URL.
It allowed us to set another URL for the instance of evergreen that was running in Kanopy staging.
=> DEVPROD-3861 distinct amboy connection string for Kanopy

model/project_parser.go, repotracker/repotracker.go, rest/route/github.go
DEVPROD-3875
Following up from [DEVPROD-781](https://jira.mongodb.org/browse/DEVPROD-781), this issue has surfaced again where a user was unauthorized to push a git tag which led to this ticket being created at a critical level as it was presumed to be a blocker.
Given that this has come up more frequently recently, this change aims to make this error more visible in the future by:
- creating a stub version for unauthorized git tag versions
- sending an email to the user's email associated with their github account
Confirmed that an unauthorized git tag push results in a [stub version with the relevant error](https://spruce-staging.corp.mongodb.com/version/sandbox_testtag9_65b42ac59dbe32e18f3e268b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and that I got an email (see attached).
=> DEVPROD-3875 Send email upon git tag unauthorized err

rest/route/github.go
DEVPROD-3888
We ran into some issues that seemed to be caused by the request cancelling which most likely happened due to a client-side timeout. 
This will ignore the request context passed into Run for the GitHub webhook route and instead use a custom context with a 60 second timeout. That will ensure that webhook requests are not affected by the original webhook request context cancelling.
=> DEVPROD-3888 Use custom context for GitHub webhook route

agent/internal/task_config.go, agent/internal/task_config_test.go, agent/logging.go, agent/logging_test.go, apimodels/agent_models.go, config.go, config_logger.go, rest/route/agent.go, rest/route/agent_test.go
DEVPROD-4025
- Add a new logger config field `RedactKeys` to hold the patterns we want to look for for key redaction
- Send redact keys with expansions and vars in agent route
- Add any matching project var keys to the private vars list when setting up the task config
- Redact all private vars and selected default vars from logs
Updated unit tests / [tested in staging](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2204_echo_variable_patch_f50345d4c091635680061fecb7f18af636a6bf08_65b7fec097b1d3897105fabe_24_01_29_19_39_01/logs?execution=2).
N/A
=> DEVPROD-4025: Configurable project var redactions

agent/internal/client/redacting_sender.go, config.go
[DEVPROD-4025](https://jira.mongodb.org/browse/DEVPROD-4025)
https://github.com/evergreen-ci/evergreen/pull/7453 caused a panic when a wrapped nil error is logged. We should check the message is loggable, like [other senders do](https://github.com/evergreen-ci/timber/blob/819ca602876e1ee91c6f7cc73885ab94ed80d841/buildlogger/basic_sender.go#L276-L278), before accessing the message string, which tries to [dereference the error](https://github.com/mongodb/grip/blob/dfee190b28366aa88b31c2386cf97ec1af7bde6b/message/error_message.go#L60).
With HEAD in staging [the error was logged](https://mongodb.splunkcloud.com/en-US/app/search/search?display.page.search.mode=fast&dispatch.sample_ratio=1&q=search%20index%3Devergreen-staging%20%22encountered%20issue%20in%20stats%20collector%22&earliest=17067329 …
=> DEVPROD-4025 fix redacting sender panic

cloud/ec2.go, model/task_queue.go, model/task_queue_service_dependency.go, scheduler/utilization_based_host_allocator.go, trigger/process.go, units/event_notifier.go
DEVPROD-4255
I pruned some of the biggest contributors to the Splunk log size. I don't think any of these are controversial since they don't drastically change traceability of code, but I addressed each one in a comment.
Post-deploy, will continue monitoring to see if it's still too much logging for Splunk. Will also verify that the Evergreen Splunk dashboard still renders properly.
N/A
N/A
=> DEVPROD-4255: reduce noise in Splunk logs

globals.go
[DEVPROD-4494](https://jira.mongodb.org/browse/DEVPROD-4494)
We're sending db.statement for the events collection which could potentially contain a copy of updates to project vars.
The fastest way to address this is to add this to the hard coded slice of collections that have their `db.statement` redacted. In the future maybe we'd want to make it configurable. Or perhaps we want to rethink whether the `db.statement` attribute is worth the risk.
If I get a chance I'll validate it on staging, but I don't think we really need to.
=> DEVPROD-4494 add events to the sensitive collections

config_test/evg_settings.yml, model/generate.go, model/patch_lifecycle.go, model/project.go, model/project_test.go, units/patch_intent.go
DEVPROD-978
Add checks that stops patches from creating more checkruns than the limit.
Added a unit test and tested manually for schedule patch, configure patch, and generate patch.
=> DEVPROD-978 Implement check run limit 

globals.go, model/host/db.go, model/host/db_test.go, units/crons.go, units/crons_remote_hour.go, units/unexpirable_spawnhost_stats.go, units/unexpirable_spawnhost_stats_test.go
DEVPROD-3944
Create a daily job that will collect estimated uptime stats on unexpirable hosts. This will help diff the cost savings before/after the sleep schedule is rolled out. It intentionally logs to Splunk rather than Honeycomb because Honeycomb's 60 day TTL is too short of a time period.
* Tested in staging that it outputted the stats in the expected format.
N/A
=> DEVPROD-3944: create job to collect unexpirable host stats

graphql/tests/task/taskLogs/results.json, rest/model/event.go
DEVPROD-915
Event log jira ticket urls were being returned with an additional `https://` which is unnecessary since the jiraHost URL already has an `https://`
=> DEVPROD-915 Remove unnecessary https from url

globals.go, model/host/host.go, units/patch_intent_test.go, units/spawnhost_modify.go, units/spawnhost_modify_test.go, units/spawnhost_start.go, units/spawnhost_start_test.go, units/spawnhost_stop.go, units/spawnhost_stop_test.go, units/spawnhost_terminate.go, units/spawnhost_terminate_test.go
DEVPROD-3946
Attach more spawn host attributes to the Amboy job Honeycomb spans (specifically for for spawn host modification jobs). This lets us do things like set up Honeycomb dashboards for stops/starts and filter by host fields like whether it's stopping an unexpirable host, the instance type, the source of the stop/start action (a user pressing the button vs. the sleep schedule), etc.
If the job errors (e.g. because AWS returns an error while stopping the host), Amboy's Honeycomb setup already records those errors and stack traces for us. They're also already logged to Splunk.
Stopped/starting a spawn host in staging and verified that [the Honeycomb data is being sent](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/cSoZWBv2MFb) and is queryable.
N/A
=> DEVPROD-3946: add Honeycomb attributes for spawn host modification jobs

agent/command.go, config.go
DEVPROD-3346
The display name will include additional relevant context like the function and block the command runs in. This context will be helpful to have in honeycomb, and the display name can be queried for in honeycomb with `evergreen.command.command_display_name contains <displayName>`.
=> DEVPROD-3346 Include command display name in honeycomb trace

self-tests.yml
[DEVPROD-4588](https://jira.mongodb.org/browse/DEVPROD-4588)
We're going to start turning on the Kanopy cluster soon. Let's turn this on now so we have a bit of history.
We should see it running on the project health when we merge.
=> DEVPROD-4588 turn on the build-and-push task

model/task/db.go
DEVPROD-4536
Mohamed and I were talking and noticed that it would be possible to use `$limit` instead of `$count` in HasMatchingTasks since we only care if a single matching task exists. I think logically this should be faster since I believe our usage of `$count` will scan all of the results to get the total number. ([docs](https://www.mongodb.com/docs/manual/reference/method/cursor.count/#index-use))
Tested on Compass Production against a server patch.
Here is the explain for the aggregation with  `$count` on a server patch with filters `[{ taskName: /s/ }, { buildVariant: /a/ }]`:
Here is the explain for the aggregation with `$limit` on a server patch with filters `[{ taskName: /s/ }, { buildVariant: /a/ }]`:
=> DEVPROD-4536: Use $limit instead of $count in HasMatchingTasks

agent/agent.go, agent/command.go, config.go
DEVPROD-4233
Including the name of the task in the span makes it counintuitive to search for
the span, as typically the name of a span is the name of the function that it is
in, and is therefore static. This adds the task.id as an attribute instead of in
the span name.
We may wish to announce in Slack that this change is being made, as it may break
existing queries.
None.
None.
=> DEVPROD-4233 Set task ID as attribute

config.go, operations/evaluate.go
DEVPROD-3025
evaluate has a --diffable flag that will alphabetize tasks and bvs 
tested locally
=> DEVPROD-3025 Update evaluate command to output sorted build variants

self-tests.yml
DEVPROD-2231
On windows machines, the gopath is being set incorrectly with run-make so this changes the responsibility of setting the gopath to the individual commands that use it rather than globally for run-make. Windows tests do not rely on any gopath being set- 
Existing CI testing
=> DEVPROD-2231 Change gopath to be specific to tasks rather than run-make

agent/command/shell.go, config.go
DEVPROD-4510
This prints the script for troubleshooting before expansions are expanded.
This should be covered by existing tests, and we should validate that a task runs in staging.
None.
=> DEVPROD-4510 Log script before expanding expansions

self-tests.yml
[DEVPROD-4588](https://jira.mongodb.org/browse/DEVPROD-4588)
We no longer need the `linux_arm64` build for staging since the app servers will be running on `linux_amd64`
=> DEVPROD-4588 one less build for staging

docs/Project-Configuration/Project-and-Distro-Settings.md, model/project_test.go
DEVPROD-4199
A user ran into issues excluding build variants with one of two tags in patch aliases. This verifies that it works and spruces up the docs. Troubleshooting was also done with the user. I couldn't reproduce the bug but verified that it now works as expected for them. 
Added. 
Included
=> DEVPROD-4199 Spruce up docs for patch alias tag selection and add a test. 

agent/command/host_create_test.go, apimodels/agent_models.go, cloud/ec2.go, cloud/ec2_client.go, cloud/ec2_fleet.go, cloud/ec2_fleet_test.go, cloud/ec2_integration_test.go, cloud/ec2_test.go, cloud/ec2_util.go, config.go, docs/Project-Configuration/Project-Commands.md, environment.go, go.mod, model/project_parser_s3.go, model/project_parser_test.go, model/task/generated_json_s3.go, model/task/generated_json_storage_test.go, rest/data/host_create.go, rest/route/host_create_test.go, self-tests.yml, testutil/config.go
This reverts commit c21f9493dd9cdd6878d9a06d10aba95cbf994a42.
This was causing error rate alerts when it was deployed and PRs weren't processing. Will confirm that it passes compile and tests, then merge the revert.
=> Revert "DEVPROD-4556: use instance profile for AWS auth on the app servers (#7503)

rest/data/project_settings.go
DEVPROD-3616
Correcting a mistake I made — there's no need to query for identifier because it's already stored in `mergedBeforeRef`.
- Tested on staging
=> DEVPROD-3616: Use mergedBeforeRef instead of querying for identifier

docs/Project-Configuration/Project-and-Distro-Settings.md
As requested in a users thread. Not applying this beyond that for simplicity.
=> docs: add tab section to github project page docs

cloud/ec2.go, cloud/ec2_client.go, cloud/ec2_test.go, cloud/ec2_util.go, cloud/ec2_util_test.go, model/host/host.go, model/host/host_test.go, units/spawnhost_modify_test.go
DEVPROD-3973
Follow-up to #7520. #7520 already handles the common case where users will just spawn an unexpirable host and then will never make it expirable again (they could just terminate it if they want it gone). This handles some less-common scenarios where a user decides to change their host's expirability setting later on.
* When switching an expirable host to be unexpirable, assign it a persistent DNS name.
* When switching an unexpirable host back to an expirable one, remove its persistent DNS name (Evergreen only manages persistent DNS names for long-lived spawn hosts).
* Remove the "random" aspect of the persistent DNS name generation so that, if given a host and user, it'll always generate the same DNS name no matter how many times it's called. The only time this wouldn't be …
=> DEVPROD-3973: manage DNS when host expirability changes

model/patch_lifecycle.go, model/patch_lifecycle_test.go
DEVPROD-3085
#7452 fixed an issue where Evergreen couldn't process renamed include files because it was trying to fetch the newly renamed include file from git, which didn't yet exist.
As it turns out, if you set `diff.renames=copies` in your local git config, the created .patch file will not say "rename from <filename>", but "copy from <filename>". #7452 only checks for renamed files, so the above issue was still surfacing for a user who had `diff.renames=copies` set. They were able to workaround by unsetting the field, but we should be able to handle this case.
Added some unit tests, and reproduced the issue with a locally created patch file. Confirmed I was able to submit a patch [successfully](https://evergreen-staging.corp.mongodb.com/filediff/65c67c009dbe324c21a0e67f/?patch_number=0) …
=> DEVPROD-3085 Check for copied include files

model/dependency.go, model/dependency_test.go, model/patch_lifecycle.go, model/patch_lifecycle_test.go, rest/route/patch_test.go
DEVPROD-4739
This fixes an issue where if you have a task within a task group that's disabled, then try to schedule it using the schedule patch REST route, it won't schedule the task group or return any error. This normally isn't a problem you encounter when you configure a patch in Spruce because it already auto-filters out disabled tasks from your selection choices.
* Allow task groups with some disabled tasks to be scheduled.
* Continue on error in more cases rather than exit early (to ensure later tasks in a list get scheduled even if there are errors for other tasks).
* Add a TODO for a similar bug (but for requesters instead of disable).
* Add unit tests for patch configure route and dependency inclusion for partly-disabled task group tasks.
* Tested manually by submitting [a patch …
=> DEVPROD-4739: fix dependency inclusion for disabled tasks in task groups

agent/command/host_create_test.go, apimodels/agent_models.go, cloud/ec2.go, config.go, docs/Project-Configuration/Project-Commands.md, globals.go, rest/data/host_create.go, rest/route/host_create_test.go, util/expand_params_test.go
DEVPROD-4767
Allow users to specify the EC2 host [tenancy option](https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-dedicated-instances.html) for host.create. Will add a follow-up PR in Shrub to add the new option once this is merged.
* Verified in staging that [a task could start an EC2 host.create host with tenancy set](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2204_kim_task_patch_3a552c8209cca308b80b52627897a8cec3000e2b_65ce55f7b8f8990007c8930c_24_02_15_18_20_39/logs?execution=1). I also double-checked that `aws ec2 describe-instances` for the instance shows its tenancy is `dedicated` (the custom value I set in the task) instead of `shared` (the default).
Updated docs.
=> DEVPROD-4767: support tenancy option for host.create

apimodels/agent_models.go, config.go, docs/Project-Configuration/Project-Commands.md, rest/data/host_create.go, rest/route/host_create_test.go
DEVPROD-4913
We need to support this feature for the `buildhost-configuration` project. They do not need to pass in an AWS key/secret since the they are ultimately using the default AWS account.
Updated unit tests. Ran a [patch in staging](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2204_test_cloud_patch_6e38484f356fbfb89f6627e970131afc3be49763_65cf87f8b2373662f5973933_24_02_16_16_06_56/logs?execution=1&logtype=task&sortBy=STATUS&sortDir=ASC) where I set the `key_name` field in the `host.create` command called in the `test-cloud` task. I verified via the AWS console that the spawn was launched with the `mcipacker` ssh key:
Updated user-facing docs.
=> DEVPROD-4913: add back support for EC2 key in create.host

model/dependency_test.go
DEVPROD-4739
This test is flaky because goconvey needs the order of slice elements to match exactly. I fixed the test to not depend on the order of the elements in the slice.
=> DEVPROD-4739: fix flaky dependency test
