evergreen-ci/evergreen

cloud/cloud_host.go
config.go
config_db.go
model/host/hostutil.go
rest/model/admin.go
service/templates/admin.html

[DEVPROD-4677](https://jira.mongodb.org/browse/DEVPROD-4677)
The path to the key on Kanopy cannot be the same as it is on EC2 because the secret can't be mounted on an existing directory.
Add an extra SSH key path to use during the cutover. Once the cutover is done we'll remove this key and set the regular one to the new path ([DEVPROD-4798](https://jira.mongodb.org/browse/DEVPROD-4798)).
Was able to kick off SSH provisioning on a host (that then failed for another reason)

DEVPROD-4677 add a temporary Kanopy SSH key

---

docs/Containers/Container-Tasks.md
model/project.go
model/project_parser.go
model/project_ref.go
self-tests.yml
units/pod_allocator.go
validator/project_validator_test.go

DEVPROD-3873
Allow container image URIs to be expanded from project variables. This will allow staging and prod to reference their own ECR repositories and get the staging container variant green again.
Tested in staging. The PR checks here can't run, so I scheduled [this patch](https://spruce.mongodb.com/version/65d7b8989ccd4eb556cbb23a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) in prod to represent the build state

DEVPROD-3873 Allow container image to use project variable

---

makefile

[DEVPROD-4627](https://jira.mongodb.org/browse/DEVPROD-4627)
Add a `local` make target to build all the stuff you'll need to do a local build using https://github.com/10gen/kernel-tools/pull/428. Kind of like the `dist` target, just for Kanopy.
It builds the stuff it's supposed to build.
I'll add it to the ops guide once https://github.com/10gen/kernel-tools/pull/428 merges.

DEVPROD-4627 add local make target

---

self-tests.yml

DEVPROD-3873
Now that the previous PR for this ticket has been deployed and Evergreen will understand an expansion for the image field, updating our YAML to use the new variable.

DEVPROD-3873 Update YAML to use variable for image

---

service/host.go
service/middleware.go
service/spawn.go

DEVPROD-2450
Host page will auto redirect to spruce just like spawn page does 
Tested that host pages will auto redirect to spruce on staging
ie
https://evergreen-staging.corp.mongodb.com/host/i-00ab599007f7dd911 redirects to  https://spruce-staging.corp.mongodb.com/host/i-00ab599007f7dd911

DEVPROD-2450 Redirect host pages to spruce if spruce enabled

---

docs/Containers/Container-Tasks.md
docs/Project-Configuration/Project-Commands.md

DEVPROD-4695
Instead of replacing with #ask-devprod-evergreen I just left these general -- the implication if you need help for _any_ feature is to find our channel, I think it doesn't need to be hardcoded. Open to the argument it should be on the home page, although users have gotten by without that so far.

DEVPROD-4695 remove #evergreen-users mentions (RIP)

---

go.mod
go.sum
model/host/host.go
model/host/host_test.go

DEVPROD-3947
I apologize in advance, the code change itself isn't actually that long (most of the diff is tests) but the algorithm is kind of tricky. Feel free to read the test cases or ask questions if you need clarification.
* Add validation function to ensure sleep schedule provided by user is sensible and follows the basic requirements.
* Add helper functions to calculate the next scheduled stop/start times. This uses [the same cron library](https://pkg.go.dev/github.com/robfig/cron) that we use for implementing the `cron` YAML field to help with the future time calculations.
Added lots of unit tests for validation and calculation correctness.
N/A

DEVPROD-3947: add validation and calculate next stop/start time

---

environment.go
graphql/redact_secrets_plugin.go
util/copy.go
util/copy_test.go

DEVPROD-5081
The `util.DeepCopy` method used [gob](https://pkg.go.dev/encoding/gob)  to encode/decode structs to allow for copying go structs. This however required each struct to be registered with the gob method in order for gob to be able to copy it. This unfortunately caused errors when used alongside the graphql request secret redaction since there were many different possibilities of structs that could be passed in that would need to be copied. This PR updates the `util.DeepCopy` method to use a more flexible json Marshall/Unmarshal method to copy structs.

DEVPROD-5081 Update Deepcopy to use JSON copy method instead of gob.

---

model/host/host.go
model/host/host_test.go

DEVPROD-4040
This is a small amendment to #7557. I looked at some of the generated DNS names after the job finished and a couple of them look like real words (for example, I saw one that had randomly generated `firstname-lastname-labs1`). Ideally, the DNS name that users see should only contain meaningless unique strings, so to avoid that confusion, I cut down the letter set down to just hexademical characters and reduced the length of the random portion. I don't think you can make many words with 3 hexademical-only characters.
After this is deployed, I'm also gonna clear the existing persistent DNS names so that the persistent DNS assignment job from #7557 can automatically regenerate them.
Updated existing tests.
N/A

DEVPROD-4040: use a smaller set of characters for persistent DNS names

---

model/task/task.go
units/host_termination.go
units/host_termination_test.go

DEVPROD-4592
This checks instead of the last task in a task group, the last task that is will or scheduled to run. The issue with checking the rigid last task in a task group is that they can be partially scheduled.
Add CI test and ran it against the old codebase and it failed
(PR patch shows the current code, [here](https://spruce.mongodb.com/task/evergreen_ubuntu2204_test_units_patch_2a81f2c4cfdcb3766b0b8c95738ac6a7392f58b6_65df4e5a2fbabec589804010_24_02_28_15_16_50?execution=0&sortBy=STATUS&sortDir=ASC) is a manual patch with the new test but the old implementation)

DEVPROD-4592 Check if task is last task to run in task group before restarting

---

agent/agent_test.go

DEVPROD-5244
Just cygwin weirdness...
[patch build with passing task on windows
](https://spruce.mongodb.com/task/evergreen_windows_test_agent_patch_6107b5deeeb8b6f9d0b0563dcebf8ec7b2085685_65e0fb603066153a34e89302_24_02_29_21_47_27/logs?execution=0&logtype=task&sortBy=STATUS&sortDir=ASC)
N/A

DEVPROD-5244: fix broken agent test

---

model/task_lifecycle.go

DEVPROD-2972
Display tasks should not have Honeycomb traces. Here is [an example of a display task](https://spruce.mongodb.com/task/mongodb_mongo_master_enterprise_amazon_linux2_arm64_all_feature_flags_fuzzers_display_aggregation_optimization_fuzzer_ad1efe8f7f0413375649c50621251fcfca8cace8_24_02_28_11_11_20/execution-tasks?execution=0&sorts=STATUS%3AASC) on production that has a Honeycomb link. Jonathan pointed out that this Honeycomb link actually corresponds to one of its [execution tasks](https://spruce.mongodb.com/task/mongodb_mongo_master_enterprise_amazon_linux2_arm64_all_feature_flags_fuzzers_aggregation_optimization_fuzzer_03_linux_enterprise_ad1efe8f7f0413375649c50621251fcfca8cace8_24_02_28_11_11_20/tests?execution=0&sortBy=STATUS&sortDir=ASC). It seems like the current code just …

DEVPROD-2972: Stop populating trace ID for display tasks

---

cmd/upload-s3/upload-s3.go
makefile
scripts/setup-credentials.sh
self-tests.yml
smoke/internal/testdata/project.yml

DEVPROD-4989
This will allow us to remove static AWS credentials from the Evergreen project variables.
- Update the existing AWS role for Evergreen integration tests to have S3 permissions for `mciuploads/evergreen`.
- Call `ec2.assume_role` at the beginning of tasks and pass around the temporary creds for S3 operations.
Ran a full [patch build](https://spruce.mongodb.com/version/65de51c9c9ec44736b869649) including the `dist` and `build-and-push` tasks.
N/A

DEVPROD-4989: use temporary AWS creds in project config

---

agent/agent.go
agent/agent_test.go
apimodels/agent_models.go
config.go
docs/Project-Configuration/Project-Configuration-Files.md
rest/route/host_agent.go
rest/route/host_agent_test.go

DEVPROD-956
Per the user request, when task groups are restarted, the restart is treated like it's a brand new task group running on the host. Previously, restarted tasks would be treated as part of the same task group, so the host would retain all the state from previous executions. This works with both single-host and multi-host task groups.
* Handle running a next tasks in the same task group but with a different execution as if it's a brand new task group.
* Fix a tiny bug that I noticed where one error message has the wrong info because the running task is cleared before the error message is created.
* Updated unit tests for next task behavior.
* Tested in a patch in staging with single-host and multi-host task groups.
* Slightly modernize some of the (very old) tests for the next …

DEVPROD-956: treat different task group execution as new task group

---

rest/route/agent.go
thirdparty/github.go

DEVPROD-5294
Sets all default fields specified in the design before creating check run
Testing will be done in the future as this change only fills in fields right before check run creation

DEVPROD-5294 Set default check run fields

---

self-tests.yml

DEVPROD-5308
Assume role state is not passed between tasks in a task group. Need to call this before each task rather than once for the entire group.
N/A
N/A

DEVPROD-5308: call assume role for each task in the `dist-and-upload-clis` task group

---

service/project.go
service/templates/menu.html
service/ui.go

DEVPROD-3137
This PR makes the "Projects" option in the menu dropdown link to Spruce using the currently set project. In order to read the project ID variable from the URL, I changed the route to use a different format. (Couldn't find a way to read the project ID from the `##` format.)
- On staging

DEVPROD-3137: Redirect to specific Spruce project page from legacy UI

---

agent/agent.go
config.go

DEVPROD-5349
This needs to happen before we handle task directory output in the reserved directory because the `Run` function blows up the reserved `build` dir.
N/A
N/A

DEVPROD-5349: send otel traces before cleaning up task output dir

---

self-tests.yml

DEVPROD-2299
Adds a new tag that excludes tasks tagged with "no-container" for linter tasks.
I was thinking of expanding this to the other tags but I think that should be done on an "as-needed" basis. This solution seems like the most self-documenting.
Configured a patch and it no longer shows up in the container ubuntu distro, only in the ubuntu distro

DEVPROD-2299 Remove govulncheck from container tasks

---

units/crons.go
units/crons_remote_fifteen_minute.go
units/persistent_dns_assignment.go

DEVPROD-4040
Follow-up to #7587 - now that the job has finished assigning persistent DNS names to existing hosts, the job can be removed. To delete the job gracefully, we have to first let any remaining persistent DNS jobs drain out of the Amboy queue (to avoid an issue where the Amboy queue might still have a job in the queue from before the deploy and doesn't know what to do with it because the code is gone). After this is deployed, then the remaining code will be deleted in a follow-up PR.
N/A
N/A

DEVPROD-4040: no-op persistent DNS assignment job

---

agent/agent.go
agent/agent_test.go
config.go

DEVPROD-5333
Use consistant naming for post task: We sometimes refer to it as "post-task" and sometimes "post task" making searching logs harder. We should stick to one.
This also specifies that it can be a teardown task command. This helps because for task groups the post commands should not run, so the logs can look like a bug.

DEVPROD-5333 Improve post task logging in agent 

---

docs/CLI.md

From user thread:
https://mongodb.slack.com/archives/C0V896UV8/p1709049364840069

docs: add tag example to local aliases

---

graphql/util.go

[DEVPROD-5413](https://jira.mongodb.org/browse/DEVPROD-5413)
Once we started shifting traffic to Kanopy we started seeing errors from [here](https://github.com/evergreen-ci/evergreen/blob/main/graphql/util.go#L135). [The docs](https://pkg.go.dev/time#LoadLocation) say it looks for timezone info in a bunch of places. The EC2 instances have this information at `/usr/share/zoneinfo` but it's missing on the ubuntu image.
Including this package will make go embed the data in the binary itself.
I spun up an ubuntu:22.04 (our base image) container and ran the example from [here](https://pkg.go.dev/time#example-LoadLocation). Before I added [the tzdata package](https://pkg.go.dev/time/tzdata) it errored (once I uninstalled go so `$GOROOT/lib/time/zoneinfo.zip` was missing) and once I added it it …

DEVPROD-5413 import tzdata package

---

service/templates/admin.html

DEVPROD-4220
Forgot to actually add the service flag womp.
Confirmed I could toggle the flag and save.

DEVPROD-4220 add auto-restart system failure service flag

---

model/user/db.go
model/user/user_test.go
rest/model/generated.go
rest/route/user_test.go

DEVPROD-4718
Specifying an email address in the request body did nothing, despite being listed in the docs as a param. This fixes it. 
Added to existing tests. 
This aligns the behavior with what's already documented.

DEVPROD-4718 Fix email address for /admin/service_users route

---

agent/agent.go
agent/agent_test.go
config.go
model/task/task.go
model/task/task_test.go
rest/route/agent.go
rest/route/github.go
thirdparty/github.go
thirdparty/github_test.go

DEVPROD-970
Restarting a task from spruce will now update the check run instead of creating a task run
on staging 
https://github.com/evergreen-ci/commit-queue-sandbox/pull/617/checks?check_run_id=21350875510
this check run's URL has been updated to the latest execution of the task link

DEVPROD-970 Allow check runs to support multiple executions

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
cloud/ec2_test.go
cloud/ec2_util.go
cloud/userdata_test.go
model/host/host.go
model/host/host_test.go
units/host_status.go

DEVPROD-4768
The host status job is responsible for polling host statuses so that Evergreen knows when they're up and running. When [getting the host status](https://github.com/evergreen-ci/evergreen/blob/99807e9b0813b44eb7c07958b8f1cbc4858f77e3/units/host_status.go#L104), it also [caches some of the information it gets](https://github.com/evergreen-ci/evergreen/blob/99807e9b0813b44eb7c07958b8f1cbc4858f77e3/cloud/ec2_util.go#L305-L327). This caching is done via many `UpdateOne` statements, so if the job checks `N` hosts and finds they're running, it will do approximately `2N` `UpdateOne`s sequentially.
Based on [Honeycomb stats](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/z5owHjDpkbH), the host status job occasionally takes several minutes to …

DEVPROD-4768: bulk write updates when caching host data from EC2

---

graphql/tests/mutation/deleteProject/results.json
rest/data/project.go
rest/route/project_test.go

[DEVPROD-5336](https://jira.mongodb.org/browse/DEVPROD-5336)
Originally, there is no way to make projects deletable/hidden- then when we added multi-tracking branch projects and repo ref, we made those deletable/hiddenable. This was out of scope and at the time, seen as not required. Most of the changes need to be done via the frontend.
Manual testing via staging. Some CI testing edited
I made two projects:
https://evergreen-staging.corp.mongodb.com/rest/v2/projects/DeleteMe
https://evergreen-staging.corp.mongodb.com/rest/v2/projects/deleteme
The 2nd one I successfully deleted when I deployed. The 1st is unable to delete. The 2nd is successfully hidden from UI as well.

DEVPROD-5336 Allow projects not tracking repos to be deletable

---

model/testresult/testresult.go

DEVPROD-4906
So we don't break parsley.
N/A

DEVPROD-4906: do not print timestamps from raw test logs if resmoke

---

agent/agent.go
config.go

DEVPROD-3871
There is currently no way to tell if the agent exited because it received "shouldExit". This will help debug things. 
I can't think of a good way to test it. I think it's simple enough to not need it.

DEVPROD-3871 Add tracing for when the agent exits because it was told to 

---

graphql/distro_resolver.go
graphql/redacted_fields_gen.go
graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql
graphql/tests/mutation/saveDistro/queries/save.graphql
graphql/tests/mutation/saveDistro/queries/validation_error.graphql
graphql/tests/mutation/saveDistro/results.json

DEVPROD-5047
On Spruce we expect these values to be entered as milliseconds:
But the function `NewAPIDuration` expects the input to be nanoseconds, causing the values to be incorrectly parsed as 0 (e.g. 5000 sent from frontend -> 5000 is divided by 1000000 to get 0.005).
- Updated GraphQL tests
- Locally on my machine

DEVPROD-5047: Fix conversion to APIDuration for TargetTime and AcceptableHostIdleTime

---

units/migrate_volume.go
units/migrate_volume_test.go

DEVPROD-4925
This changes the volume migration job to query for the user who spawned the host rather than the default "mci" user. This fixes a performance issue and a bug:
1. This query was looking through all terminated hosts owned by "mci", which is the default user for task hosts. Since the vast majority of the hosts collection is terminated task hosts, it was basically doing a collection scan.
2. Spawn hosts are always started by the real user, not by "mci", so the query would never find the right host.
Updated unit test to more accurately reflect the user information the volume migration job would have.
N/A

DEVPROD-4925: fix query for volume attached to terminated spawn host

---

self-tests.yml

DEVPROD-5432 
Disabling, from conversation.
shouldn't run in PR testing , passed `evergreen validate`

DEVPROD-5432 disable go vulnerabilities task

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-5257
We should use a different example here because later on in the docs we say: 
"Some operations may not be permitted within the "teardown_group" phase, such as "attach.results" or "attach.artifacts"."
Indeed

DEVPROD-5257 Don't use command: attach.results as an example in teardown_group

---

service/service.go

[DEVPROD-5482](https://jira.mongodb.org/browse/DEVPROD-5482)
I didn't anticipate users were downloading client binaries from this URL (without getting it from the UI first). Also it's good to have a stable URL for users to get the binary from.
This PR adds a redirect from the clients URLs to S3. It's a temporary redirect because the target URL will change with each subsequent evergreen deploy and we don't want browsers to cache an old URL.
Works in staging™️

DEVPROD-5482 client binaries redirect

---

docs/Project-Configuration/Project-Commands.md

[DEVPROD-5232](https://jira.mongodb.org/browse/DEVPROD-5232)
Add mention of timeout configurations specific to CLI tools running on Evergreen (such as DSI), to help users who run performance tests avoid a common pitfall where they didn't know that they also have to set these DSI parameters for long-running tests.

DEVPROD-5232: Add mention of timeout configurations specific to CLI tools running on Evergreen 

---

model/project_event.go
model/project_vars.go
model/project_vars_test.go
rest/data/project_test.go

DEVPROD-5339
Changed `UpdateProjectVarsByValue` to include the full project vars struct when creating project event logs. The absence of private vars previously is what led to the event logs revealing private vars in the UI.
A side effect of this fix was that modifying private variables would no longer show any event log at all in the UI because the UI analyzes before/after diffs which are not picked up when the before and after value of a private var are both redacted to `""`. To fix this, if a private variable has been modified, I've changed to show {REDACTED} in the before field so that it will show up in the UI as an event log.
Tested in staging and confirmed the project variable rotation route will not lead to event logs showing the private variable's value. Added unit tests.

DEVPROD-5339 Respect private variables in event logs for project vars rotate route

---

agent/agent.go
agent/agent_test.go
config.go

DEVPROD-5600
If a check run output file is not found, log an error to the task. Also submit a checkrun to github with an output that contains the error. 
https://github.com/evergreen-ci/commit-queue-sandbox/pull/670/checks?check_run_id=22683525279

DEVPROD-5600 Log an error if a checkrun file does not exist 

---

agent/agent.go
config.go

DEVPROD-967
If a check run file is not found, return error so that it doesn't log the success message.

DEVPROD-967 Return error so it doesn't log success 

---

graphql/generated.go
graphql/schema/types/host.graphql
graphql/tests/query/myHosts/data.json
graphql/tests/query/myHosts/queries/my_hosts.graphql
graphql/tests/query/myHosts/results.json
rest/model/host.go
rest/route/service_test.go

DEVPROD-4196 cc @Kimchelly 
- Expose hosts' persistent DNS name field to display to users
- Add GraphQL unit tests
- Verified on staging
N/A

DEVPROD-4196: Expose PersistentDNSName

---

docs/API/REST-V2-Usage.mdx
docs/CLI.md
docs/Hosts/Developer-Workstations.md
docs/Hosts/Spawn-Hosts.md
docs/Project-Configuration/Best-Practices.md
docs/Project-Configuration/Commit-Queue.md
docs/Project-Configuration/Github-Integrations.md
docs/Project-Configuration/Notifications.md
docs/Project-Configuration/Parameterized-Builds.md
docs/Project-Configuration/Project-Commands.md
docs/Project-Configuration/Project-Configuration-Files.md
docs/Project-Configuration/Project-and-Distro-Settings.md
docs/Project-Configuration/Task-Priority.md
docs/Project-Configuration/Task-Runtime-Behavior.md
docs/Project-Configuration/Task_Traces.md
docs/Reference/Comparison.md
docs/Reference/Glossary.md
docs/UI/Patch-Configuration.md
docs/UI/Version.md

DEVPROD-5372
I clicked a bunch of links in Pine and concluded that only some of the relative path links (e.g. `../API/REST-V2-Usage.md`) work, and I can't tell what causes some to work and others to not (some work, others don't, but they all are valid relative paths). My guess is that maybe the relative paths don't actually do anything, or that being able to render the link depends on the order that the files are processed by Docusaurus.
Anyways, I saw a couple links are using absolute paths starting from the docs root (i.e. https://docs.devprod.prod.corp.mongodb.com/evergreen/) and they seem to work, so I'm going to try switching all the relative path links to absolute paths to see if Docusaurus accepts them. If not, I can just revert it.
Will check the links once Pine deploys the latest …

DEVPROD-5372: use absolute path links instead of relative

---

model/host/db.go
model/host/host.go
model/host/host_test.go

DEVPROD-5633
DEVPROD-4197 is going to update Spruce so that users can set their sleep schedule on the spawn host page. I added a helper in this PR to connect the UI settings to the DB so that it can persist the user's sleep schedule settings.
I also slightly refactored the get next stop/start helpers since they don't actually need any of the host fields, just the sleep schedule settings.
cc @sophstad 
N/A

DEVPROD-5633: add helper to update sleep schedule

---

cloud/cloud.go
cloud/cloud_host.go
cloud/docker.go
cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_test.go
cloud/mock.go
cloud/static.go
graphql/mutation_resolver.go
model/host/db.go
model/host/host.go
model/host/host_test.go
rest/data/host.go
rest/route/host_spawn.go
service/spawn.go
units/migrate_volume.go
units/spawnhost_start_test.go
units/spawnhost_stop.go
units/spawnhost_stop_test.go

DEVPROD-5634
DEVPROD-4198 will update Spruce to have an extra option for unexpirable hosts on a sleep schedule to keep their host off indefinitely when they press the stop button. If they enable this, Evergreen should ignore the host's sleep schedule and just let the host stay stopped. Once the user starts their host back up, it'll resume its regular sleep schedule again.
cc @sophstad 
Updated unit tests for stop/start.
N/A

DEVPROD-5634: add option to keep host off when stopped

---

rest/route/github.go
thirdparty/github.go

DEVPROD-5597
Re-run all was not being handled for suite events 
on staging 
https://github.com/evergreen-ci/commit-queue-sandbox/pull/670/checks?check_run_id=22713199800
all check runs restarted in this pr

DEVPROD-5597 Handle GitHub Suite Re-Run events

---

docs/Project-Configuration/Project-Commands.md

The `__project_aws_ssh_key_value` is the ssh private key, not the public key.

docs: fix ssh key doc

---

model/patch/github.go
model/patch/github_test.go
model/project_ref.go
rest/data/patch_intent.go
rest/route/github.go
testutil/github.go
thirdparty/github.go
units/github_status_api.go
units/github_status_api_test.go
units/patch_intent.go
units/patch_intent_test.go

DEVPROD-1008
This introduces a new optional project ref setting field that defines the oldest allowed commit hash that can be the merge base for PR patches. If the field is set for the project and the PR patch's merge base is older than the defined commit sha, the patch will not run.
In order to make it such that the git commit comparison check API only hits for projects that have this new field set, I had to refactor the github PR intent logic a bit to move the project ref query earlier in the logic.
This will require a followup Spruce PR.
Tested in staging by setting an oldest allowed merge base on a sandbox project, and confirmed that PRs opened with merge bases before the merge base [ran tasks](https://github.com/evergreen-ci/commit-queue-sandbox/pull/680), and a PR opened with a …

DEVPROD-1008 Add setting to define oldest allowed merge base for PR patches

---

agent/command.go
agent/command/initial_setup.go
agent/command/interface.go
agent/command/registry.go
agent/command_test.go
config.go
docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-4947
The `retry_on_failure` flag wasn't working for commands within a function, so I had to add the field to the actual rendered `Command` struct so we can case on it when a sub-command fails.
Unit tests and [tested in staging](https://spruce-staging.corp.mongodb.com/task/test_trigger_sandbox_release_test_restart_on_fail_patch_200dd38a7144b884e67cf77fb705239e58fd5e11_65fdbb48872ffc0007e0524a_24_03_22_17_09_45/logs?execution=0&logtype=event).
Updated the docs to include an example that also uses a function.

DEVPROD-4947 Allow command in function to retry task on failure

---

rest/route/user.go
rest/route/user_test.go

DEVPROD-739
This removes hidden project ref IDs from the /permissions route response.
Unit tests and tested in staging

DEVPROD-739 Remove hidden projects from permissions response

---

agent/agent.go
config.go

DEVPROD-6014
print error for check run in log 
[error in task log](https://parsley-staging.corp.mongodb.com/evergreen/sandbox_ubuntu2204_print_banana_patch_75296bc001a22600252f2d4e8f35d47c9b31221b_660b29c1f77c0d00075e57db_24_04_01_21_40_21/0/task?bookmarks=0,49&shareLine=48)

DEVPROD-6014 Surface check run creation errors

---

docs/Project-Configuration/Project-and-Distro-Settings.md
go.mod
graphql/generated.go
graphql/schema/types/project.graphql
graphql/schema/types/project_settings.graphql
graphql/schema/types/repo_ref.graphql
graphql/tests/projectSettings/projectRef/data.json
graphql/tests/projectSettings/projectRef/queries/project_ref.graphql
graphql/tests/projectSettings/projectRef/results.json
rest/model/project.go

DEVPROD-1008
This adds the new field to our resolvers so it can be set via Spruce.
Unit test.
Added doc section for the feature

DEVPROD-1008 Add oldest allowed merge base to resolvers

---

agent/command/papertrail_trace.go
agent/command/papertrail_trace_test.go
agent/command/registry.go
config.go
docs/Project-Configuration/Project-Commands.md
scripts/setup-credentials.sh
self-tests.yml
testutil/testing.go
thirdparty/papertrail.go

DEVPROD-5626
Description
This commit adds the papertrail.trace Evergreen command. Projects will
use this command to simplify their interaction with the Papertrail
service when tracking artifact publishing. The command takes the
following parameters:
key_id:      The Papertrail Key ID for authentication
secret_key:  The Papertrail Secret Key for authentication
product:     The procut name to associate with each trace
version:     The product version to associate with each trace
filenames:   A list of files present locally to trace
work_dir:    An optional working directory to search for files in
Testing
In addition to the automated tests I've added, I also tested this in staging here: https://spruce-staging.corp.mongodb.com/task/evg_test_simple_bv_test_simple_task_patch_5e5de0e49ae51c658e12 …

DEVPROD-5626: add papertrail.trace command

---

agent/agent.go
agent/agent_test.go
config.go

DEVPROD-5822
Server has been getting non-matching directories for task groups because they sometimes have different executions if the first task was aborted/restarted and the rest of the tasks didn't. 
ie 
task group: 
task1: execution 1
task2: execution 0
and we ran setup group if executions did not match
we updated this logic to no longer run setup group if the execution of the next task in the same task group is smaller or equal to the execution in the current task.
unit tests
staging 
https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu2204_print_banana_patch_dc47177f87c5d979e74ae5cc4649c54474f55a3c_660dbc39aa78030007b6059f_24_04_03_20_29_51/logs?execution=1
print_banana task execution 2 does not have the set up message while running with print_apple execution 3 which does have …

DEVPROD-5822 Prevent setup group from running for tasks with smaller executions

---

github_app.go
github_app_test.go
graphql/tests/projectSettings/projectRef/data.json
graphql/tests/repoSettings/projectRef/data.json
model/project_ref_test.go
rest/route/repo_test.go
testdata/local/github_hooks.json

[DEVPROD-5983](https://jira.mongodb.org/browse/DEVPROD-5983)
Description
Edit getInstallationIDFromCache to also search by appId when provided. After [DEVPROD-5982](https://jira.mongodb.org/browse/DEVPROD-5982) is done, we will edit validateOwnerRepo to also make sure appID isn't 0 and remove the check on it not being 0.
Testing
Edited existing unit tetst

DEVPROD-5983 Edit getInstallationIDFromCache to work for user apps

---

go.mod
go.sum
model/artifact/artifact_file.go

[DEVPROD-5758](https://jira.mongodb.org/browse/DEVPROD-5758)
There's a key we need to deactivate that was used to `s3.put` many, many artifacts. When the db-contrib-tool attempts to download these artifacts it requests a presigned download link from Evergreen and Evergreen uses the key that was provided in the original `s3.put` to presign the URLs. Since 3/1/24 we've been uploading them with the new key. For the future we won't cache the actual key ([DEVPROD-5286](https://jira.mongodb.org/browse/DEVPROD-5286)). For artifacts created prior to 3/1, however, we're going to continue using the old key to presign (since rotating the key in all the affected artifacts isn't feasible ([DEVPROD-5685](https://jira.mongodb.org/browse/DEVPROD-5685))). If we want to deactivate the old key we need a …

DEVPROD-5758 special case mciuploads presigning

---

graphql/generated.go
graphql/schema/types/config.graphql
graphql/schema/types/distro.graphql

[DEVPROD-4798](https://jira.mongodb.org/browse/DEVPROD-4798)
Step one of removing required GraphQL fields is to make them optional (https://github.com/evergreen-ci/evergreen/pull/7713#discussion_r1556895334).
I wasn't 100% sure I understood
> add/remove any necessary logic needed to safely handle the field not always being there
If the fields aren't set the only effect would be on the UI side, afaik. But for now we'll continue to always set the field on the backend. So does that mean we're safe?

DEVPROD-4798 deprecate ssh key fields

---

config_amboy.go
config_test.go
environment.go
rest/model/admin.go
rest/model/admin_test.go
service/templates/admin.html
testutil/config.go

[DEVPROD-4163](https://jira.mongodb.org/browse/DEVPROD-4163)
Now that we're completely in Kanopy we don't need two separate URLs for the amboy db.
Just use the original URL field.
In staging we can still connect to the amboy db.

DEVPROD-4163 remove Kanopy amboy url

---

self-tests.yml
units/provisioning_create_host.go

DEVPROD-6213
The host creation job didn't return if the DB errored fetching the service flags, meaning the flags could be nil and cause a panic when checking them.
Didn't seem worth adding an explicit test for something so minor.

DEVPROD-6213: return on error fetching service flags

---

self-tests.yml

DEVPROD-6216
Rename the `notary_server_key` project variable in Evergreen's self-tests to not have the string `key` in it because it falsely redacts all the time in the self-test task logs (it's just the string "evergreen"). I'll rename the project variable itself once this is merged.

DEVPROD-6216: rename notary_server_key project var

---

agent/command/papertrail_trace.go
agent/command/papertrail_trace_test.go
config.go
docs/Project-Configuration/Project-Commands.md

DEVPROD-6198
This commit changes papertrail.trace to support wildcard globs in the filename parameter. Users may specify a path like "\*.tar.gz" and the command will trace all files that match. Arbitrary recursion sometimes implemented as double star globs (/foo/bar/**/*.tar.gz) is not supported.
Additionally, some checks have been added for duplicate filenames being traced in the same execution. While this was possible before, with wildcards it becomes quite a bit more likely to accidentally do. While it is possible some users have legitimate needs to trace the same filename twice, it's safer to have those users run multiple trace commands as a workaround.
I have new unit tests for these cases.
I've updated the command docs to describe this feature.

DEVPROD-6198: add wildcards to papertrail.trace

---

rest/data/commit_queue.go

DEVPROD-6114
Commit queue now does not error when the diff is too large for github to give a proper response 
tested by forcing return nothing on the get diff function 
seen in this [version](https://spruce-staging.corp.mongodb.com/version/6614d053e489c80007ef292e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (no changes in the changes tab)
but you can see that the change in the pr is being used in the test (changed echo output)
and that the pr is merged correctly in the [repo](https://github.com/evergreen-ci/commit-queue-sandbox/commit/9c8b55eb25a3ade3b1009b60f82372729ae0687d)

DEVPROD-6114 Update commit queue to allow merging with big diffs

---

rest/route/distro.go

DEVPROD-4628
Add docs for distro routes. There were a few routes that looked like they were dead and didn't have an obvious use case, so I didn't document those. Filed DEVPROD-6200 to consider removing the dead routes.
Checked the locally-generated docs and they looked as expected.

DEVPROD-4628: add docs for distro routes

---

model/github_app_auth.go
model/github_app_auth_test.go
model/project_event.go
model/project_ref.go

DEVPROD-5979
This adds the basic db functions for a new collection that will store the auth for github apps for users. It also adds a HasGitHubApp field on project settings and a HasGithubAppAuth() function and a call to it in getProjectSettings.
unit tests

DEVPROD-5979 DB functions for the new collection to store github auth 

---

validator/project_validator.go
validator/project_validator_test.go

DEVPROD-3269
Max task limit now looks at bv tasks instead of total tasks defined because tasks can be used in multiple bvs
unit test update

DEVPROD-3269 Update project limit validation to look at bv tasks

---

model/task_lifecycle.go

DEVPROD-6290
This fixes a panic noticed & detailed in this ops thread.

DEVPROD-6290 Error and do not update display task if no exec tasks are found

---

config.go
model/task/db.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go

DEVPROD-6045
This adds a subfield on the `StepbackInfo` field for the Task struct that are for generator's only. The field holds information for each generated task *going through bisect stepback*. As well, the generated tasks also get set with `StepbackInfo` for the UI to show the corresponding fields (the values are not used in the UI and won't be).
Add an extensive unit test and did a lot of staging tests. Here is a short video
https://github.com/evergreen-ci/evergreen/assets/64446617/13eef201-bfef-4cd0-a34a-a5d34544a2b9
Should I add documentation around generator tasks working now? I think the expectation is that they just work- so I'm not sure.

DEVPROD-6045 Make generator/generated tasks track properly for bisect stepback

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-909
vpc_id was never defined in host.create so I removed the mention of it from docs.

DEVPROD-909 Remove vpc_id from docs

---

units/generate_tasks.go

DEVPROD-6437
This saves the task ID before refetching the task

DEVPROD-6437 Fix panic caused by nil pointer dereference

---

config.go
rest/route/host_agent.go
rest/route/host_agent_test.go

DEVPROD-5419
If the task queue is empty, assignNextAvailableTask won't hit [this line](https://github.com/evergreen-ci/evergreen/blob/49a0c6894aa286e65db45b2ea016be8b9a6320ba/rest/route/host_agent.go#L605) to check if it should return true to indicate shouldRunTeardown. 
This adds a check when taskQueue.Length is 0 to see if teardown is needed and return true if it is. 
Added a unit test and tested on staging to make sure [this](https://github.com/evergreen-ci/evergreen/commit/81a155b822cf8d26df15ff2d67cf173b7d1bebe5) is logged in splunk.

DEVPROD-5419 Add check in assignNextAvailableTask for teardown needed when queue is empty

---

agent/command/papertrail_trace.go
agent/command/papertrail_trace_test.go
config.go
docs/Project-Configuration/Project-Commands.md

DEVPROD-6292
This commit makes a small change to papertrail.trace so it returns an error if none of the filename patterns in use match a file on disk.
Additionally, it fixes a bug and adds a test associated with working directory parsing. This bug is what prompted failing without matches, because it was very hard to debug without the error. The bug was fixed by switching to GetWorkingDirectory().
I added two new tests and altered two others. The altered tests now ensure we're handling relative working directories correctly. One of the new tests checks to ensure that traces without the working directory set work correctly. The other new test checks that we error out if we don't trace at least one file.
I also added a note about the "traces at least one file" requirement to the command …

DEVPROD-6292: require matches for papertrail.trace

---

model/lifecycle.go
model/lifecycle_test.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
rest/route/agent_test.go

DEVPROD-5223
This makes it such that when a task is restarted, the `activated_by` field changes to the user / caller that restarted it rather than always keeping the field equal to the person who initially created the task.
Existing tests.

DEVPROD-5223 Pass caller to restarted task's ActivatedBy field

---

cloud/ec2.go
model/host/db.go
model/host/db_test.go
model/host/host.go
rest/data/host.go
units/migrate_volume.go
units/migrate_volume_test.go
units/sleep_scheduler.go
units/spawnhost_start.go
units/spawnhost_start_test.go
units/spawnhost_stop.go
units/spawnhost_stop_test.go

DEVPROD-3951
This does a couple of things to make the spawn host stop/start jobs work with sleep schedules:
* When the host is stopped/started successfully, the next stop/start time is scheduled.
* Retry on error when stopping/starting the host, but reduce the max wait time spent in exponential backoff. Before, it could wait up to 2 minutes between checks when polling AWS for the host status, and the jobs didn't retry failed attempts. Now, it waits at most 1 minute between host status checks and the job retries properly.
* No-op the stop/start if it's not scheduled to stop/start. This could happen if the host is taking too long to stop/start.
* Fixed a trivial issue where I noticed the BSON tags in the sleep schedule data model were wrong.
* Tested in staging that the …

DEVPROD-3951: add sleep schedule-specific actions to start and stop jobs

---

agent/command/papertrail_trace.go
agent/command/papertrail_trace_test.go
config.go
docs/Project-Configuration/Project-Commands.md

DEVPROD-6269
This commit skips integration testing papertrail.trace on MacOS because all MacOS hosts currently run outside of AWS. Hosts running outside of AWS cannot bypass corpsecure when talking to Papertrail. This will change in the future when we migrate MacOS hosts to AWS, but for now we should skip testing there and document that this is unsupported.
This commit has no functional changes
I updated the Project-Commands docs file with this information

DEVPROD-6269: skip papertrail.trace testing on mac

---

model/task_lifecycle.go
rest/route/host_agent.go
rest/route/otel.go
thirdparty/github.go

DEVPROD-5317
add tracing for host agent end task
https://ui.honeycomb.io/mongodb-4b/environments/staging/result/tC3ag9ShgWA/trace/hBoQnTFVri6?fields%5B%5D=s_name&fields%5B%5D=s_serviceName&source=query&span=86644ab9b12567ab
tested on honeycomb

DEVPROD-5317 Add otel tracing for host agent end task

---

agent/otel.go
config.go

[DEVPROD-5783](https://jira.mongodb.org/browse/DEVPROD-5783)
Even with batching we're still over the gRPC limit sometimes. Let's use the same batch size as the SDK batch processor.

DEVPROD-5783 use the sdk's default queue size

---

agent/agent.go
agent/agent_test.go
agent/task_context.go
agent/task_context_test.go
config.go

DEVPROD-6168
The OOM tracker is currently broken because the oom tracker's [Check](https://github.com/mongodb/jasper/blob/main/oom_tracker_linux.go#L26) function must run before [Report](https://github.com/mongodb/jasper/blob/main/oom_tracker.go#L25) runs, and when we set it as part of the [end task details](https://github.com/evergreen-ci/evergreen/blob/main/agent/agent.go#L1132), this generates a Jasper report before check has a chance to run, meaning it's always empty. This PR sets the OOM details after the check for OOM lines and pids is run.
Hard coded an OOM kill into Jasper, and confirmed that [before](https://spruce-staging.corp.mongodb.com/task/sandbox_git_env_test_test_restart_on_fail_6620152e4761ed0007f44d6e_24_04_17_18_30_06/logs?execution=1&logtype=agent) the change, no OOM …

DEVPROD-6168 Retrieve OOM details only after it's been checked

---

thirdparty/github.go
thirdparty/github_test.go

DEVPROD-5990
This adds a `RevokeInstallationToken` which has some basic honeycomb tracking. As well, makes other functions that generate a token and use it only through the lifetime of that function, to also call and revoke those tokens as an added security measure. The error returned in this instance is ignored since it's not _vital_ we revoke it but a nice to have- the honeycomb span also tracks if it was actually revoked but only so that we can maybe later query for success rate.
Unit testing

DEVPROD-5990 Add RevokeInstallationToken and call it for internal functions that use a one time use token

---

model/github_app_auth.go
model/project_ref.go
model/project_ref_test.go

DEVPROD-5980
This adds a SetGithubAppCredentials method receiver to the ProjectRef. This is designed to remove the entry for empty arguments because when we test for existence, we specifically test if an entry is in the database- not it's values.
Unit testing

DEVPROD-5980 Add SetGithubAppCredentials to ProjectRef struct

---

makefile

DEVPROD-4234
Our `make lint-*` had a [security bump last March](https://github.com/evergreen-ci/evergreen/pull/6315#issue-1621703690) and added a package dependency `sha256sum`. The same thing can be done using `shasum` which is on every macos host (which most of the Evergreen team uses).
Running make lint-graphql, make lint-model, and it passing the download/install step (I also made sure it is actually comparing the SHA by editing the `goLintINstallerChecksum` variable and it failing).

DEVPROD-4234 Switch sha256sum to shasum available on macos by default

---

model/project_ref.go
model/project_ref_test.go

DEVPROD-2239
There is a bug in GetActivationTimeForVariant that causes variants to not activate if the last version that had that variant activated did not have activate_at set. It ends up setting it to zero time when trying to add a zero batch size to zero time and then activating it.  
added a unit test
This being the cause of 112 versions not being activated can be verified by searching for the build variant name [here](https://mongodb.splunkcloud.com/en-US/app/search/search?earliest=1706128126&latest=1706300926.001&q=search%20index%3Devergreen%20created%20build%20%7C%20spath%20project_identifier%20%7C%20search%20project_identifier%3D%22atlasproxy%22%7C%20spath%20version%20%7C%20search%20version%3Datlasproxy_d31ea2aa83fef051b0e3b91ad9c70c2bd42aeb21&display.page.search.mode=fast&dispatch …

DEVPROD-2239 Fix bug that causes variants to not activate

---

thirdparty/github.go

DEVPROD-5990
This fixes a nil response panic when invoking `RevokeInstallationToken`

DEVPROD-5990 Fix nil response panic

---

agent/command/papertrail_trace.go
agent/command/papertrail_trace_test.go
config.go
docs/Project-Configuration/Project-Commands.md

DEVPROD-6683
This commit removes the previous restrictions on papertrail.trace on MacOS. We have allow-listed the necessary IP addresses while we transition to AWS hosts, so there shouldn't be any more failures
The existing tests should cover this!
Removed the note about this command not running on MacOS

DEVPROD-6683: allow papertrail.trace on macos

---

cloud/ec2.go
cloud/ec2_test.go

DEVPROD-6348
There's a job that periodically bumps the expiration time for unexpirable hosts to make sure they don't get terminated by the AWS reaper. However, it can also bump the expiration for stopped unexpirable hosts, which don't have any IP address. Only update the persistent DNS + IP address for running unexpirable hosts.
N/A

DEVPROD-6348: only set persistent DNS for running unexpirable hosts

---

config.go
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-5576
Added a tiny change to include the patch alias name and source in validation; this should be helpful for the server especially now as they're migrating aliases around.
Added to unit test.

DEVPROD-5576 include source and patch alias name in validation

---

model/project_ref.go
model/project_ref_test.go
rest/data/commit_queue.go
rest/route/admin_test.go

DEVPROD-4678
Tweaked query to consider the type of merge queue.
Original commit queue query wasn't modified to consider the type of queue, so we were continuing to create the merge queue job for projects that were using the new queue, affecting our error rate.
Updated unit test.

DEVPROD-4678 create commit queue jobs only for legacy queue

---

agent/background.go
config.go

DEVPROD-6729
Remove critical log for heartbeat timeout due to a task exceeding its exec/idle timeout. Since this is typically caused by overusing the host's resources (like getting an OOM), it'll show up as a system failure to the user. It seems like this is an issue that can be diagnosed in the task itself and doesn't need to show up in our error alerting.
N/A
N/A

DEVPROD-6729: reduce agent critical logs

---

rest/route/user.go

Add more information about the route to migrate an existing user to a new username + some potential pitfall if the new user already exists.

docs: improve information on rename user route

---

docs/Project-Configuration/Project-Configuration-Files.md

Noticed that there was an example in the project config that basically just duplicates a snippet of the example already above it. Seems like it can be deleted.

docs: remove duplicate exec_timeout_secs example

---

agent/agent.go
agent/util/ec2.go
config.go
model/host/db.go
model/host/hostutil.go
operations/host_provision.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go
rest/data/host.go
rest/model/host.go
rest/route/host.go
rest/route/host_agent.go
rest/route/host_agent_test.go
rest/route/host_test.go
rest/route/service.go

DEVPROD-6752
Worth calling out that I thought this bug was fixed a long time ago, but apparently it's still an issue. So most of this change is actually a copy-paste to make it work better, not wholly new logic. There will be a follow-up PR to finalize the fix and remove the redundant fallback logic after this one is deployed.
The app server starting hosts is a rather error-prone and race-heavy process because EC2 operates separately from the Evergreen apps, so EC2 hosts can end up doing things that aren't always in sync with what Evergreen thinks is the current state of affairs. Hosts are created in a two-step process:
1. [It requests the host from EC2](https://github.com/evergreen-ci/evergreen/blob/fe548c06abac8878db33b1fab2fa98c759685085/units/provisioning_create_host.go#L409)
2. [It …

DEVPROD-6752: add route to fix building hosts that are running

---

units/host_allocator.go

DEVPROD-2269
This adds all of the [metrics](https://github.com/evergreen-ci/evergreen/blob/d14e6b9b731ba240dd597c5e4f419c12ac35493a/units/host_allocator.go#L261-L283) we're currently sending to Splunk for the host allocator job to OTel.
[staging example](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/eiaxJVEf4Bv/trace/tbcvWE3g1HM?fields[]=s_name&fields[]=s_serviceName&source=query&span=58610e4a07a30529)

DEVPROD-2269 Add more metrics to host-allocator span

---

model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go

DEVPROD-6601
This switches the midway task function to get the midway task, and if it doesn't exist, the closest one (with a lower order revision number). 
It switches the function to us ByBeforeRevision instead of directly a find.
Unit testing and staging (view comment left for screenshots/explanation)

DEVPROD-6601 Get task before midway task if midway task is not found

---

model/project_ref.go
model/project_ref_test.go
rest/data/commit_queue.go
rest/route/admin_test.go

Reverts evergreen-ci/evergreen#7776
Re some conversation in [`#evergreen-ops`](https://mongodb.slack.com/archives/G979SL0HM/p1714502763037629), some projects are missing a merge queue field, so the legacy commit queue is silently not picking up new commits.

Revert "DEVPROD-4678 create commit queue jobs only for legacy queue"

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-6975
This parameter was just missing from the documentation before.
None needed
Fixed!

DEVPROD-6975: document work_dir in papertrail.trace

---

model/host/host.go
model/host/host_test.go

DEVPROD-4693
Temporary exemptions as a feature already work, but there's not a way to set a temporary exemption in the UI right now. This adds a DB helper so that Spruce can add options for users to set a temporary exemption in DEVPROD-4200.
Per the design, a temporary exemption can be extended to at most a month from today.
N/A

DEVPROD-4693: add helper to set temporary exemption

---

rest/route/select.go
rest/route/select_test.go
rest/route/service.go

DEVPROD-6682
This adds an interface for [Evergreen Interfaces/APIs for Test Selection](https://docs.google.com/document/d/1UcK211V7_wLYTdE31OGsj9QZufJ-MQmIUBJgxUkYemw/edit#heading=h.1jak40y4seja). It takes a list of tests and then returns that list unchanged. This is intended for developers working on the integration before the test selector is ready.
This is unit tested.
This will auto-generate API v2 docs.

DEVPROD-6682 Add test selection interface

---

model/task_lifecycle.go

DEVPROD-6986
Using project ID adds an extra lookup step for users.

DEVPROD-6986 Switch honeycomb version tracing to project identifier

---

model/task/task.go
model/task/task_test.go

DEVPROD-6607
unset annotations cache when restarting task (or else everything is a known issue!) 
added to unit test

DEVPROD-6607 unset annotations cache when restarting task

---

graphql/query_resolver.go
model/project_ref.go
model/project_ref_test.go
rest/data/commit_queue.go
rest/route/admin_test.go

[DEVPROD-4678](https://jira.mongodb.org/browse/DEVPROD-4678)
Flipped the logic of the original PR to just avoid projects that are explicitly set to github's queue.
Unit tests

DEVPROD-4678 avoid creating commit queue jobs for merge queue

---

units/host_setup_script.go

DEVPROD-6651
Only let the spawn host setup script run for 30 minutes at most. From looking at Splunk, the only ones that ran for more than this were clearly stalled and just running their script forever (until the app server restarted). In any case, I don't think it's reasonable to ask the app servers to do work for >30 minutes for a very long-running script, that seems like it would be better for the user to run something like that in their own SSH session.
Didn't really seem worthwhile to add unit tests for a timeout.
N/A

DEVPROD-6651: limit how long spawn host setup script can run

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go

[DEVPROD-6951](https://jira.mongodb.org/browse/DEVPROD-6951)
Each API call calls Create on its client. Now that we're using IRSA to auth this means that each API call is preceded by [a call to STS to get creds](https://github.com/aws/aws-sdk-go-v2/blob/b0a3c24ad3d64508103806eec1bd2db566bf6a88/credentials/stscreds/web_identity_provider.go#L131-L133). This is likely why we're seeing STS throttling.
This PR caches the AWS client config in memory. This way, we only call STS once per region per session duration (one hour by default). Now that we're going to be holding onto the HTTP client over the entire lifetime of the application it doesn't make sense anymore to deal with the HTTP client pool, so Close() is no longer needed.
I was able to start a host in staging.
It's kind of hard to tell if …

 DEVPROD-6951 cache the AWS sdk configuration

---

github_app.go
thirdparty/github.go

DEVPROD-7003
This exposes the wrapped github client in the evergreen package which adds a Close function, and then consumes that struct in some internal github client code.

DEVPROD-7003 Expose close function for github client's underlying http client usage

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-5373
Add a clause in the docs that if no revisions are specified, it will clone all modules
I made sure this behavior happens by running with config:
```
modules:
- name: spruce
owner: evergreen-ci
repo: spruce
branch: main
- name: parsley
owner: evergreen-ci
repo: parsley
branch: main
#######################################
#######################################
functions:
get-project:
- command: git.get_project
type: setup
params:
directory: evergreen
#######################################
#######################################
tasks:
- name: my-task
commands:
- func: get-project
- command: shell.exec
params:
script: |
echo "I finished getting the project and modules"
#######################################
#######################################
buildvariants:
- name: …
```

DEVPROD-5373 Add a clause if no revisions are specified then git.get_project will clone all modules

---

config.go
operations/fetch.go
operations/fetch_test.go

DEVPROD-2647
This helper function is supposed to deduplicate files downloaded by `evergreen fetch` by adding indexes to the file name (e.g. `my_file_(1).txt`, `my_file_(2).txt`). The issue was that the file name being passed in was actually the full file path including the directory, and sometimes the directory would also have periods in it, so the helper would add the index to the directory instead of the file name (e.g. `/home/hello.world/file.txt` became `/home/hello_(1).world/file.txt` instead of `/home/hello.world/file_(1).txt`). To work around this, I kept the directory as-is, and then used the file name alone to splice in the index.
Also fixed a spot that had a potential deadlock in the error case. It's not that big of a deal, but it seemed easy enough to not deadlock the …

DEVPROD-2647: fix file deduplication in evergreen fetch

---

rest/data/distro.go
rest/data/distro_test.go

DEVPROD-5578
Clear the distro's task queue when disabling it (as is already advertised in Spruce UI).

DEVPROD-5578 Clear distro task queue when disabling it

---

model/build/build.go
model/lifecycle.go
model/lifecycle_test.go
model/task/task.go
rest/model/build.go
rest/model/task.go
scheduler/task_finder_test.go

DEVPROD-4597
This removes unused `Tags` fields on both the build and the task struct.
Existing tests

DEVPROD-4597 Remove unused build / task Tags field

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-5079
Task groups cannot have tags applied to them. We don't include them in the parameters but it's also nice to include an explicit disclaimer that they are _not_ supported

DEVPROD-5079 Document task groups not being allowed to have tasks

---

graphql/mutation_resolver.go
graphql/project_resolver.go
graphql/tests/mutation/setPatchVisibility/data.json
graphql/tests/query/commitQueue/data.json
graphql/tests/task/patch/data.json
rest/data/commit_queue.go
rest/data/patch_test.go
rest/model/patch.go
rest/route/patch_test.go

DEVPROD-6873
projects with GitHub merge queue enabled cannot have their patches enqueued to to the commit queue
cannot enqueue patches anymore with routes or calling graphql queries manually (tested by not disabling button and clicking it)
button disabled on version page 
disabled on project patches page 
disabled on user patches page

DEVPROD-6873 Disallow projects with GitHub merge queue to enqueue patches

---

agent/agent.go
config.go
operations/agent.go

DEVPROD-7031
The perf team is working on migrating Cedar to Kanopy and they hit an error while the agent was trying to connect to Cedar. I included some more log info about which particular host hit the issue so it's more traceable in Splunk (and wrapped it in a helper).
It's just a logging change, so it didn't seem that worthwhile to add tests.
N/A

DEVPROD-7031: log host ID when agent is exiting with error

---

globals.go
model/user/db.go
model/version_db.go
model/version_db_test.go
repotracker/repotracker.go
repotracker/repotracker_test.go
rest/route/github.go
units/periodic_builds.go
units/periodic_builds_test.go

DEVPROD-6548
Use the previous version's author by default, otherwise use a new periodic build user for readability (i'll add this via rest API after approval).
Right now for periodic builds we just leave author blank; for papertrail.trace they expect tasks to have an author associated (which also just seems reasonable). 
Augmented unit tests.

DEVPROD-6548 use authors for periodic builds

---

units/patch_intent.go
units/patch_intent_test.go

DEVPROD-3876
Makes our patch intent job ignore duplicate key errors when inserting patches. This can happen when the context suddenly is cancelled and the intent job attempts to take the job again.
Add section in unit test

DEVPROD-3876 Patch intent job should ignore duplicate key errors for GH merge queue

---

config.go
environment.go
globals.go
operations/service.go

[DEVPROD-6951](https://jira.mongodb.org/browse/DEVPROD-6951)
Give ourselves some breathing room by switching to static auth while we sort out the STS issues.
Will open a parallel PR on evergreen-deploy shortly.
Works in staging.

DEVPROD-6951 add static auth

---

go.mod
go.sum
model/generate_test.go
model/project_parser_db.go
model/project_parser_s3.go
model/project_parser_storage.go
model/project_parser_test.go
model/task/generated_json_db.go
model/task/generated_json_s3.go
model/task/generated_json_storage.go
model/task/generated_json_storage_test.go
rest/data/version_test.go

[DEVPROD-6951](https://jira.mongodb.org/browse/DEVPROD-6951)
https://github.com/evergreen-ci/pail/pull/111 made that pail caches the session so it won't need to make calls to STS for each time we create a bucket. This PR go gets the new pail.
Can still load logs in staging, fwiw.

DEVPROD-6951 pail AWS SDK session caching

---

agent/command/exec.go
agent/command/exec_test.go
agent/command/shell.go
agent/command/shell_test.go
config.go
docs/Project-Configuration/Project-Commands.md

DEVPROD-2281
Add option to prepend paths to the `PATH` env var for shell.exec. subprocess.exec already supports this option, so most of the logic is being reused.
After this is merged, I'll also merge https://github.com/evergreen-ci/shrub/pull/51.
* Updated unit tests for shell.exec.
* Tested manually in staging to verify that setting `add_to_path` prepended more paths to `PATH`.
Updated docs for shell.exec.

DEVPROD-2281: support add_to_path in shell.exec

---

docs/Project-Configuration/Project-Commands.md

[Slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1715005340215039?thread_ts=1714755036.600649&cid=C0V896UV8)
The wording around parameters set by `downstream_expansions.set` is a little ambiguous, so I thought it was worth clarifying that the parameters will appear on the child patch that receives the expansions, not the parent patch that sets them.

docs: clarify downstream params in child patch

---

units/spawnhost_start.go
units/spawnhost_stop.go
units/unexpirable_spawnhost_stats.go

DEVPROD-3955
The stats for host uptime are already logged but they're not that easy to query in Splunk because it's a map. I modified it a little bit to make it easier to query/make dashboards.
Tested in staging to verify the log format.
N/A

DEVPROD-3955: reformat sleep schedule stats to be more queryable

---

units/host_setup_script.go

DEVPROD-6651
The spawn host setup script job has to long poll the host to wait until the task data (from `evergreen fetch`) has been loaded on the spawn host (this is because the script was originally designed to run only once all the task data is loaded on the host). Since these requests can get stuck indefinitely waiting to connect (e.g. due to the host being terminated), polling for task data needs a timeout as well.
Didn't seem worth testing since it's a timeout change.
N/A

DEVPROD-6651: time out connections to check task data

---

rest/data/host.go

DEVPROD-6752
After #7796 is deployed, all intent hosts should send their EC2 instance ID to this route. In the unlikely case that it doesn't, we should not let it continue provisioning because it doesn't have a proper host ID and without that ID, the host document will remain in a bad state. Just letting them error, stop provisioning, and eventually get reaped is good enough, as I suspect this case will rarely get hit.
Already tested this change in staging as part of #7787.
N/A

DEVPROD-6752: return error if intent host does not provide instance ID

---

model/host/host.go
units/unexpirable_spawnhost_stats.go

DEVPROD-4264
Add tracking for how often people request temporary exemptions and how long. Since there's no limit on how many times a user can request an exemption (only that it cannot be longer than a month), this is useful to better monitor how people use this feature.
Tested in staging to verify the log appeared.
N/A

DEVPROD-4264: add monitoring for temporary exemptions

---

model/host/db.go
model/host/host.go
model/host/host_test.go
units/sleep_scheduler.go
units/sleep_scheduler_test.go

DEVPROD-7063
Once a temporary exemption has expired, the sleep schedule will behave correctly (i.e. the sleep schedule will run on its configured schedule), but it's a little neater/less bug-prone if we clear out expired temporary exemptions. Otherwise, if we just left the timestamp alone, it could cause confusion in the UI if the user sees an old/expired temporary exemption and wonder if they still have a temporary exemption in effect. I decided that it's best to just clear temporary exemptions once they've expired to avoid any confusion/potential bugs.
* Add sleep scheduler logic to clear temporary exemptions (and set a next stop/start time) once they've expired.
* Clear the next stop/start when setting temporary exemptions.
* Tested in staging to verify that …

DEVPROD-7063: handle expired temporary exemptions

---

units/stats_sysinfo.go
units/stats_test.go

[DEVPROD-5486](https://jira.mongodb.org/browse/DEVPROD-5486)
The system info struct is not meaningful in the context of a container running on a machine with other stuff.
We have the stats we need in Prometheus (and possibly Honeycomb soon).

DEVPROD-5486 remove system stats

---

globals.go
model/event/host_event.go
rest/data/host.go
trigger/host_spawn.go
trigger/host_spawn_test.go
units/provisioning_create_host.go
units/spawnhost_modify.go
units/spawnhost_start.go
units/spawnhost_start_test.go
units/spawnhost_stop.go
units/spawnhost_stop_test.go

DEVPROD-4474
The sleep schedule will stop/start hosts frequently, so users who are subscribed to spawn host change notifications probably don't want to see this. I filtered it so that the recurring notifications don't get sent. Users can still see all the stop/start events in the host event log if they wish.
* Check and filter spawn host notification if the sleep schedule stops/starts the host successfully.
* Only log a spawn host stop/start error if the job runs out of attempts and ends in error (i.e. failed to stop/start the host after retries). This reduces some noise in case there are transient errors stopping/starting the host.
* Tested in staging that notifications were suppressed when the sleep schedule successfully stopped/started the host. Persistent errors …

DEVPROD-4474: suppress sleep schedule notifications

---

environment.go
units/host_allocator.go
units/patch_intent.go

DEVPROD-6625
This introduces a max time that the patch intent processor and host allocator job can run, in the hopes that it prevents these jobs from getting stuck in the future. Per this [suggestion](https://jira.mongodb.org/browse/DEVPROD-7230?focusedCommentId=6345805&focusedId=6345805&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-6345805), this change also introduces a timeout for all Amboy queries in the hopes that it mitigates stuck queries. Looking at the Amboy cluster profiler, it looks like 10 seconds is a fair turnaround time during normal operation.
Existing tests

DEVPROD-6625 Set amboy DB timeout

---

model/host/db.go

DEVPROD-7063
The original query in #7872 is a correct query, but is slightly more optimized if it filters the host status. That allows the query to use the collection's indexes more efficiently.
N/A

DEVPROD-7063: check host status when clearing temporary exemption

---

units/sleep_scheduler.go

DEVPROD-7335
Set the scopes on the sleep scheduler to ensure that only one such job can run or be in the Amboy queue at a time. Prevents potential races that could happen if two sleep schedulers ran concurrently to manage sleep schedules.
Didn't seem worth testing since this is an Amboy feature.
N/A

DEVPROD-7335: set scope for sleep scheduler job

---

cmd/load-smoke-data/load-smoke-data.go
graphql/integration_atomic_test_util.go
model/host/db.go
model/host/db_test.go
model/host/host.go
model/host/host_test.go

DEVPROD-7418
The task queue page would occasionally perform an extremely slow query due to possibly using the wrong index this pr adds a hint to the query.
Test in production! Since the query planner only sometimes uses the wrong index its difficult to test this locally. The hope is that the hint will force it to consistently use a known fast index.

DEVPROD-7418 Ensure index is used for fetching task queue distros

---

config.go
operations/patch.go

DEVPROD-3663
Pass through the repeat flags.
Tested using https://spruce.mongodb.com/patch/6647a107bad5d90007db19cb/configure/tasks.

DEVPROD-3663 support repeat flags for patch-file command

---

makefile
self-tests.yml

[DEVPROD-6680](https://jira.mongodb.org/browse/DEVPROD-6680)
We aren't using dists anymore so we can safely remove the make target and tasks that use it.
Thought more about Annie's questions from https://github.com/evergreen-ci/evergreen/pull/7352 about consolidating the build-and-push tasks into a single variant. `self-tests.yml` is a little more verbose now, but it is really nice to have it all in the same variant. Still seems nice to have it in a variant separate from testing.
A subsequent PR will remove [the logic to handle serving dist CLIs](https://github.com/evergreen-ci/evergreen/blob/80f2f43e406e38fd316bfae3716a6c50788dd83a/environment.go#L1279-L1329).
Created patches to test [the main build-and-push](https://spruce.mongodb.com/version/664bc666a622d000082fe8de/tasks?sorts=STATUS%3 …

DEVPROD-6680 remove dist task

---

model/project.go
model/project_matrix_test.go
model/project_parser.go
model/project_parser_test.go
model/project_selector.go
model/project_selector_test.go
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-6943
This changes variant's erroring on unmatched tasks/tags to be a validation warning rather than translation error. Variants will still warn if they match _no_ tasks. 
I'm not sure how to differentiate the warnings without using too much domain specific logic, please critic as such!
Unit testing and I ran tests locally with the config showed in the ticket

DEVPROD-6943 Unmatching tasks/tags in variants resulting in a validation warning rather than a translation error

---

graphql/generated.go
graphql/schema/query.graphql
graphql/schema/types/annotation.graphql
graphql/schema/types/distro.graphql
graphql/schema/types/patch.graphql
graphql/schema/types/project.graphql
graphql/schema/types/project_settings.graphql
graphql/schema/types/project_vars.graphql
graphql/schema/types/subscriptions.graphql
graphql/schema/types/task.graphql
graphql/schema/types/version.graphql

DEVPROD-7439
By our GraphQL guide, array items should never be null i.e. `["a", null, "c"]` should not be allowed. This will help fix some TypeScript errors on the frontend.
- Tests should pass

DEVPROD-7439: Make array items non-nullable

---

docs/Reference/Limits.md

Our current docs say there is no patch limit size, but it is actually 100MB.

Docs: update max patch size

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-7159
Updates our set downstream expansions documentation to include when it no-ops.

DEVPROD-7159 Update set downstreams expansion documentation to include no-op requesters

---

rest/route/host_agent.go

DEVPROD-7496
[BF-31821](https://jira.mongodb.org/browse/BF-31821)
Despite the comments in the BF, the reoccurence of this BF is due to a bug that's not related to the original host decommissioning bug. This time, the host ran 4 tasks in the task group. When it requested the next task, it should have received the 5th task in the task group, but [according to Splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?earliest=1714837320&latest=1714837380&q=search%20index%3Devergreen%20i-0dc02d730e25c0db6&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&sid=1716324343.22093443), it actually got an indication that there were no more task group tasks to run. Because of this, it ran teardown group and moved onto a new standalone task (the later task …

DEVPROD-7496: add more logging for next task teardown

---

agent/agent.go
agent/agent_test.go
agent/command.go
agent/task_context.go
apimodels/agent_models.go
config.go
docs/Project-Configuration/Project-Commands.md
rest/model/task.go

DEVPROD-5122
Follow-up to #7880. That PR added support to show user-defined tags in the REST API for the command that causes the task to fail. This PR supports showing those user-defined tags for commands that fail but don't cause the task to fail. For example, a post command that fails with `post_error_fails_task: false` will appear in the list of other failed commands, along with its tags (if any). On top of just showing command tags, this feature could also be more generally used to more easily deduce out which commands in the task failed (rather than scroll through all the task logs for failed commands).
Note that the list of failed commands could be quite long depending on how much people are relying on pre/post to continue on error. I don't think it would be problematic though …

DEVPROD-5122: show failing commands that don't fail the task in task end details

---

model/lifecycle.go
model/lifecycle_test.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go

DEVPROD-6991
This removes display tasks and single host task group tasks from the `CheckUsersPatchTaskLimit`, in favor of immediately updating the user's patch task scheduling limit with the number of tasks in the group / display task when marking the task to reset upon completion. This can be safely done because a display task and a single host TG task will only ever reset if it has been previously marked as `ResetWhenFinished = true`.
For display tasks, since we cannot know in advance which tasks will fail when marking `ResetFailedWhenFinished`, we'll pessimistically assume all tasks will need to be reset. For the time being, the benefit of making this perfectly accurate is likely not worth the potential complexity.
Existing tests and added more test cases confirming that display tasks …

DEVPROD-6991 Account for single host TG and display task limit upon SetResetWhenFinished

---

model/project_ref.go
model/project_ref_test.go
rest/data/project_settings.go
rest/data/project_settings_test.go
rest/model/project.go
rest/model/project_test.go

DEVPROD-5977
This adds a new field to the project ref, `GitHubTokenPermissionByRequester` which is a list of `GitHubDynamicTokenPermission`. These store what requesters have access to what permission levels.
Unit testing

DEVPROD-5977 Add GitHub dynamic access token permission groups to project ref

---

config.go
operations/patch.go
operations/patch_util.go

DEVPROD-5918
user was receiving errors while trying to patch with default tasks and variants in local evergreen settings. 
this just logs that local tasks are being used 
locally tested with user's case

DEVPROD-5918 Add log when using local tasks for patch

---

cloud/pod_util_test.go
go.mod
go.sum
rest/data/pod.go
rest/data/project.go
rest/data/project_settings_test.go
rest/data/project_test.go
rest/route/project.go
rest/route/project_test.go
rest/route/sns.go
units/container_secret_cleanup.go
units/container_secret_cleanup_test.go
units/pod_allocator.go
units/pod_creation.go
units/pod_creation_test.go
units/pod_definition_cleanup.go
units/pod_definition_cleanup_test.go
units/pod_definition_creation.go
units/pod_definition_creation_test.go
units/pod_health_check.go
units/pod_health_check_test.go
units/pod_termination.go
units/pod_termination_test.go

[DEVPROD-6951](https://jira.mongodb.org/browse/DEVPROD-6951)
Get [the changes to cache the config](https://github.com/evergreen-ci/cocoa/commit/2e730fcd1784daf69d07b1471ce05f95135f1d7d).
If the tests pass I will merge this PR without a review, unless someone would like to review it.
Ran [a container task](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2004_container_test_auth_39d037e57cca47901275f980374d155d1f55db58_24_05_22_20_28_20/tests?execution=1&sortBy=STATUS&sortDir=ASC) on staging. It ran smoothly and I didn't see any errors in Splunk.

DEVPROD-6951 update cocoa

---

model/project.go
model/task/db.go
model/task/task.go
units/patch_intent.go
units/patch_intent_test.go

[DEVPROD-6266](https://jira.mongodb.org/browse/DEVPROD-6266)
Description
--repeat-patch was relying on BuildProjectTVPairs to create the variant tasks for patches. However, that resulted in a previous patch of: {bv1: t1, bv2: t2} ending up with {bv1: t1, bv1: t2, bv2: t1, bv2: t2}. This fixes that by reusing the variant tasks from the previous patch and applying the filtering on top of that instead of just on the tasks.
Testing
Existing unit tests and testing on staging.

DEVPROD-6266 Fix duplication for --repeat-patch 

---

validator/distro_validator.go
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-6656
UI added a distro warning field but this needs to be added to the validator before it makes sense to surface there. 
A follow up PR will unhide this field on the UI. 
Added unit tests
Will make sure the platform team is aware of this feature so that they can make use of it.

DEVPROD-6656 surface distro warnings in validator

---

rest/route/annotations.go

DEVPROD-7579
While experimenting I noticed that we had the wrong endpoint documented for the create annotation route.
https://docs.devprod.prod.corp.mongodb.com/evergreen/API/REST-V2-Usage#tag/annotations/paths/~1tasks~1%7Btask_id%7D~1annotations/put

DEVPROD-7579 Update annotations endpoint route in documentation

---

docs/Project-Configuration/Task-Runtime-Behavior.md

DEVPROD-5122
Add documentation for how to set command failure tags using the agent's status endpoint.

DEVPROD-5122: add docs for setting failure metadata tags using status endpoint

---

model/host/host.go
model/host/host_test.go

DEVPROD-7549
Explicitly prevent users from selecting a sleep schedule where the host is off 24/7. While this kind of schedule sounds kind of similar to the option to keep a host off indefinitely when stopping it, it's not really the same because the option to keep a host indefinitely off just means it'll stay off (and ignore the sleep schedule waking hours) until the user chooses to turn it back on. In contrast, a schedule that keeps a host off 24/7 means it should never be awake, and would logically prevent the user from ever turning on their host.
* Tested in staging that trying to set this schedule from the UI produced a validation error.
* Added unit test.
N/A

DEVPROD-7549: error if creating sleep schedule that is always off

---

graphql/mutation_resolver.go
model/host/host.go
model/host/host_test.go

DEVPROD-7550
Fix a bug where the sleep schedule's next stop time might be bumped too far in the future because the next start time is set on the schedule first. Both next start and next stop should be based on the current moment. For example, if it's 3pm right now and the user sets the host to a 9am - 5pm schedule, the next stop should logically be at 5pm today. However, the prior logic would set the next stop to 5pm tomorrow because it looked for a next stop time after the next start time (which is at 9am tomorrow).
N/A

DEVPROD-7550: fix calculating next stop time when editing schedule

---

model/generate.go
model/generate_test.go

BF-32559
When adding dependency edges to the graph, we were passing in g.Task which is the generator task instead of passing in newTask which is the current task in the list of tasks being generated. This caused a bug where for each new task it was adding the edges going into the GENERATOR instead of the edges going into that new task. 
Fixed and expanded the unit testing.

BF-32559  Fix bug in generated task dependency check 

---

docs/Project-Configuration/Evergreen-Data-for-Analytics.md

DEVPROD-7452
Have a new view for AWS task costs.
N/A
Updated user-facing documentation for "Evergreen Data for Analytics".

DEVPROD-7452: Add documentation for new AWS task costs view in data warehouse

---

units/generate_tasks.go

DEVPROD-7058
This isn't the actual fix (which will be posted in a separate PR), it just improves the logs in generate.tasks a little bit for the future so they're easier to trace.

DEVPROD-7058: improve logging to trace generate.tasks

---

api/host.go
apimodels/task_log.go
cmd/evergreen/evergreen.go
globals.go
model/push.go
model/task_history.go
plugin/attach_plugin.go
repotracker/repotracker.go
service/middleware.go
service/service.go

[DEVPROD-7728](https://jira.mongodb.org/browse/DEVPROD-7728)
These constants came up as unused in a code analyzer tool and they are all old so they should be safe to remove.
Existing tests

DEVPROD-7728 Remove unused constants

---

model/alertrecord/alert_bookkeeping.go
model/event/host_event.go
model/host/db.go
model/host/db_test.go
trigger/host.go
trigger/host_test.go
units/spawnhost_expiration_warning.go
units/spawnhost_expiration_warning_test.go

DEVPROD-4183
Add logic to notify the user when the temporary exemption is 2 hours and 12 hours away from expiring, which are the same as the current spawn host expiration warning thresholds. This reuses the same "spawn host expiration" subscription that users can already subscribe to in their notification preferences, so we don't need to add a new subscription option just for this.
Before this is deployed, I'm going to build an index for the alert record query so that it can find the most recent alert record efficiently.
* Tested in staging that temporary exemption notifications were sent to Slack/email as expected when it was close to expiring.
* Tested in staging that regular spawn host expiration warnings still work like before.
N/A

DEVPROD-4183: send notification if temporary exemption is expiring

---

go.mod
go.sum

DEVPROD-7058
Upgrade Amboy for https://github.com/mongodb/amboy/pull/343. If the generate.tasks job has this same issue again, it'll handle it gracefully and the issue will show up in the Splunk logs.
Existing tests compile.
N/A

DEVPROD-7058: upgrade Amboy

---

self-tests.yml

DEVPROD-3138
Upload prod deploy artifacts to both new bucket and old bucket temporarily. This is so that we can smoothly transition from deploying from the old bucket to using the new one once Evergreen devs are informed of how to deploy to prod from the new bucket.
Ran a patch in staging and manually verified that the artifacts were uploaded to the old and new buckets. Also, build-and-push in this PR patch should succeed.
Will update docs and send comms about how to use the new bucket once https://github.com/10gen/kernel-tools/pull/437 and https://github.com/evergreen-ci/evergreen-deploys/pull/28 are merged.

DEVPROD-3138: upload deploy artifacts to new bucket

---

model/project_ref.go
model/project_ref_test.go
rest/data/project_settings_test.go
rest/model/project.go
rest/model/project_test.go
thirdparty/github.go

DEVPROD-5978
This adds an intersection function for our GitHub dynamic access to get the most restrictive permissions between them. This will be needed when we add the agent route/code that should create a token with the most restrictive permissions.
We want to avoid hard coding as much as possible with GitHub's values so this uses reflection (see [Config](https://github.com/ZackarySantana/evergreen/blob/a2ea4040c4dfad5fe588235a56690c42142e8aea/config.go#L283) or [ProjectConfig](https://github.com/ZackarySantana/evergreen/blob/a2ea4040c4dfad5fe588235a56690c42142e8aea/model/project_config.go#L51) as existing examples). I wanted to avoid using reflection, but I think it's the cleanest way to avoid some heavy hard coding and it is still more efficient than an alternative like parsing it back …

DEVPROD-5978 Add intersection function for GitHub dynamic access token permission groups

---

api/host.go
graphql/mutation_resolver.go
service/host.go
service/host_test.go
units/crons.go
units/crons_remote_minute.go
units/host_monitoring_external_termination.go
units/host_monitoring_external_termination_test.go
units/host_monitoring_idle_termination.go
units/host_status.go
units/host_status_test.go
units/host_termination.go
units/provisioning_user_data_done.go
units/stats_amboy.go
units/task_monitor_execution_timeout_test.go
units/util.go

DEVPROD-7586
Previously we would falsely mark hosts as terminated if they were decomissioned and we couldn't verify their status -- this wasn't too problematic since they'd likely get cleaned up by spot, and reaper worst case, but now that we don't use spot, we often rely on the reaper timeout, which is pretty long. We should instead leave these hosts decommissioned so we'll try terminating again.
Moved termination to a queue group to avoid termination jobs gumming up the regular queue, in the worst case.
Tweaked existing unit tests.

DEVPROD-7586 avoid falsely marking decomissioned hosts as terminated

---

units/host_drawdown.go
units/host_drawdown_test.go
units/host_monitoring_idle_termination.go
units/host_monitoring_idle_termination_test.go

DEVPROD-7768
BF-31821
The code change isn't actually that large, just lots of lines/tests got moved around to refactor.
This fixes 2 issues where the idle termination job would terminate hosts running single host task groups too eagerly:
1. Give single host task groups more grace period to be idle. If the host/task lifecycle finished one task and was a little slow to get to the next task in the single host task group, it would get idle terminated after 1 minute. This is undesirable because the only options once a single host task group is terminated is to start over all the way from the beginning (or in the case of BF-31821, create more BFGs).
* I could be convinced to turn this into an admin setting rather than a constant if we really want it to be configurable.
3. Don't terminate hosts …

DEVPROD-7768: idle terminate single host task group hosts less aggressively

---

model/project_vars.go
rest/data/project_test.go
rest/route/project.go

DEVPROD-2446 
DEVPROD-5685 
1) Printing IDs is super annoying; made a change to print identifiers.
2) Added an option to only look at enabled projects (this isn't fool proof but I think it's good enough; I think this is really only useful for debugging. We could enforce that also)
3) Drive-by removed artifact rotation (DEVPROD-5685) since it doesn't work, and infra has a workaround if this is ever needed.
Added a unit test and confirmed existing unit tests still work.
updated swaggo

DEVPROD-2446, DEVPROD-5685 improve /rotate route

---

docs/Project-Configuration/Project-Commands.md
units/generate_tasks.go

DEVPROD-7058
Follow-up to https://github.com/mongodb/amboy/pull/343 - When saving generate.tasks errors back to the task document, if the error string is really long, the job could hit the 16 MB size limit and prevent the error from saving to the task. Unfortunately, the task document is already tight on space because it saves the entire generate.tasks JSON file in it, which could be up to 16 MB large, so the max error message length is set pretty conservatively.
Note that the problem could still happen in an edge case, I just made it much less likely. For example, if the task doc is filled to almost 16 MB by generated JSON input, and then it can't accommodate even the shortened 1 MB error message. I believe this means we'll eventually have to re-apply #7303 or otherwise store multi-MB …

DEVPROD-7058: truncate long generate.tasks errors

---

config.go
operations/validate.go

DEVPROD-4090
Before, during config validation we would just no-op when we get an error. This treats the error as an error and says it to the user.
Built and ran locally. I didn't add unit testing since it's not that easy to add for this one, and pretty niche. We don't test that in our other commands from what I saw- since the crux of it is just API requests that error for this command return nil rather than the error (seems like a typo / mishap, git blame dates it back 6 years).

DEVPROD-4090 Error when receiving a server error when validating config

---

cmd/evergreen/evergreen.go
go.mod
go.sum

[DEVPROD-5483](https://jira.mongodb.org/browse/DEVPROD-5483)
By default go doesn't see its number of CPUs is limited by a cgroup. Including this library will set GOMAXPROCS to the appropriate number of CPUs. noops if running outside a container.
In staging [it limited to 1 CPU](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Ddevprod-evergreen-staging%20%22maxprocs%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=1717710628.406&latest=1717710638.407&sid=1717711403.25667179), which is consistent with [the CPU limit](https://github.com/evergreen-ci/evergreen-deploys/blob/4fc29d8d298d8465958e24dc8c1a9d51aaa04cb8/charts/staging.yml#L12). Interestingly, the [CPU time we used actually went …

DEVPROD-5483 add automaxprocs

---

model/artifact/artifact_file.go

[DEVPROD-7904](https://jira.mongodb.org/browse/DEVPROD-7904)
https://github.com/evergreen-ci/evergreen/pull/7712 special cased the `mciuploads` bucket to allow us to rotate the key. The strategy there was to use the app's role to generate the presigned URL. The issue with this is that the presigned URL is only valid so long as the signing credentials are valid and the credentials we get for the app's role are temporary. So if you happen to get a presigned URL just before the app's credentials expire your link will expire soon thereafter.
From [the AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html#PresignedUrl-Expiration): (h/t @julianedwards)
> If you created a presigned URL using a temporary credential, the URL expires when the credential expires. …

DEVPROD-7904 use static credentials for presigning

---

util/webhook_grip.go
util/webhook_grip_test.go

DEVPROD-7773
I can see that Evergreen is sending webhook notifications, but they're oftentimes receiving errors back from the webhook URL. Unfortunately, there's not enough info in the error message to easily figure out which of the many webhooks it's sending to, so this PR adds more info.
* Add extra logging information when receiving non-200s from the webhook server.
* Increase timeout for webhook notification. I noticed a couple of the webhook notifications just errored due to request timeout, so giving them a little more time may let the webhook server process them.
* Checked the logging looked sufficient in staging.
N/A

DEVPROD-7773: increase timeout and add more logging for webhook notification errors

---

model/generate.go
model/generate_test.go
model/lifecycle.go
model/task_lifecycle.go
model/task_lifecycle_test.go

DEVPROD-6129
Right now, when a generated task is stepped back and in the version stepback tries to activate it, it does not exist (because the generator was not ran), it will activate the generator and then activate _all_ generated tasks. This change updates our logic to only activate stepback generated tasks from the generator (and ones who have "activate: true").
We have some existing logic that's tracking "GeneratedTasksToActivate" but it isn't working as intended- and once the generator finishes it will activate all.
This PR updates some of the testing (I found a small race-condition bug) for linear stepback's handling of generated tasks, fixes that small bug, and makes (more) use of the "GeneratedTasksToActivate" field.
Unit testing and staging testing (screenshots below for staging …

DEVPROD-6129 Activate only the generated tasks that need to be activated when stepping back

---

agent/internal/testutil/task_config.go
config_test.go
environment.go
github_app.go
github_app_test.go
graphql/project_settings_resolver.go
graphql/repo_settings_resolver.go
model/github_app_auth.go
model/project_ref.go
rest/data/host_create.go
rest/route/agent.go
rest/route/github.go
thirdparty/github.go

DEVPROD-5991
These two functions both were attached to the evergreen.Settings struct despite not using much from settings. I reversed it to take in a provider and then made our GithubAppAuth struct implement the interface as well.
I debated about making it just depend on the struct, but that would make everywhere that uses this to create the struct (essentially calling the interface's function) and then having their own error checks. With the interface, it reduces some code duplication and makes it a little more hidden.
EDIT: I removed the interface
Existing unit tests

DEVPROD-5991 Make CreateInstallationToken and HasGitHubApp work for user apps

---

go.mod
go.sum

This reverts commit 8a19aac9a2009f33d799d19ba215628a890de9d9.

Revert "CHORE: Bump gonum.org/v1/gonum from 0.14.0 to 0.15.0 (#7975)"

---

github_app.go
model/github_app_auth.go
model/github_app_auth_test.go
model/project_ref.go
rest/route/agent.go

DEVPROD-5993
This combines the struct and uses the new user app for the agent route
Existing testing

DEVPROD-5993 Combine GithubAppAuth structs and use the user's app for agent route

---

docs/Project-Configuration/Project-and-Distro-Settings.md

Came up in [Slack](https://mongodb.slack.com/archives/C0V896UV8/p1718046556434419) - we don't currently describe what a webhook can expect to receive when subscribing to a notification, so I added more details.

docs: describe expected payloads for webhook notifications

---

rest/route/github.go

DEVPROD-5859
There may be an edge case where a project does not have the correct merge queue
state after a database update. This adds logging to help debug the issue.

DEVPROD-5859 Log when merge group event is not processed

---

docs/Project-Configuration/Project-and-Distro-Settings.md
repotracker/repotracker.go
repotracker/repotracker_test.go

DEVPROD-7953
Use git tag pusher as git tag version author when able, otherwise default to what we do now (using the author of the commit that the tag was pushed to).
Added to unit test.
Updated to make sure its clear this needs to be added to settings for it to work.

DEVPROD-7953 use git tag pusher as version author when able

---

config.go
operations/host_spawn.go
rest/client/interface.go
rest/client/methods.go

DEVPROD-8230
Add CLI option to keep host off. The logic for the route to use this flag was already implemented, so the CLI just needs to pass the option along in the request body.
Tested in staging that `evergreen host stop --keep-off` stopped the host and kept it off.
Docs will be bulk updated as part of DEVPROD-4055 so that it coincides with sleep schedule comms.

DEVPROD-8230: add CLI option to keep unexpirable host off indefinitely

---

graphql/host_resolver.go
graphql/task_resolver.go

DEVPROD-8099
Removed err.Error() messages when err is nil in AbortInfo resolver.

DEVPROD-8099: Fix nil dereference errors in AbortInfo resolver

---

graphql/tests/projectSettings/projectRef/results.json
rest/model/project.go

DEVPROD-8338
I don't think the UI propagates the merge queue type, so when the GH/commit queue project settings are saved, the field is always empty, which then reverts the project back to the legacy commit queue. All projects should be using the GH merge queue so it this seems like it's fine to auto-set it.
There's gonna be a follow-up DB update to re-switch projects back over to the GH merge queue if they were accidentally reverted to the legacy commit queue.
1. I reproduced the issue in staging with the sandbox. I manually switched the project to the GH merge queue, edited the commit queue alias, saved, and then checked the DB and the commit queue was invisibly reverted from the GH merge queue back to the legacy commit queue.
2. Did the same thing as 1 after applying my fix, and it …

DEVPROD-8338: switch default commit queue type to GitHub merge queue

---

model/version.go
model/version_test.go

DEVPROD-1617
When pinging /projects/{project_id}/versions (e.g. https://evergreen-staging.corp.mongodb.com/rest/v2/projects/zackary-bisect/versions) with a body that has `{ "include_builds": true, "include_tasks": true }` it should return the builds and the tasks. It does return the builds, but the tasks are just empty strings. This makes it also return the tasks.
Added some unit testing and did staging test.
```
"tasks": [
"zackary_bisect_generated_ubuntu_generated_task_1_c92ca45d46807777699d8dace4032c5b2a70e396_24_06_05_15_46_36",
"zackary_bisect_generated_ubuntu_generated_task_2_c92ca45d46807777699d8dace4032c5b2a70e396_24_06_05_15_46_36",
"zackary_bisect_generated_ubuntu_generated_task_3_c92ca45d46807777699d8dace4032c5b2a70e396_24_06_05_15_46_36", …
```

DEVPROD-1617 Add task information to projects version route

---

model/event/host_event.go
model/event/task_event.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go

DEVPROD-5318
[An example HC trace](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/cT2VBKpd4CE/trace/aKkt735hVpG?fields[]=s_name&fields[]=s_serviceName&span=7a2f6ea93711e813) (and other examples I looked through) suggest that the slowest part of end task is marking dependencies unattainable after a task fails that has lots of dependencies. For example, if one of the compile tasks in a server patch fails, it spends all of end task blocking thousands of tasks that depend on compile before the request eventually times out.
This attempts to optimize it by reducing the number of round-trips to the DB. It's the same update, but instead of doing thousands of single updates, it'll instead do one big bulk update. I'm not that confident that this will improve …

DEVPROD-5318: update unattainable dependencies in bulk

---

model/task_lifecycle.go

DEVPROD-7034
This fixes a bug that was preventing mainline commit versions from having a version-completion trace.
Tested in [staging](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/BFbjssqGfiK?hideCompare) to confirm repotracker versions now have the version-completion trace

DEVPROD-7034 Fix mainline version-completion trace

---

graphql/mutation_resolver.go

DEVPROD-7552
If spawning an unexpirable host in the UI and setting a sleep schedule, do not start the host unless the sleep schedule is valid.
Setting a sleep schedule isn't required until the feature is fully rolled out, so it's still an optional parameter for now. Later on, it'll be a required field for creating unexpirable hosts.
Tested in staging by trying to spawn a host with an invalid sleep schedule and checked that it errored + didn't make the host.
N/A

DEVPROD-7552: validate sleep schedule before spawning host

---

model/project.go
model/project_matrix_test.go
model/project_parser.go
model/project_parser_test.go
model/project_selector.go
model/project_selector_test.go
validator/project_validator.go
validator/project_validator_test.go

This reverts commit b7a571dc55cf0c52e87deef41d391f02424d54bd.
Reverting due to [user-reported issue](https://mongodb.slack.com/archives/C0V896UV8/p1719349145144089) that seems related.

Revert "DEVPROD-6943 Unmatching tasks/tags in variants resulting in a validation warning rather than a translation error (#7821)

---

graphql/generated.go
graphql/schema/types/patch.graphql
graphql/schema/types/project.graphql
model/patch/patch.go
model/patch/trigger_intent.go
rest/model/project.go
units/patch_intent.go
units/patch_intent_test.go

DEVPROD-7529
This adds a new field on the patch trigger definition that specifies which revision to base the downstream patch off of, rather than having it always default to the latest revision for the downstream patch.
The team requesting / using this will only be setting this via API, should we keep this feature API-only?
Confirmed expected behavior in staging + unit test

DEVPROD-7529 Allow patch trigger aliases to specify revision

---

agent/command/github_generate_token.go
agent/command/github_generate_token_test.go
config.go

DEVPROD-5986
Redacts the token generated from `github.generate_token` calls.
Unit testing

DEVPROD-5986 Add expansion redaction for github.generate_token

---

model/github_app_auth.go

DEVPROD-8420 
I realized when working on https://github.com/evergreen-ci/evergreen/pull/8036 that it's very easy to accidentally mix up githubAppAuthAppId and githubAppAuthIdKey. I shortened the names to try to bring more clarity. We have some precedence of keys without the name of the struct as part of it.

DEVPROD-8420 Rename Keys 

---

github_app.go

DEVPROD-5981 
This is step one in moving over to always using the app Id. After this I'll run the script to fix all the db entries.

DEVPROD-5981 Fix flipped bool

---

graphql/version_resolver.go

DEVPROD-8097
Removed redundant nil check, and updated the returned error message for the initial nil check.

DEVPROD-8097: Remove redundant nil check in ChildVersions resolver

---

docs/Project-Configuration/Project-Commands.md
docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-5246
Adds module field in build variant, and some links referencing it in the modules and git.get_project docs

DEVPROD-5246 Add modules in the build variants fields

---

model/distro/distro.go
model/distro/distro_test.go
model/task/db.go
model/task/db_test.go

DEVPROD-7643
Added GetLatestTaskFromImage function to query database and retrieve the latest task from all the distros corresponding to the imageID. 
Added TestGetLatestTaskFromImage function to ensure function works correctly. Also ran bson queries that mimic function and it took ~200 milliseconds per query.

DEVPROD-7643: Add GetLatestTaskFromImage function to query database

---

graphql/task_resolver.go
graphql/util.go
graphql/util_test.go

DEVPROD-6860
These code changes allow users to query `task.Annotation` if they are the patch author or have a valid annotation view permission. 
UI pages where `task.Annotation` is displayed alongside non-gated information are affected and I adjusted those pages to allow rendering in the corresponding [UI PR](https://github.com/evergreen-ci/ui/pull/208)

DEVPROD-6860: Gate permissions for Task.Annotation in GraphQL

---

model/project.go

DEVPROD-8514
If the most recent mainline commit has an invalid parser project, log an error so it's traceable but doesn't appear in our alerts.

DEVPROD-8514: reduce log level for invalid parser project

---

thirdparty/runtime_environments.go
thirdparty/runtime_environments_test.go

DEVPROD-7639
Added getOSInfo method to query runtime environments API given an AMI. 
Wrote TestGetOSInfo and validated correct results with independent testing using grip debug statements.

DEVPROD-7639: Create getOSInfo method to query Runtime Environments API

---

model/lifecycle.go
model/patch_lifecycle.go
model/task/task.go
model/task/task_test.go

DEVPROD-6088
This includes the `EstimatedNumActivatedGeneratedTasks` field for generator tasks when considering a user's patch task scheduling limit.
Add a unit test

DEVPROD-6088 Include scheduling estimations for generator tasks in limit

---

agent/command/git_test.go
config_test.go
model/patch_lifecycle_test.go
model/project_test.go
operations/cli_integration_test.go
operations/fetch_test.go
repotracker/github_poller_test.go
repotracker/repotracker_test.go
thirdparty/github_test.go
trigger/project_triggers_test.go
units/commit_queue_test.go
units/patch_intent_test.go

DEVPROD-6000
This removes the reliance on the github oauth token in tests. The smoke test will be done separately in [DEVPROD-5999](https://jira.mongodb.org/browse/DEVPROD-5999) and agent-command will be done separately in [DEVPROD-8701](https://jira.mongodb.org/browse/DEVPROD-8701). 
yes

DEVPROD-6000 Remove the github oauth token from tests 

---

.github/dependabot.yml
go.mod
go.sum

This reverts commit 17ae2c511b5419cd7342e18e219aa96e35cc824a.
That version of GRPC is golang 1.22 which updates our go mod file.

Revert "CHORE: Bump google.golang.org/grpc from 1.64.0 to 1.65.0 (#8069)"

---

globals.go
model/event/subscribers.go
model/event/subscriptions.go
rest/data/project_settings.go
rest/data/project_settings_test.go
rest/model/subscriber.go
rest/model/subscriber_test.go

DEVPROD-7946
This adds redaction to the webhook secret and authorization in the ui and API.
Unit and staging tests
For staging I just deployed, added a couple headers (one being Authorization), and changed the values and changed unrelated values and checked the db for the secret value, making sure it updates when appropriately and never updates to the `<REDACTED>` value.

DEVPROD-7946 Redact webhook secret and authorization from UI and API

---

agent/command/git.go
agent/command/git_push.go
agent/command/git_push_test.go
agent/command/git_test.go
config.go

DEVPROD-8736
After https://github.com/evergreen-ci/evergreen/pull/7146 the token we are redacting is an app token not an oauth token. I didn't capitalized github because it will show up as part of the url like so: 
https://[redacted oauth token]:x-oauth-basic@github.com/evergreen-ci/evergreen.git

DEVPROD-8736 rename the redaction log for the token oauth --> github

---

config.go
go.mod
go.sum

DEVPROD-7548
Upgrade aviation to use the default keepalive timeout for Cedar grpc connections.
https://github.com/evergreen-ci/aviation/pull/57
N/A

DEVPROD-7548: upgrade aviation

---

agent/command/git_test.go
agent/internal/client/mock.go
config.go
scripts/setup-credentials.sh
scripts/setup-smoke-config.sh
self-tests.yml

DEVPROD-6001
This converts all tests (include smoke tests)
[This commit](https://spruce.mongodb.com/version/668eadc8dff1e40007f45b06/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) was ran with all the changes (except the config.go agent version update) with a different named token to make sure it is using the new token and not the existing one.

DEVPROD-6001 Use github.generate_token rather than global github_token expansion

---

config_task_limits.go
model/project_parser_s3.go
rest/model/admin.go
service/templates/admin.html

DEVPROD-6072
- Add two new task limits, one for the maximum number of large parser project tasks that can be concurrently running, and one for the maximum parser project size when degraded mode is enabled, per the two action items of the recent [engineering proposal](https://docs.google.com/document/d/1tC7rTIPb_VXld_iGn8jWgrWjJnrHNrka0rmevAgnlO0/edit#heading=h.gkhozkfcr28v).
- Introduce a parser project size hard cap for when large parser projects do get enabled.
There will be a followup PR that makes use of these two new limits.
Existing

DEVPROD-6072 Add new degraded mode associated limits

---

model/task_lifecycle.go

DEVPROD-8301
This resolves the catcher at the end of MarkEnd. Not resolving it was a programmatic error.

DEVPROD-8301 Resolve catcher at the end of MarkEnd

---

thirdparty/runtime_environments.go
thirdparty/runtime_environments_test.go

DEVPROD-8473
Added GetEvents function to thirdparty/runtime_environments to use GetHistory and GetImageDiffs.
Added testing function and used grip Debug statements to ensure proper output.

DEVPROD-8473: Add GetEvents function to thirdparty/runtime_environments to use GetHistory and GetImageDiffs

---

units/github_status_api.go

DEVPROD-8436
This reduces the size so it's viewable on smaller screen sizes. This won't work for very small screens but there's not much we can do besides something extreme like [DEVPROD-8730](https://jira.mongodb.org/browse/DEVPROD-8730)
This was the before:
This would be with the change:
This was an *alternative* design for comparison:

DEVPROD-8436 Reduce size for GitHub checks text for invalid config/project validation

---

agent/agent.go
agent/command/github_generate_token.go
agent/internal/task_config.go
agent/task_context.go
config.go

DEVPROD-5989
This adds Honeycomb traces to the command, using these we can find out what owner+repo are using the token, if they are specifying permissions, and how many successful revocations happened.
To support the traces for revoking, I added a new span for the task command cleanups and setup group command cleanups and subspans for each one they run. The rest of this PR really is just adding the attributes to the existing span and the new cleanup spans
Deployed to staging. Link to existing task's honeycomb trace [here](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen-agent/trace/aw9cNHyU6u1?fields%5B%5D=s_name&fields%5B%5D=s_serviceName&span=dfeae8971e71a609), link to new task's honeycomb trace [here](https://ui.honeycomb.io/mongodb-4b/environments/staging/dat …

DEVPROD-5989 Add Honeycomb traces to the github.generate_token command

---

units/provisioning_create_host.go

DEVPROD-8738
We've been relying on Amboy's retry mechanism producing errors in the error rate when the job has no more attempts to get alerts about persistent issues creating hosts. Instead of relying on that log (which we're reducing to a warning here: https://github.com/mongodb/amboy/pull/345), add a replacement log that we can use to alert on host creation problems.
Once this is merged, I'll adjust the error rate in production alert so that it doesn't filter out this log (it currently filters host creation job errors).
N/A
N/A

DEVPROD-8738: log when host creation fails

---

rest/model/host.go
rest/model/host_test.go
rest/route/host.go
rest/route/host_test.go

DEVPROD-8517
Expose the field containing the task ID when a spawn host is created from a task. Should be retrievable in the REST API now.
* Added unit test.
* Spawned a host from a task in staging, and checked that the task ID was populated in a REST request for the host.
Updated the auto-generated swaggo docs.

DEVPROD-8517: include spawn host task ID in API host

---

graphql/generated.go
graphql/schema/types/distro.graphql
graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql
graphql/tests/mutation/saveDistro/queries/validation_error.graphql

DEVPROD-8537
Require image ID in the GraphQL distro object. Have confirmed all staging / prod distros have this field.

DEVPROD-8537: Require imageId in GraphQL distro object

---

rest/route/patch.go

DEVPROD-1616
This removes an excerpt from the `Variants` field documentation for the /patches/{patch_id}/configure route.
The exercpt doesn't give that much useful information, is wordy, and misleads users by giving an incorrect format. Since our docs moved to automagically generate based off of code, the `variant` struct details users in our pine documentation what the field names are and we shouldn't reiterate

DEVPROD-1616 Remove confusing conflicting documentation on configure patch route

---

config.go
docs/CLI.md
model/host/host.go
model/host/host_test.go
operations/host_spawn.go
rest/data/host.go
rest/data/host_test.go
rest/route/host_spawn.go
rest/route/host_spawn_test.go

DEVPROD-7531
This is a follow-up to #8086 to let users set a sleep schedule from the REST API/CLI.
* Add CLI options to set a sleep schedule from the CLI.
* Add REST route handling for sleep schedule options (already added in #8086).
* Added unit tests for host create/modify routes.
* Tested in staging that `evergreen host create` and `evergreen host modify` set sleep schedules as expected for unexpirable hosts.
Updated docs. I didn't mention it in the unexpirable host sleep schedule info just because I wanted to keep it brief, I don't think it's that common of a workflow to create/modify hosts using the CLI, and the UI is likely more user-friendly anyways.

DEVPROD-7531: set sleep schedule from REST/CLI

---

config.go
docs/CLI.md
operations/flags.go
operations/patch.go

DEVPROD-5189
This removes the validation that prevents --repeat-failed and --repeat-patch <patch id> to be used together.
After this change, I ran `evg patch --repeat-failed --repeat-patch 668ec6e08b58d60007bd1f55` (`evg` comamnd builds local evergreen) and it produced [this](https://spruce.mongodb.com/version/6696b5768e640b000735f4c6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) patch. The failing patch I used was [this](https://spruce.mongodb.com/version/668ec6e08b58d60007bd1f55/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) one.
For unit tests, we have some existing [here](https://github.com/ZackarySantana/evergreen/blob/b40a1d76eb1cc752da5536c2e8050207ffb03a1d/units/patch_intent_test.go#L440) (also below that one we have another one) that tests doing repeat patch and repeat failed …

DEVPROD-5189 Remove patch command validation for --repeat-failed and --repeat-patch being exclusive

---

config.go
rest/client/methods.go
rest/route/service.go
rest/route/task.go

DEVPROD-8950
The route pattern was ambiguous because the router treated `/task/sync_read_credentials` as matching `/task/{task_id}` (i.e. get one task), but it's really a standalone, unrelated route. I changed the route name so it's not ambiguous.
Tested in staging that I can GET the route and it returns a valid result.
N/A

DEVPROD-8950: fix ambiguous task route

---

units/provisioning_create_host.go

DEVPROD-8738
Small amendment to #8103 - the if clause filters out hosts that aren't made by `host.create`, so I adjusted it so it logs the final attempt's error regardless of the type of host.
Didn't seem worth testing a logging change.
N/A

DEVPROD-8738: log final error for creating task hosts

---

github_app.go
gqlgen.yml
graphql/generated.go
graphql/project_settings_resolver.go
graphql/redacted_fields_gen.go
graphql/schema/types/project.graphql
graphql/schema/types/project_settings.graphql
graphql/tests/mutation/saveProjectSettingsForSection/queries/github_app_settings.graphql
graphql/tests/mutation/saveProjectSettingsForSection/results.json
graphql/tests/projectSettings/projectRef/queries/project_ref.graphql
graphql/tests/projectSettings/projectRef/results.json
graphql/tests/query/spruceConfig/results.json
model/project_event.go
model/project_ref.go
rest/data/project_settings.go
rest/data/project_settings_test.go
rest/model/project_event.go

DEVPROD-5996
Adds GraphQL support for `githubAppAuth` field in ProjectSettings.
Since this PR is already long, I will handle adding this field to the event logs (with redaction) in [DEVPROD-8877](https://jira.mongodb.org/browse/DEVPROD-8877).
* Added unit tests & GraphQL tests

DEVPROD-5996: Add GraphQL support for githubAppAuth field

---

model/generate_test.go
model/lifecycle.go
model/project_ref.go
model/project_ref_test.go
model/version.go
model/version_db.go
repotracker/repotracker.go
repotracker/repotracker_test.go

DEVPROD-5857
This is #7888 with an improvement to handle a situation where versions are created really late.
If a commit is made almost at the same time as when the cron should activate (e.g. commit at 7:59 pm, next cron run is 8 pm), we should allow the cron to activate immediately, even if Evergreen starts processing the version a tiny bit late (e.g. at 8:01 pm). This is what #7888 fixes. 
_However_, as an additional consideration, the late cron can't activate immediately if there's a cron that's already scheduled to activate or is already activating right now. To deal with this, I limited the ability to schedule late crons so that they can only be scheduled to run immediately if they're only a few minutes late _and_ no other cron activation is currently going on/just happened. If …

DEVPROD-5857: allow delayed cron activation

---

agent/command/git.go
agent/command/git_push.go
agent/command/git_push_test.go
agent/command/git_test.go
agent/command/testdata/git/multiple_modules.yml
agent/command/testdata/git/plugin_clone.yml
agent/command/testdata/git/plugin_patch.yml
agent/command/testdata/git/test_config.yml
config.go
docs/Project-Configuration/Project-Commands.md

DEVPROD-8924
Only our project and two more (one of which is a test project with a public repo so it will continue to work) passes a token to git.get_project. Once the dynamic GitHub token project rolls out, those tokens will be either oauth or GitHub app tokens. Because the url needs to be formatted differently based on the token, we need to have a way to differentiate. Because GitHub app will soon be the default, it will be a smoother experience if the default is an app token and if someone wants to use oauth, they need to set oauth to true. I'll reach out to the two projects that currently use it and have them add it before merging this. 
Tested on staging by adding a module to our self tests that already use an app token.

DEVPROD-8924 git.get_project cloning assuming tokens are always oauth

---

validator/project_validator.go
validator/project_validator_test.go

DEVPROD-3996
We've been manually making sure functions added to the `projectErrorValidators` only returns errors. This has gone well but sometimes needed a follow up PR months later. This adds some checks to make sure we only use Error. 
I added a restriction in this PR, that the `Level` field must be populated to `Error` rather than blank (which would default to `Error`) since it helps the test's correctness and it might be (it was to me for a second) why some ValidationError{} declarations didn't include a `Level` field.
I've done the same thing for the `projectWarningValidators` only returning `Warning` and `Notice`.
Unit testing. I added warning / error and then the tests would fail. The tests also work locally (if that was a concern)

DEVPROD-3996 Add test for project validations to only return respective levels

---

service/task.go

DEVPROD-9067 
Use execution from URL to get logs for files.
[first execution file](https://parsley-staging.corp.mongodb.com/taskFile/evg_ubuntu2204_upload_sample_log_patch_334c581a32d8d823020f8e5d93b96c7b10daf351_6500d3d3b237362f86002a15_23_09_12_21_11_07/0/samplelargefile )
[second execution file](https://parsley-staging.corp.mongodb.com/taskFile/evg_ubuntu2204_upload_sample_log_patch_334c581a32d8d823020f8e5d93b96c7b10daf351_6500d3d3b237362f86002a15_23_09_12_21_11_07/1/samplelargefile )
(first)
(second)
After re-deploying head, confirmed that both links show the second image.

DEVPROD-9067 use correct execution for file logs

---

cmd/evergreen/evergreen.go
config.go
operations/service_web.go

[DEVPROD-9133](https://jira.mongodb.org/browse/DEVPROD-9133)
It looks like maxprocs assumes `cfs_quota_us` and `cfs_period_us` are set, which in turn depend on the `CONFIG_CFS_BANDWIDTH` kernel configuration option. This was [added to modern versions of Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=789019), but not Jessie.
This PR moves setting GOMAXPROCS into `startWebService()` so it'll only happen in the app servers (and smoke tests and whatever), which should only be running on modern versions of Linux.
The app server started successfully in staging, and GOMAXPROCS was set appropriately.

DEVPROD-9133 only run maxprocs for the app servers

---

github_app.go
globals.go
graphql/generated.go
graphql/project_settings_resolver.go
graphql/schema/types/project_settings.graphql
graphql/tests/mutation/saveProjectSettingsForSection/results.json
graphql/tests/query/projectEvents/data.json
graphql/tests/query/projectEvents/queries/get_branch.graphql
graphql/tests/query/projectEvents/results.json
model/project_event.go
rest/data/project.go
rest/data/project_test.go
service/event_log.go

DEVPROD-8877
Show event log changes for the `githubAppAuth` field, making sure to redact the `PrivateKey` field.
- GraphQL and unit tests

DEVPROD-8877: Support showing changes to GitHub app credentials in event logs

---

graphql/generated.go
graphql/image_resolver.go
graphql/schema/types/image.graphql
graphql/tests/image/distros/data.json
graphql/tests/image/distros/queries/distros.graphql
graphql/tests/image/distros/results.json
model/distro/distro.go
thirdparty/runtime_environments.go

DEVPROD-7647
Added GraphQL support for the field: distros: [Distro!]!
Used the getDistrosForImage method to fetch the associated distros for an image.
CodeQL failing, but I did not modify the file, so will ignore. 
Added GraphQL test

DEVPROD-7647: Resolve Distros From GraphQL Image Type

---

globals.go
model/host/db.go
model/host/stats.go
rest/route/sns.go
units/host_drawdown.go
units/provisioning_create_host.go
units/provisioning_create_host_test.go
units/stats_host.go

DEVPROD-8746
* Count decommissioned hosts towards distro and global hosts limits.
* Rename some DB functions and vars that had confusing or misleading names.
* Clean up some long-expired TODOs.
Added unit test for decommissioned hosts and global hosts limit.
N/A

DEVPROD-8746: include decommissioned hosts in global hosts limit

---

graphql/generated.go
graphql/image_resolver.go
graphql/models_gen.go
graphql/mutation_resolver.go
graphql/schema/mutation.graphql
graphql/schema/types/project.graphql
graphql/tests/mutation/deleteGithubAppCredentials/data.json
graphql/tests/mutation/deleteGithubAppCredentials/queries/fail_nonexistent_github_app.graphql
graphql/tests/mutation/deleteGithubAppCredentials/queries/success.graphql
graphql/tests/mutation/deleteGithubAppCredentials/results.json

DEVPROD-9076
Adds a mutation for deleting GitHub app credentials. This corresponds to the button from the Figma designs:
PR is not that big, `make gqlgen` was outdated from Sophia's merged PR so there are a lot of generated lines.
- Added GraphQL tests

DEVPROD-9076: Create DeleteGithubAppCredentials mutation

---

cloud/ec2.go

DEVPROD-9302
* I lost my 4th grade spelling bee because I apparently can't spell easy words.
* Made the error message for starting a host consistent with the one for stopping a host.
N/A
N/A

DEVPROD-9302: fix spelling on error message

---

graphql/tests/query/projectEvents/data.json
graphql/tests/query/projectEvents/queries/no_changes.graphql
graphql/tests/query/projectEvents/results.json
model/project_event.go
rest/data/project_settings.go
rest/data/project_settings_test.go
testdata/local/github_app_auth.json

DEVPROD-8877
As I was writing the frontend code for this component, I realized I missed an edge case when checking for
```
len(changeEvent.After.GitHubAppAuth.PrivateKey) > 0 && len(changeEvent.Before.GitHubAppAuth.PrivateKey) > 0
```
I was setting the before value to `{REDACTED_BEFORE}` and the after value to `{REDACTED_AFTER}` even if they were actually the same value (unchanged).
- Added GraphQL test that does not pass without the changes in this PR

DEVPROD-8877: Fix redaction logic for githubAppAuth field

---

model/host/db.go
rest/data/host.go
units/migrate_volume.go
units/sleep_scheduler.go
units/sleep_scheduler_test.go
units/spawnhost_modify.go
units/spawnhost_start.go
units/spawnhost_start_test.go
units/spawnhost_stop.go
units/spawnhost_stop_test.go

DEVPROD-9095
* Stagger when the sleep schedule stop/start jobs can run. This is to avoid an issue where if lots of people just go with the default sleep schedule (8am-8pm Mon-Fri Eastern Time), there will be a burst of stop/start requests to AWS all at once right around those times, which triggers AWS to rate limit the requests. Spreading out the requests over a few minutes reduces the likelihood of rate limit issues.
* Start hosts a few minutes in advance of their actual startup time. We want the host to be up by the time it's supposed to wake up for its schedule, even if AWS temporarily rate limited us, so giving it more time to start up makes it more likely it'll be up at the scheduled time. Starting a few minutes earlier doesn't make a significant difference to the overall cost.
* …

DEVPROD-9095: stagger sleep schedule jobs

---

graphql/task_resolver.go
graphql/util.go
graphql/util_test.go

DEVPROD-6861
These code changes allow the user to request `Task.taskLogs` if they have the LogsView role for the project.

DEVPROD-6861: Gate permissions for Task.taskLogs in GraphQL

---

config_task_limits.go
model/lifecycle.go
model/patch_lifecycle.go
model/project_parser_s3.go
model/task/db.go
model/task/task.go
model/task_queue_service_dependency.go
model/task_queue_service_test.go
rest/model/admin.go
rest/route/degraded_mode.go
rest/route/host_agent_test.go
service/templates/admin.html

DEVPROD-6072
Implements degraded mode.
- Reduces the maximum allowed parser project size
- Reduces the number of tasks in s3 versions that can be running concurrently.
Added CPU alert in staging to fire to the alertmanager webhook at 10% CPU (to trigger it immediately). Confirmed that degraded mode turned on, and upon scheduling a bunch of tasks in s3 versions, tasks got throttled once the limit of concurrent s3 tasks were hit ([splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?sid=1721928863.1192603))

DEVPROD-6072 Implement degraded mode toggles

---

agent/internal/testutil/task_config.go
environment.go
github_app.go
github_app_test.go
rest/data/host_create.go
rest/route/agent.go
thirdparty/github.go
thirdparty/github_test.go

DEVPROD-6652
The requests that get a secondary rate limit from GitHub appear to be requesting an installation token, which means we're requesting installation tokens from GitHub too frequently. To avoid getting a new token for every single task run and every single GH API request, I added a cache to reuse tokens for Evergreen's own internal operations. However, to accommodate caching, I had to adjust a few things about how tokens are used:
* I had to remove the logic that defer revokes tokens at the end of each GitHub API call. Revoking a token after one use defeats the purpose of caching the token.
* When getting a cached token, callers now have to specify how long they need the token to be valid. This is necessary to figure out if the cached token is going to be valid for long enough to …

DEVPROD-6652: use in-memory cache for internal installation tokens

---

util/webhook_grip.go

[DEVPROD-9377](https://jira.mongodb.org/browse/DEVPROD-9377)
This is an exotic bug...
In the case where the webhook sender needs to retry it puts the client back in the pool but still holds on to a pointer to the client for the next round. In the meantime, the GitHub app [requests a client from the pool and modifies its Transport](https://github.com/evergreen-ci/evergreen/blob/3bfa042ffdf3422155ddc84c63272e302d7293db/github_app.go#L243-L244) to [overwrite the Authorization header with a new bearer token](https://github.com/bradleyfalzon/ghinstallation/blob/d680810648e94347929da00376d1e7067f3572dd/appsTransport.go#L89-L102). Subsequently the webhook sender makes the http call using the modified transport that overwrites its Authorization header.
This PR makes the webhook sender hold on to …

DEVPROD-9377 hold on to the HTTP client

---

docs/Project-Configuration/Merge-Queue.md

DEVPROD-8510
This documents merge queue behavior more fully.
**Note for reviewers:** There are a couple ways to review this directly in GitHub
1. Click the rich diff button, which is in the upper right, looks like a piece of paper, and is to the right of the `< >` symbol. This will give you a diff that is of the actual rendered markdown.
2. In the diff view, click the three dots, then "View file", to see the markdown rendered.
N/A
👀

DEVPROD-8510 Document merge queue internals

---

trigger/task.go
trigger/task_test.go

DEVPROD-4192
Task notifications currently can be sent for every task failure type except system-timed-out and setup-failed. I fixed it to send notifications for system-timed-out. (I'm not sure why setup-failed is a special case that doesn't warrant notification for task failure, but that wasn't part of the ticket.)
N/A

DEVPROD-4192: send notifications for system-timed-out tasks

---

globals.go
model/task/task.go
model/task/task_test.go
scheduler/scheduler.go
scheduler/scheduler_test.go

DEVPROD-8308
The version in question in the ticket got stuck in running because one of the tasks that runs in it runs on a distro that is frequently at capacity (`rhel81-power8-small`). Because of this the task was stuck in the queue for so long that it eventually got marked unscheduled & disabled due to being [underwater](https://github.com/evergreen-ci/evergreen/blob/1204bb07a9d27073ce14db39c52900fdb2bbbbdd/model/task/task.go#L1483).
Made a few changes:
1. Update the underwater unscheduler to log priority change events because there were none when doing this investigation
2. Change the underwater unscheduling logic to log out task IDs instead of a count of updated tasks
3. Run `UpdateBuildAndVersionStatusForTask` for modified underwater tasks so that the build/version updates properly. …

DEVPROD-8308 Update version status when unscheduling underwater tasks

---

config_task_limits.go
model/lifecycle.go
model/patch_lifecycle.go
model/project_parser_s3.go
model/task/db.go
model/task/task.go
model/task_queue_service.go
model/task_queue_service_dependency.go
model/task_queue_service_test.go
rest/model/admin.go
rest/route/degraded_mode.go
rest/route/host_agent_test.go
service/templates/admin.html

DEVPROD-6072
#8130 Was reverted because it resulted in a large number of calls to `GetConfig`, maxing out our Splunk limits.
The first commit in this PR is a re-staging of the changes in #8130 . Subsequent commits are to cache the evergreen settings in the task dispatcher, updating it every time the dispatcher refreshes itself
Tested in staging and confirmed the number of calls to `GetConfig` reduced significantly.

DEVPROD-6072 Implement degraded mode toggles with cached settings

---

environment.go

DEVPROD-8323
The attached jobs in this ticket all appear to have timed out after having excessively long queries to the MCI cluster. For [this job](https://mongodb.splunkcloud.com/en-US/app/search/search?sid=1722348706.2445878) for example, two consecutive queries to the tasks collection that each took 60 minutes before the socket was closed is why the job had a 2hr runtime. These queries show up and stick out as big outliers in the DB cluster query insights. From what I can tell (DB cluster logs don't go back that far), this is true for the other linked examples in the ticket.
I dug for a while and the 1 hour timeout doesn't appear to be related to anything in our DB client or Kanopy settings, and is most likely configured somewhere in our network infrastructure that isn't visible to us. …

DEVPROD-8323 Add query timeout to evergreen db client

---

self-tests.yml

DEVPROD-9150
Pine now has the ability to automatically check whether any changes done to your repo's documentation will be rejected by Pine (and Docusaurus) as a result of bad Markdown. It does this through an Evergreen task that is automatically triggered when a parent patch (i.e a PR in your repo) is created. This will prevent you from merging changes that will cause issues in Pine. However, we do require some setup on your end to enable this functionality for your repo.
Instructions followed here: https://docs.devprod.prod.corp.mongodb.com/pine/onboarding/#incorporating-pines-evergreen-task 
This [patch ](https://evergreen.mongodb.com/patch/66b0e254b83406000744f67b?redirect_spruce_users=true)shows the task write-downstream-expansions-for-pine.

DEVPROD-9150: Incorporate Pine's Evergreen task into Evergreen

---

docs/Reference/Limits.md

It looks like these things were updated as part of the availability project. 
cc @hadjri @bynn if you'd meant to do this as part of [DEVPROD-6977](https://jira.mongodb.org/browse/DEVPROD-6977) but I think we should update docs as we make changes to keep things as up-to-date as possible, by using the "documentation" PR template section.

docs: update task limits

---

graphql/query_resolver.go
graphql/tests/query/patch/data.json

DEVPROD-7853
This resolver was throwing an error whenever the patch had tasks deleted due to TTL. Currently, the resolver tries to determine if the patch status is aborted by querying for its tasks, and errors when it finds no tasks in the database.
I think the code in this resolver is 1. weird (status should be resolved by a `patch.Status` resolver if anything) and 2. not necessary, as it is a remnant of when Spruce wasn't able to distinguish between patches and versions. 
I deployed this on staging and verified that the versions and child patches still showed up as aborted properly:
- On staging
- Edited GraphQL test which does not pass without this patch's changes

DEVPROD-7853: Remove status calculation in patch resolver

---

makefile

[DEVPROD-9510](https://jira.mongodb.org/browse/DEVPROD-9510)
`static_assets.tgz` doesn't only depend on the `./public/static` files, but rather on everything in `public` and `service/templates`.
The new tarball is exactly the same as the old (equivalent hashes). It rebuilds now when I make a change to a template.

DEVPROD-9510 include everything in static_assets dependencies

---

model/project_ref.go

DEVPROD-9393
Add temporary feature flag to enable using Parameter Store per project. This is just to let us turn on Parameter Store in a more controlled way by setting it in the DB, users won't actually interact with this setting directly.
Checked that the feature flag was preserved even if I saved the project settings page.
N/A

DEVPROD-9393: add project-level flag for using Parameter Store

---

docs/Reference/Limits.md

The notion of "underwater" tasks is undocumented and caused a bit of confusion with users. Documenting the feature.

docs: document underwater tasks

---

agent/task_context.go
config.go

DEVPROD-6732
Fixes a panic that occurred during DB instability where the agent was presumably retrieving empty task documents, causing the required task output info field to be nil.

DEVPROD-6732 Fix agent panic

---

model/host/host.go
model/host/host_test.go
rest/data/host_create.go
rest/route/host_create.go
rest/route/host_create_test.go

DEVPROD-3968
There was a bug with `create.host` creating more hosts than it was told to create probably due to the command retrying due to failure, but the host was still created during the failure. This double checks that the number of host intents created for each command will be the same each time.
No test because this would only happen if something went wrong in a strange way

DEVPROD-3968 Validate number of hosts for create.host command

---

model/task/db.go
model/task/db_test.go

DEVPROD-4195
Disabled tasks that have been enabled in `activateTasks` do not show up in the schedulable task query since [the priority field is unset](https://github.com/evergreen-ci/evergreen/blob/f5fff80846eebd27f1622a3eadece5eff5025203/model/task/db.go#L700), preventing them from ever getting added to the task queue
Confirmed the issue no longer occurs in staging. Added a unit test.

DEVPROD-4195 Don't unset priority field when enabling disabled task

---

cmd/build-cross-compile/build-cross-compile.go
config.go

[DEVPROD-9714](https://jira.mongodb.org/browse/DEVPROD-9714)
gopsutil on macOS relies on cgo for CPU metrics ([here](https://github.com/shirou/gopsutil/blob/1e6b445a8ad4ffe097ccdb97a2f365a4e6287325/cpu/cpu_darwin_nocgo.go#L13)). In order to collect those metrics [here](https://github.com/evergreen-ci/evergreen/blob/6b7aa96e5256f9ef28f0dd65122b0ea8fe7a01b8/agent/otel.go#L179) and [here](https://github.com/evergreen-ci/evergreen/blob/6b7aa96e5256f9ef28f0dd65122b0ea8fe7a01b8/agent/otel.go#L199) we need to have cgo enabled. Although we turned it off on purpose ([here](https://github.com/evergreen-ci/evergreen/pull/5095#issue-1022996625)), it should be okay to turn cgo back on specifically for macOS which definitely has libc support.
Ran [a …

DEVPROD-9714 use cgo on macOS

---

model/task_lifecycle.go
model/task_lifecycle_test.go

DEVPROD-2527
Follow-up to #8152 - this fixes one last bug where the display task wasn't restarting properly when the last execution task finished. On the first execution where it's marked to restart when the execution tasks finish (e.g. by restarting all tasks in a patch), it would end up system failing the display task, and then on execution 1+, the display task would refuse to restart at all (because there's a limit on the number of system failure restarts).
This was because the restarting logic used `t.GetDisplayTask()`, which caches the display task after an initial lookup. If the cached display task isn't kept up-to-date, then it'll have stale data of the parent display task. This caused problems when restarting the display task because when the execution task finishes, it [updated …

DEVPROD-2527: do not system fail display task that is marked to reset

---

graphql/generated.go
graphql/image_resolver.go
graphql/image_test.go
graphql/models_gen.go
graphql/schema/types/image.graphql
thirdparty/runtime_environments.go
thirdparty/runtime_environments_test.go

DEVPROD-9475
In order to be able to paginate on the frontend, we need to know the total number of items available. The API has been updated with a new route which is what this PR uses.
500 lines from this PR were added automatically by code generation.
- Updated existing tests

DEVPROD-9475: Update Packages and Toolchains resolvers to return total and filtered counts

---

cmd/build-cross-compile/build-cross-compile.go
self-tests.yml

[DEVPROD-9714](https://jira.mongodb.org/browse/DEVPROD-9714)
#8175 was reverted because the macOS build was failing. Apparently building with cgo invokes the local C compiler (makes sense) which is missing flags that are provided by go when building for macOS (see [this issue](https://github.com/golang/go/issues/59544)). This PR cherry-picks the now-reverted changes from #8175 and builds the mac executables on mac instances.
[build-and-push succeeded](https://spruce.mongodb.com/task/evergreen_build_and_push_display_build_and_push_darwin_unsigned_patch_72f23265d19097bd5f7acc7146a4c80d380bd9bc_66ba2d0dc323d700078e3254_24_08_12_15_41_13?execution=0&sortBy=STATUS&sortDir=ASC).

DEVPROD-9714 cgo on macOS

---

model/host/hostutil.go
model/host/hostutil_test.go
rest/route/host_agent.go

DEVPROD-9348
Split from #8188.
Some static hosts are still running old versions of the agent monitor (old versions need to manually be stopped by the app server). Furthermore, some static hosts were quarantined a long time ago, so they may be running very old versions of the agent monitor. Very old versions of the agent monitor create some backward compatibility issues with the changes in https://github.com/evergreen-ci/evergreen/pull/8115 because that PR assumes that hosts will eventually roll over to the new agent monitor version. Unfortunately, we can't force them to run on the newer agent monitor version since we can't operate on a quarantined host, and it's the responsibility of the runtime environments team to bring them out of quarantine (so we could wait a very long time before …

DEVPROD-9348: revert to legacy agent monitor logic for old static hosts

---

docs/Hosts/Spawn-Hosts.md

A few people have asked about supporting hibernation for their hosts in DEVPROD-8579 rather than shutting them down entirely. Clarify that Evergreen hosts currently don't support such a thing.

docs: clarify host stopping behavior

---

rest/route/agent.go

DEVPROD-6004
Some users care about the status code more, this would be an internal error (most likely on github's part)

DEVPROD-6004 Send internal error instead of generic for invalid token generation

---

model/project_ref.go
model/project_ref_test.go
rest/route/agent.go

DEVPROD-9908
Since GitHub interprets an empty permissions as all permissions, we need to manually check if what we are sending is empty permissions.
Unit testing and deployed to staging
Added a comment since it's niche

DEVPROD-9908 GitHub token route should account for requester / intersection having no permissions

---

cmd/build-cross-compile/build-cross-compile.go
config.go
self-tests.yml

[DEVPROD-9915](https://jira.mongodb.org/browse/DEVPROD-9915)
Trying again with #8186, which was reverted because the binary wouldn't start on macos versions less than the one it was built on. Apparently this is how it's supposed to work ([docs](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html)). We need to set the `-mmacosx-version-min` flag (documented [here](https://clang.llvm.org/docs/CommandGuide/clang.html#cmdoption-mmacos-version-min)) to the minimum version we want to target. At the moment the oldest mac distros are on 10.14, but I tested setting it even older and that worked too (so we shouldn't feel that every time we retire a macOS version we need to come back here and update it right away).
The …

DEVPROD-9915 enable cgo on macos 

---

graphql/schema/types/image.graphql
thirdparty/runtime_environments.go
thirdparty/runtime_environments_test.go

DEVPROD-9928
Fixes a bug where we were returning incorrect values for the `Type` field on these events. The `Type` field should be equal to the values of our custom GraphQL enums (`"PACKAGE"`, `"TOOLCHAIN"`) but instead they were equal to the values returned directly from the API (e.g. `"Packages"`, `"Toolchains"`).
Also, although we were originally only returning package and toolchain changes, I introduced a new enum `"OPERATING_SYSTEM"` and started to additionally return OS changes since Winston said these should be included.
- Updated existing tests and wrote more tests

DEVPROD-9928: Return GraphQL enum values for ImageEventEntry.Type field

---

model/validate.go
rest/data/host.go
rest/data/task.go
rest/data/task_test.go
rest/route/host_test.go
rest/route/middleware.go
rest/route/middleware_test.go

DEVPROD-713
Completed tasks and terminated hosts shouldn't be able to make request to Evergreen, so updated the task / host middleware to reject the request in these cases. Also removed the check for the terminated host status when we fix an intent host that is mismatched with its true AWS state. 
This will cause these hosts that Evergreen believes are intent host but are actually genuine terminated EC2 instances to leak, leaving the reaper to clean them up. Since this mismatch condition is relatively rare, we can consider just allowing these hosts to leak for the sake of this change.

DEVPROD-713 Reject requests from completed tasks and terminated hosts

---

agent/internal/client/base_client.go
config.go

DEVPROD-7885
Tasks system fail without logs when we error *before* we set up loggers. 
I suspect that this happens because the macos 11 arm distro does not work well with certain golang version's io.ReadAll function and fails randomly because there is a history of that happening with certain goversions. 
The issue seemed to go away after a recent golang version update to the distros but I am adding a retry to this particular read because we would really want this to pass
will update the bf ticket with investigation update!

DEVPROD-7885 Retry reading get project body

---

environment.go

DEVPROD-8323
Since #8148 deployed we've seen a drop in long-hanging Amboy jobs, but we did just observe one occur today ([Splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?sid=1724079942.6814920)). Based on the error message the issue seems to be that the client hangs while trying to read the DB server response, so it may be that the socket was open for too long without receiving a full message. 
There is a separate [socket timeout configuration](https://www.mongodb.com/docs/drivers/go/current/fundamentals/connections/connection-guide/#connection-options) that we aren't currently using that will control how long the client waits when trying to R/W data over a connection, rather than waiting indefinitely (as it supposedly does right now).
The go driver …

DEVPROD-8323 Set socket timeout for DB client

---

config.go
config_test.go
rest/data/admin_test.go

DEVPROD-9997
The Enum only generates a single entry in the generated openAPI client code.
that entry is "announcement", which is the only one that appears to be typed.
My assumption is that this causes the Enum to not generate the other possible values.
Once the OpenAPI gets a project result, it tries to validate the input, and finds that the value (in my test case, Information) does not exist as part of the Enum.

DEVPROD-9997: fix enum configuration

---

agent/agent.go
agent/agent_test.go
agent/directory.go
agent/task_context.go
config.go

DEVPROD-5351
The task working directory and its temporary directory are currently made only when the first task in the task group runs. However, if a task deletes one (or both) of them, they'll be missing in later tasks. I modified it to ensure the directories are recreated if they're missing at the beginning of each task in the task group.
* Tested in staging by deleting the temporary directory in a task group task, then checking in a later task group task that it was recreated.

DEVPROD-5351: recreate task group working directory

---

model/project_aliases.go
model/project_aliases_test.go

DEVPROD-5739
github checks aliases being returned was causing things to fail validation silently so now they only return when it is enabled
unit test

DEVPROD-5739 Only return GitHub Checks Aliases when enabled

---

repotracker/repotracker.go
thirdparty/github.go
trigger/patch.go
trigger/version.go
units/github_status_api.go
units/github_status_refresh.go
units/patch_intent.go

DEVPROD-7824 
When sending pending statuses we don't error if there's a branch protection problem, but we do for successful statuses, which is inconsistent. Refactored this out to a helper function for simplicity.

DEVPROD-7824 ensure no error when retrieving branch protection rules

---

cloud/parameterstore/fakeparameter/db.go
cloud/parameterstore/fakeparameter/fake_parameter.go
cloud/parameterstore/fakeparameter/ssm_client.go
cloud/parameterstore/fakeparameter/ssm_client_test.go
cloud/parameterstore/ssm_client.go
cloud/parameterstore/ssm_client_test.go
self-tests.yml

DEVPROD-9623
Follow-up to #8194 to create an testing-only implementation of the SSMClient interface. Will be useful when testing code that relies on Parameter Store. This way, the unit tests can use an implementation backed by the DB rather than relying on an actual Parameter Store instance.
N/A

DEVPROD-9623: add fake Parameter Store client

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-6005
This is part two of the documentation for the dynamic github access tokens feature documenting the command itself. This will only be merged once the feature flag is flipped. 
More documentation coming in a separate PR.

DEVPROD-6005 Part Two Of Document Dynamic Github Access Tokens

---

agent/command/timeout.go
agent/internal/task_config.go
agent/task_context.go
apimodels/agent_models.go
config.go
config_task_limits.go
docs/Project-Configuration/Project-Configuration-Files.md
docs/Project-Configuration/Task-Runtime-Behavior.md
rest/model/admin.go
rest/route/agent.go
rest/route/agent_test.go
service/templates/admin.html
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-767
Looked through all the configs and found that the largest timeout is 24 hours so we will only let users specify a timeout up to 24 hours (the one 96 hour timeout task's project owner disabled his project and said it wasn't needed)
Also will be adding a splunk alert for any tasks that go over 8 hours like [this](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3D%22evergreen%22%20%7C%20spath%20path%20%7C%20search%20path%3D%22/rest/v2/task/*/heartbeat%22%7C%20spath%20duration_ms%20%7C%20search%20duration_ms%3E28800000&display.page.search.mode=fast&dispatch.sample_ratio=1&workload_pool=standard_perf&earliest=-24h@h&latest=now&display.page.search.tab=events&display.general.type=events&sid=1724358000.7550081) just so we know when there is a very long running …

DEVPROD-767 Add limit for exec timeout

---

graphql/generated.go
graphql/schema/types/host.graphql

DEVPROD-5670
- Ahead of removing the beta tester setting from the UI, make it non-required in the SleepSchedule type.
- In a followup PR once the updated UI has been deployed, I'll remove this field from GraphQL altogether
- UI functions correctly with optional field

DEVPROD-5670: Make isBetaTester field optional

---

config.go
operations/admin.go
public/static/js/admin.js
public/static/js/menu.js
rest/route/admin_banner_test.go
testutil/config.go

DEVPROD-10123
When we added project banners, we used uppercase for the GraphQL enum. But admin
banners use a lowercase type. This PR makes the admin banner also use an
uppercase type. It also ensures that both uppercase and lowercase have the same
behavior in the legacy JavaScript so that we can safely deploy this commit.

DEVPROD-10123 Consistently case admin and project banners

---

cmd/build-cross-compile/build-cross-compile.go
config.go
self-tests.yml

This reverts commit 6445c354664c04362ce567703053262f33df13f8.

Revert "DEVPROD-9915 enable cgo on macos  (#8207)"

---

model/task_queue_service.go
model/task_queue_service_dependency.go

DEVPROD-10088
These methods were unused in the task queue interface.

DEVPROD-10088 Remove unused methods on task queue interface

---

docs/Project-Configuration/Project-Commands.md
globals.go

DEVPROD-9693
Remove tenancy: host option, as we determined in the ticket.
This is a deletion so is covered by the existing tests.
Removed the tenancy: host option from the documentation.

DEVPROD-9693 Remove host tenancy from host.create

---

agent/command/s3_put.go
config.go

DEVPROD-9646
This replaces the usage of a standalone pail function that is misleading in what it does (it accepts options to presign, but doesn't) to instead use the same constructs we usually use, which is creating a bucket then calling a method on it.
The change this really does is when a user does s3.put and provides the option "skip_existing".
Here is the example task I was running:
```
- name: s3put-test
commands:
- func: clone-project
- command: s3.put
params:
aws_key: ${AWS_ACCESS_KEY_ID}
aws_secret: ${AWS_SECRET_ACCESS_KEY}
aws_session_token: ${AWS_SESSION_TOKEN}
local_file: src/evergreen.yml
remote_file: mciuploads/zackary.santana/evergreen.yml
bucket: mciuploads
region: us-east-1
permissions: public-read
content_type: ${content_type|application/x-gzip}
display_name: Binaries …
```

DEVPROD-9646 Replace usage of standalone pail function to use bucket construction instead

---

docs/Project-Configuration/Github-Integrations.md

DEVPROD-10343
Add a note to git.get_project to avoid confusion 
yes

DEVPROD-10343 Add note about git.get_project to github access token docs 

---

config_dev/project/sample.yml
docs/Project-Configuration/Controlling-when-tasks-run.md
model/project.go
model/project_parser.go
model/project_parser_db.go
model/project_parser_merge_functions.go
model/project_parser_test.go
model/testutil/api.go
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-9826
The top-level batchtime doesn't have any effect right now, so it can be removed. If any remaining YAMLs have it defined, `evergreen validate` produces a warning.
* Ran `evergreen validate` on project YAMLs and verified that for the few projects that define top-level batchtime, it emits a warning. (Those that have it just set it to 0)
Removed docs about top-level batchtime.

DEVPROD-9826: remove unused top-level batchtime

---

model/patch/patch.go
units/github_status_refresh_test.go
units/patch_intent.go

DEVPROD-2749
The patch document contained a field called display_new_ui which was used as a flag to determine if we should show the redirect_spruce_users query param in the cli. We don't need this since redirect_spruce_users will already handle redirecting users who are opted into the new UI.

DEVPROD-2749 remove patch.DisplayNewUI

---

docs/Hosts/Spawn-Hosts.md

DEVPROD-8228
Update docs for the end of the beta period. Not going to merge this until the beta ends on Tuesday Sept 3.
* Remove beta period docs.
* Remove docs for option to use the user-owned script. I didn't see anyone mention that they used it, nor do the repo stats suggest anyone cloned it, so I assume it's unused. I think it's safe to remove given that there's not much interest.

DEVPROD-8228: update docs for end of beta test period

---

docs/API/REST-V2-Usage.mdx

Noticed a new user was confused about how to use the REST v2 API. It seems like the docs don't mention anywhere on the page that the REST v2 URL format is always in the form `https://evergreen.mongodb.com/rest/v2/<ROUTE>`.

docs: clarify REST v2 URL prefix

---

graphql/generated.go
graphql/image_resolver.go
graphql/image_test.go
graphql/schema/types/image.graphql
model/task/db.go
rest/model/image.go
thirdparty/runtime_environments.go
thirdparty/runtime_environments_test.go

DEVPROD-10372
Remove these fields from the `Image` object because they aren't consistent across all images i.e. not all images, particularly Windows and Mac, have these properties.
Also fix a small issue with `latestTask` because it should be acceptable to return nil if a task has never ran on an image.

DEVPROD-10372: Remove unused fields from GraphQL Image object

---

go.mod
go.sum

DEVPROD-1919
Upgrade Jasper for https://github.com/mongodb/jasper/pull/382. The SSH library code has never been used so nothing is affected by this.
* Code compiles.
* Tested in staging to verify that a spawn host still provisions normally.
N/A

DEVPROD-1919: upgrade Jasper

---

model/distro/distro.go
model/host/hostutil.go
model/host/hostutil_test.go
operations/agent_monitor.go
operations/agent_monitor_test.go
units/provisioning_agent_monitor_deploy.go

DEVPROD-9923
The MacOS hosts have recently had trouble deploying new agent binaries. The suspected issue is that some of the MacOS hosts have SIP enabled, and those hosts are SIGKILL'ing the binary if it has some issue (such as running with CGO enabled or running an Evergreen binary that hasn't been signed by Apple). This problem persists even if a new version is downloaded that fixes the original issue - the binary still gets SIGKILL'd after redownloading a valid Evergreen agent to the file path. The workaround we found (that was found long ago during an identical outage) was to `rm` the binary, which seemed to fix the issue.
* Remove the Evergreen binary when downloading the agent monitor onto MacOS hosts.
* Remove the Evergreen binary when downloading the agent onto MacOS hosts.
* …

DEVPROD-9923: remove Evergreen client on MacOS task hosts

---

cloud/parameterstore/fakeparameter/parameter_record_db_test.go
cloud/parameterstore/parameter_cache.go
cloud/parameterstore/parameter_cache_test.go
cloud/parameterstore/parameter_manager.go
cloud/parameterstore/parameter_manager_test.go

DEVPROD-9403
Follow-up to #8231. This adds the in-memory parameter cache that will hold the parameter values that have already been retrieved during Evergreen app runtime. Reading values from the cache instead of reading directly from Parameter Store each time will reduce our API calls and keep Evergreen's usage within the Parameter Store rate limits.
To reduce the size of the PRs, this isn't used yet. A follow-up PR will actually integrate the cache with the parameter manager so that the caching and real Parameter Store all work as intended.
N/A

DEVPROD-9403: add parameter cache

---

graphql/query_resolver.go
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/results.json

DEVPROD-10176 - #8254 followup
- Fix bug where converting `[]WaterfallBuildVariant` to `[]*WaterfallBuildVariant` was creating an array of pointers to the same address (I think), resulting in this type of response:
If there's a more Go/more efficient way to do this I'd love to know!
- Updated resolver test so that it fails without these changes

DEVPROD-10176 bugfix: Correctly convert slice to slice of pointers

---

config_db.go
config_serviceflags.go
graphql/generated.go
graphql/schema/types/host.graphql
graphql/schema/types/spawn.graphql
graphql/tests/mutation/spawnHost/queries/spawn_host.graphql
graphql/tests/mutation/spawnHost/results.json
model/host/db.go
model/host/db_test.go
model/host/host.go
rest/model/admin.go
service/templates/admin.html
units/sleep_scheduler_test.go

DEVPROD-6908
The beta test for unexpirable host schedules has ended, so the beta test fields aren't needed. At this point, even if there were problems, we wouldn't revert back to the beta test; we would just disable the feature using the sleep schedule admin flag.
* Delete the feature flag for the beta test.
* Delete the beta test flag from the host model and GraphQL.
Code compiles and existing tests pass.
N/A

DEVPROD-6908: remove sleep schedule beta test fields

---

config.go
docs/CLI.md
operations/evaluate.go

DEVPROD-9526
Updating some documentation to be clear about us not supporting this right now. (Removed a matrices reference to keep the description shorter, and because we've deprecated this.)

DEVPROD-9526 clarify that evaluate command excludes module includes

---

service/version.go

DEVPROD-10153
Logging the whole project isn't secure and the identifier should be enough to trace from.

DEVPROD-10153 Log project identifier rather than whole project struct

---

graphql/generated.go
graphql/models_gen.go
graphql/patch_resolver.go
graphql/schema/types/patch.graphql
graphql/schema/types/version.graphql
graphql/tests/patch/generatedTaskCounts/data.json
graphql/tests/patch/generatedTaskCounts/queries/patch.graphql
graphql/tests/patch/generatedTaskCounts/results.json
graphql/tests/version/generatedTaskCounts/data.json
graphql/tests/version/generatedTaskCounts/queries/version.graphql
graphql/tests/version/generatedTaskCounts/results.json
graphql/version_resolver.go

DEVPROD-7444
Changes the data structure for estimating generator task activated task counts from a map to its own dedicated type to take advantage of GraphQLs strong typing safety.
Existing tests

DEVPROD-7444 Use strongly typed data structure for generated task estimation counts

---

model/generate_test.go
model/lifecycle.go

DEVPROD-10040
When adding generated tasks, we add the ones in existing builds and the ones in new builds separately. When adding tasks to existing builds we would also find and dependencies and activate them. However, when adding tasks to new builds we skipped this step. This would cause tasks generated with dependencies in new builds to not activate dependencies and therefore block the task from running.  
Added a unit test and tested on staging. 
[patch before changes ](https://spruce-staging.corp.mongodb.com/version/66db352f7ac0800007d64fac/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[patch after changes ](https://spruce-staging.corp.mongodb.com/version/66db6da8d9ad170007246cb1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

DEVPROD-10040 Activate dependencies in new builds too 

---

model/task_queue_service_dependency.go

DEVPROD-10086
This adds a nil pointer check inside of the task queue dispatcher logic. I don't think we've ever hit it, but I imagine if we did it would be bad.

DEVPROD-10086 Add nil pointer check inside of task queue dispatcher

---

model/host/db.go

DEVPROD-11146
If the `err` is non-nil from the driver, `res` might be nil, so check for nil before using it.
Not really testable since it requires the driver to error, but it's not hard to reason about by inspection.

DEVPROD-11146: check nil response for update

---

cloud/parameterstore/fakeparameter/parameter_manager_test.go
cloud/parameterstore/parameter_cache.go
cloud/parameterstore/parameter_manager.go
cloud/parameterstore/parameter_manager_test.go
cloud/parameterstore/ssm_client.go
model/github_app_auth.go

DEVPROD-9403
This is the last PR to get parameter caching to work with Parameter Store. The previous PRs (#8231 and #8262) introduced the parameter cache and the parameter records collection that contains info on when parameter were last updated. This PR integrates those two into the parameter manager so that it uses the cache when it's possible to get the parameter's value.
* Bump the parameter record when updating/deleting a new parameter.
* When reading a parameter, use the cache if possible.
* Use the parameter record to decide if the cached value is sufficiently up-to-date or not.
* Fall back to reading from Parameter Manager directly (and caching the value) if the cache doesn't have the parameter or the cache is outdated.
* Existing tests also test with caching enabled/disabled.
* …

DEVPROD-9403: use parameter cache

---

agent/agent.go
agent/task_context.go
config.go
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-767
there are multiple tasks among multiple projects with a long exec timeout so we shouldn't error but warn and set the timeout to be lower. 
unit test updated

DEVPROD-767 Warn if task exceeds max exec timeout

---

rest/data/patch_intent.go
rest/route/github.go
rest/route/github_test.go
units/github_status_api.go
units/patch_intent.go
units/patch_intent_test.go

DEVPROD-9092
For projects with the merge queue enabled on GitHub but not Evergreen, we were not sending a response to the merge queue because of a few superfluous `FindOneProjectRefWithCommitQueueByOwnerRepoAndBranch` that would fail and block the patch intent from being created.
Instead, always create the intent and respond with an appropriate error
- Tested in github-merge-queue-sandbox repo [here](https://github.com/evergreen-ci/github-merge-queue-sandbox/pull/22#event-14204590972)
- Add unit test for intent with disabled merge queue
- Remove test to noop when a project is encountered with an Evergreen merge queue since these have all been removed from production
N/A

DEVPROD-9092: Send GitHub error when merge queue is not enabled

---

cloud/parameterstore/fakeparameter/parameter_manager_test.go
cloud/parameterstore/parameter_manager.go
cloud/parameterstore/parameter_manager_test.go
cloud/parameterstore/ssm_client.go
environment.go
mock/environment.go
self-tests.yml

DEVPROD-10392
* Make it so that other packages can use the parameter manager to interact with Parameter Store by exposing it in the global env.
* Slightly refactor parameter manager constructor to use options struct and use the real SSM client implementation by default.
* Existing tests still pass, even those that initialize a test environment (this initialization indirectly creates a parameter manager).
N/A

DEVPROD-10392: make parameter manager available in global env

---

rest/model/subscriber.go
rest/route/project.go

DEVPROD-11203
The `Target` field can be either a slice or a string. However, since swaggo does not support the OpenAPI `oneOf` keyword, we set `swaggerignore` and document the field manually in the "Fetch all projects" endpoint.
I generated swagger.json manually and checked that the field is missing.
Added to the "Fetch all projects" endpoint.

DEVPROD-11203 Do not document the target field

---

graphql/generated.go
graphql/models_gen.go
graphql/query_resolver.go
graphql/schema/query.graphql
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/queries/no_filters.graphql
graphql/tests/query/waterfall/queries/pagination_backward.graphql
graphql/tests/query/waterfall/queries/pagination_forward.graphql
graphql/tests/query/waterfall/results.json
graphql/util.go
graphql/util_test.go
model/waterfall.go
model/waterfall_test.go

DEVPROD-10177
- `GetActiveWaterfallVersions` returns at most `limit` active versions that satisfy order constraints related to pagination
- Using the min and max orders returned from these active versions, or the limit from the resolver request if provided, query for all versions within this range (inclusive). This fetches active and inactive versions. Inactive versions are then grouped for easy rendering by the front end
- Only use active versions to populate the `GetWaterfallBuildVariants` query
- Add fields to return to indicate order values that should be used for pagination to the client
- Ensure `GetActiveWaterfallVersions` does not return inactive version
- GraphQL unit tests ensure pagination values returned to the client are correct
- Add unit test to ensure active/inactive …

DEVPROD-10177: Add waterfall query pagination

---

config.go

DEVPROD-11303
`IsValidBannerTheme` supports empty banner themes, and there are existing empty banner themes. A team is attempting to use Evergreen's OpenAPI spec, and the missing empty enum value is causing errors. This PR adds that as a legal value.
Existing tests should cover this. I validated by hand that the swagger.json generated by `make swaggo` looks correct.
N/A

DEVPROD-11303 Add empty bannertheme

---

graphql/task_resolver.go
graphql/tests/task/imageId/data.json
graphql/tests/task/imageId/queries/container_task.graphql
graphql/tests/task/imageId/queries/regular_task.graphql
graphql/tests/task/imageId/results.json

DEVPROD-11290
The `ImageID` resolver requires the existence of `DistroID`. I thought I had covered everything by checking for display tasks, but I missed container tasks. I decided to just make this resolver a bit more broad and allow it to return an empty string if `DistroID` is not defined.
- Added GraphQL tests

DEVPROD-11290: Fix logic for fetching task's imageID field

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-4971
We already use a tag in the docs but we don't state explicitly that the 'execution_tasks' array can be a tag or task name. This adds a task name to it and explicitly says it

DEVPROD-4971 Document that display task's execution task array can be tag or task name

---

agent/command/assume_ec2_role.go
agent/command/assume_ec2_role_test.go
config.go

DEVPROD-9944
This adds a temporary feature flag to the ec2.assume_role project command to support the migration from calling AWS on the agent --> calling AWS on the app servers.
Staging tasks [here](https://spruce-staging.corp.mongodb.com/version/66e486db04ee5100070f7e2c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). Using config:
```yaml
tasks:
- name: assume_role_legacy
commands:
- command: ec2.assume_role
params:
role_arn: ${AWS_ASSUME_ROLE_ARN}
- name: assume_role_feature_flag
commands:
- command: ec2.assume_role
params:
role_arn: ${AWS_ASSUME_ROLE_ARN}
temporary_feature_flag: true
```
The legacy task errors from an invalid ARN, while the feature one errors as expected stating it is the feature flag one.
Unit tests were refactored, since before we couldn't emulate the AWS logic since …

DEVPROD-9944 Add temporary feature flag for ec2.assume_role migration

---

cloud/parameterstore/fakeparameter/db_test.go
cloud/parameterstore/fakeparameter/parameter_record_db_test.go
config_cloud.go
config_test/evg_settings.yml
mock/environment.go
testutil/config.go

DEVPROD-9401
* Ensure testing environments use the fake Parameter Store implementation backed by the DB rather than actually using SSM Parameter Store. This will let us test functionality that uses parameters without relying on an external service for every single parameter-related functionality.
* Add some forgotten struct tags to the Parameter Store admin settings.
Existing tests still run (which implicitly sets up the fake Parameter Store).
N/A

DEVPROD-9401: set up parameter manager for testing

---

rest/route/host_agent.go

DEVPROD-10099
Correctly return 500 errors for the selected next task errors so they show up in the gimlet error logs.
Existing tests

DEVPROD-10099 Return 500 error for next task run request errors

---

model/project_vars.go

DEVPROD-9404
Update project vars data model to support storing values in Parameter Store instead of the DB. The new field maps the project var name to the location of where its corresponding parameter in kept in Parameter Store.
N/A - Doesn't provide any new functionality yet.
N/A

DEVPROD-9404: update data model for project var parameters

---

agent/agent.go
agent/agent_test.go
agent/task_context.go
config.go

DEVPROD-9738
Currently, tasks that report a failed status with the task_status API endpoint misrepresent the command that set the failure by always saving the last command ran. These code change take into the current command when the user defined task end response is processed.

DEVPROD-9738: Surface the command that set the user defined task failure status

---

agent/otel.go
agent/otel_test.go
config.go

[DEVPROD-11385](https://jira.mongodb.org/browse/DEVPROD-11385)
In https://github.com/evergreen-ci/evergreen/pull/8303 it was raised that we don't have visibility into the number of processes that are running. This PR adds process counts in accordance with the spec [here](https://opentelemetry.io/docs/specs/semconv/system/system-metrics/#metric-systemprocesscount).
[Works on staging](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/jWZ9Bkkmztq?omitMissingValues)™️

DEVPROD-11385 OTel process counters

---

api/host.go
config_jira.go
config_test.go
rest/model/admin.go
rest/route/host.go
rest/route/host_agent.go
rest/route/host_agent_test.go
testutil/config.go
units/deco_host_notify.go
units/util.go

DEVPROD-7739
* Automatically quarantine a static host if it system-fails three tasks in a row. (This behavior already used to exist but EVG-2742 mysteriously removed it for unknown reasons. I think it's fine to reintroduce.)
* Send a Splunk log when a static host is quarantined. I refactored the job so that it's less weird and more in line with how we typically write jobs (i.e. not persisting an entire copy of the host doc in the job). When this logs, [an alert will ping `#devprod-runtime-environment-alerts`](https://mongodb.splunkcloud.com/en-US/app/search/alert?s=%2FservicesNS%2Fnobody%2Fsearch%2Fsaved%2Fsearches%2FEvergreen%253A%2520Static%2520Host%2520Quarantined) that a static host is quarantined.
* Clean up some old next/end task tests so they're more in line with current coding …

DEVPROD-7739: auto-quarantine and alert for static hosts

---

model/task/db.go
model/task/db_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
units/check_blocked_tasks.go
units/host_termination.go
units/host_termination_test.go

DEVPROD-9920
Currently, if a host gets terminated midway through a single host task group, the group gets marked to automatically reset (which is correct), but it won't do that until the subsequent tasks run, which creates unnecessary failures.
This change is to block those tasks immediately so the task group can immediately reset. Also cleaned up `TestHostTerminationJob` a bit.
Reproduced the bug in staging and confirmed it went away with this change. Added unit tests.

DEVPROD-9920 Block subsequent single host TG tasks if host gets terminated

---

model/project_vars.go
model/project_vars_test.go

DEVPROD-9469
Add helper function (not used yet) to convert project var names to parameter names. We can't always use the project var name directly as the name of their corresponding Parameter Store parameter because [parameter names have some validation rules](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ssm@v1.52.3#PutParameterInput).
I checked the existing project var names and the only validation rule that's broken by existing project vars is that some project vars begin with `aws`/`ssm`. Since only that one rule is broken by the existing project vars, I wrote it to only make those existing project vars compatible with parameters and otherwise disallow other special characters to future-proof project var names in case someone tries to add an invalid character.
* Add helper …

DEVPROD-9469: convert project var names to parameter names

---

agent/otel.go
agent/otel_default.go
agent/otel_test.go
agent/otel_windows.go
config.go

[DEVPROD-11385](https://jira.mongodb.org/browse/DEVPROD-11385)
#8317 added process counters to the task OTel metrics. It also added a test that revealed which metrics weren't working. Although it doesn't hurt to call the functions and get the error, it makes more sense to be explicit about which ones are working.
This PR cherry-picks #8317 which was reverted because of the failing tests and fixes the tests. As an added bonus, it fixes disk metrics on Windows, which were failing because the disk names included colons (e.g. C:) and you can't have a colon in an instrument name. Also, process metrics were adjusted so they'd work on Windows.
The `test-agent`s are passing now.

DEVPROD-11385  OTel process counters

---

model/task/db.go
model/task/db_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
units/check_blocked_tasks.go
units/host_termination.go
units/host_termination_test.go

DEVPROD-9920
The change in #8323 resolves the BFs, but it does not need to run the dependency blocking logic if the task group has ran its final task.

DEVPROD-9920 Don't block single host TG deps if host terminates aftergroup finishes

---

self-tests.yml

DEVPROD-8801
We have not been using these task failures as a signal and they are causing our waterfall to consistently be red. This limits it to smoke test only so that we can still have some signal but eliminate the ones that are not being relied on.

DEVPROD-8801 Limit container variant tasks

---

globals.go
testdata/local/roles.json

DEVPROD-9663
This text says there's no permission to "view or edit patches", but we actually use task view permission for all viewing things, and we only use this for submission, so this shouldn't reference view.
Verified there's nothing to update for mana, since this already just says "unspecified".

DEVPROD-9663 remove incorrect patch permission text and update superuser default

---

rest/route/project_copy.go

Spotted a formatting error while reading the docs, which doesn't render. Seems like it was probably leftover from when the docs transitioned from rst to md.

docs: fix formatting on project vars copy dry_run param

---

agent/agent.go
agent/task_context.go
config.go

DEVPROD-5614
This adds the task attributes to the teardown group traces (and gives it a parent span with a proper name). It also does a small rename for the cleanups to be consistent with the others.
[Before](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen-agent/result/eRJdajDjkdV/trace/8HL89vCzvT1?fields%5B%5D=s_name&fields%5B%5D=s_serviceName&source=query&span=0e6d051173c21c16):
[After](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen-agent/result/CQ3h4iMDskc/trace/tDKy3FetuSv?fields%5B%5D=s_name&fields%5B%5D=s_serviceName&span=ff7a2f9f3d94b1ca):
(The difference in commands ran are not important, I just chose two random teardown group tasks. The difference is the attributes and the fact that the teardown group is the new named …

DEVPROD-5614 Add trace attributes to teardown group and task

---

agent/command/assume_ec2_role.go
agent/command/assume_ec2_role_test.go
agent/internal/client/base_client.go
agent/internal/client/interface.go
agent/internal/client/mock.go
apimodels/agent_models.go
apimodels/agent_models_test.go
cloud/sts.go
cloud/sts_test.go
config.go
rest/route/agent_test.go

DEVPROD-9945
For the AssumeRole migration, we made the task app route to assume a role for a task. This migrates the command to use it if the feature flag is turned on.
Deployed to staging, ran these patches [Mainline](https://spruce-staging.corp.mongodb.com/version/zackary_bisect_c23a8034170c677f2d756fa75c0d260c54efbe12/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=assume_role) and [Patch](https://spruce-staging.corp.mongodb.com/version/66f2d5daef10f50007fbc7db/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
Added some unit tests.
CLI Patch:
Mainline Patch (I edited the title to match the same style as the above):
Note: The tasks with 'external id' means that the role they are trying to assume, had a policy set up with an external id that restricted it to *my* project + …

DEVPROD-9945 Connect AssumeRole project command and app route

---

agent/agent.go
agent/command/git.go
agent/command/git_push_test.go
agent/command/git_test.go
agent/internal/client/base_client.go
agent/internal/client/client_test.go
agent/internal/client/mock.go
agent/util/expansions.go
config.go
model/project.go

DEVPROD-10509
This ticket cleans up some of the redacting logic and adds redaction to the generated tokens. 
It also fixes a bug where modules would still generate a token even if the user passed in an access token.
Existing unit tests
[This](https://parsley-staging.corp.mongodb.com/evergreen/zackary_bisect_ubuntu_long_task_with_expansions_patch_75ff53fe6dcf210f4d5116e884abdd365150b4fd_66edb8e3decf1000077360c2_24_09_20_18_03_21/2/all?bookmarks=0,932&selectedLineRange=L686) task on staging after the fix, the token for `git clone ... github-merge-queue-sandbox` is redacted.

DEVPROD-10509 Update git.clone project command to redact for modules

---

graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/results.json
model/waterfall.go
model/waterfall_test.go

DEVPROD-11617
- Fix previous implementation of waterfall sorting that sorted builds by their ID. We should sort by display name, especially since a lot of projects have their display names configured to render on the waterfall in a useful order.
- Update test such that it would fail without display name sorting

DEVPROD-11617: Sort waterfall build variants alphabetically

---

graphql/patch_resolver.go
rest/route/patch.go

DEVPROD-10170
These queries can be sped up by sorting on finish time key rather than create time key, since finish time is more friendly with the existing indexes that we have on the task collection.
Tested by comparing explain plan results in shell.

DEVPROD-10170 Use different sort key for estimated generated tasks

---

units/host_termination.go

DEVPROD-9134
With these new logs, we can create an alert to tell if we are consistently wasting host compute time by failing to provision hosts over and over, while actually creating them on the EC2 side.

DEVPROD-9134 Add agent start time and isEC2 to provisioning failure logs

---

.github/dependabot.yml

DEVPROD-11733
[smithy-go](https://github.com/evergreen-ci/evergreen/pull/8256), [sessions](https://github.com/evergreen-ci/evergreen/pull/8257), and [gqlgen](https://github.com/evergreen-ci/evergreen/pull/8332), cannot be upgraded further because they all require a higher go version than Evergreen currently runs. Adding to the ignore list until DEVPROD-3611 can upgrade Evergreen's go version, at which point DEVPROD-6962 can revisit upgrading them.

DEVPROD-11733: ignore dependencies requiring go 1.21+

---

agent/internal/taskoutput/test_log.go
agent/internal/taskoutput/test_log_test.go
config.go

DEVPROD-11778
Reduce noise in Evergreen logging warning messages.
If a log line is empty with just timestamp, the Evergreen agent should just ignore the line and move on rather than logging a warning. This is confusing for users and adds a lot of noise to the logs.
Added new test to ensure empty lines are ok.
N/A

DEVPROD-11778: Do not log warning messages for empty Evergreen test logs

---

rest/route/select.go

DEVPROD-11629
Log the inputs to the test selection route so that we can have an idea of what a sample input looks like. This info will be helpful while creating the test selection service.

DEVPROD-11629: log test selection inputs

---

agent/command/git.go
config.go

DEVPROD-10509
This reverts a small portion of https://github.com/evergreen-ci/evergreen/commit/dc993be1a6db2fe65aa8e0ba1d157d4c9f2b797d#diff-1e8d12ae20a5922169a78aaae96aab11adb323b77baf8910c3cbfba80b1d0012R720
which was causing issues for modules from a different org than the repository

DEVPROD-10509 Module cloning should always generate new token unless oauth

---

rest/model/version.go
rest/model/version_test.go

DEVPROD-11199
This propagates the git triggered info in to the rest api.
Added a unit test to make sure it propagates correctly. I didn't test in staging since it's a trivial change.
I did confirm via the version they provided that the git triggered by tag is populated (it just isn't propagated).

DEVPROD-11199 Add git triggered info to version rest api

---

units/spawnhost_expiration_warning.go
units/spawnhost_expiration_warning_test.go
units/volume_expiration_warning.go

DEVPROD-7677
If a user receives a notification that their spawn host/volume is about to expire and they extend it, currently they won't get another notification when their extended expiration is close to expiring. This change allows the user to be re-notified again after extending the expiration.
N/A

DEVPROD-7677: renotify for spawn host and volume expiration

---

plugin/attach_plugin.go
service/build.go
service/task.go
service/version.go

DEVPROD-11330
We recently had an issue where the files plugin (or tab) on the legacy ui was panicing because of a nil pointer exception when accessing the `request` field. This propogates the request object through to the plugin system.
I was also considering adding logging [here](https://github.com/ZackarySantana/evergreen/blob/ad7105b64c4cd53f7f7d05982fc484fe73534261/plugin/plugin_ui.go#L269) but decided not to since this is our legacy ui, but it would've caught this and prevented the regression. It was a bit of a pain to find out what was happening but looking at what plugins we have, there's not much and they're at a low risk of regressing (at least by the time we fully migrate to new ui)
Deployed to staging and tested. Didn't add unit tests since this is hard to test and it's our …

DEVPROD-11330 Pass request through to ui context for legacy ui plugin system

---

thirdparty/git.go

DEVPROD-752
Instead of falling back to ssh cloning, fall back to an https url without a token which will work for public repos. 
The rest of the cleanup specified in the ticket has already been done at some point.

DEVPROD-752 Remove ssh fallback

---

docs/FAQ.md

This links to questions that were tagged with `evergreen`.

docs: Add a link to the wiki with the SO question dump 

---

graphql/query_resolver.go
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/queries/all_inactive_versions.graphql
graphql/tests/query/waterfall/queries/no_versions.graphql
graphql/tests/query/waterfall/results.json
graphql/util.go
graphql/util_test.go
model/waterfall.go
model/waterfall_test.go

DEVPROD-11769
- While investigating the panic linked in the ticket, I noticed that the waterfall resolver failed to properly handle projects with 0 active versions. This PR implements that so that we can list all inactive versions on the new waterfall page.
- Added unit tests that fail without these code changes

DEVPROD-11769: Improve waterfall handling for inactive versions

---

model/host/host.go

DEVPROD-11817
After upgrading to MongoDB 8.0 this query broke due to a duplicate sort key error. I've flagged this with the query team since it didn't seem to be documented in the 8.0 release notes. 
Tested on staging and the 8.0 tests upgrade should be unblocked

DEVPROD-11817 Don't apply secondary _id sort if sort is by _id on hosts query

---

go.mod
go.sum
rest/route/service.go
service/service.go
service/ui.go

DEVPROD-11692
Upgrade to include recent gimlet change. Include a driveby change to remove the user auth from the Alertmanager route that was added in DEVPROD-667 and added auth to one more unauthed route I found.
Tested content is not available publicly anymore

DEVPROD-11692 Protect static content from public web

---

rest/route/user.go
rest/route/user_test.go

DEVPROD-9663 
1. Allow removing roles via route. (This would just be convenient, since needing to do things via DB is annoying, and has potential to be un-logged).
2. Add log for usage of the route. (I'm logging even if there are errors, because regardless I think we want to know if this happened, and this will tell us what was changed.) Will create a splunk alert for this.
Will add to the rotation playbook (i.e. ignore it if it's not intended, escalate if it seems fishy)

DEVPROD-9663 allow removing roles from route and log usage

---

graphql/generated.go
graphql/models_gen.go
graphql/query_resolver.go
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/queries/revision.graphql
graphql/tests/query/waterfall/queries/revision_nonexistent.graphql
graphql/tests/query/waterfall/results.json
graphql/util.go

DEVPROD-10182
- Accept an input for a revision hash in order to jump waterfall to a certain commit
- Uses basically the same logic as [mainline commits](https://github.com/evergreen-ci/evergreen/blob/ed6101e2f0ef85f8748910edc7de3065cabcb8f3/graphql/query_resolver.go#L814-L828)
- Add GraphQL unit tests

DEVPROD-10182: Add waterfall revision selector

---

config.go
operations/list.go
rest/client/interface.go
rest/client/methods.go
rest/route/alias.go
rest/route/alias_test.go
rest/route/service.go

DEVPROD-7489
Add functionality to the get project aliases route to also optionally retrieve YAML aliases.
Added unit testing for the whole route, and tested this in staging.

DEVPROD-7489 Allow get project aliases route to return config aliases

---

cloud/parameterstore/parameter_cache.go
cloud/parameterstore/parameter_manager.go
cloud/parameterstore/parameter_manager_test.go
cloud/parameterstore/ssm_client.go
model/project_vars.go
model/project_vars_test.go

DEVPROD-9472
This is a follow-up to #8329 to further handle and try fixing more special cases with existing project vars to fit within SSM's parameter name/value constraints.
* If a project var value is longer than the 8 KB SSM parameter length limit, try compressing it to get it within the length limit. Add `.gz` to the end of the parameter name to indicate the value was compressed with gzip. (Adding the extension will make it easier to determine that a project var needs to be decompressed when reading the parameter out of Parameter Store.)
* Refactor logic from #8329 to validate parameter name constraints after adding the `.gz` extension for compressed vars.
* Include project ID as prefix in the parameter name. This ensures that parameters are unique across projects (e.g. `aws_key` in …

DEVPROD-9472: handle long project vars and convert to parameter

---

model/task/task.go
model/task_queue.go
scheduler/planner.go
scheduler/planner_test.go
scheduler/task_queue_persister.go

DEVPROD-8586
Currently there is an opacity of how priority + our planner admin settings compute an actual sorted queue, and these factors can overlap in complex ways. If we have a way to inspect what these values are in real-time in the DB, we can better determine what priority teams should bump their versions to, and what values we should tune our  [planning multipliers](https://github.com/evergreen-ci/evergreen/blob/38b298af5e49e6b2fb50a1715760c922dfb06d95/model/distro/distro.go#L255-L261) to.
Added a field in the task queue that tracks this true queue rank value.
Ran multiple types of versions in staging (patches, mainline commits, generators) in staging and checked that this new field on the queue in the DB reflects priority * all matching planner setting factors.

DEVPROD-8586 Propagate true weighted priority to task queue doc

---

agent/agent.go
agent/command/exec.go
agent/command/exec_test.go
agent/command/shell.go
agent/command/shell_test.go
agent/internal/testutil/task_config.go
agent/task_context.go
agent/util/subtree_unix.go
agent/util/subtree_unix_test.go
agent/util/subtree_windows.go
apimodels/agent_models.go
config.go
docs/decisions/2024-10-14_task_process_termination.md
model/distro/distro.go
rest/model/distro.go
rest/model/distro_test.go
rest/route/agent.go

[DEVPROD-10457](https://jira.mongodb.org/browse/DEVPROD-10457)
The environment variable based solution has never been perfect (e.g. [EVG-15290](https://jira.mongodb.org/browse/EVG-15290), [EVG-12948](https://jira.mongodb.org/browse/EVG-12948)). And now it's broken for macOS with SIP enabled ([DEVPROD-6539](https://jira.mongodb.org/browse/DEVPROD-6539)).
The strategy from #8303 didn't work because user processes often daemonize, which includes calling setsid which gets a new session and process group ID 😭 . Also when you put a process in the shell's background it will get a new session/process group.
This PR introduces a new strategy: start user initiated processes as a separate user. This will keep their processes and any descendant processes nicely contained so we can kill them all with …

DEVPROD-10457 contain and kill subprocess.exec/shell.exec processes

---

model/task/task.go

DEVPROD-7676
this query was failing sometimes due to large document so we filter the tasks in memory before making the query 
I also thought that the cause of the large document error could be us putting in a massive amount of the same display task id for each execution task so I added a filter for that in memory as well
current tests should pass

DEVPROD-7676 Filter set tasks scheduled time in memory

---

thirdparty/github.go
thirdparty/github_test.go

DEVPROD-12051
We're getting a lot of extraneous logs in prod from trying to revoke tokens that are already revoked. (aka 401 responses)
This adds a config option to the client to ignore codes.
Add unit test

DEVPROD-12051 Add ignore codes logic to github client

---

model/project_vars.go
model/project_vars_test.go

DEVPROD-9473
Add helper that will convert an SSM parameter back to the original project var. The logic to convert a project var to a parameter already exists, this is the inverse operation.
N/A

DEVPROD-9473: decode parameters back to project variables

---

cloud/parameterstore/fakeparameter/fake_parameter.go
config_scheduler.go
graphql/generated.go
graphql/schema/types/distro.graphql
graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql
graphql/tests/mutation/saveDistro/queries/save.graphql
graphql/tests/mutation/saveDistro/queries/validation_error.graphql
graphql/tests/query/distroEvents/data.json
graphql/tests/query/distroEvents/results.json
model/distro/distro.go
model/distro/distro_test.go
rest/model/admin.go
rest/model/distro.go
scheduler/planner.go
scheduler/planner_test.go
service/templates/admin.html
validator/distro_validator.go

DEVPROD-12086
Introduce a new queue prioritization factor that lets us tune up or tune down the influence the # of dependent tasks has on its placement in the queue. This is settable on the admin page globally, as well as overridable for specific distros.
Since it looks like we've been facing issues with a large number of tasks with unfulfilled dependencies at the front of queues causing next_task route latency issues, if we turn this factor up it might be able to alleviate the issue by fulfilling their dependencies faster.
Tested locally

DEVPROD-12086 Add queue sorting factor for number of dependent tasks

---

.github/dependabot.yml

DEVPROD-12117
This adds more dependencies to our collection of ignore (because we are on an old golang version).

DEVPROD-12117 Add go 1.21 dependencies to dependabot ignore file

---

service/ui.go

DEVPROD-11144
When making CORS request to the `/logout` endpoint of Evergreen, the browser pings `/logout` with an OPTIONS method, which was returning a CORS error because Evergreen doesn't have a route for this type of request on the `/logout` path.
Added an OPTIONS method to the logout path that adds CORS headers, just like we do for all POST methods currently.
Tested in staging and confirmed that in incognito, visiting Spruce no longer gives an indefinite LOADING screen, but redirects to the login flow.

DEVPROD-11144 Add options handler to logout route

---

docs/Project-Configuration/Best-Practices.md
docs/Project-Configuration/Project-and-Distro-Settings.md

DEVPROD-11187
* As part of comms to warn users that are storing secrets in public vars, I'm gonna link to this best practices doc recommending to use private vars instead of public vars to store secrets.
* Also updated docs on private vars to mention they are redacted from task logs.

DEVPROD-11187: document best practices for variables

---

model/patch/patch.go
model/patch_lifecycle.go
model/project_parser.go
self-tests.yml
units/patch_intent.go

DEVPROD-9870
The repeat patch option was not working for modules because it would always use the latest version of the branch that the module was on. We now pull the correct module
Created a patch with a task from a module
Updated the module to not have the task 
Trying to repeat that patch will output `Unexpected reply from server (500 Internal Server Error): 400 (Bad Request): getting patched project: load project error(s): error translating project: task selectors for build variant 'included-variant' did not match any tasks`
Confirmed that the change now creates the patch correctly with the version of the module that the initial patch was created with 
`evgs patch-file --diff-patchId 67123c6e386b5e0007b8f8cb --repeat-patch 67123c6e386b5e0007b8f8cb` …

DEVPROD-9870 Support repeat patch with same module versions

---

agent/command/assume_ec2_role.go
agent/command/assume_ec2_role_test.go
config.go
go.mod

DEVPROD-9947
This removes the temporary feature flag and the old way of doing ec2.assume_role.
Removed legacy testing. Existing testing covers new implementation.

DEVPROD-9947 Remove ec2.assume_role temporary feature flag 

---

.github/dependabot.yml

DEVPROD-12203
[This Dependabot upgrade](https://github.com/evergreen-ci/evergreen/pull/8404) can't be merged because the latest tag requires go 1.21 or higher. Adding to the dependency ignore list until the go version is upgraded.

DEVPROD-12203: ignore google.golang.org/protobuf due to go version

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-9617
Added a section about how to use `evergreen evaluate` instead of include. @gmishkin i don't think mms is actually doing this yet but curious if there's anything else you think I should add while keeping this lightweight.

DEVPROD-9617 add pre-commit hook alternative to include

---

model/project_ref.go
model/project_ref_test.go
model/project_vars.go
model/project_vars_test.go

DEVPROD-11973
While the migration is ongoing, we need a way to initially sync the existing project vars into Parameter Store, and a way to re-sync if we have to toggle Parameter Store while the rollout is ongoing. This temporary logic will take all the existing project vars for a project and put them all in Parameter Store, at which point the two will be in sync.
I also added a project ref flag to indicate if a full sync is needed to get Parameter Store. If it's set, the logic will do a one-time sync. This flag has to be manually unset if I disable Parameter Store, but I think that's okay since I'm going to be setting it as needed while projects are being migrated to Parameter Store.
* Tested in staging with the sandbox project to ensure its project vars could be fully …

DEVPROD-11973: support fully syncing project vars to Parameter Store

---

model/patch/patch.go
model/patch_lifecycle.go
model/project_parser.go
units/patch_intent.go

DEVPROD-11466
This copies the module manifest from the base version to a patch
I made [this](https://spruce-staging.corp.mongodb.com/version/zackary_bisect_d254bbfb89f0e1c5ffaab6eed68c377d653aa1d3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) mainline version where `task 2` comes from an included module config file. `task 2` echo's "v1". I made a new commit on the module config file to echo "v2". I reran the mainline version, it echo's "v1" still (as it should). I made [this](https://spruce-staging.corp.mongodb.com/version/6716973661272a000743d984/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) patch based off of that commit. It echo's "v2" when it should do "v1" (like the mainline commit did).
I made [this](https://spruce-staging.corp.mongodb.com/version/6716c1fab9205f0007b61553/tasks?sor …

DEVPROD-11466 Copy module manifest from base version if it exists

---

graphql/generated.go
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/queries/no_filters.graphql
graphql/tests/query/waterfall/results.json
model/waterfall.go

DEVPROD-11734
Add task's execution number to the waterfall query by including it in the `$lookup` stage where tasks are fetched
Also removed TODOs for tickets that were closed as won't do.
Update GraphQL unit tests

DEVPROD-11734: Include task execution in waterfall query

---

agent/command/perf_send.go
apimodels/cedar_models.go
config.go
config_cedar.go
go.mod
go.sum
rest/model/admin.go
rest/route/agent.go
service/templates/admin.html
smoke/internal/testdata/admin_settings.yml

[DEVPROD-11768](https://jira.mongodb.org/browse/DEVPROD-11768)
This adds the configuration for being able to send Perf Results to SPS. It also bumps the Poplar version to be able to take advantage of the new options. I based these changes off of [this pr](https://github.com/evergreen-ci/evergreen/pull/7685/files).
Likely the best way of testing this would be pushing this to Evergreen staging. I'll work with your team on doing that.

DEVPROD-11768: Begin sending data to new perf endpoint in SPS

---

graphql/generated.go
graphql/models_gen.go
graphql/query_resolver.go
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/queries/date.graphql
graphql/tests/query/waterfall/queries/date_unmatching.graphql
graphql/tests/query/waterfall/results.json
model/version_db.go
model/version_db_test.go

DEVPROD-10185
Update GraphQL resolver to accept a date input. This value is used to fetch the most recent query created on or before the specified date. The resolver then utilizes the revision order number returned version to find `limit` versions around that version, very similarly to how the git hash selector works in the `getRevisionOrder` utility.
The versions collection already contains the index `{ identifier: 1, r: 1, create_time: 1 }` which can be used to fulfill this query.
Add GraphQL and unit tests

DEVPROD-10185: Query waterfall by date

---

model/project_ref.go
model/project_ref_test.go
model/project_vars.go
model/project_vars_test.go
rest/data/project.go
rest/data/project_test.go

DEVPROD-9405
Follow-up to #8398, which added support for `Upsert` to put project variables in Parameter Store. This PR supports `FindAndModify` and `Insert` for project variables so they'll be written to Parameter Store if it's enabled for the project.
* Support `FindAndModify` and `Insert` for storing project variables in Parameter Store.
* Refactor common Parameter Store operations into more helper functions.
* Switched some existing tests to write to Parameter Store.
* Existing tests still pass.
N/A

DEVPROD-9405: support Insert and FindAndModify for Parameter Store

---

rest/route/project_copy.go

DEVPROD-11786 Document that Github App info is not transferred in /projects/{id}/copy

---

model/task/task.go
model/task/task_test.go

DEVPROD-6798
In Archive, we don't error if the task has already been archived (because it's already been inserted into the old task collection, or because the task collection doc has been updated already). This logic isn't extended to the display task restarts however. 
Updated unit test (this failed without the changes).

DEVPROD-6798 make display task restarts more resilient

---

rest/route/github.go
rest/route/github_test.go
units/patch_intent.go
units/patch_intent_test.go

DEVPROD-9092 - third time's the charm!
For GitHub merge queue requests, don't create an intent if there is no associated project. This will avoid the "Evergreen error" response occurring on non-LeafyGreen repos: https://github.com/mongodb/leafygreen-ui/commit/1da29495dff3ca98e82148ae94ef87b537677a69
Ensure that intent is not created for GitHub requests with no project

DEVPROD-9092: Check project exists before creating merge queue intent

---

model/lifecycle.go
model/task/task.go
repotracker/repotracker_test.go

DEVPROD-11321
Currently, if a task is disabled in YAML and gets activated through being pulled in as a dependency, its disabled status will be ignored and it will be activated anyway. Patched a change to fix this.
Added test case + confirmed in staging

DEVPROD-11321 Do not activate disabled dependencies in repotracker

---

graphql/generated.go
graphql/models_gen.go
graphql/query_resolver.go
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/queries/all_inactive_versions.graphql
graphql/tests/query/waterfall/queries/date.graphql
graphql/tests/query/waterfall/queries/date_unmatching.graphql
graphql/tests/query/waterfall/queries/flattened_versions.graphql
graphql/tests/query/waterfall/queries/no_filters.graphql
graphql/tests/query/waterfall/queries/no_versions.graphql
graphql/tests/query/waterfall/queries/pagination_backward.graphql
graphql/tests/query/waterfall/queries/pagination_forward.graphql
graphql/tests/query/waterfall/queries/revision.graphql
graphql/tests/query/waterfall/queries/revision_nonexistent.graphql
graphql/tests/query/waterfall/results.json
model/version.go
model/waterfall.go
model/waterfall_test.go

DEVPROD-12405
(600 lines were autogenerated) 
We are having some issues with reconciling the mainline commits page and cursor based pagination. This PR is a precursor to doing some investigative work here. This PR adds new fields for the investigation, and fixes 2 small bugs in the resolver.
Changes:
* Return `flattenedVersions` array from Waterfall resolver. We will evaluate if this field makes it easier to cache.
* Return `Pagination` object from Waterfall resolver. Cursor based pagination method recommends returning an object containing pagination information.
* Add `Version` field to `WaterfallBuildVariant`. This will be used for caching.
* Fix bug where returning to the first page will fail to fetch leading inactive versions.
* Fix bug where previous page order would be populated …

DEVPROD-12405: Update Waterfall resolver to help with pagination investigation

---

globals.go
model/event/host_event_finder.go
model/task/db.go
rest/route/host_agent.go
rest/route/host_agent_test.go

DEVPROD-11577
A host that was repeatedly timing out wasn't being caught by the quarantine logic; we should use all statuses here , because this is what the event logs use.

DEVPROD-11577 include all system statuses in host quarantine

---

cloud/parameterstore/fakeparameter/fake_parameter.go
model/task/task.go
model/task_queue.go
model/task_queue_service_dependency.go
model/task_queue_service_test.go
rest/route/host_agent.go
rest/route/host_agent_test.go
scheduler/task_queue_persister.go

DEVPROD-12086
When the front of a task queue is comprised entirely of task group tasks, a failure mode can occur where the next task operation continuously fetches a task group task, sees that it is not ready to be dispatched, and skips it to move onto the next task group task. This can go on for a long time, resulting in really large latency for the operation such as in [this example](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/fzzrJfRkUdd/trace/BL3LZDJefCK?source=query&span=881a0bd620b25b82).
[This function](https://github.com/evergreen-ci/evergreen/blob/5f9cd51bdcfb4b58535d0df58990676052d398da/model/task_queue_service_dependency.go#L574), which tries to find a group's next dispatchable task, marks all task group tasks as …

DEVPROD-12086 Persist whether task's dependencies are met to queue items

---

cloud/docker.go
cloud/docker_client.go
cloud/docker_mock.go
rest/route/service.go
service/host.go
service/host_test.go
service/service.go

DEVPROD-11692
This re-applies #8381, which was reverted due to breaking an external build Dockerfile. That Dockerfile has since been updated so this can be re-deployed.

DEVPROD-11692 Re-apply adding auth for CLI downloads

---

cloud/ec2_test.go
graphql/tests/mutation/attachProjectToNewRepo/data.json
graphql/tests/mutation/attachProjectToRepo/data.json
graphql/tests/mutation/copyProject/data.json
graphql/tests/mutation/defaultSectionToRepo/data.json
graphql/tests/mutation/deleteProject/data.json
graphql/tests/mutation/detachProjectFromRepo/data.json
graphql/tests/mutation/promoteVarsToRepo/data.json
graphql/tests/mutation/saveProjectSettingsForSection/data.json
graphql/tests/mutation/saveRepoSettingsForSection/data.json
graphql/tests/projectSettings/vars/data.json
graphql/tests/repoSettings/vars/data.json
model/project_ref.go
model/project_ref_test.go
model/project_vars.go
model/project_vars_test.go
model/testutil/api.go
repotracker/repotracker_test.go
rest/data/commit_queue_test.go
rest/data/host_create_test.go
rest/data/project.go
rest/data/project_settings_test.go
rest/data/project_test.go
rest/route/agent_test.go
rest/route/project.go
rest/route/project_copy_test.go
rest/route/project_test.go
rest/route/user_test.go
units/patch_intent_test.go
validator/project_validator_test.go

DEVPROD-9474
Use Parameter Store in as many tests as reasonably possible that involve project variables to ensure that we have as much coverage of the project variable behavior in advance of the migration to Parameter Store.
* Enable Parameter Store in all Go/GQL tests involving project vars. The only exceptions are those that are testing project creation and the smoke test.
* Fix a few subtle bugs found through testing that are related to moving variables between projects to ensure that projects don't share parameters. For example, if copying variables from project A to project B, the underlying parameters storing project A and project B's variables should still be separate, even if they have the same variable values.
* Fix a bug related to the project PATCH route to ensure that the …

DEVPROD-9474: use Parameter Store for project variable tests

---

config.go
operations/http.go
operations/patch.go
service/api_patch.go
units/patch_intent.go

DEVPROD-6301
We were returning mixed status codes when creating patches 
ex) `creating patch: Unexpected reply from server (500 Internal Server Error): 400 (Bad Request): no such buildvariant matching 'b'`
The proposed solution is a bit hacky because it is not 100% accurate but it doesn't seem worth it to special case on every single case that this could hit. I am going to assume that if we failed to build tasks and variants for the cli patch, it is because of a user error. I am arguing for this change because it is slightly more accurate than our current behavior which is more inaccurate more frequently 
now) `creating patch: Unexpected reply from server (400 Bad Request): 400 (Bad Request): building tasks and variants: no such buildvariant matching 'b'`

DEVPROD-6301 Allow patch route to return 400

---

config_task_limits.go
docs/Project-Configuration/Project-Configuration-Files.md
model/project_ref.go
rest/model/admin.go
rest/route/agent.go
rest/route/agent_test.go
service/templates/admin.html
util/time.go

DEVPROD-6589
In order to prevent overuse of the feature, this PR imposes a limit that a single project cannot restart more than X number of tasks using the `retry_on_failure` flag in a given 24 hour period. 
I verified using historical data that this limit should not get in the way of the current usage of this feature while still keeping usage conservative. Will set this to 200 as stated in the docs once this change deploys.
Added unit tests and tested in staging

DEVPROD-6589 Impose auto restart limit on projects

---

util/expand_params.go
util/expansion.go

DEVPROD-6029
When expanding a string fails, the error message may include a partially expanded string, which may leak a secret in logs. Return the unexpanded string in the error message instead.
Existing tests

DEVPROD-6029 Return unexpanded string in expansion error message

---

agent/internal/client/base_client.go
agent/internal/client/request.go
agent/util/ec2.go
config.go
go.mod
go.sum
model/project_parser.go
model/project_parser_test.go
rest/client/methods.go
rest/client/request.go
rest/route/agent.go

DEVPROD-7885
See ticket description for occurrences, but when the agent reads this route sometimes it gets an unexpected EOF. We only call this get project [once](https://github.com/ZackarySantana/evergreen/blob/d2f59c4c012b4fe7d4cf1baf8f7deb3920c20dd5/agent/agent.go#L558) and the unexpected EOF doesn't happen for the other functions right below it (GetTask and GetExpansionsAndVars), I think it has to do with that we send it over as binary which we don't do with any other route. It could also be that parser projects tend to be on the larger side.
This PR adds retries for invalid bodies and add retries on the server side to verify the integrity of marshaling. I suspect it won't be called, but I'll create a ticket and attach it to be removed once we verify that the retries on the server …

DEVPROD-7885 Retry on invalid body for parser project route

---

model/distro/db.go

[DEVPROD-8030](https://jira.mongodb.org/browse/DEVPROD-8030)
When we all have our own staging it'll be good to have one place to configure distros (since they're likely to change often)
We won't know for sure if it works until the other pieces are in place. DIdn't break staging, fwiw.

DEVPROD-8030 use shared db for distros

---

makefile
self-tests.yml

[DEVPROD-12635](https://jira.mongodb.org/browse/DEVPROD-12635)
There is no longer a mac host in staging. We should remove the macOS build for staging. This will help the most for when you build in Evergreen with the build-and-push-staging task (because signing could take a while), but should make the local build 33% faster too.
The local build (`STAGING_ONLY=1 make local`) didn't include a macOS build and neither did [the build-and-push-staging task](https://spruce.mongodb.com/version/672bd7f9cab18c00071f8e85/tasks).

DEVPROD-12635 remove mac build for staging

---

config.go
model/patch/patch.go
model/patch_lifecycle.go
model/project_parser.go
operations/patch.go
self-tests.yml

DEVPROD-9824
we save local modules in the db so that a repeat patch call will correctly use the same changes 
tested on staging 
made a local change on a module and created a [patch](https://spruce-staging.corp.mongodb.com/version/6723de5cd2421f0007fb96e3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) 
ran `evgs patch-file --diff-patchId 6723de5cd2421f0007fb96e3 --repeat-patch 6723de5cd2421f0007fb96e3 -f`
which created a successful [patch](https://evergreen-staging.corp.mongodb.com/version/6723e569f3450a000747d8a9?redirect_spruce_users=true) with the correct task selected

DEVPROD-9824 Repeat patch command should work with local modules

---

model/project_ref.go
model/project_vars.go
model/project_vars_test.go
model/repo_ref.go
units/crons.go
units/crons_remote_five_minute.go
units/parameter_store_sync.go

DEVPROD-11187
Project vars can use Parameter Store now, but they need to be migrated into Parameter Store first. This temporary job aids the migration by automatically syncing the project vars into Parameter Store whenever it detects that a project has Parameter Store enabled but its vars are not in sync.
Tested it on a branch project and repo project in staging, and it synced their vars as expected.
N/A

DEVPROD-9423: create job to sync project vars to Parameter Store

---

model/project_vars.go
units/parameter_store_sync.go

DEVPROD-9423
Small fix that I caught while migrating all the projects in staging over to Parameter Store - apparently, some very old projects don't have an associated project vars doc (newer ones always appear to have corresponding project vars, even if it's empty).
* Handle nonexistent project vars for Parameter Store sync project.
* When comparing updated project vars against project vars that don't exist currently, ensure skeleton project vars are initialized with the project ID - this isn't actually necessary for correctness right now, but I have a sense that this is an easy way to prevent bugs in the future if someone assumes the before vars have a project ID set. 
N/A

DEVPROD-9423: initialize skeleton project vars when they do not exist

---

model/project_vars.go
model/project_vars_test.go

DEVPROD-12713
Error out early if trying to set a project variable to an empty string value. Parameter Store requires parameter values to be non-empty, and the Evergreen UI/REST API currently do not let users set empty project variables either.
N/A

DEVPROD-12713: do not allow empty project variable values

---

graphql/tests/query/projectEvents/results.json
model/project_event.go
model/project_event_test.go
rest/data/project.go
rest/data/project_test.go
service/event_log.go

DEVPROD-11826
When storing a project event in the DB, replace the project's GitHub app private key with a `{REDACTED_BEFORE}`/`{REDACTED_AFTER}` placeholder to prevent it from appearing in plaintext in the DB.
* Tested adding/deleting GitHub app credentials in staging.
N/A

DEVPROD-11826: redact GitHub app auth from project event log

---

rest/route/service.go

DEVPROD-7600
This removes the /git/patch agent route which was kept for agents running an older revision.
This should be merged in next week sometime
#8455

DEVPROD-7600 Remove carry over agent route /git/patch in favor of /patch

---

model/githubapp/github_app_auth.go
model/project_ref.go

DEVPROD-12217
* Add a field that tracks where a project's GitHub app private key is located in Parameter Store.
* Add a temporary field indicating if the GitHub app private key is synced to Parameter Store. This is analogous to the one made for project vars in DEVPROD-9393.
N/A
N/A

DEVPROD-12217: add fields for GitHub app private key parameter

---

model/githubapp/github_app_auth.go
model/project_ref.go
model/project_vars.go
model/project_vars_test.go
units/parameter_store_sync.go

DEVPROD-12217
Before, the Parameter Store parameters would be upserted into the project vars document separately from the main DB query. This wasn't ideal since it means the project variables could be partially updated (e.g. the project variable could be created but not marked as private). Now, these operations should all happen within a single atomic DB write.
Updated existing tests.
N/A

DEVPROD-12217: make Parameter Store updates atomic

---

docs/Project-Configuration/Task_Traces.md

DEVPROD-12932
Adds documentation on best practices for naming spans. This is based on https://github.com/evergreen-ci/ui/blob/1d98d068d627ded6984d8113deba2ff879a31295/ANALYTICS.md

docs: DEVPROD-12932 Add section on best practices for event traces

---

model/task_queue_service_dependency.go
rest/route/host_agent.go

DEVPROD-12086
The change from #8479 appears to be stable, but one of the logs appears to be both noisy and not providing too much insight, so removing it. The other two logs hit much less frequently and I believe to offer some insight so opting to keep those and change them from debug -> warning logs.

DEVPROD-12086 Remove noisy log

---

model/project_event.go
model/project_event_test.go
model/project_test.go
rest/data/project_test.go
rest/model/project_event.go
rest/model/project_event_test.go
rest/route/project_events_test.go

DEVPROD-12860
The plan to stop storing project var values in the DB includes [removing the BSON tag from the `ProjectVars` model](https://github.com/evergreen-ci/evergreen/blob/3e97e565fadb2db8e2bba635b132a4eb99ef4e4d/model/project_vars.go#L54-L57) - this is a security measure to avoid putting vars in the DB and future-proofing so that nobody can insert them into the DB by accident. Unfortunately, the [project change events](https://github.com/evergreen-ci/evergreen/blob/3e97e565fadb2db8e2bba635b132a4eb99ef4e4d/model/project_event.go#L24-L30) still needs a map of vars stored in the DB to keep track of which vars changed, so currently, removing the `ProjectVars.Vars` BSON tag will _also_ remove the vars from the event log. The easiest way to keep track of modified vars in the project event …

DEVPROD-12860: split project events model from project vars

---

graphql/query_resolver.go
graphql/tests/query/waterfall/results.json

DEVPROD-10200
In design sync, we decided we can remove the offset in the date filter. The most recent matching commit will show up as the leftmost version.
- Updated GraphQL tests

DEVPROD-10200: Remove offset from date filter in Waterfall query

---

model/project_parser.go
model/project_parser_test.go
rest/route/agent.go

DEVPROD-12560
This removes the retry marshal bson which was an attempt to fix tasks that were failing on specific distros with a route that returns this marshal'ed data. The log line was never hit, so we can confirm that it's not the problem (my concern was this is still using the legacy evergreen custom go driver/marshal program).

DEVPROD-12560 Remove RetryMarshalBSON on project parser struct

---

docs/Reference/Task-Statuses.md

From [DEVPROD-12690](https://jira.mongodb.org/browse/DEVPROD-12690)
Simplified the statuses page to accommodate documentation for version statuses. Not adding display statuses right now since this is more of a quick patch. 
pine patch: https://spruce.mongodb.com/version/673e15bfa5a7cc0007e47591/downstream-projects?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

docs: add version statuses

---

.github/pull_request_template.md

DEVPROD-12194 
Make a note to test pine for markdown only changes that could break it.

DEVPROD-12194 update PR description

---

graphql/tests/task/imageId/data.json
graphql/tests/task/imageId/queries/nonexistent_distro_task.graphql
graphql/tests/task/imageId/results.json
model/distro/distro.go

DEVPROD-11922
Runtime Environments team wants to delete distros, but they found a bug where deleting the distro makes the task page unviewable due to a 404 error. 
This PR fixes the bug by not throwing an error in the case of a missing distro.
- I made a new distro on staging called `ubuntu1604-large-mina` and then ran a [task](https://spruce-staging.corp.mongodb.com/task/sandbox_ubuntu2004_batchtime_task_patch_35af2286511f3b738ce514b25c45b21f6b35af28_673ff91a1a77c40007e2d0fa_24_11_22_03_23_38/logs?execution=0) on that distro. Then I deleted the distro, which caused the task page to error with a 404. After applying the changes in this PR, I could view the task page properly again.

DEVPROD-11922: Prevent task page from erroring due to missing distro

---

model/host/host.go
service/host_test.go

DEVPROD-12451
When un-quaranting a static host that has been quarantined for a while, sometimes it can get immediately re-quarantined because of a race:
- [this host monitoring job](https://github.com/evergreen-ci/evergreen/blob/bd1bfa286f54049a9bc31c34b938bb64118d3fa1/units/host_monitoring_check.go#L52) auto-quarantines the host for having a `LastCommunicatedTime` from too long ago, before the [re-provisioning job](https://github.com/evergreen-ci/evergreen/blob/ccc124bd866f1cb74b4a3fd513771d524eac1802/units/util.go#L73) (which gets queued immediately when the host is un-quarantined) can update `LastCommunicatedTime`.
This change updates a host's `LastCommunicatedTime` right at the time it gets marked as reprovisioning to fix this.
Added a check to an existing unit test

DEVPROD-12451 Update last communication time during host reprovisioning

---

cloud/parameterstore/fakeparameter/fake_parameter.go
model/host/host.go
model/host/host_test.go

DEVPROD-5498
Currently, hosts can get hit with an idle timeout due to lack of communication with the Evergreen app server if their teardown group is sufficiently long, because the teardown group happens after task completion, so no heartbeat signals are sent during that period. 
Since the change introduced in #7635 adds protections against long-running teardown groups, it should be sufficient to skip the last communicated time in the idle host check _if_ a host is actively tearing down a task group.
[Tested in staging](https://spruce-staging.corp.mongodb.com/version/6740dfc0f354c60008e9cf6a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) (executions 3 vs 4 for reference) and confirmed that without the change, a host that just ran a task group with a long teardown group is unable to pick up …

DEVPROD-5498 Do not consider elapased communication time during group teardown

---

agent/command/s3_copy.go
agent/command/s3_get.go
agent/command/s3_put.go
config.go

DEVPROD-13165
This adds `bucket` and `temporary_credentials` otel attributes for our s3 commands (s3.get, s3.put, s3copy.copy)
s3 buckets shouldn't (and cannot be) protected through obscurity. Buckets are more prone to this since they're on a [global unique naming constriction](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) and it's pretty easy to see if one exists (`curl -sI https://<bucket_name>.s3.amazonaws.com/ | grep bucket-region` can tell you if one exists and the regions it exists in.)

DEVPROD-13165 Add Otel attributes for s3 commands

---

model/task_queue_service_dependency.go

DEVPROD-13221
Now that mutex locking has is used by various helper functions inside `FindNextTask` rather than across the entire function, there's a small chance the queue will be [refreshed](https://github.com/evergreen-ci/evergreen/blob/26704b62db54d3fcaee2654f40d6999af39e4605/model/task_queue_service_dependency.go#L73)  in-between those helper functions, leaving subsequent helper functions with stale data. 
Added some checks to return nil if this happens. This should fix the occasional nil dereference / index OOB we've been seeing.
Existing tests

DEVPROD-13221 Add more nil checks to dispatcher

---

model/task_queue_service_dependency.go

DEVPROD-13221
I didn't realize that the `graph.Node` structs can also be nil, they need to be nil-checked as well. This should address the other panic we saw.

DEVPROD-13221 Add extra nil-check

---

graphql/tests/query/projectEvents/data.json
graphql/tests/query/repoEvents/data.json
model/project_event.go
rest/data/project.go
service/event_log.go

DEVPROD-11827
I migrated all the project change event logs across all projects so that the DB only stores redacted placeholder values (`{REDACTED_BEFORE}` and `{REDACTED_AFTER}`) instead of their actual plaintext value for project vars and GitHub app private key. Because the DB docs store only redacted values now and not the plaintext value, it's no longer necessary to redact the plaintext value when reading project change events out of the DB.
* I checked a bunch of events in the prod DB to verify that the project var values and GitHub app private key are replaced with redacted placeholders.

DEVPROD-11827: remove project secrets redaction when reading logs

---

graphql/mutation_resolver.go
model/github_app_auth.go
model/github_app_auth_test.go
model/githubapp/github_app_auth_db.go
model/project_ref.go
model/project_ref_test.go
model/project_vars.go

DEVPROD-9426
When writing GitHub app private keys and Parameter Store is enabled for the project, store it in Parameter Store. Unfortunately, because the temporary feature flag is on the project ref, I can't put these functions directly in the `githubapp` package yet or else it'll cause a package dependency cycle. They'll be moved over in DEVPROD-11883 once the project ref feature flag is no longer used.
* Add functions to upsert/remove GitHub app private keys using Parameter Store as the backing storage.
* Switch GitHub app DB calls to use temporary functions for now, until DEVPROD-11883 can move them into the correct package.
* Delete `InsertGitHubAppAuth` because it's unused and didn't seem worth implementing for Parameter Store.
* Add unit tests for upsert/remove.
* Tested that the …

DEVPROD-9426: support writing GitHub app private key to Parameter Store

---

cloud/ec2_util.go
globals.go

[DEVPROD-12557](https://jira.mongodb.org/browse/DEVPROD-12557)
The IAM policy that controls SSM access only allows SSM connections to hosts tagged with `AllowRemoteAccess: true`. This PR adds this tag for all hosts evergreen starts.
The tag was added to a host that started in staging.

DEVPROD-12557 add AllowRemoteAccess tag

---

graphql/mutation_resolver.go
graphql/project_settings_resolver.go
graphql/repo_settings_resolver.go
model/github_app_auth.go
model/github_app_auth_test.go
model/project_ref.go
model/project_ref_test.go
rest/data/project_settings_test.go

DEVPROD-9430
Support FindOne for GitHub app auth, using Parameter Store to fetch the private key if Parameter Store is enabled for the project.
* Updated existing tests to ensure they have Parameter Store enabled for GitHub app auth and still pass.
* Tested in staging by enabling Parameter Store, setting a private key, and running a task to see that it read the private key from Parameter Store. I also tested that a project with Parameter Store disabled works as it did before.

DEVPROD-9430: support reading GitHub app private key from Parameter Store

---

docs/Project-Configuration/Notifications.md
globals.go
model/event/host_event.go
model/host/hostutil.go
trigger/host_spawn.go
trigger/host_spawn_test.go
units/host_setup_script.go
units/host_status.go
units/host_status_test.go
units/provisioning_setup_host.go

DEVPROD-3983
Sends notifications on the success/failure of host setup scripts to users who are opted into "Spawn host outcome" notifications, as well as increases the timeout period in which we poll for the setup script to complete to make the issue described in the ticket less likely.
Deleted an unused parameter I noticed along the way.
Forced the timeout situation in staging and confirmed the notification received was as expected.

DEVPROD-3983 Spawn host setup script notifications

---

model/github_app_auth.go
model/github_app_auth_test.go
model/project_ref.go
model/project_ref_test.go
units/parameter_store_sync.go

DEVPROD-9432
Similar to project variables, when a project has Parameter Store enabled but the GitHub app private key isn't in Parameter Store yet, sync the private key to Parameter Store.
Tested in staging to verify that the job synced the GitHub app private keys for staging projects to Parameter Store.

 DEVPROD-9432: sync GitHub app private key to Parameter Store 

---

agent/command/s3_get.go
agent/command/s3_put.go
config.go

DEVPROD-13165
This adds otel attributes for 'visibility' and 'permissions' to understand how often which one is used and the combination of them.
It also adds the remote file name, this is more for individual debugging more than aggregate results. It won't be that useful as an aggregate since projects don't use consistent paths.

DEVPROD-13165 Add more s3.get/s3.put otel attributes

---

units/parameter_store_sync.go

DEVPROD-13471
Within `FindOne` for project vars and GitHub app auth, I added a consistency check to each one to verify that when we read the values out of Parameter Store, they exactly match the project vars/GitHub app auth in the DB. However, I realized during the rollout that there's so many disabled projects in Evergreen that many of them likely would never hit that consistency check because nobody's using them at all right now.
To address this and ensure that the Parameter Store parameters are checked for consistency, I added `FindOne` as part of the sync job. Now, on top of just syncing to Parameter Store to write the secrets into Parameter Store, it'll also check that the data read out of Parameter Store agrees between Parameter Store and the DB. This improves our confidence that …

DEVPROD-13471: check data consistency after syncing to Parameter Store

---

cloud/parameterstore/parameter_manager.go
model/project_vars.go
model/project_vars_test.go

DEVPROD-13470
In DEVPROD-9472, I added a workaround to allow some project vars that are longer than 8 KB to be compressed so that they can be migrated to Parameter Store. I didn't realize when I was testing at the time that Parameter Store actually will store the gzipped binary data with no error, but it can't return that binary data properly when reading it back out because it only supports text strings, not binary data (it just returns a garbled parameter value rather than the original value because it was binary data instead of text).
To further work around this limitation of Parameter Store, I encoded the gzipped binary data to a base64 text string.
* Tested in staging that Parameter Store could both store and also successfully return back a long project …

DEVPROD-13470: encode compressed project variable bytes as base64

---

model/event/host_event.go
trigger/host_spawn.go
trigger/host_spawn_test.go
units/provisioning_create_host.go

DEVPROD-8819
The user subscription for previously listened for host creation errors in general, which would notify them when their spawn host fails to start up (e.g. due to insufficient capacity). However, the way the notification infrastructure works that means _all_ host creation errors have to be processed for notifications, even for non-spawn-hosts. This can put strain on the notification system when lots of hosts are failing to start (e.g. because many task hosts are hitting insufficient capacity).
Since we only want to process notifications for spawn hosts failing to be created, I made a more specific error message.
* Added unit tests for triggers.
* Tested in staging that starting a spawn host (and manually hard-coding an error during host creation) sent me a Slack notification …

DEVPROD-8819: make more specific host creation failure event for spawn host outcome

---

config_db.go
docs/Project-Configuration/Project-Commands.md

DEVPROD-969
just update docs to say it's deprecated

DEVPROD-969 Deprecate s3Copy.copy command

---

agent/internal/redactor/redacting_sender.go
agent/internal/redactor/redacting_sender_test.go
config.go

DEVPROD-8298 
Introduce sort to redact longer expansions first.

DEVPROD-8298 redact longer expansions first

---

docs/Project-Configuration/Project-and-Distro-Settings.md

DEVPROD-13287
Fix documentation on alias parameters to not have a keyless parameters

DEVPROD-13287 FIx documentation on alias paramters

---

agent/internal/task_config.go
agent/task_context.go
apimodels/agent_models.go
config.go
rest/route/agent.go
rest/route/agent_test.go

DEVPROD-13614
This removes the EC2 keys from the agent config. We don't use these anywhere anymore, I discovered we were still passing it through in #8566. 
Waiting for an approval before updating agent version.
Existing tests.

DEVPROD-13614 Remove EC2 Keys for ec2.assume_role from agent config

---

rest/route/distro.go

DEVPROD-12847
This removes the docs for agent routes (that are distro related). I added a comment that these routes are agent routes and shouldn't be documented. I went through all the agent routes [here](https://github.com/ZackarySantana/evergreen/blob/c31e2ccd48bf5ed6f26088827adad87981f94dbd/rest/route/service.go#L71) and these were the only two.

DEVPROD-12847 Remove docs for agent routes

---

thirdparty/github.go

DEVPROD-8559
retrying if github returns an eof because it does that sometimes

DEVPROD-8559 Retry on EOF github responses

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-11829
This documents git.get_project `token` parameter to specify that it only clones the source repository and not modules

DEVPROD-11829 Document git.get_project token parameter only clones source

---

service/api_patch.go

DEVPROD-13638
Ths has come up a few times in Slack. Currently the error message suggests logging in again through the web UI, only. This adds a more specific hint about patch permissions.
Changes a string, so should be covered by existing tests.
N/A

DEVPROD-13638 Add message about patches permission in MANA

---

rest/route/annotations.go
rest/route/annotations_test.go
rest/route/commit_queue_test.go
rest/route/distro.go
rest/route/github.go
rest/route/host_agent.go
rest/route/host_create_test.go
rest/route/host_spawn_test.go
rest/route/middleware.go
rest/route/middleware_test.go
rest/route/notification_test.go
rest/route/patch_test.go
rest/route/project_events_test.go
rest/route/project_test.go
rest/route/reliability_test.go
rest/route/service_test.go
rest/route/test.go
rest/route/user.go
rest/route/user_test.go

DEVPROD-7742
This fixes the various lint warnings and errors we have throughout our project. I'm going to open a 2nd PR to try to fix up a task to fail PR's on this lint warnings and errors, this is to keep the work separated.
Existing unit tests. Nothing stood out to me to manually test, it's mostly in test files. The ones outside of test files is just removing an unused variable, preventing a nil dereference, and other things that manual checks aren't needed for.

DEVPROD-7742 Fix lint warnings and errors

---

graphql/mutation_resolver.go
model/task/db.go
model/task/task_annotations.go
model/task/task_annotations_test.go
rest/route/annotations.go

DEVPROD-12742 - followup to #8531 et al.
- For functions that update a task's annotations, also update their display status cache. This required plumbing context through a few functions in order to use `task.UpdateOneContext` which is needed for an aggregation update operation.
- Add check for `DisplayStatusCache` in tests

DEVPROD-12742: Add display status to annotations updates

---

model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/task/db.go
model/task/task.go
repotracker/repotracker.go
repotracker/repotracker_test.go

DEVPROD-10103
The `NumDependents` field for tasks can be quite undercounted because it does not currently consider cross-variant dependencies.
- Modify places that insert tasks in per-build batches to insert all tasks for the version in a single operation
- Do not compute `NumDependents` for tasks until all tasks for the version have been created
Updated unit tests to confirm cross-variant dependencies are part of the final calculation.

DEVPROD-10103 Account for cross-build dependents in NumDependents

---

config.go
operations/fetch.go
operations/fetch_test.go

DEVPROD-11437
This change updates the Git remote configuration on spawned hosts. After fetching data with a temporary token, the remote is reset to an SSH URL to enable the use of -o ForwardAgent=yes for subsequent Git operations. 
Added a unit test

DEVPROD-11437 Reset git remote configuration after fetch

---

model/github_app_auth.go

DEVPROD-11883
Since Parameter Store is now being used for all GitHub app private keys and it's been enabled for a few weeks, it's time to start switching to using just Parameter Store. As the first step, I removed the fallback behavior for Parameter Store with GitHub app private keys. Now, if the project has Parameter Store enabled and encounters a Parameter Store-related problem, it will return the error rather than fall back to using the DB.
Existing tests that use Parameter Store still pass.
N/A

DEVPROD-11883: return on Parameter Store errors for GitHub app key

---

config.go
operations/patch.go

[DEVPROD-8938](https://jira.mongodb.org/browse/DEVPROD-8938)
For UI deploys to the new stagings there will be a new task in spruce to trigger. It would be nice to not need to use the local spruce clone (maybe you won't have the commit you're trying to deploy in your local repo, maybe your local repo is in a funny state, etc).
This PR adds an option to `patch-file` to allow empty patches. We could add it to the regular patch command, but patch-file seemed appropriate because it's already giving users more control over their patch.
Used it to create an empty patch.

DEVPROD-8938 allow empty commits with patch-file

---

agent/command/s3_get.go
agent/command/s3_put.go
config.go

DEVPROD-13165
This adds the expanded remote path/file to the otel attributes for s3 proejct commands.
This will allow for more insight for s3 commands that use a user-made expansion.
It also renames the s3.put otel attribute to match the field it is tracking (path -> file) and be more consistent with the s3.get field which is already named file appropriately.

DEVPROD-13165 Add expanded remote path to otel for s3 commands

---

.golangci.yml
config.go
operations/service_web.go

DEVPROD-7742
Before merging in the fix for our linter and adding stricter rules, I'm doing smaller PRs to fix the current mistakes that our linter should be catching.
This PR fixes the spanend lint issues. There was only one. This lint will call usually if the span isn't deferred and there's error branches that would prevent the later call to `span.End()` not to be ran.
This PR does not add the spanend to our linters yet, this is blocked on upgrading our go version. The corresponding ticket is [DEVPROD-13940](https://jira.mongodb.org/browse/DEVPROD-13940).
Running golangci-lint run in my terminal results in no more lint errors. This pulls from the .golangci.yml file's configuration (which our linter task should be doing.

DEVPROD-7742 Fix current spanend lint issues

---

docs/Project-Configuration/Project-and-Distro-Settings.md

DEVPROD-13995
Document limitations on project vars now that they're parameters in Parameter Store. All project vars currently conform to these rules.

DEVPROD-13995: document project variable limitations

---

cmd/evergreen/evergreen.go
config.go
operations/patch.go
operations/patch_module.go
operations/patch_util.go

DEVPROD-13406
This is the exact same as #8599 except for [this one fix](https://github.com/evergreen-ci/evergreen/blob/57802d0dfd3d04634b56cc71bb4d953d6c6bf7d5/operations/patch_util.go#L194-L204) - it came up in [a user thread](https://mongodb.slack.com/archives/C0V896UV8/p1736448187823239?thread_ts=1736446708.114339&cid=C0V896UV8) that `evergreen patch-file` apparently writes grip logs to stderr, whereas `evergreen patch` writes grip logs to stdout. That means when a script scans for the patch info (like the patch URL), you have to check stdout for `evergreen patch` and stderr for `evergreen patch-file`. The change in #8599 made `evergreen patch-file` write to stdout, which broke their script that was looking at stderr for the patch info.
Writing to stderr in `evergreen patch-file` seems …

DEVPROD-13406: silence patch info logs for JSON output

---

model/alertrecord/alert_bookkeeping.go
units/spawnhost_expiration_warning.go
units/spawnhost_expiration_warning_test.go

DEVPROD-13845
Fix a bug where a user would get repeated notifications for a spawn host about to expire. The issue was that Evergreen checked a random record instead of the most recent alertrecord to find out the last time it notified a user about their spawn host expiring. Now, it checks the most recent record.
Updated unit test.

DEVPROD-13845: check most recent alertrecord for spawn host expiration

---

graphql/tests/mutation/deleteGithubAppCredentials/data.json
model/github_app_auth.go
model/project_ref.go
testdata/local/fake_parameters.json
testdata/local/github_app_auth.json
testdata/local/parameter_records.json
units/parameter_store_sync.go

DEVPROD-11883
As the last step of deleting the temporary feature flag logic, delete the flag that checks if the GitHub app is synced to Parameter Store before using it for GitHub app keys. Deleting this logic should not affect any project - all projects in staging/prod are already using Parameter Store for their GitHub app keys and new projects automatically use Parameter Store for GitHub app keys.
* Stop using temporary project feature flag to indicate if GitHub app keys are synced to Parameter Store.
* Remove temporary safety check for data consistency between Parameter Store and the DB.
* Update GQL/Spruce e2e test data that were still relying on the DB to instead use the test implementation of Parameter Store for GitHub app keys.
* Manually checked that all …

DEVPROD-11883: remove temporary GitHub app sync flag

---

model/build/db.go
model/generate.go
model/generate_test.go
model/task_lifecycle.go

DEVPROD-8000
This fixes a bug where a user could get multiple notifications for a version finishing when there are multiple tasks running generate.tasks. The core of the bug is that when generate.tasks adds new tasks to an existing build, that could change the build's state, but generate.tasks didn't update the build state to reflect that, which left the build in a stale state. I fixed it so that when adding new tasks to an existing build, it updates the build's status to take the new tasks into account.
The sequence of events that cause the bug is:
1. Patch schedules generator task 1 and 2 in build variant B1.
2. Generator task 1 runs and creates a new build variant B2 with a new task T1. B1 hasn't run anything yet, so it starts out as "created".
3. T1 succeeds, so B2 finishes with …

DEVPROD-8000: fix duplicate notification for generate.tasks

---

docs/Project-Configuration/Merge-Queue.md
model/task_lifecycle.go
model/task_lifecycle_test.go
rest/route/host_agent.go
rest/route/pod_agent.go

DEVPROD-2577
When a task in a GitHub merge queue version fails, fail the entire version. There's a subtle point that we cannot do this in a PR, since users might have triggered more tasks in a PR than are required for status checks, since they can use variant-level status checks. However, for a merge queue version, we can fail the entire version, since users can opt into only those tasks that must pass for a merge queue version to pass.
Added a unit test for the new function
Edited docs.

DEVPROD-2577 Abort all tasks when a merge queue version task fails

---

agent/command/archive_util.go
config.go

DEVPROD-13824
In a recent change I made to the tarball extraction utilities, I added the `validateRelativePath` from a github action check recommendation. This caused an unintended consequence on windows, because the data directory is symlinked to another drive. I removed the symlink and the test is passing.
We didn't do this validation before, so it's added security. Removing it does allow for tarballs to override symlinked files outside the target directory, but this isn't as much of an issue since we generally should trust users to only extract files they know they can extract.
Unit tests.

DEVPROD-13824 Do not validate symlinks when extracting tarballs

---

self-tests.yml

DEVPROD-8740
Because [go toolchains were added in go 1.21](https://go.dev/doc/toolchain), when our `verify-mod-tidy` task ran on `go 1.20`, it wouldn't catch PRs that update our go modfile to use packages past go version 1.20 (which would be an error in any go version).
This PR makes our mod tidy run on 1.23, to account for toolchain updates. This can be removed once we update our go version in this ticket [DEVPROD-3611](https://jira.mongodb.org/browse/DEVPROD-3611).
I created [DEVPROD-14092](https://jira.mongodb.org/browse/DEVPROD-14092) to revert this once we upgrade our go version.
I went back to a dependabot PR that had to be reverted and ran a [patch](https://spruce.mongodb.com/version/6786b3f412a3c20007d922df/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) confirming it falsely …

DEVPROD-8740 Use newer version of Go for verify-mod-tidy task

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-12438
This documents explicitly that `teardown_group_can_fail_task` is not supported.

DEVPROD-12438 Document teardown_group_can_fail_task is unsupported

---

docs/Project-Configuration/Project-Commands.md

[Slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1737053042790539)
I didn't see it mentioned anywhere, so I documented how generate.tasks behaves when restarting a generator task.

docs: mention generate.tasks is idempotent

---

docs/Project-Configuration/Project-Commands.md

Fix spelling/grammar on the note about generate.tasks and tagged tasks.

docs: fix spelling/grammar on generate.tasks tags

---

model/lifecycle.go
model/lifecycle_test.go

DEVPROD-14181
Updating a task's display status works properly, but if the task (or display task) was never activated or touched again after being created, its display status is unset. Ensure that it is set upon task creation.
Added test cases that fail without the new call to `DetermineDisplayStatus()`

DEVPROD-14181: Set DisplayStatusCache upon task and display task creation

---

self-tests.yml
validator/project_validator.go
validator/project_validator_test.go

DEVPROD-13370
during project validation, any tasks that specify a single task distro will need to be on an allowed list or it will error
unit testing
(e2e will be done later)

DEVPROD-13370 Validate single task distros during project validation

---

model/githubapp/github_app_auth.go
model/githubapp/github_app_auth_db.go

DEVPROD-9444
Now that all projects are using Parameter Store for GitHub app private keys, remove the BSON tags and remaining logic that sets the private key in the DB.

DEVPROD-9444: stop storing GitHub app private key in the DB

---

scheduler/utilization_based_host_allocator.go
scheduler/utilization_based_host_allocator_test.go

DEVPROD-14352
The host allocator [considers](https://github.com/evergreen-ci/evergreen/pull/8656/files#diff-95de4a2bca507d57fa07c55462bf2cf30ebe31780c6f6cbbb78f3eb59e0bd957L250-L262) the list of all available hosts for every single task group. So, the estimated number of free hosts will be over-counted by one multiple for every group in the queue (as the deleted comment mentions). This can cause the estimate to be extremely high, as in [this](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/hC4AGLpiVr6/trace/2UphHy19gsR?fields[]=s_name&fields[]=s_serviceName&span=447cb0fcee636665) example, where `evergreen.host_allocator.hosts_free` was over 46,000. 
This suppresses the number of hosts that are spawned because the allocator thinks there is no need to …

DEVPROD-14352 Prevent double counting of free hosts

---

agent/agent.go
agent/agent_test.go
agent/command/mock.go
agent/task_context.go
config.go

DEVPROD-14089
When a command manually sets the end task status to failure, the task should treat that as the failing command and include its failure metadata tags. However, it used the wrong tags if it set the task status to failure and continued on error because the failure metadata tags were taken from the last command that ran before deciding the task status, rather than from the command that set the task status.
Improved existing unit tests.

DEVPROD-14089: fix failure metadata tags when user-defined end task response continues

---

model/project_vars.go
rest/data/project.go
rest/model/project_event.go

DEVPROD-9443
* Stop storing project vars in the DB.
* Look up all project vars after `FindAndModify` to ensure that the project vars is populated with all the project's vars, not just the modified ones.

DEVPROD-9443: stop storing project vars in the DB

---

scripts/prepare-swagger-push.sh
self-tests.yml
service/service.go

DEVPROD-9733
S&I wanted some consistent versioning for our openapi generated spec (we use swaggo/swagger). This adds a second file that keeps track of the sha256 of the swagger.json and the current version number. If the sha256 changes, the version number gets incremented by one. This means we don't use semantic versioning for our swagger.json which goes against openapi specifications- but I don't think that's worrisome since the depending service seemingly only uses the version number for reliable historic builds.
I ran [this](https://spruce.mongodb.com/task/evergreen_ubuntu2204_push_api_docs_patch_b6d5c387fd0017ff8d0c4eee73056423cdf0cc13_67868af052e2b50007cf1822_25_01_14_16_04_08/files?execution=0) which started the versioning at 2. I ran a duplicate task …

DEVPROD-9733 Add OpenAPI version to generated spec

---

agent/command/s3_put.go
config.go
model/artifact/artifact_file.go

DEVPROD-13972
This makes presigning internal buckets fallback to using the stored credentials. This is temporary while I add a lot of internal buckets in future project tickets. I added some TODO's and a ticket label in the grip message.
I ran [this task](https://spruce-staging.corp.mongodb.com/task/zackary_bisect_s3put_private_s3put_visibility_signed.permissions_private_patch_e912fa78d2522a2bf7f99ee1ba171b36b94ae598_679260e37b3d1e00072f445a_25_01_23_15_31_58/files?execution=0) and then I manually switched the bucket to one that our IRSA doesn't have. I then checked splunk and found the corresponding [log](https://mongodb.splunkcloud.com/en-US/app/search/search?display.page.search.mode=fast&dispatch.sample_ratio=1&q=search%20index%3D%22evergreen-staging%22%20%20%7C%20spath%20message%20%7C% …

DEVPROD-13972 Fallback to credentials for IRSA presign failures

---

model/lifecycle.go
model/patch_lifecycle_test.go
model/version.go

DEVPROD-11707
To make the waterfall more functional when filters are applied that match no versions currently on the page, we'll perform a server-side query to fetch additional versions (these GraphQL query updates will be added in an upcoming PR).
This change will allow us to support querying versions by build variants without having to examine any build or task documents by adding the build variant's display name when the build variant is saved to a version's `BuildVariants` field.
Update unit test

DEVPROD-11707: Save build variant display name with version

---

model/artifact/artifact_file.go

DEVPROD-13972
Looking at the [splunk logs](https://mongodb.splunkcloud.com/en-US/app/search/search?display.page.search.mode=fast&dispatch.sample_ratio=1&q=search%20index%3D%22evergreen%22%20%20%7C%20spath%20message%20%7C%20search%20message%3D%22presigning%20with%20IRSA%20failed%22&earliest=-15m&latest=now&workload_pool=standard_perf&sid=1738008345.16058254), the error is never printed. I think this is because grip [doesn't handle err inside of its fields](https://github.com/mongodb/grip/blob/main/message/interface.go#L58).
The error should provide a lot of context, because the urls posted in the logs are working for me.

DEVPROD-13972 Log error when fallbacking during presigning a file

---

graphql/query_resolver.go

DEVPROD-12696
Ahead of further GraphQL cache improvements to the waterfall, skip fetching version build variants and tasks if not requested in the GraphQL schema
Existing tests pass; also ensured that negating the `if` condition caused tests to fail which means we're accurately accessing the request's fields.

DEVPROD-12696: Skip waterfall buildVariants pipeline if not requested

---

graphql/generated.go
graphql/schema/types/version.graphql
graphql/schema/types/waterfall.graphql
graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/queries/no_filters.graphql
graphql/tests/query/waterfall/queries/waterfall_builds.graphql
graphql/tests/query/waterfall/results.json
graphql/version_resolver.go
model/waterfall.go
model/waterfall_test.go

DEVPROD-12696
The waterfall schema currently returns versions separately from the page's build variants. This was a helpful schema for rendering the page easily, but limited how much we could leverage parallelization and Apollo caching.
I've added a field within the `Version` type that returns all of the builds and tasks for that version. This means that instead of one large query, there are several that run in parallel. The new pipeline reuses a large chunk of the old one so it's pretty well tested. Though organizing the builds into build variants now needs to be done on the client side, performance overall should be faster.
Added unit tests
On [Honeycomb](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/jx958rsSD2s/trace/cLbdAWcWwAB?fields[]=s_name&fields …

DEVPROD-12696: Parallelize waterfall queries

---

model/artifact/artifact_file.go
model/artifact/otel.go

DEVPROD-13976
I originally added splunk logs and with the limited logs I got, the error trace is a cancelled context. I thought it might be the get requests taking long on verifying the presigned urls, so I ran a local example with the url- it was extremely fast. This probably means that some code is cancelling the context (or giving a cancelled context). This honeycomb tracing will help diagnose what is doing it.
Staging task produced [this honeycomb query](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/ykrKQWUZomX/trace/vo6xFscXm3B?fields%5B%5D=s_name&fields%5B%5D=s_serviceName&span=1128719cc73cc4e6).

DEVPROD-13976 Add otel to presign file func

---

graphql/tests/version/upstreamProject/data.json
graphql/tests/version/upstreamProject/queries/no_upstream_project.graphql
graphql/tests/version/upstreamProject/results.json
graphql/version_resolver.go

DEVPROD-12696
To minimize the number of requests to the database within the `Version/upstreamProject` resolver, only check for a trigger ID if the version's requester is `trigger_request`
- Add test for no upstream project
- Fix inconsistent test data so that test passes

DEVPROD-12696: Only check for upstream project for trigger versions

---

scheduler/scheduler.go
units/provisioning_create_host.go

DEVPROD-14433
Currently, task hosts are not configured to retry in the host creation job, and hence cannot tap into the existing logic we have to retry and [try and get an instance in a different subnet ](https://github.com/evergreen-ci/evergreen/blob/430c180722b8f08cb22eaddd15a88d091ad4d303/cloud/ec2.go#L314-L341)if we run into an insufficient capacity error from AWS. Did some extra driveby code cleanup.
Had discussion with infra who said enabling this for task hosts is unlikely to cause any issues. 
In staging, I hardcoded `RunInstances` to return an insufficient capacity error 50% of the time, and started up some patches, and confirmed that hosts were using the retry logic and coming up in different subnets.

DEVPROD-14433 Introduce retry for task host creation

---

agent/globals/globals.go
cloud/docker_client.go
config.go
globals.go
model/host/hostutil.go
operations/agent.go
operations/service_deploy_smoke.go
units/provisioning_agent_deploy.go

DEVPROD-8409
The `localhost:2285/status` agent endpoint that's available to tasks currently leaks the host secret in plaintext to tasks because the endpoint returns process command-line arguments such as the agent's host ID/secret (e.g. `evergreen agent --host-id <HOST_ID> --host-secret <HOST_SECRET>`).
To prevent the `/status` endpoint from returning the host secret in plaintext, I changed the way the agent receives its host ID/secret so that they can be set as environment variables for the process instead of command-line arguments. I can't actually remove the command-ine arguments until this is deployed to prod + I do some post-deploy work to update static hosts (see below).
As I mentioned under testing, staging has drifted pretty far from prod for distros, so it's not possible to test …

DEVPROD-8409: support host auth using env vars

---

config.go
model/host/hostutil.go

DEVPROD-8409
Now that #8680 has been deployed, new agents and agent monitors should accept the host auth env vars for host auth. To ensure this for static hosts in prod, I reprovisioned all of the running ones.
This requires the static hosts to roll over one more time to ensure the agent uses only env vars for host auth. Once this is deployed, I'm going to reprovision all the static hosts.
Tested same provisioning methods as in #8680 and they still worked.
N/A

DEVPROD-8409: remove host auth CLI arguments

---

model/lifecycle.go
model/lifecycle_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
rest/route/task_restart.go

DEVPROD-9639
When a display task is restarted, it only logs a task restart event for the entire display task. On top of this, log a task restart event for each execution task so that users can view which particular execution tasks get restarted in the UI.
* Tested in staging that restarting an entire display task and just the failed tasks both show restart events as expected. Tested both via Spruce and the `/tasks/{task_id}/restart` route.

DEVPROD-9639: log task restart event for execution tasks

---

docs/Project-Configuration/Project-Configuration-Files.md
model/version.go
repotracker/repotracker.go
repotracker/repotracker_test.go
rest/route/agent.go
trigger/project_triggers.go
units/periodic_builds.go

DEVPROD-9149
A user was reporting an old module revision being used rather than the latest. This is because we don't insert a manifest during our periodic build job and the base commit's manifest is used instead. This inserts a manifest for the periodic build job.
I simulated the situation with the commit queue repository and github merge queue repository (which I'll reference as CQ and GM respectively).
1. For the CQ repo, I added GM as a module (via a commit).
2. I added a periodic build in CQ.
3. I did a [fresh commit](https://github.com/evergreen-ci/github-merge-queue-sandbox/commit/1fd3906e41ea4d7283ff5a82e9d2a2b8b12ca960) in GM which is propagated in a log line in a CQ task (which will is now newer than the latest CQ commit).
4. It ran …

DEVPROD-9149 Create manifest in periodic build job

---

model/patch_lifecycle.go
repotracker/repotracker.go
repotracker/repotracker_test.go

DEVPROD-11707
I missed some places where a build variant's display name should be set for a version in my original PR #8663.
Add additional tests that fail without changes
Created version [on staging](https://spruce-staging.corp.mongodb.com/version/67a504ca81f295000714c4d7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) that includes display names in the DB document

DEVPROD-11707: Set build variant display name more widely

---

units/provisioning_create_host.go

DEVPROD-14433
Enabling this subnet fallback has been effective! Bumping retries to 5 in the hopes that it will reduce the remaining insufficient capacity errors even further.

DEVPROD-14433 Bump number of subnets to try on fallback

---

model/generate.go
model/generate_test.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go

DEVPROD-10558
The number of tasks activated by generate.tasks currently only includes tasks that were directly created by generate.tasks. This updates the activated task count to include dependencies that were activated as a result of scheduling a generated task that has dependencies.
* Updated existing unit test for activated generated task count.
* Tested in staging patches that the activated generated task count:
* Included a dependency on an already-existing task when the generated task depended on it.
* Didn't double-count a dependency when a generated task depended on another generated task.

DEVPROD-10558: include dependencies in activated generated tasks count

---

thirdparty/github_test.go

DEVPROD-14857
This account was deleted so it is no longer available for testing write permissions. There is no suitable user to add without risk of it breaking again and I don't think it's an important enough test to take that risk.

DEVPROD-14857 Remove evrg-bot-webhook from tests

---

model/githubapp/github_app_installation.go
rest/route/agent.go

DEVPROD-13567
* Add more retry conditions for transient GitHub app token generation errors. I used [Splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20%2Frest%2Fv2%2F*%2Fgithub_dynamic_access_token%20AND%20%22request%20encountered%20internal%20error%22%20AND%20method%20!%3D%20DELETE%20AND%20%22secondary%20rate%20limit%22%0A%7C%20stats%20count%20by%20error.message&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=&earliest=1737608400&latest=1739250000&display.page.search.tab=statistics&display.general.type=statistics&sid=1739216669.49319) to find errors generating tokens over the past few weeks. Unsure if this is a comprehensive list of errors from that route, but we can always add more retry cases if we discover more.
* Do …

DEVPROD-13567: retry GitHub token request internally

---

rest/route/agent.go
rest/route/agent_test.go

DEVPROD-13555
Errors returned as a 500 mean that the agent will retry the request. I changed some errors from 500 -> 400.
Who ever reviews, I could add a comment(s) to the ones that are non-obvious why it's 400 rather than 500 (I'm a biased observer as these are mostly routes I've created/modified recently)
Unit tests

DEVPROD-13555 Return 400 for agent route idempotent errors rather than 500

---

agent/agent.go
agent/command/results_utils.go
agent/command/results_xunit.go
agent/globals/globals.go
agent/internal/redactor/redacting_sender.go
agent/internal/redactor/redacting_sender_test.go
agent/internal/task_config.go
agent/internal/taskoutput/test_log_test.go
agent/logging.go
agent/task_context.go
agent/util/expansions.go
config.go

DEVPROD-14544
The current implementation of redaction for the host secret also exposes the secret as an expansion that users can access because [it puts the host secret in the task's expansion map](https://github.com/evergreen-ci/evergreen/blob/440e66d6447986af9701d8f3ea3ef9654caac72f/agent/logging.go#L119). I changed the redacting sender so that it accepts a second, separate map that holds Evergreen-internal secrets. That way, secret strings can be redacted if they somehow accidentally appear in the logs, but they won't be accessible to the task as expansions.
* Updated unit tests for redaction.
* Tested in staging patches that 1. [if the host secret is logged in plaintext, it's redacted from the task log](https://evergreen-multi.staging.corp.mongodb.com/kimberly-tao/task_log_raw/playgrou …

DEVPROD-14544: remove host secret from expansions

---

repotracker/repotracker.go
repotracker/repotracker_test.go

DEVPROD-14947
We should be considering requester using ShouldConsiderBatchtime rather than casing directly on repotracker version (otherwise, we don't handle push triggers correctly).
It looks like I tried fixing this line in [DEVPROD-5857](https://jira.mongodb.org/browse/DEVPROD-5857) which was reverted; however, I think that this had been more of an inadvertent fix, rather than being the reason that the PR was reverted, so I think it should still be done.
Improved existing unit test to consider more requesters.

DEVPROD-14947 consider requester correctly for batchtime

---

agent/globals/globals.go
agent/internal/redactor/redacting_sender.go
agent/internal/task_config.go
apimodels/agent_models.go
config.go
globals.go
model/project.go
rest/route/agent.go
rest/route/agent_test.go

DEVPROD-14546
Related to #8712 and building on #8708 - change the way the service user's password is redacted in task logs. Instead of setting it as an private variable in an expansion (which would allow the task to also access the service password), make it an Evergreen-internal redaction string. That way, the string will be redacted if it happens to appear in task logs, but it won't be usable as an expansion.
Tested in staging to verify that [the service password is redacted if it appears](https://evergreen-staging.corp.mongodb.com/task_log_raw/evg_windows_test_agent_patch_ad48caa8037a77d28258c49e28d04a5645d05f12_67ae5bf7ccc2e500074b8695_25_02_13_20_54_16/0?type=T#L6) and [trying to use the `${host_service_password}` as an expansion does not …

DEVPROD-14546: remove Windows service password from expansions

---

agent/command/archive_auto_create_test.go
agent/command/archive_auto_extract_test.go
agent/command/archive_util.go
agent/directory.go
cmd/load-smoke-data/load-smoke-data.go
cmd/make-tarball/make-tarball.go
config.go

DEVPROD-12984
walkdir was added in a more recent go version and is more efficient than walk (since we dont need stats) 
existing tests should pass

DEVPROD-12984 Replace Walk with WalkDir

---

docs/Project-Configuration/Task-Runtime-Behavior.md

DEVPROD-13392 
Add a small caveat about what global files we are willing to clean up, so that we can easily say no to files that don't apply. Also simplified the section header, since we'll want to add to this for [DEVPROD-13248](https://jira.mongodb.org/browse/DEVPROD-13248)

DEVPROD-13392 add global file cleanup clarification

---

model/host/hostutil.go
model/host/hostutil_test.go

DEVPROD-14546
This is the first PR to improve the overall security of the service user auth in Windows. Evergreen has a special service user on Windows hosts to give it elevated permissions to run Windows background services, and it currently passes the user/password auth via command line arguments. However, it's better practice to pass them via env vars since it's harder to access a process's env compared to the process's command line arguments (e.g. from `ps` output). After this change, the service user's password should not appear in the system logs for Windows.
I'm going to post a follow-up PR to fix the original issue that the redaction logic exposes the password as an expansion.
Tested in my staging that a Windows host could still start when using an env var for the service user's …

DEVPROD-14546: change Windows service user password to env var

---

agent/agent.go
agent/internal/taskoutput/directory.go
agent/internal/taskoutput/otel.go
agent/internal/taskoutput/test_log.go
agent/internal/taskoutput/test_log_test.go
agent/otel.go
config.go

DEVPROD-14838
Add spans to trace task output handling at the end of a task.
Updated the unit tests and tested in staging [here](https://spruce-staging.corp.mongodb.com/task/evg_ubuntu2204_js_test_ad48caa8037a77d28258c49e28d04a5645d05f12_25_02_13_16_35_45/logs?execution=1&sortBy=STATUS&sortDir=ASC).
N/A

DEVPROD-14838: Add spans for task output handling

---

service/build.go

DEVPROD-12227
Previously we weren't matching to the exact build variant, so more build variants could show up.
Verified that the case in the ticket will work with this (https://spruce.mongodb.com/version/67169fb4f1f5850007ab515b/tasks?variant=^int$ redirects to just the `04a. Int Tests Java [int]` variant, whereas https://spruce.mongodb.com/version/67169fb4f1f5850007ab515b/tasks?variant=int includes an additional variant)

DEVPROD-12227 filter github links by variant correctly

---

rest/route/host.go
rest/route/host_test.go
rest/route/service.go

DEVPROD-12123
update hosts api should use the existing modify hosts function and not use custom function
existing tests should pass 
removed one test that we do not case on anymore

DEVPROD-12123 Update update host API to use existing logic

---

agent/util/git.go
config.go
docs/Project-Configuration/Project-Commands.md
thirdparty/git.go
thirdparty/git_test.go

DEVPROD-15078
While scalar was added to git in 2.38, the --no-src option wasn't added until 2.42.1. Since we rely on that, we should require at least2.42.1. before running scalar. 
It also looks like scalar is not bundled with Windows git either, so I added it to the check that makes sure that scalar is available.

DEVPROD-15078 Require git 2.42.1 for scalar

---

cloud/ec2_client.go

DEVPROD-13396
we were only gripping for a certain case but we should be gripping all the aws errors 
ticket had an idea to put custom messages for certain errors but the error codes returned by aws should cover that and this makes the code simpler

DEVPROD-13396 Grip for all aws errors

---

rest/route/service.go

DEVPROD-15126
This caused an error when Parsley attempted to fetch certain task logs. The server doesn't reply to the OPTIONS request leading to a CORS failure for subsequent requests.
https://parsley-staging.corp.mongodb.com/test/evg_race_detector_test_graphql_cb5ecf9d7c3ddcae24605392f68724f6119dbcd2_25_02_19_22_58_03/0/3d27f57abf895ff55c6c69a597437c62?bookmarks=0,142&shareLine=28
This URL works now and doesn't work without this change.

DEVPROD-15126 Respond to OPTIONS requests for GET request routes 

---

agent/agent.go
model/distro/distro.go
model/host/host.go
units/host_allocator.go
units/host_allocator_test.go

DEVPROD-13571
This new logic should figure out how many new hosts we would need for the new single task hosts 
This is only half the logic (the other half being termination) so it cannot be tested e2e until that work is done (scheduled in project) but I decided to split them and added a unit test to verify that this logic works as expected
added a unit test specifically for the new logic and created a new ticket for adding tests for the rest of host allocator jobs

DEVPROD-13571 Allocate hosts for single task distro hosts

---

model/waterfall.go
model/waterfall_test.go

DEVPROD-10178
Brief followup to https://github.com/evergreen-ci/evergreen/pull/8731
We only want to match on build variants that have actually been activated. This information is also available in the version document.
Updated tests to ensure we match on active builds and not on inactive builds

DEVPROD-10178 (2): Only match waterfall on active build variants

---

agent/command/git.go
agent/command/git_test.go
config.go

DEVPROD-11462
When a merge queue task fails because the version has been kicked out of the merge queue because another task in it failed, the error message while cloning is a bit confusing for the other ongoing tasks. This is more of a QOL improvement rather than a needed feature. I made the error message very explicit and user-friendly on purpose, as well as stopping retries as they will not do anything.
Unit test. I grabbed the exact verbiage from failures like [this](https://parsley.mongodb.com/evergreen/mms_unit_go_UNIT_GO_GO_patch_712620e0fe53d8576a6fe300f0781e21e28dd790_66ec12a0945d7e000754cecc_24_09_19_12_01_41/0/agent?bookmarks=0,267&selectedLineRange=L84&shareLine=84)

DEVPROD-11462 Stop git.clone on invalid GitHub merge queue ref

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-14878
Docs update on the permissions and visibility parameters of s3.put. This makes the documentation show usage of private and signed uploaded documents.

DEVPROD-14878 Update s3.put docs on permissions and visibility

---

agent/command/git.go
agent/internal/client/base_client.go
agent/internal/client/interface.go
agent/internal/client/mock.go
config.go
model/githubapp/github_app_auth.go
model/githubapp/github_app_installation.go
model/githubapp/github_app_test.go
rest/route/agent.go
rest/route/agent_test.go

DEVPROD-14314 
This edits the token cache to cache tokens based on the permissions they are scoped to. 
Added to existing tests

DEVPROD-14314 Fix cached tokens giving incorrect permissions

---

model/host/hostutil.go
model/host/hostutil_test.go
operations/agent_monitor.go
units/provisioning_restart_jasper.go
units/provisioning_setup_host.go

DEVPROD-14912
* Remove logic that puts the Splunk token file on task hosts.
* Add temporary logic to try cleaning up the Splunk token file on long-lived static hosts.
Once this is deployed, I'm going to reprovision all the running static hosts to remove the file and remove the Splunk token file parameter.
* Tested in staging that a host provisioned with SSH could run tasks.

DEVPROD-14912: remove Splunk token file

---

environment.go
rest/route/notification.go

DEVPROD-15268
during a slack outage, we will fail to initialize evergreen since we error on it but we should log and continue

DEVPROD-15268 Don't error while initializing slack

---

docs/Project-Configuration/Project-Configuration-Files.md
model/generate.go
model/project.go
model/project_parser.go
model/project_ref.go
model/task_lifecycle.go
model/task_lifecycle_test.go
rest/route/host_agent.go
rest/route/pod_agent.go

DEVPROD-12270
Allow setting deactivate previous from the build variant level. 
This uses the same logic for when to default as stepback. I didn't implement for the task level to keep the PR lighter, and it's not requested so we could just do it in the future. 
I refactored MarkEnd and attemptStepback a bit so that we're still only pulling parser project and projectRef once. Passing in deactivatePrevious was likely to save a project ref call (it doesn't really do anything else, as evidenced by the unit tests passing), so I removed that as well. 
Didn't add to matrices since this is deprecated (although it's honestly not complicated so I _could_... if anyone feels strongly i'll put up a PR after this one)
Ensured existing unit tests work when updated, and added an additional test for …

DEVPROD-12270 support unschedule old tasks at build variant level

---

units/host_termination.go
units/host_termination_test.go

DEVPROD-14909
If you decommission an intent host, it'll just stay decommissioned forever, and the host termination job will infinite loop on it because it looks for a host in the cloud provider. I changed the host termination job to just mark the host terminated if it's a decommissioned intent host.
* Updated unit test.
* Tested that decommissioning an intent host in my staging eventually led to it being terminated.

DEVPROD-14909: allow intent hosts to be decommissioned

---

cloud/cloud.go
cloud/cloud_test.go
cloud/ec2.go
cloud/ec2_fleet.go
model/host/db.go
model/host/db_test.go
units/host_status.go

DEVPROD-11206
This removes the provider key and secret that we pass around but don't actually use.
Unit tests.

DEVPROD-11206 Remove the provider key and secret

---

db/db_utils.go
graphql/mutation_resolver.go
graphql/project_settings_resolver.go
graphql/repo_settings_resolver.go
model/githubapp/github_app_auth_db.go
model/githubapp/github_app_auth_db_test.go
model/githubapp/github_app_auth_test.go
model/project_event.go
model/project_ref.go
model/project_ref_test.go
model/project_test.go
rest/data/project_settings.go
rest/data/project_settings_test.go
rest/route/agent.go
rest/route/project.go
rest/route/project_copy.go

DEVPROD-14162
This passes context through to the GitHub app auth database functions. This involved some context threading to some higher level functions and the creation of UpsertContext to support an upsert use case.
I didn't go and update all references that could be passed a context from this, as it's out of scope for the ticket
Unit tests.

DEVPROD-14162 Pass context in to GitHub app auth database functions

---

docs/Project-Configuration/Project-and-Distro-Settings.md

DEVPROD-10154
This behavior isn't worth changing right now but we should document it.

DEVPROD-10154: document that a waterfall version required to trigger git tag versions

---

agent/agent.go
config.go

DEVPROD-14795 
Log when the agent cannot find a task so that the user can see what went wrong.

DEVPROD-14795 Log when agent cannot find task in parser project

---

config.go
operations/patch.go

DEVPROD-13915
--json was not outputting a full json output for patch-file 
verified it was broken previously
tested that the output was what we expected 
`❯ evgs patch-file --diff-patchId 67c0bee74cf228000778d862 -j
{
"patch_id": "67c0c82567db8800076937a5",
"description": "DEVPROD-13915: DEVPROD-15025 Switch from Gp2 volume default to Gp3 default (#8752)",
"project_id": "mci",
"project_identifier": null,
"branch": "mci",
"git_hash": "97c3401b9c5e75d121afce6afe40b04abeb9a06b",
"patch_number": 808,
"hidden": false,
"author": "bynn.lee",`

DEVPROD-13915 Fix json output for patch-file command

---

config.go
operations/model.go
operations/patch_util.go

DEVPROD-10230
Discovered that if we're using the module include feature, and disable_auto_defaulting is set, then we don't cache the file so we ask for it for every included file (from a module).    
Tested it by adding two included files from module. Simplified output:
```
ui [DEVPROD-11928] $evergreen patch --include-modules -p evergreen-ui -u
Enter absolute path to module 'commit_queue' to include changes (optional): 
Enter absolute path to module 'commit_queue' to include changes (optional): 
ui [DEVPROD-11928] $evergreen-with-changes patch --include-modules -p evergreen-ui -u
Enter absolute path to module 'commit_queue' to include changes (optional): 
```

DEVPROD-10230 avoid asking for CLI module paths repeatedly

---

agent/agent.go
config.go

DEVPROD-14778
the logger needs to flush to show check run errors so I moved the flush to after we run the check run

DEVPROD-14778 Flush logger after running check run

---

rest/data/project.go
rest/route/project.go

DEVPROD-13613 
As discussed in triage, we want to log and continue on this error so that we aren't prevented from continuing errors. Doing this only for the upsert case rather than tryCopyingContainerSecrets since more of those errors seem valid. 
Will ensure existing tests pass.

DEVPROD-13613 log and continue on container secret upsert error

---

graphql/tests/query/waterfall/data.json
graphql/tests/query/waterfall/results.json
model/waterfall.go
model/waterfall_test.go

DEVPROD-15048
Right now, we are sorting by task IDs, which can lead to inconsistent results. 
Consider the following case:
* `build-and-push-darwin-unsigned` 
* `evg_build_and_push_display_build_and_push_darwin_unsigned_e2289911f2d07f303e220fd32627eb41c7517a7e_25_02_27_21_09_07`
* `build-and-push`
* `evg_build_and_push_display_build_and_push_e2289911f2d07f303e220fd32627eb41c7517a7e_25_02_27_21_09_07`
Even though `build-and-push` should come alphabetically before `build-and-push-darwin-unsigned`, the IDs dictate otherwise due to the randomly determined version hash. We should sort by display name instead.
On staging. 
Before:
After:
Also added unit tests.

DEVPROD-15048: Sort waterfall tasks alphabetically by display name

---

agent/internal/task_config.go
agent/util/ec2.go
agent/util/ec2_test.go
config.go
model/host/host.go
model/host/host_test.go
operations/agent_monitor.go
operations/host_provision.go
rest/client/interface.go
rest/client/methods.go
rest/data/host.go
rest/model/host.go
rest/route/host.go
rest/route/host_test.go

DEVPROD-13207
This is half of the change for DEVPROD-13207 - this change makes so that the EC2 hostname is set in Evergreen before it runs its first task. Re [this comment](https://jira.mongodb.org/browse/DEVPROD-13207?focusedCommentId=7108350&focusedId=7108350&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-7108350), we can't just get the hostname directly from Evergreen currently, because Evergreen may not have fetched the hostname from EC2 yet. To work around this, EC2 hosts will provide their own hostname from the locally-available EC2 instance metadata on the host. The host will then send that hostname back to Evergreen.
After this is merged, I'll post a follow-up PR to expose the hostname as an OTel attribute for tasks.
* Tested in …

DEVPROD-13207: set EC2 hostname during host provisioning

---

agent/agent_test.go
agent/command/archive_auto_create_test.go
agent/internal/client/base_client.go
agent/internal/client/interface.go
agent/internal/client/mock.go
agent/internal/task_config.go
agent/internal/task_config_test.go
agent/internal/testutil/task_config.go
agent/task_context.go
agent/util/ec2.go
agent/util/ec2_test.go
apimodels/agent_models.go
config.go
globals.go
operations/host_provision.go
rest/route/agent.go
rest/route/service.go

DEVPROD-13207
Follow-up to #8775, which set the EC2 hostname is set before the agent starts running tasks. This change sets the hostname as one of the task's OTel attributes.
* Set hostname on task OTel attributes.
* Rename "host name" from #8775 to "hostname" because most of the software world has seemingly agreed to call it "hostname" as one word.
* Refactor `NewTaskConfig` to take an options struct because the parameter list is getting out of hand.
Tested in staging that the hostname attribute appears in Honeycomb traces for Ubuntu/Windows hosts.

DEVPROD-13207: add hostname to OTel attributes

---

go.mod
go.sum

DEVPROD-11824
I noticed that #8786 [removed the gqlgen tool](https://github.com/evergreen-ci/evergreen/commit/e49feb9d582db1fadec39319f611118569fe1454#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L233), which is needed for `make gqlgen`. Re-added it back in.
`make gqlgen` works again.

DEVPROD-11824: re-add gqlgen tool

---

graphql/tests/query/waterfall/data.json
model/waterfall.go

DEVPROD-15468 - followup to https://github.com/evergreen-ci/evergreen/pull/8785
I incorrectly wrote the match operators for build variant filtering such that a version would match if it had _any_ active build and _any_ build that matched the string. We need the build that contains the string match to be active, so use `$elemMatch` to accomplish this.
Update test data such that tests fail with the old incorrect logic. However, since I added an inactive build to test data, the new query operators correctly don't find a match and the test passes.

DEVPROD-15468: Use $elemMatch operator to search build variants

---

model/task_lifecycle.go

DEVPROD-15568
This fixes a potential panic where the `task.GetDisplayTask` can return `nil, nil` which we would try access the display task regardless.
Unit tests

DEVPROD-15568 Fix a panic in evalStepback

---

agent/agent.go
agent/directory.go
agent/directory_test.go
agent/globals/globals.go
agent/internal/client/interface.go
config.go

DEVPROD-14995
This is part of the change for DEVPROD-14995. The overall goal is that if the agent fails to clean up the task directory, it should determine if it should take on another task, otherwise it should decommission/quarantine. I added a basic check to decommission/quarantine a host (static or ephemeral) if it fails to clean up 3 task directories, since that would be a sign that the data volume is filling up with too much leftover task state.
I'm going to make a follow-up PR to make it a little smarter so it can make decisions based on the disk space left. For example, if it fails to clean up one task directory but that task directory uses up 90% of the data volume's available space, quarantine immediately.
Tested in staging that it decommissioned an ephemeral host.

DEVPROD-14995: disable host after multiple failures cleaning up task directory

---

.github/dependabot.yml

DEVPROD-6962 
Unignore these dependencies (we're on version 1.24)

DEVPROD-6962 Unignore dependencies that require updated go version

---

docs/Project-Configuration/Project-Configuration-Files.md
model/project.go
model/project_test.go

DEVPROD-15595
There's no reason for this to be owner/repo only; we can just use this in general.
Updated expansion test.
Updated documentation text for these two fields. (I also alphabetized this list because i found it helpful?? but if you hate it i'll undo that)

DEVPROD-15595 extend github org/repo expansion

---

agent/command/s3_put.go
config.go

DEVPROD-12041
This commit prevents the retry loop from running when we are using skip_existing: true in s3.put. This doesn't cause anything to fail, but the logging and extra API calls are unnecessary.

DEVPROD-12041: stop skip_existing retries in s3.put

---

agent/agent.go
agent/directory.go
config.go

DEVPROD-14995
After looking at some hosts in prod, it seems like the agent unfortunately [fails to clean up task directories pretty often on static hosts](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20macos-14-arm64%20%22host%20has%20been%20decommissioned%20or%20quarantined%22%20%22clean%20up%20task%20directories%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&workload_pool=&earliest=1741406400&latest=1741615200&sid=1741615599.348925). While failing to clean up the task directory a few times should warrant a quarantine, it's more work to manage the more frequent quarantines (and I believe fixing the underlying task directory cleanup issue isn't that easy).
To make quarantines less frequent, I reduced the data directory health check to …

DEVPROD-14995: remove check for number of task directories that fail to clean up

---

model/generate.go

DEVPROD-14942
The error described in the ticket was caused by an app pod terminating while a generate tasks job was already inflight, causing only half of the tasks to be generated ([trace](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/C2JnL5XNLm/trace/yXHFFcmhgBQ?fields[]=s_name&fields[]=s_serviceName&span=22ae61f2678c7cbb)).
When the job was re-attempted on another app pod ([trace](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/evergreen/result/C2JnL5XNLm/trace/AEnscnMYovf?fields[]=s_name&fields[]=s_serviceName&span=903f00ffd291378f)), the tasks that were already generated counted on top of the tasks that were to be generated according to the input JSON, causing some double counting and triggering the max tasks per version …

DEVPROD-14942: Exclude already generated tasks from max tasks error

---

units/host_termination.go

DEVPROD-15633
I accidentally removed a return in [this commit](https://github.com/evergreen-ci/evergreen/commit/936f965fb3e7124df303043bff58dae06c3092d3#diff-6dd488a00c797fb521cd37e03c8869d4fb82c17ee75a9c79eec5648ed8f7a05bL164-L169). For intent hosts, there's no need to do any further cleanup once the host status is set to terminated in the DB.

DEVPROD-15633: finish host termination after setting intent host status

---

agent/command/s3_put.go
config.go

DEVPROD-13976
This adds back storing the keys for internal buckets to ensure we don't have any artifacts that do not have their keys stored while we add more internal buckets.

DEVPROD-13976 Store keys for internal buckets

---

agent/agent.go
agent/agent_test.go
config.go
model/host/hostutil.go
operations/agent.go

DEVPROD-13572
agent exits after looping once if the task is a single task distro task
it does not currently exit if the task is a single host task but does not fully handle the single host task group case which will be covered later 
added a unit test for agent ending the loop
will do a full end to end test with some logging next ticket
tested on staging that each task starts a new host and terminates it at the end

DEVPROD-13572 Update agent to end after running single task host task

---

model/host/host.go
model/host/host_test.go
units/host_allocator.go

DEVPROD-8937
Caps the number of intent hosts we can be processing at once to prevent over-logging.
Unit test + confirmed the query is not slow.

DEVPROD-8937 Set a max number of intent hosts

---

config.go

DEVPROD-11824
Sets a custom dialer and max connection idle time for the mongo driver. This is to mitigate some issues happening with connection time outs
Unit testing. Deployed to staging and scheduled lots of tasks

DEVPROD-11824 Use custom dialer and set max connection idle time for mongo driver

---

config_bucket.go
config_test.go
public/static/js/admin.js
rest/model/admin.go
service/templates/admin.html

DEVPROD-13980
This adds project to prefix mappings to the buckets config.
For context, this is specifically for the `mciuploads` bucket. This config will give access to projects for a prefix. This is to enable a lot of developer workflows like the master mongo project's prefix being used in branch projects (e.g. 8.1, etc)
Deployed to staging, set the fields, refreshed, removed some, refreshed. This is how it looks:
This is with some that I added, clicked saved, then refreshed:
This is after I deleted two (first and third, left the 2nd), clicked saved, then refreshed:

DEVPROD-13980 Add project to prefix mappings to buckets config

---

self-tests.yml

DEVPROD-15371
Downloading the internal repo for Go modules occasionally fails cloning internal modules on Windows. Turns out it's because specifically on Windows, the agent doesn't clean up the global `.gitconfig` file between tasks due to DEVPROD-15806.
`git config --global url."https://x-access-token:${github_token}@github.com/evergreen-ci/".insteadOf https://github.com/evergreen-ci/` appends a new configuration line to `.gitconfig` to set the URL to use when cloning Go modules. If the global `.gitconfig` already contained some pre-existing clone URL from a previous task, the new clone URL that was appended would be ignored in favor of the earlier clone URL. The Windows self-test task would flake because it would occasionally be assigned to a host that had already run a previous Windows …

DEVPROD-15371: clean up git config before setting auth token

---

rest/data/distro.go
rest/route/distro.go
rest/route/distro_test.go
rest/route/service.go

DEVPROD-15018 
route for copying distros 
takes in single_task_distro field to make the creation of these distros easier for the buildenv team
unit tests 
tested on staging route works and created these distros 
https://spruce-staging.corp.mongodb.com/distro/routecopy1/settings/general
https://spruce-staging.corp.mongodb.com/distro/routecopy2/settings/general

DEVPROD-15018 Add route to copy distros

---

agent/command/s3_put.go
config.go

DEVPROD-13973
I readded storing keys while I added a lot of internal buckets- to make sure all artifacts have some type of coverage/retrieval method. This reverts it back.
Info in ticket thread.

DEVPROD-13973 Stop storing keys for internal buckets

---

self-tests.yml

DEVPROD-15507
This scopes down our tokens generated in self-tests to just contents: read. 
[This](https://parsley.mongodb.com/evergreen/evergreen_lint_generate_lint_ceae5aa100d628053b09b71a6ab4f80aabab4e48_25_03_17_18_32_26/0/task?bookmarks=0,301&shareLine=9) is a token generated before by our lint tests.[This](https://parsley.mongodb.com/evergreen/evergreen_lint_generate_lint_patch_ceae5aa100d628053b09b71a6ab4f80aabab4e48_67d871f2bd6d320007602cc5_25_03_17_19_03_15/0/task?bookmarks=0,301&selectedLineRange=L9) is a token generated after by our lint tests.

DEVPROD-15507 Scope down GitHub token generated in self-tests to contents: read

---

agent/directory.go
config.go

DEVPROD-11126
Windows has a restrictive maximum string length on file paths, which is difficult to work around for users. To make it slightly less difficult, I reduced the usual 32-character hash in the task working directory to be 4 characters for Windows.
Because reducing the hash also makes it less unique (16^4 instead of 16^32 possible combinations) and the fact that cleaning up previous task working directories is best-effort and not a guarantee, I added some logic to attempt to re-hash the directory in case of collisions with leftover task directories on the host.
As far as backward compatibility, there's a very slight chance that some task out there that depends on the hash being exactly 32 characters long in Windows (e.g. if they're for some reason trying to parse the task working …

DEVPROD-11126: shorten Windows task directory hash

---

rest/route/host_agent.go

DEVPROD-53
Causing some alerts in splunk, it looks like we're properly timing out- but we probably don't want to alert on the context being cancelled.
Unit tests

DEVPROD-53 Don't alert on context cancelled error when getting parser project

---

config_bucket.go
config_test.go
public/static/js/admin.js
rest/model/admin.go
service/templates/admin.html

DEVPROD-13983
This adds project to bucket mappings to the buckets config.
For context, this is specifically for the other buckets owned by devprod (internal buckets) but not `mciuploads`. This config gives access to a project to a devprod owned bucket. The prefix value is optional and to support buckets that section off based on prefix (very very few do this)
Deployed to staging, set the fields, refreshed, removed some, refreshed. This is how it looks:
This is with some that I added, clicked saved, then refreshed:
This is after I deleted two (first and third, left the 2nd), clicked saved, then refreshed:

DEVPROD-13983 Add project to bucket mappings to buckets config

---

agent/internal/task_config.go
globals.go

DEVPROD-13981
Adds a repo_ref_id otel attribute to task traces. This would've helped with the linked ticket (and might still), but I'm adding this since it's better to have it than not

DEVPROD-13981 Add repo ref id otel attribute to task traces

---

model/host/host.go
units/host_drawdown.go
units/host_monitoring_idle_termination.go
units/host_monitoring_idle_termination_test.go

DEVPROD-7795
This fixes a few bugs:
- Enable host drawdown job to decommission hosts that have been running their teardown group for longer than the allowed timeout duration
- Do not consider hosts idle if they have not provided a heartbeat and they are running teardown, since we do not send heartbeats during teardown
- Include tasks that have surpassed the teardown timeout in the idle host termination job
Existing tests

DEVPROD-7795 Consider task group timeout in idle host check

---

agent/command/s3_put.go
agent/command/s3_put_test.go
config.go
model/artifact/artifact_file.go

DEVPROD-13979
Since the project is moving static -> temp credentials, this means signing artifacts is a bit different. The s3.put calls stored the role arn that was used to perform the operation, then this will cause our presign to use that role arn to generate a temporary credential.
We already use temporary credentials with all presigning of internal buckets (e.g. `mciuploads`).
I deployed to my staging, I have these two tasks:
```
- name: role-arn-ec2-assume-role
commands:
- func: clone-project
- command: ec2.assume_role
params:
role_arn: ${assume_role_arn}
- command: s3.put
params:
aws_key: ${AWS_ACCESS_KEY_ID}
aws_secret: ${AWS_SECRET_ACCESS_KEY}
aws_session_token: ${AWS_SESSION_TOKEN}
local_file: src/old-evergreen.yaml
remote_file: ${project}/${task_id}.txt
bucket: …
```

DEVPROD-13979 Sign artifacts with stored role ARN

---

units/host_termination.go

DEVPROD-15759
If a host has already been terminated, the host termination job just marks it as terminated in the DB, so there's no need to log an error for that. I reduced the log level to info so we can still trace when it happens (since it is a little weird to terminate a host that we should already know is terminated). BUt it won't appear in the error rate, so it reduces alerting noise.
N/A

DEVPROD-15759: reduce log level for host already terminated

---

model/project.go
model/task_queue_service_dependency.go
rest/route/agent.go
rest/route/build.go

DEVPROD-15996
All of these following locations were showing up as contributing to the large number of bytes the DB is sending over the wire during periods of slowness / network saturation:
- `/task/{task_id}/expansions_and_vars` route
- `/task/{task_id}/parser_project` route
- `/builds/{build_id}` route
- `MarkEnd`
- concurrent large parser project task limit check
.WithFields are added to queries that use these frequently used queries to reduce data sent.
Existing tests

DEVPROD-15996 Use WithFields for slow version queries

---

thirdparty/github.go
units/patch_intent.go

DEVPROD-5407
When all files are ignored, Evergreen sends dummy success status checks based on the status checks that are required by branch protection rules (e.g. `evergreen` and `evergreen/ubuntu2204` for self-tests). This is needed so that the user can press the merge button. GitHub also has something called rulesets, which provides effectively the same functionality as branch protection rules, but in a different feature. To accommodate projects that want to use rulesets instead of branch protection rules, send the same success status checks for rulesets as are currently sent for branch protection rules when all files are ignored.
Worth calling out that this logic is also relied on by the merge queue when determining what pending statuses to show for a merging PR. I thought it was …

DEVPROD-5407: consider rulesets for status checks

---

units/generate_tasks.go

DEVPROD-14799
This replaces the usage of `trace.ContextWithSpanContext` with some modern std context commands. Looking at honeycomb:
We haven't been collecting spans for generate.tasks because  the `trace.ContextWithSpanContext` does not work as expected, it makes a non-recording span:
This doesn't fix the ticket, but is a step towards collecting data
Unit tests

DEVPROD-14799 Use same context as amboy job for generate-tasks jobs

---

validator/project_validator.go
validator/project_validator_test.go

DEVPROD-16089
release team wanted to be able to run the validate without specifying a project because it may not always be there 
tested on staging 
added unit test

DEVPROD-16089 Skip single task distro config validation if no project

---

db/db_utils.go

DEVPROD-15419
This removes a workaround/fallback for UpdateOne, that allowed for replacing a document rather than a true update. This is legacy usage from old code.
Unit tests, in the ticket I did some splunk queries to see if it is ever called (it isn't).

DEVPROD-15419 Separate UpdateOne and ReplaceOne implementations

---

cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_util.go
model/host/host.go
units/host_status.go

DEVPROD-16047
Currently, all Evergreen hosts are assigned a public IPv4 address. CISA requires network isolation for release task distros and on top of CISA, the runtime environments team would like to eventually slowly remove public IPv4 addresses from task hosts in general because they pose a security risk and cost money. To accommodate both the immediate CISA need and assist the future path to get rid of IPv4 addresses entirely, I added a distro setting that lets you disable public IPv4 address assignment. The implication of not assigning an IPv4 address is the host will also no longer have a public hostname, meaning we cannot SSH into them (we could use SSM to connect to the host in a more secure way if needed).
Note that spawn hosts have to always get a public IPv4 address because …

DEVPROD-16047: add distro option for assigning public IPv4 address

---

model/event/subscribers.go
model/version.go
trigger/patch.go
trigger/patch_test.go

DEVPROD-15254
There's a feature to abort merge queue patches early when at least one task fails. If the merge queue patch was aborted and the GitHub repo sets up `evergreen` (the patch-level status check) as a required status check in their settings, the merge queue item would never update the status check to failed because the patch trigger logic [suppressed notifications for patch aborts](https://github.com/evergreen-ci/evergreen/blob/f84b3ff0bdf324924445806e5f76f3195d02fdc9/trigger/patch.go#L338-L345). That check would stay stuck pending until GitHub eventually times out the merge queue item. I fixed this check so to allow the notification if the subscription is for updating the merge queue status check.
* Do not suppress notification if the patch is aborted for merge queue status …

DEVPROD-15254: send status checks for aborted merge queue patches

---

rest/data/distro.go
rest/data/distro_test.go
rest/route/distro.go
rest/route/distro_test.go

DEVPROD-15896
alias being copied could lead to confusion in what distro is used so they will not be copied in route and ui
unit tests

DEVPROD-15896 Don't copy aliases for distro copy

---

scripts/setup-credentials.sh
thirdparty/jira.go

DEVPROD-16223
IT gave us a new set of Jira credentials, so I replaced them in the project vars for our Jira integration tests. However, the `creds.yml` file isn't happy with the private key because it's a multiline string. To work around this, I changed the YAML creation script so that the project var formats the private key as a multiline YAML string, like this:
```
private_key: |
some
multiline string
```
`TestJiraIntegration` passes with changes.

DEVPROD-16223: fix Jira test

---

agent/command/s3_get.go
config.go

DEVPROD-16307
This commit adjusts s3.get to explicitly close the temporary file we create before attempting to remove it. Calling remove before closing the file is fine on Linux and MacOS, but on Windows this is not allowed and causes the error "The process cannot access the file because it is being used by another process."

DEVPROD-16307: close s3.get temporary tar file before removing

---

config_cloud.go
public/static/js/admin.js
rest/data/admin_test.go
rest/model/admin.go
rest/model/admin_test.go
rest/route/admin_test.go
service/templates/admin.html
testutil/config.go

DEVPROD-16051
For CISA, distros for release tasks have to run in a separate account from Kernel-Build. It's also the case that in the long-term, runtime environments would like to eventually have **all** distros to run in a different account than Kernel-Build. This adds an admin setting so Evergreen can deduce what AWS role needs to be assumed for each account so that it can make authorized AWS API calls. There will be a follow up PR to add the associated distro setting for the account.
If you're wondering why not just put the role directly in the distro settings, it's because of long-term maintenance concerns if the role ever changes. Volumes/hosts can be long-lived and need to know the _current_ role that should be used for AWS API calls (e.g. if someone has had an unexpirable volume …

DEVPROD-16051: add admin setting to map AWS account to role to assume

---

docs/CLI.md

Small typo in regex tasks usage.

docs: regex tasks typo

---

.github/pull_request_template.md

Adding a mention that a DPIPE Ticket needs to be made. Putting this in the description so it's less likely to be missed.

docs: add DPIPE ticket to PR template

---

cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_test.go
cloud/ec2_util.go

DEVPROD-16479
It came up while setting up the separate AWS accounts (#8908) that ideally, the separate AWS account shouldn't have an SSH key put on the host since tasks in that account aren't allowed to have SSH access. SSH won't work if the host doesn't have a public IPv4 address assigned to it, so it seems fine to not set an SSH key when the host doesn't have a public IPv4 address.
* For task hosts that have public IPv4 addresses disabled, do not set any SSH key.
* For host.create hosts, also ensure that they have public IPv4 addresses assigned just like spawn hosts (because there's no other way for a task to access the host).
* Tested in staging to verify that:
* Setting the `do_not_assign_public_ipv4_address` distro setting resulted in a task host that had no …

DEVPROD-16479: do not assign SSH key pair to hosts without public IPv4 addresses

---

globals.go
graphql/task_resolver.go
graphql/tests/task/tests/data.json

DEVPROD-16171
These code changes optimize test failure filtering by checking `Task.ResultsFailed` before querying additional services.

DEVPROD-16171: Optimize Task.test query for test failure filtering

---

cloud/cloud.go
cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_integration_test.go
cloud/ec2_test.go
cloud/ec2_util.go
cloud/mock.go
cloud/sts.go
cloud/volume.go
model/distro/db.go
model/distro/distro.go
model/host/db.go
model/host/db_test.go
rest/route/service.go
units/host_status.go

DEVPROD-16051
This adds a distro setting to specify which AWS account to use. Implicitly, we've been assuming the AWS account is always Kernel-Build and that it can make API calls using IRSA (i.e. without passing explicit auth to the AWS SDK). However, as distros shift towards using different accounts, they'll need to assume an explicit IAM role in order to make those same AWS API calls into a different account.
The general way that separate AWS accounts work is:
* Set distro setting for the account name.
* In the admin settings, add a mapping between the account name and the role ARN to assume.
* EC2 cloud provider implementations will assume the role associated with the distro's account when making AWS API calls.
* Add optional distro setting for explicit account name. Propagate that …

DEVPROD-16051: support different AWS accounts for distros

---

go.mod
go.sum

DEVPROD-16299
Upgrade Grip for mongodb/grip/pull/170.

DEVPROD-16299: upgrade Grip

---

agent/internal/client/base_client.go
agent/internal/client/interface.go
agent/internal/client/mock.go
config.go
rest/route/agent.go
rest/route/service.go

DEVPROD-16197
This introduces the initial boilerplate of the new agent route that will be responsible for sending test results to the app server which will forward the metadata to cedar's DB.
Existing tests. Configured a task to use this route in staging and confirmed the test results were formatted correctly in the debug log I added.

DEVPROD-16197 Initialize agent route to send test results data

---

graphql/image_resolver.go
graphql/mutation_resolver.go
graphql/permissions_resolver.go
graphql/query_resolver.go
graphql/resolver.go
graphql/util.go
graphql/util_test.go
model/user/user.go
model/user/user_test.go
rest/route/host.go
rest/route/host_spawn.go
rest/route/host_spawn_test.go

DEVPROD-15648
Only allow a user to spawn a host in an admin-only distro if the user has distro create permissions. This requirement applies to both GraphQL and the REST API.
* Enforce requirement that user is a distro admin before spawning a host in an admin-only distro.
* Refactor check for distro admin permissions into helper method.
* Tested in staging that trying to spawn the host through `evergreen host create` without distro create permissions resulted in an error.
* Updated existing unit test for distro admin check.

DEVPROD-15648: check if user is distro admin before spawning host

---

config.go
go.mod
go.sum

DEVPROD-16776
This commits bumps our version of pail in use to the latest. This version of pail has better performance on s3.get without any other changes to Evergreen.

DEVPROD-16776: update pail version for s3.get perf improvement

---

docs/Project-Configuration/Parameterized-Builds.md

DEVPROD-16638
Patch alias parameters should not work with periodic builds right now ([DEVPROD-16296](https://jira.mongodb.org/browse/DEVPROD-16296) makes them compatible)

DEVPROD-16638 Document that patch alias parameters do not apply to periodic builds

---

config_cloud.go
rest/data/admin_test.go
rest/model/admin.go
rest/route/admin_test.go
service/templates/admin.html
testutil/config.go

DEVPROD-16584
Evergreen is going to start using IPv4 addresses from a pool of addresses, rather than just getting one automatically allocated by AWS. Add an admin setting to specify the IPAM pool from which Evergreen can get addresses.
* Unit tests.
* Tested in local Evergreen that the admin setting worked.

DEVPROD-16708: create admin setting for IPAM pool ID

---

model/testresult/cedar_service.go
model/testresult/db.go
model/testresult/local_service.go
model/testresult/local_service_test.go
model/testresult/service_interface.go
model/testresult/testresult_test.go
operations/cli_integration_test.go
service/rest_task_test.go
trigger/task_test.go

DEVPROD-16198
Boilerplate for the interface that will be used to append test results, to be implemented in [DEVPROD-16200](https://jira.mongodb.org/browse/DEVPROD-16200).
Existing tests

DEVPROD-16198 Add write operations to test results interface

---

agent/directory.go
cmd/evergreen/evergreen.go
config.go
operations/model.go
self-tests.yml
util/filepath.go

DEVPROD-15806
The ~/.gitconfig and ~/.git-credentials files weren't being cleaned up on windows because they weren't located at the current user's home directory, they were located at C:/cygwin/home/<user>. 
Tested it on staging by adding something to the git config and then making sure that the "Cleared git config." is logged on both ubuntu and windows. 
I am also adding windows tasks to the patch associated with this PR.

DEVPROD-15806 Fix home directory not found on windows

---

db/db_utils.go

DEVPROD-16579
The previous upsert would do replace's if certain conditions were met. The fallback was added to ensure that the functionality stays the same, but we alert when it triggers. It never alerted (although many tests were using Upsert as replace) so this PR just removes the fallback.
I also removed some really old panics that never get triggered- we don't do these for Upsert, Update, etc either which have the same function signature.
Unit tests (and splunk query in ticket comments)

DEVPROD-16579 Remove Upsert query fallback

---

makefile
self-tests.yml

DEVPROD-16346
Dependabot doesn't work that well with internal repos (you have to add secrets and registry configuration), so we just decided to make evergreen-ci/test-selection-client a public repo. It contains no secrets so it should be fine.
* Dependabot version updates are working again.
* Existing tests compile.

DEVPROD-16346: remove configuration for internal repo as Go module

---

validator/distro_validator.go
validator/distro_validator_test.go

DEVPROD-13608
Add validation to make sure that distro aliases can't matches an existing ID and vice versa. 
Added unit tests

DEVPROD-13608 Add validation to make sure Distro Aliases and Distro Ids don't collide 

---

self-tests.yml

DEVPROD-16944
The MacOS notary service has strict limits on how many binaries can be notarized per day, but currently, Evergreen notarizes the client every time the `build-darwin_arm64` and `build-darwin_amd64` tasks run. To reduce unnecessary notarizations, don't allow patching the tasks that notarize the client. If someone wants to just compile the binary in MacOS for a patch, they can run the `build-darwin-unsigned_arm64` and `build-darwin-unsigned_amd64` tasks.
I'm going to make some follow-up changes to reduce our usage further and ensure the deploy process is still as smooth as possible.
N/A
N/A

DEVPROD-16944: do not allow notarizing MacOS clients in patches

---

model/project.go
model/task_lifecycle.go
model/task_lifecycle_test.go

DEVPROD-16656
we were previously ignoring bvtu stepback settings which was causing some teams' stepback:false to not exit stepbacks
unit test

DEVPROD-16656 Evaluate bvtu for stepback settings

---

config_cedar.go
db/cedar_db_utils.go
db/db_utils.go
environment.go
globals.go
mock/environment.go
service/templates/admin.html

DEVPROD-16904
Evergreen will need R/W ability directly to Cedar DB cluster once it assumes the responsibility of handling the test result service. Added this.
Hard coded a REST route to fetch some Cedar data and confirmed it worked. Will update admin settings accordingly in prod before merging if approved.

DEVPROD-16904 Add Cedar DB connection to Evergreen

---

self-tests.yml

DEVPROD-16944
To reduce the amount of times the Evergreen client gets notarized per day, we're going to stop notarizing/signing MacOS clients on every commit and instead notarize only once per day in the morning. This ensures that on the morning of the deploy, if there was any commit yesterday, it'll be ready to deploy.
It's still fine to deploy a commit that's not the cron-activated one. So if the deployer wants to deploy something other than the commit that ran the cron MacOS task, they can do it as long as they schedule/run the MacOS task on that commit before deploying to prod. https://github.com/10gen/kernel-tools/pull/462 adds a check to make sure the MacOS task is activated before deploying to prod and https://github.com/10gen/kernel-tools/pull/463 introduces a convenience to the …

DEVPROD-16944: activate MacOS client tasks in a cron

---

config.go
go.mod
go.sum

DEVPROD-16983
This commit updates our pail version to the latest in order to gain considerable performance improvements for s3.put

DEVPROD-16983: update to latest pail version

---

graphql/generated.go
graphql/models_gen.go
graphql/query_resolver.go
graphql/schema/types/waterfall.graphql
model/waterfall.go
model/waterfall_test.go

DEVPROD-16870
Add parameters that allows case sensitivity to be configurable in Waterfall pipelines.
By default, if no parameter is supplied, case sensitive will be enabled by default. This is a significantly faster query than case insensitive. 
This is for P3 ticket: [DEVPROD-16699](https://jira.mongodb.org/browse/DEVPROD-16699).
After building the new task index, the queries can actually finish now as opposed to never finishing after 5 minutes, but it's still slow. Making queries case sensitive can significantly improve query speed. For example, when I tested Max's query on production, execution could be as fast as <50ms.
- Added unit tests (also rewrote them into test case format because hard to read)

DEVPROD-16870: Make case sensitivity configurable in Waterfall aggregations

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_util.go
model/host/db.go
model/host/host.go
units/provisioning_create_host.go

DEVPROD-16710
Think of this as just a POC. There will be follow-up work to investigate how it behaves at scale + make it more resilient to problems.
We've been asked to start using elastic IP addresses from an IPAM pool (basically a pool of IP addresses owned by MongoDB) because AWS will start charging us for using IP addresses that they provide to us as a convenience via `AssociatePublicIpAddress`. To support elastic IPs, Evergreen's host lifecycle has to be modified significantly to both ensure that hosts get assigned elastic IPs _and_ that we clean up the elastic IPs properly. For now, I only wrote the logic to give a host an elastic IP, which isn't actually enough to enable the feature yet because those IPs have to be cleaned up. Later PRs will deal with the issue of cleaning them up …

DEVPROD-16710: acquire elastic IP addresses from IPAM for hosts

---

agent/command/s3_evergreen_credentials.go
agent/command/s3_evergreen_credentials_test.go
rest/route/agent.go
rest/route/agent_test.go

DEVPROD-17177
Some [tasks](https://parsley.mongodb.com/evergreen/mongodb_atlas_cli_master_code_health_compile_patch_487d0d2a201d4f35a266849641c3cf69ce7f175c_680a63903175fa0007637a23_25_04_24_16_15_26/0/task?bookmarks=0,57&shareLine=38) are encountering that the time format is not being parsed correctly when getting the expiration.
Add fail unit test

DEVPROD-17177 Format AssumeRole expiration with standard time format

---

docs/Project-Configuration/Evergreen-Data-for-Analytics.md
docs/Project-Configuration/Project-Commands.md
docs/Reference/Glossary.md

DEVPROD-17176
This adds some documentation to our requester types. This came up because a user thought a version/patch was a certain requester type, but it wasn't. Although it's accessible via our rest api, we don't really document what they mean (which is important for security for AssumeRole ExternalIDs)

DEVPROD-17176 Document requester types

---

cloud/cloud.go
cloud/cloud_host.go
cloud/docker.go
cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_util.go
cloud/mock.go
cloud/static.go
units/host_termination.go

DEVPROD-16713
Builds off of #8967. Again, this is more like a POC and I might significantly rewrite this if it doesn't work well in prod.
#8967 added logic to use an elastic IP from an IPAM pool when creating a task host. This one cleans up the elastic IP when the host is terminated. This cleanup is best-effort when the host terminates but it's inevitable that we'll leak some elastic IPs (notably can leak due to unavoidable races in the host lifecycle or if the host's network interface holds onto the address for too long). There will be a follow-up to add reaper-like behavior to detect and clean up idle elastic IPs.
* Clean up elastic IP for an EC2 task host if it has one.
* Clean up elastic IP if an intent host has one (i.e. it couldn't create the EC2 host but did still allocate an …

DEVPROD-16713: release elastic IP when host is terminated

---

go.mod
go.sum
model/version.go
thirdparty/github.go
thirdparty/github_test.go

DEVPROD-12908
This adds a weak pointer cache for thirdparty.GetCommitEvent
I deployed on staging and got some events, but we just don't see the load under the function like in prod (and it's difficult to simulate it)

DEVPROD-12908 Add weak cache for thirdparty.GetCommitEvent

---

graphql/task_resolver.go

DEVPROD-17238
This resolver keeps throwing Splunk errors but we don't log the actual error to Splunk so it's hard to figure out what's happening. This PR logs the error.

DEVPROD-17238: Log error in `Task.VersionMetadata` resolver

---

cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
cloud/ec2_util.go
cloud/otel.go
globals.go
units/provisioning_create_host.go

DEVPROD-16717
Add OTel tracing for elastic IP features so we can track how long the operations take.
Tested in staging to verify the spans appeared in the relevant Amboy jobs.

DEVPROD-16717: add OTel tracing for elastic IPs

---

cloud/sts.go
cloud/sts_test.go
config_bucket.go

DEVPROD-16259
I removed the user facing code (admin page, on our config structs) but there's this unused cache option that I also added. I don't forsee us using this cache- since it really only gets called by users `ec2.assume_role` and to cache it, the would need to set times that allow for it to be cached (e.g. if all their calls ask for credentials that expire in 1h, they can be cached since the minimum time the next credentials need to for is 1 hour).
We could cache ec2.assume_role by extending every request by ~10minutes, but I don't think it's needed right now.
Existing tests (removed old test)

DEVPROD-16259 Remove AssumeRole cache

---

agent/command/results_utils.go
config.go

DEVPROD-17327
We added a new agent route to send test results to the server in [DEVPROD-17019](https://jira.mongodb.org/browse/DEVPROD-17019). Using the Evergreen-native test results service is disabled but the flag is checked on the server side. A large test results payload will exceed the HTTP server's max request size limit causing the task to fail, even though it successfully uploads the test results to Cedar. This removes the call to the agent route in the test results command.
Staging.
N/A

DEVPROD-17327: do not send test results to server (yet)

---

cloud/cloud.go
cloud/cloud_host.go
cloud/docker.go
cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_util.go
cloud/mock.go
cloud/static.go
model/host/db.go
units/crons.go
units/crons_remote_fifteen_second.go
units/host_ip_association.go
units/provisioning_create_host.go

DEVPROD-17136
After looking at preliminary data in prod for elastic IPs, I can see that associating the allocated elastic IP with the host's network interface is slow and typically takes 15-30 seconds after the host has been requested. Basically all of this time is spent waiting on EC2 to get the host to the "running" state (which is a prerequisite in EC2 to associating the elastic IP). If associating the elastic IP takes a really long time, the host creation job will slow down and may increase the likelihood of leaking hosts during app server restarts (the host will leak if the host creation job doesn't get to updating the host in the DB). To work around this, I moved this step to a separate job.
* Move elastic IP association to separate job.
* Adjust retries on elastic IP operations to …

DEVPROD-17136: move elastic IP association to separate job

---

repotracker/wrappers.go
thirdparty/github.go
thirdparty/github_test.go
units/crons.go
units/crons_remote_five_minute.go

DEVPROD-17368
creates a cron job that logs the limit every 5 minutes on splunk 
logs properly on staging

DEVPROD-17368 Update github api limit logs

---

self-tests.yml

DEVPROD-5867
Our smoke tests upload as private but without signed visibility (meaning you can't view them without aws creds), our lint lots upload as public-read (but they probably don't need to be on the public internet).
Unit tests. Tested with changes in #8988 on staging and I was able to look at our smoke test logs!

DEVPROD-5867 Add signed visibility for self-tests log artifacts

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-13696 
attach.artifact supports optional. It is tested and used by users but it wasn't documented.

DEVPROD-13696 Document optional for attach.artifacts

---

model/lifecycle.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/version.go

DEVPROD-11837
Some queries were incorrectly using Author and not AuthorID. This adds coomments explaining that Author sometimes refers to the display name and fixes queries that were using it.  
Updated existing test.

DEVPROD-11837 Use AuthorID for queries 

---

rest/route/host_agent.go
rest/route/host_agent_test.go

DEVPROD-16914
there is a bug that a host is being assigned two tasks at the same time 
i theorize this is happening because of outdated host information before the task starts
the change simply gets an updated host from the db and checks for running tasks 
the ticket also mentions that there are a lot of tasks that have overlapping start and end times but I think this is because we actually clear the host before actually ending the tasks. We do this to prevent evergreen tasks from being in a weird state where they have been marked complete but the hosts still have this task assigned. 
I think a slight overlap could be a symptom of this

DEVPROD-16914 Get latest host information for next task

---

agent/command/git.go
agent/command/git_push.go
agent/internal/client/base_client.go
agent/internal/client/interface.go
agent/internal/client/mock.go
agent/task_context.go
rest/route/agent.go

DEVPROD-12545
Our `GET /task/{task_id}/patch` (formally `GET /task/{task_id}/git/patch`) allowed passing in a patch id to get it. This was used inside the commit queue to compile multiple patch files and their changes at once when we run the patch. Since it's been removed, this is dead code and allows this route to do more than it needs to do.
Unit tests

DEVPROD-12545 Remove patch ID parameter from agent route

---

agent/command/archive_util.go

DEVPROD-17532
This fixes an error message in tarball extraction for s3.get.

DEVPROD-17532 Fix error message for link name in tarball extraction for s3.get

---

config.go
operations/client.go

DEVPROD-17395
This adds a function that runs kanopy-oidc login in a way that does not require a browser. It ensures that the output from the kanopy-oidc command is displayed to the user in real-time while ensuring that when the kanopy-oidc command prints the JWT token it is captured but not printed. This is important so that we prevent leaking the token every time an evergreen command is run. 
In [DEVPROD-17396](https://jira.mongodb.org/browse/DEVPROD-17396), this will be added to the client so that it's automatically run for every CLI command that needs it. 
Tested locally.

DEVPROD-17395 Add a wrapper for kanopy-oidc that selectively displays output

---

rest/client/mock.go

DEVPROD-17544
The rest client mock was out of date and many methods were missing or inaccurate. This cleans it up to bring it back to a usable state. 
This does not impact any current tests as it's not currently used anywhere. I'm preparing it ahead of adding new functionality to the CLI that I will need the mock for.

DEVPROD-17544 Fix client mock

---

model/task/task.go

DEVPROD-13634
In this ticket, I was adding a new display task display name to the task struct. I noticed that we have some logic to backlink the display task id post-creation. This logic was added/intended when tasks that were display tasks could potentially not have the id (4 years ago)
This ticket adds a log were that backlink logic is to confirm my suspicions and I'll revisit the log next week to make sure it isn't hit and then remove the logic.
The reason I'm including this in my ticket, is if we do use it, I should be updating the backlink to include the display task name (and I want to add documentation why we do this backlink here still). I also made [follow up work](https://jira.mongodb.org/browse/DEVPROD-17527) to convert the DisplayTaskId from a pointer to value.

DEVPROD-13634 Add log when display task id is missing from task struct

---

agent/command/assume_ec2_role_test.go

DEVPROD-17212
This fixes an AssumeRole test that expects a string rather than time
Unit tests

DEVPROD-17212 Fix AssumeRole test expects string rather than time

---

cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_util.go
model/host/db.go
model/host/ip_address.go

DEVPROD-17313
Follow-up to #9003, which introduced a collection of pre-allocated IP addresses. This changes the elastic IP logic to use the `ip_addresses` collection of pre-allocated IPs to find a free IP address. This saves on making AWS API calls to the IPAM pool for every host created/terminated by making DB calls instead.
* Use collection of pre-allocated IP addresses to assign elastic IPs to hosts.
* Unset the host from the IP address when terminating it to let it be reused.
* Remove `DisassociateAddress` step from host termination - this is no longer necessary because unassigning the host from its IP address is sufficient to allow the address to be reused by a different host. It also saves API calls when terminating hosts.
I'm going to build indexes on `{"allocation_id": 1}` and …

DEVPROD-17313: use pre-allocated elastic IP addresses

---

config.go
globals.go
operations/client.go
operations/model.go
operations/model_test.go
rest/client/client.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go
rest/client/request.go

DEVPROD-17396
- Generate a JWT token if the service flag is on, if the user doesn't have an api key or if we get an unauthorized error when trying to retrieve the service flags.  
- Give users the option to opt out. This can be helpful if users want more time to get set up after we flip the flag. 
- If we have a token, send that along with requests (not yet implemented for the legacy client). 
Added tests and also tested this against the corp secure staging endpoint with `volume list` and no api key saved to my local evergreen file. 
I will make sure the use jwt tokens flag is disabled on prod before merging this.

DEVPROD-17396 Generate a jwt token and send it along with the request 

---

model/project_ref.go
model/project_ref_test.go
model/version_activation_test.go
repotracker/repotracker.go
units/version_activation_catchup.go

DEVPROD-17555
A user ran into an issue where a nightly build with a "0 0 * * *" wasn't activated as expected. After some investigation we discovered that the reason why that happened is because when we looked at the most recent version at midnight, it was set to activate midnight of the next day rather than that current midnight. The reason why that was set to the next midnight is because that version was created at 11:59, and 11:59 is within the 5 minute cron range window of the previous version that is already set to activate at midnight. This part is correct and we need to do that to avoid a race where two builds are activated instead of one. However, in this situation, at midnight when we pull the version to activate, we should consider this buffer and ignore any versions that came in …

DEVPROD-17555 Fix builds not activating when now is within 5 minutes of the previous version's activate_at

---

model/host/host.go
units/host_drawdown.go
units/host_drawdown_test.go

DEVPROD-17803 
We want to not drawdown if the host is currently tearing down a task and it has not yet exceeded the max time.

DEVPROD-17803 Fix task group task drawdown logic

---

rest/model/version.go

DEVPROD-17798
Confirmed that we don't populate this, or use it anywhere. 

DEVPROD-17798 remove unpopulated builds field from version rest route

---

model/patch/db.go

DEVPROD-12099
Refactors the query used by the patches page to first leverage the `branch_1_create_time_1_alias_1` index before applying the `requester` filter. The `requester` field is not stored directly on patch documents—it is computed dynamically. Previously, the query used `addFields` to compute `requester`, followed by a `$match` on `requester` and other fields. This resulted in a full collection scan, since none of the filtering could benefit from indexing. With this change, we first reduce the dataset by filtering on indexed fields, and only then apply additional filtering on the dynamically computed `requester`, if it was requested by the user.
Before:
https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/spruce/result/sK46TGDkjQQ/trace/5ef5erRBVGC?fields%5B%5D=s_nam …

DEVPROD-12099 Refactor patches page query to properly use index

---

graphql/generated.go
graphql/schema/types/task.graphql

DEVPROD-13868
Surface the failure_metadata_tag field via the graphql api
Adding a field and running codegen just exposes the field via graphql.

DEVPROD-13868 Surface FailureMetadataTags in GraphQL api

---

model/repo_ref.go
rest/route/user.go
rest/route/user_test.go

DEVPROD-16645
This fixes a bug where MANA could accidentally delete repo admin permissions via the `DELETE /rest/v2/users/{user_id}/permissions` route. Repo admins are maintained by the repo admin list because MANA doesn't support repo refs, but branch projects are maintained by MANA. When MANA ran the route, it would try removing roles related to a branch project, but the route would also delete any roles for the parent repo ref as well. Since repo admins are maintained by the admin list, MANA should not be modifying them in the route. To actually remove repo admin permissions, a user needs to remove themselves from the repo admin list.
* Fix delete user permissions route so it never deletes repo admin permissions.
This doesn't retroactively fix users who have already lost their repo …

DEVPROD-16645: do not delete repo admin permissions via route

---

model/user/db.go

DEVPROD-17737
This will reduce the uptick in user has no email address we've been seeing.

DEVPROD-17737 Do not try to set slack information for the Spiffe monitoring user

---

config_release_mode.go
model/distro/distro.go
model/distro/distro_test.go
rest/model/admin.go
service/templates/admin.html
testutil/config.go

DEVPROD-17116 
Added idle time override to release mode. 
Added a unit test and ensured this worked locally. 
Will add some process docs now that release mode is complete, and loop in Aldo and Mohamed.

DEVPROD-17116 add idle time override to release mode

---

config.go
model/patch/github.go
model/patch/patch.go
operations/patch_util.go
rest/model/patch.go
thirdparty/github.go
trigger/payloads_test.go

DEVPROD-16746 
I originally misunderstood this ticket by adding branch_name to the patch (although i think it's fine to have and we don't need to get rid of it, but i can if anyone disagrees). What server leadership wants is to know from what branch a PR or CLI patch was _created from_, so they can start to track how much work is done for each ticket or unit of work.
I will make a DPIPE ticket to expose both of these. 
Confirmed that a [CLI patch](https://spruce-staging.corp.mongodb.com/patch/682f94cd7b68bb00078fb961/configure/tasks) has this information under local_branch under git_info: 
and that head_branch is set for [PR patches](https://spruce-staging.corp.mongodb.com/version/682f95364aa7b80007950ea9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) under github_patch_data:

DEVPROD-16746 add local branch info to patches

---

graphql/generated.go
graphql/schema/types/distro.graphql
graphql/tests/mutation/saveDistro/data.json
graphql/tests/mutation/saveDistro/queries/insufficient_permissions.graphql
graphql/tests/mutation/saveDistro/queries/save.graphql
graphql/tests/mutation/saveDistro/queries/validation_error.graphql
rest/model/distro.go

DEVPROD-16863
Expose the provideraccount field to the graphql api so we can use expose it on the UI.

DEVPROD-16863 Expose ProviderAccount field via graphql api

---

rest/route/github.go

DEVPROD-10172
This adds a log when we no-op for a PR when there isn't a project ref with testing enabled found.

DEVPROD-10172 Log when a pr is not attached to a project ref with testing enabled

---

docs/API/REST-V1-Usage.md
docs/API/REST-V2-Usage.mdx
docs/CLI.md
docs/FAQ/Dynamic-Github-Tokens-FAQ.md
docs/FAQ/General-FAQ.md
docs/FAQ/README.md
docs/FAQ/Static-Token-Deprecation-FAQ.md

DEVPROD-17408
I originally planned to break this up more, but that would make linking complicated, so I decided to put it all into one big PR. 
I broke up the FAQ into a few different documents, but most of it is just being moved. I'lll comment on those docs to make reviewing easier, because they can be skipped as there are no changes to the content. 
The feature flag will need to be flipped before we attempt to generate tokens in the CLI. However, I don't want to start doing that before sending an email so that users are don't get confused when they are all of a sudden prompted to click a link to authenticate. I need to link this documentation in that email, so we have a bit of a chicken and egg problem. There therefore might be a small window of time in which a user finds this …

DEVPROD-17408 Add documentation for static credentials deprecation

---

agent/util/subtree_linux_test.go
agent/util/subtree_unix_test.go
config_cloud.go

DEVPROD-13311
This test will never pass on MacOS because the more recent MacOS hosts don't support Evergreen's current process cleanup method. For MacOS/Linux, Evergreen looks for special env vars to find child processes' PIDs and cleaning them up. Since MacOS changed what processes are visible via `ps`, MacOS process cleanup doesn't really work anymore and needs to be implemented differently. More context is in DEVPROD-6539.
This env var-detecting logic will need to be replaced in DEVPROD-10457 with a different process sandboxing methodology, so this test is not useful for MacOS anymore.
Ran MacOS tests and it no longer runs this test.

DEVPROD-13311: do not run env var process cleanup test on MacOS

---

model/taskstats/stats.go
model/taskstats/stats_test.go

DEVPROD-17893
We caught up on task-stats and then began failing again once we got to the 24 hour amount of updating; I think we'll keep failing until we get three days out and start doing 12 hour updates again. Given this, I propose we just switch to 12 hour updates completely, since it hasn't been an issue. 
Fixed tests.

DEVPROD-17893 remove one-day update from task stats

---

scripts/prepare-swagger-push.sh

DEVPROD-15330
It looks like Evergreen creates an empty file when s3.get fails https://github.com/evergreen-ci/evergreen/blob/d03d37ed2d43602506e276059634c580f3d5e46e/agent/command/s3_get.go#L317. I opened https://jira.mongodb.org/browse/DEVPROD-18161 for this.
I tested the script change locally, but this is difficult to test without a commit. I set the xtrace in to investigate further if needed.
N/A

DEVPROD-15330 Handle empty vars in swaggo file

---

rest/route/patch.go
rest/route/patch_test.go

DEVPROD-18277
The type of time format we use for `start_at` is a bit weird, it **requires** quotes. We have a helper func to account for this for user-inputted values, but we don't use it for `start_at`.
I added new unit tests to make sure it works with and without quotes. I ran the new tests without the changes, and they fail.

DEVPROD-18277 Handle parsing start_at with or without quotes

---

agent/agent.go
agent/agent_test.go
agent/command/results_utils.go
agent/internal/task_config.go
config.go
globals.go
model/task_lifecycle.go

DEVPROD-12889
Traces currently don't show any failure when a test fails or no test results are posted (with `must_have_test_results: true`) because [those checks have historically been done in the app server when the task is ending](https://github.com/evergreen-ci/evergreen/blob/8a967916c296fdec9128462aefb6ba65cf646888/model/task_lifecycle.go#L778-L795). I opted to move test results checks into the agent so that the traces can display any test results-related failure.
The agents all have to roll over to the new version before the old checks can be removed. I'll post a follow-up PR once the agents have rolled over.
* Move test results missing/failed checks into the agent.
* Add temporary log to double-check that the app server logic is not used anymore.
* Add failing command and …

DEVPROD-12889: move test results check into the agent

---

docs/Project-Configuration/Project-Commands.md

Supports DEVPROD-18242
Update docs for `assume_roles` command to indicate that project ID is now visible on a project's settings page. Also update the formatting a bit.
[Pine patch](https://spruce.mongodb.com/version/6852cc3b4989a5000773f405/downstream-projects?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

DOCS: DEVPROD-18242 Update assume_role docs with project ID

---

model/distro/distro.go
rest/model/distro.go
rest/model/distro_test.go
rest/route/distro_test.go

DEVPROD-7920
Follow-up to #9125 - some distros can't have their max hosts adjusted (e.g. perf distros) while others can, so I made a flag to choose whether to allow a particular distro to have its max hosts automatically adjusted. The flag is going to be used in a follow-up PR.
I opened a UI ticket (DEVPROD-18438) to add this flag.

DEVPROD-7920: add distro flag to allow auto-tuning distro max hosts

---

rest/route/task_restart.go

DEVPROD-11839
Tasks using this route would end up having their `activated_by` field set to the user's display name rather than ID, and a surprising amount of human users use this route (300k / month).
Existing tests

DEVPROD-11839 Use userID when restarting tasks via API

---

units/provisioning_create_host.go

DEVPROD-14904
If a non-insufficient capacity error is encountered in the host creation job, there is no need to keep retrying the same job in different subnets.
Existing tests

DEVPROD-14904 Do not retry host creation on non-insuff capacity error

---

graphql/generated.go
graphql/schema/types/distro.graphql
graphql/tests/query/distro/queries/distro.graphql
graphql/tests/query/distro/results.json

DEVPROD-18438
Expose `autoTuneMaximumHosts` field for use in frontend

DEVPROD-18438: Expose `autoTuneMaximumHosts` field from GraphQL API

---

docs/Project-Configuration/Project-Commands.md

DEVPROD-18209
Users wanted some feedback (UI or logs) from generate.tasks about what it generated. This could already be done using `s3.put`

DEVPROD-18209 Document s3.put can be used to debug generate.tasks

---

graphql/generated.go
graphql/models_gen.go
graphql/schema/types/mainline_commits.graphql
graphql/schema/types/version.graphql
graphql/tests/version/taskCount/data.json
graphql/tests/version/taskCount/queries/task_count_default.graphql
graphql/tests/version/taskCount/queries/task_count_include_never_activated_tasks_false.graphql
graphql/tests/version/taskCount/queries/task_count_include_never_activated_tasks_true.graphql
graphql/tests/version/taskCount/results.json
graphql/util.go
graphql/version_resolver.go

DEVPROD-18478 
Usually whether we surface an inactive task depends on the versions requester. This PR updates it so it can be toggleable by a query parameter. This also extends other related fields so they return the same set of tasks and counts.
Before:
After:

DEVPROD-18478 Surface inactive tasks consistently across graphql resolvers

---

units/distro_auto_tune.go

DEVPROD-7920
Add logging so we can debug the distro auto-tuning if needed. I assume the numbers/general heuristics that I used for auto-tuning distro max hosts will probably will have to be tweaked eventually. This log helps figure out what the host stats looks like for that distro, so it's easier to see what data made it choose to increase/decrease/not change distro max hosts.
Checked the logged looked as expected in staging.

DEVPROD-7920: log distro auto tune debug info

---

rest/route/github.go

DEVPROD-18856: Create patches for github automatic_base_change_succeeded events
When a PR has a base branch of another branch, and that target branch is merged into main, github sends an `automatic_base_change_succeeded` event which should be sufficient notice to start a new patch
This is my first PR against evergreen. Wanted to sanity check this is a reasonable path before I write test

DEVPROD-18856: Create patches for github automatic_base_change_succeeded events

---

model/task/test_result.go

DEVPROD-16201
The request to get test results from cedar automatically includes the "base tasks" (the most recent mainline tasks) in the payload.
It could be possible to have a less common case where the base tasks are actually _newer_ than the actual tasks and ran post-deploy of switching new tasks to the Evergreen test result service, the request to Cedar will not be able to retrieve test results for those base tasks. This PR fixes this
Repro in staging and confirmed it went away.

DEVPROD-16201 Omit base tasks in Cedar request if base tasks wrote from Evergreen

---

agent/agent.go
agent/command/perf_send.go
agent/command/results_utils.go
agent/command/results_utils_test.go
agent/command/results_xunit_parser.go
agent/command/results_xunit_test.go
agent/internal/client/base_client.go
agent/internal/client/interface.go
agent/internal/client/mock.go
agent/internal/task_config.go
agent/internal/testutil/task_output.go
agent/logging.go
config.go
config_db.go
config_test/evg_settings.yml
go.mod
model/task/evergreen_service_test.go
model/task/local_service_test.go
model/task/task_output.go
model/task/test_result.go
rest/model/admin.go
rest/route/agent.go
rest/route/service.go
service/rest_task_test.go
testutil/config.go
trigger/task_test.go

DEVPROD-16202
Removes cedar from the agent. A follow up PR will be made to remove cedar-specific agent routes post deploy.
Existing tests

DEVPROD-16202 Remove cedar from Evergreen agent

---

scheduler/utilization_based_host_allocator.go

DEVPROD-18957
The distro auto-tuning logic is enabled, but I'm gonna spend a few weeks keeping an eye on it to see if any issues arise. Going to remove this log once that monitoring period is over, so I switched out the ticket number.

DEVPROD-18957: switch ticket number

---

model/distro/db.go
units/distro_auto_tune.go
units/distro_auto_tune_test.go

DEVPROD-19101
Distro auto-tuning works best on distros that are regularly used so that they have more predictable patterns of usage. Single host distros aren't regularly used since they're only for releases, so the auto-tuning won't be able to adjust distro max hosts very accurately. Because they're so niche, I don't think it makes sense to let them be auto-tuned.
* Do not allow auto-tuning for single task distros.

DEVPROD-19101: ignore single task distros for auto-tuning

---

docs/Project-Configuration/Project-Configuration-Files.md

DEVPROD-18172
Add some information on the ${github_commit} expansion. 
yes

DEVPROD-18172 Update docs to explain how ${github_commit} is set

---

units/provisioning_create_host.go

DEVPROD-18627
Places a conservative 30 minute limit on the job since they occasionally run for a long time
Existing tests

DEVPROD-18627 Add max time to create host job

---

rest/route/service.go

DEVPROD-15741
Remove edit permission for viewing a distro. This matches the current behavior for viewing all distros, so I believe this was an oversight, not a deliberate requirement.
N/A
Covered by existing API docs.

DEVPROD-15741 Don't require edit permissions to view distro

---

model/generate.go

DEVPROD-18267
Before merging https://github.com/evergreen-ci/evergreen/pull/9216/files, gut check that generating doesn't depend on this behavior or something, in which case we should maybe just comment why we don't check it here, instead of adding it.

DEVPROD-18267 log if buildvariant activate is set

---

model/project_vars.go
rest/route/project_copy_test.go

DEVPROD-19717
copy var routes were erroring because it was trying to add to a null object 
this initializes them if we are making edits to the null maps 
unit testing

DEVPROD-19717 Allow private and admin vars to be copied correctly

---

docs/Project-Configuration/Project-Configuration-Files.md
util/expansion.go
util/expansion_test.go

DEVPROD-19402
This PR introduces a new expansion resolution capability, to provide a default when the expansion is _either_ undefined **or** an empty string.
The rewritten test file showcases this really well, but a TLDR is this allows prepending a `!` to allow a check for the expansion to not be empty.
Unit tests
I did a grep of all configs to make sure no one is using a variable or expansion ending in `!`, as this would break it. I did `\$\{.*\|.*\}` as an initial grep to get all the expansion usage (17k results). I then did `\$\{.*!\|.*\}` which adds `!` right before `|` this returned 0 results

DEVPROD-19402 Add required expansions for expansion resolutions

---

model/lifecycle.go

DEVPROD-18860
This adds the git tag requester as the activator when none is found.

DEVPROD-18860 Use git tag requester as activator when none is found

---

agent/command/papertrail_trace.go
config.go

DEVPROD-18860
The papertrail service expects something in the submitter field, this ensures it fallsback to something always.

DEVPROD-18860 Fallback Submitter on papertrail trace command

---

docs/FAQ/General-FAQ.md

[Slack thread](https://mongodb.slack.com/archives/C0V896UV8/p1753982064579449)
The command assumes the Evergreen project's target branch is called `main` but the branch name it uses is whichever branch the project is tracking.

docs: fix manual patch merge-base

---

cmd/evergreen/evergreen.go
config.go
operations/flags.go
operations/last_revision.go
operations/last_revision_test.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go

DEVPROD-19992
DEVPROD-19999
The S&amp;I team wants the main functionality of [the git-co-evg-base CLI](https://github.com/evergreen-ci/git-co-evg-base) to be absorbed into the Evergreen CLI so they can deprecate the tool. Info on how it's used is [here](https://evergreen-ci.github.io/git-co-evg-base/concepts/criteria/).
I decided that the existing `evergreen last-green` command was too limited/specific to be able to handle all the functionality that git-co-evg-base has, so I made a separate `evergreen last-revision` command to generalize/extend it. Most of this change is to port over `evergreen last-green`'s functionality into the new command in a way that's more extensible (like [how git-co-evg-base does it](https://github.com/evergreen-ci/git-co-evg-base/blob/da1912185c0d974aaf690fcc19a7 …

DEVPROD-19992, DEVPROD-19999: set up basic last-revision command

---

docs/Project-Configuration/Task-Priority.md
model/project_parser.go
model/project_parser_test.go
scripts/setup-credentials.sh
validator/project_validator.go

DEVPROD-17670
People have been abusing this feature by setting 100k+ priority, so enforcing a maximum level of 50 when set via config. Implemented a silent fallback so as not to break anyone's build who is currently doing this.
Updated docs. Will also send out some comms on approval.

DEVPROD-17670 Cap the max priority that can be set in YAML

---

docs/Project-Configuration/Task-Priority.md
model/project_parser.go
model/project_parser_test.go
validator/project_validator.go

DEVPROD-17670
Caps YAML priority at 50 to prevent users from setting it to 10k+.
Prior validation warnings were set at the warning level with the intent to not break user builds. However there are users with large YAML priorities that also are set to fail on any warnings, so using warning level validations was breaking. This is the same PR with the validation level downgraded to `notice`
Tested in staging. Will be sending out the following email to devprod-announce so please LGTM this as part of review too:
```
[Evergreen] New restrictions on setting task priority via the project yaml
Hi all,
The priority setting in project YAML is now capped at 50. Any values above 50 will be automatically adjusted down to this new maximum. 
This change has been done to ensure responsible use of the …
```

DEVPROD-17670 Cap max priority set in YAML

---

docs/Project-Configuration/Controlling-when-tasks-run.md

DEVPROD-20513
This came up in a user question so adding it to be more explicit

DEVPROD-20513 Add docs explaining that tasks run by default on the waterfall

---

model/project_ref.go
model/project_test.go
rest/route/project.go

DEVPROD-20309
add filtering to the projects route to allow this to be used for validating project limits. Kept this a quick-win, just added as params.
Added tests, verified this works in local with http://localhost:9090/rest/v2/projects?owner_name=evergreen-ci&repo_name=evergreen
Swaggo updated.

DEVPROD-20309 add owner/repo filtering to the /projects route

---

config.go
operations/last_revision.go
operations/last_revision_test.go

DEVPROD-20067
git-co-evg-base has [an option to specify a minimum % of activated tasks](https://evergreen-ci.github.io/git-co-evg-base/concepts/criteria/#run-threshold), which is used to find builds have run a sizeable portion of their tasks before choosing it as a base revision. I slightly modified the semantics to instead have an option for the minimum % of finished tasks because the git-co-evg-base implementation includes running tasks, which probably aren't useful for users.
* Tested manually to verify that it could find a build variant with a sufficient % of tasks finished.
Added docs to CLI usage.

DEVPROD-20067: support option for minimum finished tasks threshold in last-revision

---

config_bucket.go
config_test.go
model/task/task.go
model/task/task_output.go

DEVPROD-20127
This starts using the correct bucket based on the admin list of projects. If a project is in the list, it will use the long retention bucket. 
Tested this on staging to make sure that it reads and writes from the correct bucket for [this task.](https://spruce-staging.corp.mongodb.com/task/minna_test_ubuntu2004_validate_commit_message_patch_dc197c1838b80e0d73a2037675b4a33d3b8f7f55_689a324769332e0007afaacf_25_08_11_18_11_29/logs?execution=0). I also added a unit test.

DEVPROD-20127  Start using the long retention s3 bucket for the specified lists of projects 

---

config.go

DEVPROD-20862
because we are recursively going through every item in settings, having 1 context might not be long enough for all the DB operations it goes through

DEVPROD-20862 Pass in a new context for each parameter store operation

---

config.go
operations/last_revision.go

DEVPROD-19997
* Add option for maximum timeout on last-revision before giving up.
* Slightly refactor the CLI input validation checks so they're in the CLI before funcs.
* Tested manually to verify that it respected the timeout.
* Tested input validations manually.
Updated CLI usage docs.

DEVPROD-19997: add option to configure timeout for last-revision

---

model/task/task_log.go
model/task/test_log.go

DEVPROD-20809
We recently moved some projects over to the long retention bucket. The files are already copied over and we plan to change the default bucket to a shorter retention. However, the existing logs still have the old bucket stored in their metadata. This adds a workaround for it that we can delete after one year from today. 
I tested this on staging with [this task.](https://spruce-staging.corp.mongodb.com/task/minna_test_ubuntu2004_validate_commit_message_patch_dc197c1838b80e0d73a2037675b4a33d3b8f7f55_689aa9a5ef8f1d0007608cc5_25_08_12_02_40_54/logs?execution=0). The task has the old default bucket saved in task output. I deleted the logs from that bucket and they are now only in the long retention bucket. If I try to load the logs, it shows "no logs found". With these changes, …

DEVPROD-20809 Change where the task log bucket is read from

---

agent/command/s3_put.go
agent/command/s3_put_test.go
config.go

DEVPROD-20997
To improve flexibility with security of s3.put, this allows expansions in the permissions parameter.
Deployed to staging, before deploying I get:
```
creating cli patch: Unexpected reply from server (500 Internal Server Error): 400 (Bad Request): error processing patch: invalid patched project config: invalid patched config syntax: post section in 's3.put' command: parsing parameters for command 's3.put' ('Upload smoke test's app server logs to S3') (step 2 of 3): invalid permissions '${some_exp|private}'
```
After deploying, the same config works

DEVPROD-20997 Allow expansions for s3.put permissions parameter

---

model/project_test.go

This pull request adds new test cases to the `TestBuildVariantPathsMatchAny` function in `model/project_test.go` to improve coverage of path matching logic, especially around combinations of ignored and included directories and files.
Path matching test improvements:
* Added a test to ensure that if a parent directory is ignored but a child directory is specifically included, files in the child directory are matched.
* Added a test to verify that if a parent directory is included but a child directory is ignored, files in the child directory are not matched.
* Added a test to confirm that if a parent directory is included, a child directory is ignored, but a specific file in the child directory is re-included, that file is matched.
Remember to add or edit docs in the docs/ directory if …

DEVPROD-19659: Add more unit tests for path filtering

---

config.go

DEVPROD-20862
we shouldn't spam splunk every time there's a context cancellation

DEVPROD-20862 Don't grip for context cancelled

---

config.go
operations/last_revision.go
operations/last_revision_test.go

DEVPROD-20001
Follow-up to #9313 - the CLI can save last-revision criteria to the user's personal Evergreen YAML config, so this adds support to reuse that saved criteria when running the last-revision command.
* Added unit test for finding criteria to reuse from config.
* Manually tested to verify that it could load last-revision criteria from the config file and checked all criteria to pass.
Updated CLI usage docs.

DEVPROD-20001: add option to reuse criteria in last-revision

---

model/event/subscribers.go
units/patch_intent.go

DEVPROD-19924
This adds child patches to merge queue. This isn't feature-complete, and users aren't able to add these via the UI yet. As well, tests will be added in [DEVPROD-19925](https://jira.mongodb.org/browse/DEVPROD-19925).
Manual testing on staging.
I deployed these changes, added the mq patch alias to my project config, and it successfully created the child patch and waited for it to complete before actually passing the merge queue. [This was the patch](https://spruce-staging.corp.mongodb.com/version/68a609446e362d000774a91a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) for reference.
Documentation will also be done in a future ticket when this feature is exposed to users.

DEVPROD-19924 Add child patches to merge queue

---

agent/otel.go
config.go

[DEVPROD-21298](https://jira.mongodb.org/browse/DEVPROD-21298)
This adds some more disk metrics to honeycomb!
Deploy to staging, run a [task](https://spruce-staging.corp.mongodb.com/task/zackary_bisect_pass_passtest_patch_faa32cbeb73b5b0b298aa5b1155e85d0621722b2_68add30c5117dd0007e275ab_25_08_26_15_30_31/logs?execution=0), got these [system metrics](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen/result/zZ8G2rQ5e4K?expd_asc=true&expd_col=_hny.ts&expd_fwd=false&expd_id=pd1KgfNzTXF&expd_page=25&tab=explore).

DEVPROD-21298 Add disk usage/available/utilization metrics to honeycomb

---

graphql/schema/types/adminSettings/other.graphql

[DEVPROD-22200](https://jira.mongodb.org/browse/DEVPROD-22200)
Add the bucket type to the bucket config for admin settings

DEVPROD-22200: Add type to bucket config

---

repotracker/repotracker.go

DEVPROD-22453
I suspect the issue is creationInfo is too large. Adding more verbose logs to analyze it better.

DEVPROD-22453 Add build creation info logs to repotracker

---

model/project.go
repotracker/repotracker.go

DEVPROD-22453
Add more log verbosity because the taskIds field is not logging in splunk and is a potential culprit.

DEVPROD-22453 Increase task ID log verbosity

---

model/lifecycle.go
repotracker/repotracker.go

DEVPROD-22453
creationInfo is causing logs to not show up in splunk so removing it to better see where things get stuck.

DEVPROD-22453 Remove creationInfo from debug logs

---

repotracker/repotracker.go

DEVPROD-22453
Kanopy alerted us that we're logging too much with these new changes so restricting logs to only look at the problematic SHA and project.

DEVPROD-22453 Cut down on log volume

---

model/generate.go
model/lifecycle.go
model/project.go
model/project_test.go
repotracker/repotracker.go

DEVPROD-22453
After a very deep dive and scattering gazillions of debug logs across prod....
[Here](https://github.com/mongodb/ai-assistant/blob/cfd3d50f0a910cb1caa8c2b6b498e6c44ccb03e1/.evg.yml) is the user's problematic YAML.
`DeployTaskGroup` is a single host task group which automatically computes dependencies in a linear direction. so lint-kube-ci -> test-all -> build-push is the dependency chain that gets computed since that's the order they were defined in
Separately, the `lint-kube-ci` is defined to depend on `test-all`. So now we have a cyclical dependency where `lint-kube-ci` and `test-all` depend on each other. We typically try to catch cyclical dependency errors in validation but this special case was missed, which is a bug.
This explains the OOM issues the evergreen app has …

DEVPROD-22453 Include SHTG dependencies when checking for cycles

---

model/generate.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/project_ref.go
model/task_creation.go

DEVPROD-22498
Follow-up to #9413, which added the CLI options so users could pick BVs/tasks on which to use test selection in CLI patches. This adds the logic so that given the user's regex variants/tasks where they'd like to enable test selection, Evergreen will create tasks with the `TestSelectionEnabled` bool set. That allows the task to use the `test_selection.get` project command. If the patch is reconfigured or tasks are generated, the new tasks are evaluated to determine which ones have test selection enabled.
* Tested in staging for:
* Task names, display task names, and task group names can match.
* User can specify just variants (i.e. use test selection in all tasks in the variant) or just tasks to match (i.e. match a task in any variant).
* Generated tasks …

DEVPROD-22498: determine if test selection enabled for tasks

---

agent/internal/task_config.go
config.go
globals.go

DEVPROD-22707
Save `Task.ActivatedAt` time to a task's Honeycomb trace. Along with the trace's start timestamp and its duration, we can calculate the wait time, run time, and total time taken by a task.
Use RFC3339 format [as expected by Honeycomb](https://docs.honeycomb.io/reference/calculated-field-formula/operators-functions/time/)
`evergreen.task.activated_time` is visible in [this](https://ui.honeycomb.io/mongodb-4b/environments/staging/datasets/evergreen-agent/trace/yFCd8j5PTB2?fields[]=s_name&fields[]=s_serviceName&span=6895cd2cdd4c5595) trace from staging

DEVPROD-22707: Add task activated time to honeycomb

---

cloud/cloud.go
cloud/cloud_host.go
cloud/docker.go
cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_test.go
cloud/mock.go
cloud/static.go

DEVPROD-17417
Adds `RebootInstance` method to be used with spawn hosts. To keep this PR small, I'm only adding the function definition; next PR will contain amboy job and GraphQL changes.
The only thing I'm unsure about is how this method interacts with sleep schedules. Let me know if I made a mistake somewhere!
On staging, I rebooted my host and checked the logs:
The timestamp of the reboot job matched when I clicked the reboot button.
Chaya also helped me confirm via the events in AWS CloudTrail.

DEVPROD-17417: Add `RebootInstance` method to cloud manager

---

agent/command/test_selection_get.go
config.go

DEVPROD-22725
Move logs for `test_selection.get` from execution to task logs. This is more convenient for users because task logs are meant for info relevant to what the task commands do.
Tested in staging to verify the logs were moved to task logs.

DEVPROD-22725: move test_selection.get logs to task logs

---

units/patch_intent.go
units/patch_intent_test.go
units/schedule_patch.go

DEVPROD-17412
Right now, a user can bypass the submit patches permission for a project by specifying it as a child patch on another project. This PR introduces a permission check to fix this security issue.
Unit tests and tested in staging.

DEVPROD-17412 Check if user has submit patch auth for child patches

---

config.go
operations/model.go
operations/model_test.go

DEVPROD-18815
Sometimes the CLI version has a suffix, e.g. 2025-07-12b. This new change allows the minimum CLI version check to parse those strings correctly.
Unit tests

DEVPROD-18815 Support suffixed strings in CLI version check
