evergreen-ci/evergreen

cli/update.go

My binary name was evergreen-patch and I was littlebit confused what exactly it was asking me to upgrade when it told me to run "evergreen get-update" as I had no "evergreen" binary :)

Use the name of the executed binary in the warning message

---

public/static/js/settings.js

It is very useful to have Evergreen at least being able to report times in time
zones where we have employees, and both the UK and Dublin were missing.
Although they historically did not keep the same time, they do now, so putting
them both under Europe/London works.

EVG-1656 Add time zone entry for United Kingdom and Ireland

---

agent/background.go
rest/client/sender.go
rest/client/sender_test.go

- Stop flush from updating the last message time.
- Update the idleTimeoutInterval before resetting the timer.

EVG-2074 Fix idle timeout

---

public/static/js/mci_module.js

Reference: https://stackoverflow.com/questions/41211875/angularjs-1-6-0-latest-now-routes-not-working

EVG-2134 revert to <1.6.0 angular location hash settings

---

model/host/db.go
model/host/host.go
model/host/host_test.go
public/static/js/hosts.js
service/models.go
service/templates/hosts.html

The 2 changes are:
- Instead of running 1 db query per host that's running a task to get the task data, get all of it in 1 aggregation
- Stop filtering hosts as you type and instead filter once you hit enter

EVG-2091 improve performance of hosts page

---

config.go
model/task/db.go
scheduler/runner.go
scheduler/task_finder.go
scheduler/task_finder_test.go

I was curious about the performance of this operation, and so wanted
to see what the impacts/factors were, and then I accidentally wrote
two application-level implementations, with some interesting results: 
The test suite reports on the relative runtimes (as in [this
run](https://evergreen.mongodb.com/task/mci_ubuntu1604_test_scheduler_patch_b7f54713a78a6484aa3d025f11876c11b876ff20_59eaaa042a60ed09f70096aa_17_10_21_01_59_50)),
e.g: 
=== RUN   TestCompareTaskRunnersWithFuzzyTasks
[test.scheduler] 2017/10/21 02:03:19 [p=notice]: [alternative='6.559450433s' legacy='14.361323113s' length='243488' parallel='7.093386369s' pipeline='23.457452001s']
[test.scheduler] 2017/10/21 02:03:22 [p=notice]: [alternative='4.936629ms' legacy='5.982618ms' length='459' parallel='3.552666ms' …

EVG-1726: add task finder feature flag, alternate implementations

---

config.go
glide.lock
glide.yaml
vendor/github.com/mongodb/grip/send/buffered.go
vendor/github.com/mongodb/grip/send/multi.go
vendor/github.com/mongodb/grip/send/multi_test.go
vendor/github.com/mongodb/grip/send/slack.go
vendor/github.com/mongodb/grip/send/slack_test.go

This commit has two main aspects, first it updates grip to have more
well-formed messages slack messages, without dupication and better
metadata. 
Second, it removes buffering of messages for the slack logger. This is
important because buffering was causing messages to get batched
together, which made it difficult to filter only the high priority levels.
As an aside this will return to our earlier practice of logging debug
messages to splunk, which was a regression introduced with the earlier
slack change.

EVG-2273: update slack logging

---

hostinit/setup.go

Side note, RemoteCommand should probably grip stdout/stderr when the command fails.

EVG-2266 Evergreen spawned host failed to load task artifacts

---

rest/route/github_test.go
self-tests.yml

'*-with-mongodb' needed because environment config sets up amboy queues and requires the database.

EVG-2244 Fix race-rest-route test

---

db/lock.go
repotracker/runner.go

This builds heavily on top of the pending PR #423, which accounts for
much of its noise, if you can just look at the changes in the second
commit that might be useful. 
For some time now the only DB lock is used by the repotracker and its
not a global lock (indeed it only prevents multiple runs of the
repotracker from occuring at the same time.) While that's not possible
within a single binary given the current mode of operation, it might
be possible if there were two runner intances at a time, so it makes
sense to leave this around for now. 
This PR just clarifies the code to match the current state of
reality.

EVG-90: remove global lock

---

command/shell_test.go

extended sleep duration to 60 seconds; grip's collect all processes on OS X take ~30-40 seconds

EVG-2362 Fix test-command on OS X

---

model/task/task.go
model/task_history.go
model/task_history_test.go
model/testresult/testresult.go
service/rest_task_history.go

Running the timing comparison test, the new (non-aggregation) query is significantly slower than the old (aggregation) query, but it handles large test results that could potentially error the old one. Let me know if you think we need to rethink the approach

EVG-2057 rewrite of test history query

---

model/patch/cli_intent.go
model/patch/cli_intent_test.go
model/patch/github.go
model/patch/github_test.go
model/patch/patch.go
rest/model/patch.go
rest/model/patch_test.go

Per discussion with @tychoish, APIPatch has been extended to include Alias, as well as the underlying patch data.

EVG-2408 Extend Rest v2 API to include patch alias

---

public/static/js/projects.js
rest/data/repotracker.go
service/project.go
service/templates/projects.html

Implemented as a checkbox in the ui admin page. It only shows up when the webhook is setup and the repository is setup to track push events.

EVG-2499 Add button to project admin page to trigger "catchup run"

---

model/patch_lifecycle.go

Original bug was from leaving the "caller" param empty, not from using the CancelPatch function. Tested in staging.

EVG-2586 Fix patch cancellation

---

cloud/ec2.go
cloud/ec2_cost_test.go
cloud/ec2_integration_test.go
cloud/ec2_test.go
cloud/ec2_util.go
model/task_history_test.go
model/task_queue.go
self-tests.yml
service/project.go

This commit
1. Fixes outstanding lint errors
2. Removes cloud from the race detector. It does not spawn goroutines and has never tripped the race detector, and since it uses a global price manager, running the tests in a loop in Evergreen fails for a handful of tests. Furthermore, it spawns real instances, so we should not run the cloud tests in a loop.
3. Removes dead code from the cloud package.

EVG-2416 Remove dead code, don't test cloud on race detector

---

model/version/version.go
model/version/version_test.go
scripts/indexes.js
self-tests.yml

I haven't written any code to find duplicate tasks/builds since we must have duplicate versions in order to have duplicate tasks and builds. This is done in lieu of EVG-2468

EVG-2735 Add Pipeline for detecting duplicate Versions

---

model/project.go
model/project_test.go
service/patch.go

This brings partial support of display tasks to patch aliases. EVG-2722 has been created to track the remaining issues in display tasks.

EVG-2601 Patch alias does not support display tasks

---

operations/model.go

As the command continues past this warning, it should be on stderr, not stdout

EVG-2748 Print new version message on stderr

---

command/git.go
command/git_patch_test.go
command/git_test.go
command/testdata/test.diff
command/testdata/test.patch

Concerns:
1. Submodules. I recall a Cloud project that applied a diff that included changes to a submodule. I imagine this might break that.
2. I've omitted --whitespace=fix from the mailbox style patch apply since this only affects Github PRs. CLI patches will remain unaffected. 
Notes:
--binary is implied for git-am. There is no equivalent of --index for git-am.

EVG-2734 Evergreen cannot apply mailbox-style patches which create new files, and moves them in a later commit

---

makefile
operations/service_deploy_smoke_utils.go

See https://github.com/richardsamuels/evg-lint/ for docs
Here is a patch:
https://evergreen.mongodb.com/version/5a8492602fbabe2af3000af5
The two failing lint tasks will be fixed by John later this sprint.

EVG-2705 Custom Evergreen linter

---

repotracker/github_poller.go

Although the recent date change works fine for our squash-and-merge based workflow, it leads to out-of-sequence dates for versions in mongodb master. Here's a screenshot of commits made today:
We'd expect these all to have todays date, corresponding to the push to master, but actually have the commit date.

EVG-2793 Dates are wrong/out-of-sequence

---

monitor/host_monitoring.go

I believe line 89 of host_monitoring.go blocked because the channel was full, because the readers of the channel (line 63) all returned due to the context being canceled, but the channel was still open

EVG-2779 close host monitoring channel when canceling

---

public/static/plugins/perf/js/perf.js
public/static/plugins/perf/js/trend_chart.js
service/templates/task_perf_data.html

EVG-2609: fixed precision on labels for numbers less than 1.
It seems to work on chromium / firefox / safari and Edge. Evergreen doesn't seem to work on explorer.

EVG-2438: add toolbar for origin / zoom and linear / log modes.

---

config.go
environment.go
environment_test.go
globals.go
migrations/anser_test.go
migrations/github_hook_test.go
migrations/project_aliases_test.go
migrations/zero_date_fix_test.go
mock/environment.go
monitor/hosts_test.go
operations/cli_integration_test.go
operations/flags.go
operations/service.go
operations/service_deploy_migration.go
operations/service_runner.go
operations/service_web.go
rest/data/admin_test.go
rest/data/cli_update_test.go
rest/route/github_test.go
units/github_status_api_test.go
units/patch_intent_test.go
units/repotracker_test.go
units/stats_test.go

This change is non-functional until I resolve the TODO comment, but to do that I first need to make sure the evergreen config we have in chef explicitly has the /etc/mci_settings file set
BUILD-4576
It looks like we already have that set, so I've removed the default

EVG-2661 separate database from rest of config in evergreen service

---

model/task_lifecycle.go
model/task_lifecycle_test.go
units/github_status_api.go

Since the cleanup doesn't make it immediately clear how this fix works: we were erroneously updating status based on task failure. See left diff, line 530.
This lead to status updates being sent too soon, and using a zero time to calculate time differences

EVG-2641 Evergreen claims Github PR patches completed in negative times

---

public/static/plugins/perf/js/trend_chart.js

The old behavior can be seen in the following:
As you can see the current behavior truncates on both the left and the right. 
The new behavior fixed both these issues:
Left margin of 120 is to allow for even larger scale values. It is also possible to reduce the right margin, but in this case the graph appears off center.

EVG-2371: scale doesnt allow large numbers, the hover label truncates

---

service/templates/task_perf_data.html

This is only a partial fix as it looks like the container div may be the root cause. See https://github.com/angular/material/issues/5021.

EVG-2982: allow for better text selection.

---

service/patch.go

when manually authorizing patches, it set the wrong requester, which prevented status updates from happening.

EVG-2944 Use correct requester for manually authorised patches

---

public/static/js/projects.js
service/project.go

Note that this silently enabled webhooks and tracks push events when "add project" is used. If the hook can't be created, it logs it but still allows for project creation

EVG-2971 New Evergreen projects should have webhooks/webhook repotracker enabled by default

---

operations/host_spawn.go
rest/model/string.go

This fixes printing errors when used in a format string such as:
```
grip.Infof("Spawn host created with ID '%s'. Visit the hosts page in Evergreen to check on its status.", host.Id)
```
Now correctly prints:
```
evergreen-ci/evergreen master Δ ./clients/darwin_amd64/evergreen host create -d rhel70-small -k mathewrobinson
A new version is available. Run './clients/darwin_amd64/evergreen get-update --install' to download and install it.
[evergreen] 2018/04/20 12:45:00 [p=info]: Spawn host created with ID 'evg-rhel70-small-20180420164500-1674881231148019645'. Visit the hosts page in Evergreen to check on its status.
```

EVG-3188 Implement fmt.Stringer for APIString

---

glide.lock
model/event/subscriptions.go
model/trigger/build.go
model/trigger/build_test.go
model/trigger/patch.go
model/trigger/patch_test.go
model/trigger/payloads.go
service/api_task.go
service/patch.go
units/github_status_api.go
units/github_status_api_test.go
units/patch_intent.go
units/patch_intent_test.go
vendor/github.com/mongodb/grip/send/github_status.go

The remaining code in units/github_status_api can't be fully integrated into event driven notifications.
Bad config -> no patch is created.
For Auth request and patch pending, putting these into Event driven notifications risks out of order notifications, and users will not receive any immediate feedback that Evergreen has been notified about the PR.

EVG-3087 Convert existing Github PR Status API code to use event driven notifications

---

makefile
scripts/generate-lint.go

Note, there is a temporary hack in scripts/generate-lint.go to force the lint to run on everything. I'll undo that before merge.

EVG-3468 Enable goimports in gometalinter

---

command/git.go

- Staging patch created from windows: https://evergreen-staging.corp.mongodb.com/version/5b16cc0bb237362c41d7e4dc
- Staging patch created from OS X: https://evergreen-staging.corp.mongodb.com/version/5b16cdc897b1d35f01dc4ede
This patch contained whitespace changes and was successfully applied. Note that lint should have failed in the above patches, but it didn't because we don't run gofmt through our linter.
Additionally, I've confirmed that we can apply patches made in OS X, on Windows/OSX/Linux and create a patch from windows (with whitespace changes) and apply them on Windows/OSX/Linux

EVG-2719 Do not apply patches with --whitespace=fix

---

db/db_utils.go
model/host/db.go
model/host/host.go
model/host/host_test.go
operations/service.go
units/crons.go
units/host_monitoring_last_container_finish_time.go
units/host_monitoring_last_container_finish_time_test.go

Implemented first part of ticket -- creating necessary jobs, model updates, and functions to compute and cache last container finish time for all hosts with containers.

EVG-3423 add jobs updating last container finish time for parent hosts

---

rest/data/patch_intent.go
units/patch_intent.go

I'm deleting the block in patch_intents.go because I found out that its value was unused while comparing the logic to patch intents.

EVG-3155 Github Patch intents are being created for projects which don't have pr testing enabled

---

units/host_termination.go

This is an issue I noticed when investigating whether Evergreen already terminates idle containers. Currently, Evergreen does not check if the teardown script is empty before connecting to the host via SSH. This creates a lot of unnecessary overhead when there are no teardown scripts (which will be the case for containers).

EVG-3666 stop Evergreen from SSH-ing into host if teardown script empty

---

model/task/task.go
model/task_lifecycle.go

So here's the deal: our task model assumes that a status of failed or succeeded means the build is finished, which turn makes the version or patch as finished, but we mark builds as failed the second we see a non-successful task. 
In theory, this will fix things, but I need to throw this in staging to confirm. I also think I'll need to do a javascript/front end fix, so that builds with one failed task, and all others in progress are marked as failed.
Lastly, I removed the UndispatchedTime line because it no longer seems relevant, but I'll be doing some more investigation into that before merging.

EVG-3455 Remove Undispatched status from task.IsFinished

---

cloud/docker_client.go

Tiny change -- just generating a host secret for the new container before starting the agent. This is necessary because the "evergreen agent" command requires a non-empty host secret flag.

EVG-3661 generate host secret for Docker container hosts

---

thirdparty/s3_test.go

Instead of using the same URLs each time https://github.com/evergreen-ci/evergreen/blob/414a2b6371ac0712153316792c13115e433d1a54/thirdparty/s3_test.go#L14-L15, generate unique names like so: 
```
sourceURL   = "s3://build-push-testing/test/source/<random-string>"
downloadURL = "https://s3.amazonaws.com/build-push-testing/test/source/<same-random-string>"
```

EVG-3680: generate unique names for S3 integration tests

---

cloud/docker.go
cloud/docker_client.go
cloud/docker_mock.go
cloud/docker_test.go
service/templates/distros.html

This PR adds EnsureImageDownloaded to the Docker client, which checks whether the image specified by the URL in the distro's provider settings is already present on the parent host, and imports the image from the URL if necessary.

EVG-1930 docker manager should download new images

---

cloud/docker.go
cloud/docker_client.go
cloud/docker_test.go

Keeps distro-specified user in Docker settings. This allows Evergreen to configure new containers so that the Evergreen agent runs as the correct user on the remote machine.

EVG-3692 Start agent in containers as user specified in distro

---

cloud/docker.go
cloud/docker_client.go
cloud/docker_mock.go
cloud/docker_test.go

Having the user in the dockerSettings struct causes an issue, because the Validate() function is called when creating a new distro and my changes made it so that user is only added to dockerSettings when Spawnhost is called. We figured the best way to fix this is to pass user as a string to CreateContainer.

EVG-3692 move user out of Docker settings struct

---

cloud/docker_client.go

The Dockerfile to build a new image from is actually at `/api/dockerfile`, not `/rest/v2/dockerfile`.

EVG-3731: update Dockerfile route

---

service/templates/distros.html

Previously, the Pool ID field for container pool distros was being saved within provider settings. It should be stored in the distro.ContainerPool field.

EVG-3727 Save container pool ID to correct distro field

---

scheduler/scheduler.go
scheduler/scheduler_test.go

Scheduler was originally creating parents based on a container distro instead of looking at the parent distro set in the container pool.

 EVG-3728: create parent intent documents using container pool distro

---

cloud/docker_test.go

This was causing errors when repeatedly running a single test in the TestDockerSuite. We never use the inserted distro in any queries, so it makes sense to remove it.

EVG-3480 remove unnecessary distro collection insert

---

model/host/host.go
model/host/host_test.go
scheduler/scheduler.go
scheduler/scheduler_test.go

Scheduler currently does not check the number of parent hosts that are about to come up when calculating how many new parents are needed.

EVG-3730: check uninitialized parent documents before inserting new ones

---

cloud/docker_client.go

EnsureImageDownloaded now runs ImageInspect periodically after an ImageImport call to ensure that an image has actually been downloaded to the parent host. Also, makeDockerLogMessage now wraps other log data with the name of the API call and the parent host ID.

EVG-1930 verify that ImageImport has succeeded

---

globals.go
model/host/db.go
model/host/host_test.go
units/provisioning_create_host.go

Previously, the intent document is removed before SpawnHost is called and the host document is reinserted as starting only after SpawnHost returns. This is a problem for containers, since SpawnHost can take even a few minutes to return (if the parent has to download and build new container images). In such cases, the scheduler will continue to create new container intent documents.
This adds a new HostSpawning status after the intent doc is picked up by Hostinit but before SpawnHost returns. This prevents the Scheduler from creating redundant container intent docs or removing container intent documents while containers are Spawning.

 EVG-3822 Create new status after initializing and before starting

---

units/host_monitoring_container_state.go
units/host_monitoring_container_state_test.go

This makes two changes to the container state consistency job in order to fix bugs discovered in E2E testing.
- Exports the provider name in the job. This was not previously exported, which meant that the job tried to retrieve a "" cloud manager whenever it ran.
- Only terminates not running in Docker that are running or decommissioned in the DB. Previously, the job would terminate any containers not running in Docker (including host documents that were still initializing).

EVG-3507 fix bugs in container state consistency job

---

public/static/js/services/rest.js
public/static/js/spawned_hosts.js
public/static/partials/user_host_options.html

I didn't see a field in the task document that tells me whether the task spawned any hosts, but if there is one then the checkbox can be hidden if not applicable

EVG-3222 add UI element for createhost reproduction

---

units/host_termination.go

Host termination job now mark containers in the database as terminated when their parents have already been terminated. Previously, decommissioned containers whose parents have already terminated would never exit because running TerminateInstance on a container always fails (since the Docker daemon was on the parent).

EVG-5159 terminate container in DB if parent already terminated

---

cloud/docker.go
cloud/docker_client.go
cloud/docker_test.go
cloud/docker_util.go

Removes container port configuration from the Docker client and tests. We noticed that when multiple containers were trying to start at the same time, they all tried to bind to the same port and only one would be able to start successfully. We realized that these exposed ports are no longer necessary, since we do not directly SSH into the individual containers. The code supporting exposed ports can be safely removed.
Should we keep the utils, even if the Docker client no longer uses them?

EVG-5151 remove exposed port from Docker containers

---

cloud/docker.go
cloud/docker_client.go
cloud/docker_mock.go

Fixes *theoretical* memory leak by returning httpClient to the pool after it is used. The new Close() method is part of the Docker client, and only attempts to put the httpClient back if it is not already nil, in which case it was either never taken from the pool or already put back. Each method in the Docker cloud manager that uses the httpClient in a Docker client call now has "defer m.client.Close()" to make sure the httpClient is always put back.

EVG-5148 add dockerClient.Close() method to return httpClient to pool

---

trigger/interface.go

Spawn host and host expiration have different handlers registered, but the same selectors. That means that when processing 1 type of events subscriptions for the other will be found, which causes this error. I don't think there's any need to error here, since it's either going to be programmer error or this scenario

EVG-5146 don't error for triggers not in registry

---

cloud/docker.go
cloud/docker_mock.go

This affects how we decide which containers to set as terminated in our HostMonitorContainerStateJob.

EVG-5173: return containers by name instead of ID in GetContainers

---

cloud/cloud.go
cloud/docker.go
cloud/docker_client.go
cloud/docker_test.go
model/host/counters.go
model/host/db.go
model/host/host.go
model/host/host_test.go
units/building_container_image.go
units/building_container_image_test.go
units/provisioning_create_host.go

Closed old PR (https://github.com/evergreen-ci/evergreen/pull/1513) because it was too messy with various local commits that attempted to fix Docker errors with Thomas's refactor (https://github.com/evergreen-ci/evergreen/commit/dd558974ec67f6aad7509badcd5847bf0fb3f7c5). 
`BuildingContainerImageJob` makes is so that when many containers come up on the same parent, they do not all try to download the same image. Parents will hold a map of ready container images. This also separates out the downloading and building of the images, blocking until the provisioned image is ready on each container. 
This job retries 5 times (arbitrary number, can be changed) before finally giving up and terminating the parent. This is necessary because if the parent stays up, containers will continue to try to …

 EVG-5152: create job to prepare container images before SpawnHost

---

cloud/docker_client.go
config_containerpools.go
rest/model/admin.go
service/templates/distros.html
testutil/config.go

The warning message in `archlinux-packer` had a typo, and we do not use `Port` in `archlinux-docker` anymore, so I've removed it completely.

EVG-5219: remove port and typo from distro UIs

---

scheduler/duration_based_host_allocator.go
scheduler/scheduler.go
scheduler/scheduler_test.go
scheduler/utilization_based_host_allocator_test.go
units/provisioning_create_host.go

This fixes the problem where all the containers were being put on one parent because we were checking the DB for available parents before any of the containers knew about each other. Now, we check for how many more containers a parent can have by keeping its current number of containers in a slice. 
`MaxDurationPerDistroHostWithContainers` is an arbitrary number right now, but will affect some utilization based host allocator tests.

EVG-5207: create containers only on parents with space

---

scripts/generate-lint.go
self-tests.yml

This is how I've been running self-tests in staging (Most of the time though, I've just been running patches with `.test` and those all finish very quickly once the containers are up). When testing what is in this PR, `js-test`, `smoke-test-endpoints`, `smoke-test-task`, `test-command`, and `test-operations` fail. 
Things to note: 
- this changes the hard coded `lintVariant` to archlinux-docker
- you can check the Docker API calls in Splunk with the search `message="docker API call"` 
- containers are "building" for about 12 min before they come up as running. This is just how long the image import and download takes
- `make: go: Command not found` at the end of tasks 
- `smoke-test-endpoints` and `smoke-test-task` just seem to never finish, possibly looping forever
- parents have …

EVG-5221 run Evergreen self-tests with many containers

---

model/lifecycle_test.go
model/task/db.go
model/task/sorter.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
units/task_monitor_execution_timeout.go
units/task_monitor_execution_timeout_test.go

The first commit is undoing a revert, the second is a change that I forgot to make in the original commit

EVG-5212 clear reset flag on display tasks

---

self-tests.yml

this is just a stopgap to fail our tests early on docker until I fix them (they're timing out after 6 hours currently)

EVG-5221 update exec timeout for smoke tasks

---

cmd/generate-lint/generate-lint.go
makefile

This turns of staticcheck (for now), the longpull for it in the
context of megacheck slows everything down. 
I have a pull request that should let us turn it back on.

EVG-5347: expedite linting

---

repotracker/repotracker.go
repotracker/repotracker_test.go

The error in this case was a duplicate key when inserting a task

EVG-5456 continue on error when creating versions in repotracker

---

public/static/js/subscriptions.js
service/templates/build.html
service/templates/task.html
service/templates/version.html

* User's email is pre-populated in notification email field
* Slack username field is no longer populated with an API call

EVG-5291: Default in the user's email when adding a subscription via email

---

globals.go
rest/route/host.go
rest/route/host_test.go
rest/route/service.go

Which of these are not valid user set states and should be removed from globals.go? 
ValidUserSetStatus = []string{
HostRunning,
HostTerminated,
HostUninitialized,
HostBuilding,
HostStarting,
HostProvisioning,
HostProvisionFailed,
HostQuarantined,
HostDecommissioned,
}

EVG-1720: change a single host status patch

---

validator/distro_validator.go
validator/distro_validator_test.go
validator/project_validator.go
validator/project_validator_test.go

We want to use the '|' character as a separator for the start_at key when querying test/task statistics. This would assume the character does not appear in test, task, variant and distro names.

EVG-5412 Prevent usage of '|' in task, distro and variant names

---

model/stats/db.go
model/stats/query.go
model/stats/query_test.go

When querying test and task statistics the semantic was to resume **after** the document corresponding to the StartAt. With this change we resume **at** the document.

EVG-5412 Update StartAt semantic

---

public/package-lock.json
public/package.json
public/static/app/perf-bb/SignalProcessingCtrl.js
public/static/app/perf-bb/constants.js
public/static/app/perf-bb/hazardLevelCell.js
public/static/app/perf-bb/microHazardChart.js
public/static/app/perf-bb/templates.js
public/static/js/tests/conf/karma.conf.js
service/templates/signal_processing.html

* Use client sort instead of server side sort
* Default sort by commit and then by hazard value (magnitude)
* Fixed diff calculation for latencies
* More descriptive Hazard chart instead of single-value regression
* New columns: Magnitude, Min. Magnitude, Prev./Next Mean
* Now, should be, more or less, consistent with python code
Palette for hazard chart:

EVG-5484 (feat) PerfBB - Hazard representation and calculation

---

public/static/app/perf/perf.js
public/static/app/perf/trend_chart.js

EVG-5332 (fix) Trendchart - display current commit for MAXONLY mode

---

service/templates/admin.html

The previous commit caused the radio buttons to be on top of one another instead of side-by-side.
Through experimentation I determined the change that caused this was adding whitespace between the button elements. It's not clear to me why this caused the bug. Regardless, setting the layout to row is a better way to express what we're trying to do.

EVG-5731: Fix degraded mode flags in UI

---

apimodels/s3copy.go
command/s3_copy.go
command/s3_put.go
model/s3copy.go
service/api_plugin_s3copy.go

The only thing I did not do that the ticket requested was copy the permissions of the filed being copied. This would break code where they are expecting files to have public-read permissions when copied over (public-read is the default).

EVG-3389: s3Copy.copy command should accept a permissions argument

---

public/static/js/build.js
public/static/js/task.js
public/static/js/version.js

Duplicate subscriptions were being posted if the user created more than one subscription without refreshing the page.
By removing the list and posting one subscription at a time we avoid duplicate subscriptions.

EVG-5717: fix UI bug when adding subscriptions

---

public/static/js/task_timing.js
public/static/js/task_timing.test.js

It seem that project tasks set is not equal to all bv tasks set (Probably, bug in the model or some sort of a 'feature')

EVG-5757 (fix) Task Timing - use bv tasks insetad of prj tasks

---

public/static/app/common/Settings.js
public/static/app/common/Settings.test.js
public/static/app/common/constants.js
public/static/app/perf-bb/SignalProcessingCtrl.js

* Persistent filtering settings for Signal Processing page (plugin -> performance baron)
* `Settings` service accepts `Object` type

EVG-5658 (feat) Signal Processing - persistent filtering settings

---

apimodels/agent_models.go
cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_test.go
model/host/db.go
model/host/host.go
model/host/host_test.go
rest/data/host_create.go
rest/data/host_create_test.go
rest/model/createhost.go
rest/model/createhost_test.go
units/provisioning_setup_host.go

This is a preliminary code review, assuming that setting the NetworkInterface to creating an IPv6 address will be enough. We don't yet know if there will still be a public DNS name when the NetworkInterface object specifies AssociatePublicIpAddress as false.

EVG-5770 spawn ipv6 host from tasks

---

model/commitqueue/github_pr_sender.go

Stop the merge from going through if HEAD of the PR is not the commit we tested.
This could happen if a user pushes a commit to a PR after we've already created a patch to test the commit queue item but before we go to merge.

EVG-5813: Add SHA check to merge options

---

units/commit_queue.go

Brian talked me out of making a timeout to remove stuck items from the queue in favor of more aggressive error handling to keep them from getting stuck in the first place.
The rule I followed here was that if an error is likely to be a problem for everything on the queue (e.g. we aren't getting a response back from GitHub when we ask for more information about a PR) then we log the error and let the queue block (instead of emptying the queue) whereas if the problem is likely specifically for this item (e.g. the item can't be parsed as an int) then we log the error and remove it from the queue.

EVG-5812: Remove items from queue that would block

---

units/commit_queue.go

Fix for bug encountered when a PR was pushed to the queue while the commit queue was in degraded mode and then manually merged before the commit queue picked it up.
The queue blocked when the PR came to the head of the queue and was not processed.
The commit queue was not acting on the PR because GitHub reports `mergeable: nil` for already merged PRs.

EVG-5839: Fix for PRs pushed and subsequently merged

---

agent/agent.go
agent/task.go

I had wanted to refactor the part of the agent that fetches the task config since I felt this change adds too much code duplication, but that refactor breaks many tests due to how the tests are setting up mock data and it was really nasty trying to untangle that. Let me know if you'd like me to revisit that

EVG-5821 fetch project vars earlier in agent

---

agent/agent.go
agent/agent_test.go
apimodels/agent_models.go
service/api_task.go
service/api_task_test.go

The bug that this addresses is in the following sequence of events:
1. An agent calls /end, having finished a task.
2. The agent calls /next_task. It receives a new task and `newAgent`, which means that it should exit if it's safe to do so, i.e., it's not in a task group.
3. The server marks the new task as dispatched.
4. The agent checks to see if it's safe to exit. It is, because `nextTaskHasDifferentTaskGroupOrBuild` returns `true`. It then calls /next_task _again_, in order to ensure that the host is marked as needing a new agent. Then it exits.
The problem is that in order to find out if it's safe to exit, the agent must get a new task, but getting a new task causes that task to enter the dispatched state. At that point the server expects the agent to be running the task, but the …

EVG-5844 Never exit with a task group task

---

rest/data/task.go
rest/data/task_test.go

Used to return a 404, which is appropriate if the client asks for a specific task but not when the user asks for an empty list

EVG-5785: Return an empty response for a build with no tasks

---

model/task/db.go
rest/data/task_test.go

Pagination is done by taking the next _limit_ number of tasks greater than or equal to the key provided and giving a key for the next page as the _limit+1_ task. If the tasks are not sorted the _limit+1_ task will likely not be the correct key.
Deploying this will require replacing the build_id index on the database with a composite index of build_id and _id so the match/sort stages can be done efficiently.

EVG-5843: Add sort to tasks for build aggregation

---

public/static/js/projects.js
service/project.go
service/templates/projects.html

There was a checkbox on the projects page to enable webhooks for a repository (owner/repo pair). 
Since we almost always want webhooks (to support PR testing and commit queue) this PR is to enable it by default on save, and to display just the status on the projects page.

EVG-5771: Enable GitHub webhooks automatically

---

model/context.go

The context was not getting populated with tasks that had been archived as long as the query for a non-archived task was successful (even if it returned nil) since mgo.ErrNotFound was caught and handled further down the call stack. Therefore it was impossible to get the task page for an archived task.
When a user would click a link for an archived task (such as an execution task) they would get a 404.

EVG-5848: Check for Old Tasks

---

model/context.go
service/task.go

Additional fix for display task links. This fixes the case where an execution number is not provided in the URL (to show the latest execution).
Reference PR #2072. This PR is to add commit 287baf3.

EVG-5848: display task links

---

model/task/db.go
rest/data/task_test.go

Refer to PR #2068. The commit was reverted because it was merged before the index described there was built.
This PR is to reintroduce those commits now that the index has been added.

EVG-5843: build task pagination

---

command/git.go
command/git_test.go
model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/commitqueue/db.go
model/commitqueue/github_pr_sender.go
model/commitqueue/github_pr_sender_test.go
model/patch/db.go
operations/commit_queue.go
operations/commit_queue_test.go
rest/client/mock.go
rest/data/commit_queue.go
rest/data/commit_queue_test.go
rest/data/interface.go
rest/model/commit_queue.go
rest/model/commit_queue_test.go
rest/route/commit_queue_test.go
rest/route/github.go
rest/route/github_test.go
rest/route/testdata/comment_event.json
thirdparty/git.go
thirdparty/git_test.go
units/commit_queue.go
units/commit_queue_test.go

Support adding a module patch to commit queue tests. "Patches" in this case are in the form of PRs against module repos.
To include a module PR with the main PR add a json doc to the evergreen merge comment. For example: `evergreen merge {"modules":[{"module":"test_module", "issue":"1234"}]}` where _1234_ is the PR number of the module _test_module_. Patches cannot be added after the `evergreen merge` comment is already started since commit queue patches are immediately finalized.
All PRs are checked out in the patch created to test the merge (the module PRs are checked out in the directories specified for the module in the config file). If the patch succeeds the main PR and all the module PRs are merged.

EVG-5577: Commit queue set-module

---

glide.lock
rest/route/task.go
vendor/github.com/evergreen-ci/gimlet/framework_response.go

Companion to gimlet PR 23 (https://github.com/evergreen-ci/gimlet/pull/23).
The error handling here is no longer necessary.

EVG-5785: remove check for empty response

---

model/host/host.go
model/host/host_test.go

Wasn't sure if it was correct to return an error if host not found, but other functions in this file seem to ignore that so I went with that precedent, unless this is something we want to keep track of.

EVG-5487 only mark host as provisioned if status is valid

---

rest/data/version.go
service/waterfall.go

My initial plan was to more rigorously differentiate between triggered builds, but that went down a rabbit hole of lots of changes so I'm just going to do this for the waterfall

EVG-5824 stop displaying '(removed)' on variants

---

agent/agent.go
rest/client/logger.go

JIRA: https://jira.mongodb.org/browse/EVG-5949
This is the same logging change as [EVG-5882](https://github.com/evergreen-ci/evergreen/pull/2082) but it checks if `tc.logger != nil` before checking the logger closed status.

EVG-5949: check that logger is non-nil before checking if it's closed

---

rest/data/commit_queue.go
rest/route/github.go

Upon queueing, the commit queue sends a status to the GitHub PR indicating the PR is on the queue.
GitHub displays the statuses of the commit at the tip of the branch being merged in, so the API call needs to reference the SHA of that commit.

EVG-5922: fix destination of github status messages

---

command/registry.go

Disambiguate commands within functions in the command description. 
For example, if a shell.exec in a function fails and that function contains multiple shell.execs we will now know which one failed.

EVG-5852: add command number to command description

---

rest/data/host_create_test.go
rest/model/createhost.go
rest/model/createhost_test.go

host.list response modeled after that in the technical design. I wonder however if there was a reason we use "host" for containers instead of "instance_id" as we do for non-containers (do we specifically want these outputs to be mutually exclusive?)

EVG-5865 add containers to host.list

---

service/task_history.go
service/task_history_test.go

When more than one version have equal create_time we leave out versions with a matching create_time from the task history since we're querying for $lt and $gt the middle version, but not equal.
(create_time is set for repotracker versions to the commit time reported by GitHub which has second precision so collision is not terribly difficult)
The solution was to match on $gte and $lte the middle version, but if it's equal than it must be $gt and $lt a second field which is guaranteed to be unique. The commit SHA was chosen as the second field because it's unique.
**Before deploying this PR** we should evaluate how to update the project_id:requester:create_time compound index to include the gitspec field.

EVG-5846: fix task history panel

---

model/patch/patch.go
thirdparty/github.go
thirdparty/github_test.go
units/commit_queue.go
units/commit_queue_test.go
units/patch_intent.go
units/patch_intent_test.go

Add the diff GiHub provides for a PR to the patch so it can be displayed in the UI.
For example:

EVG-5857: add diff to commit queue patches

---

cloud/cloud.go
cloud/docker.go
cloud/docker_client.go
cloud/docker_mock.go
cloud/docker_test.go
model/host/host.go
rest/data/host_create.go
scheduler/scheduler.go
scheduler/scheduler_test.go
units/building_container_image.go
units/building_container_image_test.go
units/provisioning_create_host.go

For context, want containers started from host.create and scheduler to pipe through provisioning_create_host. Besides a placeholder for finding parents (which will be handled in a later ticket) this ticket covers the following:
- Determine if method for create.host containers is Import or Pull (based on format of image). https://docs.docker.com/engine/reference/commandline/pull/ “Pull from a different registry” is how I’m distinguishing this.
- Use h.DockerOptions instead of h.Distro.ProviderSettings in all cases (to unify scheduler and host.create). This changed NewBuildingContainerImageJob signature, verified this shouldn’t be a problem.
- Only use the evergreen agent command we've had previously if no command is given (which is required for host.create containers).
- Only build image …

EVG-5867 support starting containers without agent

---

service/task_history.go
service/task_history_test.go

The query introduced in PR #2103 is slow because the sort doesn't use the index.
This PR returns to the previous query and adds a separate query for versions with matching create_time and the results are appended together in memory.

EVG-5846: task history missing

---

cmd/build-cross-compile/build-cross-compile.go

JIRA: https://jira.mongodb.org/browse/EVG-5975
go1.12 requires an absolute path for GOCACHE.

EVG-5975: make GOCACHE use an absolute path instead of relative path

---

plugin/perf.go
public/static/app/common/PointsDataService.js
public/static/app/common/PointsDataService.test.js
public/static/app/common/constants.js
public/static/app/perf/perf.js
public/static/app/perf/trend_chart.js
service/templates/base_angular.html

I edited [19_03_15_14_05_13](https://evergreen.mongodb.com/task/sys_perf_linux_standalone_bestbuy_agg_0a856820ba29e19dcba0979f71b11ae01f4be0f1_19_03_15_14_05_13) to make it an outlier and rejected.
You can see in the following GIF that there is no current marker (yellow circle). Also if you watch the dates on the Right Hand Side, the 15th march is skipped (so it isn't being rendered).
[19_03_16_14_18_52](https://evergreen.mongodb.com/task/sys_perf_linux_standalone_bestbuy_agg_6161eb7b7aff5305b445dcdd20825f041b5e5a68_19_03_16_14_18_52) is the commit after the rejected task. 
Notice there is a current icon but the 15th March is still not displayed in the dates on the Right Hand Side.

EVG-6011 don't show rejected task data

---

globals.go
model/patch/patch_test.go
operations/commit_queue.go
operations/commit_queue_test.go
operations/patch.go
operations/patch_util.go
rest/client/interface.go
rest/client/mock.go
rest/client/rest.go
rest/model/commit_queue.go
units/commit_queue.go

Theory of operation: 
1. an mbox formatted patch (which includes commit metadata) is uploaded as an unfinalized patch. 
2. the patch ID is enqueued on the project's commit queue.
steps 1 & 2 are severable (with the `--pause` option) to allow uploading modules to the patch before enqueuing (which is part of an upcoming ticket, [EVG-5932](https://jira.mongodb.org/browse/EVG-5932)).
Open question: do we want to allow passing in extra args to `git format-patch` as we do for `git diff` when creating patches?

EVG-5931: Commit Queue merge command

---

cloud/cloud_host.go
cloud/cloud_intent.go
cloud/docker_test.go
cloud/ec2_integration_test.go
cloud/gce_test.go
cloud/openstack_test.go
cloud/spawn.go
cloud/vsphere_test.go
model/host/host.go
model/host/host_intent.go
model/host/host_test.go
rest/data/host_create.go
rest/data/host_create_test.go
rest/route/host_create.go
rest/route/host_create_test.go
scheduler/scheduler.go
scheduler/scheduler_test.go
units/host_termination.go
units/provisioning_agent_deploy.go
units/provisioning_create_host.go

Moves the logic of creating/assigning parents out of scheduler into host and cloud, and calls this in both scheduler and hostCreate. Note that a lot of this code isn't new, just moved.

EVG-5895 move creating/assigning parents out of scheduler

---

public/static/app/common/constants.js
public/static/app/perf/perf.js
service/templates/task_perf_data.html

I couldn't test the rendering of the new toggle locally, but I did test the functionality by cross wiring origin mode to show / hide rejects.

EVG-6024 add UI control to show / hide rejects. The default hides rejected data.

---

cmd/evergreen/evergreen.go
config.go
model/build/db.go
operations/admin.go
operations/admin_all_configs.go
operations/commit_queue.go
operations/commit_queue_test.go
operations/export.go
operations/fetch.go
operations/http_test.go
operations/last_green.go
operations/list.go
operations/model.go
operations/patch.go
operations/patch_cancel.go
operations/patch_finalize.go
operations/patch_list.go
operations/patch_module.go
operations/subscriptions.go
operations/update.go
operations/validate.go
service/rest_stats.go
service/scheduler.go

JIRA: https://jira.mongodb.org/browse/EVG-5989
* Re-added `evergreen export` subcommand.
* Removed unused `Communicator`s and added `Close()` to unclosed `Communicators`.
* The endpoints that export requests usually return "200 OK" but sometimes return "500 Internal Server Error" (especially `/rest/v1/scheduler/host_utilization`), seemingly because of some timeout on the server side. I've tested this with the cli, curl, and my browser and it happens sporadically.

EVG-5989: add export cli tool

---

globals.go
model/distro/db.go
model/distro/distro.go
public/static/js/distros.js
rest/model/distro.go
rest/route/distro.go
rest/route/distro_test.go
service/templates/distros.html
validator/distro_validator.go
validator/distro_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-5998
https://jira.mongodb.org/browse/EVG-5999
https://jira.mongodb.org/browse/EVG-6044
* Added an option to the UI to configure provisioning.
If somebody wants to suggest a better name for the field than `BootstrapMethod`, let me know because I don't love it.

EVG-5998, EVG-5999, EVG-6044: Add legacy SSH/Jasper bootstrap option to distro UI and REST.

---

model/distro/distro.go
model/host/host.go
model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6055
This is currently unused because it's just in preparation for Jasper being started as a service when it's being started over SSH.

EVG-6055: add function to check Linux host's init system

---

rest/model/distro.go
service/distros.go

JIRA: https://jira.mongodb.org/browse/EVG-6081
I assumed that only the UI page would use the `(*UIServer).modifyDistro()` method (`POST /distros/{distro_id}`), but apparently build uses it to update their AMIs as well.

EVG-6081: default to legacy SSH if not specified in UI server

---

model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
public/static/js/filters/filters.common.js

When execution tasks depend on a previous execution task succeeding (which has failed), they will block indefinitely and thus the overall task will appear yellow as Started instead of red as Failed.
Approach: if there exists failed tasks and all unfinished tasks are blocked, then update the status as failed.

EVG-6021 fix display tasks appearing yellow when blocked on themselves

---

model/test_log.go

Currently the log link is "http://test_log/..." when it should be "http://evergreen.mongodb.com/test_log/.."

EVG-5826 fix log link for testresults

---

apimodels/agent_models.go
cloud/docker.go
cloud/docker_client.go
cloud/docker_mock.go
command/host_create.go
globals.go
model/host/db.go
model/host/host.go
model/host/host_intent.go
rest/data/host_create.go
rest/data/host_create_test.go
rest/model/createhost.go
rest/model/createhost_test.go
rest/route/host_create.go
rest/route/host_create_test.go
service/host.go
units/building_container_image.go
units/crons.go
units/host_monitoring_container_state.go
units/host_monitoring_external_termination.go
units/host_monitoring_idle_termination.go
units/host_monitoring_last_container_finish_time.go
units/oldest_image_removal.go
units/provisioning_create_host.go
units/stats_host_idle.go

Work in progress--couple small details left to work out/test. This is an overview of the logic changes made, if anyone would like to code review this draft:
* parentID stored in host intent will not persist 
* Container pool validated in the wrong spot
* NewBuildingContainerJob wasn’t getting hit, because was relying on CurrentAttempts, and should retry
* Change method of determining import or pull
* External Identifier not necessary

EVG-5872 dogfooding spawn containers

---

cloud/docker_integration_test.go
self-tests.yml

This test is flaky because we can't always ensure that docker is up on the parent. It's possible that why this occasionally takes so long should be investigated separately, but the test itself doesn't verify much functionality and is more reliably tested locally.

EVG-5958 remove flaky image pull test

---

model/host/host.go

This ticket was made off of the assumption that UserHost is always set to false as stated in the comment, because RemoveStaleInitializing filters by UserHost (in order to not remove intent hosts spawned by tasks or users). However, UserHost can be set to true, and so this comment should be removed to avoid future confusion.

EVG-6017 remove incorrect comment

---

trigger/payloads.go
trigger/payloads_test.go

Add URL base from evergreen config before transferring failed tests from the task to the template.

EVG-5826 fix log link in emails

---

model/commitqueue/github_pr_message.go
model/commitqueue/github_pr_message_test.go

The default commit queue PR commit message was removed in #2179 but the check for a message was not. It never really made sense to require one anyway.

EVG-6099: remove check for commit message

---

cloud/docker_client.go
command/host_create.go
rest/client/rest.go
units/host_monitoring_container_state.go
units/host_monitoring_parent_decommission.go
units/host_status.go

Typo in routes... Still getting errors that the communicator for whatever reason isn't able to parse, so I added logging to GetDockerLogs to figure out what's happening.

EVG-6100 logging in GetLogs and small route fixes

---

model/build/build.go
model/build/build_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go

The logged status of a patch is derived from the outcome of `AllUnblockedTasksFinished`. Since an aborted task is deactivated, when the task completes and calls `endTask` the patch is logged as succeeding since the function assumes a deactivated task has not failed. The logged status is the status reported to the user, so slack notifications for deactivated tasks were said to be successful.
The activated status checked is from the cached task, which was not being updated when the task was restarted. Therefore it was reported successful each subsequent time the task was restarted.
This PR is to only assume deactivated tasks are okay if the task isn't complete and to update the cached task's activated field on restart.

EVG-6050: fix activated field in cached task

---

model/project_ref.go
public/static/js/projects.js
rest/model/project.go
service/templates/projects.html

This commit queue setting on the project page was a placeholder that ended up unused.

EVG-5937: remove status action setting

---

model/task/task.go
model/task/task_test.go

Tasks older than the threshold were still being scheduled. We were filtering out tasks with an unset activated time so those were still being scheduled.
The activated time is fixed since #2184 and #2218 so that any activated task will have an activated time. We could do nothing, but I suggest removing the now superfluous check for unset activated time.

EVG-5896: remove check for unset activated time

---

service/templates/notifications.html
units/commit_queue.go
units/commit_queue_test.go

If a user hasn't set up their commit queue notification setting they will be opted in to email notifications when they submit a patch to the commit queue.

EVG-6131: add default email notifications

---

units/host_termination.go

We don't want to log if status is decommissioned either--really terminated is the only status we should care about here.

EVG-5979 fix job collision logging

---

config.go
operations/flags.go
operations/patch_module.go

the `addRefFlag()` function sets a default value for the --ref flag (HEAD), so when it's not specified on the command line it is not "" (which would include changes to the working tree) but rather "HEAD"

EVG-6141: fix set-module ref flag

---

model/host/host.go
model/host/host_test.go

The original algorithm mistakenly ignored uninitialized parents (making newly created parents useless). 
EVG-5895 fixes this in some places; however, these changes didn’t account for uninitialized containers also being ignored. We still want to consider these uninitialized containers in our calculations so we don't overload an uninitialized parent.
NOTE: this might not be the whole problem? But it's the main one I'm seeing, and would be relevant eventually.

EVG-6134 scheduler parent calculation correction

---

agent/agent_test.go
agent/command.go
agent/task.go
model/project.go
model/project_parser.go
model/project_parser_test.go

Want users to be able to define their own timeout for setup_group. Note this still only gives an error if setup_group_can_fail_task is also set.

EVG-5970 add setup_group_timeout_secs

---

units/commit_queue.go
units/commit_queue_test.go

Make the commit queue's commit titles consistent with GitHub's

EVG-5858: add PR number to commit title

---

public/static/app/common/RestartUtil.js

When trying to restart all failed tasks in a version, we weren't checking the Test Timed Out status, which is still a failure.

EVG-6147 restart test-timed-out tasks

---

public/static/app/perf/TestSample.js
public/static/app/perf/perf.js
public/static/app/perf/trend_chart.js
public/static/js/filters/filters.common.js
service/templates/task_perf_data.html

This is the parts that could be done without MAKE-762. Metrics that are not ops/s should be handled appropriately on the trend charts now, though things that require commit data (x axis, hovering, comparisons) don't yet work for expanded metrics

EVG-6087 handle other metrics on trend charts

---

model/commitqueue/commit_queue_test.go
model/commitqueue/db.go

When a project enables the commit queue and a commit queue doesn't yet exist we insert a commit queue into the database.
The check for whether or not a commit queue exists assumes an error is returned when no documents match the query but the error was being swallowed.

EVG-6162: pass through a ResultsNotFound error

---

service/project.go

While investigating EVG-6162 it was challenging to track down changes to a project's commit queue because the changes weren't appearing in the project's event log (EVG-5405).
The changes were being made to the projectRef before the original projectRef was preserved.

EVG-6162: include commit queue changes in project events

---

command/git_push.go
operations/commit_queue.go

- The committer information was not getting passed through to the git.push task.
- The commit message was not being set to the branch name when not passed in.
Also, clarified the commit message flag.

EVG-6143: Fix commit-queue CLI

---

model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go

A panic occurred when the GitHub merge sender tried to send a message using the GitHub status sender. This happened because when it was instantiated a nil interface was passed in as the GitHub status sender.
This PR is to pass the actual sender.

EVG-6143: pass real sender to GitHub merge sender

---

cloud/docker_client.go

Unable to replicate setup failures (I think it may have actually been a rebase issue). Did notice an extra case that should be handled by GetDockerStatus.

EVG-6133 prevent status from logging unnecessary errors

---

units/building_container_image.go

JIRA: https://jira.mongodb.org/browse/EVG-5983
* Parent host is set to decommissioned instead of terminated to ensure underlying cloud host is terminated by host termination job.

EVG-5983: if building container image job fails, set parent to decommissioned

---

config.go
operations/flags.go
operations/model.go
operations/model_test.go
operations/patch.go
operations/patch_module.go
operations/patch_util.go

By default the command to generate the diff for a patch/module will be `git diff {merge_base} HEAD`
Provide an option to run `git diff {merge_base}`, preserving the original behavior which includes working tree changes in patches/modules.

EVG-6142: ignore working tree changes by default

---

model/project.go
validator/project_validator_test.go

The problem was that David's config changes were invalid, but were not caught by the validator (they errored at runtime, but the error was just logged and we continue)

EVG-6136 validate dependencies in task groups

---

model/task/task.go
model/task/task_test.go

Since display tasks are never scheduled the display task's scheduled time will be set when one of its execution tasks run.

EVG6140: add scheduled time to display tasks

---

model/task/db.go
model/task/results.go
model/task/task_test.go
rest/data/interface.go
rest/data/status.go
rest/model/status.go
rest/model/status_test.go
rest/route/status.go
rest/route/status_test.go

The recent_tasks endpoint shows the number tasks that have completed recently, broken down by status. This will break it down further by distro or project.

EVG-6039: break down recent_tasks by distro or project

---

config.go
operations/patch.go

Aliases were not being read in from the command line.

EVG-6169: fix aliases for patch-file command

---

repotracker/github_poller.go

Shed light on when the repotracker runs and picks up no revisions.

EVG-6198: add logging to track unscheduled bvs

---

makefile
model/generate.go
model/generate_test.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/task/sorter.go
model/task/task_test.go
repotracker/github_poller_test.go
repotracker/repotracker.go
repotracker/repotracker_test.go
rest/data/interface.go
rest/data/version.go
rest/data/version_test.go
rest/route/version_create.go
self-tests.yml
service/patch.go
trigger/project_triggers.go
units/generate_tasks.go

Inserting version, build, and task documents are in the same transaction which will abort if any errors (including non-db errors potentially). All db tests now run with a single node replica set which doesn't seem to add any noticeable overhead

EVG-5823 repotracker inserts tasks in a transaction

---

model/build/task_cache.go
model/build/task_cache_test.go
model/task/sorter.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go

Restarting tasks checks that the status is a finished status (either "failed" or "succeeded"). However, for display tasks if an execution task system-failed the status would be "system-failed", so it would not be restarted.
This PR is to make exec task and display task statuses consistent.

EVG-6159: restart system failed tasks

---

model/project_aliases.go
model/project_aliases_test.go
service/project.go

Before when we upserted we were modifying the current project's patch aliases to have the new project ID, which is why they "disappeared" for the current project. We should be adding a new alias document.

EVG-5878 create new patch alias for copied projects

---

units/host_monitoring_idle_termination.go
units/host_termination.go

The first commit doesn't need to be reviewed, as it's a revert with hopefully a fix for repeated host termination jobs.
By adding the termination jobs to a queue in idle host jobs instead of running them immediately we will hopefully prevent duplicate jobs. Let me know if this is not how you amboy.

EVG-5979 add termination jobs to queue to avoid repeated jobs

---

service/templates/version.html

EVG-6083 add tooltip to variant names on version page

---

rest/data/aliases.go
rest/data/aliases_test.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/route/project_copy.go
rest/route/project_copy_test.go
rest/route/service.go

Add route to create a copy of a project. Only available to project admins. Copies project, variables, and aliases, and the new project is disabled.
_Note:_ some project variable things aren't tested to avoid repeated code with EVG-6189. Will rebase on that and add these tests before merging.

EVG-6188 add route to copy project

---

model/task_config.go

Verify that an error (besides "does not exist) is not given for stat (checking if stat is nil for good measure).

EVG-6212 fix panic

---

validator/project_validator.go
validator/project_validator_test.go

For context, the verifyTaskDependencies validator covers most cases relating to coverage but it doesn't case specially for "*", which is the purpose of the all dependencies validator. 
This validator should consider that you can specify all tasks per variant, and thus multiple dependencies specifying all tasks may still be valid.

EVG-5946 clarify all dependencies validator

---

public/static/js/task.js

Updated the search filter on the task page to be case insensitive, because the other filter boxes in Evergreen are case insensitive.

 EVG-6241: Make search filter for test results case insensitive

---

model/github_hook.go
model/project_ref.go
model/project_ref_test.go
model/project_vars.go
model/project_vars_test.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/route/project.go
rest/route/project_vars_test.go
service/project.go

Originally our projects patch route merely updated the document in the DB, whereas an update from the UI verifies input, creates a webhook, and enables PR testing and the commit queue.
This version of the PR has no tests, because I'm not sure the best way to test the webhooks piece of this code (which is the main consideration). Would we want to put it in staging and hit the route to verify? Or is it enough if the existing UI route proves unbroken since the logic is the same?

EVG-6190 modify patch route

---

model/repository_test.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/route/project.go
rest/route/project_test.go

I originally made a separate route for this, but actually it's such a simple change I think a "revision" query parameter to the PATCH project route should be enough.

EVG-6192 add revision parameter to PATCH projects

---

globals.go
model/host/hostutil.go
model/host/hostutil_test.go
operations/agent_monitor.go
operations/agent_monitor_test.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6167
When bootstrapping via non-legacy SSH, update host's curator binary to latest version and restart service with the new version and config.

EVG-6167: update/reinstall Jasper service via SSH

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6004
User data now gets latest Jasper CLI version and updates the config of the Jasper service on the host to reflect this.

EVG-6004: add command to update/force restart Jasper in user data script

---

config.go
operations/commit_queue.go

Clarify the name of the flag used to resume testing after adding modules.

EVG-6281: change commit queue flag name

---

public/static/app/perf/perf.js

I'm not sure that this is the entirety of the problem, but weird ordering issues with angular's $q will definitely cause the graphs to not show (and bugsnag shows occurrences of this)

EVG-6163 serialize some trend chart queries

---

model/project_parser.go
units/patch_intent.go

Although a status is sent to GitHub for project validation errors, only a generic error would be sent if the project file couldn't be unmarshaled. 
This will send the invalid project validation error to GitHub.

EVG-6093: report config unmarshal error as a GitHub status

---

model/patch/patch.go
model/patch/patch_test.go
service/api_patch.go
units/commit_queue.go
units/commit_queue_test.go

In the CLI commit queue the githashes within a patch's modules were not being updated to the latest hashes.
If a patch was merged while an item was already enqueued the second item's merge would fail since git.get_project does a hard reset to each module's githash before applying a patch.

EVG-6255: update module githashes for commit queue patches

---

model/distro/db.go
model/distro/distro.go
rest/model/distro.go
rest/route/distro_test.go
service/templates/distros.html

JIRA: https://jira.mongodb.org/browse/EVG-6282
New setting determines where the agent monitor installs the evergreen client for the agent.

EVG-6282: add distro option to set the directory where evergreen binary is downloaded

---

rest/route/project.go
rest/route/project_test.go

Tiny fix I'm throwing on my documentation ticket. In some routes we're using ProjectRefs but building APIProjects, which loses information and is inconsistent.

EVG-6228 all project routes should return projectRefs

---

units/patch_intent.go

Make it easier to help users with patch errors by logging a more detailed error.

EVG-6154: add error logging

---

model/task/task.go
model/task/task_test.go
model/version.go
public/static/js/build.js
public/static/js/version.js
service/build.go
service/models.go
service/version.go
util/time.go

The UI was miscalculating the time taken for builds and the makespan for versions.
Both of these were the result of assumptions about tasks that didn't hold for display tasks since execution tasks run in parallel so `time_taken != finish_time - start_time`.

EVG-5994: Fix time taken and makespan in UI

---

operations/commit_queue.go

The fixes in #2123 did not include the merge and set-module subcommands.

EVG-6302: make commit queue CLI respect -c option

---

public/static/js/projects.js
rest/data/interface.go
rest/data/subscription.go
rest/data/subscription_test.go
rest/route/project_copy.go
service/project.go

Current UI doesn't add subscriptions to the form data before copying project, and also doesn't change the ID (so would only update, not insert new subscriptions). This fix is verified in staging.

 EVG-6249 copy subscriptions in API route and from UI

---

model/generate.go
model/generate_test.go
model/version.go
model/version_db.go
units/generate_tasks.go

Earlier we fixed this race condition by checking that the config string we were replacing was still the most recent config for the version. Rather than relying on this string, we should use an incrementing integer to keep track of the config version.

EVG-6268 catch race conditions when saving new config using an integer

---

model/task/task.go
trigger/task_test.go

Retake on #2395.
It's _necessary_ to clear Aborted on restart (Archive) so a restarted task isn't immediately aborted.
It's _okay_ to clear Aborted on restart because any previous iterations of the task still running (that haven't done a heartbeat since it's been aborted) will exit after the task has been reset since the secret has changed and the heartbeat will return a 409.

EVG-6220: only clear aborted on restart

---

command/git_push.go
model/commitqueue/github_pr_message.go
model/commitqueue/github_pr_message_test.go
model/commitqueue/github_pr_sender.go
model/commitqueue/github_pr_sender_test.go
model/event/commit_queue_event.go
model/event/subscribers.go
model/event/subscribers_test.go
model/notification/notification.go
rest/model/subscriber.go
rest/model/subscriber_test.go
units/commit_queue.go
units/commit_queue_test.go
units/event_send_test.go

The commit queue needs to merge modules before the main repo so the manifest will be correct when it runs for the main repo.
The changes for each version of the commit queue are each in their own commit. 
The PR commit queue required an architectural change: instead of creating separate subscriptions for each PR there is one subscription for the entire item and the same message merges all the PRs. This way the merge order can be controlled.

EVG-6242: commit queue module merge order

---

public/static/js/task_admin.js

When restarting a task fails, the modify task modal is closed and the error is displayed at the top of the window as a notification. This fix has been verified in staging.

EVG-6300: hide unresponsive modal on restart task failure

---

model/task_lifecycle.go

(sorry wasn't sure what to call this branch?) The simple fix is that we should be checking that task isn't nil. The error is stemming from the NewVersionActivationJob it looks like, which doesn't seem (?) to be recently changed so I'm not sure why it's just now panicking.

Panics in prod: verify task isn't nil

---

scheduler/utilization_based_host_allocator.go
scheduler/utilization_based_host_allocator_test.go

`Distro`s can have a `PlannerSettings.MinimumHosts` greater than zero. The host allocator should be able to create these hosts if they don't exist.

EVG-6194 minimum number of hosts per distro

---

globals.go
units/commit_queue.go
units/commit_queue_test.go

Prevent pre from running before merge tasks by packaging the task in a task group by itself and not defining a pre for the task group. 
This works since a task group's pre takes precedence over the project's pre.

EVG-6257: add merge task to task group

---

model/host/db.go
units/crons.go
units/host_monitoring_idle_termination_test.go

Now I remember why I had that second sort in the aggregation for `IdleEphemeralGroupedByDistroID()`

EVG-6293 min hosts not preserved for rhel70-stitch distro

---

cloud/ec2.go
cloud/ec2_test.go
cloud/user_data.go
cloud/user_data_test.go
model/credentials/db.go
model/credentials/db_test.go
model/host/db.go
model/host/host.go
model/host/hostutil.go
model/host/hostutil_test.go
units/host_termination.go
units/host_termination_test.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6230
* Create Jasper credentials when host is first started up.
* For user data, this is before the host is spawned.
* For all others, this is in the provisioning setup host job.
* Delete Jasper credentials when host is terminated.

EVG-6230: manage Jasper credentials on host creation and deletion

---

cloud/ec2.go
cloud/user_data.go
cloud/user_data_test.go
model/credentials/db.go
model/credentials/db_test.go
model/host/db.go
model/host/host.go
model/host/hostutil.go
model/host/hostutil_test.go
units/host_termination.go
units/host_termination_test.go
units/provisioning_setup_host.go

Host termination job didn't populate the env field until after `DeleteJasperCredentials()`, which requires an environment. I moved the logic to set j.env up.

EVG-6230: manage lifetime of Jasper credentials on host creation and deletion

---

model/lifecycle.go
units/commit_queue.go

#2421 adds a commit queue merge task to a task group to avoid running pre.
However:
- MaxHosts was not set so it wasn't treated as a task group. 
- The build variant was defined with the merge task itself instead of the task group.
- The CommitQueueMerge label on tasks wasn't being propagated forward for task groups.

EVG-6257: Avoid Pre for Commit Queue Merge

---

command/git_push.go
units/commit_queue.go

Starting directory was not set correctly for merge commands.
Additionally, modules were not included in the merge buildVariant.

EVG-6359: fix CLI commit queue merge for modules

---

command/registry.go
model/generate_test.go
model/project.go
model/project_matrix.go
model/project_parser.go
model/project_parser_test.go
model/project_selector.go
model/project_selector_test.go
model/project_test.go
model/version.go
model/version_db.go
rest/data/host_create_test.go

The trick here is Params of PluginCommandConf, of type map[string]interface{}. This solution unmarshals the PluginCommandConf yaml into an intermediate structure to transform Params into a yaml string.

EVG-6269 persist parserProject

---

model/event/subscribers.go
model/event/subscriptions.go
rest/data/interface.go
rest/data/subscription.go
rest/data/subscription_test.go
rest/model/project.go
rest/route/project.go
rest/route/project_test.go
rest/route/service.go
rest/route/subscription.go
rest/route/subscription_test.go
trigger/build.go
trigger/build_test.go
trigger/commit_queue.go
trigger/common.go
trigger/host.go
trigger/host_spawn.go
trigger/host_spawn_test.go
trigger/host_test.go
trigger/patch.go
trigger/patch_test.go
trigger/payloads.go
trigger/task.go
trigger/task_test.go
trigger/version.go
trigger/version_test.go

We already had some functionality for subscriptions, but to avoid lots of repeated code there's some refactoring. Also moved revision from a query parameter to a field in the APIProjectRef.

EVG-6240 add support for subscriptions, refactor revision

---

rest/route/github.go
rest/route/github_test.go

When a PR is closed (merged or otherwise) Evergreen deactivates any undispatched tasks in patches running for the PR. If this happens to a PR at the head of a commit queue the version will never finish and the item will block the queue until it is manually removed.
This PR is to remove an item from the commit queue when the item's PR is closed.

EVG-6276: dequeue closed PRs from the commit queue

---

rest/route/project.go
rest/route/project_test.go

I forgot to return subscriptions with GET project.
Also, the PUT route (available to super users) currently upserts a project. However, this literally just modifies the project in the database and doesn't do any validation/processing, which is how PATCH used to be. I believe PUT should just insert and not modify, and if project admins want to modify they can then PATCH.

EVG-6414 return subscriptions with project and modify PUT

---

globals.go
units/host_monitoring_external_termination.go
units/host_monitoring_external_termination_test.go
units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go

Hosts that we can't deploy agents or agent monitors to are marked as terminated without checking if the reason we couldn't deploy to them was that the host had already been externally terminated. In the event this happens before the external termination monitor job runs we never find out the problem was external termination.
This PR is to check if hosts were externally terminated before decommissioning them.

EVG-6317: check hosts for external termination

---

config.go
model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/commitqueue/db.go
operations/commit_queue.go
operations/commit_queue_test.go
operations/http.go
operations/patch_util.go
rest/model/commit_queue.go
rest/model/patch.go
rest/model/patch_test.go
service/api_patch.go
units/commit_queue.go

Example PR output:
```Project: mci
Type of queue: PR
Owner: evergreen-ci
Repo: evergreen
Queue Length: 3
1:
PR # : 123
URL : https://github.com/evergreen-ci/evergreen/pull/123
Build : http://dev-evg.mongodb.com/version/my_version
Modules :
1: test_module (1234)
2:
PR # : 456
URL : https://github.com/evergreen-ci/evergreen/pull/456
```
Example CLI Output:
```Project: mci
Type of queue: CLI
Queue Length: 3
1:
ID : 5d2760467561cc2f577f7794
Created : 2019-07-11 16:13:58.845 +0000 UTC
Description : fix things
Build : http://dev-evg.mongodb.com/version/5d2760467561cc2f577f7794
Status : dispatched
Finalized : Yes
Modules :
1: test_module (1234)
```

EVG-6333 improve commit-queue list

---

model/lifecycle.go
model/project.go
model/project_test.go
model/task/db.go
model/task/sorter.go
model/task/task.go
scheduler/setup_funcs.go
scheduler/setup_funcs_test.go
scheduler/task_prioritizer.go
scheduler/task_priority_cmp_test.go

(going to write a test, in the model package of the new method on TaskGroup, but I want to run through the existing suites)

EVG-6233: store task group index in tasks

---

model/project_ref.go
model/project_vars.go
rest/data/project.go
rest/data/project_test.go
rest/model/project.go
rest/model/project_event.go
rest/route/project.go

Some things that were bad:
* Not all fields from Triggers were being converted.
* Admins and Triggers updates would over-write existing.
* No way to delete admins.
* Could un-redact private variables. (maybe you should still be able to do this via route, but not possible via front-end so?)
* PATCH returned only a partially updated document which was really confusing. To return the fully updated document involves doing everything in GET again basically, which doesn't seem necessary for every slight modification.

EVG-6446 fix patch route

---

config.go
operations/commit_queue.go

The rest client gives a 404 for the project ref route. I verified that the API client works for both /ref and /patches.

EVG-6333 use different client

---

command/registry.go
model/generate_test.go
model/project.go
model/project_matrix.go
model/project_parser.go
model/project_parser_test.go
model/project_selector.go
model/project_selector_test.go
model/version.go
model/version_db.go
rest/data/host_create_test.go

So, before I did this "clever" thing in my unmarshaller where I cased on the type of Params (if this was the first time we saw the project, Params was map[string]interface{}, but after that would be a YAML string). This wasn't safe with rollbacks and outdated agents, as the old marshaller didn't know what to do with this yaml string.
Instead, we should keep Params and ParamsYAML entirely separate, and keep them both updated. Specifically we need Params so unmarshalling from the config string works; this will be corrupted in the database. This now makes TestParserProjectPersists fail--not sure if there's a good way to make these yamls match (the messed up Params makes them different). I had an idea we could set all Params to nil when re-marshalling, but that approach seemed to require many …

EVG-6269 unmarshal params into separate fields

---

model/generate_test.go
model/project.go
model/project_parser.go

While empty params maps are omitted with the omitempty tag, it doesn't work for paramsYAML as an empty marshalled paramsYAML is some variation of "| {}". Now, if paramsYAML doesn't contain any letters, we don't load Params (and similarly, if Params is empty, we don't set paramsYAML). Unrelated, there is also some minor refactoring of resolveParams.
This was tested with the server and cloud yamls. My only concern is that isEmptyYAML may be inefficient--I wanted it to not rely on Params as we may remove this variable.
(sorry if you saw weird emails about a different pull request, I pushed to the wrong branch.)

EVG-6269 omit 'empty' yamls

---

agent/agent.go
apimodels/agent_models.go
service/api_task.go
service/api_task_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6284
* Agent sends its current revision with request to `GetNextTask` endpoint to handle agent monitor downloading the latest agent version instead of the agent deploy job.
* On non-legacy hosts, logs host event indicating new agent is deployed when the agent's request has up-to-date revision but the database host is outdated.

EVG-6284: log when a new agent version is deployed by the agent monitor

---

globals.go
model/host/host.go
model/host/hostutil.go
model/host/hostutil_test.go
service/api_task.go
units/provisioning_agent_monitor_deploy.go

JIRA:
https://jira.mongodb.org/browse/EVG-6229
https://jira.mongodb.org/browse/EVG-6238
* **EVG-6229**: If the API server does a host health check and it is not running, stop the host's agent monitor before sending response telling the agent to exit.
* **EVG-6238**: If host eventually enters the running state again. (e.g. static hosts are unquarantined), the agent monitor deploy job should automatically run because either `NeedsNewAgentMonitor` flag is set or `MaxLCTInterval` is elapsed.

EVG-6229, EVG-6238: stop agent monitor during host health checks in API server

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6504

EVG-6504: use "--flag value" command line argument format instead of "--flag=value"

---

command/git_push.go
command/git_push_test.go
command/git_test.go
rest/client/mock.go

Since modules can be (and often are) cloned within another repo, when the commit queue would `git add -A ` in the super-repo it would also add the module as a subproject.
This PR gets around this by specifying the files to add based on the patch summary stored in the patch.
Another bug fixed by this PR is that when there were only changes to the module the commit queue would nonetheless create an empty commit on the main repo. Now we check if the patch is empty before pushing a commit.

EVG-6405: extra submodule

---

model/repository_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6524
Test execution seems to depend on whether ValidProject or InvalidProject runs first.

EVG-6524: fix TestUpdateLastRevision

---

command/git_push.go
command/git_push_test.go
model/repository_test.go

Pass the commit message through stdin with the `--file -` option.
I wanted to avoid passing the message to stdin of every git command, so I split up the commands.

EVG-6473: handle arbitrary commit messages

---

units/provisioning_agent_monitor_deploy.go
units/provisioning_setup_host.go

https://jira.mongodb.org/browse/EVG-6525
* Agent monitor writes log files to same directory as agent.
* Use home dir as working directory for evergreen setup and teardown commands.
* Improve log messages.

EVG-6525: set working directories for evergreen binary processes

---

operations/commit_queue.go
operations/patch_util.go

If the `-m --message` option is provided that message will be used. Otherwise the existing commit message(s) will be used. If there is more than one commit, the commit messages are concatenated and the user is prompted to confirm.

EVG-6475: pull merge commit message from existing commits

---

public/static/app/perf/perf.js
public/static/js/filters/filters.common.js

- Previously when converting cedar data, we could have empty entries if the task had multiple execution
- Cedar didn't have a way to filter based on project before, which would cause it to return data from (for example) the 4.2 branch when viewing a sys-perf task

EVG-6365 fix data formatting issue, filter on project in perf plugin

---

operations/agent_monitor.go

JIRA: https://jira.mongodb.org/browse/EVG-6535

EVG-6535: agent monitor should only listen on loopback address

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6511
All the bash commands that use ~ for home directory (for the legacy and non-legacy host provisioning paths) now depend on `Distro.User` being set to find the home directory.

EVG-6511: use distro-based home directory instead of '~' for all commands

---

units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6557
If the agent monitor is successfully started by user data, the app server shouldn't need to RPC into the host to start an agent monitor.

EVG-6557: update the LCT for a host bootstrapped with user data during provisioning

---

model/host/hostutil.go

JIRA: https://jira.mongodb.org/browse/EVG-6558
If we don't do this, the dial blocks until the caller's context (e.g. agent monitor deploy job context) cancels.

EVG-6558: explicitly set timeout on dialing into Jasper service

---

model/commitqueue/db.go

Checking the queue is unchanged is unnecessary since $push is an atomic operation.

EVG-6520: remove check for unchanged queue

---

model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
rest/data/commit_queue_test.go
units/commit_queue.go

#2501 introduced a panic if an item is removed from the commit queue while the commit queue is processing. If the queue is processing `head := queue.Next()` returned nil, so
https://github.com/evergreen-ci/evergreen/blob/492da7edcc398ed23a87da9785dbcb3d02afae49/rest/data/commit_queue.go#L87
panicked.

EVG-6472: return next even if processing

---

model/host/db.go
model/host/host_test.go
model/validate.go
model/validate_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6546
If the host ID given in the agent request doesn't match a host ID in the database (because it was given the intent host ID when started through user data), try to match it against `Host.JasperCredentialsID`.

EVG-6546: API server should accept host ID if it matches Jasper credentials ID

---

operations/fetch.go
operations/fetch_test.go

We still need to truncate filenames (see EVG-5649) but we should not truncate file extensions, because then users cannot download the files without renaming.

EVG-6327 truncate filenames without modifying extensions

---

model/lifecycle.go
model/project.go
model/project_aliases.go
model/project_aliases_test.go
model/project_test.go
operations/list.go
public/static/js/projects.js
repotracker/repotracker.go
rest/model/project_event.go
rest/model/project_event_test.go
rest/model/string.go
service/templates/projects.html

New alias rule: valid if (a task regex XOR a task tag) AND (a variant regex XOR a variant tag)
Also involves a UI change to add variant tags.

EVG-6309 support variant tags in aliases

---

public/static/js/settings.js

This piece of code has been modified so that it only sends formatted feedback if the opt in box was checked initially, but was not checked at the time the user hit "save."

EVG-6555: fix feedback submission on patch page opt in

---

operations/commit_queue.go

This is the same message used for patches.

EVG-6361 confirm success for commit-queue set-module

---

cloud/ec2.go
cloud/ec2_test.go

Many times when trying to tag a spot instance request (sir) right after creating it AWS returns an error that the sir doesn't exist. Since retry logic is built into the AWS client tagging eventually succeeds, but API calls are wasted.
The problem seems to be that the AWS API is only [eventually consistent](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency).
Since tagging sirs isn't really necessary as long as the instance that gets created for them is tagged (tags on sirs don't propagate to the instances that get created for them) this PR is to stop tagging them.

EVG-6502: stop tagging spot instance requests

---

service/patch.go
service/templates/patch_version.html

I'm not sure if there's an intelligent way to know if an item is paused--only a CLI item can be paused, so we should error if the item isn't found for other cq types (assuming that other types could ever have patch pages). Otherwise print a message that it could be paused. The front end component needs to be verified in staging.

EVG-6427 consider paused cq items on patch page

---

model/project_ref.go
model/project_ref_test.go
rest/data/commit_queue.go
rest/data/commit_queue_test.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/route/github.go
rest/route/github_test.go
service/project.go

Commit queue item doesn't necessarily exist, so we should only return an error if there's a database error or if there's an actual issue removing an item that exists.
(Note: slightly awkward error hardcoding. Alternatively we could store these errors as constants, or not have TryDequeue return an error when there's an issue removing an existing item, although that feels overly simplistic)

EVG-6530 do not error in webhook if cq item/projectRef not found

---

model/build/db.go
model/task/db.go
model/version_db.go
rest/data/interface.go
service/rest_version.go
service/rest_version_test.go

Currently, the v1 endpoint to get recent versions returns tasks by build using the task cache. This change gives dependable task data (since apparently the task cache is buggy), and allows for pagination.
Note the ticket description for this isn't right, the solution described isn't what cloud needed.
Has been tested in staging.

EVG-6206 use task db in v1 getRecentVersions

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
cloud/ec2_integration_test.go
cloud/ec2_price.go
cloud/ec2_test.go
cloud/ec2_util.go
model/host/db.go
model/host/host.go
model/host/host_test.go

- The most common API call is `DescribeInstances`. Cache the response for a batch of instances and remove multiple calls for each individual instance. Also move tagging to `OnUp` for on-demand hosts and Fleet spot hosts so we can avoid making a call for each on-demand/Fleet host and be consistent about when we tag instances (spot instances are tagged `OnUp`).
- In second place is `DescribeSpotInstanceRequests`. Previously we would call this repeatedly until Spot instances transitioned to running. Now, once a spot instance request has been fulfilled cache the instance id and stop making this call.

EVG-6547: reduce AWS API calls

---

command/results_gotest.go
command/results_xunit.go
command/results_xunit_test.go
command/testdata/xunit/junit_12.xml
util/file.go

FYI the function in results_gotest.go doesn't _have_ to call the function in results_xunit if that's bad organization, just didn't want to copy code. Also if you believe in test driven development (#controversial) the original code does fail the new test.

EVG-6114 support gitignore style globbing

---

command/git_push.go
command/git_push_test.go

Because git.get_project applies changes to the index (with the `--index` option) it's not necessary to run `git add` in git.push. Additionally, `git add` returns an error on removed files that have already been added to the index and the merge task aborts.

EVG-6596: remove `git add` from git.push

---

model/task_queue.go
model/task_queue_service_dependency.go
scheduler/task_queue_persister.go

We've been populating the order of a task in a task group for a while in order to make sure that the order of tasks are correct.

EVG-6539: sort dispatchable task group tasks in the dag scheduler

---

command/results_gotest.go
command/results_xunit.go
command/results_xunit_test.go
command/testdata/xunit/junit_12.xml
util/file.go

Only the second commit needs to be looked at. This change was using the wrong working directory, and shouldn't join it with the filepath before running util.BuildFileList. This change passes the smoke tests in a patch.

EVG 6114 fix workdir for git-ignore style globbing

---

model/project_ref.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/route/project.go
rest/route/service.go

Previously we showed public projects to non-authed users in the rest v2 API.
However, triggers should probably not be visible, since they can reference
private projects. Instead of handling this in the APIProjectRef struct, which is
used by other projects, I opted for making the list projects endpoint private,
since there's no reason for non-authed users to use this endpoint.

EVG-1732 Add auth to list projects endpoint

---

cloud/ec2_util.go
cloud/spawn.go
model/host/db.go
model/host/host.go
model/host/host_intent.go
operations/host_spawn.go
operations/host_test.go
rest/client/interface.go
rest/client/mock.go
rest/client/rest.go
rest/data/host.go
rest/data/host_test.go
rest/data/interface.go
rest/model/host.go
rest/route/host_spawn.go
rest/route/host_spawn_test.go
service/api_spawn.go
service/spawn.go

Made changes that allow users to add for AWS instances from the commandline using the following syntax:
evergreen host create -t key1=value1 -t key2=value2 [arguments...]
The are then stored in a map[string]string in a new InstanceTags field in the host document. I changed the makeTags(host) function in ec2_util.go to add these tags to the AWSClient.
Would appreciate feedback on how I could test my changes behind putting this in staging and seeing if tags entered through the commandline end up in host documents.

EVG-6618 Support tags for spawn hosts

---

model/task/task.go
model/task/task_test.go

If more than one dependency is blocked by a task we're only updating the first and then returning.

EVG-5960 fix UpdateBlockedDependencies

---

model/patch_lifecycle.go
model/patch_lifecycle_test.go
model/project_parser.go
model/project_parser_test.go
service/api_patch.go
units/commit_queue.go
units/patch_intent.go

Some investigation has uncovered that 
1) execution tasks are destructively modified for parser projects, and
2) we store the expanded project in patches (and subsequent versions), where we should store just the parser project in the yaml.

EVG-6641 store untranslated projects for versions/patches

---

command/generate.go
command/util_test.go
model/task/db.go
model/task/task.go
rest/data/generate.go
rest/data/generate_test.go
rest/route/task_generate_test.go
units/crons.go
units/crons_remote_fifteen_second.go
units/generate_tasks.go
units/generate_tasks_test.go

This removes retries from the generate.tasks job in favor of a background job that populates generate.tasks jobs based on a query. The query looks for tasks that contain a generate.tasks command and that are running. It creates a generate.tasks job for each of those. If any those jobs fail due to a race, they will not error. A new job will be created to try again 15 seconds later.

EVG-6517 Support generate.tasks across deploys

---

model/generate.go
model/project_parser.go
model/project_parser_test.go
model/task/task.go
model/task/task_test.go
model/version.go
model/version_test.go

- #2404 was supposed to allow a commit queue merge to depend on generated tasks, but they weren't being added as dependencies because we were checking if the generating task was the actual merge task as opposed to checking that it's in a commit queue patch.
- The way dependencies were supposed to have been added would have rebuilt the merge task's dependencies array, wiping out the cached blocked status. 
- The merge task's CommitQueueMerge field wasn't being set because it was not plumbed through the project parsing. This field is still used elsewhere.

EVG-6426 generated tasks for commit queue patches

---

util/subtree_linux.go

Check whether all processes have successfully exited after kill is called, and adds to the log for each process that is not cleaned up after a certain amount of time. Uses util.Retry so that the program can continue quickly in most cases where processes immediately exit. 
If anyone has opinions about the timeout constants, I'd love to hear them.

EVG-6437 Log if a process is not cleaned up between tasks

---

globals.go
model/build/build.go
model/build/build_test.go
model/lifecycle.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
scheduler/task_finder.go
scheduler/task_finder_test.go
service/task.go

The second of two PRs (first was #2591) to add cached dependency status to tasks.
This PR uses the cached status to determine if a task is blocked.

EVG-5960: use the unattainable field to determine if a task is blocked

---

operations/service.go
units/crons_remote_minute.go

This pull request just moves provisioning create host jobs to their own queue so other jobs don't get blocked behind them. Sam walked me through most of these simple changes.

EVG-6666 Put provisioning-create-host in its own queue

---

model/context.go
model/project.go
model/project_ref.go
model/project_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
model/task_queue.go
model/task_queue_test.go
model/testutil/api.go
model/testutil/integration_test_setup.go
operations/cli_integration_test.go
repotracker/repotracker.go
rest/model/project.go
rest/route/project.go
rest/route/project_test.go
service/api.go
service/api_patch.go
service/rest_project_test.go
service/task_history.go
service/ui_plugin_perfdash.go
validator/project_validator_test.go

This refactors finding a project into 2 separate functions. If a version is
available, use the config from that version. Otherwise, find the latest good
version. That is, where previously we had called model.FindProject("", ref), use
model.FindLastKnownGoodProject(ref), and where we had previously called
model.FindProject, call model.FindProjectFromTask, call
model.FindProjectFromVersionID(t.Version).
This also removes LocalConfig as a concept completely, since this is not used in
code, only in tests.

EVG-6649 Use config from version if available

---

public/static/app/perf/perf.js

Fixed a problem caused by EVG-6420 where if a data set has all 0 values for the lowest thread count, we think that it has no data at all and don't draw the graph. I verified that this doesn't re-break EVG-6420

EVG-6638 display trend graphs where a thread level has 0 values

---

makefile
model/credentials/credentials_test.go
self-tests.yml

JIRA: https://jira.mongodb.org/browse/EVG-6736
* Add test-model-credentials.
* Increase test timeout for slow hosts.

EVG-6736: add test-model-credentials task

---

model/distro/distro.go
model/host/db.go
model/host/host.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6738
* Host termination find query checks for user data hosts that haven't provisioned within the cutoff.
* Prevent setup host job from retrying once and immediately no-oping for user data provisioning.
* I can't spell "communication".

EVG-6738: ensure hosts provisioned with user data that fail to start agent are terminated

---

command/git.go
command/git_test.go
command/manifest.go

- Teach git.get_project about the module expansions manifest.load sets
- Add the module githash specified by the manifest to git.get_project's checks (so that users don't need to add it as a param to git.get_project anymore)
- Add logging of what module ref we're using and why

EVG-6679 better integration of manifest and git.get_project

---

cloud/cloud.go
cloud/cloud_test.go
cloud/docker_test.go
cloud/gce_test.go
cloud/openstack_test.go
cloud/vsphere_test.go
globals.go
model/host/stats_test.go
model/scheduler_stats_test.go
scheduler/deficit_based_host_allocator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6744
None of the distros use this setting anymore.

EVG-6744: remove legacy EC2 provider name

---

units/generate_tasks.go

It's possible for a config error to be returned if another job has called
g.Save(). In that case, we should not return the error. This case is equivalent
to g.Save() returning mongo.ErrNoDocuments and should therefore return the same
value.

EVG-6517 Do not return config error if another job has run

---

model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/commitqueue/db.go
units/commit_queue.go

This adds a EnqueueTime field to each commit queue item that is set when the item is added to the queue. The commitQueueJob now logs how long an item had been waiting in the queue (at the time it is popped), in addition to the current length of the commit queue.

EVG-6682 Track commit queue length and item wait time

---

service/templates/distros.html

* `distro.planner_settings.minimum_hosts` should be Planner agnostic.  
* We use this lower bound when decided the number of idle hosts of a given distro that should be considered for termination; this is not Planner dependent.

EVG-6580: it's not possible to set min hosts in the UI unless a distro is set to tunable

---

operations/service.go
units/crons_remote_hour.go

This makes an hourly cron and adds the cache historical test data and the jasper
deploy jobs to it. We currently have a fifteen-minute but nothing on an hourly
cadence.

EVG-6751 Make hourly cron

---

units/generate_tasks.go
units/generate_tasks_test.go

If a task is aborted or timed out, there may still be generate jobs in the
queue. However, they should not run. In the former case, the user has indicated
that they don't want them to run by aborting the task. In the latter case, if
the generated tasks end up in a display task with the generator, then that task
will be purple or red even if all the generated tasks succeed. The user may
restart this task, causing not just the generator, but all the other tasks to
reexecute.

EVG-6517 Don't generate tasks if the generator is not running

---

model/task/task.go
model/task/task_test.go

The loop was ending on the first iteration so only one blocked dependency was actually cleared every time the task was reset.

EVG-6755 reset all blocked tasks

---

model/task/db.go
model/task/task_test.go

Although overriding dependencies makes all dependencies satisfied, blocked tasks were not up for consideration by the scheduler since they were excluded by the scheduleableTasksQuery.

EVG-6745 allow override deps for blocked tasks

---

model/task_lifecycle.go
model/task_lifecycle_test.go

If a task has override dependencies set there's no reason to activate its dependencies when it's activated.

EVG-6354 don't activate dependencies for tasks with OverrideDependencies set

---

cloud/ec2.go
cloud/ec2_util.go

Adds validation to GetInstanceStatuses that ensures that the response from m.client.DescribeInstances is properly formed. Should prevent panics.
See https://jira.mongodb.org/browse/EVG-6669 for the problem.

EVG-6669 Handle malformed AWS DescribeInstances response

---

model/lifecycle.go
repotracker/repotracker.go
scripts/indexes.js

- Create a copy of the function that creates builds/tasks, but does not insert them
- Have the existing function wrap the copy above
- Change the repotracker to hold all the builds/tasks/version it needs to create for a version in memory, then insert them at the end in a transaction

EVG-6779 don't do reads within repotracker transaction

---

model/distro/distro.go

This addresses https://jira.mongodb.org/browse/EVG-6173.
It seemed like the container pool in which ubuntu1604-test hosts are spawned was maxing out at 8 hosts, even though it seemed like archlinux-parent's PoolSize (reflected in the UI as "Maximum number of hosts allowed:") was set at 10.
However, this isn't really a bug. PoolSize is not related to container pools -- it's the max number of running hosts allowed with a certain distro at a time. The number of containers spawned on a parent host is determined by the MaxContainers field of the container pool specified by the container distro (confusing, I know). This is set in the admin config, not the distro document. In our case, MaxContainers is correctly set to 8.
No changes made except adding a clarifying comment to the distro PoolSize …

EVG-6173 Add comment explaining distro pool size

---

public/static/js/patches.js
service/models.go
service/templates/patches.html
service/timeline.go

The new and old patches pages load a lot of unnecessary data which causes slow load times for users with large builds. This PR is to pass only the required data.
Goes with https://github.com/evergreen-ci/spruce/pull/24 and https://github.com/evergreen-ci/evergreen.js/pull/10

EVG-6568 load only necessary data

---

model/patch_lifecycle.go
units/commit_queue.go
units/commit_queue_test.go

The commit queue was not actually updating the project config with HEAD's since the project was updated before the githash of the patch was updated.

EVG-6791 refresh cached project config

---

model/generate.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
repotracker/repotracker.go
service/patch.go
validator/project_validator.go
validator/project_validator_test.go

Discard a build created without any tasks (such as if all tasks are patch_only and it's a mainline build, or all tasks are not patchable and it's a patch build).

EVG-6034 skip taskless builds

---

model/host/host.go
model/host/hostutil.go
service/api_task.go
service/api_task_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6793
The agent might start and set the host as running before the provisioning setup host job has run successfully (this can cause a host to be terminated since the app server didn't finish provisoining). The Provisioned key will be set once the host has run the setup host job.

EVG-6793: no-op the agent until the app server is done provisioning

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_integration_test.go
cloud/ec2_test.go
cloud/mock.go
cloud/spawn.go
model/host/host.go
model/host/host_intent.go
model/host/host_test.go
operations/before.go
operations/host_spawn.go
rest/client/mock.go
rest/data/host.go
rest/data/host_test.go
rest/model/host.go
rest/route/host.go
rest/route/host_spawn.go
rest/route/host_spawn_test.go
rest/route/service_test.go
service/api_spawn.go
service/spawn.go
units/spawnhost_modify.go
units/spawnhost_modify_test.go

**Waiting on EVG-6627 (start/stop hosts) because instance type can only be modified on stopped hosts.**
EC2 hosts are normally spawned with the instance type specified in the distro's provider settings. These changes allow users to override this by specifying an instance type when creating a spawn host:
> evergreen host create --type <INSTANCE_TYPE>
Users can also change the instance type of an existing stopped host:
> evergreen host modify --host <HOST_ID> --type <INSTANCE_TYPE>

EVG-6624 Modify instance type for spawn hosts

---

makefile

JIRA: https://jira.mongodb.org/browse/EVG-6805
This is mostly because I don't want to see the useless cygpath usage text in the task logs.

EVG-6805: only invoke cygpath if gopath is defined

---

model/host/host.go
units/provisioning_create_host.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6789
This fixes two problems:
1. Occasionally, multiple create host jobs run concurrently and spawn multiple hosts for a single intent document. I fixed this by atomically updating the host status from initializing to building (like what's currently done for the agent deploy job).
2. If the create host job successfully spawns a host but fails afterwards because it can't replace the intent host document with the real host document, terminate the cloud instance immediately.
Note on problem 2: instead of terminating as soon as the job fails, it's possible that we could try requeueing the create host job and reuse the already-spawned instance ID. However, this runs the risk of not having enough information to terminate the cloud instance since the …

EVG-6789: create host job can leak hosts

---

model/generate.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/patch_lifecycle_test.go
repotracker/repotracker.go
service/patch.go
validator/project_validator.go
validator/project_validator_test.go

#2719 caused large patches to not be able to be finalized since the context used when inserting tasks had been canceled. The problem was a context with a timeout being reused to insert tasks.
This PR is to reintroduce the reverted changes from #2719 and fix the bug. The new commits start from ac24d43.

EVG-6034 taskless builds

---

model/host/hostutil.go
model/host/hostutil_test.go
units/jasper_deploy.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6790

EVG-6790: set splunk token for Jasper as a file instead of string flag

---

service/spawn.go

When a user updates the expiration of a spawn host using the Evergreen UI, the confirmation message now shows the updated expiration time in the user's own timezone specified by their user settings. The message defaults to UTC if the timezone field is improperly set for whatever reason.

EVG-6786 Display updated expiration time in client time zone

---

model/distro/db.go
model/distro/distro.go
model/host/hostutil.go
model/host/hostutil_test.go
operations/agent_monitor.go
public/static/js/distros.js
rest/model/distro.go
rest/model/distro_test.go
rest/route/distro_test.go
service/templates/distros.html
validator/distro_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6808
`~/.bash_profile` sets some environment variables and ulimits expected by certain tasks.
1. The environment variables can be acquired just by running the agent within a login shell.
2. Ulimits can't exceed the limits of the spawning process and systemd processes don't obey the configuration in `/etc/security/limits.conf`. Since the Jasper service will run at different (often lower) ulimits by default than needed by the agent, we have to manually set limits in the service file. These can be set from the distro settings.

EVG-6808: run agent with bash login setup

---

auth/auth.go
auth/github.go
config_ui.go
glide.lock
rest/model/admin.go
service/templates/admin.html
service/ui.go
vendor/github.com/evergreen-ci/gimlet/middleware_auth_user.go

- Allow configuration of the domain of the login cookie
- Fix an unrelated bug where the patch UI routes don't send CORS headers if not authenticated (no functional difference, but you get a less weird error)

EVG-6456 allow specifying login domain

---

service/timeline.go

Fixes issue where Evergreen was trying to dereference a project pointer for an error message in the case where the project was nil. Now it just gets the project ref ahead of time (which is just cached in the context) to be able to access the identifier even if GetProject fails!

EVG-6782 Don't dereference a nil project

---

util/subtree_linux.go

Noticed while looking into an unrelated patch failure:
```
[2019/10/03 16:36:38.649] cleaning up processes for task: motor_main__ssl~nossl_tox_env~synchro_os~ubuntu_test_4.2_replica_set_patch_a88316b8fd06bfca05503d98a24e424ffd69f623_5d96820961837d0adbcb0b01_19_10_03_23_19_45
[2019/10/03 16:36:38.650] Killed process 4000
[2019/10/03 16:36:38.650] Killed process 4097
[2019/10/03 16:36:38.650] Killed process 4321
[2019/10/03 16:36:38.650] Killed process 4322
[2019/10/03 16:36:38.650] Killed process 4323
[2019/10/03 16:36:38.652] Failed to clean up process &d%!(EXTRA int=0)
[2019/10/03 16:36:38.652] Failed to clean up process &d%!(EXTRA int=1)
[2019/10/03 16:36:38.652] Failed to clean up process &d%!(EXTRA int=2)
[2019/10/03 16:36:38.652] Failed to clean up process &d%!(EXTRA int=3) …
```

Fix log when process is not cleaned up

---

cloud/spawn.go
globals.go
model/distro/db.go
model/distro/distro.go
model/host/hostutil.go
operations/host_setup.go
rest/data/host_create.go
rest/model/distro.go
rest/route/distro_test.go
service/templates/distros.html
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6815
* SCP and run the setup script depending on the contents of the header line (e.g. `#!/bin/bash` or `#!/usr/bin/env powershell`).
* PowerShell requires that scripts have the .ps1 extension instead of .sh.
* Spawn hosts need to edit setup script to copy SSH keys so PowerShell needs to know the path to the Cygwin file system (`BootstrapSettings.RootDir`).

EVG-6815: run setup script as either shell or powershell

---

units/crons.go

Since the counter wasn't being incremented the limit wasn't being enforced.
Also, continue to create spawn hosts even after hitting the limit.

EVG-6828 limit host requests to 16 at a time

---

model/task_lifecycle.go

I couldn't figure out what was happening exactly, but some scenario was incorrectly marking a build failed, and this is the only spot that it could be

EVG-6486 stricter check for a build failing

---

service/timeline.go

Add a field needed for https://github.com/evergreen-ci/spruce/pull/23
Also goes with https://github.com/evergreen-ci/evergreen.js/pull/11

EVG-6583 add alias to PatchInfo

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_util.go
cloud/mock.go
cloud/spawn.go
model/host/db.go
model/host/host.go
model/host/host_intent.go
model/host/host_test.go
operations/flags.go
operations/host_spawn.go
public/static/js/spawned_hosts.js
rest/data/host.go
rest/model/host.go
rest/route/host.go
rest/route/host_spawn.go
units/crons.go
units/crons_remote_hour.go
units/spawnhost_expiration_check.go
units/spawnhost_expiration_check_test.go

This PR adds a bunch of ways to configure the expiration time of spawn hosts, specifically allowing for spawn hosts that never expire. Here are the new things you can do!
To make a spawn host stick around indefinitely
> evergreen host modify --host ID --no-expire
The same option is available when creating spawn hosts
> evergreen host create --key KEY --distro DISTRO --no-expire
To make it a normal spawn host again that expires in 24 hours (not sure how often this will be used because you'd probably just terminate it)
> evergreen host modify --host ID --expire
To extend a host's expiration time (already exists in UI, not in CLI)
> evergreen host modify --host ID --extend HOURS
Essentially, a host that never expires has a new NoExpiration field set as true and has its ExpirationTime field …

EVG-6616 Make expiration for spawn hosts configurable

---

cloud/cloud_host.go
cloud/spawn.go
public/static/js/services/rest.js
public/static/js/spawned_hosts.js
public/static/partials/user_host_details.html
rest/model/host.go
service/spawn.go
service/ui.go

This pull request adds a drop down menu under where you can configure spawn host expiration time that allows you to select a new instance type for your spawn host. It populates the list of instance types from the admin settings (which allow you to whitelist instance types on a per-provider basis). You'll get an error banner if you try to change the instance type of a host that isn't stopped.

EVG-6625 Display modify instance type for spawn hosts

---

globals.go
model/build/build_test.go
model/stats/db.go
model/task/results.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle.go
model/task_lifecycle_test.go
rest/data/version_test.go
trigger/task.go
trigger/task_jira.go
trigger/task_jira_test.go
trigger/task_test.go
units/task_monitor_execution_timeout.go

Since system unresponsive and stranded tasks are always an Evergreen problem, it's incorrect for them to trigger build break and regression notifications.
Additionally, notifications for these events are annoying since the tasks are automatically restarted.

EVG-6668 prevent notifications for system unresponsive and stranded tasks

---

config.go
operations/cli_integration_test.go
operations/flags.go
operations/http.go
operations/patch.go
operations/patch_util.go
service/api_patch.go
util/slice.go
util/slice_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6823
Somebody asked for the `--task` behavior to be the same as the `--variant` behavior, so this should do  that. For some reason, the variants are joined into a string on the client side, then split again on the server side, which allows specifying variants as a comma-separated list.
This change permits that behavior for tasks as well, but it also requires that all users update their evergreen binary, or else they will send the wrong payload (variants will be a string instead of string slice) to the server.

EVG-6823: specify tasks in the same way as variants for patches

---

model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/event/subscriptions_test.go
model/lifecycle.go
model/lifecycle_test.go
public/static/js/build_admin.js
public/static/js/task_admin.js
public/static/js/version_admin.js
rest/data/commit_queue.go
rest/data/commit_queue_test.go
service/build.go
service/task.go
service/version.go

Most of this PR is moving "remove from commit queue" code from rest/data to model for use in service.

EVG-6773 remove unscheduled versions from commit queue

---

auth/user.go
glide.lock
globals.go
model/build/db.go
model/patch/db.go
model/task/db.go
model/user/user.go
model/user/user_test.go
model/version_db.go
rest/route/middleware.go
rest/route/service.go
service/api.go
service/ui.go
thirdparty/github_models.go
util/strings.go
util/strings_test.go
vendor/github.com/evergreen-ci/gimlet/acl/roles_test.go
vendor/github.com/evergreen-ci/gimlet/auth_interfaces.go
vendor/github.com/evergreen-ci/gimlet/auth_mock_test.go
vendor/github.com/evergreen-ci/gimlet/auth_user_basic.go
vendor/github.com/evergreen-ci/gimlet/ldap/ldap_test.go
vendor/github.com/evergreen-ci/gimlet/middleware_auth.go
vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager.go
vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager_test.go
vendor/github.com/evergreen-ci/gimlet/user_service_basic.go

To keep this short, adding this to all routes and an integration test will be in the next PR
- Create a middleware helper that takes various API variables and extracts the correct project scope
- Add the permission middleware to 1 route in each of the 3 API apps

EVG-6376 enforce project permissions in some routes

---

model/generate_test.go
model/patch_dependencies.go
model/patch_lifecycle_test.go

Our current dependencies checker didn't consider that the given task itself could be a task group, which caused FindTaskForVariant to return nil. Instead we want FindTaskForVariant (and subsequent work) to be called on each task for the group.

EVG-6739 recurse on task groups for patch dependencies

---

model/notification/db.go
model/notification/notification_test.go
units/event_metajob.go
units/event_metajob_test.go
units/event_send.go

If the `event_metajob` dropped a notification after marking the event as processed the notification was never sent.
Adding a step to the `event_metajob` to catch dropped notifications will make sure all notifications that make it to the database are sent.

EVG-6827 catch unprocessed notifications

---

cloud/spawn.go
cloud/user_data.go
cloud/user_data_test.go
model/host/hostutil.go
model/host/hostutil_test.go
units/provisioning_user_data_done.go
units/provisioning_user_data_done_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6865
* Windows user data can run tasks.
* Write setup script to file and run using `evergreen host setup`. For some reason, user data still mysteriously hangs while running scripts containing long lines, but `evergreen host setup` (which logically does the same thing) doesn't have this problem. I dunno.

EVG-6865: support Windows user data

---

auth/auth.go
config_ui.go
rest/model/admin.go
service/user.go

This adds a configuration setting that will expire the login cookie for a specific domain upon login. It's intentionally not added to the UI since it really shouldn't be used (and maybe should be removed in the future)

EVG-6877 add setting to expire login token

---

cloud/user_data.go
cloud/user_data_test.go
model/host/hostutil.go
model/host/hostutil_test.go
units/provisioning_user_data_done_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6884
`evergreen host setup` is only run on Windows. All other distros have the risk that root's umask will prevent the working directory from having the necessary permissions.

EVG-6884: only run evergreen host setup command on Windows

---

model/event/host_event_agent_deploy.go
units/host_monitoring_external_termination.go
units/task_monitor_execution_timeout.go
units/task_monitor_execution_timeout_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6892
This fixes an issue where a spot host was reclaimed by AWS and it did not run the external termination detection job due to a race, which caused lots of failed agent monitor deploys to a host that was terminated in AWS but the app server thought was running.
The running task was cleared by the task execution timeout job without verifying if the host was still alive. Since the LCT had elapsed and the host had no running task, the app server attempted to deploy the agent monitor (which updates the LCT) before it could check for external termination. Both are populated depending on the LCT.
* Manually check for an externally terminated host before the task is cleared.
* Fix an issue where the agent monitor deploy job wouldn't terminate a host …

EVG-6892: check for external termination when checking timed out task

---

thirdparty/github.go
thirdparty/github_test.go

The `TestGetGithubPullRequestDiff` test has been intermittently broken on Evergreen's waterfall. The test had been relying on the diff being a set number of characters, but sometimes the commit SHA is abbreviated with 9 digits and sometimes with 10 (only recently with 10).
```
$ diff attempt1.txt attempt2.txt
2c2
< index c661de2f91..f188a4d7ac 100644
---
> index c661de2f9..f188a4d7a 100644
28c28
< index 27186d2dcc..216f7a099e 100644
---
> index 27186d2dc..216f7a099 100644
```
Also took the opportunity to use go-github for getting the diff.

EVG-6894 fix TestGetGithubPullRequestDiff

---

units/generate_tasks.go

EVG-6517 handled the case where CheckProjectConfigurationIsValid errored as a
result of another generate.tasks job having updated the version document. This
might also happen in g.NewVersion() as well, since there is a validation check
there.
This change refactors the error handling code into its own function and calls it
in both places.

EVG-6885 Handle additional race case in generate.tasks

---

units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go
units/task_monitor_execution_timeout.go
units/task_monitor_execution_timeout_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6859
* If the agent deploy failed while curling the agent binary over SSH, don't wait until MaxLCT (5 mins) to elapse before attempting redeploy.
* This might increase the provisioning error rate if the hosts are really slow at starting up sshd since it will try the agent deploy job more often.
* Agent monitor deploy job now decommissions host if setup script fails.

EVG-6859: retry agent deploy job without waiting for MaxLCT to elapse

---

cloud/cloud.go
cloud/cloud_host.go
cloud/docker.go
cloud/docker_test.go
cloud/ec2.go
cloud/ec2_fleet.go
cloud/gce.go
cloud/gce_test.go
cloud/mock.go
cloud/openstack.go
cloud/openstack_test.go
cloud/spawn.go
cloud/static.go
cloud/vsphere.go
cloud/vsphere_test.go
model/host/hostutil.go
rest/route/host_test.go
units/host_execute.go
units/host_termination.go
units/jasper_deploy.go
units/provisioning_agent_deploy.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-6903
Use `host.Host.GetSSHOptions()` instead since all the GetSSHOptions implementations were identical anyways.

EVG-6903: remove cloud manager GetSSHOptions

---

cloud/ec2_fleet.go
cloud/ec2_util.go

JIRA: https://jira.mongodb.org/browse/EVG-6892
The only field that the fleet manager actually needs in `(*ec2FleetManager).GetInstanceStatus()` to return a value is `(*ec2.Instance).State.Name`. Other fields in the response from `(*awsClientImpl).GetInstanceInfo()` (such as PublicDnsName) are not guaranteed to be populated, especially if the host is already terminated on the AWS side. Furthermore, these fields are only needed for caching host data, so don't require validation of optional AWS response fields and only warn if caching fails in `(*ec2FleetManager).GetInstanceStatus()`.

EVG-6892: do not require caching to succeed in order to call GetInstanceStatus

---

service/task_history.go
service/task_history_test.go

Add a secondary sort on revision for versions with equal create time.
In the process, simplify the logic by consolidating the concurrent and consecutive queries into a single query.
Will need to discuss how the new query uses the index.

EVG-6022 correct the ordering of concurrent versions

---

model/lifecycle.go
model/task_lifecycle.go

I'm not sure what exactly is the cause of the errors still, but this removes a place when we're unnecessarily reading our own write

EVG-6764 simplify updating cache in generate.tasks

---

cloud/ec2.go
cloud/ec2_test.go
cloud/ec2_util.go
model/host/db.go
rest/route/host_spawn.go

Each volume must have a unique device name, which is recommended to be of the form `/dev/sd[f-p[1-6]`. This generates a device name if the device name isn't specified, and uses a device name assuming no other currently attached volume has that device name.

EVG-6619 generate device name before attaching volume

---

config_jira_notifications.go
config_test.go
public/static/js/admin.js
rest/model/admin.go
rest/model/admin_test.go
service/templates/admin.html
trigger/task_jira.go
trigger/task_jira_test.go

Since components and labels are sent to JIRA as lists they can't be specified with the existing custom JIRA fields admin setting because that will just send JIRA a string. Allow an admin to specify components and labels for JIRA issues as comma separated lists.
Move some conversion logic into the rest model.

EVG-6888 pipe through components and labels for JIRA issues

---

scheduler/task_priority_cmp.go
scheduler/task_priority_cmp_test.go

In https://github.com/evergreen-ci/evergreen/commit/60788eca2454682f882ae00e4e9b4659d651e119, we started using the cached task group order instead of parsing the yaml in order to determine the order of task groups. This introduced a regression. In the case where two task groups have different build IDs, they should be sorted according to how they were originally sorted, i.e., in groupTaskGroups.

EVG-6901 Fix task group order regression

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_test.go
cloud/ec2_util.go
model/host/db.go

JIRA: https://jira.mongodb.org/browse/EVG-6912
* Several cloud tests were expecting fields when caching host data that were not set in the mock AWS client.
* Also fix some `TestAttachVolumes` types.
* Fix `TestOnUp` due to bug where host volumes would be set on in-memory host but would not be persisted to the database the first time the host's volumes are retrieved. (Can someone verify that this is actually what we want to do?)

EVG-6912: fix EBS volume tests

---

model/build/build.go
model/build/build_test.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/task/sorter.go
model/task/task_test.go
repotracker/repotracker.go

Scheduling a large patch was taking a long time. Tracked down the two biggest culprits to
1. For each task in each build we were making a query to get the `create_time`
2. We were inserting builds and tasks once for each build.
As an aside, tasks' bulk inserter wasn't doing unordered inserts.

EVG-6014 streamline patch finalization

---

units/commit_queue.go
units/commit_queue_test.go

TL;DR Tiny change == big impact
CLI commit queue items define build variants/tasks at the time of insertion into the queue, rather than at the HEAD of the queue, so if the commit queue alias is changed we don't just run those tasks.
Turns out we do already re-generate tasks at the time of creating the version (to add the merge task correctly), but we append to the existing ones. So we just need to null out tasks/build variants before creating the merge task.

EVG-6743 refresh commit-queue patch tasks when creating version

---

service/task_history.go
service/task_history_test.go

#2812 added a secondary sort on revision order number. However, because the query was no longer able to use the index for sort the query failed (the in-memory sort exceeded memory limits) and the commit was reverted. 
In the interim, an index was added to the database, `identifier_1_r_1_create_time_1_order_1` which supported the query.
Looking over the explain plan with Stu, though, we decided that breaking the query in two and concatenating the results, as it originally was, makes for a more efficient query.

EVG-6022 add secondary sort on order number

---

scripts/indexes.js

JIRA: https://jira.mongodb.org/browse/MCI-3056
`data.r_type` does not exist in the event_log collections. The `EventLogEntry` struct type has an `EventLogEntry.ResourceType` (`r_type`) field but the event types in `EventLogEntry.Data` (`data`) (e.g. `HostEventData`, `DistroEventData`) do not have any field with a bson struct tag `r_type`.

MCI-3056: do not create indexes on nonexistent data.r_id field in event_log

---

model/event/event.go
model/event/event_test.go
scripts/indexes.js
units/event_metajob_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6939
Remove the unused `task_event_log` collection.

EVG-6939: remove empty task_event_log collection

---

cloud/ec2_client.go

In instant mode CreateFleet can error without returning an error. This means we
have to add an additional check for that case so that we do the right thing in
the RequestLimitExceeded case. Currently we are not doing exponential back off
for CreateFleet the way we do for every other API all.

EVG-6918 Handle additional error case in CreateFleet

---

rest/model/project.go

#2856 added the option to disable the repotracker without disabling the rest of the project. However, since the field wasn't added to the `APIProjectRef` it wasn't configurable through the API.

EVG-5908 add repotracker_disabled field to APIProjectRef

---

apimodels/agent_models.go
model/distro/distro.go
rest/data/host_create.go
rest/data/host_create_test.go
rest/route/host_create_test.go
units/provisioning_setup_host.go
validator/distro_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6915
The original test failure was due to a security group firewall configuration in host.create that blocked traffic to/from the host's Jasper service To work around this, there's a new provisioning option "none" to effectively do what is currently done for task-spawned hosts (i.e. don't connect to the host at all via SSH or RPC. Just do some cloud host bookkeeping and immediately mark the host as running so that tasks can use it).
* Provide user option to override provisioning method in the host.create config. Default is "none".
* I don't know if we even want users to be able to configure provisioning settings at all given that they've don't do any host SSH provisioning currently anyways. I'm open to just removing this and having "none" be an …

EVG-6915: do not contact task-spawned hosts

---

operations/admin.go
operations/host_spawn.go

JIRA: https://jira.mongodb.org/browse/EVG-6957
Fixes config file flag for `evergreen admin banner`, `evergreen host list`, and `evergreen host terminate`.

EVG-6957: use correct CLI context to get conf path

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_test.go
model/host/host.go
model/host/host_test.go
public/static/js/spawned_hosts.js
public/static/partials/user_host_details.html
service/templates/spawned_hosts.html

If a host is stopped and then started:
1. AWS will give the instance a new public IP and DNS name
2. the launch time is reset
3. instance stores go away
When we start the instance we should cache the new values for DNS name, launch time, volumes, and volume sizes.

EVG-6848 refresh cached host values on start

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6973
Using `(*Host).GenerateJasperCredentials()` deletes the existing credentials and does not save the new ones to the database. This was effectively deleting all the credentials stored in the database each time a connection was established to a host Jasper service.

EVG-6973: use existing client credentials in database to connect to Jasper

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-6976, https://jira.mongodb.org/browse/EVG-6977
`evergreen fetch` failed on an ubuntu1804-test spawn host because the user data script ran evergreen as root instead of the distro user (ubuntu). This prevented the host from transitioning from provisioning to running. Fetching task data is a nice to have but not required for the spawn host to be considered running.
* Run `evergreen fetch` as Jasper command.
* Even if `evergreen fetch` fails, the CLI will return exit code 0 (because the request was made successfully, even if the command did not), so it will not trigger errexit on the user data script (unless Jasper could not be contacted).

EVG-6976, EVG-6977: fetch task data as unprivileged user and continue on error

---

model/host/host.go
model/host/host_test.go
rest/data/host.go
rest/data/interface.go
rest/route/admin_spawn_hosts.go
rest/route/service.go

The commented code isn't meant to be committed--I started adding something for admins to filter data by user and then couldn't think of a use case so I stopped, but if someone has an argument for why it's valuable I'll implement it.
This returns some basic metrics on overall spawn host and volume usage.

EVG-6630 give metric data to admins

---

public/static/partials/hostevent.html
units/provisioning_create_host.go

Also disambiguate successful and failed start/stop/modify attempts on the host events page.
Can't print "failed" for failed attempts since the successful field is only present for events that occurred since 50df9cd27639e7e3cd0962ab5c22ef3cf96f9dcf was deployed.

EVG-6984 don't log when host create succeeded

---

cmd/generate-lint/generate-lint.go
cmd/go-test-config/make-config.go
makefile
model/host/hostutil_test.go
self-tests.yml
units/generate_tasks_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7003
From the email yesterday, GOROOT is no longer explicitly set _and_ the default go version in the PATH variable is go1.13. It seems like we were implicitly using go1.7 on race detector and lint for a while. Furthermore, gometalinter relies on invoking the go binary in PATH, so we need to set that. I also fixed a misnamed function "set-up-credentials" (should be setup-credentials) and fixed an annoying log message due to a makefile error when setting gobin.

EVG-7003: fix go environment in evergreen config

---

model/host/host_test.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/MAKE-1027
The APM changes caused queries on these tests to slow down enough to hit the test timeout.

EVG-7004: increase test timeout

---

model/host/hostutil.go
operations/before.go
operations/host.go
operations/host_spawn.go
rest/client/interface.go
rest/client/mock.go
rest/client/rest.go
rest/model/host.go
rest/route/host_spawn.go
rest/route/service.go
units/jasper_deploy.go

Add a command to the CLI to run a command on users' spawnhosts.
The command is passed to bash on the spawn host and the CLI prints the command's output.

EVG-6629 run command on host

---

model/host/db.go
model/host/host.go
model/host/host_test.go
service/api.go
service/api_middleware_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7022
Some hosts had their "needs new agent monitor" flag set due to max LCT elapsing on a particularly long latency between intent host creation and agent start time. Therefore, it attempted to deploy when an agent monitor was running on the host.
* The max LCT check should only be used to redeploy the agent if the agent is not obviously up and running (in this case, it was definitely running). This change disables the flag that triggers agent/agent monitor deploys if the agent successfully contacts the app server via a REST route.
* I also made the
The flow is slightly confusing but this is because the following events occurred:
1. The intent host was created at 10:34am.
2. The create host job only started at 11:12am, well after max LCT elapsed …

EVG-7022: agent contact should disable agent deploys

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_test.go
cloud/ec2_util.go
model/host/volume.go
rest/data/host.go
rest/data/interface.go
rest/route/host_spawn.go
rest/route/host_spawn_test.go

Generates device name differently because the AWS docs seem inconsistent, and we should regenerate device name on failure so we don't retry repeatedly with a bad device name. Also some code cleanup (using the connector for volume things, remove old debugging, etc.)

EVG-6945 generate device name better

---

service/timeline.go
service/ui.go

when opted into the new patches page, landing on these routes will redirect from our angular app to our react app patches page:
/patches/user -> /patches/user/{your_username} 
/patches/user/username -> /patches/user/username
/patches/mine -> /patches/user/{your_username}

EVG-6595: support new patches page routes

---

model/patch_lifecycle.go
model/patch_lifecycle_test.go
rest/data/project.go
rest/route/project.go
rest/route/project_test.go
service/project.go
service/templates/projects.html
units/patch_intent.go
units/patch_intent_test.go

FinalizePatch is called by both CLI and PR patches, to create a version when the item is removed from the queue. I think adding validation at the end of the queue is consistent for the different types of queues, and allows for the changing of task/variant aliases before the item reaches the head of the queue.

EVG-6890 only create version if patch has versions/tasks

---

rest/model/patch.go
rest/model/patch_test.go

Access Tasks from VariantTasks instead of Patch to prevent the variant_tasks in the patches endpoint from containing all tasks

EVG-6940: variant_tasks in patches endpoint contains all tasks

---

model/generate.go
model/generate_test.go
model/lifecycle.go
model/patch_dependencies.go
model/project_parser.go

If a generated task depended on another task being added for another variant that already existed the depended-on task wasn't being pulled in to the patch.
Because dependencies were included for existing and new variants separately, when we called `AddNewBuilds` with tasks for existing builds, they were passed over.
Additionally, the depended-on task wasn't available in `AddNewBuilds`'s TaskIDTable, so it wasn't being added as added as a dependency.

EVG-6409 generated task dependencies

---

config.go
operations/http.go
service/api_patch.go

JIRA: https://jira.mongodb.org/browse/EVG-6847
This is a follow-on for [EVG-6823](https://jira.mongodb.org/browse/EVG-6823) that essentially removes the duplicate buildvariants field after people have had time to update their evergreen binaries.

EVG-6847: remove old buildvariants specification

---

model/event/event_finder.go
model/event/host_event_test.go
service/event_log.go
service/host.go
service/host_test.go
units/host_termination_test.go

Host event logs are created using both the host ID and the host tag (bringing us back to the FindHostByIdOrTag changes), so we should find event logs using both of these.
Also removed an unused host event.

EVG-6286 use ID and tag for host logging

---

migrations/anser_test.go
migrations/suite_test.go
mock/environment.go
model/host/host_test.go
model/host/hostutil_test.go
model/reliability/db_test.go
rest/data/admin_test.go
rest/route/commit_queue_test.go
rest/route/distro_test.go
rest/route/reliability_test.go
service/api_task_test.go
service/host_test.go
units/commit_queue_test.go
units/event_send_test.go
units/github_status_api_test.go
units/host_termination_test.go
units/patch_intent_test.go
units/periodic_builds_test.go
units/provisioning_convert_host_to_legacy_test.go
units/provisioning_convert_host_to_new_test.go
units/provisioning_jasper_restart_test.go
units/provisioning_user_data_done_test.go
units/stats_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7017
`(mock.Environment).Configure()` is primarily used to set sane default values. The db settings field on the mock environment has never been set and the path to the settings has been ignored for a long time so I just removed both.

EVG-7017: remove unused path and db settings from mock environment

---

model/host/hostutil.go
model/host/hostutil_test.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-7049
* Fix an issue on Windows where the existing PATH contains spaces so it needs double quotes to treat it as a string.
* Export the path so that the bash variable is set in the environment.

EVG-7049: fix PATH shell quoting and export

---

cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
units/stats_host_idle.go
units/stats_task_end.go

#2898 caused the case where CostCalculator wasn't implemented to error, and we want to ignore the error. 
Logging the error brought to light that Fleet doesn't implement the interface, so this fixes that too.

EVG-6408 fix CostCalculator not implemented errors

---

model/manifest/db.go
model/manifest/manifest.go
model/manifest/manifest_test.go
operations/fetch.go
plugin/manifest_plugin.go
rest/data/task.go
service/api_patch.go
service/api_plugin_manifest.go
service/ui_plugin_manifest.go

Manifests' records of module githashes are updated when a patch is created that includes module patches where the base commit is not the same as the one recorded in the manifest. This causes the manifest to be incorrect for other versions sharing the same manifest (the repotracker version as well as other patches off the same base commit).
This PR removes the manifest update in favor of dynamically adding a `ModuleOverrides` field to the manifest based on the patch requesting the manifest.

EVG-6454 use githashes from patch modules

---

model/task_lifecycle.go
model/task_lifecycle_test.go
service/api_task.go

This was a fun bug!
Two things went wrong:
1. The attempt to dequeue when the version finished didn't work because the version completion wasn't logged. When a task in a single-host task group fails we add the rest of the tasks in the task group as blocked dependencies of the failed task. Since we do this _after_ the call to `MarkEnd` if there are no more tasks in the version the version will never finish, since when `MarkEnd` ran the tasks were not blocked.
2. The attempt to dequeue when the task failed didn't work since we weren't using the PR number as the issue id.
Along the way it became apparent we were trying to dequeue from the commit queue for failed tasks belonging to versions that had no patch, which returned an error for every failed task for the waterfall, for instance, and …

EVG-7014 fix commit queue dequeue for task groups and PR items

---

public/static/app/common/ApiTaskdata.js
public/static/app/perf/perf.js
public/static/app/perfdiscovery/PerfDiscoveryDataService.js
public/static/app/perfdiscovery/PerfDiscoveryDataService.test.js
public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
public/static/js/filters/filters.common.js
public/static/js/filters/filters.test.js
service/templates/perfdiscovery.html

- Run a formatter on the files I touched (don't review the first commit)
- Add wrapper methods to retrieve task and trend data from cedar and convert afterwards (same as those used in trend charts)
- Conditionally use those to retrieve data, based on user selecting what they want to be the data source for the current/baseline/trend data

EVG-6549 allow toggling expanded metrics in perf discovery

---

repotracker/repotracker.go

We saw a case of a version not being created for server commit 88956acd276472b1b4c0192f73b07d67c4cae29c-- there was a transaction error and this failed to start the transaction again on retry. Likely what happened is in the first attempt we errored at aborting the transaction, so we couldn't start the transaction again and we don't retry again.
Instead, we should create a new client if an abort attempt fails. 
(Alternatively we could try to abort the transaction in a retry loop, but it's possible there's some reason it can't be aborted and this won't help us move on.)

EVG-7008 retry with new client if transaction won't abort

---

model/generate.go
model/project.go
model/project_matrix_test.go
model/project_parser.go
model/project_parser_test.go
model/project_selector.go
model/project_test.go
model/version_db.go
model/version_test.go
validator/project_validator.go
validator/project_validator_test.go

Do this in a validation and in translate project.
This pull request looks longer than it is because I'm mad that createIntermediateProject manually formats []error when modern day evergreen has been blessed with catcher.Resolve(), and I fixed it in parser project but that might never happen so I'm doing it now.

EVG-6931 validate task names don't have spaces

---

model/generate.go
model/generate_test.go
model/task/db.go
model/task/task.go
units/generate_tasks.go
units/generate_tasks_test.go

Although storing bytes is convenient, since it means that you never have to
convert to and from byte slices, it makes it difficult for a human being to
examine the task document in the database to find out the contents of the
generator.

EVG-6579 Store strings instead of bytes for generate.tasks

---

cloud/ec2_client.go
rest/route/host_spawn.go

If the user gives a bad device name, we should error immediately because it will also not work on retry, and we can't simply regenerate the device name. 
Also noticed that we don't check if the host we've looked up is actually still up--can't attach volumes to terminated instances so.

EVG-6922 don't retry if user-given device name fails

---

model/host/host.go
model/host/host_test.go
operations/host_spawn.go

Tacking another small thing onto this ticket--should use a plain logger and also can filter on status and UserHost being true to limit the results for volumes and avoid adding another index.

EVG-6922 fix volume query

---

model/task_lifecycle.go
model/task_lifecycle_test.go

Since the task cache doesn't contain execution tasks this update fails for execution tasks, preventing the display task from restarting in the (majority) case where the last task to finish is system failed.

EVG-7016 stop updating build cache for execution tasks

---

public/static/app/common/ApiTaskdata.js
public/static/app/perf/perf.test.js
public/static/app/perfdiscovery/PerfDiscoveryDataService.js
public/static/js/filters/filters.common.js
public/static/js/filters/filters.test.js

Fixed 2 data format issues:
- The shared code to convert data from cedar to perf.json format drops most of the metadata. These are the changes in filters.common
- Instead of making the methods to retrieve expanded data return just the data, replace the HTTP responses with the correctly formatted data. Perf discovery is expecting this behavior

EVG-6549 correctly convert metadata for expanded metrics

---

model/host/db.go
model/host/host.go
model/host/host_test.go
scheduler/wrapper.go
units/crons_remote_hour.go

JIRA: https://jira.mongodb.org/browse/EVG-6747
Changes the distro page behavior so that adding static hosts (new or existing) to distros automatically starts the agent/agent monitor (after some period of time). If it needs to convert provisioning, this also occurs. I only set the conversion jobs to populate once an hour but I can move it to a more frequent interval (e.g. every 15 mins) if we want a speedier time from static host addition to actually running tasks.

EVG-6747: set status on static hosts depending on provisioning

---

globals.go
model/patch/github.go
model/patch/github_test.go
operations/list.go
rest/data/aliases.go
rest/route/project.go
rest/route/project_test.go
service/project.go
service/project_test.go
units/patch_intent_test.go

Check for GitHub alias definitions when enabling PR testing by generalizing changes made in #2896 that check for commit queue alias definitions when enabling the commit queue.

EVG-5883 check for enabling PR testing without patch definitions

---

model/host/db.go
model/host/host.go
model/host/host_test.go
scheduler/wrapper.go
scheduler/wrapper_test.go
units/crons_remote_hour.go

JIRA: https://jira.mongodb.org/browse/EVG-6747
Same as previous PR but only sets the static host's status if the host is not in the database or its status was terminated.

EVG-6747: change static host status only for new hosts and terminated hosts

---

model/task/db.go
model/task/task.go
model/version.go
model/version_test.go
public/static/js/task_timing.js
service/stats.go
trigger/task.go

Under the Patches view the array of patch documents that the information about a task/build (such as the create_time) was derived from was not aligned with the array of tasks so hovering over a dot would show the information of a different patch. Additionally, under the Commits view versions are sorted on order number (on the server side) while tasks/builds are sorted on create_time (on the client side), so they could be misaligned since the create_time is when the commit was created and order number is the order it got pushed onto master.
The solution in this PR is to sort tasks/builds on create_time on the server side (it had been on the client side) and align the arrays of patches and versions with the array of tasks/builds.
Will need to look over the indexes on builds and tasks to …

EVG-6186 sort patches

---

model/lifecycle.go

World's tiniest PR explained:
I don't know how this hasn't been discovered before, but Robert reported an issue where trying to belatedly add a task to a PR patch didn't actually add the task. Apparently, when we get the build we didn't also get the requester field, so `b.IsPatchBuild()` was always returning false since the build requester was empty, and for this task `patch_only` was true, so `task.SkipOnNonPatchBuild()` returned true, so we skipped this task entirely. Correctly interpreting `p.IsPatchBuild()` as true (by including the requester field) fixes this.
https://github.com/evergreen-ci/evergreen/blob/master/model/lifecycle.go#L691

EVG-6436 use requester field

---

model/host/hostutil.go
model/host/hostutil_test.go
units/host_termination.go

JIRA: https://jira.mongodb.org/browse/EVG-7089
* User data provisioning does not write the script to a file, so do it before running it during termination. I don't want to do this in the user data script since I want to keep the user data script as small as possible and writing a shell script within a shell script is likely to cause shell quoting madness.
* I'm pretty sure this doesn't work on Windows, but I'm also pretty sure the legacy method also doesn't work with teardown scripts on Windows.
* Run the teardown script with Jasper if using new provisioning.

EVG-7089: run teardown script on new provisioned hosts

---

model/testresult/testresult.go
rest/data/interface.go
rest/data/test.go
rest/data/test_test.go
rest/route/test.go
rest/route/version.go
rest/route/version_test.go

** Will update documentation after approval, and attach to the ticket. 
I outlined the following workflow for cloud in the ticket, for which we're adding a `variant` parameter to route (3) to filter results by variant, and a `task_name` parameter to route (4) to filter results by test.
(also some of these tests were messy and I couldn't resist a mild refactor)
> (1) /versions/{start_version_id} to get the RevisionOrderNumber.
> (2) /projects/{project_id}/versions — pass in this RevisionOrderNumber as the start, include the limit (would only need the version IDs from this)
> (3) /versions/{version_id}/builds gives Tasks in the TaskCache, can find the ID of the correct task (looking at display name "d", could add a parameter to get a specific build using variant name)
> (4) Can get tasks …

EVG-6671 add query parameters to limit results

---

config.go
operations/commit_queue.go

Because the `messageFlagName` flag doesn't exist it will be set to "".

EVG-7105 pull the correct description flag

---

model/github_hook.go

This ticket is to fix EVG-6540, i.e. use an existing webhook if applicable.
The main thing I see is that we expect `hook.GetURL()` to equal the `config.url` that we set in CreateHooks, but the github [documentation](https://developer.github.com/v3/repos/hooks/#create-a-hook) implies that the hook URL isn't made from the config.url.

EVG-6934 compare url config

---

model/generate.go
model/generate_test.go
model/project_parser.go
model/project_parser_db.go
model/project_parser_test.go
model/version_db.go

I think implementing that commented code in Save() would be the way to ensure the two stay at the most updated version. I think a next step would be switching `pp.ConfigUpdateNumber > v.ConfigUpdateNumber` to `>=` (potentially at the same time we toggle UseParserProject, or I could just add that as another if statement to avoid the toggle).
If we use the code as it is now (i.e. without implementing the commented code) we could see the following race when UseParserProject is true:
- Version has num 2, Parser Project has num 4, so we generate using the parser project document.
- We store version verifying with the version config number 2, so version is now at 3.
- We don't store parser project because 3 < 4. (unless we don't check `$lte` in which case we just overwrite, possibly the case of …

EVG-7077 include parser project in generate tasks (w/comments)

---

model/patch/patch.go
model/patch/patch_test.go
model/version.go
model/version_test.go
service/stats.go

#2971 displays task history sorted by create_time of the tasks/builds. Since this is defined differently for tasks/builds and patches/versions and the create_time shown on the page is that of patches/versions, they still appear out of order. Moreover, the definition of create_time for patches/versions is probably what we're after anyway.
This PR aligns builds/tasks with patches/versions sorted on create_time.

EVG-6186 order by patch/version create time

---

model/build/db.go
service/version.go

This ticket was made because looking up base builds just by revision would be incorrect (as other patches would also have this revision), but actually the query is correct since it checks Requester, it's just misleadingly named.

EVG-6844 rename misleading query

---

cloud/ec2.go
cloud/ec2_cost_test.go
cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
cloud/ec2_price.go
cloud/ec2_test.go
cloud/ec2_util.go
model/host/host.go
units/stats_host_idle.go
units/stats_task_end.go

#2933 was reverted because we were making too many AWS API calls to get spot instance pricing. Because Fleet wasn't caching pricing, every task that completed caused us to make an API call.
This PR reintroduces the changes from #2933 and caches cost in the host document when the host is marked as running. This is similar to the existing strategy for hosts requested through the ec2Manager. Although the pricing will not be accurate since AWS charges the _current_ rate and the rate may change over the lifetime of the host, it is sufficiently accurate for calculating the cost of a task.

EVG-7056 cache spot instance pricing

---

model/build/build.go
model/lifecycle.go
model/lifecycle_test.go
model/task/db.go
service/version.go

Deactivating a version takes a long time when there are many tasks. While the version is in an intermediate state where some builds are deactivated and some are active, there's an execution path where every task to finish will be considered to be the last task in the version to finish*. If in-flight tasks are also aborted this exacerbates the problem since many tasks will be finishing while the version is in the intermediate state.
The fixes here are to:
- Abort tasks **after** we've deactivated builds and tasks
- Deactivate all the builds and then all the tasks (as opposed to interleaving them). This minimizes the time the version is in the intermediate state where some builds are still activated.
\* For the record, what happened was: the version was unscheduled with the option to abort …

EVG-7013 Extra notifications

---

cloud/cloud_status.go
cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_test.go
cloud/ec2_util.go
units/host_status.go

- Address a possible cause: if the instance is terminated by AWS before it gets to running we should terminate it in the db.
- If AWS forgets about a host we should do the same and terminate it in the db.
- Log the status of a host that's not ready yet and unknown AWS statuses so if this happens again we'll know which status we're not handling
- Use the AWS SDK's constants for instance status

EVG-7076 terminate hosts AWS forgot about

---

public/static/js/spawned_hosts.js

Although the promises were collected, they were not actually being joined.

EVG-7093 reload when promises resolve

---

self-tests.yml

Getting a commit 100 commits prior to HEAD 
https://github.com/evergreen-ci/evergreen/blob/6e1246f06a283334bdbee1ddbfb4168cdebaf4ea/repotracker/github_poller_test.go#L51
failed because shallow clone specifies a depth of 100 (so we're off by one).
I considered getting the SHA of 99 commits ago, but this seemed cleanest to me since we won't have a dependency on the depth remaining the same.

EVG-6139 unshallow clone for a test using old commits

---

public/static/app/perfdiscovery/PerfDiscoveryDataService.js
public/static/app/perfdiscovery/PerfDiscoveryDataService.test.js
public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
service/templates/perfdiscovery.html

- Add a dropdown to perf discovery that allow selection of metrics other than ops/sec
- Populate this dropdown from the loaded data. Any metrics that either the baseline or comparison has data for will be added to the list. The default is still ops/sec
- When the dropdown is changed, reload the data, filtering for just that metric. Also change the header of the column for this value to the appropriate label

EVG-7078 allow selecting metrics in perf discovery

---

auth/auth_test.go
auth/ldap_test.go
config_auth.go
rest/model/admin.go
service/templates/admin.html

This is to remove the LDAP config that was going to be used for Okta.

EVG-7001: revert LDAP options

---

config.go
operations/http.go
util/yaml.go

Reading a project YAML into a model.Project is not always valid. Tags cannot be
parsed correctly. Instead it has to be parsed with LoadProjectInto.

EVG-7160 Use LoadProjectInto instead of ReadYAMLInto in fetch

---

service/middleware.go
service/ui.go

Enabling CORS for GQL requests requires setting the header from the GQL request in the response headers.

EVG-7111 enable CORS for gql requests

---

config.go
operations/http.go
service/api_patch.go

EVG-5545 send patches over the wire base64 encoded

---

service/ui.go

All GET and POST requests to the GQL server require login. OPTIONS requests do not require login. By design, OPTIONS requests do not include auth headers such as cookie. This is because it's used to describe the communication options for the target resource.
This PR will be followed by a PR to Spruce that allows developer to log in and out while in dev mode. This will set the user's cookie and enable making authenticated queries to gql server. Handling authentication in production in Spruce is a ticket that will be discussed later on in the design doc. Currently Spruce does not handle its own authentication in production--it shares the cookie from Evergreen.

EVG-7109 OPTIONS requests do not require login

---

glide.lock
model/project_ref.go
model/project_ref_test.go
service/project.go
util/slice.go
util/slice_test.go
vendor/github.com/evergreen-ci/gimlet/auth_interfaces.go
vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager.go
vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager_test.go

- Add a "restricted" field to a project. Selecting this means that logged in users by default do not have any access to it. The admins and superusers will have access to it, and additional access must be granted manually
- This field is intentionally not in the API, let me know if you think it's needed
- When changing this flag in the UI, appropriately adjust access so that logged in users gain/lose access to it
- When updating the list of project admins, give/remove admin access for those users (not related to this flag, should have been in the previous PR)

EVG-7062 add restricted projects

---

globals.go
model/generate.go
rest/data/host_create.go
rest/data/host_create_test.go
service/rest_version.go
service/rest_version_test.go

I'd like to deploy this next week. Before that I'll do a re-read of what UseParserProject touches (reference https://github.com/evergreen-ci/evergreen/commit/37638678d41c27d3ffe7702ffc9c34fd6fe5dbdb and https://github.com/evergreen-ci/evergreen/commit/3c877e5ac0e81aca1627ff1cbb8caeb0667cf8b5). 
generate-lint and the smoke tasks work in staging, and I'd like to let it bake over the weekend.

EVG-7085 turn on parser project

---

graphql/http_handler.go
service/ui.go

Refactor the gql http handler func to be in the graphql package. This format will allow for more easily adding middleware later on.

GQL http handler

---

model/project.go
model/project_parser.go
model/project_selector.go

Potentially some omitempties missing (I actually don't know if it matters but just in case), but we should check length of empty maps rather than nil since it might exist bc of database things but still just be empty.
I looked in project_matrix.go, project_parser.go, project.go, and project_selector.go for other instances of this problem and this is what I came up with.

EVG-7085 check length and add omitempty

---

command/git.go
command/git_test.go
command/testdata/test.diff
model/patch/patch.go
model/patch/patch_test.go
model/testdata/test.patch
service/api_patch.go

Merging this ahead of https://github.com/evergreen-ci/evergreen/pull/3006, so if we roll that back we will have a check in place stating that patches cannot be mbox (since apps won't know how to handle this format anymore in `git.push`). 
(refactor of isMailboxPatch was intended for that PR anyway)

EVG-6592 (part 1) check is not mailbox diff

---

model/project.go
model/project_parser_test.go

This can be done independently of the other EVG-7085 revert.
I have no idea how this slipped through during phase 1 of this project, since that was forever ago, but when retrieving a parser project from the database, params weren't being restored before use.
Also improved the parser project test to have caught this, and tested with server and cloud yamls.

EVG-7085 handle params when unmarshalling bson

---

service/ui.go

Running e2e tests in evergreen for Spruce waits on the local server to start by pinging server with a HEAD http request. This route allows the [wait-on](https://github.com/jeffbski/wait-on) module to ping the local evergreen server.

add route for Head HTTP request

---

model/patch/db.go
model/patch/patch_test.go
public/static/js/patches.js
rest/route/middleware_test.go
service/api_patch.go
service/templates/patches.html
service/timeline.go

This is in-line with the Newer/Older buttons, and modifies the query rather than the current patch results (John has verified that this is the least awkward approach).

EVG-6600 option to filter commit queue patches

---

db/errors.go
model/generate.go
model/project_parser_db.go
model/task/task.go
model/task/task_test.go
units/generate_tasks.go

Because parser project race conditions are exposed as duplicate key errors and not results not found, we want to case on this in generate tasks.
(For context, this is because of upsert: when we can't find a parser project with our config number, we attempt to insert a new one, but if a parser project already exists with an updated config number then we receive a duplicate key error for trying to reuse the version ID, so effectively it says the same thing as a ResultsNotFound.)

EVG-7085 generate tasks should noop with duplicate key errors

---

service/middleware.go
service/ui.go

the `needsLogin` middleware responds with a 302 redirect. This PR creates an additional auth middleware that responds with a 401 status code instead. Open to different naming :)

EVG-7205: needsLoginNoRedirect middleware

---

model/patch/patch.go
model/patch/patch_test.go
operations/commit_queue.go
operations/patch.go
operations/patch_util.go

The immediate issue is that since c022192f89f2ac746dbe07d9c5c76752dcabdf3f commit queue patches with no community commits get the default patch description which fails commit message validation. This is addressed by moving the check for an empty patch description to be specific to the patch and patch-file CLI commands.
Since de91beefb4ca4ffced5138447ed94cdba4e55042 commit queue commit messages come from the messages of the commits enqueued and the patch description is no longer doing double-duty as the commit message. Therefore, it seems reasonable to standardize commit queue patch descriptions (especially in light of complaints like [this one](https://jira.mongodb.org/browse/EVG-6600)). The original patch's description will be of the form 
```
Commit Queue Merge: '<commit message>' into …
```

EVG-7190 standardize commit queue patch messages

---

model/generate.go
model/generate_test.go
model/lifecycle.go
model/patch_lifecycle.go
model/task/task.go
model/task/task_test.go
model/version.go
model/version_test.go

>Depending on a task generator should also depend on the tasks it generates
It _should_ be okay to do this for all generated tasks, so I opted not to make this a parameter for the generator.
Depend on the generated tasks with the same status as the dependency on the generator. So if you depend on the generator completing (pass, fail, or blocked) you will depend on the generated task completing and if you depend on it succeeding you will depend on the generated task succeeding. Short of adding a parameter on the task I couldn't think of a good way to indicate depending on generated tasks failing, but this seems like it won't be used. 
After looking through some code, I didn't update the dependencies in the project's config string and parser project, though it's hard to be absolutely …

EVG-7184 generator deps

---

model/host/host.go
model/host/host_test.go
units/provisioning_create_host.go

This is a small but risky refactor. Previously the behavior of the host create job was:
1. Spawn host with the cloud provider (probably changes ID, except for docker)
2. Remove old host document
3. Mark new host as starting
4. Insert new host document
Now it'll be:
1. Spawn host with the cloud provider (probably changes ID, except for docker)
2. Mark new host as starting
3a. If the ID didn't change, replace the intent host with the new host
3b. If the ID did change, remove the old document then insert the new document

EVG-7249 fix race between provisioning and agent for docker

---

glide.lock
model/project.go
model/project_parser.go
model/project_ref.go
model/project_ref_test.go
model/version_activation.go
repotracker/repotracker.go
validator/project_validator.go
validator/project_validator_test.go
vendor/github.com/robfig/cron/.gitignore
vendor/github.com/robfig/cron/.travis.yml
vendor/github.com/robfig/cron/LICENSE
vendor/github.com/robfig/cron/README.md
vendor/github.com/robfig/cron/chain.go
vendor/github.com/robfig/cron/chain_test.go
vendor/github.com/robfig/cron/constantdelay.go
vendor/github.com/robfig/cron/constantdelay_test.go
vendor/github.com/robfig/cron/cron.go
vendor/github.com/robfig/cron/cron_test.go
vendor/github.com/robfig/cron/doc.go
vendor/github.com/robfig/cron/go.mod
vendor/github.com/robfig/cron/logger.go
vendor/github.com/robfig/cron/option.go
vendor/github.com/robfig/cron/option_test.go
vendor/github.com/robfig/cron/parser.go
vendor/github.com/robfig/cron/parser_test.go
vendor/github.com/robfig/cron/spec.go
vendor/github.com/robfig/cron/spec_test.go

I made a logic change in my last commit, which we can discuss:
`sched.Next(thisTime)` will return the next time we expect to run after thisTime. Originally we discussed using `lastActivated` as `thisTime`. Say we want to run daily at midnight, and `lastActivated` was Tuesday afternoon, and our current version is Wednesday afternoon. We'll set the current version for Wednesday at midnight, and we'll run midday on Wednesday (since afternoon is after midnight), which we don't want for expensive tests. 
Instead, we should set to `sched.Next(time.Now())`, i.e. Thursday at midnight. Let me know if you think I'm missing something about the logic/goal.
Separately, This supports cron syntax such as "`@daily`", "`@every 2h`", "`hour | dayOfMonth | dayOfWeekOptional`" etc. I can document this …

EVG-7182 add cron_batchtime to project build variants

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7298
Ensure that the owner is the distro owner so when users SSH into their spawn host, the evergreen binary is executable.

EVG-7298: fix spawn host binary permissions

---

globals.go
model/generate.go
rest/data/host_create_test.go
service/rest_version.go
service/rest_version_test.go

This reverts commit ee70bc05619cc73a0c8f0b82ec57a3444d2a6966.
To deploy after quarterly planning or Wednesday morning, no review necessary.

EVG-7085 turn on parser project (#3024) (#3057)

---

model/host/host.go
model/host/host_test.go
units/provisioning_create_host.go

Since the parent ID for containers did not get changed when the actual host's ID changed, [this check](https://github.com/evergreen-ci/evergreen/blob/master/model/host/host.go#L1507) fails, among other places

EVG-7249 update parent IDs when they're assigned

---

auth/okta.go
glide.lock
service/templates/admin.html
service/user.go
vendor/github.com/evergreen-ci/gimlet/glide.lock
vendor/github.com/evergreen-ci/gimlet/middleware_auth_user.go
vendor/github.com/evergreen-ci/gimlet/okta/okta.go
vendor/github.com/evergreen-ci/gimlet/okta/okta_test.go

JIRA: https://jira.mongodb.org/browse/MAKE-1139
This gimlet version makes fewer Okta calls by making group checking optional to try to speed up logging in and reauthing. I did some random drive-by fixes that I found in the login and admin page.

MAKE-1139: revendor gimlet

---

graphql/generated.go
graphql/integration_spec.json
graphql/integration_test.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/testdata/projects1.graphql

Having favorited projects also in all projects caused duplicate key issues when rendering the data in the projects dropdown. This PR filters favorite projects out of all projects.

EVG-7200: Filter favorites out of all projects

---

public/static/partials/user_host_details.html

[EVG-7130](https://jira.mongodb.org/browse/EVG-7130)
While tags can be added to a host that is starting, provisioning, stopping, or stopped, it cannot be added to a host that is still initializing. Attempting to do so causes 500 errors that are confusing to the user. 
I added error prevention, by removing the the option to add a tag while the host is initializing, instead asking the user to wait until it's done. 
Attached are screenshots that show the adding tags card in different host states.

Evg 7130 - Adding a tag fails before AWS gives us an instance

---

public/static/app/perf/TestSample.js
public/static/app/perf/TrendSamples.js
public/static/app/perf/perf.js
public/static/app/perf/trend_chart.js
public/static/app/perf/trend_chart.test.js
service/templates/task_perf_data.html

- Expose the selected threads data (currently scoped to only the trend chart) by passing a closure which returns the data to the parent scope
- Use the selected threads data to filter both the baseline and hover sample data
- Refactor the HTML template a bit to have less inline computation

EVG-6439 use correct thread level for perf comparisons

---

config.go
operations/patch_util.go

Remove the `--summary` option to `git format-patch` which causes a summary of file changes to be appended to the commit message.
The fix is on the client side so users will need to update their CLI to get the fix.

EVG-7323 remove summary from commit messages

---

model/alertrecord/alert_bookkeeping.go
model/alertrecord/alert_bookkeeping_test.go
trigger/task.go
trigger/task_test.go

The task trigger checks if a BFG has already been created for an earlier revision, but in the case of stepback the existing alert is for a later revision.
This PR records the revision order number of the _previous_ task in the alert (similar to how it's done for TaskRegression) so we can check if **this transition** from passing to failing already has an alert. Also reorganized `shouldIncludeTest` to be more understandable/maintainable.

EVG-7229 BFGs on stepback

---

apimodels/agent_models.go
cloud/cloud.go
cloud/docker.go
cloud/ec2.go
cloud/ec2_fleet.go
cloud/ec2_test.go
cloud/ec2_util.go
cloud/gce.go
cloud/gce_costs_test.go
cloud/mock.go
cloud/openstack.go
cloud/static.go
cloud/vsphere.go
model/distro/db.go
model/distro/distro.go
model/host/host.go
model/host/host_intent.go
model/host/host_test.go
rest/data/host_create.go
rest/model/distro.go
rest/route/host_create_test.go
scheduler/scheduler.go
scheduler/wrapper.go
scheduler/wrapper_test.go
validator/distro_validator.go
validator/distro_validator_test.go

Lots of changed files, basically just to add a ProviderSettingsList to the distro.
**Open Questions:** 
1. Added FromDistroSettings to the ProviderSettings interface, to handle getting from the list or the old data structure. This takes in zone because of ec2 (and potentially for supporting other providers in the future), but is that awkward? Sometimes region (not zone) will be passed in also. Just seems unnecessary to save both region and zone to Host when you can get the region from the zone easily. I almost added this to the Manager, but some places seem to use settings and not a manager.
2. Should we error more visibly if updating Distro with provider list doesn't work?
3. Is `"go.mongodb.org/mongo-driver/bson"` the preferred library? 
4. I wrote this so there might be a reason... but …

EVG-7232 add provider settings list

---

rest/data/distro.go
rest/route/distro.go

I started writing something more complicated but I think the methods involved might impact other things so I want to think about it without a time pressure--regardless, settings this list to be nil in the case of an overall update should make EVG-7232 safe because `FromDistroSettings()` will set it correctly again.

EVG-7329 remove ProviderSettingsList for distro updates 

---

self-tests.yml

https://evergreen.mongodb.com/build/evergreen_ubuntu1604_docker_patch_1bc18e2b55c47b8e3bcac136c539e42edef45b9b_5e402c1f2a60ed2a3ac25db0_20_02_09_15_58_24

EVG-7314: fix docker tests

---

model/project.go
public/static/js/projects.js

It looks like having empty display names was making the waterfall wonky, and this only happened when the "last good version" had a different config file than the others (in this case, when triggered versions create a "generate" variant; potentially we should _always_ be using build.DisplayName rather than this project mapping but I'm not sure what the argument is either way).
Includes a tiny fix to a triggers bug I hit along the way.

EVG-6655 include displayName in WithFields

---

cloud/cloud.go
cloud/ec2_test.go
cloud/ec2_util.go
validator/distro_validator.go
validator/distro_validator_test.go

This ticket was originally to change GetManagerOptions to consider multiple regions, but actually it's always called by host distros (which only have one region defined).
This would only be false in the case of validating multiple provider settings, so the big change was that, and to not GetManager just to unmarshal a settings object.

EVG-7235 validate multiple provider settings

---

model/context.go
rest/route/middleware.go

[EVG-6935](https://jira.mongodb.org/browse/EVG-6935)
This bug was reproducible when run locally. However, when run in production or staging, instead of causing a panic, a 401 -Unauthorized- error was returned instead. 
This fixes the cause of the panic, and also returns a 400 error with a message indicating that the project was not found, instead of 401 Unauthorized

EVG-6935 Fix panic and 401 error when fetching with non-existent project_id or distro_id 

---

scheduler/wrapper.go
scheduler/wrapper_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7360
If we don't do this, the allocator turns off the reprovisioning flag after the first update.

EVG-7360: preserve reprovisioning if already set

---

makefile
operations/host_spawn.go
operations/host_spawn_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7365
Make rsync command compatible with the rsync command used on cygwin, which requires cygwin paths instead of native paths.

EVG-7365: make rsync work with cygwin

---

command/git.go

Without the `--keep-cr` flag the commit queue will strip Windows \r from patches.

EVG-7371 add --keep-cr flag to git am

---

graphql/errors.go
graphql/integration_spec.json
graphql/resolvers.go

**Would like to get some thoughts on this before changing all the tests to reflect new errors.**
Create a better system for sending errors in gql resolvers. Now all resolver errors will have an error code associated with them.

EVG-7342: gql error handling

---

model/host/db.go

This is mostly for deploys since they tend to cause max LCT to elapse.

Increase time until agent monitor attempts to deploy

---

public/static/app/perfdiscovery/PerfDiscoveryDataService.js
public/static/app/perfdiscovery/PerformanceDiscoveryCtrl.js
service/templates/perfdiscovery.html

Previously we were doing a full load of data from evergreen/cedar when the metric changed. Now we're caching any loads of the data and just filtering the bound data when it changes

EVG-7194 don't reload data when changing metric

---

cloud/cloud.go
cloud/ec2_util.go
cloud/spawn.go
globals.go
model/distro/distro.go
model/distro/distro_test.go
operations/host_spawn.go
rest/data/distro.go
rest/data/host.go
rest/data/host_test.go
rest/model/host.go
rest/route/host_spawn_test.go

Originally I was planning to add Region to the host document, but since we decided to limit ProviderSettingsList to 1 item (to keep the host document tidy) we don't need that anymore.
1. Sets user_data for the list as well as legacy
2. Gets ImageID from the list if legacy isn't provided
3. Pass region up through the create route

EVG-7236 add region support to hosts

---

command/s3_put.go
command/s3_put_test.go
model/artifact/artifact_file.go
model/artifact/artifact_file_test.go
service/task.go

Note: I know that the testing is probably a bit overkill, but it helped me verify that it is working as expected. Should I leave it in there, or remove it?

EVG-7135 Expand AttachFiles to persist expansion key with artifact

---

command/s3_put.go
command/s3_put_test.go

Prior to this commit s3.put checked if LocalFile was an absolute path before 
expanding values. This means that if a user provided an expansion in LocalPath
which made it absolute, s3.put would behave as if it were local. This commit
inverts the order, expanding values before checking if the path is absolute.

EVG-7226 Check if LocalFile is absolute after expanding values

---

cloud/spawn.go
cloud/user_data.go
model/distro/distro.go
model/host/host.go
model/host/hostutil.go
model/host/hostutil_test.go
operations/host_setup.go
operations/host_spawn_test.go
operations/host_test.go
units/host_status.go
units/host_termination.go
units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go
units/provisioning_convert_host_to_legacy.go
units/provisioning_convert_host_to_new.go
units/provisioning_create_host.go
units/provisioning_jasper_restart.go
units/provisioning_setup_host.go
units/provisioning_user_data_done.go
units/provisioning_user_data_done_test.go
units/ssh_keys_update_static.go
util/capped_writer.go

JIRA: https://jira.mongodb.org/browse/EVG-7334
This is an assortment of random, unrelated improvements and cleanup.
* Make convenience functions for running SSH commands. This includes running arbitrary scripts over SSH so there is no chance of shell quoting problems due to faulty argument interpretation.
* Make teardown more reliable by falling back to SSH in case Jasper fails.
* Print output of teardown script to stdout so it can be captured by host termination job.
* Consolidate common commands between setup host job and user data.
* Replace all usages of `*exec.Cmd` with `*jasper.Command`.
* Remove old init system detection code.
* Add TODO for fixing task fetching on Windows legacy SSH spawn hosts (none at this point, but might as well fix).

EVG-7334: clean up host provisioning

---

model/host/hostutil.go
model/host/hostutil_test.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-7334
* Move user data specific command to user data script.
* Only apply curl timeout to curl command.

EVG-7334: move user-data-specific spawn host fetch

---

model/distro/db.go
units/crons.go
units/host_monitoring_parent_decommission.go
units/host_monitoring_parent_decommission_test.go

Previously the scheduler was creating host intents for parent distros in the same way that it creates other hosts, so that it didn't get marked as running containers. This now makes the scheduler skip planning parent distros, and also makes the job that deco's parents handle min hosts

EVG-7324 respect min hosts for parents

---

service/api_plugin_git.go

Writing the status header seems to fix the problem. It's not clear why it's suddenly an issue or why this fixes it.

EVG-7400 write headers in patch file response

---

cloud/cloud.go
cloud/docker.go
cloud/ec2.go
cloud/ec2_test.go
cloud/gce.go
cloud/openstack.go
cloud/static.go
cloud/vsphere.go
model/distro/db.go
model/host/host.go
rest/data/distro.go
rest/route/distro.go
rest/route/distro_test.go
service/distros.go

This to maybe fix the weird "overwriting AMIs and distro provider" thing by not calling a different Update for provider settings list.

EVG-7232 only update distro settings in logged places

---

graphql/generated.go
graphql/integration_spec.json
graphql/resolvers.go
graphql/schema.graphql
graphql/testdata/task_test-formats-html-url-with-line-num-and-log-id-when-url-empty.graphql
graphql/testdata/task_test-formats-raw-url-with-query-param-and-log-id-when-raw-url-empty.graphql
graphql/testdata/task_test-logs-empty-str.graphql
graphql/testdata/task_test-logs-prepend-api_url-when-scheme-and-host-not-provided.graphql
graphql/testdata/task_test-logs-use-original-url-when-provided.graphql
graphql/testdata/task_test-nonexistent-task_id.graphql
graphql/util.go
rest/model/test.go
rest/route/service_test.go

This PR was made to support the HTML and RAW log links in the Task page test table
The two new TestLog fields are `htmlDisplayURL` and `rawDisplayURL`. We prepend the API URL to the `rawDisplayURL` and `htmlDisplayURL` inside of the resolver instead of `APITest.BuildFromService` if there is not a scheme and host present in the display URLs from the APITest struct. The code in `BuildFromService` decides if we need to change up the format of the URL using logID and/or lineNum depending on a set of conditions.

EVG-7210: Expose URLs for html & raw logs in TestLog GQL type

---

model/task/task.go

JIRA: https://jira.mongodb.org/browse/EVG-2854

EVG-2854: do not put single-host task groups in the alias queue

---

model/distro/distro.go
model/host/hostutil.go
model/host/hostutil_test.go
rest/route/host_spawn.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-7387
This is a compatibility fix for Windows legacy and non-legacy provisioning.
For almost all cases, paths to Windows files and directories have to be specified as native file paths when passing them as command line arguments (i.e. if you use `/`, it refers to `C:/` not `C:/cygwin`). Jasper processes (which run via exec), are consistent with this behavior because all file paths have to be in native Windows style (e.g. `C:/cygwin/home/Administrator/evergreen.exe fetch --dir C:/cygwin/data`). However, when invoking executables directly through legacy SSH, we have to use Unix-style paths (e.g. `/home/Administrator/evergreen.exe`) since their paths are evaluated directly in Cygwin bash. The Unix-style path rule doesn't apply for CLI flags on the …

EVG-7387: use correct home directory for legacy SSH

---

graphql/integration_spec.json
graphql/integration_test.go
operations/cli_integration_test.go
operations/commit_queue_test.go
service/api_patch_test.go
service/api_status_test.go
service/api_test_utils.go

This change allows us to access user permissions set in the gql integration test setup data during gql tests so we can properly test queries that require specific permissions. 
I added a third parameter to `CreateTestsServer` to enable this setting and had to change some test results since the time zone was adjusted after enabling NaiveManager for GQL tests.

EVG-7441: Use NaiveManager instead of MockUserManager for GQL tests

---

cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
cloud/ec2_util.go

Because Evergreen's most common call to the AWS API is CreateTags, combining tagging with the CreateFleet request will save many API calls.

EVG-7212 remove extra calls to CreateTags

---

config_containerpools.go
model/host/host.go
model/host/host_intent.go
model/host/host_test.go
rest/data/host_create.go
rest/route/host_create.go
rest/route/host_create_test.go
scheduler/scheduler.go
units/host_termination.go

Previously, the approach was to pack containers on as few parent hosts as possible, because that would minimize cost. This changes that behavior to pack containers from the same distro (and thus image, usually) onto the same host, because that will minimize latency. It also sets a cap of 3 distros on the same host to make it unlikely that downloading many different images will fill up the disk

EVG-7165 simplify how we allocate containers

---

config_db.go
config_serviceflags.go
model/generate.go
model/generate_test.go
model/lifecycle.go
model/patch_lifecycle.go
model/project_parser.go
model/project_parser_db.go
model/testutil/api.go
model/version_db.go
repotracker/repotracker.go
rest/data/host_create_test.go
rest/data/version_test.go
rest/model/admin.go
service/rest_version.go
service/rest_version_test.go

Stop writing to version config if we don't have to! 
(Surprised this wasn't already in the transaction, I definitely remember writing that at some point. Wonder if it got included in a revert at some point and accidentally got left out. If anyone can think of a reason it shouldn't be in the transaction let me know).

EVG-6929 stop writing config string to versions

---

public/static/app/perf/TestSample.js
public/static/app/perf/perf.js

Previously selecting max only in trend charts would cause a runtime error because we look for thread results with the string "MAX" as the thread level. This handles that by looking up the highest thread count in the results

EVG-7374 handle max only thread level comparisons

---

thirdparty/github.go

Log a structured message with the GitHub API limits returned with each request.
Will need to adjust the Splunk dashboard to reflect the new shape of the message. Also need to set up a Splunk alert for low capacity remaining.

EVG-7362 improve GitHub rate limit logging

---

model/project.go
trigger/process_test.go
trigger/project_triggers.go

A common workflow is probably to set a trigger on a project that is also one of your modules. In that scenario, we will now create a manifest with the triggered version so that test setup should for the most part just work without you having to add configuration to check out the upstream revision

EVG-7464 create manifest for triggered builds if matching module

---

command/s3_put.go
graphql/util.go
model/artifact/artifact_file.go
model/artifact/artifact_file_test.go
plugin/attach_plugin.go
plugin/attach_plugin_test.go

This PR mainly takes care of moving the url signing code so that it loads n the build page as well, and not only on the task page. [EVG-7474](https://jira.mongodb.org/browse/EVG-7474)
It also fixes the visibility (for signed and private)[EVG-7136](https://jira.mongodb.org/browse/EVG-7136) and suppresses some logging for private files.

Evg-7474 Generate self-signed s3 URLs on build page load

---

model/artifact/artifact_file.go
plugin/attach_plugin.go
public/static/plugins/attach/partials/build_files_panel.html

Remove the task name in the Build Page > Files panel for empty file lists. That information shouldn't really be sent to build_files_panel.html in the first place if it has no files, but that's a longer fix. Let me know if you think it's worth pursuing.

EVG-7474 Remove taskName For Empty File Lists

---

trigger/task.go
trigger/task_test.go

When a server test moves between execution tasks the test failure trigger thinks the test is new and alert for every failure. By grouping all tests in a display task together we look for this test in the entire display task and recognize the test has run before.

EVG-7304 group display task BFGs together

---

model/distro/distro.go
model/host/hostutil.go
model/host/hostutil_test.go
operations/host_spawn.go
rest/route/host_spawn.go
service/templates/distros.html
units/provisioning_agent_deploy.go
units/provisioning_setup_host.go

JIRA: https://jira.mongodb.org/browse/EVG-7439
This changes no functionality, but tries to use native paths instead of Cygwin POSIX paths (which are deceptive and dangerous) wherever possible in host provisioning. There's some cases where this is impossible, for which I wrote comments explaining the reason I hacked around them to make it as obvious as possible why they have to be done that way.

EVG-7439: use absolute paths where possible

---

auth/auth_test.go
auth/only_api.go
auth/only_api_test.go
glide.lock
model/user/db.go
model/user/user.go
self-tests.yml
vendor/github.com/evergreen-ci/gimlet/cached/user_service_cached.go

JIRA: https://jira.mongodb.org/browse/MAKE-1178
* Store API-only users in the users collection because `MustHaveUser` requires that it receive a DBUser from the gimlet middleware. No regular user can be authed in by the API-only user manager.
* Add a special OnlyAPI flag to DBUsers so that we can distinguish regular users from API-only users. This is also used to ensure that the set of API-only users in the users collection exactly matches the ones populated in the admin config.
* The only downside I can see to this is that before we make the user manager, we have to sync the API-only users in the DB before we set up the user manager. We also can't know if a regular user with the same ID is already in the collection when we save the admin settings (because it would cause a dependency on …

MAKE-1169: store API-only users in the DB

---

cloud/cloud.go
cloud/docker.go
cloud/ec2.go
cloud/gce.go
cloud/openstack.go
cloud/static.go
cloud/vsphere.go
model/host/host.go
rest/route/host_create_test.go
service/distros.go

Distro UI not loading because updating distro settings in erroneously removing the legacy provider settings structure, which the current distro UI is still using (to be changed in EVG-7233).

EVG-7499 maintain settings for distro UI

---

agent/agent.go
agent/agent_test.go
agent/logging.go
agent/logging_test.go
agent/task.go
operations/agent.go

The initial problem was that the agent was sending system-failed in the wrong format. I fixed that, but it surfaced another problem in which some shared functions to end the task will attempt to log to the task, but the scenarios in which we were trying to send system-failed did not have a logger for the task. This now adds a default sender which can be used to log to the agent's file

EVG-7463 send correct status from agent, add a default logger for errors

---

model/commitqueue/dequeue_sender.go
model/commitqueue/dequeue_sender_test.go

Now that the commit queue job dequeues the head of the queue when the version has finished running, the notification needs to check that the item it's dequeueing is still on the queue before it logs an event. Otherwise, multiple notifications can be sent for the same item if they run close enough together.

EVG-7559 fix double notification

---

cloud/docker.go
cloud/ec2.go
cloud/gce.go
cloud/openstack.go
cloud/static.go
cloud/vsphere.go
model/host/host.go
rest/route/host_create_test.go

I'd like to revert this within the next week, but need to migrate all of the distros from using settings to using provider_settings (as some unmigrated distros still do have provider_settings with bad data, or with empty items, so there's no way to determine if it's accurate).

EVG-7571 preference legacy for distro settings

---

service/templates/distros.html

JIRA: https://jira.mongodb.org/browse/EVG-7578
Stop the annoying silent autofilled password causing your evergreen password to be saved in plaintext to the database. It will still give you an autofill dropdown if you use the field since it's a username/password form. I tested only on the latest chrome, firefox, and safari.

EVG-7578: prevent autofill passwords for docker in distro settings

---

trigger/task.go
trigger/task_test.go

#3241 grouped test results from a display task together so a test could be compared against its last execution even when the test had moved within execution tasks. Every execution task with a test regression still generated a separate BFG.
This PR groups all test regressions from a single display task into a single BFG reporting all test regressions in the display task.
Because the task triggers were excluding display tasks from notifications and this is no longer true for test regressions the check for display task has been moved into the individual triggers.

EVG-7304 group all tests in a display task in one BFG

---

cloud/ec2_fleet.go
cloud/ec2_fleet_test.go
cloud/spawn.go
cloud/spawn_test.go
config_cloud.go
model/distro/distro.go
model/host/host.go
model/host/host_intent.go
public/static/js/admin.js
public/static/js/services/rest.js
public/static/js/spawned_hosts.js
public/static/partials/user_host_details.html
public/static/partials/user_host_options.html
rest/data/host.go
rest/model/admin.go
rest/model/host.go
service/spawn.go
service/templates/admin.html
service/templates/distros.html
service/ui.go
units/provisioning_setup_host.go

Automate migrating volumes between spawnhosts. Allow a user to select a volume to mount on the new spawnhost from a list of volumes that they've created and that aren't currently mounted on an instance.
- Set the AZ (by way of its subnet id) of a new spawn host to match the AZ of the volume we want to mount on it (because volumes need to be in the same AZ as the instance you want to mount it to)
- Add a map of `AZ -> subnet id` to the admin page so we don't need to keep asking AWS for the subnet ids in Fleet and when mounting an instance. This will save many API calls.
- Don't run the format command if the volume has already been formatted

EVG-7176 migrate volumes

---

model/host/static_hosts.go
scheduler/wrapper.go

JIRA: https://jira.mongodb.org/browse/EVG-7577
The host allocator updates the static host status every 15 seconds, which can be confusing if you manually update the status in the UI but then its status changes invisibly after the host allocator runs. This change is mostly to track when the host allocator does such a change.

EVG-7577: log when static host status is changed by the system

---

makefile
vendor/github.com/99designs/gqlgen/codegen/generated!.gotpl

I believe the gqlgen library introduced a bug for repos that don't use gomod, so I'll submit an issue to them once I get a minimal repro. In the meantime this should work around the problem, you'll need to run it by typing "make gqlgen"

EVG-7563 temporary shim for gqlgen

---

graphql/integration_spec.json
model/commitqueue/commit_queue.go
model/commitqueue/commit_queue_test.go
model/commitqueue/db.go
model/commitqueue/github_pr_sender.go
model/patch_lifecycle.go
model/task_lifecycle.go
operations/commit_queue.go
operations/commit_queue_test.go
rest/data/commit_queue.go
rest/data/project.go
service/project.go
units/commit_queue.go

When processing a commit queue item, we need to check that the patch isn't nil so we don't panic.

EVG-7438 dequeue item if patch is nil

---

model/project_vars.go
model/project_vars_test.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/route/project.go
rest/route/project_copy.go
rest/route/project_copy_test.go
rest/route/service.go

Originally when I made this route, cloud had very specific requests. Now doing what I should have done, which was make a more generalized/customizable route. Changes include:
1) Copy public variables (only copy private if indicated)
2) Allow users to fully overwrite the source project variables (i.e. delete variables projectB has that projectA did not)
3) Dry run returns what would be copied as is more conventional, not what will be overwritten (if users want that level of information they can use more API calls). This still redacts private variables.

EVG-7467 generalize copy project vars route

---

validator/distro_validator.go
validator/distro_validator_test.go
validator/project_validator.go
validator/project_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7585
This prevents errors about nonexistent distros when doing `evergreen validate` on a config which uses a distro alias (which is important since I'm in the process of deleting distros and aliasing them).

EVG-7585: allow distro aliases in project config

---

public/static/app/perf/TrendSamples.js
public/static/app/perf/perf.js
public/static/app/perf/perf.test.js

Previously we were sorting by commit order in the structure that stores trend data. For patches, commit order is a number that is the patch # for the user (we use the same field as commits) so it sorts nonsensically. This fixes the sorting.
There is still the lingering issue of patches being mislabeled (for example https://evergreen.mongodb.com/task/sys_perf_linux_standalone_audit_industry_benchmarks_patch_58abcf6577982367232a6c76d1ee277a4031ed3c_5dead5740ae6060c325daab9_19_12_06_22_26_35##%257B%2522compare%2522%253A%255B%257B%2522hash%2522%253A%252258abcf6577982367232a6c76d1ee277a4031ed3c%2522%257D%255D%257D shows on the trend graph with the metadata from its base commit) but that is due to the data being stored ambiguously

EVG-7101 correctly order trend graphs for patches

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/patchBuildVariants/data.json
graphql/tests/patchBuildVariants/queries/invalid-id.graphql
graphql/tests/patchBuildVariants/queries/patch-build-variants.graphql
graphql/tests/patchBuildVariants/results.json
model/task/task.go

https://jira.mongodb.org/browse/EVG-7514
Use patch ID to query for build variants
- Get all tasks for patch using `FindTasksByVersion`
- Map tasks to their respective variant

EVG-7514: query for patch build variants

---

model/manifest/db.go
model/manifest/manifest.go
model/manifest/manifest_test.go
repotracker/github_poller.go
repotracker/repotracker.go
repotracker/repotracker_test.go
service/api_plugin_manifest.go
thirdparty/github.go
thirdparty/github_test.go
trigger/process_test.go
trigger/project_triggers.go

If a patch changes a module's definition in the project's evergreen.yml we create a new manifest for the patch and save it in the db so we don't need to make GitHub API calls for each task. However, when subsequent patches are created on the same base commit it's not clear which manifest they should get and we end up creating a new manifest for every subsequent patch that includes a manifest defined differently from the manifest the db returns.
This PR marks the base commit's manifest so patches can get specifically the manifest of the base commit.
Additionally, when a patch warrants creating a new manifest we shouldn't get the most recent module commit as of the time of the _patch_, but rather as of the time of the base commit. This PR gets the base commit's time from GitHub and gets the …

EVG-7376 disambiguate modules

---

rest/data/host_create.go
rest/route/distro.go
rest/route/host_create_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7593
I just used the first distro ID that the alias can resolve into.

EVG-7593: allow distro aliases in host.create

---

model/host/db.go
model/host/host.go
model/host/host_test.go
model/task_start_estimation.go
service/distros.go
units/crons.go
units/host_monitoring_idle_termination_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7595
The job that populates the idle host termination job now decommissions hosts in missing (i.e. deleted) distros rather than erroring when it finds a missing distro.

EVG-7595: decommission hosts running agents on distros that are deleted

---

model/host/hostutil.go

JIRA: https://jira.mongodb.org/browse/EVG-7437
I forgot that `path.Join` cleans the path.

EVG-7437: do not use clean path

---

config_alerts_notify.go
config_test.go
model/commitqueue/dequeue_sender_test.go
model/event/event_finder.go
model/event/event_test.go
model/task_lifecycle_test.go
rest/model/admin.go
service/templates/admin.html
units/crons.go
units/crons_remote_minute.go
units/event_metajob.go
units/event_metajob_test.go
units/spawnhost_expiration_warning_test.go

Also sort the events so they're processed in FIFO order. This will require changing the index `processed_at_1` to `processed_at_1_timestamp_1`
Once this is merged will need to add a Splunk dashboard and an alert for passing some threshold for unprocessed events (>10,000?).

EVG-7292 make event processing limit configurable

---

cmd/evergreen/evergreen.go
globals.go
model/host/hostutil.go
model/host/hostutil_test.go
operations/model.go

The config file that's placed on spawnhosts is overshadowed by the config placed in the home directory in the build image (which is missing a user's credentials) because we look for the config file in the home directory before the executable directory. 
This PR will overwrite the build image's config with a user specific one.

EVG-7545 put config file in home dir

---

graphql/generated.go
graphql/schema.graphql

there is a default value provided for `statuses` param; therefore this param can be undefined

EVG-7610: Make statuses param in patchTasks resolver optional

---

model/alertrecord/alert_bookkeeping.go
model/event/subscriptions.go
model/user/user.go
public/static/js/notifications.js
rest/data/user.go
rest/model/user.go
service/templates/notifications.html
trigger/task.go

The Goal: Some users want a notification when the first task fails, not when the whole patch has finished. 
There does seem to be a race condition where tasks that fail around the same time all send the notification (which I think is why I thought this was broken). I'm thinking `generateWithAlertRecord` should do it before actually inserting the alert record because potentially generating takes some time.

EVG-7255 add first failing task in version trigger

---

testutil/testing.go

JIRA: https://jira.mongodb.org/browse/EVG-7616
I never run integration tests on my computer anyways, so it would be easier to just ignore them locally rather than check every time I run `make test-` if it failed because of an integration test.

EVG-7616: add environment variable to skip integration tests

---

public/static/partials/user_host_options.html
service/spawn.go

JIRA: https://jira.mongodb.org/browse/EVG-7614
Since we aren't putting SSH keys on the host anyways to do the clone, loading task data is impossible on a virtual workstation (and kind of nonsensical).

EVG-7614: make task data option and virtual workstations mutually exclusive

---

cloud/spawn.go
model/distro/distro.go
model/distro/distro_test.go
model/host/host.go
model/host/host_test.go
model/scheduler_stats.go
model/task_config.go
rest/data/host_create.go
rest/route/admin_clear.go
rest/route/admin_test.go
rest/route/middleware.go
scheduler/utilization_based_host_allocator.go
service/api_task.go
service/spawn.go
units/host_monitoring_parent_decommission.go
units/provisioning_agent_deploy.go
validator/distro_validator.go
validator/distro_validator_test.go
validator/project_validator.go
validator/project_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7600
I checked all the places where we rely on distro IDs and added validation to prevent docker parents and containers from using distro aliases.
DIstro aliases are allowed for:
* Tasks
* host.create command
* Making hosts from this task's host.create when starting a spawn host
Distro aliases are _not_ allowed for:
* Docker container/parent distros
* This is mostly because container pools have to map 1:1 to an exact distro ID.
* Also, it would mess with the host allocator if a distro alias mapped to multiple parents or multiple container distros.
* Spawn hosts - typically, someone should know which distro they want to make and what they're going to get.
* Scheduler stats for a distro (i.e. `evergreen export`)

EVG-7600: allow distro aliases where appropriate

---

scripts/indexes.js

#3307 required replacing the processed_at_1 index with processed_at_1_ts_1.
Make the change in indexes.js

EVG-7292 replace processed_at_1 index

---

model/host/host.go

JIRA: https://jira.mongodb.org/browse/EVG-7644
This is only a problem when moving static hosts between distros. I also noticed that static hosts across distros also causes quarantined hosts to be terminated, then set to running, but I don't really think that's super important to fix.

EVG-7644: allow static host statuses to be changed from terminated

---

glide.lock
service/host.go
service/ui.go
vendor/github.com/evergreen-ci/gimlet/.golangci.yml
vendor/github.com/evergreen-ci/gimlet/app.go
vendor/github.com/evergreen-ci/gimlet/app_routing.go
vendor/github.com/evergreen-ci/gimlet/buildscripts/run-linter.go
vendor/github.com/evergreen-ci/gimlet/evergreen.yaml
vendor/github.com/evergreen-ci/gimlet/framework_response_error.go
vendor/github.com/evergreen-ci/gimlet/handling_test.go
vendor/github.com/evergreen-ci/gimlet/makefile
vendor/github.com/evergreen-ci/gimlet/middleware_auth_user.go
vendor/github.com/evergreen-ci/gimlet/middleware_auth_user_test.go
vendor/github.com/evergreen-ci/gimlet/proxy_no_error.go
vendor/github.com/evergreen-ci/gimlet/proxy_options.go
vendor/github.com/evergreen-ci/gimlet/proxy_with_error.go
vendor/github.com/evergreen-ci/gimlet/rolemanager/role_manager_test.go
vendor/github.com/evergreen-ci/gimlet/server.go

If an error occurs reaching the backend (e.g.code-server isn't running) the default behavior is to return a 502 status code and an empty response. This will catch that error and pass a message and 500 status code.
Goes together with evergreen-ci/gimlet#77. Once that PR is approved it will be revendored and included here.

EVG-7613 handle backend-not-reachable errors

---

command/git.go
command/git_test.go

In order for the main commit's manifest to include module changes commit queue commits need to be in the correct order, first modules and then the main patch. Reorder patches so the main patch gets applied last.

EVG-7632 reorder patches

---

config.go
model/project_ref.go
model/project_ref_test.go
model/version_activation.go
operations/validate.go

I ran evergreen validate over all the configs and removing intervals for cron will only affect the go driver. Also, I added a quiet flag because running evergreen validate on all configs is really annoying.

EVG-7622 invalidate intervals for cron and add quiet flag to validate

---

cloud/cloud.go
cloud/cloud_test.go
cloud/ec2.go
public/static/js/distros.js
service/distros.go
service/templates/distros.html
validator/distro_validator.go

This is my start! Feel free to play around. The thing I'm having the most trouble with is:
Right now (for example), australia-1 isn't configured. If I go in and type some stuff and then remove it all, I don't want australia-1 to be saved. (I wrote this into UpdateProviderSettingsList).
I was thinking though, if australia-1 was already configured and I want to remove all the settings (i.e. delete it as an existing option), I'm not sure the best way to do that. 
1) Should all of this validation go in the go file instead? 
2) Should I be using form better? I'm not sure I can use $dirty because that also takes into consideration non provider settings fields. Can I define form.settings somehow and then call form.settings.$dirty? Will this still allow me to define settings.region from the …

EVG-7233 display multiple regions on distro page

---

graphql/tests/patchTasks/queries/filter-by-variant-partial-search-term.graphql
graphql/tests/patchTasks/results.json
model/task/task.go

Should have been this all along to return results for partial searches, i.e. `clo` returns true for `cloud`

EVG-7519: use regex to match variant name

---

cloud/ec2_client.go
cloud/ec2_fleet.go
cloud/ec2_fleet_test.go

Query the AWS API for which instance types are supported by an AZ and only ask for one of the AZs that support the distro's instance type.
Keep an in-memory cache so we don't need to make these calls every time we start an instance. 
I'm open to creating a new collection as an alternative to the in-memory cache.

EVG-7601 cache instance types by supported by AZs

---

model/host/hostutil.go
units/host_execute.go
units/host_termination.go
units/provisioning_agent_deploy.go
units/provisioning_convert_host_to_legacy.go
units/provisioning_jasper_restart.go
units/provisioning_setup_host.go
units/ssh_keys_update_static.go

JIRA: https://jira.mongodb.org/browse/EVG-7657
The host already knows its own SSH options, so it's redundant to pass them into `RunSSH` methods.
* Remove `sshOptions` parameters in provisioning.
* Clean up some copy-pastes and contexts.

EVG-7657: do not pass sshOptions into host SSH commands

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/patchTasks/queries/filter-by-base-status.graphql
graphql/tests/patchTasks/results.json

Since base status is not a field on the db model, filter the tasks by base status before being returned from resolver.

EVG-7528: filter patchTasks by base status

---

model/host/db.go
model/host/host_test.go

The host allocator should only look at hosts that it starts when finding stale hosts to remove. Exclude hosts spawned by tasks from the query.

EVG-7671 exclude hosts spawned by tasks from stale host intent check

---

cloud/ec2.go
model/distro/distro.go
rest/model/distro.go
rest/model/distro_test.go
service/templates/distros.html
units/provisioning_setup_host.go
units/provisioning_setup_host_test.go
units/provisioning_user_data_done.go

- A mounted volume's device name isn't necessarily the same as the device name specified in the AWS AttachVolume request, and isn't necessarily the same every time. The docs suggest pulling the device name from the output of the `lsblk` command, so this PR parses the device name from the output of that command. The parsing relies on the assumption that the most recently added device will be listed last in `lsblk`'s output. It's no longer necessary to keep a device name field in the distro, so it's been removed.
AWS docs:  1) [device names](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html), 2) [identifying the device](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html#identify-nvme-ebs-device)
- The ec2Client may generate a different device name …

EVG-7603 parse device name from lsblk

---

model/distro/distro.go
model/host/db.go
model/host/host.go
model/host/hostutil.go
rest/route/distro.go
trigger/host_spawn.go

JIRA: https://jira.mongodb.org/browse/EVG-7670
This just does a bit stricter checking for hosts created from tasks with host.create. Most of the time, we assume that a host with `StartedBy != evergreen.User` is a spawn host, which is not necessarily the case for hosts started via host.create.

EVG-7670: check for spawn hosts where necessary

---

units/provisioning_setup_host.go
units/provisioning_user_data_done.go

- Use the `ln source_file ... destination_dir` form (if for some reason it runs twice it shouldn't make an infinity mirror of soft links)
- Append a newline to the end of `/etc/fstab`
- Scope `provisioning_user_data_done` and `provisioning_setup_host` jobs per host. Each host will only have one job at a time so they don't each add their own home volume to the host.

EVG-7603 volume fixes

---

apimodels/agent_models.go
command/registry.go
command/s3_push.go
command/s3_push_test.go
glide.lock
globals.go
model/task_config.go
service/api_status.go
vendor/github.com/evergreen-ci/pail/.golangci.yml
vendor/github.com/evergreen-ci/pail/bucket_test.go
vendor/github.com/evergreen-ci/pail/cmd/run-linter/run-linter.go
vendor/github.com/evergreen-ci/pail/evergreen.yaml
vendor/github.com/evergreen-ci/pail/glide.lock
vendor/github.com/evergreen-ci/pail/gridfs.go
vendor/github.com/evergreen-ci/pail/gridfs_legacy.go
vendor/github.com/evergreen-ci/pail/interface.go
vendor/github.com/evergreen-ci/pail/local.go
vendor/github.com/evergreen-ci/pail/makefile
vendor/github.com/evergreen-ci/pail/parallel.go
vendor/github.com/evergreen-ci/pail/s3_bucket.go

JIRA: https://jira.mongodb.org/browse/EVG-7420
Dump the whole task directory into a private S3 bucket for tasks.
* Allow filtering variants that run s3.push.
* Allow file exclusion.
* Only one copy of s3.push per task. If you run the task again, it overwrites the original s3.push content. It might be possible to make this have unique task dumps for each execution of the task but it would be more complicated.

EVG-7420: create s3 command to upload task directory

---

cloud/ec2.go
cloud/ec2_client.go
cloud/ec2_util.go
model/host/db.go
model/host/host.go
rest/route/host_spawn.go

For whatever reason when I did this query originally I made it so device name had to be unique across all hosts--it just needs to be unique for the given host, so no DB query is necessary.
Additionally, we know that the 10 names we generate are valid so we shouldn't need to retry device names for that.
Having an issue though where errors aren't being returned correctly to the CLI? Seems to be hanging instead, even if the errors are inside of Run() for the route (`error sending request to attach volume: Post https://evergreen-staging.corp.mongodb.com/api/rest/v2/hosts/i-06c3e1da518f1f056/attach: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`)
Also made a fix to DeleteVolume: saw an issue with a volume in my list not existing in AWS. Does AWS terminate volumes …

EVG-7685 generate device name without host query

---

db/db_utils.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/task_lifecycle_test.go

1) Checks when adding new dependencies if the dependency already exists.
(This also updates unattainable if it should be updated). Do you think it's okay that this would add a new dependency if the taskId matched but the status didn't? I'm not sure when this would happen or if/how we handle that currently.
2) When marking dependencies unattainable/attainable, check all dependencies. (This shouldn't really be too expensive, I don't think a task ever has a _ton_ of dependencies unless there are duplicate bugs.)

EVG-7408 don't add duplicate dependencies

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/task/queries/reliesOn-dep-status-equals-all-statuses.graphql
graphql/tests/task/queries/reliesOn-dep-status-failed.graphql
graphql/tests/task/queries/reliesOn-task-status-equals-dep-status.graphql
graphql/tests/task/queries/reliesOn-task-status-not-success-nor-fail.graphql
graphql/tests/task/queries/reliesOn-unmet.graphql
graphql/tests/task/results.json

https://jira.mongodb.org/browse/EVG-7393
This PR adds a uiLink for the Dependency type. This is so we can link to the relevant task page from the title of a Depends on entry.

EVG-7393: uiLink field for Dependency type

---

model/manifest/db.go
model/manifest/manifest_test.go

With the migration complete, the check for legacy manifests (without the `is_base` field) is no longer necessary.

EVG-7376 remove check for legacy manifest

---

service/api_task.go
units/host_termination.go
units/provisioning_agent_deploy.go
units/provisioning_agent_monitor_deploy.go
units/util.go
units/util_test.go

- Refactor the places that were decoing a poisoned host and adding a job into a single function
- Call this function for parent + other containers if we try to disable a container

EVG-7024 deco parent if container is poisoned

---

graphql/generated.go
graphql/integration_spec.json
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/testdata/task-files-query-display.graphql
graphql/testdata/task-files-query-empty.graphql
graphql/testdata/task-files-query-err1.graphql
graphql/testdata/task-files-query-err2.graphql
graphql/testdata/task-files-query-exec.graphql

https://jira.mongodb.org/browse/EVG-7633
This PR makes some schema changes to include the file count when taskFiles are queried. GroupedFiles are now nested inside the TaskFiles type. 
Frontend changes were made to reflect the schema adjustments: https://github.com/evergreen-ci/spruce/pull/117

EVG-7633: Include fileCount in taskFiles query

---

command/s3_pull.go
command/s3_pull_test.go
command/s3_push.go
command/s3_push_test.go
model/task_config.go

JIRA: https://jira.mongodb.org/browse/EVG-7423
This is the inverse operation of s3.push. Most of the changes are refactoring since the commands are nearly identical.

EVG-7423: create s3 command to download task directory

---

model/distro/distro.go
rest/model/distro.go
service/templates/distros.html

The icecream settings aren't required since the host already has the icecream config built into the AMI.

EVG-7426: make icecream settings optional and fix json tag

---

config.go
model/project_parser.go
model/project_parser_test.go
operations/admin_all_configs.go
operations/fetch.go
operations/http.go
rest/client/interface.go
rest/client/methods.go
rest/client/mock.go
service/api.go
service/rest.go
service/rest_project.go
service/rest_version.go

As elaborated in [EVG-7167](https://github.com/evergreen-ci/evergreen/pull/3383), this adds new functions and modifies the operations package but the agent still uses the legacy functions.

EVG-7167 add routes to get project with bson

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7724
Make the change to the .evergreen.yml location (#3316) compatible with non-userdata spawn hosts.

EVG-7724: fix permissions on evergreen yaml for spawn host

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7716
Use yaml instead of json for readability. Also, if people ever try to update the evergreen config, it will have to be in yaml format.

EVG-7716: write evergreen config as yaml instead of json

---

model/host/db.go
model/host/host.go
units/provisioning_setup_host.go

Set HomeVolumeID so in future retries we continue to attach using the already created volume.

EVG-7746 use created volume in retry attempts

---

globals.go
gqlgen.yml
graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/task/data.json
graphql/tests/task/queries/spawnHostLink-distro-provider-docker.graphql
graphql/tests/task/queries/spawnHostLink-distro-provider-static.graphql
graphql/tests/task/queries/spawnHostLink-no-host.graphql
graphql/tests/task/queries/spawnHostLink-spawn-not-allowed.graphql
graphql/tests/task/queries/spawnHostLink.graphql
graphql/tests/task/results.json

https://jira.mongodb.org/browse/EVG-7531
This field will be used to link to the Spawn host page from the task metadata panel in Spruce.

EVG-7531: spawnHostLink field in Task GQL type

---

units/patch_intent.go

We ignore warnings and don't report them during patch intent creation.

EVG-7680: only return early if patch contains errors

---

public/static/app/perf/perf.js
public/static/js/filters/filters.common.js

Previously, we were attempting to match the execution number on previous iterations for a task when converting trend data, but that should not be done at all

EVG-7640 fix trend data from cedar getting incorrectly filtered

---

graphql/tests/task/data.json
graphql/tests/task/queries/spawnHostLink-distro-provider-docker.graphql
graphql/tests/task/results.json

apparently docker does need to be a spawnable provider type, so removing this test

EVG-7531 remove docker test

---

service/ui.go

https://jira.mongodb.org/browse/EVG-7432
Spruce utilizes the login and logout endpoints for authentication. These changes are necessary for spruce to work in staging and prod environments. However these changes will be removed once @john-m-liu configures Spruce to use okta for authentication. 
RELATED TO PR https://github.com/evergreen-ci/spruce/pull/130

EVG-7432: enable CORS for login and logout endpoints

---

public/static/js/filters/filters.common.js
public/static/js/filters/filters.test.js

Data from cedar returns test results for each thread in a separate document, which the previous conversion code was not handling at all. I had to guess at the format based on existing examples, but modified it to merge thread results into a single doc when converting

EVG-7609 handle multiple thread results coming from cedar

---

cloud/user_data.go
cloud/user_data_test.go
model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7813
This change only matters for Windows.
We've been relying on build to let us run user data after after a Windows host is created (because it restarts several times and runs the image has its own user data that runs before ours does). You can only run user data once on Windows unless you do one of these: 
1. You reset the "user data ran" flag (which has been done in buildhost-configuration up until now). It won't run if you run user data (which is done in the AMI to initialize disks) and upload more user data (which we rely on for host provisioning). As part of incremental builds, they're removing the user data reset.
2. You add the "persist" tag to your script, which means that the script will run every single time the host is restarted.
The …

EVG-7813: add persist tags for Windows user data shell scripts

---

model/distro/db.go
scheduler/utilization_based_host_allocator.go
scheduler/utilization_based_host_allocator_test.go
service/templates/distros.html
units/crons.go

I very rarely touch the scheduler (yay for new things!) so let me know if I've gone about this all wrong.
I also considered an additional distro field so we would only do this for distros that are workstation clusters; however, in the DB it looks like we only even have one disabled distro so I'm not convinced it's necessary.

EVG-7676 start min hosts for disabled distros

---

cloud/ec2.go

I'm not sure if this is the extent to what you wanted.
We could alternatively have two jobs: a job that requests Stop and sets to stopping, and then a cron job that checks hosts in the Stopping status to see if they've stopped. Depends on how much trouble this is actually causing.

EVG-7797 cleanup StopInstance

---

globals.go
model/host/db.go

New host provisioning allows hosts to begin to run tasks before they are in the
running status. This means that new hosts might not be counted by the
NumHostsByTaskSpec query, which causes a race in task group task dispatching in
which multiple tasks in a single-host task group can run concurrently on several hosts.

EVG-7681 Count provisioning host status task group task count

---

model/generate.go

JIRA: https://jira.mongodb.com/browse/EVG-7678
Apparently mainline commits don't have patch documents.

EVG-7678: make patch document optional for mainline commits generating tasks

---

public/static/partials/user_host_options.html

The UI seems broken due to this tag so you can't actually select the desired volume.

EVG-7725: fix span closing tag in volume dropdown

---

public/static/app/perf/perf.js

The problem is that for trend data with the same create_time, sorting by just that field can leave it in the wrong order, where "right" is the order in which the commits were pushed. This is really a band-aid to both fix this problem and not re-break sorting for patch builds, since the behavior for patches isn't really defined and the data is not readily available in the trend data.
Opened https://jira.mongodb.org/browse/EVG-7820 for the tech debt part

EVG-7653 use a secondary sort for perf data with the same create time

---

trigger/task.go
trigger/task_test.go

Sorry about all our previous other conversations; this change should allow us to make no database changes (yay!).
The change to task's selectors makes it so GithubPR tasks will also match for Subscriptions made for patches. This may extend to other subscriptions as well, but if as you say users see PR patches and regular patches to be in the same category, then I think this change is logical.

EVG-7859 trigger patch notifications with PR patches

---

graphql/generated.go
graphql/schema.graphql
graphql/tests/patch/queries/createTime-does-not-exist.graphql
graphql/tests/patch/queries/createTime-exists.graphql
graphql/tests/patch/results.json

https://jira.mongodb.org/browse/EVG-7863
This field is meant to be displayed in the My Patches underneath the patch description

EVG-7683: Add createTime field to Patch gql type

---

graphql/generated.go
graphql/models_gen.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/patchTasks/queries/all-params.graphql
graphql/tests/patchTasks/queries/count.graphql
graphql/tests/patchTasks/queries/filter-by-bad-task-name.graphql
graphql/tests/patchTasks/queries/filter-by-bad-variant.graphql
graphql/tests/patchTasks/queries/filter-by-base-status.graphql
graphql/tests/patchTasks/queries/filter-by-multiple-statuses.graphql
graphql/tests/patchTasks/queries/filter-by-status.graphql
graphql/tests/patchTasks/queries/filter-by-task-name.graphql
graphql/tests/patchTasks/queries/filter-by-variant-partial-search-term.graphql
graphql/tests/patchTasks/queries/filter-by-variant.graphql
graphql/tests/patchTasks/queries/limit-and-pagination-1.graphql
graphql/tests/patchTasks/queries/limit-and-pagination-2.graphql
graphql/tests/patchTasks/queries/no-params.graphql
graphql/tests/patchTasks/queries/sort-base-status-descending.graphql
graphql/tests/patchTasks/queries/sort-by-base-status.graphql
graphql/tests/patchTasks/queries/sort-by-name.graphql
graphql/tests/patchTasks/queries/sort-by-status.graphql
graphql/tests/patchTasks/queries/sort-by-variant.graphql
graphql/tests/patchTasks/queries/sort-descending.graphql
graphql/tests/patchTasks/results.json
graphql/util.go
model/task/task.go
rest/data/interface.go
rest/data/task.go

https://jira.mongodb.org/browse/EVG-7737
The numerator in the task count on the patch page. It currently represents number of paginated tasks fetched; it increases as user scrolls. this fixes it so that denominator = total patch task count. numerator = total # tasks that match filter criteria

EVG-7737: add filtered task count field to patch tasks query

---

command/s3_get.go
command/s3_get_test.go
command/s3_put.go
model/project_event_test.go
model/project_vars.go
model/task_config.go
public/static/js/projects.js
rest/data/project.go
rest/model/project_event.go
rest/route/project_copy.go
service/api.go
service/project.go
service/templates/projects.html

For restricted variables, I don't want to duplicate the logic of private variables as well/allow for programmer error with ensuring restricted variables are also private variables -- I think it's okay to trust the user to make restricted variables private.

EVG-7037 add restricted project vars for safe commands

---

config_hostinit.go
model/host/db.go
model/host/host_test.go
rest/data/admin_test.go
rest/model/admin.go
service/templates/admin.html
units/host_status.go
units/host_status_test.go

this is super hacky, but I thought it was less bad than other alternatives
- set an arbitrary limit of 500 for hosts we'll check cloud status for so that the aggregation does not get an intermediate stage that's too big (we hit the problem at ~2000)
- terminate hosts that AWS can't find

EVG-7864 more robust handling in set-cloud-hosts-ready

---

rest/route/user.go

the nil value is not a nil interface quirk strikes again

EVG-7741 fix route if adding role to unidentified user

---

model/project_parser.go
model/project_parser_test.go

This is a nuanced change so let me know if you don't follow:
We were getting warnings from YamlStrict about tasks having Status dependencies. This came from the TaskSelector unmarshaller, because Status is a field of ParserDependency, not TaskSelector. 
The reason ParserDependency even calls a TaskSelector is for single-string dependencies (for which we would unmarshal into a string). If ParserDependency only tries to do this if a normal unmarshal errors (i.e. we probably have a single string selector) then this should unmarshal correctly (and if it can't for good reason, it should still error in the second phase of the TaskSelector unmarshaller).

EVG-7865 parserDependency only unmarshals taskSelector on error

---

auth/auth.go
model/user_lifecycle.go
model/user_lifecycle_test.go
rest/route/service_test.go
rest/route/user.go
rest/route/user_test.go

I think this will still work correctly in the case where the user document is created before the user actually logs in, but I'm not 100% confident
- Allow setting a user's roles when we first create the user
- Change the role adding route to create a shell user if the user doesn't exist, so that they will have the given roles when they first log in

EVG-7741 allow creating new users for onboarding

---

command/s3_pull.go
command/s3_pull_test.go
operations/pull.go

JIRA: https://jira.mongodb.org/browse/EVG-7895
If a pail bucket uses `Pull()`, it no-ops if there is no matching content. This validates that there's at least one item in the bucket before pulling.

EVG-7895: error if S3 task sync contents are empty when pulling

---

service/waterfall.go

To explain what's going on:
When going through the versions, if we find a build with no display name in the buildVariantMappings, we set the build variant display name to be the build's display name (this is why display names still show up correctly in the waterfall).
_However,_ we sort by iterating through bvSet, and if there is no display name in the buildVariantMappings we use the ID instead (this is the structure we use for sorting, which is why we sometimes sort by ID).

EVG-6916 add build variant display names to mapping

---

model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/task/db.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go
rest/data/patch.go
rest/data/version.go
service/api_patch.go
service/api_task.go
service/build.go
service/task.go
service/templates/task.html
service/version.go
units/patch_intent.go

Make it apparent why a task was aborted when:
- the task was cancelled because another task failed (for the commit queue)
- the task was cancelled when another version superseded it (a new commit was pushed to the PR)
- the task was cancelled because the PR was closed
- a user aborted the task
Save the reason in the task document and display it on the task page.

EVG-7262 aborted tasks

---

model/host/db.go
model/host/host.go
units/generate_tasks_test.go
units/host_monitoring_idle_termination.go

JIRA: https://jira.mongodb.org/browse/EVG-7809
This evaluates a user data host for idle termination if it's stuck in the provisioning state but has an agent that has run tasks. Before, it if managed to run tasks before the cutoff and was stuck in the provisioning state forever, it would never be terminated. This only occurs if the setup host job was unable to retry (most likely because the app server was restarted). However, with the recent changes to the setup host job so that it can retry without relying on the job to re-enqueue itself and this change, it should no longer be an issue.

EVG-7809: evaluate idle termination if provisioning cutoff is passed

---

model/user_lifecycle.go

Not urgent, but cleans this up a bit. This function is called every time we re-authenticate a user. Only when the user is first created by the roles route should we be updating roles

EVG-7741 don't update roles after initial insert

---

model/user/user.go

this will allow our rest APIs to noop if someone tries to add a duplicate role, which will make handling edge cases in mana easier

EVG-6367 noop attempts to add duplicate roles

---

model/generate.go
model/generate_test.go
units/generate_tasks.go

JIRA: https://jira.mongodb.org/browse/EVG-7804
The errors are accumulated but never used. Alternatively, if we think this actually requires error handling, we could just return/log the error.

EVG-7804: return errors from MergeGeneratedProjects

---

service/task.go

If the host was created before a distro was updated, some parameters may be out of date that we would want to refresh (i.e. maybe just SpawnAllowed) so we should check the existing distro configuration.
My only question is if a host was created before SpawnAllowed was set to False, should we still allow the task to spawn a host? I assume not.

MCI-3215 check host can spawn from task before loading task page

---

service/ui_plugin_build_baron.go
units/event_metajob.go
units/event_send.go
units/event_send_test.go

#2774 added a step to the event-metajob to catch unprocessed notifications and enqueue a new job for them, but the id of the new job collides with the original so it's not inserted. 
Add a timestamp to the job ID.

EVG-7921 add timestamp

---

config.go
operations/commit_queue.go

Give every commit queue patch a label to make it clear which patches are for the commit queue.
For example:
```
Commit Queue Merge: 'SERVER-12345 message' into 'mongodb/mongo:master'
```
This was originally the intention of #3047 but needed to wait for the changes to pass commit queue validation. https://github.com/mongodb/mongo/commit/09b9e9316877084501db453d08510345465a6770 added this format so both the new and old formats pass validation.

EVG-7190 standardize commit queue patch descriptions

---

model/host/db.go
model/host/volume.go
model/host/volume_test.go

The way the query had been written was querying the host collection with an unindexed field (`volumes.volume_id`).
Use the host id in the volume document instead.

EVG-7948 fix volume expiration query

---

graphql/generated.go
graphql/integration_spec.json
graphql/resolvers.go
graphql/schema.graphql
graphql/testdata/task1.graphql
graphql/tests/task/data.json
graphql/tests/task/queries/patchNumber.graphql
graphql/tests/task/results.json

https://jira.mongodb.org/browse/EVG-7682
Remove the patchNumber field because it represents the same thing as the order field on the Task gql type. https://github.com/evergreen-ci/spruce/pull/155 should be merged before this PR to avoid gql errors in Spruce.

EVG-7682: Remove patchNumber field from Task gql type

---

public/static/js/spawned_hosts.js

I'm a little unclear on what all is going on with window.location, but it looks like if we just do "reload" then we don't refresh the stale data when spawning from task.

EVG-7938 refresh link after creating host

---

command/attach_artifacts_test.go
command/scripting.go

This is primarily to avoid having the user specify duration in nanoseconds.

EVG-7969: duplicate scripting test options struct

---

config.go
operations/http.go
service/api_patch.go

https://github.com/evergreen-ci/evergreen/commit/f036124c01bd7de98e2b03e660636d08634a6fe9 added a copy of patches that gets base64 encoded over the wire.
The string version is no longer necessary and now that enough users have updated their CLI it should be okay to remove.

EVG-7248 patch string cleanup

---

public/static/app/perf/perf.js

There are links from the perf BB/discovery pages to specific tests on the trend chart which use the location hash like a normal HTML bookmark. The trend charts separately try to encode state as json within the hash (yuck), and don't handle any other formats. This is a band-aid fix to be able to handle both scenarios

EVG-7636 handle bookmarks in trend chart URL

---

model/task/task.go
trigger/task_jira.go
trigger/task_jira_test.go

The link to task logs stopped working when failing execution tasks were grouped together in one BFG (#3281) since the link points to the display task's (inexistent) logs.
This PR will change the links for display task BFGs to look like this:
```
Task Logs (test1 test2)
Task Logs (test3 test4)
```
Grouping tests by execution task will also make it easier to identify when a task went off the rails and caused its tests to fail.

EVG-7597 BFG display task logs

---

model/repository.go
rest/route/github.go

From [this panic](https://mongodb.slack.com/archives/C866SR2LR/p1589469424008500), the nil interface problem has come back to haunt us.
However, from [splunk](https://mongodb.splunkcloud.com/en-US/app/search/search?q=search%20index%3Devergreen%20%22adding%20tag%20to%20version%22&display.page.search.mode=verbose&dispatch.sample_ratio=1&earliest=1589428800&latest=1589515200&sid=1589470641.2161980), the pusher of these tags might be legitimate bots (for example, mms-build-account), so I think we want to remove this strict validation so these tags can still show on the waterfall. Potentially we could still make Authorized Users strictly limited to real users and not bots, but I think it's okay to allow that flexibility.

EVG-7623 remove strict user validation in github webhook

---

public/static/partials/user_host_options.html

Basically I just moved the `ng-show` visibility to a div that includes the checkbox and text.

EVG-7962: hide task sync text if disabled

---

model/host/host.go
units/provisioning_agent_monitor_deploy.go
units/provisioning_convert_host_to_legacy.go
units/provisioning_convert_host_to_legacy_test.go
units/provisioning_convert_host_to_new.go
units/provisioning_convert_host_to_new_test.go
units/provisioning_jasper_restart.go

JIRA: https://jira.mongodb.org/browse/EVG-7904
* Document the meaning of the different host provisioning constants so we don't misuse them or misunderstand them.
* Use the constants consistently according to their semantic meaning.

EVG-7904: document host provisioning constants and use them consistently

---

graphql/resolvers.go
graphql/tests/task/results.json

This is a fix for the task patch metadata resolver. All base commits have version IDs, therefore `FindPatchById` was throwing an error because ID is not a Mongo `ObjectId`. The fix is to use `FindVersionById` which will work for both Patch and Version IDs.

EVG-7776: use FindVersionById to get patch metadata

---

cloud/cloud.go
cloud/docker.go
cloud/ec2.go
cloud/ec2_fleet.go
cloud/gce.go
cloud/mock.go
cloud/openstack.go
cloud/static.go
cloud/vsphere.go
model/host/host.go
units/provisioning_setup_host.go
units/provisioning_user_data_done.go

Reinstating scopes on `provisioning-setup-host` and `user-data-done` jobs now that they won't break amboy (hopefully). Will need to monitor the amboy dashboard after it's deployed.
Also, string matching on the AWS error was sketchy. If trying to attach the volume returns an error ask AWS if the volume is attached to **this** instance and continue on error if it is.

EVG-8010 terminated workstations

---

globals.go
graphql/resolvers.go
graphql/util.go
model/build/db.go
model/generate.go
model/grid/grid.go
model/lifecycle.go
model/project.go
model/task_history.go
model/version.go
model/version_db.go
repotracker/repotracker.go
repotracker/repotracker_test.go
rest/client/rest.go
rest/data/version.go
rest/model/build.go
rest/route/stats.go
rest/route/version_create.go
scheduler/task_prioritizer.go
service/rest_version.go
service/task_history.go
service/timeline.go
service/ui_plugin_manifest.go
service/version.go
trigger/process_test.go

I could use some thoughts on this ticket: 
I want to create a new requester GitTagRequester that is also used for displaying the waterfall. But it looks like we use SystemVersionRequesterTypes for the waterfall and also a lot of logical things.
I've only modified the query used for displaying versions on the waterfall to include GitTagRequester, but is there somewhere else I should be considering?

EVG-7990 add git tag requester

---

globals.go
graphql/util.go
model/distro/distro_test.go
model/lifecycle.go
model/lifecycle_test.go
model/patch_dependencies.go
model/patch_lifecycle_test.go
model/project.go
model/project_parser.go
model/project_parser_test.go
model/project_test.go
model/version_db.go
rest/route/distro_test.go
util/bool.go
validator/project_validator.go
validator/project_validator_test.go

This mildly depends on EVG-7990 but only because of the requester, I think I can re-base this later.
Tasks with `git_tag_only: true` should only be able to run for the GitTagRequester type, so mainline builds and patches should ignore it. This means that `patchable: false` a subset of GitTagOnly since these are already not patchable, and PatchOnly contradictory as they shouldn't be able to be patched.

EVG-7626 add git_tag_only option for tasks/variants

---

globals.go
operations/host_spawn.go
units/provisioning_setup_host.go
units/provisioning_setup_host_test.go

The strategy is:
```
If (the volume is fresh) {
mount the volume on the instance (somewhere that's not ~)
copy the contents of the home directory into the volume
umount 
}
mount on ~
```
If it's being migrated from another instance (I've used whether it has a filesystem as a proxy for this) just mount on ~. I considered moving the preexisting contents into a `old_home` directory and copying the new instance's home like we do for fresh volumes, but it was decided leaving the user's configuration in place would be less confusing for users and that the image's ~ would be relatively static between workstation distros.
I considered cp'ing the contents of ~ to another place on the root partition, mounting, and mv'ing the contents into the volume. I worried this approach wouldn't work if the …

EVG-8028 mount on ~

---

model/host/volume.go
public/static/partials/user_host_options.html
rest/model/host.go
units/provisioning_setup_host.go

https://github.com/evergreen-ci/evergreen/commit/0da1ec1e1367fc65810c69edab58f6ae3198d961 mounts a volume on ~. If the volume has a filesystem we don't copy anything onto them on the assumption the home contents of the previous instance will work on the next. We need to prevent users from mounting other volumes they've created (and potentially created a filesystem on) that have never been a workstation's home directory.
Admittedly this is not a common case going forward, but if users migrate from existing workstations which didn't mount on ~ to new ones which do they will have problems...

EVG-8028 remove non-home volumes from volume list

---

graphql/resolvers.go
graphql/util.go
model/commitqueue/commit_queue.go
model/version.go
model/version_test.go
rest/data/commit_queue.go
rest/data/commit_queue_test.go
service/build.go
service/task.go

We were calling RemoveCommitQueueItem using a versionID, but this only worked for CLI queues because the item issue would equal the versionID. Instead we should have different deletions for issue or for version.

EVG-7993 distinguish between issue and version when removing from cq

---

globals.go
operations/host_spawn.go
units/provisioning_setup_host.go
units/provisioning_setup_host_test.go

Reintroduce the changes from #3610 which were reverted because they broke provisioning for workstations.
The issue was not caught in staging because the distro I was testing on had an additional volume besides the root volume and the home volume. Without the intervening volume we were getting the root volume and thinking it was the home volume, since the volume is partitioned.

EVG-8028 reintroduce home mount

---

model/task/results.go
model/task/task.go
model/task_lifecycle.go
model/task_lifecycle_test.go
units/task_monitor_execution_timeout_test.go

While I think the logic with unstartedTasks is also wrong, I think the actual case brought up in the ticket comes from the first part of [this line](https://github.com/evergreen-ci/evergreen/blob/master/model/task_lifecycle.go#L1147) `statusTask.Status != evergreen.TaskFailed `.
I'm not 100% sure what you were trying to do in the original ticket @ybrill but given the description about SystemFailed I think we should only set display task as finished early in the system failed case (if at all).

EVG-7596 consider started tasks when updating display task status

---

model/host/hostutil.go

[patch build](https://evergreen.mongodb.com/version/5eceaf3832f41719ac97a74f) to make sure dist works

MAKE-1152: Use MaxInt32 instead of MaxInt64

---

agent/agent.go
agent/agent_command_test.go
agent/agent_test.go
agent/agent_timeout_test.go
agent/task.go
agent/testdata/agent-integration.yml
apimodels/agent_models.go
config.go
model/project.go
model/project_parser.go
model/project_parser_db.go
rest/model/codegen.go
rest/model/task.go
service/templates/task.html

Run the oom tracker in the agent. The messages are cleared just before the task's commands run and the messages are checked when they complete or time out.
Add the results to the task's status details so it's stored in the db and accessible through the API. Also add to the task card.

EVG-1134 oom killer

---

model/host/hostutil.go
model/host/hostutil_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7983
The `.evergreen.yml` file used to written to `~/cli_bin` but is now written to the home directory. Therefore, we had to change the owner of the file to the distro user because the file already existed as a leftover artifact from AMI creation (which also uses evergreen, so it created a `~/.evergreen.yml` owned by the privileged user and is baked into the AMI). However, some distros (e.g. debian) seem to not have this file, so we have to make this command optional.

EVG-7983: allow changing owner of existing evergreen yaml optional on spawn hosts

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/patch-taskStatuses/data.json
graphql/tests/patch-taskStatuses/queries/baseTaskStatuses.graphql
graphql/tests/patch-taskStatuses/queries/taskStatuses.graphql
graphql/tests/patch-taskStatuses/results.json
graphql/util.go
model/task/task.go
rest/data/interface.go
rest/data/task.go

Resolver that gets all tasks for a patch. Will be used to dynamically render the patch task statuses in the dropdown on patch details page.

EVG-8021: fields on Patch gql type for all task statuses

---

public/static/app/perf/perf.js
public/static/app/perf/perf.test.js
public/static/app/perf/trend_chart.js
public/static/app/perf/trend_chart.test.js
service/templates/task_perf_data.html

Note there is 1 breaking change here - I've refactored how the trend charts/task page handle the URL hash and changed the format to not encode a JSON object in the URL. This means that existing links that people have posted will just link to the task without doing anything extra (I expect that most of the "extra" things are saved comparisons). Let me know if you think this is a problem.
The following changes to trend charts will be persisted in the URL hash to make sharing them possible. Some of these somewhat worked before, and some are new features
- Collapsed graphs
- Comparisons (both tag and commit hash)
- Selected metric
- All/max thread radio button
- Thread levels for specific tests

EVG-7900 save more in URL for trend charts

---

apimodels/agent_models.go
command/host_create.go
command/host_create_test.go

Move parsing from a file out of ParseParams, to its own method called in expandAndValidate. Parsing from a file in ParseParams doesn't work since the file is not yet available at that point.

Evg 7915: Allow passing a file to host.create

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/user/data.json
graphql/tests/user/queries/user.graphql
graphql/tests/user/results.json
rest/model/user.go

User ID is needed in parts of the UI, such as for generating the href for the 'user patches' link, which will be `/user/:userId/patches` (the new 'my patches' url)

EVG-8057: add userId to user query

---

cloud/docker.go
cloud/ec2_util.go
model/host/host_intent.go
rest/data/host_create.go
rest/data/host_create_test.go
rest/route/host_create_test.go

Cloud used "archlinux-parent" as the docker distro instead of a docker distro, so pool was nil.

EVG-8088 only allow distros with container pools for docker hosts

---

model/user/user.go
service/patch.go

If a user is opted into spruce v1, they will be redirected from `evergreen.mongodb.com/patch/:id` to `spruce.mongodb.com/patch/:id/configure`
This allows us to redirect users to Spruce when they click on a patch link from the CLI

EVG-8061: redirect opted in users from legacy patch page to Spruce reconfigure page

---

config.go
model/project_ref.go
model/project_ref_test.go
operations/host_spawn.go

The working directory for commands is validated before we actually run the command so we need to mkdir first.
When the directory doesn't exist we prepend a mkdir command. Subsequent commands will have their working directory set by the PreHook.
A separate bug was the command logging. When we log the command being executed we were logging the last project command for every command. The reason appears to be that when the Prerequisite function executes it captures the current value of the obj variable (which changes as we iterate over the slice). Storing in a separate variable fixes the issue.

EVG-8113 fix project setup commands

---

rest/model/codegen.go
rest/model/codegen_test.go
rest/model/templates/field.gotmpl
rest/model/templates/service_methods.gotmpl
rest/model/testdata/expected/basic.go
rest/model/testdata/schema/basic.graphql
rest/model/testdata/schema/config.yml

This connects the 2 previous parts. Given a schema for what you want the REST model to look like as well as the db model it's connected to, we will generate the struct and conversion code. Still needs work on handling complex types and validation (coming soon)

EVG-8026 connect struct and conversion code generation

---

rest/model/codegen.go
rest/model/codegen_test.go

I have absolutely no idea why this fails only with the -race flag, why the other test that calls into the same code doesn't fail, and how this is able to compile while hitting this error, but at least it'll make the build green

EVG-8073 skip code gen test on race detector

---

service/timeline.go

'Patches' link in the legacy dropdown will redirect to Spruce user patches page if user is opted into Spruce.

EVG-8057: redirect spruce users from legacy my patches to spruce

---

model/distro/distro.go
model/distro/distro_test.go
model/event/distro_event.go
model/event/distro_event_test.go
rest/route/distro.go
service/distros.go

The context for this is that []*birch.Document is showing up as nil for event logs: I believe it has something to do with the way MongoDB inserts interfaces because this isn't something that happens for distros. 
Because the event package has to use interfaces because of import cycle drama, we have to live with the interface nonsense. I propose changing the structure of the event log so that provider setting data can still be seen.
If you have a different idea let me know.

EVG-8039 use different structure for distro event logs

---

model/project.go

This change isn't much but maybe it'll help users more clearly understand that the warning is their fault (a misnamed field for commands would now give this warning:
```
WARNING: input fields may not match the command fields: yaml: unmarshal errors:
line 832: cannot unmarshal !!seq into struct { Function string "yaml:\"func,omitempty\" bson:\"func,omitempty\""; Type string "yaml:\"type,omitempty\" bson:\"type,omitempty\""; DisplayName string "yaml:\"display_name,omitempty\" bson:\"display_name,omitempty\""; Command string "yaml:\"command,omitempty\" bson:\"command,omitempty\""; Variants []string "yaml:\"variants,omitempty\" bson:\"variants,omitempty\""; TimeoutSecs int "yaml:\"timeout_secs,omitempty\" bson:\"timeout_secs,omitempty\""; Params map[string]interface {} …
```

EVG-8031 reword evergreen validate error

---

model/project_aliases.go
model/project_parser.go
model/repository.go
model/version.go
repotracker/github_poller.go
repotracker/repotracker.go
repotracker/repotracker_test.go
rest/data/aliases.go
rest/data/aliases_test.go
rest/data/interface.go
rest/data/project.go
rest/data/version.go
rest/route/github.go
rest/route/github_test.go
rest/route/testdata/release.yml
service/templates/projects.html
trigger/project_triggers.go

Users can either define project aliases the normal way, or using a new yaml file. If multiple git tag aliases match, then it has to be the normal way, since we shouldn't have to do any processing with the new yaml. Defining using aliases will be tested in another ticket. 
From staging test (pre author changes): https://evergreen-staging.corp.mongodb.com/version/yb_mci_testing1_5ed6deb69dbe320829565557

EVG-7627 trigger version from git tag (using yaml)

---

service/api_task.go

To determine if task groups running out of order is from a race because earlier tasks in the groups failed.

EVG-7903 add debugging logs for task groups

---

graphql/generated.go
graphql/integration_spec.json
graphql/schema.graphql
graphql/testdata/task1.graphql
rest/model/task.go
rest/model/task_test.go

https://jira.mongodb.org/browse/EVG-8016
a link to the html event logs for the task log page in Spruce

EVG-8016: add eventLogLink to Task type log field

---

command/results_gotest.go
command/results_gotest_parser.go
command/results_gotest_parser_test.go
command/scripting.go
command/scripting_test.go
config.go
self-tests.yml

JIRA: https://jira.mongodb.org/browse/EVG-8151
This gets around having an extra step where we would have to create a file and call `gotest.parse_files` on the output of `subprocess.scripting`.
* `subprocess.scripting` supports reporting non-JSON go test results.
* Drive-by fix various bugs in `subprocess.scripting`.
* Refactor go test parsing functions so that it can be shared between `gotest.parse_files` and `subprocess.scripting`.

EVG-8151: report go test results from subprocess.scripting

---

service/task.go
service/templates/task.html

[EVG-8053](https://jira.mongodb.org/browse/EVG-8053)
Shorted aborted by from "taskID" to "build display name:task display name". 
Previous: 
Post change (different task data):

EVG-8053 Aborted by task name is too long

---

rest/model/commit_queue.go
rest/model/commit_queue_test.go
rest/route/github.go
rest/route/github_test.go

[EVG-7929](https://jira.mongodb.org/browse/EVG-7929)
Note, this trims leading and trailing whitespace, not duplicate whitespace between words.

EVG-7929 Trim whitespace when matching on github comments

---

model/host/db.go
service/api_task.go

My new theory is that the statuses used in NumHostsByTaskSpec are wrong, because we're hitting[ this race](https://github.com/evergreen-ci/evergreen/blob/5c5e0fa5ce1f1d9a20f8117604350af98440c959/service/api_task.go#L577) in a case where I can't find logged evidence of a race.

EVG-7903 add task group race debugging logic

---

units/provisioning_create_host.go

converted 'problem removing intent host' and 'could not find host' from errors to warning

EVG-7916 Make provisioning-create-host job errors reflect actionable problems

---

model/project_ref.go
rest/data/project.go
service/project.go
service/templates/projects.html
units/crons.go
units/crons_remote_five_minute.go
units/repotracker.go

This change can't be committed until we've modified the projects that are currently using the legacy repotracker to stop using it. Because we still use the repotracker for catchup jobs and github webhooks, the repotracker itself doesn't seem to need edits.
Note: I don't want to hide repotracker settings if webhooks aren't enabled since people might not expect that / understand why those are related, which is why I'm keeping the section but adding a new warning.

EVG-8203 remove support for legacy repotracker

---

model/patch/db.go

https://jira.mongodb.org/browse/EVG-8200
This change will allow users to fetch large amount of patches without running out of memory

EVG-8200: Increase performance of UserPatches query

---

graphql/generated.go
graphql/resolvers.go
graphql/schema.graphql
graphql/tests/task/results.json

https://jira.mongodb.org/browse/EVG-8133
originally we were throwing an error when a baseTask did not exist. this prevented the user from viewing a task without a base task in spruce.

EVG-8133: make baseTaskMetadata nullable

---

rest/data/repotracker.go
rest/data/repotracker_test.go

If we need to debug, this case will still log here and we will see no project refs have been processed. https://github.com/evergreen-ci/evergreen/blob/890ae52fcb0ce2c019c163bc26f63097bec16c88/rest/data/repotracker.go#L121

EVG-7045 return 200 code from github webhook for no matching projects

---

units/provisioning_jasper_restart.go

JIRA: https://jira.mongodb.org/browse/EVG-8259
Allow hosts that are provisioning/running to restart jasper, which is only safe to do if the host is not running a task (since restarting jasper will shut down the agent and agent monitor and we wouldn't want this to abruptly system fail a task).
This change should be safe because there's a check [here](https://github.com/evergreen-ci/evergreen/blob/bd4afd4af6d8ea1e5b3bf7abfc8955170969db1d/units/provisioning_jasper_restart.go#L139-L149) to verify that 1. the host is not running a task and 2. the host is not running an agent monitor (which fulfills the conditions to restart jasper).

EVG-8259: allow running hosts to restart jasper service

---

config.go
model/patch/patch.go
operations/patch_util.go
service/patch.go
units/patch_intent.go

The patch configure page now uses the same pattern as the other ones, meaning you have to add something extra in the URL to go to spruce

EVG-8285 don't redirect by default in configure page

---

model/project_ref.go
operations/service_deploy_smoke_utils.go
rest/data/project.go
rest/route/project.go
rest/route/service.go
service/project.go
service/templates/projects.html
units/crons.go
units/crons_remote_five_minute.go
units/repotracker.go

The first commit doesn't need review. My only question is should triggering the repotracker via route be restricted by more than just user (and how that will work with smoke).

EVG-8203 remove support for legacy repotracker (#3664)

---

command/registry.go
globals.go
model/project.go
rest/data/host_create.go
validator/project_validator.go
validator/project_validator_test.go

So it could output separate messages now:
```
ERROR: project config may only call ec2 host.create 50 time(s) but it is called 54 time(s)
ERROR: project config may only call docker host.create 200 time(s) but it is called 205 time(s)
```

EVG-8087 validate host.create counts by provider

---

model/task_json.go
model/task_json_test.go

Although the [task](https://evergreen.mongodb.com/task/sys_perf_linux_standalone_validate_cmd_patch_aef7cbf49c396df95c02606a9e94d26c892e53ed_5e72767c1e2d17595813fb53_20_03_18_19_52_18) linked in the ticket doesn't seem to have this error (the task exists on the base commit too), it's still possible for cases where the task doesn't exist on the base commit.
My change is to find the base commit's revision order number from the task's base version (having the same revision). This will always be the same as tasks' revision order numbers.

EVG-7606 find base revision order number from the base version

---

repotracker/repotracker.go

Changing to retry on all errors because the error labels come from both the server and the driver, and I don't trust that interaction enough to have the repotracker rely on it

EVG-7403 retry on all errors in repotracker

---

auth/only_api.go
auth/only_api_test.go
operations/service_web.go

[EVG-7835](https://jira.mongodb.org/browse/EVG-7835)
Instead of returning when the setupUserManager fails, log an EmergencyFatal error and continue to start the app. 
Question for reviewers: Does this need to be tested? Any suggestions?

EVG-7835: app shouldn't fail to start if an api_only user is misconfigured	

---

apimodels/runtime_models.go
model/project_ref.go
operations/host_spawn.go

In order to allow scripts to get input from a user we need to pass stdin through to the jasper command that runs the script. The SenderWriter that was wrapping stdout was causing issues too (because it doesn't flush until it hits a \n), so I replaced it with `os.Stdout`. The script's errors should go to our stderr as well (not stdout), so I replaced that too.

EVG-8204 pass through standard streams

---

graphql/util.go
rest/data/patch.go
service/api_patch.go
units/patch_intent.go

This is to show when patches are created and finalized (and from where), as well as what tasks/variants were scheduled (and at what point).
I used "operation"="patch creation" instead of "source"="patch intent" since the latter also includes logs for github PR patches and etc, but I'm open to changes around the log naming.

EVG-8067 add logging around patch creation

---

model/host/host.go

[EVG-6895](https://jira.mongodb.org/browse/EVG-6895)
`modify --host <hostID> --expire  --extend 5  ` didn't work properly, because even if it was already set to expire, --expire would set  `h.ExpirationTime = time.Now().Add(evergreen.DefaultSpawnHostExpiration)`. The time was reset before adding on the desired extension time, causing it to update to the wrong time.

EVG-6895 evergreen host modify should update expiration on UI

---

repotracker/repotracker.go

The issue is definitely similar to what we were referring to earlier this week: the repotracker is trying to catch up on old revisions. We’re supposed to be hitting this thirdparty.FileNotFoundError, and the root error is "Requested file at .evergreen2.yml not found" but it turns  out we're not because I decided to [wrap the error](https://github.com/evergreen-ci/evergreen/pull/3644/files) in a refactor.
I am perplexed about how [the commit it’s failing on](https://github.com/10gen/mms/tree/8ad61471afd1a54c9543acf37b0da3ed95cc8574) doesn't have the requested file considering the commit before does have it, but 🤷

EVG-8294 look at the cause of repotracker errors

---

model/host/db.go
service/api_task.go
service/api_task_test.go
service/ui.go

I believe the race looked like this:
1) host1 gets task1 and sets as running task
2) host2 gets task2 and sets as running task
3) host1 sees that there are 2 hosts running tasks for the task group, and there should only be one, so it unsets task1 as running 
4) host2 sees that there is 1 host running tasks for the task group, which is correct, and attempts to run task2, which fails.
Considering single_host_task_groups can rely on order mattering, I think we can handle this race condition using order instead.

EVG-7903 fix task group race

---

makefile

Sorry for the mega hacky solution, but I don't see any other way outside of switching to gomod. https://github.com/golang/tools/commit/e31c80b82c039b355c6214fa13610c2bf347612d made a change so that goimports executes go env partially using the default build environment, which on many (all?) of our build images will be using go1.7 which does not support the flag that goimports needs

EVG-12399 work around goimports vendoring problem

---

apimodels/buildlogger_models.go
config.go
config_logger.go
glide.lock
rest/client/client.go
rest/model/admin.go
service/api_buildlogger.go
service/api_buildlogger_test.go
service/templates/admin.html
vendor/github.com/evergreen-ci/timber/basic_sender.go
vendor/github.com/evergreen-ci/timber/glide.lock
vendor/github.com/evergreen-ci/timber/logger_producer.go
vendor/github.com/evergreen-ci/timber/makefile
vendor/github.com/evergreen-ci/timber/setup.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/makefile
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar.go
vendor/github.com/evergreen-ci/timber/vendor/github.com/evergreen-ci/aviation/services/cedar_test.go

JIRA: https://jira.mongodb.org/browse/EVG-9694
* Revendor timber.
* Add API key to admin logger settings.
* Dial into cedar GRPC service using API key if it's set in the admin settings.
* I'm going to migrate the admin settings once this is merged and before the deploy goes out.

EVG-9694: auth into buildlogger with API key instead of LDAP password

---

config.go

JIRA: https://jira.mongodb.org/browse/EVG-8311
This will log to `journalctl` since it logs before logging is initialized, but I'm going to check the app server logs once this is deployed. I suspect this isn't actually the problem, but it can't hurt to double check.

EVG-8311: add logging for slack logger setup

---

graphql/integration_spec.json
graphql/resolvers.go
graphql/tests/patch/results.json
graphql/util.go

In response to https://github.com/evergreen-ci/spruce/pull/279#discussion_r451265753
This pr formats the duration strings on the backend.

EVG-8145 Format duration strings on backend

---

model/task_lifecycle.go
model/task_lifecycle_test.go

Took a similar approach to RestartVersion.
(Note the title of EVG-6810, avoid parsing project in loop, no longer applies, but Ii'm handling the "don't try to restart execution tasks" comment, as well as avoiding multiple restarts).

EVG-6810 avoid restarting display tasks and task groups multiple times

---

model/task/task.go
model/task/task_test.go

JIRA: https://jira.mongodb.org/browse/EVG-12405
Some projects use priority in their waterfall tasks, which cause them to never be unscheduled after the underwater threshold (2 weeks). This doesn't actually fix the original problem that the task queue never empties out, but it prevents tasks from passing the underwater unscheduling threshold and lingering forever.
* Do not allow tasks with set priority to remain in underwater task queues.
* Minor fix for test that was depending on order of docs returned from a find query.

EVG-12405: unschedule underwater tasks with non-zero priority

---

validator/project_validator.go
validator/project_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7765
For example, this shouldn't be allowed since it should use either a command or a func:
```
task: foo
commands:
- func: bar
command: bat
```

EVG-7765: do not allow both a command and function to be specified

---

apimodels/agent_models.go
auth/auth.go
command/host_create_test.go
config_cloud.go
rest/model/admin.go
service/templates/admin.html

The problem is that for docker host.create, we require a distro to be given so that we know container pool information, but this is clunky for the user as they don't necessarily care about this.
Theoretically we don't need a distro at all because I think we  just need the container pool; however a lot of places in the code rely on hosts having a distro document correctly configured, so we'd have to build a partial distro with the passed in container pool and other configuration options. The other issue with this is that currently container pools are defined in admin settings, which users can't see, so having them specify this is just as clunky.
A default distro seems the best, since if users don't specify a distro for host.create they'll be none the wiser (I'll set Distro in Admin …

EVG-8094 set default docker distro from admin settings

---

rest/route/host_spawn.go

[EVG-12400](https://jira.mongodb.org/browse/EVG-12400)

EVG-12400 No error is displayed when modifying a host that is terminated

---

validator/project_validator.go
validator/project_validator_test.go

JIRA: https://jira.mongodb.org/browse/EVG-7751
Give validation warnings if tasks/build variants have names with special meaning.

EVG-7751: add warnings for tasks and buildvariants with special keywords

---

model/host/db.go
model/host/host.go
service/api_task.go
service/api_task_test.go

In the previous PR https://github.com/evergreen-ci/evergreen/commit/354f21dd42516d7c884fa371ff439069ea78f556, we exited with a race if the current task was in a single-host task group, was new to the host, and wasn't the first task in the group.
This was evidently too strict and had to be reverted. A less-strict version may be this: store running task order numbers with the host, and exit with a race if the current task is later in the task group than a currently running task. (If the host doesn't have order number cached, we'll revert to the previous format of race detecting).
So in the race condition scenario we currently have: 
Host1 gets/assigns task1
Host2 gets/assigns task2
Host1 checks for race--sees 2 hosts are running tasks but max hosts is 1, so it exits
Host2 checks for …

EVG-7903 improve task group race with cached order numbers

---

scheduler/wrapper.go
scheduler/wrapper_test.go

JIRA: https://jira.mongodb.org/browse/EVG-12404
Currently, if a host is converted from legacy to non-legacy provisioning (or vice versa) but it fails and we want to back out of the conversion by reverting the distro settings, the host status will not change from provisioning back to running. This aims to fix that.

EVG-12404: set host to running if reprovision is aborted

---

model/task_lifecycle.go

The issue that happened on Saturday was with System Failed tasks: it looks like they hit ClearAndResetStrandedTask, which doesn't mark other tasks in the task group as unattainable the way that cleanUpTimedOutTask does, so the task group is unable to restart because the other tasks in the group are still Activated and Unblocked. By marking these dependencies as blocked, we enable restarting the task group.

EVG-12491 block dependencies for system-failed tg

---

model/project_ref.go
operations/host_spawn.go

Jasper closes a command's output streams when the process completes. If we're passing in our std streams we need to prevent Jasper from closing them so we can continue to use them.
I also noticed we were creating a setup command's directories even if `--dry-run` was specified.

EVG-12533 wrap std streams

---

operations/service_web.go

JIRA: https://jira.mongodb.org/browse/EVG-8311
I have no clue what's wrong with the production Slack logger since it looks the same as staging, so I'm adding this one-time sanity log in tomorrow's deploy to see if it will actually just work.

EVG-8311: add sanity debug log to check Slack notifications

---

model/task_lifecycle.go

I think the issue is that UpdateBuildAndVersionStatusForTask is called almost constantly, but I can't figure out why this is happening, so I'm adding more logs.

EVG-7769 add more display task logs

---

model/task_lifecycle.go

Considering UpdateBuildAndVersionStatusForTask is called from MarkEnd whenever a task ends, it shouldn't be necessary to update the status of _every_ display task for the build (doing so caused UpdateDisplayTask to race really frequently with the update).
Also added an additional check to UpdateDisplayTask to verify that the task status hasn't been changed since the display task was cached.

EVG-7769 fix multiple TASK_FINISHED events for display tasks

---

command/results_go_test2json.go
command/results_gotest.go

JIRA: https://jira.mongodb.org/browse/EVG-8159
* Use working directory the same between the two.
* Use globbing in `gotest.parse_json`, which previously did not glob.
* Should we actually document `gotest.parse_json`? It's not in the wiki.

EVG-8159: use same globbing behavior between gotest.parse_files and gotest.parse_json

---

model/task/task.go
trigger/task.go
trigger/task_test.go

This expands on the changes in https://github.com/evergreen-ci/evergreen/commit/23940c688fd955095789ad8b0a7b01ff0dd3d0eb. For the most part it doesn't make sense for tasks to notify for individual execution tasks, except for the "first failure" triggers. For those we alert on execution tasks (as soon as we know we have a failure) but not the display task, with the exception of the "first failure with name" which will run all the checks to see if the name matches

EVG-8082 don't send some notifications for execution tasks

---

model/host/host.go
rest/data/host.go
rest/data/interface.go

https://jira.mongodb.org/browse/EVG-12519
DB query for getting paginated running hosts for the `/hosts` page in the new UI
**Hosts can be filtered by**
- hostID
- distroID
- currentTaskID
- statuses
- startedBy
Hosts can be sorted in ascending and descending order by all column headers (id, distro, status, current task, elapsed, uptime, idle time)

EVG-12519: GetPaginatedRunningHosts DB query

---

config.go
rest/client/rest.go

JIRA: https://jira.mongodb.org/browse/EVG-7800
A lot of the REST client methods assume that the server will return a `gimlet.ErrorResponse` in the body if it has a non-200 response, but a lot of them don't (e.g. if the user fails auth, it doesn't seem to return a `gimlet.ErrorResponse` as JSON). This is supposed to deal with those two cases better by returning the user a (hopefully) more useful message in either case.
* Return the response body text in the error message if it can't be parsed as a `gimlet.ErrorResponse`. Always return the status code in the error if it's non-200.
* Clean up some of the non-200 logic handling.
* Fix some functions not closing the response body.

EVG-8159: include response body in error message from REST client

---

graphql/resolvers.go

I dont think the estimatedStart field was being populated before it would keep defaulting to 0. This should fix it.

EVG-8116 Fix estimatedStart time not being populated

---

cmd/scrambled-eggs/scramble.py

This skips values that are extended json, and also strings that are numeric

EVG-12614 don't sanitize extended json

---

model/project.go
rest/data/interface.go
rest/data/project.go
rest/data/project_test.go
rest/model/build.go
rest/model/task.go
rest/route/project.go
rest/route/service.go

Timelines didn't line up to be able to generate this, but I wrote it in a way that generating it will probably create the same-ish code, and will try to do it again once array handling is done. This route takes a version, retrieves its config, and returns the variants and tasks that a given alias would select for it

EVG-12453 add API to test a project alias

---

config.go
operations/admin.go
operations/http.go
rest/client/request.go
rest/client/rest.go
rest/route/service.go

JIRA: https://jira.mongodb.org/browse/EVG-12603
The CLI authentication relies on the user having a valid refresh token from Okta to auth in with their API key. However, this token expires after 100 days, after which the CLI can return 401 Unauthorized without any additional context. The user can fix this by logging in again, which gets them a new Okta refresh token, so any REST requests made through the CLI suggest the re-login solution.
* Add login suggestion if a CLI request gets 401 Unauthorized.
* Drive-by fix `evergreen admin get-settings` because the request goes to the legacy settings and wouldn't actually give you the real settings.
* I opened [a ticket](https://jira.mongodb.org/browse/EVG-12632) for a problem in which `evergreen admin enable-service`/`disable-service` fetch empty …

EVG-12603: suggest re-logging into the UI if the CLI returns 401 Unauthorized

---

glide.lock
rest/route/aws.go
rest/route/aws_test.go
rest/route/service.go
vendor/github.com/robbiet480/go.sns/.gitignore
vendor/github.com/robbiet480/go.sns/.travis.yml
vendor/github.com/robbiet480/go.sns/LICENSE
vendor/github.com/robbiet480/go.sns/README.md
vendor/github.com/robbiet480/go.sns/example_test.go
vendor/github.com/robbiet480/go.sns/main.go
vendor/github.com/robbiet480/go.sns/sns_test.go

Add a route to listen for SNS notifications.
The fields of the notification are defined [here](https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html)
The [AWS docs](https://docs.aws.amazon.com/sns/latest/dg/sns-verify-signature-of-message.html) suggest verifying the signature included with SNS notifications. I vendored a library to do the heavy lifting.
When you add a subscription to a topic AWS sends an initial subscription confirmation message to the endpoint with a URL to GET to confirm the subscription. No notifications are sent until the subscription is confirmed. (The process of setting up an endpoint to handle HTTP(S) notifications is described [here](https://docs.aws.amazon.com/sns/latest/dg/sns-http-https-endpoint-as-subscriber.html#SendMessageToHttp.prepare) …

EVG-12390 add SNS rest route

---

glide.lock
units/reauthorization_job.go
vendor/github.com/evergreen-ci/gimlet/CODEOWNERS
vendor/github.com/evergreen-ci/gimlet/makefile
vendor/github.com/evergreen-ci/gimlet/okta/okta.go
vendor/github.com/evergreen-ci/gimlet/okta/okta_test.go

JIRA: https://jira.mongodb.org/browse/EVG-12629
If the background reauth job sees that the refresh token is invalid, log out the user to force them to log back in. This fixes a problem where the user may remain logged into the UI but their CLI will not be able to auth because their refresh token expired. The solution to the expired token is to log in again.
Note that because the tokens we get are only valid for 100 days, it means that people's login sessions are also capped at 100 days before they have to log in again.

EVG-12629: log out user if refresh token is expired

---

command/results_gotest_parser.go
command/results_gotest_parser_test.go
command/testdata/gotest/8_simple.log

Sometimes the go test build itself can fail and so we don't run tests, and our parser should catch this and fail the task (failing the command will fail the task).

EVG-7913 error on go test build failures

---

rest/route/host.go
rest/route/host_test.go

JIRA: https://jira.mongodb.org/browse/EVG-8255
* Log out the user so that their login session is invalidated and the background reauth job doesn't attempt to auth the user.

EVG-8255: clear login cache when offboarding users

---

config.go
operations/patch_util.go
operations/patch_util_test.go

The Apple version of git adds a string to the end of git's version string. 
1. Match the addition to the version string (`(Apple Git-128)`) in a non-capture group.
2. Use a non-capture group for the rest of the version number, so there's only one captured group.
At least we're [not alone](https://github.com/chef/chef/issues/6350)

EVG-12681 fix for Apple's git

---

config.go
operations/patch_util.go

Another bug deriving from #3762: the app server expects empty patches to be the empty string, but we put mbox headers on every patch.
Catch the case of empty patches.

EVG-12687 handle empty patches

---

operations/patch_util.go
operations/patch_util_test.go

Fix for dots in Apple's version

EVG-12681 really fix Apple git regexp

---

rest/data/host.go
rest/data/host_test.go
rest/route/aws.go
rest/route/aws_test.go
rest/route/host.go
rest/route/middleware.go
rest/route/service.go

When we get a notification for a spot host about to be terminated enqueue a job to terminate it.
If we get a notification that a host that was already terminated and we didn't know about it enqueue a job to clean up the host.

EVG-12391 terminate spot instances

---

command/archive_tarball_create.go
util/artifacts_tar.go

Hoping this logging will be enough to help us understand why tasks sometimes restart during this command.

EVG-12609 add logging for archive.targz_pack

---

cmd/evergreen/evergreen.go
config.go

This now returns "configuration file \`<bad_file>\` does not exist", instead of continuing on to unhelpful errors.

EVG-9701 give user friendly error for bad config file

---

units/commit_queue.go

Previously, the commit queue added dependencies for the merge task for every task in the project that matched the commit queue alias. Some time ago a git_tag_only task was defined for the commit queue sandbox. Since it matched the alias, it was added as a dependency for the merge task. Subsequently, the dependency includer would remove the merge task from the patch, since it depended on a task that [wasn't able to be included in the patch](https://github.com/evergreen-ci/evergreen/blob/9fd979e10199588f0fe5109aed9f6419f9ddfb2d/model/patch_dependencies.go#L48).
The solution in this PR is to first figure out which tasks should be in the patch by rebuilding the lists of tasks/variants in `updatePatch`. Then the merge task is made to depend on whatever is actually in the patch.

EVG-9703 fix merge-task dependencies

---

cloud/ec2_fleet.go
cloud/ec2_fleet_test.go

If we have no overrides to make (i.e. no AZ supports the instance type) we need to pass a nil overrides slice instead of an empty one because AWS considers an empty overrides slice an invalid request.
Also if the only AZ that supports this instance type is already supplied in the launch template (i.e. only one AZ supports the instance type) we should skip making overrides.

EVG-12684 catch empty overrides

---

rest/model/codegen_test.go

I had investigated this previously and didn't turn up anything, so I'm just adding the skip to this test as well. For whatever reason, having the race detector enabled makes this test unable to resolve packages within our own repo. The code doesn't currently have any concurrency features and I don't plan on using them, so I'm not concerned about skipping the test

EVG-8325 skip codegen tests on race detector

---

model/lifecycle.go
model/lifecycle_test.go
model/patch_lifecycle.go
model/task/task.go
model/task/task_test.go
repotracker/repotracker.go
repotracker/repotracker_test.go
service/task.go
units/patch_intent.go

Because in `createTasksForBuild` we strictly match on alias, we filter out any dependencies that don't match the alias. Some functions that call this already add dependencies to the list of taskNames, but some don't seem to so I added `IncludePatchDependencies`. 
I also snuck in a performance fix for BlockedState, because this individually finds each of the tasks dependencies, but getTaskDependencies already gets all of these in one statement so we can just use that.

EVG-12554 handle aliases before creating tasks

---

cmd/evergreen/evergreen.go
command/git.go
config.go
operations/agent_monitor.go
operations/service_deploy_smoke.go

JIRA: https://jira.mongodb.org/browse/EVG-12720
This fixes two separate problems that broke the smoke tests:
1. Revert e317c728fa2e1ea078368e57bc2c2c5919045e68 (@ablack12) because the CLI requires an evergreen YAML for all commands, which will break commands that don't have an evergreen.yaml (e.g. `evergreen service deploy`).
2. For smoke-test-agent-monitor specifically - do not remove temp file from smoke test command, because the agent monitor needs to be given a path to a file where the agent will be downloaded. If you try removing the file at the same time that the agent monitor is downloading the agent, it'll get "Text file busy" and the agent won't be able to run.

EVG-12720: fix smoke tests

---

cmd/scrambled-eggs/scramble.py
makefile

This adds support for scrambling a newline-delimited list of json, rather than strict json. If the input file is a list, call it like 
`make scramble file=testdata/local/admin.json multi=1`

EVG-12614 support list of json

---

config.go
operations/patch_util.go
operations/patch_util_test.go

The git for Windows' version string was being excluded by the regexp because it includes characters that aren't part of the `\d` character class. Loosen the regexp to catch all word characters (`[A-Za-z0-9_]`). You can try it out [here](https://regex101.com/r/Hn4MMA/1).
Additionally, when we hit this error we should print an error and continue with the patch instead of preventing the patch from being uploaded.

EVG-12746 catch Windows versioning

---

config.go
operations/update.go

JIRA: https://jira.mongodb.org/browse/EVG-12767
The update was removing the temp file before it could be installed in the current binary location. It also closed the same file handle multiple times, which was producing errors.

EVG-12767: fix temp file removal during update

---

service/api_patch.go

We don't check in middleware because the project ID isn't in the request variables/query parameters and [urlVarsToProjectScopes](https://github.com/evergreen-ci/evergreen/blob/7c56f5ebef25da056b60ed558392d4d6d031d858/rest/route/middleware.go#L503) would return a 404.

EVG-12737 add permissions check to submitPatch route

---

config.go
operations/commit_queue.go
operations/patch.go
operations/patch_module.go

Add checks for skipConfirm to more prompts.
I'm open to discussion about individual cases where we haven't been checking it, but I think in general we should honor the user's choice to skip confirmations. I could hear an argument for confirm at least logging the message when we skip confirmation, but I've left it alone for now.
A separate issue I included in this PR was to return an error when the user aborts a patch for uncommitted changes.

EVG-7674 multiple commits

---

config.go
operations/update.go

JIRA: https://jira.mongodb.org/browse/EVG-12767
Close the temp file before we exec it, otherwise it returns "text file busy". This problem seems to be specific to Linux.

EVG-12767: close temp evergreen file before using it

---

model/host/static_hosts.go
model/host/static_hosts_test.go
rest/data/distro.go
scheduler/wrapper.go
service/distros.go

Zakhar thought this host couldn't be terminated due to distro aliases, but really we don't allow termination for non-ephemeral hosts. Distro admins / super users should be able to do this though, given that we need to do this right now.
I originally wrote something to authenticate that the user has distro host edit permissions, but it actually looks like we already do this [here](https://github.com/evergreen-ci/evergreen/blob/05466742638f662831fcf70b959b12dcdd99e3d0/public/static/js/host.js#L7) and [here](https://github.com/evergreen-ci/evergreen/blob/55ea271af62f265d44b624f7204e59438fcef1fe/service/ui.go#L340) so I think this check is overall unnecessary.

EVG-9767 allow termination of non-ephemeral hosts

---

command/git.go
command/git_push.go
command/git_push_test.go
command/git_test.go
units/commit_queue.go

Old versions of git (<2.1.2) don't support the -c option. Instead, set the config on the repo (--local) level when we clone the repo.
I considered just setting it in the case where we need it (when we run `git am`) but it seems like a good idea to set it in every case since git sometimes refuses to do random things when it's not set.
Also removed the committer_name and committer_email parameters from the git.push command where they are no longer used (post the transition to mbox).

EVG-12779 set local git config

---

command/git.go
command/git_push.go
command/git_push_test.go
command/git_test.go
command/testdata/git/test_mbox.patch
config.go
units/commit_queue.go

The changes in #3887 were reverted because the --local option also isn't supported on old versions of git.
Instead, pass the committer information as [environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#_committing). I _tested_ that this method is supported.

EVG-12779 remove git -c option

---

model/task/task.go
model/task/task_test.go
scheduler/scheduler.go

We're supposed to deactivate and disable underwater tasks (i.e. tasks that have been activated and not run for ~a week). The task finders and [UnscheduleStaleUnderwaterTasks](https://github.com/evergreen-ci/evergreen/blob/582e882a8e2d35e66d7f9ac1bc23c838b9546840/model/task/task.go#L806) both use the [same query](https://github.com/evergreen-ci/evergreen/blob/582e882a8e2d35e66d7f9ac1bc23c838b9546840/model/task/db.go#L523) to find tasks that are ready to run, but the task finders also [include any distro in the set of distro aliases](https://github.com/evergreen-ci/evergreen/blob/582e882a8e2d35e66d7f9ac1bc23c838b9546840/model/task/task.go#L1818), while UnscheduleStaleUnderwaterTasks only looks for the distro itself. This PR makes UnscheduleStaleUnderwaterTasks also look for tasks in any of …

EVG-12712 match underwater query with task finder

---

service/project.go

I was updating projectRef.TracksPushEvent, which then gets overridden by responseRef.TracksPushEvents. Rather than just update responseRef every time hook != nil though, I think it's safer to just update with hook != nil directly.

EVG-12696 correctly update repotracking when modifying project

---

model/generate_test.go
model/lifecycle.go
model/task/task.go
model/task/task_test.go

The existing solution wasn't deduplicating the dependencies because as we iterate over the `map[string]displayTaskInfo` we modify a copy of the displayTaskInfo without saving it back into the map. The display task itself has dependencies added because the displayTaskInfo stores a _pointer_ to the task.
I found the pointer logic misleading, so I reordered the function to create execution tasks first. This way we can set the dependencies on the display task without keeping a pointer to it.

EVG-8282 deduplicate display task dependencies

---

model/lifecycle.go
model/task/db.go

While generate.tasks does activate tasks that it creates, it seems that when a task already exists it skips it. My theory is that this doesn't normally cause a problem since most of the version will be activated already, but in the case that existing dependencies _haven't_ been activated, this doesn't activate them. (This is assuming that dependencies have been added by IncludeDependencies and not somewhere later.)

EVG-8327 activate tasks that already exist in generate.tasks

---

config.go
operations/flags.go
operations/model.go
operations/patch.go
operations/patch_module.go
operations/patch_util.go

An alternative to #3909: Allow users to continue using diffToMbox, but only if they opt-in.
This has an advantage that users will have the option to package multiple commits in one commit when it's enqueued (without squashing themselves).

EVG-12825 put diffToMbox behind a flag

---

cloud/ec2.go
cloud/ec2_price.go
cloud/ec2_util.go
units/host_termination.go

It's probably personal preference where/when to suppress these errors. I've suppressed the functions that are used in places that aren't strictly related to cost (the most important of which is `getProvider`, which is used to spawn hosts). I've also added another region check for the ec2Manager, but I didn't with ec2Fleet since these won't be in other regions.

EVG-12642 suppress non-crucial price fetcher errors

---

agent/command.go
config.go

I originally took this ticket with the intent of adding a display name to commands (didn't know that it already exists) and to improve command logging in general. The only change here is to move the end of command log line from the agent to task log

EVG-7976 move log message to task logs

---

model/project_ref.go

This is not a fix to the problem in the ticket, but something I noticed while investigating. I believe it's only possible to hit this when duplicating a project with the API, but the result is that the new project will not be added to the scope for "all projects," though it should

EVG-12784 better maintain list of all projects when creating new

---

makefile

JIRA: https://jira.mongodb.org/browse/EVG-12873
This is going to generate a bunch of lint errors once it's merged.

EVG-12873: use latest version of golangci-lint

---

.golangci.yml
api/host.go
cmd/generate-lint/generate-lint.go
graphql/resolvers.go
model/task_lifecycle.go
rest/model/codegen.go
rest/model/conversions.go
rest/model/host.go
util/expand_params.go

JIRA: https://jira.mongodb.org/browse/EVG-12873
* Fix generate-lint, which did not run `make get-go-imports`, which is required for Evergreen to compile.
* Fix all package linting issues.

EVG-12873: fix lint issues

---

config.go
operations/flags.go
operations/model.go
operations/patch.go
operations/patch_module.go
operations/patch_util.go

#3910 stopped most patches from being wrapped in patch format until [SERVER-50401](https://jira.mongodb.org/browse/SERVER-50401) could be implemented. Now that it has, revert those changes.
Still keep the PreserveCommits configuration option added there, since that still seems useful.

EVG-12826 store patches in mbox format

---

agent/agent.go
agent/task.go
config.go

Containers don't have write access to dmesg (needed to clear the log before we start running the task).
Detecting an OOM kill is also not meaningful in the context of containers since it could have been the result of another task.

EVG-12537 disable oom tracker for containers

---

model/task_lifecycle.go

I wasn't able to figure out the cause, so the approach here is to add more redundancy when computing dependencies. Now in end task, we will reset the unattainable state of dependent tasks to what they should be. In the scenarios that I'm aware of, the line I added should not actually do anything, but the hope is that whatever scenario is causing this ticket will be fixed by this.
Note that not all code paths to put a task in a finalized status goes through here - notably our stranded task jobs. For those, they should already be resetting the dependencies as well as the task, so it presumably will run again to completion and hit this path

EVG-12788 re-evaluate dependencies on end task

---

auth/auth.go
config_auth.go
config_db.go
rest/model/admin.go
service/templates/admin.html

Missed a couple things in the last pr
- add a read-only only-api auth manager if allowing service users
- add a checkbox to admin settings to toggle this

EVG-12676 add missing service user pieces

---

graphql/resolvers.go
graphql/ui_plugin_build_baron.go
model/task/db.go
model/task/task.go
model/task/task_test.go
model/version.go
service/build.go
service/task.go

Version/build makespans are the time from the beginning of the first task execution to the end of the last. If a task is restarted long after the version has finished running the makespan is an inordinately long time. Since what users really want to know from the makespan is how long the version took to run, this is not helpful.
This PR uses tasks' first execution to determine the makespan.

EVG-8310 makespan for first execution only

---

model/task_lifecycle.go

We correctly identified that when a version has only finished + blocked tasks, we should set the build as finished, but we set updates.BuildComplete instead of BuildComplete. I looked at the history and I believe it's an oversight that we have two variables to convey this, so I consolidated.

EVG-12418 update when the build is complete correctly

---

public/static/js/patch_new.js

BuildVariants were changed to use a different struct for display tasks (#3954) but the old UI is still referencing a field from the old struct.

ExecutionTasks -> ExecTasks

---

graphql/resolvers.go
model/version.go

The changes in #3955 are only evident in builds. Patch/Version makespans are still taking later executions into account.
The issue is the projection which excluded execution numbers...

EVG-8310 add execution number to projections

---

globals.go
model/host/db.go
model/host/host.go
model/host/host_test.go
model/host/hostutil.go
model/host/hostutil_test.go
service/api_task.go
service/api_task_test.go
units/host_status.go
units/host_status_test.go
units/host_termination_test.go
units/provisioning_setup_host.go
units/provisioning_user_data_done.go
units/provisioning_user_data_done_test.go

All we were doing for userdata hosts in provisioning-setup-host was to call the host's OnUp function and set the DNS name. Relocating these steps to the cloud-host-ready job allows us to skip the provisioning state for userdata hosts, so:
- there's one less job per host (we don't need to run the provisioning-setup-host job anymore)
- the exceptions for allowing userdata hosts to run tasks are simpler

EVG-12393 eliminate provisioning state for userdata hosts

---

agent/agent.go
agent/task.go
config.go
model/patch_lifecycle_test.go
model/project_test.go
model/task_config.go
model/version_db.go
service/api.go
units/patch_intent.go
util/expansion.go

Parameter hierarchy is as follows (lowest to highest priority):
1) Existing expansions
2) Project variables
3) Project parameters
4) Version parameters (in the future, this should include parameters added by UI, CLI, and user project defaults).
Made a change from my last PR to not add project parameters to the version/patch document (if we need to know what the defaults were, we can look up the project used for the version).
This is confirmed to work for project parameters, [here](https://evergreen-staging.corp.mongodb.com/task/yb_mci_ubuntu1604_unit_tests_patch_e04c03bebce04359961eb0074fa46541d8b3c38e_5f5a913ab237364777ce927e_20_09_10_20_50_08) with "hello world!" being the parameter defined in the committed project, and [here](https://evergreen-staging.corp.mongodb.com/task/yb_mci_ubuntu …

EVG-12875 add parameters as expansions

---

model/host/db.go
model/host/host_test.go

#3970 has the cloud-host-ready job set user data hosts as `provisioned: true` and `status: starting` once we find out the host is running. Hosts in this state need to be excluded from the query the cloud-host-ready job uses to find hosts to check.

EVG-12393 remove provisioned user data hosts from cloud-host-ready job

---

service/api_plugin_manifest.go
thirdparty/api_models.go
thirdparty/github.go
thirdparty/github_test.go

When the app server returns a 500 error for the `load.manifest` command the command will retry ten times. When the error is caused by a misconfigured module we should recognize it and return an error to the agent that will tell it not to retry. This will 1) give faster feedback on the error and 2) avoid consuming our allotment of GitHub API calls.

EVG-8206 manifest retries

---

cmd/run-linter/run-linter.go

JIRA: https://jira.mongodb.org/browse/EVG-12937
run-linter has always been set in the evergreen repo only to have half the concurrency that it's supposed to have for no reason. I updated run-linter so it matches the ones in all the PLT repos and uses the default concurrency (i.e. `runtime.NumCPU`).

EVG-12937: fix run-linter concurrency

---

units/crons.go
units/provisioning_jasper_restart.go

JIRA: https://jira.mongodb.org/browse/EVG-12961
Currently, the job to restart Jasper on a host won't be enqueued if it can't get the host's credentials from the database (e.g. the credentials may have been deleted when the Jasper restart job used up all of its retries without successfully restarting Jasper). This makes it so that if the credentials can't be found, it'll assume the host isn't running Jasper right now and will restart Jasper using just SSH.

EVG-12961: handle restarting Jasper service even if credentials expiration is unknown

---

makefile

JIRA: https://jira.mongodb.org/browse/EVG-12937
The linter is quite slow on the first task that runs in a task group (usually it's lint-api or lint-agent), likely because golangci-lint hasn't cached anything yet. Passing an increased timeout to handle the first slow task in the task group should fix the intermittent lint failures.

EVG-12937: increase linter timeout

---

repotracker/repotracker.go

Considering yaml format errors get a stub version, parser errors should too.
I also think the error should be a little bit more informative, but this _might_ be noisy for parser errors so I can remove that change if preferred.

EVG-13032 include parser errors in repotracker exceptions

---

graphql/util.go
model/dependencies.go
model/generate.go
model/patch_lifecycle_test.go
model/project.go
repotracker/repotracker.go
units/generate_tasks_test.go

- have the dependency includer be able to return errors. This ended up being a bit unnecessary since the callers will all just log the error, but oh well
- when expanding a single task's dependencies, have any scenarios where you specify * to mean "all tasks that would be able to run for this version" rather than "all valid tasks for this variant." This is the same check that we would do later for the main task. This allows * to be more intelligent when pulling in dependencies, because it won't pull in ones that wouldn't be able to run anyway

EVG-12967 better handle ambiguous dependencies with * selector

---

agent/agent.go
cloud/ec2.go
globals.go
model/event/host_event.go
model/host/host.go
operations/agent_monitor.go
public/static/partials/hostevent.html
service/templates/distros.html
units/provisioning_create_host.go

Example of a host that was configured to fallback: https://evergreen-staging.corp.mongodb.com/host/i-0cd48c0a2350cc643 (verified in AWS that the lifecycle was normal and not spot).
The event log can be modified if that wording is clunky, but I think it'll be nice to have something.
Distro page change:

EVG-13049 allow ec2-spot/fleet to fallback to on-demand

---

agent/agent.go
agent/logging.go
apimodels/agent_models.go
command/s3_copy.go
command/s3_put.go
command/s3_util.go
config.go
config_cloud.go
model/project_parser_test.go
rest/model/admin.go
rest/model/admin_test.go
self-tests.yml
service/api_status.go
service/templates/admin.html
testutil/config.go
util/s3.go

JIRA: https://jira.mongodb.org/browse/EVG-9080
* The agent will use path-style URLs if the bucket has a dot; otherwise, it'll default to virtual hosted-style URLs.
* Warn for dotted buckets because dotted buckets created after Sept. 30 will not have valid URL attachments for `s3.put` and `s3.copy`. Dotted buckets are still okay if the bucket is created before Sept. 30, but since we don't know when a bucket was created, we have to warn even if the dotted bucket was created before Sept 30.
* Remove S3BaseURL from admin settings.

EVG-9080: handle path-style and virtual hosted-style S3 URLs
